### ISSUE TITLE
Jetson推理PP_PicoDet_V2_S_Pedestrian_192x192_infer时出错

### ISSUE THREAD

**Issue by liutingxi** [PaddlePaddle/FastDeploy#1004]
## 环境

- 【编译命令】遵循 https://github.com/PaddlePaddle/FastDeploy/blob/develop/docs/cn/build_and_install/jetson.md， 去掉了Paddle Inference
- 【系统平台】: Linux x64(Ubuntu 18.04)
- 【硬件】： Nvidia Jetson Xavier NX
- 【编译语言】： C++ / Python(3.6）

## 问题日志及出现问题的操作流程
基于https://github.com/PaddlePaddle/FastDeploy/tree/develop/examples/vision/keypointdetection/det_keypoint_unite 中提供的python demo，成功运行了PP_PicoDet_V2_S_Pedestrian_320x320_infer+PP_TinyPose_256x192_infer，但切换为PP_PicoDet_V2_S_Pedestrian_192x192_infer+PP_TinyPose_128x96_infer时出错

注：已将
https://github.com/PaddlePaddle/FastDeploy/tree/develop/examples/vision/keypointdetection/det_keypoint_unite#L39
https://github.com/PaddlePaddle/FastDeploy/tree/develop/examples/vision/keypointdetection/det_keypoint_unite#L55
两处的size分别修改为1, 3, 192, 192和1, 3, 128, 96

尝试了C++版本，遇到了同样的core

下附日志：

- python版本

[INFO] fastdeploy/backends/tensorrt/trt_backend.cc(500)::BuildTrtEngine Start to building TensorRT Engine...
[INFO] fastdeploy/backends/tensorrt/trt_backend.cc(586)::BuildTrtEngine TensorRT Engine is built successfully.
[INFO] fastdeploy/backends/tensorrt/trt_backend.cc(588)::BuildTrtEngine Serialize TensorRTEngine to local file picodet_lite.trt.
[INFO] fastdeploy/backends/tensorrt/trt_backend.cc(598)::BuildTrtEngine TensorRTEngine is serialized to local file picodet_lite.trt, we can load this model from the seralized engine directly next time.
[INFO] fastdeploy/runtime.cc(585)::Init Runtime initialized with Backend::TRT in Device::GPU.
[INFO] fastdeploy/backends/tensorrt/trt_backend.cc(500)::BuildTrtEngine Start to building TensorRT Engine...

[INFO] fastdeploy/backends/tensorrt/trt_backend.cc(586)::BuildTrtEngine TensorRT Engine is built successfully.
[INFO] fastdeploy/backends/tensorrt/trt_backend.cc(588)::BuildTrtEngine Serialize TensorRTEngine to local file tinypose_lite.trt.
[INFO] fastdeploy/backends/tensorrt/trt_backend.cc(598)::BuildTrtEngine TensorRTEngine is serialized to local file tinypose_lite.trt, we can load this model from the seralized engine directly next time.
[INFO] fastdeploy/runtime.cc(585)::Init Runtime initialized with Backend::TRT in Device::GPU.
Load video /home/nvidia/revai/sit_up/test_1.mp4
[ERROR] fastdeploy/backends/tensorrt/trt_backend.cc(345)::Infer [ERROR] Error occurs while copy memory from GPU to CPU.
Aborted (core dumped)

- C++版本
[INFO] fastdeploy/backends/tensorrt/trt_backend.cc(500)::BuildTrtEngine Start to building TensorRT Engine...
[INFO] fastdeploy/backends/tensorrt/trt_backend.cc(586)::BuildTrtEngine TensorRT Engine is built successfully.
[INFO] fastdeploy/backends/tensorrt/trt_backend.cc(588)::BuildTrtEngine Serialize TensorRTEngine to local file ./picodet_lite.trt.
[INFO] fastdeploy/backends/tensorrt/trt_backend.cc(598)::BuildTrtEngine TensorRTEngine is serialized to local file ./picodet_lite.trt, we can load this model from the seralized engine directly next time.
[INFO] fastdeploy/runtime.cc(585)::Init Runtime initialized with Backend::TRT in Device::GPU.
[INFO] fastdeploy/backends/tensorrt/trt_backend.cc(500)::BuildTrtEngine Start to building TensorRT Engine...
[INFO] fastdeploy/backends/tensorrt/trt_backend.cc(586)::BuildTrtEngine TensorRT Engine is built successfully.
[INFO] fastdeploy/backends/tensorrt/trt_backend.cc(588)::BuildTrtEngine Serialize TensorRTEngine to local file ./tinypose_lite.trt.
[INFO] fastdeploy/backends/tensorrt/trt_backend.cc(598)::BuildTrtEngine TensorRTEngine is serialized to local file ./tinypose_lite.trt, we can load this model from the seralized engine directly next time.
[INFO] fastdeploy/runtime.cc(585)::Init Runtime initialized with Backend::TRT in Device::GPU.
Load video
[ERROR] fastdeploy/backends/tensorrt/trt_backend.cc(345)::Infer [ERROR] Error occurs while copy memory from GPU to CPU.
Aborted (core dumped)

**Comment by felixhjh** [comment]
您好，经过测试，的确在jetson设备上会出现 PP_PicoDet_V2_S_Pedestrian_192x192_infer 使用tensorrt部署失败的问题，这边暂时还在定位bug修改，以下给出临时解决方案，推荐使用Paddle-TRT
编译可参考文档，下载相应的 Paddle Inference Jetpack预编译库
https://github.com/PaddlePaddle/FastDeploy/blob/release/1.0.2/docs/cn/build_and_install/jetson.md
编译安装完成后，在下面example示例上 https://github.com/PaddlePaddle/FastDeploy/blob/release/1.0.2/examples/vision/keypointdetection/det_keypoint_unite/python/det_keypoint_unite_infer.py#L55 增加
option.enable_paddle_to_trt()

**Comment by jiangjiajun** [comment]
此ISSUE由于一年未更新，将会关闭处理，如有需要，可再次更新打开。
