### ISSUE TITLE
RKNUP(Python方式)部署中遇到问题:AssertionError: PicoDet model initialize failed.

### ISSUE THREAD

**Issue by MrMzl** [PaddlePaddle/FastDeploy#1008]
## 环境

- 【FastDeploy版本】： fastdeploy-python      1.0.0 
- 【系统平台】: Linux firefly 4.19.219   aarch64 GNU/Linux   (Ubuntu20.04.3)
- 【硬件】： AIO-3568J开发板
- 【编译语言】： Python(3.8.10）

## 问题日志及出现问题的操作流程
- 运行/FastDeploy/examples/vision/detection/paddledetection/rknpu2/python目录下面的infer脚本文件提示下面错误:
- 执行命令:
python3 infer.py --model_file ./picodet_s_416_coco_lcnet/picodet_s_416_lcnet_rk3568.rknn --config_file ./picodet_s_416_coco_lcnet/infer_cfg.yml --image 000000014439.jpg                             
-  错误提示:                      
- - [INFO] fastdeploy/vision/common/processors/transform.cc(159)::FuseNormalizeColorConvert BGR2RGB and Normalize are fused to Normalize with swap_rb=1
[ERROR] fastdeploy/fastdeploy_model.cc(200)::CreateRKNPUBackend Cannot find an available npu backend to load this model.
[ERROR] fastdeploy/vision/detection/ppdet/base.cc(23)::Initialize       Failed to initialize fastdeploy backend.
Traceback (most recent call last):
  File "infer.py", line 42, in <module>
    model = fd.vision.detection.PicoDet(
  File "/home/firefly/.local/lib/python3.8/site-packages/fastdeploy/vision/detection/ppdet/__init__.py", line 189, in __init__
    assert self.initialized, "PicoDet model initialize failed."
AssertionError: PicoDet model initialize failed.
-  备注1:picodet_s_416_coco_lcnet文件夹中的模型文件在c++方式部署时能够成功运行
![image](https://user-images.githubusercontent.com/85120075/209896548-39b61ca7-2f74-49b5-b3d4-897a0558185f.png)

**Comment by Zheng-Bicheng** [comment]
感谢您的反馈，我复现一下

**Comment by Zheng-Bicheng** [comment]
您再重新测试一下develop版本的fastdeploy。我在develop版本中没发现这个问题，可能已经修复

**Comment by Zheng-Bicheng** [comment]
解决了吗

**Comment by MrMzl** [comment]
> 解决了吗

您好，郑工，最近在测试其他东西，这个问题过两天测试了回复您。

**Comment by Zheng-Bicheng** [comment]
Picodet的问题解决了吗

**Comment by MrMzl** [comment]
> Picodet的问题解决了吗

目前在fastdeploy-release-1.0.0上重新测试后能够正常推理部署，只是执行运行代码后（python/c++）会有一行提示：E RKNN: [07:43:46.025] rknn_set_core_mask: No implementation found for current platform!详细日志见链接：https://pan.baidu.com/s/1VT2K4qjIa7co1tVqDduvFA 提取码: t5xh ,郑工您那边有时间可以帮忙看看，感谢指导。

**Comment by Zheng-Bicheng** [comment]
> > Picodet的问题解决了吗
> 
> 目前在fastdeploy-release-1.0.0上重新测试后能够正常推理部署，只是执行运行代码后（python/c++）会有一行提示：E RKNN: [07:43:46.025] rknn_set_core_mask: No implementation found for current platform!详细日志见链接：https://pan.baidu.com/s/1VT2K4qjIa7co1tVqDduvFA 提取码: t5xh ,郑工您那边有时间可以帮忙看看，感谢指导。

这个是正常现象，后续会进行修复，不影响推理
