### ISSUE TITLE
fastdeploy-linux-aarch64-1.0.1.tgz  无法下载

### ISSUE THREAD

**Issue by snowperson01** [PaddlePaddle/FastDeploy#1014]
git上[fastdeploy-linux-aarch64-1.0.1.tgz](https://bj.bcebos.com/fastdeploy/release/cpp/fastdeploy-linux-aarch64-1.0.1.tgz) 该地址无法下载。 

{"code":"NoSuchKey","message":"The specified key does not exist.","requestId":"a48d716a-93e9-4987-99df-34a0af8c49d2"}

**Comment by jiangjiajun** [comment]
麻烦先下载1.0.0版本，1.0.1刚验证确实无法下载

**Comment by jiangjiajun** [comment]
此ISSUE由于一年未更新，将会关闭处理，如有需要，可再次更新打开。
