### ISSUE TITLE
请问框架最后的识别结果得自己去解析吗？没有啥一键转list之类的功能吗？

### ISSUE THREAD

**Issue by lilianjie111111** [PaddlePaddle/FastDeploy#1016]
![image](https://user-images.githubusercontent.com/102579571/209941595-66c5d0f5-520f-4a78-ad2d-9acb79fb07df.png)

**Comment by jiangjiajun** [comment]
这是一个结构体，自行查阅API定义即可 https://baidu-paddle.github.io/fastdeploy-api/

**Comment by jiangjiajun** [comment]
此ISSUE由于一年未更新，将会关闭处理，如有需要，可再次更新打开。
