### ISSUE TITLE
OSError: (External) CUDNN error(14), CUDNN_STATUS_VERSION_MISMATCH.

### ISSUE THREAD

**Issue by yutao007** [PaddlePaddle/FastDeploy#1020]
## 环境

- 【FastDeploy版本】： fastdeploy-gpu-python         1.0.1
fastdeploy-tools              0.0.1
addle-bfloat                 0.1.7
paddlepaddle                  2.4.1
paddlepaddle-gpu              2.4.1
paddleslim                    2.4.0
pandas                        1.3.2
pandocfilters                 1.4.3
parl                          2.1.1
parso                         0.8.2
torch                         1.5.0
torchvision                   0.6.0
tornado                       6.1
- 【编译命令】fastdeploy compress --config_path=/media/extend/FastDeploy/tools/common_tools/auto_compression/configs/detection/yolov5s_quant.yaml  --method='QAT' --save_dir='./yolov5s_qat_model/'
- 【系统平台】: Linux x64(Ubuntu 20.04) 
- 【硬件】： 说明具体硬件型号，如 Nvidia GPU 1050TI， cuda_11.2.0_460.27.04_linux   cudnn-11.3-linux-x64-v8.2.0.53
- 【编译语言】： Python3.7.6

uantize': False, 'onnx_format': True, 'quant_post_first': False, 'scale_trainable': True, 'name': 'Distillation', 'loss': 'soft_label', 'node': [], 'alpha': 1.0, 'teacher_model_dir': './yolov5s.onnx', 'teacher_model_filename': 'model.pdmodel', 'teacher_params_filename': 'model.pdiparams'}
Adding quant op with weight:|████████████████████████████████████████| 1360/1360
Adding OutScale op:|███████████████████████████████████████████████████| 929/929
2022-12-30 14:06:05,808-INFO: When a preprocess_func is used in quant_aware, Need to save a mapping table to match variable names in the convert phase.
2022-12-30 14:06:05,808-INFO: The mapping table is saved as './mapping_table_for_saving_inference_model'.
Traceback (most recent call last):
  File "/media/extend/anaconda3/bin/fastdeploy", line 8, in <module>
    sys.exit(main())
  File "/media/extend/anaconda3/lib/python3.7/site-packages/common_tools/common_tools.py", line 81, in main
    auto_compress(args)
  File "/media/extend/anaconda3/lib/python3.7/site-packages/common_tools/auto_compression/fd_auto_compress/fd_auto_compress.py", line 127, in auto_compress
    ac.compress()
  File "/media/extend/anaconda3/lib/python3.7/site-packages/paddleslim/auto_compression/compressor.py", line 594, in compress
    train_config)
  File "/media/extend/anaconda3/lib/python3.7/site-packages/paddleslim/auto_compression/compressor.py", line 776, in single_strategy_compress
    train_program_info, test_program_info, strategy, train_config)
  File "/media/extend/anaconda3/lib/python3.7/site-packages/paddleslim/auto_compression/compressor.py", line 792, in _start_train
    fetch_list=train_program_info.fetch_targets)
  File "/media/extend/anaconda3/lib/python3.7/site-packages/paddle/fluid/executor.py", line 1463, in run
    six.reraise(*sys.exc_info())
  File "/media/extend/anaconda3/lib/python3.7/site-packages/six.py", line 719, in reraise
    raise value
  File "/media/extend/anaconda3/lib/python3.7/site-packages/paddle/fluid/executor.py", line 1459, in run
    return_merged=return_merged)
  File "/media/extend/anaconda3/lib/python3.7/site-packages/paddle/fluid/executor.py", line 1726, in _run_impl
    return_merged=return_merged)
  File "/media/extend/anaconda3/lib/python3.7/site-packages/paddle/fluid/executor.py", line 1254, in _run_parallel
    tensors = exe.run(fetch_var_names, return_merged)._move_to_list()
OSError: (External) CUDNN error(14), CUDNN_STATUS_VERSION_MISMATCH. 
  [Hint: Please search for the error code(14) on website (https://docs.nvidia.com/deeplearning/cudnn/api/index.html#cudnnStatus_t) to get Nvidia's official solution and advice about CUDNN Error.] (at /paddle/paddle/phi/kernels/gpudnn/pool_grad_kernel.cu:284)
  [operator < pool2d_grad > error

尝试换过cudnn-11.2-linux-x64-v8.1.1.33，仍然不能执行，并且报错找不到cudnn

**Comment by yunyaoXYY** [comment]
> ## 环境
> * 【FastDeploy版本】： fastdeploy-gpu-python         1.0.1
>   fastdeploy-tools              0.0.1
>   addle-bfloat                 0.1.7
>   paddlepaddle                  2.4.1
>   paddlepaddle-gpu              2.4.1
>   paddleslim                    2.4.0
>   pandas                        1.3.2
>   pandocfilters                 1.4.3
>   parl                          2.1.1
>   parso                         0.8.2
>   torch                         1.5.0
>   torchvision                   0.6.0
>   tornado                       6.1
> * 【编译命令】fastdeploy compress --config_path=/media/extend/FastDeploy/tools/common_tools/auto_compression/configs/detection/yolov5s_quant.yaml  --method='QAT' --save_dir='./yolov5s_qat_model/'
> * 【系统平台】: Linux x64(Ubuntu 20.04)
> * 【硬件】： 说明具体硬件型号，如 Nvidia GPU 1050TI， cuda_11.2.0_460.27.04_linux   cudnn-11.3-linux-x64-v8.2.0.53
> * 【编译语言】： Python3.7.6
> 
> uantize': False, 'onnx_format': True, 'quant_post_first': False, 'scale_trainable': True, 'name': 'Distillation', 'loss': 'soft_label', 'node': [], 'alpha': 1.0, 'teacher_model_dir': './yolov5s.onnx', 'teacher_model_filename': 'model.pdmodel', 'teacher_params_filename': 'model.pdiparams'} Adding quant op with weight:|████████████████████████████████████████| 1360/1360 Adding OutScale op:|███████████████████████████████████████████████████| 929/929 2022-12-30 14:06:05,808-INFO: When a preprocess_func is used in quant_aware, Need to save a mapping table to match variable names in the convert phase. 2022-12-30 14:06:05,808-INFO: The mapping table is saved as './mapping_table_for_saving_inference_model'. Traceback (most recent call last): File "/media/extend/anaconda3/bin/fastdeploy", line 8, in sys.exit(main()) File "/media/extend/anaconda3/lib/python3.7/site-packages/common_tools/common_tools.py", line 81, in main auto_compress(args) File "/media/extend/anaconda3/lib/python3.7/site-packages/common_tools/auto_compression/fd_auto_compress/fd_auto_compress.py", line 127, in auto_compress ac.compress() File "/media/extend/anaconda3/lib/python3.7/site-packages/paddleslim/auto_compression/compressor.py", line 594, in compress train_config) File "/media/extend/anaconda3/lib/python3.7/site-packages/paddleslim/auto_compression/compressor.py", line 776, in single_strategy_compress train_program_info, test_program_info, strategy, train_config) File "/media/extend/anaconda3/lib/python3.7/site-packages/paddleslim/auto_compression/compressor.py", line 792, in _start_train fetch_list=train_program_info.fetch_targets) File "/media/extend/anaconda3/lib/python3.7/site-packages/paddle/fluid/executor.py", line 1463, in run six.reraise(*sys.exc_info()) File "/media/extend/anaconda3/lib/python3.7/site-packages/six.py", line 719, in reraise raise value File "/media/extend/anaconda3/lib/python3.7/site-packages/paddle/fluid/executor.py", line 1459, in run return_merged=return_merged) File "/media/extend/anaconda3/lib/python3.7/site-packages/paddle/fluid/executor.py", line 1726, in _run_impl return_merged=return_merged) File "/media/extend/anaconda3/lib/python3.7/site-packages/paddle/fluid/executor.py", line 1254, in _run_parallel tensors = exe.run(fetch_var_names, return_merged)._move_to_list() OSError: (External) CUDNN error(14), CUDNN_STATUS_VERSION_MISMATCH. [Hint: Please search for the error code(14) on website (https://docs.nvidia.com/deeplearning/cudnn/api/index.html#cudnnStatus_t) to get Nvidia's official solution and advice about CUDNN Error.] (at /paddle/paddle/phi/kernels/gpudnn/pool_grad_kernel.cu:284) [operator < pool2d_grad > error
> 
> 尝试换过cudnn-11.2-linux-x64-v8.1.1.33，仍然不能执行，并且报错找不到cudnn

Hi你好，
我看到log里，所提示的内容可能还是和环境相关呢，可能还是cudnn的版本有问题，
可以做一些如下的尝试:
1).看到你Paddle用的是2.4.1版本，试一试同时把PaddleSlim升级到2.4.1，对齐了试试 
2).压缩过程中监控一下GPU的显存, 看看是否是因为显存不够造成的
3).再排查一下自己的软件环境问题，如果排查不到的话，可以使用paddle官方提供的docker再来试试.

**Comment by yutao007** [comment]
大神，能够有一个paddle家族的知识图谱吗？paddlepaddle   paddleslim    paddle lite     FastDeploy     x2paddle   等等家族软件

**Comment by yutao007** [comment]
谁依赖谁，谁又是干什么的

**Comment by yutao007** [comment]
我将PaddleSlim升级到2.4.1了，监控到gpu显存没有满，那只能是环境问题了。我按照官方提供的环境conda配置的。不知道别人是否出现跟我类似的问题。

**Comment by yunyaoXYY** [comment]
> 谁依赖谁，谁又是干什么的

这个可以看看 全景图 https://www.paddlepaddle.org.cn/overview

**Comment by yutao007** [comment]
暂时我放弃qat了，至少ptq有用。我开始探索下一步官方例子部署到1126上

**Comment by yunyaoXYY** [comment]
> 我将PaddleSlim升级到2.4.1了，监控到gpu显存没有满，那只能是环境问题了。我按照官方提供的环境conda配置的。不知道别人是否出现跟我类似的问题。

1.可以新建一个conda环境， 然后，只安装fastdeploy, 安装paddle，和安装paddleslim, 再尝试一下. 
2.可以尝试一下飞桨官方的docker，排除环境问题

**Comment by yutao007** [comment]
谢谢，我现在使用官方yolov5.onnx例子ptq压缩后看是否在rk1126上部署成功吧。主线有问题，那细枝末节就不讨论了。

**Comment by yutao007** [comment]
你们东西很宏大，感觉很刁。但是如果为了降低以前的部署难度，增加新的学习难度，那确实没必要啃这个框架了。

**Comment by yunyaoXYY** [comment]
> 谢谢，我现在使用官方yolov5.onnx例子ptq压缩后看是否在rk1126上部署成功吧。主线有问题，那细枝末节就不讨论了。

好的，欢迎先把全流程打通

**Comment by jiangjiajun** [comment]
此ISSUE由于一年未更新，将会关闭处理，如有需要，可再次更新打开。
