### ISSUE TITLE
text的示例无法兼容windows平台运行

### ISSUE THREAD

**Issue by huangwm999** [PaddlePaddle/FastDeploy#1024]
*********************************************
温馨提示：根据社区不完全统计，按照模板提问，可以加快回复和解决问题的速度
*********************************************

## 环境

- 【FastDeploy版本】： fastdeploy-win-x64-1.0.1
- 【编译命令】
- 【系统平台】: Windows x64(Windows10)
- 【硬件】： 普通CPU环境
- 【编译语言】： C++ 

## 问题日志及出现问题的操作流程
- text目录下的示例无法兼容windows平台运行
- 【模型跑不通】
- - 示例 ernie-3.0，uie 在windows复现均有问题
- - 出现运行循环卡顿，或异常退出

- 【问题分析】
- - 目前定位问题为Visual Studio 定义字符串为ANSI格式，而非Utf8字符串
- - 但是预测模型的输入，默认为utf8字符串
- - NLP底层引擎 core_tokenizers，fastdeploy 有字符串预处理部分，导致ANSI字符串进入后死循环

- 【解决方法】
定义函数
```C++
#include <windows.h>
std::string Uni2UTF8StrS(wchar_t *src) {
#if 1
  int nLen = WideCharToMultiByte(CP_UTF8, 0, src, -1, NULL, 0, NULL, NULL);
  if (nLen <= 0)
    return std::string("");
  char *pszDst = new char[nLen];
  if (NULL == pszDst)
    return std::string("");
  WideCharToMultiByte(CP_UTF8, 0, src, -1, pszDst, nLen, NULL, NULL);
  pszDst[nLen - 1] = 0;
  std::string strTemp(pszDst);
  delete[] pszDst;
  return strTemp;
#endif
#if 0
	std::wstring_convert<std::codecvt_utf8_utf16<wchar_t>, wchar_t> cvt;
	cvt.to_bytes(std::wstring(pwszSrc));
#endif
};

std::string Uni2UTF8Str(const std::wstring &pwszSrc) {
  LPCWSTR src = pwszSrc.c_str();
  return Uni2UTF8StrS((wchar_t *)pwszSrc.c_str());
}
```

将所以原始字符串定义类似如下：
```C++
std::vector<std::string> texts_ds = {"花呗收款额度限制", "花呗支持高铁票支付吗"};
```
重新定义为：
```C++
std::vector<std::string> texts_ds = {Uni2UTF8Str(L"花呗收款额度限制"), Uni2UTF8Str(L"花呗支持高铁票支付吗")};
```
有多处需要修改可解决上述问题，期待出windows编码兼容的版本。

**Comment by DefTruth** [comment]
@huangwm999 非常感谢，我们已经收到您的反馈~

**Comment by DefTruth** [comment]
请问您的编译方式是什么呢？是命令行编译还是cmake gui的编译方式？

**Comment by joey12300** [comment]
@huangwm999 您好，这个错误看起来像VisualStudio的编码设置问题，您看看重新设置VS的编码格式是否能解决：https://github.com/PaddlePaddle/FastDeploy/blob/17ff330daa9b87a5e443899579fdccfd92782ffe/docs/cn/faq/build_on_win_with_gui.md#%E7%89%B9%E5%88%AB%E6%8F%90%E7%A4%BA

**Comment by jiangjiajun** [comment]
此ISSUE由于一年未更新，将会关闭处理，如有需要，可再次更新打开。
