### ISSUE TITLE
docs

### ISSUE THREAD

**Issue by Sqhttwl** [PaddlePaddle/FastDeploy#1027]
# docs
C++预测库（aarch64)下载链接无效
![2d4731f245f0a2ef38ed4117afefefbe](https://user-images.githubusercontent.com/61459740/210234343-1d26cf0c-5a80-4d32-8425-184505dcb0c8.png)
![a684137cc0ee710d3092f9f09ad9ae58](https://user-images.githubusercontent.com/61459740/210234369-a4974650-b748-4512-ba1e-e9477a2c1fbf.png)

**Comment by leiqing1** [comment]
感谢反馈问题，我们立马修正。
也欢迎加入到开源建设中，从一个文档pr开始，从一个模型建设开始 🍀

**Comment by jiangjiajun** [comment]
@Sqhttwl Hi， 你好，我们已经更新文档。目前最新版本为1.0.2 可直接点这个链接下载 https://bj.bcebos.com/fastdeploy/release/cpp/fastdeploy-linux-aarch64-1.0.2.tgz

**Comment by jiangjiajun** [comment]
此ISSUE由于一年未更新，将会关闭处理，如有需要，可再次更新打开。
