### ISSUE TITLE
FastDeploy_examples_yolov7face_python_infer.py调用model.predict(im)报错

### ISSUE THREAD

**Issue by i-passion** [PaddlePaddle/FastDeploy#1030]
*********************************************
温馨提示：根据社区不完全统计，按照模板提问，可以加快回复和解决问题的速度
*********************************************

## 环境

- 【FastDeploy版本】： 1.0.2
- 【编译命令】用的example
- 【系统平台】: Linux x64(Ubuntu 18.04) / Windows x64(Windows10) 
- 【硬件】： CPU
- 【编译语言】： Python(3.7或3.8等）

## 问题日志及出现问题的操作流程
https://github.com/PaddlePaddle/FastDeploy/blob/release/1.0.2/examples/vision/facedet/yolov7face/python/infer.py
运行报错，提示model没有predict属性

## 解决方案：
需在Fastdeploy的python安装包文件中添加2行语句，请管理员合并到下一个版本里。
https://github.com/PaddlePaddle/FastDeploy/blob/release/1.0.2/python/fastdeploy/vision/facedet/contrib/yolov7face.py
class YOLOv7Face(FastDeployModel)类下添加：
def predict(self, input_image):
        return self._model.predict(input_image)

**Comment by wjj19950828** [comment]
@i-passion 您好，目前```predict``` API已经添加，PR链接：https://github.com/PaddlePaddle/FastDeploy/pull/1039

**Comment by jiangjiajun** [comment]
此ISSUE由于一年未更新，将会关闭处理，如有需要，可再次更新打开。
