### ISSUE TITLE
原生UIE性能到顶的情况下，FastDeploy能够带来多少的性能优化，希望提供测试报告附在github文档中

### ISSUE THREAD

**Issue by we-enjoy-today** [PaddlePaddle/FastDeploy#1033]
现在的情况是，多阶段推理，原生UIE fp16 use_faster=true 就已经到顶了

希望能出一个测试报告，附在github文档的部署示例中，即在上述基础上，FastDeploy最大能够提高多少性能

最好能做一个改造示例。因为从原生UIE迁移到FastDeploy部署，并且获得最大化的性能提升，里面还是有一些细节和注意事项的。

文档里的说明内容更详细、性能提升结果可复现，有利于FastDeploy大规模推广、也方便我跟朋友们安利，祝好~

类似这种效果：

![image](https://user-images.githubusercontent.com/96770068/210310881-e187e83a-3a98-42a4-8548-992dff0dcb00.png)

**Comment by jiangjiajun** [comment]
此ISSUE由于一年未更新，将会关闭处理，如有需要，可再次更新打开。
