### ISSUE TITLE
怎么尽可能使用GPU

### ISSUE THREAD

**Issue by JustinBili** [PaddlePaddle/FastDeploy#1035]
测试了rvm的trt加速，RTX2070显卡下1080P的输入图大概120ms，但是看了下gpu使用才4%左右，怎么尽可能的使用gpu，速度还能提升吗？

**Comment by jiangjiajun** [comment]
这可能是由于预处理在CPU上的原因。 整个推理是 图像 -> CPU预处理 -> GPU模型推理 -> CPU结果后处理。 整个数据流计算过程在CPU/GPU切换导致。

我们正在做前后处理的GPU化，之后希望可以进一步提升端到端的性能。

**Comment by leiqing1** [comment]
@jiangjiajun @JustinBili 不确定这里尽可能多的使用还包含多batch使用等？ 
得看你是离线处理多张图，还是实时一张图像一张图像来处理？ 多batch、多进程都可以充分利用资源，提升吞吐量（即整体推理速度）。

**Comment by JustinBili** [comment]
> @jiangjiajun @JustinBili 不确定这里尽可能多的使用还包含多batch使用等？ 得看你是离线处理多张图，还是实时一张图像一张图像来处理？ 多batch、多进程都可以充分利用资源，提升吞吐量（即整体推理速度）。

测试的是实时摄像头画面

**Comment by jiangjiajun** [comment]
> 测试了rvm的trt加速，RTX2070显卡下1080P的输入图大概120ms，但是看了下gpu使用才4%左右，怎么尽可能的使用gpu，速度还能提升吗？

另外在Windows上使用nvidia-smi命令来查看GPU使用率，不建议使用任务管理器来查看使用率

**Comment by jiangjiajun** [comment]
此ISSUE由于一年未更新，将会关闭处理，如有需要，可再次更新打开。
