### ISSUE TITLE
希望能够开直播视频讲讲FastDeploy的设计思路、架构组成、先进点代码实现，并提供录播视频，链接放在github文档中

### ISSUE THREAD

**Issue by we-enjoy-today** [PaddlePaddle/FastDeploy#1036]
我和朋友都使用了FastDeploy，目前都有这方面的需求，讨论后决定发这个issue

现有的介绍视频更多的是从产品使用的角度，但是为了更好的使用FastDeploy，希望能够更多的深入了解FastDeploy的架构设计、代码实现，以及后续的优化方向。

**Comment by jiangjiajun** [comment]
此ISSUE由于一年未更新，将会关闭处理，如有需要，可再次更新打开。
