### ISSUE TITLE
OCR中：det和cls模型可以正常编译为trt文件，但是rec模型编译时报错

### ISSUE THREAD

**Issue by jasper-cell** [PaddlePaddle/FastDeploy#1038]
## 环境

- 【FastDeploy版本】： fastdeploy-release1.0.0
- 【编译命令】cmake .. -DBUILD_ON_JETSON=ON \
         -DENABLE_VISION=ON \
         -DCMAKE_INSTALL_PREFIX=${PWD}/installed_fastdeploy
- 【系统平台】: jetson AGX
- 【硬件】： jetpack4.6.1
![image](https://user-images.githubusercontent.com/54393886/210316363-1758b806-1f2d-445e-83bd-b642703e6fec.png)

- 【编译语言】： C++ 

## 问题日志及出现问题的操作流程
![image](https://user-images.githubusercontent.com/54393886/210316175-ecb1e658-4417-42d7-bb1a-fb7b36faf18b.png)

det和cls模型可以正常编译为trt文件，但是rec模型编译时报错

**Comment by jiangjiajun** [comment]
注意到你用的是Jetpack 4.6.1，这可能是由于TRT版本的原因。 单纯使用TrtBackend是选Paddle导出为ONNX格式，再依赖TensorRT自带的ONNXParser解析模型。 版本较低的情况下，对于ONNX支持也可能会存在问题。

当前的情况下，建议在Jetson下编译时，开启Paddle后端，编译集成Paddle Inference。 在推理PaddleOCR时，使用Paddle Inference内置的TensorRT

**Comment by jasper-cell** [comment]
![image](https://user-images.githubusercontent.com/54393886/210318186-125e10f9-f03c-43d3-83c1-86ad55bf26f2.png)
我在用下面命令加入paddle inference时
cmake .. -DBUILD_ON_JETSON=ON \
         -DENABLE_VISION=ON \
         -DENABLE_PADDLE_BACKEND=ON \
         -DPADDLEINFERENCE_DIRECTORY=/Download/paddle_inference_jetson \
         -DCMAKE_INSTALL_PREFIX=${PWD}/installed_fastdeploy
进行编译时出现了上图中的错误

**Comment by jiangjiajun** [comment]
@jasper-cell HI，你能试下修改Fastdeploy/cmake/paddle_inference.cmake， 删除第60行，然后删除编译缓存，重新编译试下吗？

**Comment by jasper-cell** [comment]
![image](https://user-images.githubusercontent.com/54393886/210354114-e632f549-a8ff-4d30-8c5b-06a03e8f8f6d.png)
删除之后cmake可以过了，但是make的时候出现了上图问题

**Comment by jasper-cell** [comment]
![image](https://user-images.githubusercontent.com/54393886/210364842-2fbced08-cc43-4b81-bb49-bf09705ab105.png)
尝试解决了之后，在99%卡住了

**Comment by jiangjiajun** [comment]
https://github.com/PaddlePaddle/FastDeploy/pull/1044 我重新修改了代码，你能拉下这个分支编译试下吗？

**Comment by jasper-cell** [comment]
![image](https://user-images.githubusercontent.com/54393886/210467106-1919d410-b1a7-4dcb-8f64-0aa1d6fab6da.png)
您好，十分感谢您的解答，但是该分支还是在99的时候报错了。最后采用上图的方式来解决了，只有det和cls模块采用trt，rec模块只开始GPU

**Comment by jiangjiajun** [comment]
@jasper-cell Hi， 不好意思，昨天代码提的时候基于develop分支，确实存在编译问题。我已经将最新代码合入到develop分支，你可以按照下面的方式来编译，我测试已经没问题了。

```
git clone https://github.com/PaddlePaddle/FastDeploy
cd FastDeploy/python
git checkout develop

# 下载xavier 4.6.1的paddle inference包，具体根据开发环境下载
wget https://paddle-inference-lib.bj.bcebos.com/2.4.1/cxx_c/Jetson/jetpack4.6.1_gcc7.5/xavier/paddle_inference_install_dir.tgz
tar xvf paddle_inference_install_dir.tgz

export BUILD_ON_JETSON=ON
export ENABLE_VISION=ON
export ENABLE_PADDLE_BACKEND=ON
export PADDLEINFERENCE_DIRECTORY=${PWD}/paddle_inference_install_dir

python3 setup.py build
python3 setup.py bdist_wheel
```

**Comment by jiangjiajun** [comment]
此ISSUE由于一年未更新，将会关闭处理，如有需要，可再次更新打开。
