### ISSUE TITLE
'DetectionResult: [xmin, ymin, xmax, ymax, score, label_id 这种数据格式怎么解析成字典，或者list之类的数据格式

### ISSUE THREAD

**Issue by Firestick-Xia** [PaddlePaddle/FastDeploy#1047]
'DetectionResult: [xmin, ymin, xmax, ymax, score, label_id 这种数据格式怎么解析成字典，或者list之类的数据格式？
![image](https://user-images.githubusercontent.com/57173448/210493151-45bd357f-8c12-4b5b-8268-0ef28aed66c8.png)

**Comment by jiangjiajun** [comment]
https://baidu-paddle.github.io/fastdeploy-api/ Python和C++中各结构和函数定义参考这个文档

**Comment by Firestick-Xia** [comment]
![image](https://user-images.githubusercontent.com/57173448/210495687-ff311008-4606-40cc-a66e-2266ed88ec52.png)
还是不知道如何处理，怎么一条一条处理输出的结果呢？

**Comment by Firestick-Xia** [comment]
返回给后端，返回结构化的输出结果（json格式）

**Comment by jiangjiajun** [comment]
```
result = ppyoloe.model.predict(im)
```
`result.score`是一个`list of int`，也就是`[1, 2, 3, 4]`， 其它的成员变量同理

这里有类似的函数将结果转为json https://github.com/PaddlePaddle/FastDeploy/blob/29c6716d4e1b5a3c17328e3bac0464e73bfd519f/python/fastdeploy/vision/utils.py#L27-L38
