### ISSUE TITLE
请问预计PaddleX模型什么时候能支持？

### ISSUE THREAD

**Issue by CashBai** [PaddlePaddle/FastDeploy#1050]
平时多数模型都是paddlex训练的，但是FastDeploy加载PaddleX的模型会报错，从别的issue上得到消息是暂时不支持。想问一下，计划什么时候会将PaddleX的模型也支持起来呀？

**Comment by jiangjiajun** [comment]
麻烦列一下你需要支持的模型列表（模型名），按优先级顺序列出，我们会按照优先级顺序评估，先支持一部分

**Comment by CashBai** [comment]
@jiangjiajun 分类ResNet50_vd_ssld，目标检测PPYolov2（骨架ResNet50_vd_dcn），语义分割DeepLabv3+（骨架ResNet50_vd）

**Comment by jiangjiajun** [comment]
方便的话，同时提供下你导出的模型哈

**Comment by CashBai** [comment]
@jiangjiajun 模型比较大，传百度网盘可以吗

**Comment by jiangjiajun** [comment]
可以

**Comment by CashBai** [comment]
@jiangjiajun 链接: https://pan.baidu.com/s/1bfCx_xXgqWv6BRJyHSimkA 提取码: 1uth
里面有三个模型，分类、目标检测、语义分割都各放了一个

**Comment by jiangjiajun** [comment]
此ISSUE由于一年未更新，将会关闭处理，如有需要，可再次更新打开。
