### ISSUE TITLE
用trition server 21.01编译服务器镜像的时候出错

### ISSUE THREAD

**Issue by intjun** [PaddlePaddle/FastDeploy#1051]
cmake .. -DFASTDEPLOY_DIR=/workspace/fastdeploy/build/fastdeploy_install -DTRITON_COMMON_REPO_TAG=r21.02 -DTRITON_CORE_REPO_TAG=r21.02 -DTRITON_BACKEND_REPO_TAG=r21.02;
make -j`nproc`'
出错：
![1672816720(1)](https://user-images.githubusercontent.com/23567603/210503399-0ccedb0b-fc66-47eb-a449-4d5072401db8.jpg)

**Comment by heliqi** [comment]
我们适配的triton版本是21.10+， 所以请把TRITON_COMMON_REPO_TAG等设置为 r21.10

**Comment by intjun** [comment]
> 我们适配的triton版本是21.10+， 所以请把TRITON_COMMON_REPO_TAG等设置为 r21.10

21.10+需要cuda11.4，那我们想编译cuda11.2的版本的话如何编译呢？

**Comment by heliqi** [comment]
21.10的Triton官方镜像是cuda 11.4， 并不是21.10需要CUDA 11.2。 
你需要cuda 11.2只能自己基于CUDA 11.2的镜像从源码编译Triton相关的库+制作一个CUDA 11.2的镜像。

Triton 的每个版本有更新升级一些接口和功能， 你使用旧版本Triton编译 FastDeploy肯定会出现报错（使用的接口在旧版本不存在）

**Comment by heliqi** [comment]
能说下为啥一定需要CUDA11.2的镜像吗？ 需求合理的话，我们后续可以考虑出更多CUDA11版本的镜像

**Comment by intjun** [comment]
> 能说下为啥一定需要CUDA11.2的镜像吗？ 需求合理的话，我们后续可以考虑出更多CUDA11版本的镜像

因为公司的服务器各种原因不能升级驱动，驱动只支持到cuda11.2

**Comment by heliqi** [comment]
了解，我们已经将CUDA 11.x版本镜像加入后续计划, 预计完成要在春节前后。
如果你想编译Triton， 可以看下这个build脚本:   https://github.com/triton-inference-server/server/blob/r21.10/build.py

**Comment by heliqi** [comment]
@intjun  我们已经支持cuda 11.2的镜像编译，具体参考这个[PR](https://github.com/PaddlePaddle/FastDeploy/pull/1169)
如果需要其他版本CUDA，只需要把Dockerfile中的依赖镜像从cuda11.2改成 cudax.y即可

**Comment by intjun** [comment]
> @intjun 我们已经支持cuda 11.2的镜像编译，具体参考这个[PR](https://github.com/PaddlePaddle/FastDeploy/pull/1169) 如果需要其他版本CUDA，只需要把Dockerfile中的依赖镜像从cuda11.2改成 cudax.y即可

感谢！
