### ISSUE TITLE
paddle很多模型是训练模型，不是推理模型，希望增加直接适用训练模型的方式

### ISSUE THREAD

**Issue by song4875343** [PaddlePaddle/FastDeploy#1055]
不少模块并没有提供从训练模型转推理模型的方法，能否直接适用训练模型的参数文件直接转onnx。

**Comment by jiangjiajun** [comment]
训练参数转onnx是支持的，直接调用paddle.onnx.export接口即可，跟动转静是同样的导出方式

**Comment by song4875343** [comment]
是吗？能否给个例子，目前例子中的文件，需要分别给出"infer.pdmodel"，"infer.pdiparams"的路径

**Comment by jiangjiajun** [comment]
https://www.paddlepaddle.org.cn/documentation/docs/zh/guides/advanced/model_to_onnx_cn.html#id1

**Comment by song4875343** [comment]
非常感谢

**Comment by jiangjiajun** [comment]
此ISSUE由于一年未更新，将会关闭处理，如有需要，可再次更新打开。
