### ISSUE TITLE
能否提升paddle模型读取，库导入的速度

### ISSUE THREAD

**Issue by song4875343** [PaddlePaddle/FastDeploy#1056]
paddle训练的模型可圈可点，但是paddle模型python import导入很多库时，时间非常长，这样很多企业应用时代码头一次适用，时间非常长，影响使用体验。对用pytorch类似问题，导入库和模型用0.3秒，而paddle进程导入一个paddle就要花2秒，其他乱七八糟的，一起需要4~5秒钟。

**Comment by jiangjiajun** [comment]
import fastdeploy现在有这个问题吗？

**Comment by song4875343** [comment]
import paddle 就需要2秒

**Comment by jiangjiajun** [comment]
import paddle需要时间长，是因为安装的是GPU版本，在import时，需要对GPU做资源的初始化，这个天然会耗时。

**Comment by song4875343** [comment]
我安装的是paddle cpu版本，但是调入paddlenlp.transform.autotoken 会自动调入paddle，不知道能否改进。在torch实现同样的功能时间是paddle框架的1/10的时间，我想还是有改进空间的。

**Comment by jiangjiajun** [comment]
此ISSUE由于一年未更新，将会关闭处理，如有需要，可再次更新打开。
