### ISSUE TITLE
 RobustVideoMatting source. License question 

### ISSUE THREAD

**Issue by ox-prog** [PaddlePaddle/FastDeploy#1059]
I'm wondering if it's possible to use [PaddlePaddle RVM built-in C++ module and models](https://github.com/PaddlePaddle/FastDeploy/tree/release/1.0.2/examples/vision/matting/rvm), due to the fact that [original model](https://github.com/PeterL1n/RobustVideoMatting) has GPL-3.0 license ( Disclose source), and PaddlePaddle has  Apache-2.0 license (not disclose source)

**Comment by jiangjiajun** [comment]
Hi, The model is exported from the original repo, so if we are going to use the exported model, I think we need to follow GPL license. (Thanks for reminding me to put a license notice here https://github.com/PaddlePaddle/FastDeploy/tree/release/1.0.2/examples/vision/matting/rvm)

The code in FastDeploy is not copied from the repo, we reimplement all the preprocessing and postprocessing code in c++,  so we still keep open resourced  with Apache-2.0 license,  if there's any problem, please let me know.

**Comment by ox-prog** [comment]
Hi, thank you! 
Could you please advise in terms of FastDeploy license to make it more clear: if I want to use FastDeploy (Apache 2 ) in my commercial project (closed source) with GPL-license model (like RVM disclose source) then should I disclose my source code for GPL license? Or I can follow Apache 2 license and just attach model weights and links?

As you mention, you implement RVM from scratch - Am I correct that now just model weights is GPL, and I can disclose  only its?

**Comment by leiqing1** [comment]
Hi This RVM model comes from the  repo of [PeterL1n/RobustVideoMatting](https://github.com/PeterL1n/RobustVideoMatting). It should also be the GPT license. If you want to use it, you need to follow the GPT license. FastDeploy code follows Apache 2 protocol including  RVM code.
