### ISSUE TITLE
加载自己编译的libtriton_fastdeploy.so出现问题

### ISSUE THREAD

**Issue by intjun** [PaddlePaddle/FastDeploy#1061]
自己尝试编译不同cuda版本的server镜像，启动时出现bug
![1672885753(1)](https://user-images.githubusercontent.com/23567603/210688011-2d8ac7f6-a840-4b64-b11b-7c94a937431f.png)

**Comment by heliqi** [comment]
你编译时使用的cmake指令能发下吗？ 链接的Triton 版本是多少？ 
看报错是有Triton的接口没对上

**Comment by intjun** [comment]
> 你编译时使用的cmake指令能发下吗？ 链接的Triton 版本是多少？ 看报错是有Triton的接口没对上
cmake .. -DFASTDEPLOY_DIR=/workspace/fastdeploy/build/fastdeploy_install -DTRITON_COMMON_REPO_TAG=r21.10 -DTRITON_CORE_REPO_TAG=r21.10 -DTRITON_BACKEND_REPO_TAG=r21.10

但是我这个tritonsever的镜像是21.02的。如果改为cmake .. -DFASTDEPLOY_DIR=/workspace/fastdeploy/build/fastdeploy_install -DTRITON_COMMON_REPO_TAG=r21.10 -DTRITON_CORE_REPO_TAG=r21.02 -DTRITON_BACKEND_REPO_TAG=r21.02就是产生编译错误

**Comment by heliqi** [comment]
那是fd的serving跟triton版本没对应导致的， fd serving适配的是Triton 21.10版本以上。 21.02版本太古老，我们目前不支持。

这个我先关闭，我们统一在这个issue中讨论吧: https://github.com/PaddlePaddle/FastDeploy/issues/1051
