### ISSUE TITLE
rv1126上部署demo，交叉编译失败

### ISSUE THREAD

**Issue by richjjj** [PaddlePaddle/FastDeploy#1064]
## 环境

- 【FastDeploy版本】： develop
- 【编译命令】: 交叉编译，编译器为 gcc-arm-8.3-2019.03-x86_64-arm-linux-gnueabihf
- 【系统平台】: host为Ubuntu 20.04
- 【硬件】: RV1126
- 【编译语言】： C++

## 问题日志及出现问题的操作流程
1. 交叉编译fastdeploy库成功
2. 编译[rv1126平台上的yolov5例子](https://github.com/PaddlePaddle/FastDeploy/tree/release/1.0.2/examples/vision/detection/yolov5/rv1126/cpp)出错
     - 错误日志为：
![image](https://user-images.githubusercontent.com/37280580/210696604-8372228b-5af3-4bf3-839a-e6d00c0d55fb.png)
     - 可能原因：paddlelite和opencv预编译库所用的 gcc版本高于8.3

**Comment by richjjj** [comment]
# 补充信息
1. 编译器为 arm-linux-gnueabihf-gcc-9.4 能交叉编译成功
2. demo拷贝到rv1126板子上运行失败
     - 错误日志：
![image](https://user-images.githubusercontent.com/37280580/210698335-71d23245-dbde-4dc6-ba94-dedbba8c422a.png)

**Comment by yeliang2258** [comment]
arm-linux-gnueabihf-gcc-9.4时，输入model和测试图片看看，可以看看run_with_adb.sh，前面这些log信息不算是报错

**Comment by richjjj** [comment]
> arm-linux-gnueabihf-gcc-9.4时，输入model和测试图片看看，可以看看run_with_adb.sh，前面这些log信息不算是报错

执行命令是：```./infer_demo ./models/yolov5s_ptq_model ./images/000000014439.jpg```
除了这些log信息就没有其他的打印信息了，也没有图片保存。

**Comment by yeliang2258** [comment]
> # 补充信息
> 1. 编译器为 arm-linux-gnueabihf-gcc-9.4 能交叉编译成功
> 2. demo拷贝到rv1126板子上运行失败
>    
>    * 错误日志：
>      ![image](https://user-images.githubusercontent.com/37280580/210698335-71d23245-dbde-4dc6-ba94-dedbba8c422a.png)

这个的log信息麻烦截全我看看？因为我这边跑通的demo也会有这些信息，这后面的关键信息没看到呢。
![image](https://user-images.githubusercontent.com/30516196/210742451-006c3555-06a7-4958-b48b-db4f5fdba6af.png)

**Comment by richjjj** [comment]
执行demo后的所有log信息：[log.txt](https://github.com/PaddlePaddle/FastDeploy/files/10350904/log.txt)

**Comment by yeliang2258** [comment]
辛苦将下面的几个export信息加进去再试试，
export GLOG_v=5
export VIV_VX_ENABLE_GRAPH_TRANSFORM=-pcq:1
export VIV_VX_SET_PER_CHANNEL_ENTROPY=100
export TIMVX_BATCHNORM_FUSION_MAX_ALLOWED_QUANT_SCALE_DEVIATION=300000
export VSI_NN_LOG_LEVEL=5

**Comment by richjjj** [comment]
> 辛苦将下面的几个export信息加进去再试试， export GLOG_v=5 export VIV_VX_ENABLE_GRAPH_TRANSFORM=-pcq:1 export VIV_VX_SET_PER_CHANNEL_ENTROPY=100 export TIMVX_BATCHNORM_FUSION_MAX_ALLOWED_QUANT_SCALE_DEVIATION=300000 export VSI_NN_LOG_LEVEL=5

大佬辛苦了。还是一样的，没有结果

**Comment by yeliang2258** [comment]
奇怪了，麻烦加一下我的微信吧，一起讨论一下，微信号：

**Comment by jiangjiajun** [comment]
此ISSUE由于一年未更新，将会关闭处理，如有需要，可再次更新打开。
