### ISSUE TITLE
fd_serving容器没有ip

### ISSUE THREAD

**Issue by cunjing56** [PaddlePaddle/FastDeploy#1079]
*********************************************
温馨提示：根据社区不完全统计，按照模板提问，可以加快回复和解决问题的速度
*********************************************
参考此案例运行
https://github.com/PaddlePaddle/FastDeploy/blob/develop/examples/vision/detection/paddledetection/serving/README.md

docker run -it --net=host --name fd_serving --shm-size="1g"  -v D:/pkg/FastDeploy/examples/vision/detection/paddledetection/serving/:/serving registry.baidubce.com/paddlepaddle/fastdeploy:1.0.1-cpu-only-21.10  bash

新建容器fd_serving 没有分配ip, win, ubuntu均是 
![image](https://user-images.githubusercontent.com/112528302/210937046-adb394a3-03e8-48eb-90ba-22ccafcd3585.png)
![image](https://user-images.githubusercontent.com/112528302/210937183-5a7ea149-4a1e-4f76-a170-3eade71f858a.png)
请问执行代码是否有问题？ host需要改成bridge吗？

**Comment by heliqi** [comment]
启动容器时设置net=host，host模式中容器将共享主机网络，本身是不会分配ip，可以看到Networks中会有个host配置。
我们在demo中使用host模式，是为了方便用户在主机或容器中都能执行客户端请求测试。
你可以根据自己需求修改docker启动命令，使用其他模式。比如通过-p参数只映射想要暴露的端口， 也可以设置container 、none等模式

**Comment by heliqi** [comment]
如果你想让容器被分配ip，用默认的bridge模式即可。
