### ISSUE TITLE
可以使用fastdeploy部署GPLink模型吗（UIE的蒸馏模型）？

### ISSUE THREAD

**Issue by 996-icu-FuJian** [PaddlePaddle/FastDeploy#1081]
如题，有的话是否有实例呢？

**Comment by joey12300** [comment]
@996-icu-FuJian 您好，目前暂时不支持GPLink模型的部署，想问下现有的UIE模型能满足您的业务需求吗？是出于什么目的想部署GPLink呢？

**Comment by 996-icu-FuJian** [comment]
> @996-icu-FuJian 您好，目前暂时不支持GPLink模型的部署，想问下现有的UIE模型能满足您的业务需求吗？是出于什么目的想部署GPLink呢？

您好！现有的UIE模型在CPU端推理速度较慢，期望可以加速模型的推理速度。

**Comment by jiangjiajun** [comment]
此ISSUE由于一年未更新，将会关闭处理，如有需要，可再次更新打开。
