### ISSUE TITLE
[Android] 使用预编译的cpu android动态库 运行失败

### ISSUE THREAD

**Issue by MarsMeng1994** [PaddlePaddle/FastDeploy#1086]
[FastDeploy][ERROR] fastdeploy/runtime.cc(262)::UsePaddleBackend	The FastDeploy didn't compile with Paddle Inference.

看起来像是因为提供的预编译库没有编Paddle Inference，只支持Paddle Lite。
请问有Lite的调用方法吗？我这边的实现参考的：
https://github.com/PaddlePaddle/FastDeploy/blob/release/1.0.2/docs/cn/quick_start/runtime/cpp.md

**Comment by DefTruth** [comment]
是的，目前Android端只支持Lite，如果您是在adb中通过脚本测试的话，那和正常的C++调用是一样的，只需要对RuntimeOption增加一行代码：  
```c++
option.UsePaddleLiteBackend(); // 老版本的SDK 使用 option.UseLiteBackend()
```  
```C++
fastdeploy::RuntimeOption c_runtime_option;
c_runtime_option.UseCpu();
c_runtime_option.UseLiteBackend();
```
如果是希望通过JNI接入到Android App中使用，则可以参考：  
- [faq/use_cpp_sdk_on_android.md](https://github.com/PaddlePaddle/FastDeploy/blob/release%2F1.0.2/docs/cn/faq/use_cpp_sdk_on_android.md)

**Comment by DefTruth** [comment]
Java SDK API 可以参考：  
- https://github.com/PaddlePaddle/FastDeploy/tree/release/1.0.2/java/android

**Comment by jiangjiajun** [comment]
此ISSUE由于一年未更新，将会关闭处理，如有需要，可再次更新打开。
