### ISSUE TITLE
build Fast deploy on Raspbian(bullseye) 32 bit 

### ISSUE THREAD

**Issue by saeedkhanehgir** [PaddlePaddle/FastDeploy#1098]
## Environment

FastDeploy version:  0.6.0 
OS Platform: Raspbian(bullseye) 32 bit 

## Problem description

Hi
Thanks for sharing this project.
I want to build Fast Deploy on Raspbian(bullseye) 32 bit . I use the below command for building.

`sudo cmake .. -DENABLE_ORT_BACKEND=ON -DOPENCV_DIRECTORY=/usr/local/ -DCMAKE_INSTALL_PREFIX=${PWD}/myjob -DENABLE_VISION=ON`

but I get this error.

![Screenshot from 2023-01-09 14-39-31](https://user-images.githubusercontent.com/65589645/211295076-c81934be-dfdb-4f67-ba66-fd84f2a576aa.png)

Can you help me?
Thanks

**Comment by jiangjiajun** [comment]
Hi, @saeedkhanehgir  ONNX Runtime doesn't provide a prebuilt library for 32bit arm platform, so it's not support for FastDeploy either.

If you need to build FastDeploy with ONNX Runtime on Raspbian 32bit platform, please

- 1. Build ONNXRuntime on Raspbian first, refer to it's [build step](https://onnxruntime.ai/docs/build/inferencing.html#cpu), please build version 1.12.0, the newest version is not supported yet.
- 2. After build ONNX Runtime C++ library, rebuild FastDeploy by use `-DORT_DIRECTORY=/path/to/onnxruntime_library`, the path `/path/to/onnxruntime_library` contains `include` and `lib`

**Comment by jiangjiajun** [comment]
By the way, if you need to deploy Paddle model on Raspbian, it's recommend to use Paddle Lite backend, just use the follwing build command

```
cmake .. -DENABLE_LITE_BACKEND=ON \
               -DOPENCV_DIRECTORY=/use/local \
               -DPADDLELITE_URL=https://bj.bcebos.com/fastdeploy/third_libs/lite-linux-armhf-2.1.2.tgz
```

We haven't test on arm 32bit platform yet, so if there's any problem, please let me know.

**Comment by jiangjiajun** [comment]
此ISSUE由于一年未更新，将会关闭处理，如有需要，可再次更新打开。
