### ISSUE TITLE
什么时候支持SSE指令集CPU

### ISSUE THREAD

**Issue by yzm0080** [PaddlePaddle/FastDeploy#1103]
### 支持SSE指令集CPU，在一些低功耗CPU上使用
工控机上多采用低功耗的cpu，例如 Intel Atom系列，它不支持AVX 及 FMA指令集，只支持SSE。
在windows开发机上编译PaddleOCR工程示例，正常运行，部署到工控机的windows10上却无法运行，用cpu-z工具查看cpu信息时才注意到是 Intel Atom x5-Z8350，不支持AVX 及 FMA指令集。

TensorFlow Lite好像是支持SSE指令集cpu。

**Comment by ZeyuChen** [comment]
@yzm0080 https://github.com/PaddlePaddle/FastDeploy

关于CPU的部署可以关注下FastDeploy这个产品，未来这类需求会通过FastDeploy来满足，欢迎提相关Issues。

**Comment by jiangjiajun** [comment]
FastDeploy里面集成了ONNX Runtime后端，可以试用下哈

**Comment by nefusmzj** [comment]
> 

您的意思是，FastDeploy配置使用ONNX Runtime的后端，可以在不支持AVX的CPU上运行吗？
