### ISSUE TITLE
GPU发布服务错误 Error: Failed to initialize NVML

### ISSUE THREAD

**Issue by cunjing56** [PaddlePaddle/FastDeploy#1106]
*********************************************
温馨提示：根据社区不完全统计，按照模板提问，可以加快回复和解决问题的速度
*********************************************

## 环境
nvidia-docker images serving registry.baidubce.com/paddlepaddle/fastdeploy:1.0.1-gpu-cuda11.4-trt8.4-21.10 

win

参考案例
(https://github.com/PaddlePaddle/FastDeploy/blob/develop/examples/vision/detection/paddledetection/serving/README.md)

gpu部署已经修改runtime config.pbtxt
![image](https://user-images.githubusercontent.com/112528302/211511749-90e0a6a4-a5ac-476c-9103-11252235190c.png)

yoloe 的name也改了，也注释了
![image](https://user-images.githubusercontent.com/112528302/211512055-92ee30d7-7922-44fc-bf00-ff1fd4c22148.png)

现在发布gpu服务报错

![image](https://user-images.githubusercontent.com/112528302/211512222-f7275ac4-3a4a-48b5-a926-dc0909623854.png)
![image](https://user-images.githubusercontent.com/112528302/211512683-33aaed16-d26f-414f-ba89-1c0b43bfb230.png)

**Comment by heliqi** [comment]
看起来是Driver版本太低。你在容器中执行下 `nvidia-smi`看看，如果有报错先执行下`ldconfig`,再执行下`nvidia-smi`。
执行结果截图下

**Comment by cunjing56** [comment]
> 看起来是Driver版本太低。你在容器中执行下 `nvidia-smi`看看，如果有报错先执行下`ldconfig`,再执行下`nvidia-smi`。 执行结果截图下

谢谢，是容器启动 的时候没带--gpus all 比如这样。
docker run --gpus all -it --net=host --name fd_serving_gpu --shm-size="1g"  -v D:/pkg/FastDeploy/examples/vision/detection/paddledetection/serving/:/serving registry.baidubce.com/paddlepaddle/fastdeploy:1.0.1-gpu-cuda11.4-trt8.4-21.10  bash
