### ISSUE TITLE
fastdeploy支持jetson jetpack4.5及其以下版本吗

### ISSUE THREAD

**Issue by futureflsl** [PaddlePaddle/FastDeploy#1122]
看了官方要求是jetpack必须是4.6，但是现在市场上主流用的最多还是jetpack4.5及其以下版本,这些版本cuda都是10.2，建议提供对jetpack4.5及其以下版本支持，不然jetson只支持4.6版本使用上基本没有什么意义。目前绝大部分还是用的cuda10.2版本jetson

**Comment by JoeyZhu** [comment]
同问
