### ISSUE TITLE
python安装fastdeploy之后显示__init__中没有vision

### ISSUE THREAD

**Issue by guoyunqingyue** [PaddlePaddle/FastDeploy#1128]
遵照要求使用pip install fastdeploy-gpu-python -f https://www.paddlepaddle.org.cn/whl/fastdeploy.html 成功安装fastdeploy后，打算部署Yolov5模型，但显示__init__中没有vision，请问是我缺少了哪部操作吗

**Comment by jiangjiajun** [comment]
麻烦贴一下报错提示

另外注意在运行的python目录下，不要有fastdeploy/fastdeploy.py命名的文件、目录，因为这会影响python导入库重名问题

**Comment by guoyunqingyue** [comment]
目前运行时报错是 ModuleNotFoundError: No module named 'resource'  我也进行了安装，但并没有效果。此外，没有目录或者文件命名为fastdeploy/fastdeploy.py，但from fastdeploy.vision中vision仍然处于标红状态，显示__init__中没有vision。fastdeploy-gpu-python的版本为1.0.2

**Comment by jiangjiajun** [comment]
根据你的说明，你应该是从pypi源上安装了一个叫做`fastdeploy`的包，那个并非FastDeploy的包。 按照下面重新安装一下
```
pip uninstall fastdeploy
pip uninstall fastdeploy-gpu-python
pip install fastdeploy-gpu-python -f https://www.paddlepaddle.org.cn/whl/fastdeploy.html
```

**Comment by guoyunqingyue** [comment]
问题解决了，感谢指点

**Comment by jiangjiajun** [comment]
此ISSUE由于一年未更新，将会关闭处理，如有需要，可再次更新打开。
