### ISSUE TITLE
Yolov8  feature request

### ISSUE THREAD

**Issue by UygarUsta99** [PaddlePaddle/FastDeploy#1132]
Yolov8 is released by ultralytics,do you have any plans on adding the model in the near future ?

**Comment by jiangjiajun** [comment]
It will be supported next week.

**Comment by wjj19950828** [comment]
@UygarUsta99 Hi, the code has been integrated, use the following api, welcome to try~

```python
model = fd.vision.detection.YOLOv8(args.model, runtime_option=runtime_option)
```

refer to [yolov8 demo](https://github.com/PaddlePaddle/FastDeploy/blob/develop/examples/vision/detection/yolov8/python/infer.py)

**Comment by UygarUsta99** [comment]
Thanks for the great work,I sure will as soon as possible !

**Comment by UygarUsta99** [comment]
I have tried the yolov8 in c++ and it works great but I had to export yolov8 onnx weights using colab myself because I ran into conversion issues with tensorrt using yolov8 weights you provided.Might wanna check that out.Also I used the library on jetson tx2.

**Comment by wjj19950828** [comment]
@UygarUsta99 What is the specific error reported when running TRT?

I have verified that the provided ONNX model can run TRT

**Comment by jiangjiajun** [comment]
> 
which jetpack version you are using?  Please try to update to the latest version

**Comment by wjj19950828** [comment]
@UygarUsta99 I saw you raised the same [issue](https://github.com/PaddlePaddle/FastDeploy/issues/798) when running yolov5, is this the same problem? Can you try the previous method to solve it?

**Comment by UygarUsta99** [comment]
@wjj19950828  The error was export error when converting yolov5 onnx weights to tensorrt.I had solved the issue when I exported the onnx weights with a torch version different than 1.12.With yolov8 I did the same,I exported the weights again using colab and it worked.
@jiangjiajun I have jetpack 4.6 installed on my jetson tx2,which may be the problem but I dont think I can upgrade it to newer versions.

**Comment by jiangjiajun** [comment]
The model structure of YOLOv8 is more complicate than YOLOv5, this may cause fail in jetpack 4.6(TRT 8.0)。 Maybe you can try to optimize the YOLOv8 onnx model by onnx-simplifier first

**Comment by UygarUsta99** [comment]
> The model structure of YOLOv8 is more complicate than YOLOv5, this may cause fail in jetpack 4.6(TRT 8.0)。 Maybe you can try to optimize the YOLOv8 onnx model by onnx-simplifier first

Will try thank you !

**Comment by UygarUsta99** [comment]
Any plans on adding rotating object detection models such as PP-YOLOE-R ? @jiangjiajun @wjj19950828

**Comment by jiangjiajun** [comment]
It's on our plan. A new version will be released in next month which will support PP-YOLOE-R

**Comment by UygarUsta99** [comment]
Thanks !
