### ISSUE TITLE
windows部署C++代码（gpu）

### ISSUE THREAD

**Issue by David-Wang001** [PaddlePaddle/FastDeploy#1133]
## 环境

- 【FastDeploy版本】： 说明具体的版本，fastdeploy-win-x64-gpu-1.0.2
- 【编译命令】如果您是自行编译的FastDeploy，请说明您的编译方式（参数命令）
- 【系统平台】: Windows x64(Windows10)
- 【硬件】： 说明具体硬件型号，Nvidia GPU 3060I， CUDA 11.2 CUDNN 8.0.4
- 【编译语言】： C++

## 问题日志及出现问题的操作流程
![微信图片_20230113014025](https://user-images.githubusercontent.com/14051049/212139825-c966f971-4c52-4225-ad89-dcdf046d7415.png)
![微信图片_20230113014032](https://user-images.githubusercontent.com/14051049/212139854-c741ceda-410c-4f65-93a3-6b087a0ebf4d.png)

windows上部署fastdeploy，debug报错“没有为 openvino.dll 加载的符号文件”。
C++代码编译不报错，运行报错。

**Comment by jiangjiajun** [comment]
1. Windows上目前不支持Debug模型，采用Release模型即可
2. 编译后的exe出现上述问题，一般原因都是没有找到dll，需要将所有fastdeploy的dll拷贝到exe所在目录下。 fastdeploy的dll文件很多，不建议手动拷贝（容易遗漏），请使用此文档中提供的工具fastdeploy_init.bat来进行指拷贝 https://github.com/PaddlePaddle/FastDeploy/blob/release/1.0.2/docs/cn/faq/use_sdk_on_windows.md#413-fastdeploy_initbat-%E5%AE%89%E8%A3%85-sdk-%E4%B8%AD%E6%89%80%E6%9C%89%E7%9A%84-dll-%E5%88%B0%E6%8C%87%E5%AE%9A%E7%9A%84%E7%9B%AE%E5%BD%95-%E6%8E%A8%E8%8D%90

**Comment by lhh753159** [comment]
windows上 CPU版本的 yolov5face 怎么把 图像预处理的 img size 大小改为 160x160，找了两天没找到源码在哪路改 @jiangjiajun  /(ㄒoㄒ)/~~

**Comment by jiangjiajun** [comment]
@lhh753159  
可以看到这里有个成员变量`size`
https://github.com/PaddlePaddle/FastDeploy/blob/f441ffe56bd291edde6780b2a177c6ccdc349197/fastdeploy/vision/facedet/contrib/yolov5face.h#L53-L56

所以调用`model.size = {160, 160}`, 即可改变预处理时的大小

**Comment by lhh753159** [comment]
解决了  笔芯♥ @jiangjiajun

**Comment by leeguandong** [comment]
我也遇到这个问题，用文档中提供fastdeploy_init.bat来迁移dll就解决了。

**Comment by jiangjiajun** [comment]
此ISSUE由于一年未更新，将会关闭处理，如有需要，可再次更新打开。
