### ISSUE TITLE
为什么推理速度会越来越慢？

### ISSUE THREAD

**Issue by universea** [PaddlePaddle/FastDeploy#1134]
*********************************************
温馨提示：根据社区不完全统计，按照模板提问，可以加快回复和解决问题的速度
*********************************************

## 环境

- 【FastDeploy版本】： 说明具体的版本，如fastdeploy-linux-gpu-1.0.1
- 【编译命令】pip install
- 【系统平台】: Windows x64(Windows10) 
- 【硬件】： 说明具体硬件型号，如 Nvidia GPU 1050， CUDA 11.7 CUDNN 8.4
- 【编译语言】： C++ / Python(3.7或3.8等）

<img width="551" alt="1673576862899" src="https://user-images.githubusercontent.com/13444641/212223094-44538ead-ce69-4222-af96-e0892db6abf4.png">

**Comment by jiangjiajun** [comment]
Hi, 你好，麻烦提供一下具体的测试代码我们分析下

**Comment by universea** [comment]
> Hi, 你好，麻烦提供一下具体的测试代码我们分析下

import fastdeploy as fd
import cv2
import os
from fastdeploy import ModelFormat
import time


def parse_arguments():
    import argparse
    import ast
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--model", default=None, help="Path of yolov7 onnx model.")
    parser.add_argument(
        "--image", default=None, help="Path of test image file.")
    parser.add_argument(
        "--device",
        type=str,
        default='cpu',
        help="Type of inference device, support 'cpu' or 'gpu'.")
    parser.add_argument(
        "--use_trt",
        type=ast.literal_eval,
        default=False,
        help="Wether to use tensorrt.")
    return parser.parse_args()


def build_option(args):
    option = fd.RuntimeOption()

    if args.device.lower() == "gpu":
        option.use_gpu()

    if args.use_trt:
        option.use_trt_backend()
        option.set_trt_input_shape("images", [1, 3, 640, 640])
    return option


args = parse_arguments()

if args.model is None:
    model = fd.download_model(name='YOLOv7')
else:
    model = args.model

# 配置runtime，加载模型
runtime_option = build_option(args)
model = fd.vision.detection.YOLOv7(model, runtime_option=runtime_option)

# 预测图片检测结果
if args.image is None:
    image = fd.utils.get_detection_test_image()
else:
    image = args.image


im = cv2.imread(image)
for i in range(100):
    start_time = time.time()
    result = model.predict(im)
    end_time = time.time()
    print("time cost:", float(end_time - start_time) * 1000.0, "ms")

# 预测结果可视化
vis_im = fd.vision.vis_detection(im, result, score_threshold=0.5)



cv2.imwrite("visualized_result.jpg", vis_im)
print("Visualized result save in ./visualized_result.jpg")

**Comment by universea** [comment]
> Hi, 你好，麻烦提供一下具体的测试代码我们分析下

`import fastdeploy as fd
import cv2
import os
from fastdeploy import ModelFormat
import time


def parse_arguments():
    import argparse
    import ast
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--model", default=None, help="Path of yolov7 onnx model.")
    parser.add_argument(
        "--image", default=None, help="Path of test image file.")
    parser.add_argument(
        "--device",
        type=str,
        default='cpu',
        help="Type of inference device, support 'cpu' or 'gpu'.")
    parser.add_argument(
        "--use_trt",
        type=ast.literal_eval,
        default=False,
        help="Wether to use tensorrt.")
    return parser.parse_args()


def build_option(args):
    option = fd.RuntimeOption()

    if args.device.lower() == "gpu":
        option.use_gpu()

    if args.use_trt:
        option.use_trt_backend()
        option.set_trt_input_shape("images", [1, 3, 640, 640])
    return option


args = parse_arguments()

if args.model is None:
    model = fd.download_model(name='YOLOv7')
else:
    model = args.model

# 配置runtime，加载模型
runtime_option = build_option(args)
model = fd.vision.detection.YOLOv7(model, runtime_option=runtime_option)

# 预测图片检测结果
if args.image is None:
    image = fd.utils.get_detection_test_image()
else:
    image = args.image


im = cv2.imread(image)
for i in range(100):
    start_time = time.time()
    result = model.predict(im)
    end_time = time.time()
    print("time cost:", float(end_time - start_time) * 1000.0, "ms")

# 预测结果可视化
vis_im = fd.vision.vis_detection(im, result, score_threshold=0.5)



cv2.imwrite("visualized_result.jpg", vis_im)
print("Visualized result save in ./visualized_result.jpg")`

**Comment by universea** [comment]
> Hi, 你好，麻烦提供一下具体的测试代码我们分析下

`import fastdeploy as fd
import cv2
import os
from fastdeploy import ModelFormat
import time


def parse_arguments():
    import argparse
    import ast
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--model", default=None, help="Path of yolov7 onnx model.")
    parser.add_argument(
        "--image", default=None, help="Path of test image file.")
    parser.add_argument(
        "--device",
        type=str,
        default='cpu',
        help="Type of inference device, support 'cpu' or 'gpu'.")
    parser.add_argument(
        "--use_trt",
        type=ast.literal_eval,
        default=False,
        help="Wether to use tensorrt.")
    return parser.parse_args()


def build_option(args):
    option = fd.RuntimeOption()

    if args.device.lower() == "gpu":
        option.use_gpu()

    if args.use_trt:
        option.use_trt_backend()
        option.set_trt_input_shape("images", [1, 3, 640, 640])
    return option


args = parse_arguments()

if args.model is None:
    model = fd.download_model(name='YOLOv7')
else:
    model = args.model

runtime_option = build_option(args)
model = fd.vision.detection.YOLOv7(model, runtime_option=runtime_option)

if args.image is None:
    image = fd.utils.get_detection_test_image()
else:
    image = args.image


im = cv2.imread(image)
for i in range(100):
    start_time = time.time()
    result = model.predict(im)
    end_time = time.time()
    print("time cost:", float(end_time - start_time) * 1000.0, "ms")


vis_im = fd.vision.vis_detection(im, result, score_threshold=0.5)



cv2.imwrite("visualized_result.jpg", vis_im)
print("Visualized result save in ./visualized_result.jpg")`

**Comment by wjj19950828** [comment]
@universea 用的FD什么版本呢，然后环境是跑在cpu还是gpu上呢，确认下环境是否有其他进程再跑，导致占用cpu资源

**Comment by wjj19950828** [comment]
@universea 使用下最新版本FastDeploy(1.0.2)或者nightly build版本，以及确认下目前gpu卡的状态

使用ONNXRuntime GPU后端，使用上面相同脚本，我这边测试都在同一个耗时，没有越来越慢
<img width="355" alt="image" src="https://user-images.githubusercontent.com/19977378/212594545-f6a0ada6-981b-4034-9b88-f077ed01de40.png">

**Comment by universea** [comment]
> @universea 使用下最新版本FastDeploy(1.0.2)或者nightly build版本，以及确认下目前gpu卡的状态
> 
> 使用ONNXRuntime GPU后端，使用上面相同脚本，我这边测试都在同一个耗时，没有越来越慢 <img alt="image" width="355" src="https://user-images.githubusercontent.com/19977378/212594545-f6a0ada6-981b-4034-9b88-f077ed01de40.png">

好的，我再试试，谢谢啦！

**Comment by DefTruth** [comment]
可以看下电脑是否设置了电池为省电模式或平衡模式

**Comment by jiangjiajun** [comment]
此ISSUE由于一年未更新，将会关闭处理，如有需要，可再次更新打开。
