### ISSUE TITLE
fastdeploy使用nuitka打包后无法运行

### ISSUE THREAD

**Issue by Hr-Song** [PaddlePaddle/FastDeploy#1135]
nuitka打包命令 nuitka demo.py --mingw64 --standalone
打包后报错为
![b2ceea8934d1020e31511d3bb60e8b7](https://user-images.githubusercontent.com/48303845/212227349-64d8563a-acee-461a-8632-7b08704a290a.png)

**Comment by Hr-Song** [comment]
pyinstaller打包后也是同样的报错

**Comment by chenqianhe** [comment]
试试 QPT ？
https://github.com/QPT-Family/QPT

**Comment by chenqianhe** [comment]
> nuitka打包命令 nuitka demo.py --mingw64 --standalone 打包后报错为 ![b2ceea8934d1020e31511d3bb60e8b7](https://user-images.githubusercontent.com/48303845/212227349-64d8563a-acee-461a-8632-7b08704a290a.png)

我个人经验来看，很可能是有什么包没打包进去导致找不到对应的文件了

最好是让打包后运行时要正常输出log，这样好查看问题

**Comment by Hr-Song** [comment]
使用qpt打包后解决问题，需要使用 SubModule 添加fastdeploy的whl

**Comment by chenqianhe** [comment]
> 使用qpt打包后解决问题，需要使用 SubModule 添加fastdeploy的whl

缺模块的话，pyinstaller 应该是得手动复制过去，也是可以解决

能打包了就好

**Comment by cuinfo** [comment]
我也出现相同的错误，原因是：\fastdeploy\libs\third_libs\openvino 下的dll 库无法加载导致的，复制或者添加对应路径即可

**Comment by yangf11** [comment]
> 使用qpt打包后解决问题，需要使用 SubModule 添加fastdeploy的whl

请问一下我遇到了一个问题就就是qpt打包成功了fastdeploy 但是只能用管理员模式运行 普通模型下打开会秒关，请问你是否遇到了这个问题

**Comment by yangf11** [comment]
> 

能详细描述一下如何复制或者添加对应路径从而成功打包的吗

**Comment by chenqianhe** [comment]
> > 
> 
> 能详细描述一下如何复制或者添加对应路径从而成功打包的吗

可以直接去 qpt 看看或者问下他们 issue

**Comment by zachary-zheng** [comment]
直接copy   ...\site-packages\fastdeploy\libs  libs文件夹到打包目录的fastdeploy内替换即可！
