### ISSUE TITLE
yolov8

### ISSUE THREAD

**Issue by sl00001** [PaddlePaddle/FastDeploy#1138]
yolov8 有支持计划吗

**Comment by jiangjiajun** [comment]
正在支持，预计会在下周发布

**Comment by wjj19950828** [comment]
@sl00001  您好，目前代码已经合入，使用如下api，欢迎试用~

```python
model = fd.vision.detection.YOLOv8(args.model, runtime_option=runtime_option)
```

更多后端选项参考代码 [yolov8 demo](https://github.com/PaddlePaddle/FastDeploy/blob/develop/examples/vision/detection/yolov8/python/infer.py)

**Comment by jiangjiajun** [comment]
此ISSUE由于一年未更新，将会关闭处理，如有需要，可再次更新打开。
