### ISSUE TITLE
picodet模型,.onnx模型转.rknn时报错ValueError: Unknow elem_type for multiclass_nms3_0.tmp_0!

### ISSUE THREAD

**Issue by chenzhizui** [PaddlePaddle/FastDeploy#1140]
根据官网教程安装了rknntoolkit环境，对picodet模型转成onnx格式以后，继续用export.py转rknn的过程中报如下错误：
{'mean': [[128.5, 128.5, 128.5]], 'std': [[128.5, 128.5, 128.5]], 'model_path': './picodet_s_416_coco_lcnet/picodet_s_416_coco_lcnet.onnx', 'outputs_nodes': None, 'do_quantization': False, 'output_folder': './picodet_s_416_coco_lcnet_infer', 'target_platform': 'RK3588'}
W __init__: rknn-toolkit2 version: 1.4.0-22dcfef4
W load_onnx: It is recommended onnx opset 12, but your onnx model opset is 11!
E load_onnx: Unknow elem_type for multiclass_nms3_0.tmp_0!
W load_onnx: ===================== WARN(2) =====================
E rknn-toolkit2 version: 1.4.0-22dcfef4
E load_onnx: Catch exception when loading onnx model: /FastDeploy/tools/rknpu2/picodet_s_416_coco_lcnet/picodet_s_416_coco_lcnet.onnx!
E load_onnx: Traceback (most recent call last):
E load_onnx:   File "rknn/api/rknn_base.py", line 1152, in rknn.api.rknn_base.RKNNBase.load_onnx
E load_onnx:   File "rknn/api/rknn_base.py", line 575, in rknn.api.rknn_base.RKNNBase._create_ir_and_inputs_meta
E load_onnx:   File "rknn/api/ir_graph.py", line 44, in rknn.api.ir_graph.IRGraph.__init__
E load_onnx:   File "rknn/api/ir_graph.py", line 380, in rknn.api.ir_graph.IRGraph.rebuild
E load_onnx:   File "rknn/api/rknn_log.py", line 113, in rknn.api.rknn_log.RKNNLog.e
E load_onnx: ValueError: Unknow elem_type for multiclass_nms3_0.tmp_0!
Traceback (most recent call last):
  File "export.py", line 47, in <module>
    assert ret == 0, "Load model failed!"
AssertionError: Load model failed!
请问是因为什么原因导致？

**Comment by jiangjiajun** [comment]
https://github.com/PaddlePaddle/FastDeploy/tree/release/1.0.2/examples/vision/detection/paddledetection/rknpu2  参考下这里的文档，在导出模型时，不能包含NMS

**Comment by chenzhizui** [comment]
> https://github.com/PaddlePaddle/FastDeploy/tree/release/1.0.2/examples/vision/detection/paddledetection/rknpu2 参考下这里的文档，在导出模型时，不能包含NMS

请问export.nms=True这个参数在哪个脚本里面设置？

**Comment by Zheng-Bicheng** [comment]
> > https://github.com/PaddlePaddle/FastDeploy/tree/release/1.0.2/examples/vision/detection/paddledetection/rknpu2 参考下这里的文档，在导出模型时，不能包含NMS
> 
> 请问export.nms=True这个参数在哪个脚本里面设置？

在PaddleDetection导出模型的时候设置,详情参考[picodet模型文档](https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.4/configs/picodet)

**Comment by Zheng-Bicheng** [comment]
解决掉这个问题了吗

**Comment by chenzhizui** [comment]
> 解决掉这个问题了吗

没有 能否提供一份测试通过的转换说明？

**Comment by Zheng-Bicheng** [comment]
看一下`examples/vision/detection/paddledetection/rknpu2/picodet.md`这个文档

**Comment by chenzhizui** [comment]
> 看一下`examples/vision/detection/paddledetection/rknpu2/picodet.md`这个文档

就是根据这个文档转报错的

**Comment by Zheng-Bicheng** [comment]
这个文档进行了更新，你重新看下develop版本的

**Comment by Zheng-Bicheng** [comment]
解决了吗

**Comment by Zheng-Bicheng** [comment]
导出节点改成导出至dev节点的上一个mul节点对部署更友好一点

**Comment by Zheng-Bicheng** [comment]
您好，我们重新更新了一个版本的导出config,您可以再测试一下，这次不需要您从头写yaml了。pull develoop分支下来再试试
