### ISSUE TITLE
ocr部署中文乱码问题

### ISSUE THREAD

**Issue by GreenAvocado92** [PaddlePaddle/FastDeploy#1142]
win11 + vs2019 + c++
部署ocr时，识别到的中文为乱码，模型由官网下载

**Comment by jiangjiajun** [comment]
这个问题多为编码问题。  模型识别本身不会有中英文（都是生成数字id）， 唯一涉及到数字转换为中文的地方，是传入的字典文件。可以自行检查下编码的配置

**Comment by GreenAvocado92** [comment]
![image](https://user-images.githubusercontent.com/91200482/212587708-90a4be5c-2881-408e-9640-acaf039df663.png)我修改了dict.txt的编码格式，然后用vs单独建立了一个工程运行此段代码，输出是正常的，但是直接调用fastdeploy还是乱码，您说的这个编码格式是哪一块的格式呢

**Comment by yunyaoXYY** [comment]
> ![image](https://user-images.githubusercontent.com/91200482/212587708-90a4be5c-2881-408e-9640-acaf039df663.png)我修改了dict.txt的编码格式，然后用vs单独建立了一个工程运行此段代码，输出是正常的，但是直接调用fastdeploy还是乱码，您说的这个编码格式是哪一块的格式呢

你好，可以试试修改vs2019的编码格式, 看看怎么让终端输出不乱码

**Comment by GreenAvocado92** [comment]
> 
我单独建立一个工程，是可以正常输出的，但是直接用fastdepoly编译好的API，还是乱码，

**Comment by GreenAvocado92** [comment]
搞定了，各种修改，也不知道哪个起作用了，多谢各位大佬指点

**Comment by jiangjiajun** [comment]
此ISSUE由于一年未更新，将会关闭处理，如有需要，可再次更新打开。
