### ISSUE TITLE
RKNUP2部署RKYOLO模型时出现的AttributeError: module 'fastdeploy.vision.detection' has no attribute 'RKYOLOV5'问题!

### ISSUE THREAD

**Issue by MrMzl** [PaddlePaddle/FastDeploy#1149]
## 环境

- 【FastDeploy版本】： git clone https://github.com/PaddlePaddle/FastDeploy.git
- 【系统平台】: Linux firefly 4.19.219 aarch64 GNU/Linux (Ubuntu20.04.3)
- 【硬件】： AIO-3568J开发板
- 【编译语言】： Python 3.8.10

## 问题日志及出现问题的操作流程
- 附上详细的问题日志有助于快速定位分析
- 【运行日志】
- 运行/FastDeploy/examples/vision/detection/rkyolo/python目录下面的infer脚本文件提示下面错误,运行代码为python3 infer.py --model_file ./model --image 000000014439.jpg,模型文件为从rk官方仓库中提供的rknn格式模型(https://eyun.baidu.com/enterprise/share/init?cid=8272257679089781337&uk=2751701137&sid=202211118572878233).
- Log:
![image](https://user-images.githubusercontent.com/85120075/212519875-63edc2c4-0218-4e2c-a47c-d6186f7cbc5c.png)
- model_file:
![image](https://user-images.githubusercontent.com/85120075/212519895-3e0f6642-4c4f-4c13-b544-4da3a979c733.png)

**Comment by MrMzl** [comment]
![image](https://user-images.githubusercontent.com/85120075/212519981-e7213f1e-3d79-4a78-b4fd-9b7f8a231c67.png)

**Comment by Zheng-Bicheng** [comment]
我复现一下

**Comment by Zheng-Bicheng** [comment]
@MrMzl 你用的是哪个版本的fastdeploy我这边没有这个问题呀

**Comment by Zheng-Bicheng** [comment]
你安装的是哪个python包呀，356X的python目前编译好像还有点问题，编译起来很慢

**Comment by MrMzl** [comment]
> @MrMzl 你用的是哪个版本的fastdeploy我这边没有这个问题呀

![image](https://user-images.githubusercontent.com/85120075/212598362-9863c15e-89cc-46ff-9640-3e1a023720dd.png)

**Comment by Zheng-Bicheng** [comment]
> > @MrMzl 你用的是哪个版本的fastdeploy我这边没有这个问题呀
> 
> ![image](https://user-images.githubusercontent.com/85120075/212598362-9863c15e-89cc-46ff-9640-3e1a023720dd.png)

你这个包哪里下的

**Comment by MrMzl** [comment]
> > > @MrMzl 你用的是哪个版本的fastdeploy我这边没有这个问题呀
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/85120075/212598362-9863c15e-89cc-46ff-9640-3e1a023720dd.png)
> 
> 你这个包哪里下的
这个应该是下载的预编译库
https://github.com/PaddlePaddle/FastDeploy/blob/develop/docs/cn/build_and_install/download_prebuilt_libraries.md
pip install fastdeploy-python==1.0.0 -f https://www.paddlepaddle.org.cn/whl/fastdeploy_nightly_build.html
这块的版本是我指定的.
RK板端开发环境是按照下面的流程实现的，这个环境需要一次搭建好就可以，还是我更新fastdeploy官方仓库提供的branches后也需要重新操作。
https://github.com/PaddlePaddle/FastDeploy/blob/develop/docs/cn/faq/rknpu2/environment.md

**Comment by Zheng-Bicheng** [comment]
> > > @MrMzl 你用的是哪个版本的fastdeploy我这边没有这个问题呀
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/85120075/212598362-9863c15e-89cc-46ff-9640-3e1a023720dd.png)
> 
> 你这个包哪里下的 这个应该是下载的预编译库 https://github.com/PaddlePaddle/FastDeploy/blob/develop/docs/cn/build_and_install/download_prebuilt_libraries.md pip install fastdeploy-python==1.0.0 -f https://www.paddlepaddle.org.cn/whl/fastdeploy_nightly_build.html 这块的版本是我指定的. RK板端开发环境是按照下面的流程实现的，这个环境需要一次搭建好就可以，还是我更新fastdeploy官方仓库提供的branches后也需要重新操作。 https://github.com/PaddlePaddle/FastDeploy/blob/develop/docs/cn/faq/rknpu2/environment.md

rknpu版本的FastDeploy没有提供预编译库，需要你自己在板端编译，目前rk3568只测试过c++，python可能还有点问题

**Comment by Zheng-Bicheng** [comment]
如果你想要用交叉编译，切换到develop版本，根据`docs/cn/faq/rknpu2/build.md`交叉编译
