### ISSUE TITLE
PaddleX模型Predict崩溃

### ISSUE THREAD

**Issue by nOObVs** [PaddlePaddle/FastDeploy#1151]
*********************************************
温馨提示：根据社区不完全统计，按照模板提问，可以加快回复和解决问题的速度
*********************************************

## 环境

- 【FastDeploy版本】： fastdeploy-win-x64-1.0.2
- 【编译命令】: 未编译
- 【系统平台】: Windows x64(Windows10)
- 【硬件】： 有3080，但是使用option.UseCpu(); option.UseOpenVINOBackend();
- 【编译语言】： 未编译

## 问题日志及出现问题的操作流程
- 附上详细的问题日志有助于快速定位分析
- 【模型跑不同】
-   使用`examples`下的部署示例的代码，调用paddleX导出基于PPLCNet训练后的分类模型。模型能正常加载，但是到了Predict直接崩溃。代码如下：
void CpuInfer(const std::string& model_dir, const std::string& image_file) {
    auto model_file = model_dir + "model.pdmodel";
    auto params_file = model_dir + "model.pdiparams";
    auto config_file = model_dir + "model.yml";

    cv::Mat im = cv::imread(image_file);
    
    std::vector<int64_t> vec = {1, im.channels() ,im.size().height ,im.size().width };
    const std::map<std::string, std::vector<int64_t>> imMap = { {"image",vec} };

    auto option = fastdeploy::RuntimeOption();
    option.UseCpu();
    option.UseOpenVINOBackend();
    option.SetOpenVINODevice("CPU");
    option.SetOpenVINOShapeInfo(imMap);
    auto model = fastdeploy::vision::classification::PaddleClasModel(
        model_file, params_file, config_file, option);
    if (!model.Initialized()) {
        std::cerr << "Failed to initialize." << std::endl;
        return;
    }

    fastdeploy::vision::ClassifyResult res;
    if (!model.Predict(im, &res)) {
        std::cerr << "Failed to predict." << std::endl;
        return;
    }

    // print res
    std::cout << res.Str() << std::endl;
}

[即使注释了option的配置代码，Predict还是会崩溃。图像是3通道，尺寸512，512.

**Comment by nOObVs** [comment]
![test](https://user-images.githubusercontent.com/65331912/212540352-1d5f2cf5-cb33-4047-8f0f-067b9c14bdd2.png)
这是原图，是从训练集里面拷贝出来做测试的

报错的图示如下：
![7e322b34140a6bca0e4c52768363c06](https://user-images.githubusercontent.com/65331912/212540465-32407909-84a6-4d59-975b-cd0f75bd7ce1.jpg)

当切换paddle的后端，这次至少有崩溃信息打印，看意思说是输入的通道是512？
<img width="1042" alt="2dd1e985a973bfd0c1dacae09499570" src="https://user-images.githubusercontent.com/65331912/212541739-b2960df5-ef64-4190-97a8-efde33946332.png">

**Comment by nOObVs** [comment]
[P0002-T0005_export_model.zip](https://github.com/PaddlePaddle/FastDeploy/files/10421657/P0002-T0005_export_model.zip)

此为PaddleX客户端导出的模型

![image](https://user-images.githubusercontent.com/65331912/212576160-ea267426-a523-45b7-88da-8d72118a87de.png)

**Comment by jiangjiajun** [comment]
PaddleX导出的模型yaml文件还没有支持，你可以参考examples/vision/classificaiton/paddleclas里面的示例，使用PaddleClas的yaml文件

**Comment by nOObVs** [comment]
> Collaborator

您好，我没找到您说的这个文件。子目录（D:\Paddle\fastdeploy-win-x64-1.0.2\examples\vision\classification\paddleclas\serving\models\preprocess\1\inference_cls.yaml）里面有看到一个，需要更改内容吗？
![image](https://user-images.githubusercontent.com/65331912/212599369-34b3d735-2d0d-4ec3-b031-c3320173c258.png)


您好，我把上述子目录内的inference_cls.yaml引用进去替代了model.yml，能跑通了，虽然预测的结果不对......谢谢。但是这个问题，很容易劝退我这种新手呀，哈哈哈哈。

**Comment by jiangjiajun** [comment]
因为目前还并没有支持PaddleX的模型，这部分工作我们有同事正在做，但还没release出来

**Comment by jiangjiajun** [comment]
此ISSUE由于一年未更新，将会关闭处理，如有需要，可再次更新打开。
