### ISSUE TITLE
服务化部署：PP-Matting Python Deployment 如何获取抠图的透明背景图

### ISSUE THREAD

**Issue by liuziyingbeidou** [PaddlePaddle/FastDeploy#1154]
*********************************************
温馨提示：根据社区不完全统计，按照模板提问，可以加快回复和解决问题的速度
*********************************************

## 环境

- 【FastDeploy版本】： 说明具体的版本，cpu： fastdeploy-python  1.0.2
- 【编译命令】pip
- 【系统平台】: Windows x64(Windows10) 
- 【硬件】： 
- 【编译语言】： Python(3.9）

## 问题日志及出现问题的操作流程
- 附上详细的问题日志有助于快速定位分析
    模型：
    [pp-matting-hrnet_w18-human_512](https://bj.bcebos.com/paddlehub/fastdeploy/PP-Matting-512.tgz)
   代码：
    [client.py 和 serving.py 参考](https://github.com/PaddlePaddle/FastDeploy/tree/develop/examples/vision/detection/paddledetection/python/serving)

![image](https://user-images.githubusercontent.com/13762699/212601523-37929cfa-ec47-43c5-9683-5a5bc44923d3.png)

**Comment by felixhjh** [comment]
您可以调用这个接口对背景图片进行替换
vis_im_with_bg = fd.vision.swap_background(im, transparent_img, result)
```
# 替换黑色背景
import numpy as np
img_height, img_width = 300, 300
n_channels = 3
black_img = np.zeros((img_height, img_width, n_channels), dtype=np.uint8)
vis_im_with_bg = fd.vision.swap_background(im, black_img, result)
```
可以参考这个示例 
https://github.com/PaddlePaddle/FastDeploy/blob/develop/examples/vision/matting/ppmatting/python/infer.py#L65
但是现在swap_background接口 并不支持四通道的背景图片，因此透明背景图片暂时不支持
如果需要支持四通道背景图片的话，可以自行修改swap_background接口增加对alpha通道的支持，然后编译安装FastDeploy
可视化接口：https://github.com/PaddlePaddle/FastDeploy/blob/develop/fastdeploy/vision/visualize/swap_background.cc#L24
编译文档：https://github.com/PaddlePaddle/FastDeploy/tree/develop/docs/cn/build_and_install

**Comment by liuziyingbeidou** [comment]
好的，谢谢；怎么把前景图替换成白色；生成mask呢

**Comment by felixhjh** [comment]
> 好的，谢谢；怎么把前景图替换成白色；生成mask呢

```
# 替换白色背景
import numpy as np
img_height, img_width = 300, 300
n_channels = 3
white_img = np.zeros((img_height, img_width, n_channels), dtype=np.uint8) + 255
vis_im_with_bg = fd.vision.swap_background(im, white_img, result)
```

**Comment by felixhjh** [comment]
> 好的，谢谢；怎么把前景图替换成白色；生成mask呢

mask就是模型返回的结果，你可以根据结果自己生成相应的前景为白色，背景是黑色的图片
具体返回的返回结构体可以参考这个文档
https://www.paddlepaddle.org.cn/fastdeploy-api-doc/python/html/vision_results_en.html

**Comment by liuziyingbeidou** [comment]
好的 我看下
