### ISSUE TITLE
fastdeploy::vision::VisSegmentation如何使用自定义颜色

### ISSUE THREAD

**Issue by yueyue0574** [PaddlePaddle/FastDeploy#1155]
fastdeploy::vision::SegmentationResult获得的结果用fastdeploy::vision::VisSegmentation显示，如果我需要自定义颜色该如何处理？或者过滤掉SegmentationResult中的某些类，剩下的类进行着色

**Comment by felixhjh** [comment]
> fastdeploy::vision::SegmentationResult获得的结果用fastdeploy::vision::VisSegmentation显示，如果我需要自定义颜色该如何处理？或者过滤掉SegmentationResult中的某些类，剩下的类进行着色

https://github.com/PaddlePaddle/FastDeploy/blob/develop/fastdeploy/vision/visualize/segmentation.cc#L27
暂时不支持自定义颜色，可以看下这个函数，这里的color_map替换成你想要的颜色，重新编译安装下FastDeploy就可以了

**Comment by yueyue0574** [comment]
> > fastdeploy::vision::SegmentationResult获得的结果用fastdeploy::vision::VisSegmentation显示，如果我需要自定义颜色该如何处理？或者过滤掉SegmentationResult中的某些类，剩下的类进行着色
> 
> https://github.com/PaddlePaddle/FastDeploy/blob/develop/fastdeploy/vision/visualize/segmentation.cc#L27 暂时不支持自定义颜色，可以看下这个函数，这里的color_map替换成你想要的颜色，重新编译安装下FastDeploy就可以了

感谢
