### ISSUE TITLE
FastDeploy Streamer支持并行多模型吗？

### ISSUE THREAD

**Issue by eyu11** [PaddlePaddle/FastDeploy#1157]
Supporting parallel multiple models inferencing in one pipeline

**Comment by wang-xinyu** [comment]
具体是什么样的多模型，能展开讲讲吗？

**Comment by eyu11** [comment]
这是在deepstream6.1出来的新一个特性，就是在一个pipline能够针对不同视频源设置多个并行的模型推理，如下图示例







饿鱼
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/FastDeploy"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年1月17日(星期二) 上午10:15
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/FastDeploy] FastDeploy Streamer支持并行多模型吗？ (Issue #1157)





 
具体是什么样的多模型，能展开讲讲吗？

**Comment by wang-xinyu** [comment]
@eyu11 deepstream支持的我们都可以支持，因为是FastDeploy Streamer是它之上的框架，只是目前还没有这样的demo，可以参考这个配置文件指南来实现 https://github.com/PaddlePaddle/FastDeploy/blob/develop/streamer/docs/cn/yaml_config.md

**Comment by jiangjiajun** [comment]
此ISSUE由于一年未更新，将会关闭处理，如有需要，可再次更新打开。
