### ISSUE TITLE
基于现有的接口，如何得到透明背景的方案呢，请指点迷津

### ISSUE THREAD

**Issue by liuziyingbeidou** [PaddlePaddle/FastDeploy#1159]
*********************************************
温馨提示：根据社区不完全统计，按照模板提问，可以加快回复和解决问题的速度
*********************************************

## 环境

- 【FastDeploy版本】： fastdeploy-python             1.0.2
- 【编译命令】pip
- 【系统平台】: Windows x64(Windows10)
- 【硬件】： 
- 【编译语言】： Python(3.9）

或者多个模型协作完成
谢谢！

**Comment by felixhjh** [comment]
已支持，参照如上PR，调用相应接口即可
