### ISSUE TITLE
Can you update new release  

### ISSUE THREAD

**Issue by soham24** [PaddlePaddle/FastDeploy#1166]
There has been lot of update to codebase, it will be great if you release new build
thanks

**Comment by jiangjiajun** [comment]
@soham24 We are going to release 1.0.3 this week. And if you want to use the latest code, we provided daily build version here https://github.com/PaddlePaddle/FastDeploy/blob/develop/docs/en/build_and_install/download_prebuilt_libraries.md

**Comment by soham24** [comment]
@jiangjiajun thanks
