### ISSUE TITLE
请问现在支持从内存中加载模型吗

### ISSUE THREAD

**Issue by hujiongqazqq** [PaddlePaddle/FastDeploy#1174]

**Comment by leiqing1** [comment]
@hujiongqazqq 现在支持用Paddle Inference作为后端从内存加载模型，其他后端正在修改pr，待合入。
可以参考API文档中 set_model_buffer这个API使用。set_model_buffer()传入内存中的byte流文件，然后调用predict的时候就传入空文件名。春节后会把PR链到这个 issue下，请关注。

**Comment by monkeycc** [comment]
主要还是模型加密问题

**Comment by heliqi** [comment]
> 主要还是模型加密问题

@monkeycc  模型加密功能我们也正在同步支持中

**Comment by felixhjh** [comment]
已支持，参照链接PR
