### ISSUE TITLE
希望fastdeploy提供java调用的demo

### ISSUE THREAD

**Issue by truthsun22** [PaddlePaddle/FastDeploy#1179]
因为公司的项目基本都是java，想把fastdeploy结合到java项目中，注！不是android。谢谢

**Comment by DefTruth** [comment]
@truthsun22 请问是非android的什么系统呢？

**Comment by truthsun22** [comment]
> 

就是普通的纯java的项目。纯java如何调用fastdeploy

**Comment by DefTruth** [comment]
目前java的api只适配了android系统，纯java的api正在规划中，你们一般是用于什么场景呢？主要是调用已经集成好的模型，还是说希望使用runtime的java版本api呢？

**Comment by truthsun22** [comment]
> 目前java的api只适配了android系统，纯java的api正在规划中，你们一般是用于什么场景呢？主要是调用已经集成好的模型，还是说希望使用runtime的java版本api呢？

调用已集成好的模型，包括前后处理示例代码即可，其实就是把android的相关API，稍作修改可以适配到纯java就可以。无论什么场景，打个比方，pphuman是用python代码编写的垂类业务场景，我们想用java去替代python实现业务逻辑

**Comment by chenqianhe** [comment]
用 JNI 或 JNA 不可以吗

**Comment by jiangjiajun** [comment]
此ISSUE由于一年未更新，将会关闭处理，如有需要，可再次更新打开。
