### ISSUE TITLE
model.predict希望加入其它参数

### ISSUE THREAD

**Issue by truthsun22** [PaddlePaddle/FastDeploy#1180]
比如置信度，类别名等参数，目前置信度信息等都是通过配置文件读取进去的，不太灵活，结合到自己项目中如果想更改置信度等参数，只能重新生成参数文件

**Comment by DefTruth** [comment]
@truthsun22 请问您用的具体是什么模型呢？需要配置该模型的哪些参数？

**Comment by truthsun22** [comment]
> @truthsun22 请问您用的具体是什么模型呢？需要配置该模型的哪些参数？

比如ppyoloe模型，model = fd.vision.detection.PPYOLOE(model_file, params_file, config_file, runtime_option=runtime_option)
推理时就一个参数，model.predict(im)
结合到业务系统的时候，灵活传参最好，比如传入置信度，这比从配置文件读取要方便一些
还有就是可视化函数也封装的比较死，不太灵活。当然我可以自己写，但是希望提供官方python代码，这样可以学习一下，谢谢

**Comment by jiangjiajun** [comment]
此ISSUE由于一年未更新，将会关闭处理，如有需要，可再次更新打开。
