### ISSUE TITLE
服务化部署客户端安装tritionclient和opencv失败

### ISSUE THREAD

**Issue by cunjing56** [PaddlePaddle/FastDeploy#1181]
*********************************************
温馨提示：根据社区不完全统计，按照模板提问，可以加快回复和解决问题的速度
*********************************************
服务化部署案例
https://github.com/PaddlePaddle/FastDeploy/blob/develop/examples/vision/detection/paddledetection/serving/README.md
## 环境

- 【FastDeploy版本】： 说明具体的版本，如fastdeploy-linux-gpu-0.8.0
- 【系统平台】: Linux x64(Ubuntu 18.04) 
- 【硬件】： 说明具体硬件型号，如 Nvidia GPU 3080TI， CUDA 11.2 CUDNN 8.3
- 【编译语言】： Python(3.7）

部署两个客户端，一个是ubuntu18, 一个是ubuntu18内的python容器
ubuntu18 安装tritionclient失败，一遍遍的增加依赖，最后在abc停住了
![image](https://user-images.githubusercontent.com/112528302/215305004-bbd8b250-bf09-425f-86e3-5ba74382bd6f.png)

python容器安装opencv失败
![image](https://user-images.githubusercontent.com/112528302/215304999-791cfe2e-ae49-433d-b3f6-a8b8194c2d3f.png)

请问如何解决啊？

**Comment by heliqi** [comment]
Ubuntu安装tritonclient时尝试指定版本:
```
python3 -m pip install tritonclient[all]==2.10.0
```
你的报错看起来是安装aiohttp报错，你也可以不是用缓存直接安装试试:
```
python3 -m pip install -U multidict
python3 -m pip --no-cache-dir install aiohttp
```

**Comment by cunjing56** [comment]
> Ubuntu安装tritonclient时尝试指定版本:
> 
> ```
> python3 -m pip install tritonclient[all]==2.10.0
> ```
> 
> 你的报错看起来是安装aiohttp报错，你也可以不是用缓存直接安装试试:
> 
> ```
> python3 -m pip install -U multidict
> python3 -m pip --no-cache-dir install aiohttp
> ```
感谢回复！tritonclient指定版本就好了!
