### ISSUE TITLE
服务化部署客户端如何发送多个图片请求？

### ISSUE THREAD

**Issue by cunjing56** [PaddlePaddle/FastDeploy#1182]
参考部署文档
https://github.com/PaddlePaddle/FastDeploy/blob/develop/examples/vision/detection/paddledetection/serving/README_CN.md
请问如何发送多个图片请求？有没有可能实现切图、拼图处理？
![image](https://user-images.githubusercontent.com/112528302/215308091-349c2350-37e2-490c-a470-32553e89700c.png)

**Comment by heliqi** [comment]
想要发送多张图片，可以这样修改serving目录中的`[paddledet_grpc_client.py](https://github.com/PaddlePaddle/FastDeploy/blob/develop/examples/vision/detection/paddledetection/serving/paddledet_grpc_client.py)`:
```
    im1 = cv2.imread("xxx")
    im2 = cv2.imread("xxx2")
    im = np.array([im1, im2])
    result = runner.Run([im, ])
```
ps: py中的注释有提示batch输入是 im = np.array([im1, im2, im3])

**Comment by cunjing56** [comment]
> 想要发送多张图片，可以这样修改serving目录中的`[paddledet_grpc_client.py](https://github.com/PaddlePaddle/FastDeploy/blob/develop/examples/vision/detection/paddledetection/serving/paddledet_grpc_client.py)`:
> 
> ```
>     im1 = cv2.imread("xxx")
>     im2 = cv2.imread("xxx2")
>     im = np.array([im1, im2])
>     result = runner.Run([im, ])
> ```
> 
> ps: py中的注释有提示batch输入是 im = np.array([im1, im2, im3])

哦哦
请问这个结果是box框吗？score值在哪里？我想实现服务化部署的切图、预测、拼图，我看ppdet的infer拼图需要score
![image](https://user-images.githubusercontent.com/112528302/215414679-c6f5f59d-f42b-4856-93bf-afe70a420978.png)
![image](https://user-images.githubusercontent.com/112528302/215417157-69ec6a19-5983-4b7d-b4d4-289f3584baf2.png)

**Comment by heliqi** [comment]
返回的value有多种值，打印时只打印了boxes: https://github.com/PaddlePaddle/FastDeploy/blob/8c651f95088f66b9fefabdc2aa17d47b56a97e00/examples/vision/detection/paddledetection/serving/paddledet_grpc_client.py#L109

想获取scores只需要使用 value['scores']即可
-----分割线------------
检测任务的结果数据结构可以看这个文档:
https://baidu-paddle.github.io/fastdeploy-api/python/html/vision_results_en.html#detectionresult

![image](https://user-images.githubusercontent.com/34152981/215418531-572db243-7348-4ec9-acbf-b902a074e638.png)

**Comment by sniperking1234** [comment]
@heliqi 请问如果图片大小不一样的话，只能一张张地检测吗
