### ISSUE TITLE
带参数接口的客户端程序

### ISSUE THREAD

**Issue by cunjing56** [PaddlePaddle/FastDeploy#1185]
参考
https://github.com/PaddlePaddle/FastDeploy/blob/develop/examples/vision/detection/paddledetection/serving/README.md

客户端程序paddledet_grpc_client.py，现想让图片路径与请求服务地址变成显示参数，参考slice_image的参数写法
![image](https://user-images.githubusercontent.com/112528302/215318456-be2042c9-7e39-4a70-ad43-12e600230db7.png)

客户端执行的时候报错
![image](https://user-images.githubusercontent.com/112528302/215318475-9adf9d9f-8c1d-4f18-ab2f-e67155498626.png)

请问是什么问题呢？

**Comment by heliqi** [comment]
你删除掉第96行试试？

**Comment by cunjing56** [comment]
> 你删除掉第96行试试？

成功！！！！
