### ISSUE TITLE
FastDeploy 服务化部署 为什么不用 Paddle Serving

### ISSUE THREAD

**Issue by monkeycc** [PaddlePaddle/FastDeploy#1191]
FastDeploy 服务化部署 
为什么不用 [Paddle Serving](https://github.com/PaddlePaddle/Serving)
而要使用 [Triton Inference Server](https://github.com/triton-inference-server/server)

**Comment by jiangjiajun** [comment]
PaddleServing 目前还只支持Paddle Inference作为后端，不能支持其它后端。因此当前集成的是Triton，Paddle Serving我们会根据其后续的迭代开发再集成。
