### ISSUE TITLE
silero-vad 在 Linux x64 推理时结果异常

### ISSUE THREAD

**Issue by chenqianhe** [PaddlePaddle/FastDeploy#1193]
*********************************************
温馨提示：根据社区不完全统计，按照模板提问，可以加快回复和解决问题的速度
*********************************************

## 环境

- 【FastDeploy版本】： https://github.com/PaddlePaddle/FastDeploy/tree/09d8e0f19ab52f368533c1a2591d5ff9d50f493e
- 【编译命令】cmake .. -DENABLE_ORT_BACKEND=ON -DCMAKE_INSTALL_PREFIX=${PWD}/compiled_fastdeploy_sdk
- 【系统平台】: Linux x64(Ubuntu 20.04)
- 【编译语言】： C++ 

## 问题日志及出现问题的操作流程

cpp 测试代码见 https://github.com/PaddlePaddle/FastDeploy/tree/develop/examples/audio/silero-vad

实际使用代码见 https://github.com/chenqianhe/VAD-addon

![](https://user-images.githubusercontent.com/54462604/213858784-6e8f0806-cd7f-4000-b10e-3a6ede642b4e.png)

![581675081775_ pic](https://user-images.githubusercontent.com/54462604/215477271-206f31a1-1fe6-4a28-847d-2678cd4083ea.jpg)

**Comment by jiangjiajun** [comment]
分析代码后发现，如下的`Preprocess`存在将局部变量内存返回函数外使用的问题，因此会带来随机数据影响结果（不同操作系统表现形式可能不同）
其中如下代码中，采用了函数传值，`audioWindowsData`为函数内的局部变量，而Tensor调用了`SetExternalData`去共享局部变量的内存
https://github.com/PaddlePaddle/FastDeploy/blob/1427d5d29a0a5cc0fab2c88fd3cc8275556bda72/examples/audio/silero-vad/cpp/vad.cc#L96-L117

改为如下代码即可解决
```
// 函数传入参数改为引用，而非传值拷贝，解决局部变量出作用域失效的问题
bool Vad::Preprocess(std::vector<float>& audioWindowData) {
    inputTensors_.resize(4);
    inputTensors_[0].name = "input";
    inputTensors_[0].SetExternalData(input_node_dims_, fastdeploy::FDDataType::FP32, audioWindowData.data());

    inputTensors_[1].name = "sr";
    inputTensors_[1].SetExternalData(sr_node_dims_, fastdeploy::FDDataType::INT64, sr_.data());

    inputTensors_[2].name = "h";
    inputTensors_[2].SetExternalData(hc_node_dims_, fastdeploy::FDDataType::FP32, _h.data());

    inputTensors_[3].name = "c";
    inputTensors_[3].SetExternalData(hc_node_dims_, fastdeploy::FDDataType::FP32, _c.data());
    return true;
}
```
