### ISSUE TITLE
Android12系统源码导入FastDeploy时编译错误

### ISSUE THREAD

**Issue by Guilty39** [PaddlePaddle/FastDeploy#1194]
*********************************************
温馨提示：根据社区不完全统计，按照模板提问，可以加快回复和解决问题的速度
*********************************************

## 环境

- 【FastDeploy版本】： 说明具体的版本，如fastdeploy-linux-gpu-0.8.0
- 【编译命令】如果您是自行编译的FastDeploy，请说明您的编译方式（参数命令）
- 【系统平台】: Linux x64(Ubuntu 18.04) / Windows x64(Windows10) / Mac OSX arm(12.0) / Mac OSX intel(12.0)
- 【硬件】： 说明具体硬件型号，如 Nvidia GPU 3080TI， CUDA 11.2 CUDNN 8.3
- 【编译语言】： C++ / Python(3.7或3.8等）

## 问题日志及出现问题的操作流程
- 附上详细的问题日志有助于快速定位分析
- 【模型跑不同】
- - 先执行`examples`下的部署示例，包括使用examples提供的模型，确认是否可以正确执行
- - 如若`examples`下的代码可以运行，但自己的模型，或自己的代码不能运行
- - - 提供复现问题的 代码+模型+错误log，供工程师快速定位问题
- 【模型精度问题】
- - 先执行`examples`下的部署示例，包括使用examples提供的模型，确认是否可以正确执行
- - 如若`examples`下的代码可以运行，但自己的模型，或自己的代码不能运行
- - - 提供复现问题的 代码+模型+错误log，供工程师快速定位问题
- 【性能问题】描述清楚对比的方式
- - 注意性能测试，循环跑N次，取后80%的用时平均（模型启动时，刚开始受限于资源分配，速度会较慢）
- - FastDeploy的Predict包含模型本身之外的数据前后处理用时
- - - 提供复现问题的 代码+模型+错误log，供工程师快速定位问题

你好，我希望再Android12系统中使用FastDeploy，在尝试导入Android版本的动态库时，编译过程中出现了如下报错：
ld.lld: error: undefined symbol: fastdeploy::vision::matting::PPMatting::PPMatting(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, fastdeploy::RuntimeOption const&, fastdeploy::ModelFormat const&)
目前推测是ndk命名空间与Android系统源码中的命名空间不同导致的（std::__1和std::__ndk1），请问这种情况应该如何解决呢？

**Comment by DefTruth** [comment]
@Guilty39 请问您使用的是fastdeploy android的c++ sdk还是java sdk呢？以及可以提供下以下的信息吗？
- fastdeploy android c++/java sdk版本
- 您使用的android ndk版本和android sdk版本 
- 手机的型号和芯片信息
- 具体的测试代码
- 编译命令

**Comment by Guilty39** [comment]
1、使用的是fastdeploy android的c++ sdk

2、sdk版本是30，ndk版本是21.0.6113669

3、机器是正在开发中的开发板，芯片是高通的晓龙870处理器

4、在camxchinodehook.cpp的CopyImage函数中添加了测试代码

5、编译的时候直接编译整个系统，导入FastDeploy的相关编译规则在Android.mk中





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/FastDeploy"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年1月31日(星期二) 上午10:46
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/FastDeploy] Android12系统源码导入FastDeploy时编译错误 (Issue #1194)





 
@Guilty39 请问您使用的是fastdeploy android的c++ sdk还是java sdk呢？以及可以提供下以下的信息吗？
  
fastdeploy android c++/java sdk版本
 
您使用的android ndk版本和android sdk版本
 
手机的型号和芯片信息
 
具体的测试代码
 
编译命令

**Comment by DefTruth** [comment]
可以换成ndk25先试一下，我们先复现下您的问题

**Comment by DefTruth** [comment]
使用c++ sdk可以参考这个文档哈：https://github.com/PaddlePaddle/FastDeploy/blob/develop/docs/cn/faq/use_cpp_sdk_on_android.md

**Comment by Guilty39** [comment]
你好，这个文档介绍的是在APP中使用jni的方式导入FastDeploy，但我需要在Android系统源码中导入，是将FastDeploy库放在系统源码中与系统一起编译的，导入的方式与文档中介绍的方式不一样




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/FastDeploy"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年2月1日(星期三) 中午11:06
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/FastDeploy] Android12系统源码导入FastDeploy时编译错误 (Issue #1194)





 
使用c++ sdk可以参考这个文档哈：https://github.com/PaddlePaddle/FastDeploy/blob/develop/docs/cn/faq/use_cpp_sdk_on_android.md

**Comment by DefTruth** [comment]
目前暂时不建议直接联编fastdeploy的源码，因为涉及的依赖和配置会比较多。如果您要考虑从源码编译fastdeploy的android c++库，可以参考android编译文档：  
- https://github.com/PaddlePaddle/FastDeploy/blob/develop/docs/en/build_and_install/android.md
