### ISSUE TITLE
是否提供对FreeYolo支持？

### ISSUE THREAD

**Issue by futureflsl** [PaddlePaddle/FastDeploy#1196]
开源地址：https://github.com/yjh0410/FreeYOLO，是否能提供对这个框架支持

**Comment by jiangjiajun** [comment]
如果前后处理与其它YOLO模型一样，其实很容易支持。欢迎一起来开发啊，有兴趣可以在我们的微信群里找到我的头像添加我

**Comment by jiangjiajun** [comment]
此ISSUE由于一年未更新，将会关闭处理，如有需要，可再次更新打开。
