### ISSUE TITLE
fastdeploy 是否可以提供 rotate 旋转目标检测ppyoloe-r的推理脚本

### ISSUE THREAD

**Issue by forword-1234** [PaddlePaddle/FastDeploy#1198]

**Comment by forword-1234** [comment]
[ERROR] fastdeploy/backends/ort/ops/multiclass_nms.cc(185)::Compute     Require the 3-dimension of input boxes be 4, but now it's 8.
multiclass_nums 不是可以支持四边形四点输入的吗？

**Comment by DefTruth** [comment]
正在支持中

**Comment by monkeycc** [comment]
期待 旋转目标检测  ing ...

**Comment by Splendon** [comment]
大概什么时候有结果啦

**Comment by DreamMaker777** [comment]
期待ppyoloe-r @DefTruth

**Comment by njflove** [comment]
现在支持了吗？@DefTruth
