### ISSUE TITLE
RK3588 YOLOV8 onnx转rknn

### ISSUE THREAD

**Issue by shuyue-jl** [PaddlePaddle/FastDeploy#1208]
v8的onnx转rknn报这个错怎么办
E load_onnx: Traceback (most recent call last):
E load_onnx:   File "rknn/api/rknn_base.py", line 1152, in rknn.api.rknn_base.RKNNBase.load_onnx
E load_onnx:   File "rknn/api/rknn_base.py", line 617, in rknn.api.rknn_base.RKNNBase._create_ir_and_inputs_meta
E load_onnx: TypeError: '<=' not supported between instances of 'NoneType' and 'int'
rknn对应接口都封装了，也改不了呀
v8这个版本的onnx不管是否有nms都报这个bug
望解答。。。。。。

**Comment by Zheng-Bicheng** [comment]
你这个YOLOV8的ONNX是哪个版本的？Paddle还是官方的

**Comment by Zheng-Bicheng** [comment]
看样子是输入shape没固定，你参考哪个文档转换的模型啊

**Comment by Zheng-Bicheng** [comment]
解决了吗

**Comment by lizheng-1** [comment]
我遇到了同样的错误，也固定输出了，用的是 [https://github.com/PaddlePaddle/FastDeploy/blob/release/1.0.5/examples/vision/detection/paddledetection/rknpu2/README_CN.md](https://github.com/PaddlePaddle/FastDeploy/blob/release/1.0.5/examples/vision/detection/paddledetection/rknpu2/README_CN.md)这里的示例。请问我该怎么解决这个问题？

**Comment by Zheng-Bicheng** [comment]
> 我遇到了同样的错误，也固定输出了，用的是 https://github.com/PaddlePaddle/FastDeploy/blob/release/1.0.5/examples/vision/detection/paddledetection/rknpu2/README_CN.md这里的示例。请问我该怎么解决这个问题？

参考以下文档，看一下输出节点指定的是否和你们的模型一致

https://github.com/PaddlePaddle/FastDeploy/tree/develop/examples/vision/detection/paddledetection/rknpu2

**Comment by lizheng-1** [comment]
我是直接下载你们提供的这个模型[picodet](https://bj.bcebos.com/paddlehub/fastdeploy/rknpu2/picodet_s_416_coco_lcnet.zip)，先静态图转ONNX， 固定shape，查看模型结构，其中NonMaxSuppression节点的输入节点不一样，我修改为这样：
outputs_nodes:
  - 'tmp_16'
  - 'p2o.Concat.9'
![image](https://user-images.githubusercontent.com/63158425/230904159-93fd8772-439b-4445-a1b2-0a34f33e1caa.png)

请问outputs_nodes应该怎样修改

**Comment by Zheng-Bicheng** [comment]
这应该没有问题呀，你报什么错误

**Comment by lizheng-1** [comment]
> 

I     convert_global_avgpool_to_conv: remove node = ['p2o.GlobalAveragePool.2'], add node = ['p2o.GlobalAveragePool.2_2conv_0', 'p2o.GlobalAveragePool.3']
I     convert_div_to_mul: remove node = ['p2o.Div.26'], add node = ['p2o.Div.26_2mul']
I     convert_div_to_mul: remove node = ['p2o.Div.29'], add node = ['p2o.Div.29_2mul']
E build: Catch exception when building RKNN model!
E build: Traceback (most recent call last):
E build:   File "rknn/api/rknn_base.py", line 1546, in rknn.api.rknn_base.RKNNBase.build
E build:   File "rknn/api/graph_optimizer.py", line 1276, in rknn.api.graph_optimizer.GraphOptimizer.fuse_ops
E build:   File "rknn/api/fuse_rules.py", line 2138, in rknn.api.fuse_rules._p_convert_resize_to_deconv
E build: TypeError: unsupported operand type(s) for /: 'NoneType' and 'int'
Traceback (most recent call last):
  File "tools/rknpu2/export.py", line 58, in <module>
    assert ret == 0, "Build model failed!"
AssertionError: Build model failed!

**Comment by Zheng-Bicheng** [comment]
> I convert_global_avgpool_to_conv: remove node = ['p2o.GlobalAveragePool.2'], add node = ['p2o.GlobalAveragePool.2_2conv_0', 'p2o.GlobalAveragePool.3']
> I convert_div_to_mul: remove node = ['p2o.Div.26'], add node = ['p2o.Div.26_2mul']
> I convert_div_to_mul: remove node = ['p2o.Div.29'], add node = ['p2o.Div.29_2mul']
> E build: Catch exception when building RKNN model!
> E build: Traceback (most recent call last):
> E build: File "rknn/api/rknn_base.py", line 1546, in rknn.api.rknn_base.RKNNBase.build
> E build: File "rknn/api/graph_optimizer.py", line 1276, in rknn.api.graph_optimizer.GraphOptimizer.fuse_ops
> E build: File "rknn/api/fuse_rules.py", line 2138, in rknn.api.fuse_rules._p_convert_resize_to_deconv
> E build: TypeError: unsupported operand type(s) for /: 'NoneType' and 'int'
> Traceback (most recent call last):
> File "tools/rknpu2/export.py", line 58, in 
> assert ret == 0, "Build model failed!"
> AssertionError: Build model failed!

你ONNX文件给我下

**Comment by lizheng-1** [comment]
[Uploading picodet.zip…]()
picodet.onnx 是固定之后的
目标设备为：rk3588

**Comment by Zheng-Bicheng** [comment]
我拿你给我的ONNX模型，可视化看到的结果和上面不一致，对应的两个输出节点应该是

```
p2o.Mul.179
p2o.Concat.9
```

**Comment by lizheng-1** [comment]
> 我拿你给我的ONNX模型，可视化看到的结果和上面不一致，对应的两个输出节点应该是
> 
> ```
> p2o.Mul.179
> p2o.Concat.9
> ```
我尝试过 这两个节点，修改后报这个错
![image](https://user-images.githubusercontent.com/63158425/230907083-05496fc4-752a-4a86-acd9-42936014d311.png)

------------
问什么我们看到的节点不一样？请问你是用netron查看的吗？
我看到的如下
![image](https://user-images.githubusercontent.com/63158425/230907360-cd0d6049-f684-4093-a5d1-2253a72050a8.png)

**Comment by Zheng-Bicheng** [comment]
* 我是用netron查看的
* 请你使用develop版本的fastdeploy，rknntoolkit已经进行了更新，1.4.0是非常老的版本了
* 如果看不懂英文可以切换到中文文档，里面详细的描述了应该是红色方框圈出来的节点名称而不是NMS这个OP的两个输入

**Comment by lizheng-1** [comment]
更换develop代码后，参数修改为：
outputs_nodes:
  - 'tmp_17'
  - 'p2o.Concat.9'
报错为：
npu2/config/picodet_s_416_coco_lcnet_unquantized.yaml                               --target_platform rk3588
{'mean': [123.675, 116.28, 103.53], 'std': [58.395, 57.12, 57.375], 'model_path': './picodet_s_416_coco_lcnet/picodet.onnx', 'outputs_nodes': ['tmp_17', 'p2o.Concat.9'], 'do_quantization': False, 'dataset': None, 'output_folder': './picodet_s_416_coco_lcnet'}
W __init__: rknn-toolkit2 version: 1.4.0-22dcfef4
W load_onnx: If you don't need to crop the model, don't set 'inputs'/'input_size_list'/'outputs'!
W load_onnx: It is recommended onnx opset 12, but your onnx model opset is 11!
E load_onnx: The len of mean_values ([123.675, 116.28, 103.53]) for input 0 is wrong, expect 2!
W load_onnx: ===================== WARN(3) =====================
E rknn-toolkit2 version: 1.4.0-22dcfef4
E load_onnx: Catch exception when loading onnx model: /media/lenovo/deep/fastd/FastDeploy-develop/picodet_s_416_coco_lcnet/picodet.onnx!
E load_onnx: Traceback (most recent call last):
E load_onnx:   File "rknn/api/rknn_base.py", line 1152, in rknn.api.rknn_base.RKNNBase.load_onnx
E load_onnx:   File "rknn/api/rknn_base.py", line 635, in rknn.api.rknn_base.RKNNBase._create_ir_and_inputs_meta
E load_onnx:   File "rknn/api/rknn_log.py", line 113, in rknn.api.rknn_log.RKNNLog.e
E load_onnx: ValueError: The len of mean_values ([123.675, 116.28, 103.53]) for input 0 is wrong, expect 2!
Traceback (most recent call last):
  File "tools/rknpu2/export.py", line 52, in <module>
    assert ret == 0, "Load model failed!"
AssertionError: Load model failed!

![image](https://user-images.githubusercontent.com/63158425/230910425-dff1bf30-8f9f-484a-b7fe-1b7283383f85.png)
---
参数 修改为：
p2o.Mul.179
p2o.Concat.9
时
报错如下：
{'mean': [[123.675, 116.28, 103.53]], 'std': [[58.395, 57.12, 57.375]], 'model_path': './picodet_s_416_coco_lcnet/picodet.onnx', 'outputs_nodes': ['p2o.Mul.179', 'p2o.Concat.9'], 'do_quantization': False, 'dataset': None, 'output_folder': './picodet_s_416_coco_lcnet'}
W __init__: rknn-toolkit2 version: 1.4.0-22dcfef4
W load_onnx: If you don't need to crop the model, don't set 'inputs'/'input_size_list'/'outputs'!
W load_onnx: It is recommended onnx opset 12, but your onnx model opset is 11!
E load_onnx: The 'p2o.Mul.179' in outputs=['p2o.Mul.179', 'p2o.Concat.9'] is invalid!
W load_onnx: ===================== WARN(3) =====================
E rknn-toolkit2 version: 1.4.0-22dcfef4
E load_onnx: Catch exception when loading onnx model: /media/lenovo/deep/fastd/FastDeploy-develop/picodet_s_416_coco_lcnet/picodet.onnx!
E load_onnx: Traceback (most recent call last):
E load_onnx:   File "rknn/api/rknn_base.py", line 1136, in rknn.api.rknn_base.RKNNBase.load_onnx
E load_onnx:   File "rknn/api/rknn_log.py", line 113, in rknn.api.rknn_log.RKNNLog.e
E load_onnx: ValueError: The 'p2o.Mul.179' in outputs=['p2o.Mul.179', 'p2o.Concat.9'] is invalid!
Traceback (most recent call last):
  File "tools/rknpu2/export.py", line 52, in <module>
    assert ret == 0, "Load model failed!"
AssertionError: Load model failed!

---
参数为
outputs_nodes:
  - 'tmp_16'
  - 'p2o.Concat.9'
报错如下：
E build: Catch exception when building RKNN model!
E build: Traceback (most recent call last):
E build:   File "rknn/api/rknn_base.py", line 1546, in rknn.api.rknn_base.RKNNBase.build
E build:   File "rknn/api/graph_optimizer.py", line 1276, in rknn.api.graph_optimizer.GraphOptimizer.fuse_ops
E build:   File "rknn/api/fuse_rules.py", line 2138, in rknn.api.fuse_rules._p_convert_resize_to_deconv
E build: TypeError: unsupported operand type(s) for /: 'NoneType' and 'int'
Traceback (most recent call last):
  File "tools/rknpu2/export.py", line 58, in <module>
    assert ret == 0, "Build model failed!"
AssertionError: Build model failed!

**Comment by Zheng-Bicheng** [comment]
你用develop版本的fastdeploy了吗？你这个rknntoolkit2版本和现在FastDeploy的文档根本对不上呀，先同步一下环境。其次，'./picodet_s_416_coco_lcnet/picodet.onnx'这个模型应该是你自己使用paddle2onnx工具生成的吧？那你应该自己用netron可视化，然后再找到对应两个节点的名字呀。

**Comment by lizheng-1** [comment]
> 

- 是用的develop版本
- picodet.onnx的生成是按照这个文档的步骤做的，就是输出名修改了下。
- 我按照develop给的文档再重新配置下环境吧
非常感谢您的解答！

**Comment by Zheng-Bicheng** [comment]
> * 是用的develop版本
> * picodet.onnx的生成是按照这个文档的步骤做的，就是输出名修改了下。
> * 我按照develop给的文档再重新配置下环境吧
>   非常感谢您的解答！

那你应该把你转换完的模型上传上来，而不是上传我已经转换好的模型🥲这样我怎么帮你排查错误呢？

**Comment by TachibanaYoshino** [comment]
@Zheng-Bicheng 
[files.zip](https://github.com/PaddlePaddle/FastDeploy/files/11207457/files.zip)
How to convert it to rknn correctly, and add post-processing for inference?
