### ISSUE TITLE
rk3588部署yolov5报错

### ISSUE THREAD

**Issue by shuyue-jl** [PaddlePaddle/FastDeploy#1209]
[WARNING] fastdeploy/runtime/backends/rknpu2/rknpu2_backend.cc(315)::Infer      The input tensor type != model's inputs type.The input_type need INT8,but inputs[0].type is UINT8
[ERROR] fastdeploy/vision/detection/ppdet/ppdet_decode.cc(146)::DecodeAndNMS    The size of output must be fpn_stride * 2.
Aborted
这个怎么解决

**Comment by Zheng-Bicheng** [comment]
能再详细一点吗？RK3588上部署YOLOV5仅支持RKYOLOV5,PaddleDetection的yolov5还没有测试过

**Comment by Zheng-Bicheng** [comment]
但是理论上也是可以的，你能提供一下你的ONNX模型吗
