### ISSUE TITLE
服务化部署 use backend 预编译不支持

### ISSUE THREAD

**Issue by suparek** [PaddlePaddle/FastDeploy#1215]
拉取 registry.baidubce.com/paddlepaddle/fastdeploy:1.0.2-cpu-only-21.10

启动时分别试了三个backend：paddle、paddle_lite、onnx_runtime 分别报

UsePaddleBackend The FastDeploy didn't compile with Paddle Inference.

UseLiteBackend The FastDeploy didn't compile with Paddle Lite. 

UseTrtBackend The FastDeploy didn't compile with TrtBackend. 

难道各种backend都不支持吗？这是怎么回事呢？

附上日志：

<img width="1179" alt="image" src="https://user-images.githubusercontent.com/9245996/216023706-fb29b0d0-5c94-4741-a9da-67b758f01d7f.png">

**Comment by heliqi** [comment]
1. 你启动的是ernie demo？
2. linux环境还是windows？
3. 把你修改config的地方发出来看看
我这边拉取镜像并运行 ernie的例子可以成功启动(修改backend为paddle、ort都可)， 你删除镜像重新pull试试？

**Comment by suparek** [comment]
> 1. 你启动的是ernie demo？
> 2. linux环境还是windows？
> 3. 把你修改config的地方发出来看看
>    我这边拉取镜像并运行 ernie的例子可以成功启动(修改backend为paddle、ort都可)， 你删除镜像重新pull试试？

谢谢回复，已经解决了，在dockerfile里把 fastdeploy-python 先 uninstall，再重新装一下，就好了，估计是为了省docker镜像空间吧。

```
RUN python3 -m pip uninstall -y fastdeploy-python
RUN python3 -m pip install fastdeploy-python -f https://www.paddlepaddle.org.cn/whl/fastdeploy.html -i http://mirrors.aliyun.com/pypi/simple --trusted-host mirrors.aliyun.com
```
