### ISSUE TITLE
在RK3568平台上实现RKYOLOv5模型部署过程中遇到的“Segmentation fault”问题

### ISSUE THREAD

**Issue by Rsndmmm** [PaddlePaddle/FastDeploy#1219]
*********************************************
温馨提示：根据社区不完全统计，按照模板提问，可以加快回复和解决问题的速度
*********************************************

## 环境

【FastDeploy版本】： fastdeploy-1.0.2
【编译命令】按照仓库提供的环境编译方式完成C++和Python环境的编译。
【系统平台】: Linux FriendlyElec 5.10.110 
【硬件】： RK3568
【编译语言】： C++ & Python(3.7）

## 问题日志及出现问题的操作流程
- 附上详细的问题日志有助于快速定位分析
- 【模型跑不通】
自己的数据集，用rknn的训练代码https://github.com/airockchip/yolov5训练出的模型，转到torchscript，再做量化转成rknn看起来都没什么问题，到rk3568设备上推理时候直接报错退出，修改postprocess.h里的类别数量之后还是报错
<img width="1283" alt="image" src="https://user-images.githubusercontent.com/27794711/216072491-9b34b601-650f-4a2e-8888-bd8922c2b148.png">
demo路径：FastDeploy/examples/vision/detection/rkyolo/cpp和FastDeploy/examples/vision/detection/rkyolo/python

**Comment by Zheng-Bicheng** [comment]
在[PR1212](https://github.com/PaddlePaddle/FastDeploy/pull/1213)中将会修复这个问题，修复好后会通知您

**Comment by Zheng-Bicheng** [comment]
C++版本的已经修复，Python我这段时间忙完后支持

**Comment by Zheng-Bicheng** [comment]
你好，python 版本已经支持，你再测试一下
