### ISSUE TITLE
FastDeploy导出paddleyolo模型为rknn模型报错

### ISSUE THREAD

**Issue by wen-flow** [PaddlePaddle/FastDeploy#1220]
*********************************************
温馨提示：根据社区不完全统计，按照模板提问，可以加快回复和解决问题的速度
*********************************************

## 环境

- 【FastDeploy版本】： develop
- 【编译命令】python tools/rknpu2/export.py --config_path tools/rknpu2/config/yolov7_tiny_unquantized.yaml --target_platform rk3588
- 【系统平台】: Linux x64(Ubuntu 20.04)
- 【硬件】： Nvidia GPU GTX 850M， CUDA 11.2 CUDNN 8.3
- 【编译语言】： python 3.8

## 问题日志及出现问题的操作流程
- 附上详细的问题日志有助于快速定位分析
- 【模型跑不同】
- - 先执行`examples`下的部署示例，包括使用examples提供的模型，确认是否可以正确执行
- - 如若`examples`下的代码可以运行，但自己的模型，或自己的代码不能运行
- - - 提供复现问题的 代码+模型+错误log，供工程师快速定位问题
- 【paddleyolo导出的onnx模型FastDeploy无法转化为RKNN】
- -RKNN2环境（python3.8）
[requirements.txt](https://github.com/PaddlePaddle/FastDeploy/files/10563699/requirements.txt)
- -配置文件
[yolov7_tiny_unquantized.zip](https://github.com/PaddlePaddle/FastDeploy/files/10565101/yolov7_tiny_unquantized.zip)

- -报错详情
{'mean': None, 'std': None, 'model_path': './yolov7_tiny.onnx', 'outputs_nodes': ['p2o.Div.1', 'p2o.Concat.58'], 'do_quantization': False, 'dataset': './dataset.txt', 'output_folder': './yolov7_tiny'}
W __init__: rknn-toolkit2 version: 1.4.0-22dcfef4
W load_onnx: If you don't need to crop the model, don't set 'inputs'/'input_size_list'/'outputs'!
W load_onnx: It is recommended onnx opset 12, but your onnx model opset is 11!
W load_onnx: The config.mean_values is None, zeros will be set for input 0!
W load_onnx: The config.std_values is None, ones will be set for input 0!
W load_onnx: The config.mean_values is None, zeros will be set for input 1!
W load_onnx: The config.std_values is None, ones will be set for input 1!
I base_optimize ...
I base_optimize done.
I 
I fold_constant ...
E build: Catch exception when building RKNN model!
E build: Traceback (most recent call last):
E build:   File "rknn/api/rknn_base.py", line 1541, in rknn.api.rknn_base.RKNNBase.build
E build:   File "rknn/api/graph_optimizer.py", line 608, in rknn.api.graph_optimizer.GraphOptimizer.fold_constant
E build:   File "rknn/api/ir_graph.py", line 941, in rknn.api.ir_graph.IRGraph.make_model
E build:   File "rknn/api/ir_graph.py", line 93, in rknn.api.ir_graph.IRGraph.infer_shapes
E build:   File "/home/wen/anaconda3/envs/rknn2-38/lib/python3.8/site-packages/onnx/checker.py", line 104, in check_model
E build:     C.check_model(protobuf_string)
E build: onnx.onnx_cpp2py_export.checker.ValidationError: Field 'shape' of type is required but missing.
Traceback (most recent call last):
  File "tools/rknpu2/export.py", line 58, in <module>
    assert ret == 0, "Build model failed!"
AssertionError: Build model failed!
- -paddleyolo导出的模型文件

[yolov7_tiny.zip](https://github.com/PaddlePaddle/FastDeploy/files/10565098/yolov7_tiny.zip)

**Comment by Zheng-Bicheng** [comment]
能否提供一下ONNX格式的模型？YOLOV7还没测试过

**Comment by wen-flow** [comment]
> 

您好  很抱歉提问时模型没有上传成功，现在已经重新上传了模型和配置文件。
经过尝试已经通过安装最新deta版本RKNN2（https://eyun.baidu.com/enterprise/share/link?cid=8272257679089781337&uk=1883176049&sid=202205053973938618#sharelink/path=%2F, 密码：rknn）RK_NPU_SDK-> RK_NPU_SDK_1.4.0->develop->rknn-toolkit2-1.4.1b21->packages->rknn_toolkit2-1.4.1b21_6c452f2d-cp36-cp36m-linux_x86_64.whl来解决。
我在实验yolov8_s时也遇到了相同的问题，均可以通过上述方法解决，您可以尝试复现一下，谢谢！

**Comment by wen-flow** [comment]
> 能否提供一下ONNX格式的模型？YOLOV7还没测试过
@Zheng-Bicheng 您好 很抱歉提问时模型没有上传成功，现在已经重新上传了模型和配置文件。
经过尝试已经通过安装最新deta版本RKNN2（https://eyun.baidu.com/enterprise/share/link?cid=8272257679089781337&uk=1883176049&sid=202205053973938618#sharelink/path=%2F, 密码：rknn）RK_NPU_SDK-> RK_NPU_SDK_1.4.0->develop->rknn-toolkit2-1.4.1b21->packages->rknn_toolkit2-1.4.1b21_6c452f2d-cp36-cp36m-linux_x86_64.whl来解决。
我在实验yolov8_s时也遇到了相同的问题，均可以通过上述方法解决，您可以尝试复现一下，谢谢！

**Comment by Zheng-Bicheng** [comment]
建议使用p2o.Concat.58和p2o.Concat.56作为输出节点再测试一下

**Comment by Zheng-Bicheng** [comment]
你用的Paddle2ONNX是最新版本吗?

**Comment by wen-flow** [comment]
> 建议使用p2o.Concat.58和p2o.Concat.56作为输出节点再测试一下

尝试了一下，相同的错误。

**Comment by wen-flow** [comment]
> 你用的Paddle2ONNX是最新版本吗?
我使用的Paddle2ONNX 的版本为1.0.5

**Comment by Zheng-Bicheng** [comment]
你先试试配置文件改成这样行不行
```
outputs_nodes:
  - 'p2o.Concat.56'
  - 'p2o.Concat.58'
```

**Comment by wen-flow** [comment]
> 你先试试配置文件改成这样行不行
> 
> ```
> outputs_nodes:
>   - 'p2o.Concat.56'
>   - 'p2o.Concat.58'
> ```

还是相同的错误。
{'mean': None, 'std': None, 'model_path': './yolov7_tiny.onnx', 'outputs_nodes': ['p2o.Concat.56', 'p2o.Concat.58'], 'do_quantization': False, 'dataset': './dataset.txt', 'output_folder': './yolov7_tiny'}
W __init__: rknn-toolkit2 version: 1.4.0-22dcfef4
W load_onnx: If you don't need to crop the model, don't set 'inputs'/'input_size_list'/'outputs'!
W load_onnx: It is recommended onnx opset 12, but your onnx model opset is 11!
W load_onnx: The config.mean_values is None, zeros will be set for input 0!
W load_onnx: The config.std_values is None, ones will be set for input 0!
I base_optimize ...
I base_optimize done.
I 
I fold_constant ...
E build: Catch exception when building RKNN model!
E build: Traceback (most recent call last):
E build:   File "rknn/api/rknn_base.py", line 1541, in rknn.api.rknn_base.RKNNBase.build
E build:   File "rknn/api/graph_optimizer.py", line 608, in rknn.api.graph_optimizer.GraphOptimizer.fold_constant
E build:   File "rknn/api/ir_graph.py", line 941, in rknn.api.ir_graph.IRGraph.make_model
E build:   File "rknn/api/ir_graph.py", line 93, in rknn.api.ir_graph.IRGraph.infer_shapes
E build:   File "/home/wen/anaconda3/envs/rknn2-38/lib/python3.8/site-packages/onnx/checker.py", line 104, in check_model
E build:     C.check_model(protobuf_string)
E build: onnx.onnx_cpp2py_export.checker.ValidationError: Field 'shape' of type is required but missing.
Traceback (most recent call last):
  File "tools/rknpu2/export.py", line 58, in <module>
    assert ret == 0, "Build model failed!"
AssertionError: Build model failed!

**Comment by Zheng-Bicheng** [comment]
我这边测试没有问题，模型能够成功转换，看一下你的onnx版本是不是1.10.0

**Comment by Zheng-Bicheng** [comment]
[yolov7_tiny.zip](https://github.com/PaddlePaddle/FastDeploy/files/10566056/yolov7_tiny.zip)

**Comment by wen-flow** [comment]
> 



> 我这边测试没有问题，模型能够成功转换，看一下你的onnx版本是不是1.10.0

您指的是paddle转onnx时环境的onnx版本呢（这个我用的1.13.0）？还是rknn2环境的onnx呢（这个我用的1.9.0）？

**Comment by wen-flow** [comment]
> [yolov7_tiny.zip](https://github.com/PaddlePaddle/FastDeploy/files/10566056/yolov7_tiny.zip)

谢谢了

**Comment by Zheng-Bicheng** [comment]
> > 我这边测试没有问题，模型能够成功转换，看一下你的onnx版本是不是1.10.0
> 
> 您指的是paddle转onnx时环境的onnx版本呢（这个我用的1.13.0）？还是rknn2环境的onnx呢（这个我用的1.9.0）？

pip list 看一下onnx的版本，或者直接输入以下命令
```
pip uninstall onnx
pip install onnx==1.10.0
```

**Comment by Zheng-Bicheng** [comment]
能行了吗

**Comment by wen-flow** [comment]
> 能行了吗

改为onnx为1.10.0仍然不行。

**Comment by wen-flow** [comment]
> > 能否提供一下ONNX格式的模型？YOLOV7还没测试过
> > @Zheng-Bicheng 您好 很抱歉提问时模型没有上传成功，现在已经重新上传了模型和配置文件。
> > 经过尝试已经通过安装最新deta版本RKNN2（https://eyun.baidu.com/enterprise/share/link?cid=8272257679089781337&uk=1883176049&sid=202205053973938618#sharelink/path=%2F, 密码：rknn）RK_NPU_SDK-> RK_NPU_SDK_1.4.0->develop->rknn-toolkit2-1.4.1b21->packages->rknn_toolkit2-1.4.1b21_6c452f2d-cp36-cp36m-linux_x86_64.whl来解决。
> > 我在实验yolov8_s时也遇到了相同的问题，均可以通过上述方法解决，您可以尝试复现一下，谢谢！

@Zheng-Bicheng 暂时通过这个方法解决了。

**Comment by corejava** [comment]
File "test.py", line 27, in <module>
    rknn = RKNN(verbose=True)
  File "/bak/envs/rknn/lib/python3.8/site-packages/rknn/api/rknn.py", line 58, in __init__
    self.rknn_base = RKNNBase(cur_path, verbose)
  File "rknn/api/rknn_base.py", line 75, in rknn.api.rknn_base.RKNNBase.__init__
  File "/bak/envs/rknn/lib/python3.8/site-packages/pkg_resources/__init__.py", line 514, in get_distribution
    dist = get_provider(dist)
  File "/bak/envs/rknn/lib/python3.8/site-packages/pkg_resources/__init__.py", line 386, in get_provider
    return working_set.find(moduleOrReq) or require(str(moduleOrReq))[0]
  File "/bak/envs/rknn/lib/python3.8/site-packages/pkg_resources/__init__.py", line 683, in find
    if dist is not None and dist not in req:
  File "/bak/envs/rknn/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3135, in __contains__
    return self.specifier.contains(item, prereleases=True)
  File "/bak/envs/rknn/lib/python3.8/site-packages/pkg_resources/_vendor/packaging/specifiers.py", line 902, in contains
    item = Version(item)
  File "/bak/envs/rknn/lib/python3.8/site-packages/pkg_resources/_vendor/packaging/version.py", line 197, in __init__
    raise InvalidVersion(f"Invalid version: '{version}'")
pkg_resources.extern.packaging.version.InvalidVersion: Invalid version: '1.4.0-22dcfef4'

按照文档操作，版本认证都没过去，请问大家有没有遇到这个问题？

**Comment by Zheng-Bicheng** [comment]
> File "test.py", line 27, in rknn = RKNN(verbose=True) File "/bak/envs/rknn/lib/python3.8/site-packages/rknn/api/rknn.py", line 58, in **init** self.rknn_base = RKNNBase(cur_path, verbose) File "rknn/api/rknn_base.py", line 75, in rknn.api.rknn_base.RKNNBase.**init** File "/bak/envs/rknn/lib/python3.8/site-packages/pkg_resources/**init**.py", line 514, in get_distribution dist = get_provider(dist) File "/bak/envs/rknn/lib/python3.8/site-packages/pkg_resources/**init**.py", line 386, in get_provider return working_set.find(moduleOrReq) or require(str(moduleOrReq))[0] File "/bak/envs/rknn/lib/python3.8/site-packages/pkg_resources/**init**.py", line 683, in find if dist is not None and dist not in req: File "/bak/envs/rknn/lib/python3.8/site-packages/pkg_resources/**init**.py", line 3135, in **contains** return self.specifier.contains(item, prereleases=True) File "/bak/envs/rknn/lib/python3.8/site-packages/pkg_resources/_vendor/packaging/specifiers.py", line 902, in contains item = Version(item) File "/bak/envs/rknn/lib/python3.8/site-packages/pkg_resources/_vendor/packaging/version.py", line 197, in **init** raise InvalidVersion(f"Invalid version: '{version}'") pkg_resources.extern.packaging.version.InvalidVersion: Invalid version: '1.4.0-22dcfef4'
> 
> 按照文档操作，版本认证都没过去，请问大家有没有遇到这个问题？

你直接编译试试吧，现在不需要安装驱动了，FastDeploy自带
