### ISSUE TITLE
请问是否可以给fastdeploy::vision::classification::YOLOv5Cls加上batchPredict

### ISSUE THREAD

**Issue by yueyue0574** [PaddlePaddle/FastDeploy#1225]
请问是否可以给fastdeploy::vision::classification::YOLOv5Cls加上batchPredict

**Comment by GodIsBoom** [comment]
> 请问是否可以给fastdeploy::vision::classification::YOLOv5Cls加上batchPredict

你好，已经重构YOLOv5Cls，支持了batchPredict，直接调用`YOLOv5Cls::BatchPredict(const std::vector<cv::Mat>& images, std::vector<ClassifyResult>* results) `，输入是多张image的vector，输出是对应的多个ClassifyResult的vector，具体代码改动可见https://github.com/PaddlePaddle/FastDeploy/pull/1237

**Comment by yueyue0574** [comment]
> > 请问是否可以给fastdeploy::vision::classification::YOLOv5Cls加上batchPredict
> 
> 你好，已经重构YOLOv5Cls，支持了batchPredict，直接调用`YOLOv5Cls::BatchPredict(const std::vector<cv::Mat>& images, std::vector<ClassifyResult>* results) `，输入是多张image的vector，输出是对应的多个ClassifyResult的vector，具体代码改动可见#1237

谢谢

**Comment by jiangjiajun** [comment]
安装nightly build版本即可（安装方式参考安装文档）
