### ISSUE TITLE
 FastDeploy ppocrv2 python infer.py使用trt模式推理生成rec推理trt文件报错

### ISSUE THREAD

**Issue by QQQTAO** [PaddlePaddle/FastDeploy#1229]
*********************************************
温馨提示：根据社区不完全统计，按照模板提问，可以加快回复和解决问题的速度
*********************************************

## 环境

- 【FastDeploy版本】：fastdeploy-linux-gpu-1.0.2
- 【编译命令】python infer.py "args": [
                "--det_model","/home/qintao/FastDeploy/examples/vision/ocr/PP-OCRv2/inference/ch_PP-OCRv3_det_infer",
                "--cls_model","/home/qintao/FastDeploy/examples/vision/ocr/PP-OCRv2/inference/ch_ppocr_mobile_v2.0_cls_infer",
                "--rec_model","/home/qintao/FastDeploy/examples/vision/ocr/PP-OCRv2/inference/rec_chinese_common_v2.0_9.27",
                "--rec_label_file","/home/qintao/FastDeploy/examples/vision/ocr/PP-OCRv2/ppocr_keys_v1.txt",
                "--image", "/home/qintao/FastDeploy/examples/vision/ocr/PP-OCRv2/12.jpg",
                "--device","gpu",
                "--backend","trt",
- 【系统平台】: Linux x64(Ubuntu 18.04) 
- 【硬件】： Nvidia GPU 3090， CUDA 11.2 CUDNN 8.1 tensorrt 8.4.3.1
- 【编译语言】：Python3.9

## 问题日志及出现问题的操作流程
使用默认模式对infer.py进行调试，可以正常输出结果，使用trt模式进行调试ocr文本检测和ocr文本方向分类可以正常编译生成trt文件，文本识别trt编译时报错，报错内容如下：
[INFO] fastdeploy/backends/tensorrt/trt_backend.cc(500)::BuildTrtEngine Start to building TensorRT Engine...
[ERROR] fastdeploy/backends/tensorrt/trt_backend.cc(238)::log   1: [codeGenerator.cpp::compileGraph::476] Error Code 1: Myelin (myelinExceededMemBudget : Exceeded mem budget of 1073741824. Need 4035485696
)
[ERROR] fastdeploy/backends/tensorrt/trt_backend.cc(238)::log   2: [builder.cpp::buildSerializedNetwork::399] Error Code 2: Internal Error (Assertion enginePtr != nullptr failed.)
[ERROR] fastdeploy/backends/tensorrt/trt_backend.cc(563)::BuildTrtEngine        Failed to call buildSerializedNetwork().
[ERROR] fastdeploy/backends/tensorrt/trt_backend.cc(676)::CreateTrtEngineFromOnnx       Failed to build tensorrt engine.
[INFO] fastdeploy/runtime.cc(585)::Init Runtime initialized with Backend::TRT in Device::GPU.

我对c的代码不太熟悉，无法定位到报错的位置，希望可以帮忙解答一下，十分感谢。

**Comment by yunyaoXYY** [comment]
> 温馨提示：根据社区不完全统计，按照模板提问，可以加快回复和解决问题的速度
> 
> ## 环境
> * 【FastDeploy版本】：fastdeploy-linux-gpu-1.0.2
> * 【编译命令】python infer.py "args": [
>   "--det_model","/home/qintao/FastDeploy/examples/vision/ocr/PP-OCRv2/inference/ch_PP-OCRv3_det_infer",
>   "--cls_model","/home/qintao/FastDeploy/examples/vision/ocr/PP-OCRv2/inference/ch_ppocr_mobile_v2.0_cls_infer",
>   "--rec_model","/home/qintao/FastDeploy/examples/vision/ocr/PP-OCRv2/inference/rec_chinese_common_v2.0_9.27",
>   "--rec_label_file","/home/qintao/FastDeploy/examples/vision/ocr/PP-OCRv2/ppocr_keys_v1.txt",
>   "--image", "/home/qintao/FastDeploy/examples/vision/ocr/PP-OCRv2/12.jpg",
>   "--device","gpu",
>   "--backend","trt",
> * 【系统平台】: Linux x64(Ubuntu 18.04)
> * 【硬件】： Nvidia GPU 3090， CUDA 11.2 CUDNN 8.1 tensorrt 8.4.3.1
> * 【编译语言】：Python3.9
> 
> ## 问题日志及出现问题的操作流程
> 使用默认模式对infer.py进行调试，可以正常输出结果，使用trt模式进行调试ocr文本检测和ocr文本方向分类可以正常编译生成trt文件，文本识别trt编译时报错，报错内容如下： [INFO] fastdeploy/backends/tensorrt/trt_backend.cc(500)::BuildTrtEngine Start to building TensorRT Engine... [ERROR] fastdeploy/backends/tensorrt/trt_backend.cc(238)::log 1: [codeGenerator.cpp::compileGraph::476] Error Code 1: Myelin (myelinExceededMemBudget : Exceeded mem budget of 1073741824. Need 4035485696 ) [ERROR] fastdeploy/backends/tensorrt/trt_backend.cc(238)::log 2: [builder.cpp::buildSerializedNetwork::399] Error Code 2: Internal Error (Assertion enginePtr != nullptr failed.) [ERROR] fastdeploy/backends/tensorrt/trt_backend.cc(563)::BuildTrtEngine Failed to call buildSerializedNetwork(). [ERROR] fastdeploy/backends/tensorrt/trt_backend.cc(676)::CreateTrtEngineFromOnnx Failed to build tensorrt engine. [INFO] fastdeploy/runtime.cc(585)::Init Runtime initialized with Backend::TRT in Device::GPU.
> 
> 我对c的代码不太熟悉，无法定位到报错的位置，希望可以帮忙解答一下，十分感谢。

Hello你好，
我刚用1.0.3版本跑了一下，是没有报错的，要不换成1.0.3版本试试？
还有一个问题，为什么想要选择ocrv2来部署呢，ocrv3有更好的性能.

**Comment by QQQTAO** [comment]
> > 温馨提示：根据社区不完全统计，按照模板提问，可以加快回复和解决问题的速度
> > ## 环境
> > 
> > * 【FastDeploy版本】：fastdeploy-linux-gpu-1.0.2
> > * 【编译命令】python infer.py "args": [
> >   "--det_model","/home/qintao/FastDeploy/examples/vision/ocr/PP-OCRv2/inference/ch_PP-OCRv3_det_infer",
> >   "--cls_model","/home/qintao/FastDeploy/examples/vision/ocr/PP-OCRv2/inference/ch_ppocr_mobile_v2.0_cls_infer",
> >   "--rec_model","/home/qintao/FastDeploy/examples/vision/ocr/PP-OCRv2/inference/rec_chinese_common_v2.0_9.27",
> >   "--rec_label_file","/home/qintao/FastDeploy/examples/vision/ocr/PP-OCRv2/ppocr_keys_v1.txt",
> >   "--image", "/home/qintao/FastDeploy/examples/vision/ocr/PP-OCRv2/12.jpg",
> >   "--device","gpu",
> >   "--backend","trt",
> > * 【系统平台】: Linux x64(Ubuntu 18.04)
> > * 【硬件】： Nvidia GPU 3090， CUDA 11.2 CUDNN 8.1 tensorrt 8.4.3.1
> > * 【编译语言】：Python3.9
> > 
> > ## 问题日志及出现问题的操作流程
> > 使用默认模式对infer.py进行调试，可以正常输出结果，使用trt模式进行调试ocr文本检测和ocr文本方向分类可以正常编译生成trt文件，文本识别trt编译时报错，报错内容如下： [INFO] fastdeploy/backends/tensorrt/trt_backend.cc(500)::BuildTrtEngine Start to building TensorRT Engine... [ERROR] fastdeploy/backends/tensorrt/trt_backend.cc(238)::log 1: [codeGenerator.cpp::compileGraph::476] Error Code 1: Myelin (myelinExceededMemBudget : Exceeded mem budget of 1073741824. Need 4035485696 ) [ERROR] fastdeploy/backends/tensorrt/trt_backend.cc(238)::log 2: [builder.cpp::buildSerializedNetwork::399] Error Code 2: Internal Error (Assertion enginePtr != nullptr failed.) [ERROR] fastdeploy/backends/tensorrt/trt_backend.cc(563)::BuildTrtEngine Failed to call buildSerializedNetwork(). [ERROR] fastdeploy/backends/tensorrt/trt_backend.cc(676)::CreateTrtEngineFromOnnx Failed to build tensorrt engine. [INFO] fastdeploy/runtime.cc(585)::Init Runtime initialized with Backend::TRT in Device::GPU.
> > 我对c的代码不太熟悉，无法定位到报错的位置，希望可以帮忙解答一下，十分感谢。
> 
> Hello你好， 我刚用1.0.3版本跑了一下，是没有报错的，要不换成1.0.3版本试试？ 还有一个问题，为什么想要选择ocrv2来部署呢，ocrv3有更好的性能.

好的，fastdeploy是我之前安装的，我重新试一下，因为ppocrv3的识别模型是轻量化的lcnet识别性能不太理想，我是使用ppocrv2的service模型finetune的，比较下来识别性能更好一些。

**Comment by yunyaoXYY** [comment]
> * rec_chinese_common_v2.0_9.27

不好意思，我才看到你是用自己训练的rec模型在跑，我是用的文档里的官方的rec模型，我怀疑可能是模型的问题. 这个模型在其他的推理引擎上，能正常推理吗？

**Comment by yunyaoXYY** [comment]
> > > 温馨提示：根据社区不完全统计，按照模板提问，可以加快回复和解决问题的速度
> > > ## 环境
> > > 
> > > * 【FastDeploy版本】：fastdeploy-linux-gpu-1.0.2
> > > * 【编译命令】python infer.py "args": [
> > >   "--det_model","/home/qintao/FastDeploy/examples/vision/ocr/PP-OCRv2/inference/ch_PP-OCRv3_det_infer",
> > >   "--cls_model","/home/qintao/FastDeploy/examples/vision/ocr/PP-OCRv2/inference/ch_ppocr_mobile_v2.0_cls_infer",
> > >   "--rec_model","/home/qintao/FastDeploy/examples/vision/ocr/PP-OCRv2/inference/rec_chinese_common_v2.0_9.27",
> > >   "--rec_label_file","/home/qintao/FastDeploy/examples/vision/ocr/PP-OCRv2/ppocr_keys_v1.txt",
> > >   "--image", "/home/qintao/FastDeploy/examples/vision/ocr/PP-OCRv2/12.jpg",
> > >   "--device","gpu",
> > >   "--backend","trt",
> > > * 【系统平台】: Linux x64(Ubuntu 18.04)
> > > * 【硬件】： Nvidia GPU 3090， CUDA 11.2 CUDNN 8.1 tensorrt 8.4.3.1
> > > * 【编译语言】：Python3.9
> > > 
> > > ## 问题日志及出现问题的操作流程
> > > 使用默认模式对infer.py进行调试，可以正常输出结果，使用trt模式进行调试ocr文本检测和ocr文本方向分类可以正常编译生成trt文件，文本识别trt编译时报错，报错内容如下： [INFO] fastdeploy/backends/tensorrt/trt_backend.cc(500)::BuildTrtEngine Start to building TensorRT Engine... [ERROR] fastdeploy/backends/tensorrt/trt_backend.cc(238)::log 1: [codeGenerator.cpp::compileGraph::476] Error Code 1: Myelin (myelinExceededMemBudget : Exceeded mem budget of 1073741824. Need 4035485696 ) [ERROR] fastdeploy/backends/tensorrt/trt_backend.cc(238)::log 2: [builder.cpp::buildSerializedNetwork::399] Error Code 2: Internal Error (Assertion enginePtr != nullptr failed.) [ERROR] fastdeploy/backends/tensorrt/trt_backend.cc(563)::BuildTrtEngine Failed to call buildSerializedNetwork(). [ERROR] fastdeploy/backends/tensorrt/trt_backend.cc(676)::CreateTrtEngineFromOnnx Failed to build tensorrt engine. [INFO] fastdeploy/runtime.cc(585)::Init Runtime initialized with Backend::TRT in Device::GPU.
> > > 我对c的代码不太熟悉，无法定位到报错的位置，希望可以帮忙解答一下，十分感谢。
> > 
> > 
> > Hello你好， 我刚用1.0.3版本跑了一下，是没有报错的，要不换成1.0.3版本试试？ 还有一个问题，为什么想要选择ocrv2来部署呢，ocrv3有更好的性能.
> 
> 好的，fastdeploy是我之前安装的，我重新试一下，因为ppocrv3的识别模型是轻量化的lcnet识别性能不太理想，我是使用ppocrv2的service模型finetune的，比较下来识别性能更好一些。

不好意思，我才看到你是用自己训练的rec模型在跑，我是用的文档里的官方的rec模型，我怀疑可能是模型的问题. 这个模型在其他的推理引擎上，能正常推理吗？

**Comment by QQQTAO** [comment]
> > > > 温馨提示：根据社区不完全统计，按照模板提问，可以加快回复和解决问题的速度
> > > > ## 环境
> > > > 
> > > > * 【FastDeploy版本】：fastdeploy-linux-gpu-1.0.2
> > > > * 【编译命令】python infer.py "args": [
> > > >   "--det_model","/home/qintao/FastDeploy/examples/vision/ocr/PP-OCRv2/inference/ch_PP-OCRv3_det_infer",
> > > >   "--cls_model","/home/qintao/FastDeploy/examples/vision/ocr/PP-OCRv2/inference/ch_ppocr_mobile_v2.0_cls_infer",
> > > >   "--rec_model","/home/qintao/FastDeploy/examples/vision/ocr/PP-OCRv2/inference/rec_chinese_common_v2.0_9.27",
> > > >   "--rec_label_file","/home/qintao/FastDeploy/examples/vision/ocr/PP-OCRv2/ppocr_keys_v1.txt",
> > > >   "--image", "/home/qintao/FastDeploy/examples/vision/ocr/PP-OCRv2/12.jpg",
> > > >   "--device","gpu",
> > > >   "--backend","trt",
> > > > * 【系统平台】: Linux x64(Ubuntu 18.04)
> > > > * 【硬件】： Nvidia GPU 3090， CUDA 11.2 CUDNN 8.1 tensorrt 8.4.3.1
> > > > * 【编译语言】：Python3.9
> > > > 
> > > > ## 问题日志及出现问题的操作流程
> > > > 使用默认模式对infer.py进行调试，可以正常输出结果，使用trt模式进行调试ocr文本检测和ocr文本方向分类可以正常编译生成trt文件，文本识别trt编译时报错，报错内容如下： [INFO] fastdeploy/backends/tensorrt/trt_backend.cc(500)::BuildTrtEngine Start to building TensorRT Engine... [ERROR] fastdeploy/backends/tensorrt/trt_backend.cc(238)::log 1: [codeGenerator.cpp::compileGraph::476] Error Code 1: Myelin (myelinExceededMemBudget : Exceeded mem budget of 1073741824. Need 4035485696 ) [ERROR] fastdeploy/backends/tensorrt/trt_backend.cc(238)::log 2: [builder.cpp::buildSerializedNetwork::399] Error Code 2: Internal Error (Assertion enginePtr != nullptr failed.) [ERROR] fastdeploy/backends/tensorrt/trt_backend.cc(563)::BuildTrtEngine Failed to call buildSerializedNetwork(). [ERROR] fastdeploy/backends/tensorrt/trt_backend.cc(676)::CreateTrtEngineFromOnnx Failed to build tensorrt engine. [INFO] fastdeploy/runtime.cc(585)::Init Runtime initialized with Backend::TRT in Device::GPU.
> > > > 我对c的代码不太熟悉，无法定位到报错的位置，希望可以帮忙解答一下，十分感谢。
> > > 
> > > 
> > > Hello你好， 我刚用1.0.3版本跑了一下，是没有报错的，要不换成1.0.3版本试试？ 还有一个问题，为什么想要选择ocrv2来部署呢，ocrv3有更好的性能.
> > 
> > 
> > 好的，fastdeploy是我之前安装的，我重新试一下，因为ppocrv3的识别模型是轻量化的lcnet识别性能不太理想，我是使用ppocrv2的service模型finetune的，比较下来识别性能更好一些。
> 
> 不好意思，我才看到你是用自己训练的rec模型在跑，我是用的文档里的官方的rec模型，我怀疑可能是模型的问题. 这个模型在其他的推理引擎上，能正常推理吗？
这个就是resnet34 的crnn finetune模型，这个模型我一直在用paddle推理没有什么问题，这个和ppocrv2 service是一样的，我一会重新安装fastdepoly再试一下，有问题了再沟通

**Comment by QQQTAO** [comment]
> 这个就是resnet34 的crnn finetune模型，这个模型我一直在用paddle推理没有什么问题，这个和ppocrv2 service是一样的，我一会重新安装fastdepoly再试一下，有问题了再沟通

**Comment by QQQTAO** [comment]
> 

这个就是resnet34 的crnn finetune模型，这个模型我一直在用paddle推理没有什么问题，这个和ppocrv2 service是一样的，我一会重新安装fastdepoly再试一下，有问题了再沟通

**Comment by QQQTAO** [comment]
> > > > 温馨提示：根据社区不完全统计，按照模板提问，可以加快回复和解决问题的速度
> > > > ## 环境
> > > > 
> > > > * 【FastDeploy版本】：fastdeploy-linux-gpu-1.0.2
> > > > * 【编译命令】python infer.py "args": [
> > > >   "--det_model","/home/qintao/FastDeploy/examples/vision/ocr/PP-OCRv2/inference/ch_PP-OCRv3_det_infer",
> > > >   "--cls_model","/home/qintao/FastDeploy/examples/vision/ocr/PP-OCRv2/inference/ch_ppocr_mobile_v2.0_cls_infer",
> > > >   "--rec_model","/home/qintao/FastDeploy/examples/vision/ocr/PP-OCRv2/inference/rec_chinese_common_v2.0_9.27",
> > > >   "--rec_label_file","/home/qintao/FastDeploy/examples/vision/ocr/PP-OCRv2/ppocr_keys_v1.txt",
> > > >   "--image", "/home/qintao/FastDeploy/examples/vision/ocr/PP-OCRv2/12.jpg",
> > > >   "--device","gpu",
> > > >   "--backend","trt",
> > > > * 【系统平台】: Linux x64(Ubuntu 18.04)
> > > > * 【硬件】： Nvidia GPU 3090， CUDA 11.2 CUDNN 8.1 tensorrt 8.4.3.1
> > > > * 【编译语言】：Python3.9
> > > > 
> > > > ## 问题日志及出现问题的操作流程
> > > > 使用默认模式对infer.py进行调试，可以正常输出结果，使用trt模式进行调试ocr文本检测和ocr文本方向分类可以正常编译生成trt文件，文本识别trt编译时报错，报错内容如下： [INFO] fastdeploy/backends/tensorrt/trt_backend.cc(500)::BuildTrtEngine Start to building TensorRT Engine... [ERROR] fastdeploy/backends/tensorrt/trt_backend.cc(238)::log 1: [codeGenerator.cpp::compileGraph::476] Error Code 1: Myelin (myelinExceededMemBudget : Exceeded mem budget of 1073741824. Need 4035485696 ) [ERROR] fastdeploy/backends/tensorrt/trt_backend.cc(238)::log 2: [builder.cpp::buildSerializedNetwork::399] Error Code 2: Internal Error (Assertion enginePtr != nullptr failed.) [ERROR] fastdeploy/backends/tensorrt/trt_backend.cc(563)::BuildTrtEngine Failed to call buildSerializedNetwork(). [ERROR] fastdeploy/backends/tensorrt/trt_backend.cc(676)::CreateTrtEngineFromOnnx Failed to build tensorrt engine. [INFO] fastdeploy/runtime.cc(585)::Init Runtime initialized with Backend::TRT in Device::GPU.
> > > > 我对c的代码不太熟悉，无法定位到报错的位置，希望可以帮忙解答一下，十分感谢。
> > > 
> > > 
> > > Hello你好， 我刚用1.0.3版本跑了一下，是没有报错的，要不换成1.0.3版本试试？ 还有一个问题，为什么想要选择ocrv2来部署呢，ocrv3有更好的性能.
> > 
> > 
> > 好的，fastdeploy是我之前安装的，我重新试一下，因为ppocrv3的识别模型是轻量化的lcnet识别性能不太理想，我是使用ppocrv2的service模型finetune的，比较下来识别性能更好一些。
> 
> 不好意思，我才看到你是用自己训练的rec模型在跑，我是用的文档里的官方的rec模型，我怀疑可能是模型的问题. 这个模型在其他的推理引擎上，能正常推理吗？

>这个就是resnet34 的crnn finetune模型，这个模型我一直在用paddle推理没有什么问题，这个和ppocrv2 service是一样的，我一会重新安装fastdepoly再试一下，有问题了再沟通

**Comment by yunyaoXYY** [comment]
> > > > > 温馨提示：根据社区不完全统计，按照模板提问，可以加快回复和解决问题的速度
> > > > > ## 环境
> > > > > 
> > > > > * 【FastDeploy版本】：fastdeploy-linux-gpu-1.0.2
> > > > > * 【编译命令】python infer.py "args": [
> > > > >   "--det_model","/home/qintao/FastDeploy/examples/vision/ocr/PP-OCRv2/inference/ch_PP-OCRv3_det_infer",
> > > > >   "--cls_model","/home/qintao/FastDeploy/examples/vision/ocr/PP-OCRv2/inference/ch_ppocr_mobile_v2.0_cls_infer",
> > > > >   "--rec_model","/home/qintao/FastDeploy/examples/vision/ocr/PP-OCRv2/inference/rec_chinese_common_v2.0_9.27",
> > > > >   "--rec_label_file","/home/qintao/FastDeploy/examples/vision/ocr/PP-OCRv2/ppocr_keys_v1.txt",
> > > > >   "--image", "/home/qintao/FastDeploy/examples/vision/ocr/PP-OCRv2/12.jpg",
> > > > >   "--device","gpu",
> > > > >   "--backend","trt",
> > > > > * 【系统平台】: Linux x64(Ubuntu 18.04)
> > > > > * 【硬件】： Nvidia GPU 3090， CUDA 11.2 CUDNN 8.1 tensorrt 8.4.3.1
> > > > > * 【编译语言】：Python3.9
> > > > > 
> > > > > ## 问题日志及出现问题的操作流程
> > > > > 使用默认模式对infer.py进行调试，可以正常输出结果，使用trt模式进行调试ocr文本检测和ocr文本方向分类可以正常编译生成trt文件，文本识别trt编译时报错，报错内容如下： [INFO] fastdeploy/backends/tensorrt/trt_backend.cc(500)::BuildTrtEngine Start to building TensorRT Engine... [ERROR] fastdeploy/backends/tensorrt/trt_backend.cc(238)::log 1: [codeGenerator.cpp::compileGraph::476] Error Code 1: Myelin (myelinExceededMemBudget : Exceeded mem budget of 1073741824. Need 4035485696 ) [ERROR] fastdeploy/backends/tensorrt/trt_backend.cc(238)::log 2: [builder.cpp::buildSerializedNetwork::399] Error Code 2: Internal Error (Assertion enginePtr != nullptr failed.) [ERROR] fastdeploy/backends/tensorrt/trt_backend.cc(563)::BuildTrtEngine Failed to call buildSerializedNetwork(). [ERROR] fastdeploy/backends/tensorrt/trt_backend.cc(676)::CreateTrtEngineFromOnnx Failed to build tensorrt engine. [INFO] fastdeploy/runtime.cc(585)::Init Runtime initialized with Backend::TRT in Device::GPU.
> > > > > 我对c的代码不太熟悉，无法定位到报错的位置，希望可以帮忙解答一下，十分感谢。
> > > > 
> > > > 
> > > > Hello你好， 我刚用1.0.3版本跑了一下，是没有报错的，要不换成1.0.3版本试试？ 还有一个问题，为什么想要选择ocrv2来部署呢，ocrv3有更好的性能.
> > > 
> > > 
> > > 好的，fastdeploy是我之前安装的，我重新试一下，因为ppocrv3的识别模型是轻量化的lcnet识别性能不太理想，我是使用ppocrv2的service模型finetune的，比较下来识别性能更好一些。
> > 
> > 
> > 不好意思，我才看到你是用自己训练的rec模型在跑，我是用的文档里的官方的rec模型，我怀疑可能是模型的问题. 这个模型在其他的推理引擎上，能正常推理吗？
> 
> > 这个就是resnet34 的crnn finetune模型，这个模型我一直在用paddle推理没有什么问题，这个和ppocrv2 service是一样的，我一会重新安装fastdepoly再试一下，有问题了再沟通

好的，如果还是不行的话，建议调小rec模型的Batch Size和动态shape试试

**Comment by QQQTAO** [comment]
![image](https://user-images.githubusercontent.com/48081128/216535713-030389a1-9247-434e-9d5e-d01b832e0641.png)
使用ppocr service模型是使用v2版本、还是v3版本的python infer.py进行推理

**Comment by yunyaoXYY** [comment]
> ![image](https://user-images.githubusercontent.com/48081128/216535713-030389a1-9247-434e-9d5e-d01b832e0641.png) 使用ppocr service模型是使用v2版本、还是v3版本的python infer.py进行推理

用PPOCRv2目录下的代码

**Comment by QQQTAO** [comment]
> > ![image](https://user-images.githubusercontent.com/48081128/216535713-030389a1-9247-434e-9d5e-d01b832e0641.png) 使用ppocr service模型是使用v2版本、还是v3版本的python infer.py进行推理
> 
> 用PPOCRv2目录下的代码

非常感谢，我更换了fastdeploy包之后没有问题了，v2和v3版本都可以正常推理输出结果。

**Comment by Jaccica** [comment]
您好！我部署ppocrv2服务却吊不起来，请问怎么解决？谢谢！可以加一个QQ吗？我的QQ是1282270703，谢谢！

**Comment by Jaccica** [comment]
> > > ![image](https://user-images.githubusercontent.com/48081128/216535713-030389a1-9247-434e-9d5e-d01b832e0641.png) 使用ppocr service模型是使用v2版本、还是v3版本的python infer.py进行推理
> > 
> > 
> > 用PPOCRv2目录下的代码
> 
> 非常感谢，我更换了fastdeploy包之后没有问题了，v2和v3版本都可以正常推理输出结果。

您好！我部署ppocrv2服务却调不起来，请问怎么解决？谢谢！可以加一个QQ吗？我的QQ是1282270703，谢谢！

**Comment by QQQTAO** [comment]
你使用ppocrv2是哪部分出问题了




秦涛
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/FastDeploy"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月23日(星期天) 下午4:35
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/FastDeploy]  FastDeploy ppocrv2 python infer.py使用trt模式推理生成rec推理trt文件报错 (Issue #1229)





    
 使用ppocr service模型是使用v2版本、还是v3版本的python infer.py进行推理
  
用PPOCRv2目录下的代码
  
非常感谢，我更换了fastdeploy包之后没有问题了，v2和v3版本都可以正常推理输出结果。
  
您好！我部署ppocrv2服务却调不起来，请问怎么解决？谢谢！可以加一个QQ吗？我的QQ是1282270703，谢谢！

**Comment by QQQTAO** [comment]
> > > > ![image](https://user-images.githubusercontent.com/48081128/216535713-030389a1-9247-434e-9d5e-d01b832e0641.png) 使用ppocr service模型是使用v2版本、还是v3版本的python infer.py进行推理
> > > 
> > > 
> > > 用PPOCRv2目录下的代码
> > 
> > 
> > 非常感谢，我更换了fastdeploy包之后没有问题了，v2和v3版本都可以正常推理输出结果。
> 
> 您好！我部署ppocrv2服务却调不起来，请问怎么解决？谢谢！可以加一个QQ吗？我的QQ是1282270703，谢谢！

我加你qq好友了，你通过一下，你部署服务时是哪部分出问题了，直接使用的官方的推理模型吗？
