### ISSUE TITLE
yolov8 使用

### ISSUE THREAD

**Issue by sl00001** [PaddlePaddle/FastDeploy#1231]
![bb819eb183e2cf293b5ce458ada33ff](https://user-images.githubusercontent.com/106507366/216543107-eff1239e-1dbc-454e-b78b-f53a07ca59da.png)

问下yolov8里面推理的时候需要输入conf_threshold 和nms_threshold  怎么处理  看了下和yolov5 不一样  谢谢

**Comment by jiangjiajun** [comment]
FD的新模型中，所有的后处理模块都在成员变量`postprocessors_`里面，前处理模块都在成员变量`preprocessors_`里面

如果需要修改前后处理参数，则可以使用如下方式
```
model.GetPreprocessor().SetXXX()
```
```
model.GetPostprocssor().SetXXX()
```

**Comment by sl00001** [comment]
好的 知道了 谢谢

**Comment by liuyiche** [comment]
python版本的是在哪设置置信度和iou呢

**Comment by jiangjiajun** [comment]
`
model.postprocessor.xxx = 0.5
`
通过上面这种方式设置python

**Comment by liuyiche** [comment]
> `model.postprocessor.xxx = 0.5` 通过上面这种方式设置python

dir(model.postprocessor) 里有这些：  置信度和iou具体是怎么设置呢？
['__class__', '__delattr__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', 'is_mini_pad', 'is_scale_up', 'padding_value', 'run', 'size', 'stride']
