### ISSUE TITLE
PaddleDetection YOLOv3 (python)训练的结果，与导出后用FastDeploy(cpu+openvino)部署的结果有差别

### ISSUE THREAD

**Issue by DreamMaker777** [PaddlePaddle/FastDeploy#1234]
PaddleDetection YOLOv3 (python)训练的结果，与导出后用FastDeploy部署的结果有差别：

原版yolov3 example代码，直接将读取的原图送入推理，这样部署的结果差很多：

          auto model = fastdeploy::vision::detection::YOLOv3(model_file, params_file,
                                                               config_file, option);
            if (!model.Initialized()) {
              std::cerr << "Failed to initialize." << std::endl;
              return;
            }
          
            auto im = cv::imread(image_file);
          
            fastdeploy::vision::DetectionResult res;
            if (!model.Predict(im, &res)) { ///////直接将读取的原图送入推理
              std::cerr << "Failed to predict." << std::endl;
              return;
            }

我加上resize代码，结果就比较接近了，检测出来的框与paddledetection基本一致，但是存在漏检，且在置信度方面有差异：
            auto model = fastdeploy::vision::detection::YOLOv3(model_file, params_file,
                                                               config_file, option);
            if (!model.Initialized()) {
              std::cerr << "Failed to initialize." << std::endl;
              return;
            }
          
            auto im1 = cv::imread(image_file);
            cv::resize(im1, im, cv::Size(608, 608),0,0,cv::INTER_AREA);   /////////加入resize的代码
            fastdeploy::vision::DetectionResult res;
            if (!model.Predict(im, &res)) {    ///////直接将读取的原图送入推理
              std::cerr << "Failed to predict." << std::endl;
              return;
            }

第一张是原图(部分截图)，第二张是paddledetection结果，第三张是未resize的结果，第四张是resize后的结果
![44](https://user-images.githubusercontent.com/31379701/216756066-058d6d6f-2591-42c9-875a-15b2390d5f21.jpg)
![11](https://user-images.githubusercontent.com/31379701/216756069-0250e7e3-77f5-47f7-bf5b-fefa1c92a565.jpg)
![22](https://user-images.githubusercontent.com/31379701/216756072-446a315f-5700-400c-bc0f-7a62c91b1713.jpg)
![33](https://user-images.githubusercontent.com/31379701/216756076-4cc835e6-7fd7-4f9d-894f-372aad21a471.jpg)

未resize的结果普遍检测错误、漏检；resize后结果更好，但是置信度有差距(这张图不明显，但是很多相差10%以上，可能由此导致漏检)；查看了导出模型时生成的infer_cfg.yml文件，此文件是用于fastDeploy预处理的吗？里面含有resize操作是否在部署时没有用到？NormalizeImage、Permute等操作是否也需要自己实现？
![55](https://user-images.githubusercontent.com/31379701/216756419-6a1516ab-53a7-49d8-8e9b-962fdd18d044.jpg)

**Comment by jiangjiajun** [comment]
FastDeploy在部署时依赖于这个infer_cfg.yml文件进行预处理。我们验证过COCO数据集上训练的yolov3精度与原PaddleDetection没有差别。

当前你这里存在差异的问题，方便的话，提供以下信息，便于我们确认
- 1. PaddleDetection代码版本
- 2. 导出的YOLOv3模型和测试图片（可通过任意网盘分享，也可发送至邮箱jiangjiajun@baidu.com）
- 3. 使用PaddleDetection的推理代码及相应命令

**Comment by DreamMaker777** [comment]
> FastDeploy在部署时依赖于这个infer_cfg.yml文件进行预处理。我们验证过COCO数据集上训练的yolov3精度与原PaddleDetection没有差别。
> 
> 当前你这里存在差异的问题，方便的话，提供以下信息，便于我们确认
> 
> * 1. PaddleDetection代码版本
> * 2. 导出的YOLOv3模型和测试图片（可通过任意网盘分享，也可发送至邮箱[jiangjiajun@baidu.com](mailto:jiangjiajun@baidu.com)）
> * 3. 使用PaddleDetection的推理代码及相应命令

@jiangjiajun 感谢回复，我检查了一下整个工程，发现模型弄混了。。。经过测试训练的结果和部署的结果基本没差异。十分感谢！
