### ISSUE TITLE
服务化部署label问题

### ISSUE THREAD

**Issue by cunjing56** [PaddlePaddle/FastDeploy#1236]
*********************************************
温馨提示：根据社区不完全统计，按照模板提问，可以加快回复和解决问题的速度
*********************************************

## 环境

- 【FastDeploy版本】： [说明具体的版本，如fastdeploy-linux-gpu-0.8.0](fastdeploy:1.0.1-gpu-cuda11.4-trt8.4-21.10)
- 【系统平台】: Linux x64(Ubuntu 18.04) 
- 【硬件】： 说明具体硬件型号，如 Nvidia GPU 3080TI， CUDA 11.2 CUDNN 8.3
- 【编译语言】： Python(3.7）

## 问题日志及出现问题的操作流程
PaddleDetection 服务化部署示例
https://github.com/PaddlePaddle/FastDeploy/tree/develop/examples/vision/detection/paddledetection/serving

参考服务化部署案例，我实现了自训练的fasterRCNN模型的服务化部署，但是输出的结果里默认的类型id为0。我实际文件标注编号是1，类型是riceplant
![image](https://user-images.githubusercontent.com/112528302/216896934-85dd6785-28e8-4002-b390-6fd31a01b8da.png)
这种情况在本地预测的时候也出现过，是这个Testdataset的标注路径的失效导致的。现在是这个json应该放在服务化部署的哪个路径上？
![image](https://user-images.githubusercontent.com/112528302/216897215-38e000de-5b79-49bf-949f-94c69df6d31e.png)

当前我只是有一个标记，可以自己改一下编号就过去了，但是当类型多起来的时候，谁是谁，这怎么分辨？所以希望能知道这样的问题根本的解决方法是什么？

**Comment by jiangjiajun** [comment]
自行写在后处理里面。
- 后处理初始化时，加载一个label_list
- 接收到预测结果后，根据label_list，将id转为标签

**Comment by cunjing56** [comment]
> 自行写在后处理里面。
> 
> * 后处理初始化时，加载一个label_list
> * 接收到预测结果后，根据label_list，将id转为标签

没懂，如何关联预测结果的类别编号跟我标记数据的类别编号呢？就是有5个目标，结果出来0,1,2,3,4，难道就能对应我标记数据的1,2,3,4,5？

**Comment by cunjing56** [comment]
> 自行写在后处理里面。
> 
> * 后处理初始化时，加载一个label_list
> * 接收到预测结果后，根据label_list，将id转为标签

现在是类编的编号不清楚是怎么定义的。我明明输入的是1，为什么会输出0，我想从源头改了。你说都输出来了，我再改，不是猜吗？十几种虫子我也不认识谁是1谁是2 啊，你能懂吗？

**Comment by jiangjiajun** [comment]
这个id与标签的顺序，参考PaddleDetection模型导出的infer_cfg.yml文件。 查看里面有一栏labels的字段，0~n对应于这个Labels中各个标签的顺序

**Comment by cunjing56** [comment]
> 这个id与标签的顺序，参考PaddleDetection模型导出的infer_cfg.yml文件。 查看里面有一栏labels的字段，0~n对应于这个Labels中各个标签的顺序

太感谢了，要的就是这句话！
