### ISSUE TITLE
Support C API

### ISSUE THREAD

**Issue by taojishou** [PaddlePaddle/FastDeploy#1257]
fastdeploy有c的api吗？我们想通过cgo调用

**Comment by jiangjiajun** [comment]
https://github.com/PaddlePaddle/FastDeploy/pull/1217 正在开发中，预计会很快有一个版本。

现在你们通过C API是想部署什么模型在什么硬件上呢？

**Comment by taojishou** [comment]
希望通过go调用，硬件的话目前是x86

**Comment by jiangjiajun** [comment]
现在是想部署哪些模型呢？

C API的封装，对于模型会按优先级进行支持，目前正在支持PaddleDetection/PaddleClas/PaddleSeg/PaddleOCR模型

**Comment by taojishou** [comment]
PaddleDetection和PaddleOCR这些模型会多一些

**Comment by taojishou** [comment]
capi的话 后面会支持比如rv1126这样的吗

**Comment by jiangjiajun** [comment]
都可以支持，但会按照优先级来开发。例如最优先的是CPU/GPU，你也可以提更多硬件的需求给到我们

**Comment by taojishou** [comment]
好的，预计什么时候可以支持PaddleDetection的 cpu/gpu的capi

**Comment by rainyfly** [comment]
下周末可以尝试使用，我们需要补充一下文档
