### ISSUE TITLE
paddle模型转换为rknn模型报错

### ISSUE THREAD

**Issue by chenjf2015103095** [PaddlePaddle/FastDeploy#1258]
运行环境：
rknn版本：rknn_toolkit2-1.3.0_11912b58-cp38-cp38-linux_x86_64.whl
paddlepaddle：2.4.1
paddle2onnx:1.0.5
onnx:1.7.0

问题描述：
在github上下载的picodet_s_416_coco_lcnet模型进行模型的转换，pd-->onnx-->rknn进行转换
其中在onnx-->rknn模型报错：
root@linux:/media/workspace/fd_serving/FastDeploy# python3 tools/rknpu2/export.py --config_path tools/rknpu2/config/RK3588/picodet_s_416_coco_lcnet.yaml 
{'model_path': '/media/workspace/rknn_rknpu2/picodet_s_416_coco_lcnet/picodet_s_416_coco_lcnet.onnx', 'output_folder': '/media/workspace/rknn_rknpu2/picodet_s_416_coco_lcnet/picodet_s_416_coco_lcnet', 'target_platform': 'RK3588', 'normalize': {'mean': [[0.485, 0.456, 0.406]], 'std': [[0.229, 0.224, 0.225]]}, 'outputs': ['p2o.Div.79', 'p2o.Concat.9']}
W __init__: rknn-toolkit2 version: 1.3.0-11912b58
<class 'list'>
yaml_config["outputs"] =  ['p2o.Div.79', 'p2o.Concat.9']
W load_onnx: It is recommended onnx opset 12, but your onnx model opset is 11!
E load_onnx: Catch exception when loading onnx model: /media/workspace/rknn_rknpu2/picodet_s_416_coco_lcnet/picodet_s_416_coco_lcnet.onnx!
E load_onnx: Traceback (most recent call last):
E load_onnx:   File "rknn/api/rknn_base.py", line 1157, in rknn.api.rknn_base.RKNNBase.load_onnx
E load_onnx: UnboundLocalError: local variable 'inp' referenced before assignment
Traceback (most recent call last):
  File "tools/rknpu2/export.py", line 57, in <module>
    assert ret == 0, "Load model failed!"
AssertionError: Load model failed!

**Comment by Zheng-Bicheng** [comment]
```
pip uninstall onnx
pip install onnx==1.10.0
```

**Comment by Zheng-Bicheng** [comment]
另外建议选择绿色的Mul节点作为输出节点
<img width="1400" alt="image" src="https://user-images.githubusercontent.com/58363586/217416761-6bc113cd-adcd-44aa-b6fb-b9c367953935.png">

**Comment by Zheng-Bicheng** [comment]
还有，你这个rknn转换工具为什么是1.3.0的版本，现在都更新到1.4.0了

**Comment by Zheng-Bicheng** [comment]
解决了吗
