### ISSUE TITLE
预编译库Linux aarch64  C++ SDK下载链接失效

### ISSUE THREAD

**Issue by cgisky1980** [PaddlePaddle/FastDeploy#1262]
(https://github.com/PaddlePaddle/FastDeploy/blob/develop/docs/cn/build_and_install/download_prebuilt_libraries.md)
预编译库  C++ SDK

Linux aarch64   | fastdeploy-linux-aarch64-1.0.3.tgz
下载链接失效

**Comment by jiangjiajun** [comment]
@cgisky1980  已解决

**Comment by cgisky1980** [comment]
> @cgisky1980 已解决
编译倒是成功了  cpu 推理貌似不行啊
~/src/NLP/build$ ./infer_demo uie-base 0
[ERROR] fastdeploy/runtime/runtime_option.cc(143)::UsePaddleBackend     The FastDeploy didn't compile with Paddle Inference.
Aborted (core dumped)

**Comment by cgisky1980** [comment]
哦 明白了 Linux aarch64和Mac OSX下仅集成ONNX Runtime模块

**Comment by jiangjiajun** [comment]
在Linua aarch64下仅集成PaddleLite和ONNX Runtime模块
