### ISSUE TITLE
怎样把模型转换为json格式

### ISSUE THREAD

**Issue by WanderAlphonse** [PaddlePaddle/FastDeploy#1263]
`model = fd.vision.detection.YOLOv5(
model_file=os.path.join(ROOT, 'best.onnx'),
runtime_option=runtime_option)

model = model.to_json() #这个方法似乎是不可用的
`

**Comment by jiangjiajun** [comment]
没有支持这种方式。 转成json的需求是什么呢？

**Comment by WanderAlphonse** [comment]
> 没有支持这种方式。 转成json的需求是什么呢？

我记得TensorFlow是支持转成json的，我不是什么编程高手，对我而言，特别是tensorrt模式下这个模型加载速度太慢了，我想把这个模型加载放入一个flask的文件中，然后用flask返回一个json格式的模型，从而我能在另一个文件使用requests.get方法获取到这个模型，这样我只需要保持flask app为启动状态，后续我调试时就可以无限获取这个模型了而不是每次都加载它，因为flask返回值不支持直接返回model格式的数据，所以我想把model转换成json格式，而flask是支持返回json格式的。

当然，我不知道是否有其他更简单的方法来实现我的需求，如果有的话请麻烦你告诉我，谢谢了

**Comment by jiangjiajun** [comment]
TensorRT模型加载速度慢的问题，在如下文档第2个问题中有提到解决方案，看是否能满足你的需求

https://github.com/PaddlePaddle/FastDeploy/blob/develop/docs/cn/faq/tensorrt_tricks.md
