### ISSUE TITLE
Windows下编译后报错

### ISSUE THREAD

**Issue by fyy0114** [PaddlePaddle/FastDeploy#1268]
*********************************************
温馨提示：根据社区不完全统计，按照模板提问，可以加快回复和解决问题的速度
*********************************************

## 环境

- 【FastDeploy版本】： fastdeploy-win-x64-1.0.3
- 【系统平台】: Windows x64(Windows11)
- 【硬件】： i7-12700K/Redeon RX 6750XT
- 【编译语言】： C++ 
- 【编译平台】： cmake + vs 2022 

## 问题日志及出现问题的操作流程
 准备用预编译好的CPU环境下Windows C++ SDK加载PPYOLOE coco 300的模型进行推理，先写了一点基本的代码加载库，可以编译成功，将所需dll复制到build/DEBUG目录下运行程序，结果报错

![WXWorkLocal_167584613342](https://user-images.githubusercontent.com/103732515/217480364-69e2819a-0609-40d6-a751-c65d93f8c254.png)

代码只有短短一行
```
#include "fastdeploy/vision.h"

int main(){
	fastdeploy::RuntimeOption option;
	
	return 0;
}

```
直接运行的报错如下图

![image](https://user-images.githubusercontent.com/103732515/217480980-544b144a-94f1-413b-a5cf-40ccb2fc8ddb.png)

编译的cmakelists文件如下

```
cmake_minimum_required(VERSION 3.0.0)
project(__TIMESTAMP__ VERSION 0.1.0)

set(CMAKE_CXX_STANDARD 11)

include(CTest)

find_package(FastDeploy REQUIRED)
include_directories(${FASTDEPLOY_INCS})

add_executable(main test.cpp)

target_link_libraries(main ${FASTDEPLOY_LIBS})


set(CPACK_PROJECT_NAME ${PROJECT_NAME})
set(CPACK_PROJECT_VERSION ${PROJECT_VERSION})

include(CPack)
```

**Comment by DefTruth** [comment]
现在不支持Debug模式，只支持release模式，可以切换到release模式试一下

**Comment by jiangjiajun** [comment]
- 1. 不支持Debug模式，需切换到Release
- 2. 编译的exe可执行程序在运行时，需将所有依赖的dll文件拷贝到exe所在目录。鉴于手动拷贝可能会遗留，出现上面的错误提示，建议参考这个文档，使用`fastdeploy_init.bat`来批量拷贝
https://github.com/PaddlePaddle/FastDeploy/blob/develop/docs/cn/faq/use_sdk_on_windows.md

**Comment by fyy0114** [comment]
> * 1. 不支持Debug模式，需切换到Release
> * 2. 编译的exe可执行程序在运行时，需将所有依赖的dll文件拷贝到exe所在目录。鉴于手动拷贝可能会遗留，出现上面的错误提示，建议参考这个文档，使用`fastdeploy_init.bat`来批量拷贝
>      https://github.com/PaddlePaddle/FastDeploy/blob/develop/docs/cn/faq/use_sdk_on_windows.md


> 现在不支持Debug模式，只支持release模式，可以切换到release模式试一下

您好，按照您说的使用cmake添加
`install_fastdeploy_libraries(${CMAKE_CURRENT_BINARY_DIR}/Release)`
已经解决问题，感谢！
