### ISSUE TITLE
服务化部署PPOCRv3,内存占用不释放

### ISSUE THREAD

**Issue by wxz5459** [PaddlePaddle/FastDeploy#1271]
## 环境

- 【FastDeploy版本】： paddlepaddle/fastdeploy:1.0.3-cpu-only-21.10 参考示例服务化部署ppocrv3

## 问题日志及出现问题的操作流程
- 【性能问题】描述清楚对比的方式
- - backend为paddle和openvino,多并发请求OCR服务（500张图片，10并发）
1、默认配置（动态shape）,内存占用快速增长且推理结束后不释放
2、固定infer shape后，内存占用增长速度变缓，但内存占用依旧不释放

**Comment by heliqi** [comment]
1. 如果使用onnxruntime后端是否有问题？
2. 服务端的paddle/openvino配置能发下吗？ 测试的图片如果可以也提供下，不好发图片提供下图片的shape。方便我这边复现问题

**Comment by wxz5459** [comment]
1、切换ONNX依然存在占用不释放问题
2、访问OCR服务前将图片统一resize到(960,960),内容均为百度搜索中的财报图片
3、两个新问题：det模块的paddle后端输出存在问题，其他后端正常；openvino后端无法达到指定并发数，理论上应该是16(det)+16(rec) = 32,测试下来只有16,其他后端能够达到32。
对det_postprocess代码进行了修改：删除了cls模块，加上rec_batch_num的限制
**det_postprocess代码:**

    def initialize(self, args):
        """`initialize` is called only once when the model is being loaded.
        Implementing `initialize` function is optional. This function allows
        the model to intialize any state associated with this model.
        Parameters
        ----------
        args : dict
          Both keys and values are strings. The dictionary keys and values are:
          * model_config: A JSON string containing the model configuration
          * model_instance_kind: A string containing model instance kind
          * model_instance_device_id: A string containing model instance device ID
          * model_repository: Model repository path
          * model_version: Model version
          * model_name: Model name
        """
        # You must parse model_config. JSON string is not parsed here
        self.model_config = json.loads(args['model_config'])
        print("model_config:", self.model_config)

        self.input_names = []
        for input_config in self.model_config["input"]:
            self.input_names.append(input_config["name"])
        print("postprocess input names:", self.input_names)

        self.output_names = []
        self.output_dtype = []
        for output_config in self.model_config["output"]:
            self.output_names.append(output_config["name"])
            dtype = pb_utils.triton_string_to_numpy(output_config["data_type"])
            self.output_dtype.append(dtype)
        print("postprocess output names:", self.output_names)
        self.postprocessor = fd.vision.ocr.DBDetectorPostprocessor()
        self.rec_preprocessor = fd.vision.ocr.RecognizerPreprocessor()
        self.cls_threshold = 0.9
        self.rec_batch_num = 6

    def execute(self, requests):
        """`execute` must be implemented in every Python model. `execute`
        function receives a list of pb_utils.InferenceRequest as the only
        argument. This function is called when an inference is requested
        for this model. Depending on the batching configuration (e.g. Dynamic
        Batching) used, `requests` may contain multiple requests. Every
        Python model, must create one pb_utils.InferenceResponse for every
        pb_utils.InferenceRequest in `requests`. If there is an error, you can
        set the error argument when creating a pb_utils.InferenceResponse.
        Parameters
        ----------
        requests : list
          A list of pb_utils.InferenceRequest
        Returns
        -------
        list
          A list of pb_utils.InferenceResponse. The length of this list must
          be the same as `requests`
        """
        responses = []
        for request in requests:
            infer_outputs = pb_utils.get_input_tensor_by_name(
                request, self.input_names[0])
            im_infos = pb_utils.get_input_tensor_by_name(request,
                                                         self.input_names[1])
            ori_imgs = pb_utils.get_input_tensor_by_name(request,
                                                         self.input_names[2])

            infer_outputs = infer_outputs.as_numpy()
            im_infos = im_infos.as_numpy()
            ori_imgs = ori_imgs.as_numpy()

            results = self.postprocessor.run([infer_outputs], im_infos)
            batch_rec_texts = []
            batch_rec_scores = []
            batch_box_list = []
            for i_batch in range(len(results)):

                cls_labels = []
                cls_scores = []
                rec_texts = []
                rec_scores = []

                box_list = fd.vision.ocr.sort_boxes(results[i_batch])
                image_list = []
                if len(box_list) == 0:
                    image_list.append(ori_imgs[i_batch])
                else:
                    for box in box_list:
                        crop_img = get_rotate_crop_image(ori_imgs[i_batch],
                                                         box)
                        image_list.append(crop_img)

                batch_box_list.append(box_list)

                width_list = []
                for img in image_list:
                    width_list.append(img.shape[1] / float(img.shape[0]))
                indices = np.argsort(np.array(width_list))

                rec_texts_np = np.array([])
                rec_scores_np = np.array([])
                for beg_img_no in range(0, len(image_list), self.rec_batch_num):
                    end_img_no = min(len(image_list), beg_img_no + self.rec_batch_num)
                    batch_img_list = []
                    
                    for ino in range(beg_img_no,end_img_no):
                        batch_img_list.append(image_list[indices[ino]])
                    rec_pre_tensors = self.rec_preprocessor.run(batch_img_list)
                    # rec_pre_tensors = self.rec_preprocessor.run(image_list[beg_img_no:end_img_no])
                    rec_dlpack_tensor = rec_pre_tensors[0].to_dlpack()
                    rec_input_tensor = pb_utils.Tensor.from_dlpack(
                        "x", rec_dlpack_tensor)

                    inference_request = pb_utils.InferenceRequest(
                        model_name='rec_pp',
                        requested_output_names=['rec_texts', 'rec_scores'],
                        inputs=[rec_input_tensor])
                    inference_response = inference_request.exec()
                    if inference_response.has_error():
                        raise pb_utils.TritonModelException(
                            inference_response.error().message())
                    else:
                        # Extract the output tensors from the inference response.
                        rec_texts = pb_utils.get_output_tensor_by_name(
                            inference_response, 'rec_texts')
                        rec_texts = rec_texts.as_numpy()
                        rec_texts_np = np.append(rec_texts_np,rec_texts)

                        rec_scores = pb_utils.get_output_tensor_by_name(
                            inference_response, 'rec_scores')
                        rec_scores = rec_scores.as_numpy()
                        rec_scores_np = np.append(rec_scores_np,rec_scores)

                batch_rec_texts.append(rec_texts_np)
                batch_rec_scores.append(rec_scores_np)

            out_tensor_0 = pb_utils.Tensor(
                self.output_names[0],
                np.array(
                    batch_rec_texts, dtype=np.object_))
            out_tensor_1 = pb_utils.Tensor(self.output_names[1],
                                           np.array(batch_rec_scores))
            out_tensor_2 = pb_utils.Tensor(self.output_names[2],
                                           np.array(batch_box_list))
            inference_response = pb_utils.InferenceResponse(
                output_tensors=[out_tensor_0, out_tensor_1, out_tensor_2])
            responses.append(inference_response)
        return responses

    def finalize(self):
        """`finalize` is called only once when the model is being unloaded.
        Implementing `finalize` function is optional. This function allows
        the model to perform any necessary clean ups before exit.
        """
        print('Cleaning up...')

**det和rec的配置：**
#---------------
instance_group [
  {
    # The number of instances is 1
    count: 4
    # Use GPU, CPU inference option is:KIND_CPU
    kind: KIND_CPU
  }
]

optimization {
  execution_accelerators {
    # cpu_execution_accelerator : [
    #   {
    #     name : "paddle"
    #     # 设置推理并行计算线程数为4
    #     parameters { key: "cpu_threads" value: "16" }
    #     # 开启mkldnn加速，设置为0关闭mkldnn
    #     parameters { key: "use_mkldnn" value: "1" }
    #   }
    # ]

    cpu_execution_accelerator : [
      {
        name : "openvino"
        # 设置推理并行计算线程数为4
        parameters { key: "cpu_threads" value: "16" }
        parameters { key: "num_streams" value: "4" }
      }
    ]

    # cpu_execution_accelerator : [
    #   {
    #     name : "onnxruntime"
    #     # 设置推理并行计算线程数为4
    #     parameters { key: "cpu_threads" value: "16" }
    #   }
    # ]
  }
}

**Comment by heliqi** [comment]
好的，我们这边看下你说的几个问题，后面有结论给你反馈 @wxz5459

**Comment by dzz10** [comment]
我想知道这个内存一直增加的问题修复了吗,fastdeploy-win-x64-1.0.7此问题依旧.
从700M一直加加加,到2G了

**Comment by dzz10** [comment]
@wxz5459 问题解决了吗

**Comment by wxz5459** [comment]
用static shape，内存就不会无序增长了
或者升级openvino版本，也可以有效缓解这个问题

**Comment by dzz10** [comment]
@wxz5459 static shape要怎么做呢,我输入的图像大小都是一样的.
gpt告诉我要导出模型再弄配置文件,我感觉它又在打胡乱说了.
