### ISSUE TITLE
MaskRCNN的结果图片中没有mask

### ISSUE THREAD

**Issue by wang-xinyu** [PaddlePaddle/FastDeploy#1272]
## 环境

- 【FastDeploy版本】： develop branch
- 【编译命令】cmake .. -DENABLE_ORT_BACKEND=OFF \
         -DENABLE_TRT_BACKEND=ON \
         -DENABLE_PADDLE_BACKEND=ON \
         -DENABLE_OPENVINO_BACKEND=OFF \
         -DWITH_GPU=ON \
         -DTRT_DIRECTORY=/workspace/TensorRT-8.4.1.5 \
         -DENABLE_VISION=ON \
         -DENABLE_TEXT=OFF \
         -DENABLE_CVCUDA=ON \
         -DCMAKE_INSTALL_PREFIX=${PWD}/fastdeploy-dev
- 【系统平台】: Linux x64(Ubuntu 20.04.4 LTS)
- 【硬件】： 说明具体硬件型号，如 Nvidia GPU T4， CUDA 11.7
- 【编译语言】： python3.8

## 问题日志及出现问题的操作流程

```
cd FastDeploy/examples/vision/detection/paddledetection/python

python3 infer_mask_rcnn.py --model mask_rcnn_r50_1x_coco --image 000000014439.jpg
```

![1222638b12698c1b04a08970c04274fd](https://user-images.githubusercontent.com/15235574/217498258-c6104d99-b7fd-4ae9-8f96-d95eefc8dd2b.jpg)

**Comment by qianbin1989228** [comment]
我也遇到了一样的问题

**Comment by panp4n** [comment]
输出的结果中就没有。

**Comment by panp4n** [comment]
请问该问题解决了吗

**Comment by qianbin1989228** [comment]
> 请问该问题解决了吗
 
官方主力大部队都去搞文心一言了，这里感觉越来越静悄悄了
