### ISSUE TITLE
 paddlenlp 的C++库 在哪?

### ISSUE THREAD

**Issue by cgisky1980** [PaddlePaddle/FastDeploy#1277]
*********************************************
温馨提示：根据社区不完全统计，按照模板提问，可以加快回复和解决问题的速度
*********************************************

## 环境

- 【FastDeploy版本】： fastdeploy-linux-aarch64-1.0.3
- 【系统平台】: Linux aarch64(Ubuntu 18.04) 
- 【硬件】： RK3588
- 【编译语言】： C++

## 问题日志及出现问题的操作流程
https://github.com/PaddlePaddle/FastDeploy/tree/develop/examples/text/uie/cpp/
c++的例子 make 的时候报错
error: ‘paddlenlp’ is not a namespace-name
 using namespace paddlenlp;
这个 paddlenlp 的C++库 在哪?

**Comment by jiangjiajun** [comment]
@cgisky1980 昨天你在提issue时，我临时编译了一个包上传上去，但是没有开启`ENABLE_TEXT`选项。 我刚重新再编译并开启了`ENABLE_TEXT`，麻烦重新下载后使用

**Comment by cgisky1980** [comment]
好~~感谢
