### ISSUE TITLE
如何筛选 yolov5  推理的结果

### ISSUE THREAD

**Issue by HiaHong** [PaddlePaddle/FastDeploy#1279]
## Environment

FastDeploy version: e.g 0.8.0 or the latest code in develop branch
OS Platform:  Windows x64 
Hardware: e.g. Nvidia GPU 3080Ti  CUDA 11.2 CUDNN 8.3
Program Language: e.g. Python 3.7

`DetectionResult: [xmin, ymin, xmax, ymax, score, label_id]
1110.355835,425.777344, 1257.300659, 522.001709, 0.829359, 0
558.526306,659.826904, 719.997986, 751.881592, 0.823671, 0
1248.770752,426.186157, 1408.032959, 524.551147, 0.814135, 0
759.281067,682.981812, 840.883850, 774.683960, 0.809666, 0
750.875183,540.860107, 925.318909, 660.229492, 0.806654, 0
1808.166016,467.900391, 2105.863281, 555.792969, 0.806545, 2
1341.073242,541.609497, 1469.515625, 648.473511, 0.804522, 0
1154.162842,691.180542, 1220.338623, 774.633179, 0.795894, 0
412.432709,659.394653, 554.675232, 799.230347, 0.795412, 0
605.183289,479.122070, 714.999939, 615.235107, 0.794305, 0
1016.549805,423.201172, 1118.640625, 522.117188, 0.794164, 1`

比如要筛选score大于 0.8 或者 label_id 为 '1' 的结果

## Problem description
Please attach the log file if there's problem happend.

**Comment by jiangjiajun** [comment]
```
result = model.predict(im)

boxes = list()
for i in range(len(result.boxes)):
    if result.scores[i] > 0.8 and result.label_ids[i] == '1':
        boxes.append(result.boxes[i])
```

**Comment by HiaHong** [comment]
非常感谢,回复速度超级好评
但是
同时筛选score大于 0.8 并且label_id 为 '1' 的结果 返回的boxes 是 [ ],没有结果

**Comment by jiangjiajun** [comment]
那就说明没有结果

**Comment by HiaHong** [comment]
事实上是有的,发现问题了,数据类型的问题

result.label_ids[i] == '1' 改成 str(result.label_ids[i])  == '1'
或者
result.label_ids[i] == '1' 改成 result.label_ids[i] == 1

`result = model.predict(im)

boxes = list()
for i in range(len(result.boxes)):
    if result.scores[i] > 0.8 and str(result.label_ids[i]) == '1':
        boxes.append(result.boxes[i])`
