### ISSUE TITLE
fastdeploy 对jenston 平台是否可以增加 开启/关闭DLA，以及 支持 Int8 量化相关API

### ISSUE THREAD

**Issue by shanyu155** [PaddlePaddle/FastDeploy#1284]
Nvidia  DLA:
<img width="284" alt="b2bbfa6814264b0c0885461b42c449f" src="https://user-images.githubusercontent.com/27769380/217740560-ae8b8a8d-9e6d-4a1d-aca1-318b392a6ff4.png">

kINT8 :
![image](https://user-images.githubusercontent.com/27769380/217743128-c432fc8f-1430-409c-8e8a-e530bb70a09c.png)

**Comment by jiangjiajun** [comment]
支持量化模型加载，无需用户手动设置，只要加载的是量化模型，便会自动使用INT8精度推理
