### ISSUE TITLE
fastdeploy::vision::segmentation::PaddleSegModel(model_dir） 如何解决加载模型路径为中文  

### ISSUE THREAD

**Issue by teymur-git** [PaddlePaddle/FastDeploy#1296]
******
fastdeploy::vision::segmentation::PaddleSegModel(model_dir）中文路径就会失败，该如何解决
![image](https://user-images.githubusercontent.com/60127735/218004720-5d8c99cf-90f7-4247-883a-1df555ed0bc6.png)

## 环境

- 【FastDeploy版本】： 说明具体的版本，如fastdeploy-win10-gpu-0.8.0
- 【编译命令】如果您是自行编译的FastDeploy，请说明您的编译方式（参数命令）
- 【系统平台】: Windows x64(Windows10) 
- 【硬件】： 用的cpu
- 【编译语言】： C++

**Comment by DefTruth** [comment]
一般情况下，不建议使用中文路径哈，很容易会遇到字符编码问题，可以改成英文路径

**Comment by teymur-git** [comment]
想解决，有没有解决方法

**Comment by teymur-git** [comment]
@DefTruth 想解决，有没有解决方法

**Comment by hhxdestiny** [comment]
> 一般情况下，不建议使用中文路径哈，很容易会遇到字符编码问题，可以改成英文路径

同问，调用层如何改编码都不行

**Comment by GengGode** [comment]
传入路径之前做一下字符串编码转换？
内部应该默认走的gbk编码吧，提前转换过去试试

**Comment by MistEO** [comment]
有兴趣可以参考 [我们的 fork](https://github.com/MaaAssistantArknights/FastDeploy/blob/master/fastdeploy/runtime.cc#L216)

自行读取后通过 option 传入 buffer，[demo](https://github.com/MaaAssistantArknights/MaaAssistantArknights/blob/dev/src/MaaCore/Config/Miscellaneous/OcrPack.cpp#L139)
