### ISSUE TITLE
使用fastdeploy部署ppocrv3， npu推断，时间很长

### ISSUE THREAD

**Issue by EasyIsAllYouNeed** [PaddlePaddle/FastDeploy#1299]
*********************************************
温馨提示：根据社区不完全统计，按照模板提问，可以加快回复和解决问题的速度
*********************************************

## 环境

- 【FastDeploy版本】： 说明具体的版本，如fastdeploy-linux-gpu-0.8.0
- fastdeploy
- 【编译命令】如果您是自行编译的FastDeploy，请说明您的编译方式（参数命令）
- 【系统平台】: Linux x64(Ubuntu 18.04) / Windows x64(Windows10) / Mac OSX arm(12.0) / Mac OSX intel(12.0)
-  Linux x64 麒麟10
- 【硬件】： 说明具体硬件型号，如 Nvidia GPU 3080TI， CUDA 11.2 CUDNN 8.3
- 华为atlas300i，cann5.1.2
- 【编译语言】： C++ / Python(3.7或3.8等）
Python3.9
## 问题日志及出现问题的操作流程
使用fastdeploy，ppocrv3， npu推断，时间很长
- 附上详细的问题日志有助于快速定位分析
[log.txt](https://github.com/PaddlePaddle/FastDeploy/files/10707227/log.txt)

- 【模型跑不同】
- - 先执行`examples`下的部署示例，包括使用examples提供的模型，确认是否可以正确执行
- - 如若`examples`下的代码可以运行，但自己的模型，或自己的代码不能运行
- - - 提供复现问题的 代码+模型+错误log，供工程师快速定位问题
- 【模型精度问题】
- - 先执行`examples`下的部署示例，包括使用examples提供的模型，确认是否可以正确执行
- - 如若`examples`下的代码可以运行，但自己的模型，或自己的代码不能运行
- - - 提供复现问题的 代码+模型+错误log，供工程师快速定位问题
- 【性能问题】描述清楚对比的方式
- - 注意性能测试，循环跑N次，取后80%的用时平均（模型启动时，刚开始受限于资源分配，速度会较慢）
- - FastDeploy的Predict包含模型本身之外的数据前后处理用时
- - - 提供复现问题的 代码+模型+错误log，供工程师快速定位问题

**Comment by yunyaoXYY** [comment]
你好，

从你的log里，我没有看到 "./driver/huawei_ascend_npu/driver.cc:70 CreateProgram] Create program for huawei_ascend_npu." 这样的log， 看起来似乎并没有成功用上Ascend的推理卡. 可以检查一下驱动和固件.

同时, 推理的过程中，还可以通过 npu-smi info来查看Ascend推理卡是否在正常工作.
