### ISSUE TITLE
[ERROR] fastdeploy/runtime/backends/ort/ort_backend.cc(278)::fastdeploy::OrtBackend::Infer      Failed to Infer: Got invalid dimensions for input: images for the following indices

### ISSUE THREAD

**Issue by monkeycc** [PaddlePaddle/FastDeploy#1303]
[ERROR] fastdeploy/runtime/backends/ort/ort_backend.cc(278)::fastdeploy::OrtBackend::Infer      Failed to Infer: Got invalid dimensions for input: images for the following indices

yolov8 onnx  1280
报错

解决方法 
`model.preprocessor.size = [1280, 1280]`

**Comment by jiangjiajun** [comment]
所以解决了是吗？

**Comment by monkeycc** [comment]
解决了

这个希望在文档中  增加一下说明
