### ISSUE TITLE
onnx部署问题

### ISSUE THREAD

**Issue by GreenAvocado92** [PaddlePaddle/FastDeploy#1316]
根据官网教程编译，模型也没官网提供，在win下运行，报错如下：
![image](https://user-images.githubusercontent.com/91200482/218648365-023a53b8-82d6-4766-a71d-1a9e87db2851.png)

**Comment by jiangjiajun** [comment]
需要将所有的dll拷贝至exe所在目录下，参考这篇文档的使用方式 https://github.com/PaddlePaddle/FastDeploy/blob/develop/docs/cn/faq/use_sdk_on_windows.md

**Comment by GreenAvocado92** [comment]
> 需要将所有的dll拷贝至exe所在目录下，参考这篇文档的使用方式 https://github.com/PaddlePaddle/FastDeploy/blob/develop/docs/cn/faq/use_sdk_on_windows.md

这个是没有问题的，但是我用来部署yolov5.onnx(fastdeploy提供的)，没有反应，代码如下：
![image](https://user-images.githubusercontent.com/91200482/218660539-37555889-9e33-4f64-848d-8521c429fc9b.png)

**Comment by jiangjiajun** [comment]
注意使用Release模式编译（不支持Debug模式）。另外你这里说的“没反应”是指什么

**Comment by GreenAvocado92** [comment]
> 
使用的是Release, 没反应是指：我用win编译生成了exe，双击exe弹出的命令窗口是黑色的，并没有cout任何内容，同时，电脑变的很卡

**Comment by ShawnXsw** [comment]
> > 
> 
> 使用的是Release, 没反应是指：我用win编译生成了exe，双击exe弹出的命令窗口是黑色的，并没有cout任何内容，同时，电脑变的很卡

@GreenAvocado92  我猜你编译开了OPENVINO，运行时拷贝dll时候缺少了一个openvino的plugins.xml，放进去就好

**Comment by GreenAvocado92** [comment]
> 
重新编译了，确实是这个问题，为啥就不能先提示下呢

**Comment by GreenAvocado92** [comment]
> > > 
> > 
> > 
> > 使用的是Release, 没反应是指：我用win编译生成了exe，双击exe弹出的命令窗口是黑色的，并没有cout任何内容，同时，电脑变的很卡
> 
> @GreenAvocado92 我猜你编译开了OPENVINO，运行时拷贝dll时候缺少了一个openvino的plugins.xml，放进去就好

**Comment by GreenAvocado92** [comment]
fastdeploy上提供的yolov5.onnx的模型是怎么来的
