### ISSUE TITLE
主体检测模型picodet_lcnet_x2_5_640_mainbody_infer报错

### ISSUE THREAD

**Issue by truthsun22** [PaddlePaddle/FastDeploy#1332]
主体检测模型是picodet_lcnet_x2_5_640_mainbody_infer，调用examples\vision\detection\paddledetection\python\infer_picodet.py来检测，报如下错误
[ERROR] fastdeploy/vision/detection/ppdet/postprocessor.cc(26)::fastdeploy::vision::detection::PaddleDetPostprocessor::ProcessMask	The data type of out mask tensor should be INT32, but now it's FDDataType::FP32
[ERROR] fastdeploy/vision/detection/ppdet/base.cc(75)::fastdeploy::vision::detection::PPDetBase::BatchPredict	Failed to postprocess the inference results by runtime.
另外，lite版的主体检测模型picodet_PPLCNet_x2_5_mainbody_lite_v1.0_infer，也不行

**Comment by jiangjiajun** [comment]
你的PicoDet模型来源是哪里呢，麻烦检查下这个模型的输出是否是2个？

**Comment by truthsun22** [comment]
> 你的PicoDet模型来源是哪里呢，麻烦检查下这个模型的输出是否是2个？

页面在https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.5/configs/picodet/legacy_model/application/mainbody_detection/README.md，模型下载地址是https://paddledet.bj.bcebos.com/models/picodet_lcnet_x2_5_640_mainbody_infer.tar
输出2个是什么意思？
另外，lite版的主体检测模型也不行，lite版在页面https://github.com/PaddlePaddle/PaddleClas/blob/release/2.5/docs/zh_CN/training/PP-ShiTu/mainbody_detection.md，模型下载地址是https://paddle-imagenet-models-name.bj.bcebos.com/dygraph/rec/models/inference/picodet_PPLCNet_x2_5_mainbody_lite_v1.0_infer.tar，用FD推理报
Traceback (most recent call last):
  File "E:\ai\paddle\fastdeploy\FastDeploy\examples\vision\detection\paddledetection\python\infer_picodet.py", line 57, in <module>
    model = fd.vision.detection.PicoDet(
  File "E:\Anaconda\envs\paddle2.4\lib\site-packages\fastdeploy\vision\detection\ppdet\__init__.py", line 225, in __init__
    self._model = C.vision.detection.PicoDet(
RuntimeError: Check 'false' failed at C:\Jenkins\workspace\private-ci\ie\build-windows-vs2019\b\repos\openvino\src\frontends\paddle\src\frontend.cpp:60:
FrontEnd API failed with OpConversionFailure: :
Fail to convert fill_constant Exception Check 'false' failed at C:\Jenkins\workspace\private-ci\ie\build-windows-vs2019\b\repos\openvino\src\frontends\paddle\src\op\fill_constant.cpp:29:
FrontEnd API failed with OpValidationFailure: While validating node 'fill_constant':
fill_constant only supports i32, f32, i64

**Comment by jiangjiajun** [comment]
这个模型虽然名字叫PicoDet，但并没有包含NMS等操作，建议跟PaddleDetection的同学确认模型输出含义。或者是否能提供包含NMS的模型

**Comment by truthsun22** [comment]
> 这个模型虽然名字叫PicoDet，但并没有包含NMS等操作，建议跟PaddleDetection的同学确认模型输出含义。或者是否能提供包含NMS的模型

谢谢，那lite版那个呢？FD的PicoDet是不支持int8吗？

**Comment by jiangjiajun** [comment]
Lite版提供的模型应该是基于比较老版本的PaddleDetection保存下来的模型，存在while控制流（在FD里面应该可以使用Paddle Inference/Paddle Lite后端部署，不能使用ORT，OpenVINO等后端）。最新的PaddleDetection模型导出的PicoDet模型不存在while控制流，各后端都能支持

**Comment by huge3286** [comment]
您好，我最近也需要部署主体检测模型，请问您找到解决方案了吗。官方提供的其它模型可以使用吗。
就比如下面这个链接里的模型都提供了ONNX
https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.6/configs/picodet

**Comment by tomjeans** [comment]
老版本模型 output.size()==7需要重新写后处理 可以参考下paddlelite postprocess那块
