### ISSUE TITLE
win11人脸检测SCRFD模型predict方法异常结束

### ISSUE THREAD

**Issue by Plz-Thx** [PaddlePaddle/FastDeploy#1335]
- 【FastDeploy版本】： fastdeploy-win-x64-1.0.3
- 【编译命令】官方C++ Release SDK
- 【系统平台】: Windows x64(Windows11)
- 【硬件】： 使用CPU版本
- 【编译语言】： C++
- 【编译工具】： vs2019/cmake3.24.3/gcc8.1

首先感谢大佬提供的超赞项目！
![1676448283070](https://user-images.githubusercontent.com/68574803/218968480-f93fd315-5322-44d6-bad4-411be9fcd8e2.jpg)

![1676447310675](https://user-images.githubusercontent.com/68574803/218968079-55692810-b074-4e9e-b283-93232738601f.jpg)

体验中遇到一个问题：按教程[https://github.com/PaddlePaddle/FastDeploy/blob/develop/docs/cn/faq/use_sdk_on_windows_build.md](url)中sln及cmake方法，SCRFD模型均无法得到预测结果，运行至`model.Predict(&im, &res)`处就终止，并未打印res以及后续输出人脸检测结果；同样按教程配置的yolov5s-face模型可正常输出预测结果:
![1676448466154](https://user-images.githubusercontent.com/68574803/218974751-cbd0006f-ff50-43eb-9655-69be50f1c71a.jpg)
请问是何原因？

**Comment by DefTruth** [comment]
@Plz-Thx 请问您使用的具体是scrfd的哪个模型嗯？

**Comment by DefTruth** [comment]
你使用的是不带关键点的模型，可以设置：  
```c++
model.use_kps = false;
```  
可以参考一下文档中的说明：
- https://github.com/PaddlePaddle/FastDeploy/blob/develop/examples/vision/facedet/scrfd/cpp/README_CN.md

**Comment by Plz-Thx** [comment]
设置后可以正常运行了，谢谢回复
