### ISSUE TITLE
RKNPU2 支持TinyPose

### ISSUE THREAD

**Issue by liutingxi** [PaddlePaddle/FastDeploy#1336]
期望可以支持TinyPose在RKNPU2设备上运行，例如RK3588

原始Paddle模型为wget https://bj.bcebos.com/paddlehub/fastdeploy/PP_TinyPose_256x192_infer.tgz
转换后的onnx模型，配置文件和rknn模型见附件。

非常感谢！

[PP_TinyPose_256x192_RK3588.zip](https://github.com/PaddlePaddle/FastDeploy/files/10741623/PP_TinyPose_256x192_RK3588.zip)

**Comment by Zheng-Bicheng** [comment]
@liutingxi 你转换模型的版本号是多少？我这边转换好像会报错诶。

**Comment by Zheng-Bicheng** [comment]
搞定了哈,我提个PR

**Comment by liutingxi** [comment]
> 搞定了哈,我提个PR

@Zheng-Bicheng 简直是神速！辛苦大佬！
