### ISSUE TITLE
构建镜像出现 CMake Error: Could not find CMAKE_ROOT !!! 问题

### ISSUE THREAD

**Issue by Lennon-cheng** [PaddlePaddle/FastDeploy#1342]
*********************************************
温馨提示：根据社区不完全统计，按照模板提问，可以加快回复和解决问题的速度
*********************************************

## 环境

- 【FastDeploy版本】： develop
- 【编译命令】bash scripts/build_fd_cuda_11_2.sh
- 【系统平台】: centos 7
- 【硬件】： Quadro RTX 6000
- 【编译语言】： C++ 

## 问题日志及出现问题的操作流程
由于修改了源代码，想重新构建镜像。参考如下文档：
https://github.com/PaddlePaddle/FastDeploy/blob/develop/serving/docs/zh_CN/compile.md
当执行：bash scripts/build_fd_cuda_11_2.sh 时，出现如下错误
看着有两个问题，
一个fatal: detected dubious ownership in repository at '/workspace/fastdeploy'：不确定这个是否需要处理
一个是：CMake Error: Could not find CMAKE_ROOT !!!

Setting up git (1:2.25.1-1ubuntu3.10) ...
Setting up python3-pip (20.0.2-5ubuntu1.7) ...
Setting up python3.8-dev (3.8.10-0ubuntu1~20.04.6) ...
Setting up libpython3-dev:amd64 (3.8.2-0ubuntu2) ...
Setting up python3-dev (3.8.2-0ubuntu2) ...
Processing triggers for libc-bin (2.31-0ubuntu9.9) ...
fatal: detected dubious ownership in repository at '/workspace/fastdeploy'
To add an exception for this directory, call:

	git config --global --add safe.directory /workspace/fastdeploy
running build
running build_py
running create_version
running cmake_build
CMake Error: Could not find CMAKE_ROOT !!!
CMake has most likely not been installed correctly.
Modules directory not found in
/workspace/fastdeploy/serving/cmake-3.18.6-Linux-x86_64/share/cmake-3.18
CMake Error: Error executing cmake::LoadCache(). Aborting.

Traceback (most recent call last):
  File "setup.py", line 417, in <module>
    setuptools.setup(
  File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 144, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python3.8/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.8/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/usr/lib/python3.8/distutils/command/build.py", line 135, in run
    self.run_command(cmd_name)
  File "/usr/lib/python3.8/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "setup.py", line 266, in run
    subprocess.check_call(cmake_args)
  File "/usr/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/workspace/fastdeploy/serving/cmake-3.18.6-Linux-x86_64/bin/cmake', '-DPYTHON_INCLUDE_DIR=/usr/include/python3.8', '-DPYTHON_EXECUTABLE=/usr/bin/python3', '-DBUILD_FASTDEPLOY_PYTHON=ON', '-DCMAKE_EXPORT_COMPILE_COMMANDS=ON', '-DONNX_NAMESPACE=paddle2onnx', '-DPY_EXT_SUFFIX=.cpython-38-x86_64-linux-gnu.so', '-DCMAKE_BUILD_TYPE=Release', '-DENABLE_RKNPU2_BACKEND=OFF', '-DENABLE_SOPHGO_BACKEND=OFF', '-DWITH_ASCEND=OFF', '-DENABLE_ORT_BACKEND=OFF', '-DENABLE_OPENVINO_BACKEND=OFF', '-DENABLE_PADDLE_BACKEND=OFF', '-DENABLE_POROS_BACKEND=OFF', '-DENABLE_TRT_BACKEND=OFF', '-DENABLE_LITE_BACKEND=OFF', '-DPADDLELITE_URL=OFF', '-DENABLE_VISION=ON', '-DENABLE_ENCRYPTION=OFF', '-DENABLE_FLYCV=OFF', '-DENABLE_CVCUDA=OFF', '-DENABLE_TEXT=ON', '-DENABLE_BENCHMARK=OFF', '-DWITH_GPU=ON', '-DWITH_IPU=OFF', '-DWITH_KUNLUNXIN=OFF', '-DBUILD_ON_JETSON=OFF', '-DTRT_DIRECTORY=/workspace/fastdeploy/serving/TensorRT-8.4.1.5/', '-DCUDA_DIRECTORY=/usr/local/cuda', '-DLIBRARY_NAME=fastdeploy', '-DPY_LIBRARY_NAME=fastdeploy_main', '-DOPENCV_DIRECTORY=', '-DORT_DIRECTORY=', '-DPADDLEINFERENCE_DIRECTORY=', '-DRKNN2_TARGET_SOC=', '/workspace/fastdeploy']' returned non-zero exit status 1.
fatal: detected dubious ownership in repository at '/workspace/fastdeploy'
To add an exception for this directory, call:

	git config --global --add safe.directory /workspace/fastdeploy
Didn't detect path: fastdeploy/libs/third_libs exist, please execute `python setup.py build` first
CMake Error: Could not find CMAKE_ROOT !!!
CMake has most likely not been installed correctly.
Modules directory not found in
/workspace/fastdeploy/serving/cmake-3.18.6-Linux-x86_64/share/cmake-3.18
CMake Error: Error executing cmake::LoadCache(). Aborting.

make: *** No targets specified and no makefile found.  Stop.
make: *** No rule to make target 'install'.  Stop.
CMake Error: Could not find CMAKE_ROOT !!!
CMake has most likely not been installed correctly.
Modules directory not found in
/workspace/fastdeploy/serving/cmake-3.18.6-Linux-x86_64/share/cmake-3.18
CMake Error: Error executing cmake::LoadCache(). Aborting.

make: *** No targets specified and no makefile found.  Stop.

**Comment by heliqi** [comment]
看起来是权限问题，试下用root执行脚本 或 把脚本里的docker指令加root权限执行

**Comment by Lennon-cheng** [comment]
> 看起来是权限问题，试下用root执行脚本 或 把脚本里的docker指令加root权限执行

**Comment by Lennon-cheng** [comment]
@heliqi   嗨，感谢回复！我尝试了 “sudo bash scripts/build_fd_cuda_11_2.sh”  和 shell 脚本docker部分加 sudo，依然遇到同样问题
<img width="979" alt="image" src="https://user-images.githubusercontent.com/33142144/219294896-50579bda-a505-4b91-b7b6-edc51e7b9218.png">

**Comment by heliqi** [comment]
我看提示是目录的问题，试试执行下这句(加脚本试试)：
git config --global --add safe.directory /workspace/fastdeploy

<img width="535" alt="image" src="https://user-images.githubusercontent.com/34152981/219297017-b0664c52-5ff0-4d11-a6af-ae40720d4316.png">

**Comment by Lennon-cheng** [comment]
@heliqi  嗨，我尝试在图中位置，添加git config 相关命令，依然报同样的错
<img width="972" alt="image" src="https://user-images.githubusercontent.com/33142144/219299263-623d5488-4ea5-46f3-8b4e-c56ff4d77ea0.png">

**Comment by heliqi** [comment]
位置写错了，放到最上，肯定要一上来先执行

**Comment by Lennon-cheng** [comment]
根据 @heliqi 建议，通过手动启动容器：
nvidia-docker run -i --name xxx -v`pwd`/..:/workspace/fastdeploy nvcr.io/nvidia/tritonserver:21.10-py3-min bash
再执行脚本中对应的那些命令，发现是CMake的问题。我重新下载cmake并编译解决问题。
