### ISSUE TITLE
【急！】在荣品A311D上部署PPYOLOE+_s时，遇到NPU跑不起来的情况

### ISSUE THREAD

**Issue by Taichipeace** [PaddlePaddle/FastDeploy#1347]
## 环境

- 【FastDeploy版本】： 拉取fastdeploy-develop版本源码，自行编译
- 【编译命令】cmake -DCMAKE_TOOLCHAIN_FILE=./../cmake/toolchain.cmake -DWITH_TIMVX=ON  -DTARGET_ABI=arm64 -DENABLE_FLYCV=ON -DCMAKE_INSTALL_PREFIX=fastdeploy-timvx -DENABLE_VISION=ON -DENABLE_LITE_BACCKEND=ON -Wno-dev ..
- 【系统平台】: aarch64 linux kernel 4.9.113，gcc、g++=9.3.0，make=4.2.1，cmake=3.22.6，ubuntu 20.04 arm64
- 【硬件】： 荣品A311D，NPU驱动已经安装为 6.4.4.3
- 【编译语言】： C++ 

### 问题描述：【模型跑不通】

* 已经按照FD官方文档跑通 [PP-YOLOE 量化模型 C++ 部署示例](https://github.com/PaddlePaddle/FastDeploy/blob/develop/examples/vision/detection/paddledetection/a311d/cpp/README_CN.md)。这个Demo的Arm cpu和NPU都可以跑通。

* 然后我换上了自己训练的PPYOLOE+_s模型，infer_cfg.yml文件也替换了。此时可以在 Arm Cpu 上跑通，精度也OK。

* 然后，按照文档的方法，打开NPU推理方式：
```
  // fastdeploy::vision::EnableFlyCV();
  // fastdeploy::RuntimeOption option;
option.UseTimVX();
 // option.SetLiteSubgraphPartitionPath(subgraph_file);
```
* 编译执行，此时已经有报错。
记录Log信息，找到其中的Subgraph operators之后的内容，单独存到 subgrapph.txt中，用新的 txt文件替换原有的subgraph.txt文件。
* 然后打开读取异构计算的txt文件的语句：
```
  // fastdeploy::vision::EnableFlyCV();
  // fastdeploy::RuntimeOption option;
option.UseTimVX();
option.SetLiteSubgraphPartitionPath(subgraph_file);
```
* 再次执行，仍然报错，且报错内容相同。
* 以上测试流程，不管是用PTQ还是QAT方式压缩的模型，都是一样的现象，一样的报错。

- 日志信息，见附件：log_ppyoloe_plus.txt
- 使用的模型包括subgraph.txt，在zip附件中：ppyoloe_plus_qat_model_atai.zip
- 测试图片，见附件：test03.zip
- 运行程序的脚本为：
```
export GLOG_v=5; 
export SUBGRAPH_ONLINE_MODE=true; 
export RKNPU_LOGLEVEL=5; 
export RKNN_LOG_LEVEL=5; 
ulimit -c unlimited; 
export VIV_VX_ENABLE_GRAPH_TRANSFORM=-pcq:1; 
export VIV_VX_SET_PER_CHANNEL_ENTROPY=100; 
export TIMVX_BATCHNORM_FUSION_MAX_ALLOWED_QUANT_SCALE_DEVIATION=300000; 
export VSI_NN_LOG_LEVEL=5;

export LD_LIBRARY_PATH=/home/rpdzkj/Downloads/FastDeploy-develop/examples/vision/detection/paddledetection/a311d/cpp/build/install/lib/;

#./build/install/infer_demo ./build/install/models/ppyoloe_noshare_qat ./build/install/images/000000014439.jpg
#./build/infer_demo ./models/ppyoloe_plus_ptq_model_new ./images/test03.jpg
./build/infer_demo ./models/ppyoloe_plus_qat_model_new ./images/test03.jpg
```

[ppyoloe_plus_qat_model_atai.zip](https://github.com/PaddlePaddle/FastDeploy/files/10755738/ppyoloe_plus_qat_model_atai.zip)
[log_ppyoloe_plus.txt](https://github.com/PaddlePaddle/FastDeploy/files/10755739/log_ppyoloe_plus.txt)
[test03.zip](https://github.com/PaddlePaddle/FastDeploy/files/10755779/test03.zip)

**Comment by yingshengBD** [comment]
[subgraph.txt](https://github.com/PaddlePaddle/FastDeploy/files/10766912/subgraph.txt)
注意不要在windows 编辑器下创建TXT，它的换行符和linux不一样 导致异构判定失效

**Comment by Taichipeace** [comment]
> 

万分感谢 yingsheng 大佬！！
问题完美解决。
