### ISSUE TITLE
PP-OCRv3   fastdeploy::vision::ocr::DBDetector(det_model_file, det_params_file, det_option); 出现：段错误 (核心已转储)

### ISSUE THREAD

**Issue by kekezhu0000** [PaddlePaddle/FastDeploy#1348]
## 环境

- 【FastDeploy版本】： fastdeploy-linux-x64-1.0.3
- 【编译命令】如果您是自行编译的FastDeploy，请说明您的编译方式（参数命令）
- 【系统平台】: Linux x64(Ubuntu 20.10) 
- 【硬件】： CPU
- 【编译语言】： C++ 

只是添加了日志，其他的代码没有修改
![111](https://user-images.githubusercontent.com/47800318/219533269-8e6f7728-a777-44e7-97bd-45f662ce06e6.png)
![222](https://user-images.githubusercontent.com/47800318/219533303-278292ad-9b2e-40ca-ad18-59f7cb685763.png)
![333](https://user-images.githubusercontent.com/47800318/219533287-d8f37cfc-ad92-4494-9dba-ac3824e092db.png)
![4444](https://user-images.githubusercontent.com/47800318/219536945-fe80eb47-a66f-45c3-af64-75f661ce46c0.png)
![555](https://user-images.githubusercontent.com/47800318/219536955-7c3b1784-7964-48fc-942d-03ee231ec1f2.png)

![666](https://user-images.githubusercontent.com/47800318/219537947-bd0f25a7-6a9a-4570-bd51-4ded4fc68682.png)

**Comment by wang-xinyu** [comment]
图片路径是否正确？应该是`./12.jpg` 或者`12.jpg`

```
./infer_demo ./ch_PP-OCRv3_det_infer ./ch_ppocr_mobile_v2.0_cls_infer ./ch_PP-OCRv3_rec_infer ./ppocr_keys_v1.txt ./12.jpg 0
```

**Comment by kekezhu0000** [comment]
图片路径是否正确？应该是./12.jpg 或者12.jpg     都试过了，不是这的问题
![886](https://user-images.githubusercontent.com/47800318/219558766-873d2a00-d237-4a75-91d6-9e2534880a25.png)

**Comment by wang-xinyu** [comment]
在当前目录执行ls命令截图看一下？

**Comment by kekezhu0000** [comment]
![999](https://user-images.githubusercontent.com/47800318/219562152-6af954b2-91c4-4005-9344-18d74825be90.png)

**Comment by yunyaoXYY** [comment]
> 在当前目录执行ls命令截图看一下？

稍等 我复现看下

**Comment by yunyaoXYY** [comment]
你好，我用 1.03版本的FastDeploy和 develop版本的FastDeploy，用CPU都是能跑的

**Comment by kekezhu0000** [comment]
要不您用  向日葵远程看一下？是不是环境配置问题

**Comment by yunyaoXYY** [comment]
> 要不您用 向日葵远程看一下？是不是环境配置问题

你原封不动地跑一下 python的demo，如果python能跑通，那么就可能不是环境问题，可能是你自己加了代码后，有点问题.

**Comment by kekezhu0000** [comment]
我测试一下python吧，刚才我测试了以下matting  c++ 也成功了，是不是在虚拟机上跑，内存小造成的？
![dd](https://user-images.githubusercontent.com/47800318/219566478-105051bc-136b-4374-bad8-cdabb721b446.png)

**Comment by kekezhu0000** [comment]
非常感谢 [yunyaoXYY](https://github.com/yunyaoXYY)的耐心解答，我把虚拟机重新安装了Ubuntu ，重新部署了一下，没有问题了，原来的系统我还留着，有空而再查一下是那个问题导致的，再次表示感谢！

**Comment by yunyaoXYY** [comment]
> 非常感谢 [yunyaoXYY](https://github.com/yunyaoXYY)的耐心解答，我把虚拟机重新安装了Ubuntu ，重新部署了一下，没有问题了，原来的系统我还留着，有空而再查一下是那个问题导致的，再次表示感谢！

解决了就好
