### ISSUE TITLE
这个不会用啊

### ISSUE THREAD

**Issue by l7518597** [PaddlePaddle/FastDeploy#135]
不会用啊  还是和lite.ai.toolkit一样要先自己编译吗?
话说好不容易学会lite.ai.toolkit的编译  难受

**Comment by DefTruth** [comment]
@l7518597 fastdeploy现在支持python pip 方式直接安装，同学可以尝试一下哈 ~ 另外我们也提供了各个平台和硬件c++的预编译库，方便快速部署 ~ 后续我们可能会将lite.ai.toolkit中的重点模型以contrib的方式移植到fastdeploy中来。

**Comment by l7518597** [comment]
您好,可以win32位系统部署吗

**Comment by jiangjiajun** [comment]
> 

目前0.2.0只支持Windows 10 64位哈
