### ISSUE TITLE
fastdeploy 无法在 jetson nano 上面实现tensorRT功能

### ISSUE THREAD

**Issue by qiulongquan** [PaddlePaddle/FastDeploy#1350]
## 环境

- 【FastDeploy版本】： jetson nano编译版本，fastdeploy-python    0.0.0
- 【编译命令】：Python编译安装
- 【系统平台】: Linux (Ubuntu 18.04) 
- 【硬件】：  Nvidia jetson nano b01 4G， CUDA 10.2 CUDNN 8.2.1
- 【编译语言】： Python 3.6.15

## 问题日志及出现问题的操作流程
jetson nano硬件环境下多个example模型在tensorRT模式下无法正常预测（在GPU模式下都可以正常预测并返回结果）

预测命令
FastDeploy/examples/vision/detection/paddledetection/python$ python infer_ppyoloe.py --model_dir ppyoloe_crn_l_300e_coco --image 000000014439.jpg --device gpu --use_trt True

日志log
(paddle3.6) qiulongquan@qiulongquan-desktop:~/ml/FastDeploy/examples/vision/detection/paddledetection/python$ python infer_ppyoloe.py --model_dir ppyoloe_crn_l_300e_coco --image 000000014439.jpg --device gpu --use_trt True
[WARNING] fastdeploy/backends/tensorrt/trt_backend.cc(552)::CreateTrtEngineFromOnnx     Cannot build engine right now, because there's dynamic input shape exists, list as below,
[WARNING] fastdeploy/backends/tensorrt/trt_backend.cc(556)::CreateTrtEngineFromOnnx     Input 0: TensorInfo(name: image, shape: [-1, 3, 640, 640], dtype: FDDataType::FP32)
[WARNING] fastdeploy/backends/tensorrt/trt_backend.cc(556)::CreateTrtEngineFromOnnx     Input 1: TensorInfo(name: scale_factor, shape: [-1, 2], dtype: FDDataType::FP32)
[WARNING] fastdeploy/backends/tensorrt/trt_backend.cc(558)::CreateTrtEngineFromOnnx     FastDeploy will build the engine while inference with input data, and will also collect the input shape range information. You should be noticed that FastDeploy will rebuild the engine while new input shape is out of the collected shape range, this may bring some time consuming problem, refer https://github.com/PaddlePaddle/FastDeploy/docs/backends/tensorrt.md for more details.
[INFO] fastdeploy/runtime.cc(289)::Init Runtime initialized with Backend::TRT in Device::GPU.
[INFO] fastdeploy/vision/detection/ppdet/ppyoloe.cc(67)::Initialize     Detected operator multiclass_nms3 in your model, will replace it with fastdeploy::backend::MultiClassNMS(background_label=-1, keep_top_k=300, nms_eta=1, nms_threshold=0.7, score_threshold=0.01, nms_top_k=10000, normalized=1).
[WARNING] fastdeploy/backends/tensorrt/utils.cc(40)::Update     [New Shape Out of Range] input name: image, shape: [1, 3, 640, 640], The shape range before: min_shape=[-1, 3, 640, 640], max_shape=[-1, 3, 640, 640].
[WARNING] fastdeploy/backends/tensorrt/utils.cc(52)::Update     [New Shape Out of Range] The updated shape range now: min_shape=[1, 3, 640, 640], max_shape=[1, 3, 640, 640].
[WARNING] fastdeploy/backends/tensorrt/utils.cc(40)::Update     [New Shape Out of Range] input name: scale_factor, shape: [1, 2], The shape range before: min_shape=[-1, 2], max_shape=[-1, 2].
[WARNING] fastdeploy/backends/tensorrt/utils.cc(52)::Update     [New Shape Out of Range] The updated shape range now: min_shape=[1, 2], max_shape=[1, 2].
[WARNING] fastdeploy/backends/tensorrt/trt_backend.cc(281)::Infer       TensorRT engine will be rebuilt once shape range information changed, this may take lots of time, you can set a proper shape range before loading model to avoid rebuilding process. refer https://github.com/PaddlePaddle/FastDeploy/docs/backends/tensorrt.md for more details.
[INFO] fastdeploy/backends/tensorrt/trt_backend.cc(416)::BuildTrtEngine Start to building TensorRT Engine...
[ERROR] fastdeploy/backends/tensorrt/trt_backend.cc(228)::log   1: [executionResources.cpp::setTacticSources::156] Error Code 1: Cudnn (Could not initialize cudnn, please check cudnn installation.)
[ERROR] fastdeploy/backends/tensorrt/trt_backend.cc(228)::log   2: [builder.cpp::buildSerializedNetwork::609] Error Code 2: Internal Error (Assertion enginePtr != nullptr failed. )
[ERROR] fastdeploy/backends/tensorrt/trt_backend.cc(465)::BuildTrtEngine        Failed to call buildSerializedNetwork().
Segmentation fault (core dumped)

![image](https://user-images.githubusercontent.com/36796264/219549393-0c6a694a-04ff-4f89-ba02-aee2ca00bb7d.png)

**Comment by wang-xinyu** [comment]
看起来是没找到cudnn，运行dpkg -l | grep cudnn看一下

**Comment by qiulongquan** [comment]
> dpkg -l | grep cudnn

好像没有问题啊，cudnn==8.2.1
(paddle3.6) qiulongquan@qiulongquan-desktop:~$ dpkg -l | grep cudnn
ii  libcudnn8                                             8.2.1.32-1+cuda10.2                        arm64        cuDNN runtime libraries
ii  libcudnn8-dev                                         8.2.1.32-1+cuda10.2                        arm64        cuDNN development libraries and headers
ii  libcudnn8-doc                                         8.0.0.180-1+cuda10.2                       arm64        cuDNN documents and samples
ii  libcudnn8-samples                                     8.2.1.32-1+cuda10.2                        arm64        cuDNN documents and samples
ii  nvidia-container-csv-cudnn                            8.2.1.32-1+cuda10.2                        arm64        Jetpack CUDNN CSV file
ii  nvidia-cudnn8                                         4.6.3-b17                                  arm64        NVIDIA CUDNN8 Meta Package

但是conda list 里面我发现了 cudnn     8.3.2.44      h66ab864_1    conda-forge
我无法在jetson nano上面安装 cudnn==8.2.1
这个是否有冲突 是否需要删掉 cudnn  8.3.2.44（我删掉也没有起作用）

![image](https://user-images.githubusercontent.com/36796264/219601974-565b93cb-ad14-4d80-baa2-883b65791b67.png)

我尝试检测 tensorRT 发现无法找到trt
Python 3.6.15 | packaged by conda-forge | (default, Dec  3 2021, 19:12:04) 
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorrt as trt
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'tensorrt'
>>> 

怎么才能恢复tensorRT呢？

**Comment by leiqing1** [comment]
@qiulongquan NVIDIA官网是不建议修改Jetpack的环境的，如果可以建议从新SDK manager刷机。

**Comment by qiulongquan** [comment]
> @qiulongquan NVIDIA官网是不建议修改Jetpack的环境的，如果可以建议从新SDK manager刷机。

感谢你的建议，是的，升级版本后很多地方出现问题，最后还是通过刷机恢复到4.6.1版本

**Comment by qiulongquan** [comment]
现在已经可以实现fastdeploy 在jetson nano上面通过trt部署了，但是速度不是很快大概脸部检测 45ms一张 
https://github.com/PaddlePaddle/FastDeploy/blob/develop/examples/vision/facedet/retinaface/README_CN.md
这个模型的入力尺度640-640，我希望能够降低入力尺度到320*320
我尝试修改fastdeploy 中的set_shape（下面的函数参数），但是速度没有改变
option.trt_option.set_shape("images", [1, 3, 192, 192],[1, 3, 320, 320],[1, 3, 640, 640])

请问 我如何才能调整模型的入力尺度到320呢？ 谢谢

**Comment by Phoenix8215** [comment]
CUDA10.2可以通过编译安装fastdepoly了吗(○´･д･)ﾉ😮😮😮
