### ISSUE TITLE
编译中加入flycv报错

### ISSUE THREAD

**Issue by ShawnXsw** [PaddlePaddle/FastDeploy#1353]
- 【FastDeploy版本】： fastdeploy-linux-gpu-0.0.0（dev-2023.2.17）
- 【编译命令】
cmake .. -DENABLE_ORT_BACKEND=ON \
         -DENABLE_PADDLE_BACKEND=ON \
         -DENABLE_OPENVINO_BACKEND=ON \
         -DENABLE_TRT_BACKEND=ON \
         -DWITH_GPU=ON \
         -DTRT_DIRECTORY=/root/3rdparty/TensorRT-8.0.3.4 \
         -DCUDA_DIRECTORY=/usr/local/cuda \
         -DCMAKE_CUDA_ARCHITECTURES=86 -DCMAKE_CUDA_COMPILER=/usr/local/cuda/bin/nvcc \
         -DCMAKE_INSTALL_PREFIX=${PWD}/INSTALL/fastdeploy \
         -DENABLE_VISION=ON \
         -DOPENCV_DIRECTORY=/root/3rdparty/opencv \
         -DENABLE_TEXT=OFF \
         -DENABLE_CVCUDA=ON \
         -DENABLE_FLYCV=ON
- 【系统平台】: Linux x64(Ubuntu 18.04) 
- 【硬件】：  Nvidia GPU 3090， CUDA 11.2 CUDNN 8.1
- 【编译语言】： C++

【编译错误】
![image](https://user-images.githubusercontent.com/33308054/219564787-b8f1d7ed-f921-436c-bf05-4c4f0c3312db.png)

**Comment by jiangjiajun** [comment]
在FastDeploy，目前建议在Linux aarch64/armhf平台打开FLYCV，x64上FLYCV仍然还在优化性能中。 

但是Linux x64上编译出错问题应该是编译逻辑存在问题，麻烦 @DefTruth 关注下

**Comment by ShawnXsw** [comment]
自动下载的flycv库无shared so，只有静态lib， 默认参数WITH_FLYCV_STATIC=OFF，应该是这里问题

**Comment by DefTruth** [comment]
> 

好的，我来跟进下这个问题
