### ISSUE TITLE
使用tinypose rknpu2相关

### ISSUE THREAD

**Issue by houyaoqi17** [PaddlePaddle/FastDeploy#1357]
https://github.com/PaddlePaddle/FastDeploy/blob/develop/examples/vision/keypointdetection/tiny_pose/rknpu2/python/pptinypose_infer.py#L38-L39
这两行代码不支持，运行会报错，可以看一下吗

**Comment by Zheng-Bicheng** [comment]
我再看一下，您先用c++端吧

**Comment by Zheng-Bicheng** [comment]
错误信息是什么

**Comment by houyaoqi17** [comment]
> 错误信息是什么

FastDeploy/examples/vision/keypointdetection/tiny_pose/rknpu2/python$ python3 pptinypose_infer.py --tinypose_model_dir PP_TinyPose_256x192/ --image hrnet_demo.jpg
[INFO] fastdeploy/runtime/backends/rknpu2/rknpu2_backend.cc(57)::GetSDKAndDeviceVersion rknn_api/rknnrt version: 1.4.0 (a10f100eb@2022-09-09T09:07:14), driver version: 0.8.0
index=0, name=image, n_dims=4, dims=[1, 256, 192, 3], n_elems=147456, size=294912, fmt=NHWC, type=FP16, qnt_type=AFFINE, zp=0, scale=1.000000, pass_through=0
index=0, name=conv2d_441.tmp_1, n_dims=4, dims=[1, 17, 64, 48], n_elems=52224, size=104448, fmt=NCHW, type=FP16, qnt_type=AFFINE, zp=0, scale=1.000000, pass_through=0
[INFO] fastdeploy/runtime/runtime.cc(383)::CreateRKNPU2Backend  Runtime initialized with Backend::RKNPU2 in Device::RKNPU.
Traceback (most recent call last):
  File "/home/rpdzkj/Documents/code/FastDeploy/examples/vision/keypointdetection/tiny_pose/rknpu2/python/pptinypose_infer.py", line 38, in <module>
    tinypose_model.disable_normalize()
AttributeError: 'PPTinyPose' object has no attribute 'disable_normalize'
E RKNN: [10:15:45.588] can not find memory for freeing

**Comment by Zheng-Bicheng** [comment]
尝试过拉取下来重新编译python 吗？

**Comment by houyaoqi17** [comment]
> 尝试过拉取下来重新编译python 吗？

https://github.com/Zheng-Bicheng/FastDeploy/tree/tiny_pose  使用的这个分支，重新编译过

**Comment by Zheng-Bicheng** [comment]
用主仓库的develop分支哦，你用我的临时分支干嘛。:-)

发自我的 iPhone

在 2023年2月17日，18:24，houyaoqiqiqi ***@***.***> 写道：

﻿

尝试过拉取下来重新编译python 吗？

https://github.com/Zheng-Bicheng/FastDeploy/tree/tiny_pose 使用的这个分支，重新编译过

**Comment by Zheng-Bicheng** [comment]
已经修复
