### ISSUE TITLE
picodet rknn量化相关问题

### ISSUE THREAD

**Issue by houyaoqi17** [PaddlePaddle/FastDeploy#1358]
使用rknn量化，会出现以下问题

:~/Documents/code/FastDeploy/examples/vision/detection/paddledetec
tion/rknpu2/python$ python3 infer.py --model_file picodet_xs_320_coco_lcnet/picodet_xs_320_coco_lcn
et_rk3588_quantized.rknn  --config_file picodet_xs_320_coco_lcnet/infer_cfg.yml
[INFO] fastdeploy/vision/common/processors/transform.cc(45)::FuseNormalizeCast  Normalize and Cast are fused to Normalize in preprocessing pipeline.
[INFO] fastdeploy/vision/common/processors/transform.cc(93)::FuseNormalizeHWC2CHW       Normalize and HWC2CHW are fused to NormalizeAndPermute  in preprocessing pipeline.
[INFO] fastdeploy/vision/common/processors/transform.cc(159)::FuseNormalizeColorConvert BGR2RGB and NormalizeAndPermute are fused to NormalizeAndPermute with swap_rb=1
[INFO] fastdeploy/runtime/backends/rknpu2/rknpu2_backend.cc(57)::GetSDKAndDeviceVersion rknn_api/rknnrt version: 1.4.0 (a10f100eb@2022-09-09T09:07:14), driver version: 0.8.0
index=0, name=image, n_dims=4, dims=[1, 320, 320, 3], n_elems=307200, size=307200, fmt=NHWC, type=INT8, qnt_type=AFFINE, zp=-14, scale=0.018658, pass_through=0
index=0, name=p2o.Mul.179, n_dims=4, dims=[1, 2125, 4, 1], n_elems=8500, size=8500, fmt=NCHW, type=INT8, qnt_type=AFFINE, zp=-63, scale=2.518318, pass_through=0
index=1, name=p2o.Concat.9, n_dims=4, dims=[1, 80, 2125, 1], n_elems=170000, size=170000, fmt=NCHW, type=INT8, qnt_type=AFFINE, zp=-128, scale=0.003438, pass_through=0
[INFO] fastdeploy/runtime/runtime.cc(383)::CreateRKNPU2Backend  Runtime initialized with Backend::RKNPU2 in Device::RKNPU.
[WARNING] fastdeploy/runtime/backends/rknpu2/rknpu2_backend.cc(323)::Infer      The input tensor type != model's inputs type.The input_type need INT8,but inputs[0].type is UINT8
DetectionResult: [xmin, ymin, xmax, ymax, score, label_id]

Segmentation fault (core dumped)

**Comment by Zheng-Bicheng** [comment]
Picodet暂不支持量化哦，尝试用PP-YOLOE吧
