### ISSUE TITLE
init failed fastdeploy

### ISSUE THREAD

**Issue by developWmark** [PaddlePaddle/FastDeploy#1359]
*********************************************
温馨提示：根据社区不完全统计，按照模板提问，可以加快回复和解决问题的速度
*********************************************

## 环境

- 【FastDeploy版本】： 说明具体的版本，如fastdeploy-linux-gpu-1.0.3
 python -m pip install fastdeploy-gpu-python -f https://www.paddlepaddle.org.cn/whl/fastdeploy.html

- 【编译命令】python 包
- 【系统平台】: Linux x64(Ubuntu 18.04) 
- 【硬件】：具体硬件型号 Nvidia GPU 1060 3090 v100， 驱动 CUDA 11.2  CUDNN 8.3
- 【编译语言】： Python 3.8

## 问题日志及出现问题的操作流程
使用conda管理的包   conda config --add channels conda-forge && conda install cudatoolkit=11.2 cudnn=8.2
![08b88540128497fb5198c7911586715](https://user-images.githubusercontent.com/93702453/219687420-d58dbba1-bfef-4302-94a1-7400780a3229.png)
![f39e8dd1b83c92cda73c61cf0b04f3a](https://user-images.githubusercontent.com/93702453/219687449-bb49b5c6-3d18-41cb-90cf-edb88ed6c133.png)

**Comment by jiangjiajun** [comment]
export LD_LIBRARY_PATH试下

**Comment by developWmark** [comment]
请问一下导入哪个路径

**Comment by jiangjiajun** [comment]
export LD_LIBRARY_PATH=/home/wps/anaconda3/envs/fastdeploy_gpu/lib/:${LD_LIBRARY_PATH}
