### ISSUE TITLE
考虑推出Gradio类似的框架不

### ISSUE THREAD

**Issue by monkeycc** [PaddlePaddle/FastDeploy#1360]
考虑推出Gradio类似的WEB在线推理框架不,集成了GUI
https://github.com/gradio-app/gradio

虽然我们有什么[服务化部署](https://github.com/PaddlePaddle/FastDeploy/blob/develop/serving)
但是部署费劲 还要会前端交互
太重量级了
没这个方便

**Comment by jiangjiajun** [comment]
暂时未在计划中。 不过如果要是有兴趣，欢迎来共建！

**Comment by monkeycc** [comment]
https://github.com/flet-dev/flet


[Flutter](https://flutter.dev/)
这个框架思路可以
封装了 Flutter UI
python直接就能用了
只需要加上FastDeploy检测代码

**Comment by jiangjiajun** [comment]
如若有意开发贡献，我可以协助（可以微信交流群直接找到我的头像加我）

**Comment by heliqi** [comment]
@monkeycc 
1. 目前我们有结合VDL的可视化部署: https://github.com/PaddlePaddle/FastDeploy/blob/develop/serving/docs/zh_CN/vdl_management.md
这个服务是高性能c++版本，相对麻烦点
2. 如果你想要部署简单快速的python版服务(并发性能弱点)，可以参考这个: https://github.com/PaddlePaddle/FastDeploy/tree/develop/examples/vision/segmentation/paddleseg/serving/simple_serving
