### ISSUE TITLE
onnx部署yolov5模型问题

### ISSUE THREAD

**Issue by GreenAvocado92** [PaddlePaddle/FastDeploy#1367]
win下，用fastdeploy部署yolov5的onnx模型，发现，fastdeploy上提供的*.onnx模型是可以的，但是我从yolov5中下载*pt转成onnx模型是无法识别的，请问，*.onnx模型是怎么生成的（针对ultralytics/yolov5)

**Comment by wjj19950828** [comment]
@GreenAvocado92 无法识别是什么意思，具体报什么错呢，麻烦提供一下onnx模型以及复现代码

**Comment by GreenAvocado92** [comment]
> 
已经搞定，谢谢，我现在用的yolo v6.1是可以的
