### ISSUE TITLE
fastdeploy调用yolov5无法使用GPU

### ISSUE THREAD

**Issue by GreenAvocado92** [PaddlePaddle/FastDeploy#1369]
![A7O78E%$26~@YIA6GDWM}GT](https://user-images.githubusercontent.com/91200482/220026903-3d094b37-62e8-4477-874c-48ed7698ea3a.jpg)
![XO@Y{L3V79 X I7O}W}B3 F](https://user-images.githubusercontent.com/91200482/220026991-9cedd504-a3ff-4cd2-838a-e5e47a9cef6c.jpg)
![3RG@K$VQY@GM3E@82FBFNTE](https://user-images.githubusercontent.com/91200482/220026992-584dc148-7592-4790-b154-9e920d4451fb.png)

第一张图是调用yolov5的代码，第二图是yolov5初始化时的提示，使用CPU， 第三张图是YOLOE的初始化提示

**Comment by jiangjiajun** [comment]
<img width="828" alt="image" src="https://user-images.githubusercontent.com/19339784/220036621-b8212ba0-264c-4b85-80d6-1ee2a71f648b.png">
使用方式参考PP-YOLOE

**Comment by GreenAvocado92** [comment]
> <img alt="image" width="828" src="https://user-images.githubusercontent.com/19339784/220036621-b8212ba0-264c-4b85-80d6-1ee2a71f648b.png">
> 
> 使用方式参考PP-YOLOE

thinks
