### ISSUE TITLE
N5095 cpu上PP-OCR服务化部署失败

### ISSUE THREAD

**Issue by flamebox** [PaddlePaddle/FastDeploy#1372]
使用registry.baidubce.com/paddlepaddle/fastdeploy:1.0.2-cpu-only-21.10镜像在赛扬N5095上部署，环境是ubuntu20.04 。在启动服务后：fastdeployserver --model-repository=/ocr_serving/models
会报错失败
<img width="983" alt="1676878678325" src="https://user-images.githubusercontent.com/18228342/220042345-77cab7e6-56fb-4725-acbc-1180e4b51cc3.png">
同样的model文件和配置，同样的环境，在我的i5-1240p笔记本上是能正常运行的。
是否N5095 CPU不支持avx指令集导致的？
是否有解决办法？

**Comment by jiangjiajun** [comment]
有可能，试下重新编译一个cpu的镜像（只开启ORT后端，关闭Paddle/OpenVINO后端）。 麻烦 @rainyfly 提供下Serving CPU 编译文档，以及如何关闭Paddle/OpenVINO后端

**Comment by rainyfly** [comment]
你好，FastDeploy的Serving CPU镜像的编译文档如下：https://github.com/PaddlePaddle/FastDeploy/blob/develop/serving/docs/zh_CN/compile.md
其中对于后端的支持可以修改
https://github.com/PaddlePaddle/FastDeploy/blob/develop/serving/scripts/build.sh 这个文件。关闭Paddle和OpenVino可以设置如下位置为OFF
![d4df3ee147de8b9bd84aac5a3d7b9954](https://user-images.githubusercontent.com/22424850/220233146-07187b71-16f0-4bd7-9443-da39b6d1dcca.png)
![fab38a2680beab0369e908d47b05f068](https://user-images.githubusercontent.com/22424850/220233284-3217366e-ac8e-43ab-bad8-7f79771509d8.png)

关于支持的编译选项可以参考文档 https://github.com/PaddlePaddle/FastDeploy/blob/develop/docs/cn/build_and_install/cpu.md
![image](https://user-images.githubusercontent.com/22424850/220232572-52ee47bb-1e0b-4b92-a296-133c692d6534.png)

**Comment by flamebox** [comment]
已经重新编译镜像并运行成功了，谢谢！
但使用ONNX Runtime后端真的好慢，这个cpu上请求一次推理耗时要1秒多。我在1240p上用openvino只需100多ms。
请问后面会支持在不带avx指令集的cpu上跑serving用openvino后端吗？

**Comment by heliqi** [comment]
@flamebox  有跑过openvino吗？ 可以编译镜像时把oepnvino开关打开，尝试下。有任何问题可以反馈下

**Comment by flamebox** [comment]
> @flamebox 有跑过openvino吗？ 可以编译镜像时把oepnvino开关打开，尝试下。有任何问题可以反馈下

打开oepnvino选项后，启动服务报错，提示libiomp5.so缺失。无论后端用openvino还是onnx都是一样。
<img width="899" alt="1677031327977" src="https://user-images.githubusercontent.com/18228342/220501847-729efd94-0aab-4b14-8ac3-47bb9a19addd.png">

**Comment by heliqi** [comment]
@flamebox  这个报错是因为你的机器没有安装openmp库，openvino编译时依赖了OpenMP。
安装openmp后再试试:
```
apt-get install libomp-dev
```

**Comment by flamebox** [comment]
> 

你好，最终还是成功运行起来了，速度比之前用onnxruntime快了一倍多点，不错。
但是我在编译环境下安装OpenMP后编译出来的镜像还是会报libiomp5.so缺失，需要在容器内再安装一次libomp-dev后就可以启动服务了。
我看了build这个文件夹内，是有生成这个动态库的，不知道为什么打包docker镜像时没有放进去？
<img width="543" alt="1677036714961" src="https://user-images.githubusercontent.com/18228342/220514516-30d286f4-f295-4c51-81d9-c86b4cd6f2d5.png">

**Comment by heliqi** [comment]
@flamebox 看起来很不错的效果。
在镜像中肯定有这个so， 可能是我忘记在dockerfile中加入环境变量导致找不到。 
你应该可以在镜像的 /opt/fastdeploy/third_libs目录下找到该so

**Comment by flamebox** [comment]
> > 
> 
> 你好，最终还是成功运行起来了，速度比之前用onnxruntime快了一倍多点，不错。 但是我在编译环境下安装OpenMP后编译出来的镜像还是会报libiomp5.so缺失，需要在容器内再安装一次libomp-dev后就可以启动服务了。 我看了build这个文件夹内，是有生成这个动态库的，不知道为什么打包docker镜像时没有放进去？ <img alt="1677036714961" width="543" src="https://user-images.githubusercontent.com/18228342/220514516-30d286f4-f295-4c51-81d9-c86b4cd6f2d5.png">



> @flamebox 看起来很不错的效果。 在镜像中肯定有这个so， 可能是我忘记在dockerfile中加入环境变量导致找不到。 你应该可以在镜像的 /opt/fastdeploy/third_libs目录下找到该so

确实是在的
<img width="549" alt="1677037744453" src="https://user-images.githubusercontent.com/18228342/220516970-c565133f-12a5-456d-accd-bcdbc2e798d0.png">

**Comment by heliqi** [comment]
@flamebox 好的。我记录下这个问题，后面修复下Dockerfile。 你可以先手动设置环境变量 或 尝试修复Dockerfile给我们提PR。

**Comment by heliqi** [comment]
通过手动编译镜像已解决报错问题并成功运行服务化部署
