### ISSUE TITLE
【jetson nano环境】facedet脸部检测模型入力尺寸修改 模型无法检测发生错误

### ISSUE THREAD

**Issue by qiulongquan** [PaddlePaddle/FastDeploy#1373]
## 环境

- 【FastDeploy版本】： jetson nano编译版本，fastdeploy-python 0.0.0
- 【编译命令】：Python编译安装
- 【系统平台】: Linux (Ubuntu 18.04)
- 【硬件】： Nvidia jetson nano b01 4G， CUDA 10.2 CUDNN 8.2.1
- 【编译语言】： Python 3.7.12

## 问题日志及出现问题的操作流程
飞浆官方提供的facedet 脸部检测模型Pytorch_Retinaface（https://github.com/biubug6/Pytorch_Retinaface） 模型入力尺寸是640*640 为了提高jetson nano检测速度，修改成320*320。 然后正常导出onnx模型

![image](https://user-images.githubusercontent.com/36796264/220047883-77dedddc-7aec-4cdb-a664-5a2d9f057e35.png)

在FastDeploy部署无法正常检测脸部，出现下面error信息

(paddle3.7) qiulongquan@qiulongquan-desktop:~/ml/FastDeploy/examples/vision/facedet/retinaface/python$ python face_det_infer.py 
WARNING:root:`RuntimeOption.set_trt_max_workspace_size` will be deprecated in v1.2.0, please use `RuntimeOption.trt_option.max_workspace_size = 1073741824` instead.
WARNING:root:`RuntimeOption.enable_paddle_trt_collect_shape` will be deprecated in v1.2.0, please use `RuntimeOption.paddle_infer_option.collect_trt_shape = True` instead.
[INFO] fastdeploy/runtime/backends/tensorrt/trt_backend.cc(692)::CreateTrtEngineFromOnnx        Detect serialized TensorRT Engine file in ./tensorrt_cache/model.trt, will load it directly.
[INFO] fastdeploy/runtime/backends/tensorrt/trt_backend.cc(108)::LoadTrtCache   Build TensorRT Engine from cache file: ./tensorrt_cache/model.trt with shape range information as below,
[INFO] fastdeploy/runtime/backends/tensorrt/trt_backend.cc(111)::LoadTrtCache   Input name: input0, shape=[1, 3, 320, 320], min=[1, 3, 320, 320], max=[1, 3, 320, 320]

[INFO] fastdeploy/runtime/runtime.cc(355)::CreateTrtBackend     Runtime initialized with Backend::TRT in Device::GPU.
[ERROR] fastdeploy/runtime/backends/tensorrt/trt_backend.cc(232)::log   3: [executionContext.cpp::setBindingDimensions::944] Error Code 3: API Usage Error (Parameter check failed at: runtime/api/executionContext.cpp::setBindingDimensions::944, condition: profileMaxDims.d[i] >= dimensions.d[i]. Supplied binding dimension [1,3,640,640] for bindings[0] exceed min ~ max range at index 2, maximum dimension in profile is 320, minimum dimension in profile is 320, but supplied dimension is 640.
)

已经确认 在640*640入力尺寸下可以正常进行脸部检测，系统环境应该没有问题，主要出在入力尺寸转换后的模型上面
请给与帮助 谢谢

**Comment by jiangjiajun** [comment]
```
[INFO] fastdeploy/runtime/backends/tensorrt/trt_backend.cc(692)::CreateTrtEngineFromOnnx Detect serialized TensorRT Engine file in ./tensorrt_cache/model.trt, will load it directly.
[INFO] fastdeploy/runtime/backends/tensorrt/trt_backend.cc(108)::LoadTrtCache Build TensorRT Engine from cache file: ./tensorrt_cache/model.trt with shape range information as below,
[INFO] fastdeploy/runtime/backends/tensorrt/trt_backend.cc(111)::LoadTrtCache Input name: input0, shape=[1, 3, 320, 320], min=[1, 3, 320, 320], max=[1, 3, 320, 320]
```
在这个日志中，他提示到，
- 1. 已经检测到设定的目录下存在缓存trt文件，会直接加载它（而不是重新构建模型）`./tensorrt_cache/model.trt `
- 2. 当前加载的缓存trt文件，他能接受的输入Shape范围是` input0, shape=[1, 3, 320, 320], min=[1, 3, 320, 320], max=[1, 3, 320, 320]`，即只能是1，3，320，320的输入
- 3. 当前你的输入是640，跟这个320的不符合

FD中集成的RetinaFace，默认认为模型输入大小是640，640，而这里改成320后，则需要对应调用API，修改图像预处理逻辑（原来resize成640，640， 现在得改成resize成320， 320）,使用下面的API，应该是调用`model.size = [320, 320]`即可
https://github.com/PaddlePaddle/FastDeploy/blob/develop/python/fastdeploy/vision/facedet/contrib/retinaface.py#L54-L61

注意改完后，先删除对应位置的model.trt缓存

**Comment by qiulongquan** [comment]
> 

感谢你的回复
我确认过了https://github.com/PaddlePaddle/FastDeploy/blob/develop/python/fastdeploy/vision/facedet/contrib/retinaface.py#L54-L61
这个修改的地方。修改后还是没有改变
我修改的地方截图发给你看一下
![image](https://user-images.githubusercontent.com/36796264/220066047-37388e83-0c24-4721-a599-a475be233053.png)

另外infer.py文件中构建option的函数我也有一些修改
![image](https://user-images.githubusercontent.com/36796264/220066568-8796d7f1-e9e1-4c08-93c5-696da87dfdfa.png)

model.trt缓存文件已经删除 

如果我哪里有错误 请指正 谢谢

**Comment by jiangjiajun** [comment]
不是修改上述的代码
- 1. 将上述对FastDeploy代码的修改还原
- 2. 在infer.py中， 在调用model.predict前，新增一行代码`model.size = [320, 320]`

**Comment by qiulongquan** [comment]
> 不是修改上述的代码
> 
> * 1. 将上述对FastDeploy代码的修改还原
> * 2. 在infer.py中， 在调用model.predict前，新增一行代码`model.size = [320, 320]`

你是完全正确的 ，问题已经解决了 太感谢了。

我还有一个和模型预测结果获取相关的问题
face_det_results = model.predict(frame,conf_threshold=0.25, nms_iou_threshold=0.5)
我需要获取到face_det_results里面的boxes坐标值 但是好像不正确，如何能够获得脸部检测4点坐标 
![image](https://user-images.githubusercontent.com/36796264/220072296-a8e51a2c-df4c-4bec-815e-90d04e40215a.png)

谢谢 我已经自己解决了  
face_det_results.boxes
可以获取
