### ISSUE TITLE
ppocrV3 预测 报错 module numpy has no attribute astype

### ISSUE THREAD

**Issue by EasyIsAllYouNeed** [PaddlePaddle/FastDeploy#1378]
*********************************************
温馨提示：根据社区不完全统计，按照模板提问，可以加快回复和解决问题的速度
*********************************************

## 环境

- 【FastDeploy版本】：  fastdeploy-linux-gpu-1.0.2
- 【编译命令】如果您是自行编译的FastDeploy，请说明您的编译方式（参数命令）
- 【系统平台】: Linux x64(Ubuntu 20.04) 
- 【硬件】：  如 Nvidia GPU TeslaP40， CUDA 11.4  CUDNN 8.4
- 【编译语言】： C++ / Python3.8

## 问题日志及出现问题的操作流程
- 附上详细的问题日志有助于快速定位分析
- 【性能问题】描述清楚对比的方式
- 预测特定图片：
  报 module numpy has no attribute astype
  同时gpu占用大于80%
  控制台报显存oom

- - - 提供复现问题的 代码+模型+错误log，供工程师快速定位问题
问题图片
[12345.png.zip](https://github.com/PaddlePaddle/FastDeploy/files/10783432/12345.png.zip)  
[stack.txt](https://github.com/PaddlePaddle/FastDeploy/files/10783482/stack.txt)

![1099745716](https://user-images.githubusercontent.com/121446530/220081336-27461ee8-82c0-41c3-921b-2414e2dbe41b.jpg)

![1398360170](https://user-images.githubusercontent.com/121446530/220082136-9d997d5e-62d2-49fb-8d44-6e221226c9b6.jpg)

**Comment by yunyaoXYY** [comment]
你好, 
把 FastDeploy/examples/vision/ocr/PP-OCRv3/serving/models/det_postprocess/1/model.py 里的#193, 
改为 image_list[index] = image_list[index].astype(np.uint8), 来试试

**Comment by jiangjiajun** [comment]
> 你好, 把 FastDeploy/examples/vision/ocr/PP-OCRv3/serving/models/det_postprocess/1/model.py 里的#193, 改为 image_list[index] = image_list[index].astype(np.uint8), 来试试

是个需要修复的bug吗？

**Comment by yunyaoXYY** [comment]
> > 你好, 把 FastDeploy/examples/vision/ocr/PP-OCRv3/serving/models/det_postprocess/1/model.py 里的#193, 改为 image_list[index] = image_list[index].astype(np.uint8), 来试试
> 
> 是个需要修复的bug吗？

需要修，之前的例子应该没有走到这一行代码. 
我用用户的这个图片，复现了之后来修一下
