### ISSUE TITLE
【Supported】Yolov5 classification

### ISSUE THREAD

**Issue by sctrueew** [PaddlePaddle/FastDeploy#138]
Hi,

Is it possible to support https://github.com/ultralytics/yolov5/pull/8956 models?

Thanks

**Comment by DefTruth** [comment]
@sctrueew hi ~, we have received your issue.  we may support this latest yolov5-cls classification https://github.com/ultralytics/yolov5/pull/8956 models in next release (version v0.3.0). What tasks do you mainly use this model for?

**Comment by sctrueew** [comment]
@DefTruth Hi, thanks for your response. It would be helpful if you could classify and extract features for me.

**Comment by DefTruth** [comment]
ongoing ~

**Comment by sctrueew** [comment]
@DefTruth Hi,

any news?

**Comment by DefTruth** [comment]
This will release via next version (v0.3.0) of FastDeploy. By the way, what do you think is the advantage of YOLOV5-CLS over other classification models ？

**Comment by sctrueew** [comment]
Thank you. In my opinion, it's easy to train and use all PyTorch models, such as EfficientNetV2 and others

**Comment by DefTruth** [comment]
Thanks for your recommendation, !!! yolov5-cls is already in our support plan ~

**Comment by sctrueew** [comment]
@DefTruth Hi, Yolov5-Seg just released and also please support that.

Thanks in advance!
