### ISSUE TITLE
多线程预测时候报错[Paddle2ONNX] Find dumplicate output name p2o.Add.1，it will rename to p2o.p2o.Add.1.0

### ISSUE THREAD

**Issue by happybear1015** [PaddlePaddle/FastDeploy#1388]
使用cpp在windows进行多线程预测图像，使用的模型为paddlecls模型。
多线程思路为：将所有图像路径存储在一个容器中，设置线程数，每一个线程预测的图像数为：总图像数/线程数。
线程数设置为1时，可以正常运行，设置为多线程，就会报错如下，并自动退出程序：
![image](https://user-images.githubusercontent.com/66996161/220228944-0b926429-c72f-474f-90a6-520a811872fc.png)

请求大佬帮忙解决，谢谢！

**Comment by jiangjiajun** [comment]
你好，能提供一个复现的示例代码吗，便于我们快速分析

**Comment by happybear1015** [comment]
好的。
好的，代码如下：
#include "fastdeployision.h"
#include <iostream>
#include <chrono>
#include <tuple>
#include <thread>
#include <vector>


#ifdef WIN32
const char sep = '\\'; //windows中，使用\\分隔符。
#else
const char sep = '/';
#endif

double cost_time = 0.0;
int class_id = 0;
float score = 0.0;

std::tuple<double, int, float> InferThread(const std::string& model_dir, const std::string& image_file, const std::string& mode) {
    auto sep = "//";
    auto model_file = model_dir + sep + "inference.pdmodel"; // 模型结构文件.pdmodel的完整目录
    auto params_file = model_dir + sep + "inference.pdiparams"; // 模型参数文件.pdiparams的完整目录
    auto config_file = model_dir + sep + "inference_cls.yaml"; // 分类预测的配置文件inference_cls.yaml的完整目录

    auto option = fastdeploy::RuntimeOption();
    if (mode == "gpu") {
        option.UseGpu();
    }
    else {
        option.UseCpu();
    }
    auto model = fastdeploy::vision::classification::PaddleClasModel(
        model_file, params_file, config_file, option);
    if (!model.Initialized()) {
        std::cerr << "Failed to initialize." << std::endl;
    }
    auto im = cv::imread(image_file);
    auto start = std::chrono::steady_clock::now();
    fastdeploy::vision::ClassifyResult res;
    if (!model.Predict(im, &res)) {
        std::cerr << "Failed to predict." << std::endl;
    }
    auto end = std::chrono::steady_clock::now();
    auto diff = end - start;
    double cost_time = std::chrono::duration<double, std::milli>(diff).count();

    std::stringstream ss(res.Str());
    std::string label_ids_str, scores_str;
    ss.ignore(std::numeric_limits<std::streamsize>::max(), ':');
    ss >> label_ids_str;
    ss.ignore(std::numeric_limits<std::streamsize>::max(), ':');
    ss >> scores_str;
    int class_id = std::stoi(label_ids_str);
    float score = std::stof(scores_str);
    std::cout << "Image " << image_file << ": " << "cost time = " << cost_time << " ms, class id = " << class_id << ", score = " << score << std::endl;
    return std::make_tuple(cost_time, class_id, score);
}
#include <Windows.h>


// 遍历目录下的所有文件，并返回文件名列表。
std::vector<std::string> listFiles(const std::string& dir_path) {
    std::vector<std::string> file_list;
    std::string search_path = dir_path + sep + "*.*";
    WIN32_FIND_DATAA file_data;  
    HANDLE handle = FindFirstFileA(search_path.c_str(), &file_data);

    if (handle == INVALID_HANDLE_VALUE) {
        // 检查文件句柄是否有效。如果无效，说明打开目录失败，输出错误信息并返回空的字符串向量。
        std::cerr << "Failed to open directory: " << dir_path << std::endl;
        return file_list;
    }
    do {
        if (!(file_data.dwFileAttributes & FILE_ATTRIBUTE_DIRECTORY)) {
            file_list.push_back(dir_path + sep + file_data.cFileName);
        }
    } while (FindNextFileA(handle, &file_data));
    
    FindClose(handle);
    // 关闭文件句柄，释放系统资源

    return file_list;
    // 返回查找到的文件路径列表
}

// 每个线程的处理函数
void processImages(const std::string& model_dir, const std::vector<std::string>& image_files, const std::string& mode) {
    for (const auto& image_file : image_files) {
        InferThread(model_dir, image_file, mode);
    }
}

int main() {
    // 设置模型目录和图像目录
    std::string model_dir = "E:\\xiaoxiong\\work\\mian_ma_clas\\BUSHU\\fastdeploy-use-test2\\infer_ppcls2\\x64\\Release\\inference";
    std::string image_dir = "F:\\001LWM\\Document\\Desktop\\ceshi_predict\\b1";
    std::string mode = "gpu"; // 或者使用"cpu"

    // 遍历图像目录，获取所有图像文件的路径
    auto image_files = listFiles(image_dir);

    // 指定线程数量
    int num_threads = 1;

    // 创建线程
    std::vector<std::thread> threads;
    int num_images = image_files.size();

    int images_per_thread = num_images / num_threads;
    // 每个线程处理的图像数
    for (int i = 0; i < num_threads; i++) {
        int start_idx = i * images_per_thread;
        int end_idx = (i == num_threads - 1) ? num_images : (i + 1) * images_per_thread;

        std::vector<std::string> thread_image_files(image_files.begin() + start_idx, image_files.begin() + end_idx);

        threads.emplace_back(processImages, model_dir, thread_image_files, mode);
    for (auto& thread : threads) {
        thread.join();
    }
    system("pause");
    return 0;
}

**Comment by happybear1015** [comment]
#include "fastdeploy/vision.h"
#include <iostream>
#include <chrono>
#include <tuple>
#include <thread>
#include <vector>


#ifdef WIN32
const char sep = '\\'; //windows中，使用\\分隔符。
#else
const char sep = '/';
#endif

double cost_time = 0.0;
int class_id = 0;
float score = 0.0;

std::tuple<double, int, float> InferThread(const std::string& model_dir, const std::string& image_file, const std::string& mode) {
    auto sep = "//";
    auto model_file = model_dir + sep + "inference.pdmodel"; // 模型结构文件.pdmodel的完整目录
    auto params_file = model_dir + sep + "inference.pdiparams"; // 模型参数文件.pdiparams的完整目录
    auto config_file = model_dir + sep + "inference_cls.yaml"; // 分类预测的配置文件inference_cls.yaml的完整目录

    auto option = fastdeploy::RuntimeOption();
    if (mode == "gpu") {
        option.UseGpu();
    }
    else {
        option.UseCpu();
    }
    auto model = fastdeploy::vision::classification::PaddleClasModel(
        model_file, params_file, config_file, option);
    if (!model.Initialized()) {
        std::cerr << "Failed to initialize." << std::endl;
    }
    auto im = cv::imread(image_file);
    auto start = std::chrono::steady_clock::now();
    fastdeploy::vision::ClassifyResult res;
    if (!model.Predict(im, &res)) {
        std::cerr << "Failed to predict." << std::endl;
    }
    auto end = std::chrono::steady_clock::now();
    auto diff = end - start;
    double cost_time = std::chrono::duration<double, std::milli>(diff).count();

    std::stringstream ss(res.Str());
    std::string label_ids_str, scores_str;
    ss.ignore(std::numeric_limits<std::streamsize>::max(), ':');
    ss >> label_ids_str;
    ss.ignore(std::numeric_limits<std::streamsize>::max(), ':');
    ss >> scores_str;
    int class_id = std::stoi(label_ids_str);
    float score = std::stof(scores_str);
    std::cout << "Image " << image_file << ": " << "cost time = " << cost_time << " ms, class id = " << class_id << ", score = " << score << std::endl;
    return std::make_tuple(cost_time, class_id, score);
}
#include <Windows.h>


// 遍历目录下的所有文件，并返回文件名列表。
std::vector<std::string> listFiles(const std::string& dir_path) {
    std::vector<std::string> file_list;
    std::string search_path = dir_path + sep + "*.*";
    WIN32_FIND_DATAA file_data;  
    HANDLE handle = FindFirstFileA(search_path.c_str(), &file_data);

    if (handle == INVALID_HANDLE_VALUE) {
        // 检查文件句柄是否有效。如果无效，说明打开目录失败，输出错误信息并返回空的字符串向量。
        std::cerr << "Failed to open directory: " << dir_path << std::endl;
        return file_list;
    }
    do {
        if (!(file_data.dwFileAttributes & FILE_ATTRIBUTE_DIRECTORY)) {
            file_list.push_back(dir_path + sep + file_data.cFileName);
        }
    } while (FindNextFileA(handle, &file_data));
    
    FindClose(handle);
    // 关闭文件句柄，释放系统资源

    return file_list;
    // 返回查找到的文件路径列表
}

// 每个线程的处理函数
void processImages(const std::string& model_dir, const std::vector<std::string>& image_files, const std::string& mode) {
    for (const auto& image_file : image_files) {
        InferThread(model_dir, image_file, mode);
    }
}

int main() {
    // 设置模型目录和图像目录
    std::string model_dir = "E:\\xiaoxiong\\work\\mian_ma_clas\\BUSHU\\fastdeploy-use-test2\\infer_ppcls2\\x64\\Release\\inference";
    std::string image_dir = "F:\\001LWM\\Document\\Desktop\\ceshi_predict\\b1";
    std::string mode = "gpu"; // 或者使用"cpu"

    // 遍历图像目录，获取所有图像文件的路径
    auto image_files = listFiles(image_dir);

    // 指定线程数量
    int num_threads = 1;

    // 创建线程
    std::vector<std::thread> threads;
    int num_images = image_files.size();

    int images_per_thread = num_images / num_threads;
    // 每个线程处理的图像数
    for (int i = 0; i < num_threads; i++) {
        int start_idx = i * images_per_thread;
        int end_idx = (i == num_threads - 1) ? num_images : (i + 1) * images_per_thread;

        std::vector<std::string> thread_image_files(image_files.begin() + start_idx, image_files.begin() + end_idx);

        threads.emplace_back(processImages, model_dir, thread_image_files, mode);
    for (auto& thread : threads) {
        thread.join();
    }
    system("pause");
    return 0;
}

**Comment by happybear1015** [comment]
`#include "fastdeploy/vision.h"
#include <iostream>
#include <chrono>
#include <tuple>
#include <thread>
#include <vector>


#ifdef WIN32
const char sep = '\\'; //windows中，使用\\分隔符。
#else
const char sep = '/';
#endif

double cost_time = 0.0;
int class_id = 0;
float score = 0.0;

std::tuple<double, int, float> InferThread(const std::string& model_dir, const std::string& image_file, const std::string& mode) {
    auto sep = "//";
    auto model_file = model_dir + sep + "inference.pdmodel"; // 模型结构文件.pdmodel的完整目录
    auto params_file = model_dir + sep + "inference.pdiparams"; // 模型参数文件.pdiparams的完整目录
    auto config_file = model_dir + sep + "inference_cls.yaml"; // 分类预测的配置文件inference_cls.yaml的完整目录

    auto option = fastdeploy::RuntimeOption();
    if (mode == "gpu") {
        option.UseGpu();
    }
    else {
        option.UseCpu();
    }
    auto model = fastdeploy::vision::classification::PaddleClasModel(
        model_file, params_file, config_file, option);
    if (!model.Initialized()) {
        std::cerr << "Failed to initialize." << std::endl;
    }
    auto im = cv::imread(image_file);
    auto start = std::chrono::steady_clock::now();
    fastdeploy::vision::ClassifyResult res;
    if (!model.Predict(im, &res)) {
        std::cerr << "Failed to predict." << std::endl;
    }
    auto end = std::chrono::steady_clock::now();
    auto diff = end - start;
    double cost_time = std::chrono::duration<double, std::milli>(diff).count();

    std::stringstream ss(res.Str());
    std::string label_ids_str, scores_str;
    ss.ignore(std::numeric_limits<std::streamsize>::max(), ':');
    ss >> label_ids_str;
    ss.ignore(std::numeric_limits<std::streamsize>::max(), ':');
    ss >> scores_str;
    int class_id = std::stoi(label_ids_str);
    float score = std::stof(scores_str);
    std::cout << "Image " << image_file << ": " << "cost time = " << cost_time << " ms, class id = " << class_id << ", score = " << score << std::endl;
    return std::make_tuple(cost_time, class_id, score);
}
#include <Windows.h>


// 遍历目录下的所有文件，并返回文件名列表。
std::vector<std::string> listFiles(const std::string& dir_path) {
    std::vector<std::string> file_list;
    std::string search_path = dir_path + sep + "*.*";
    WIN32_FIND_DATAA file_data;  
    HANDLE handle = FindFirstFileA(search_path.c_str(), &file_data);

    if (handle == INVALID_HANDLE_VALUE) {
        // 检查文件句柄是否有效。如果无效，说明打开目录失败，输出错误信息并返回空的字符串向量。
        std::cerr << "Failed to open directory: " << dir_path << std::endl;
        return file_list;
    }
    do {
        if (!(file_data.dwFileAttributes & FILE_ATTRIBUTE_DIRECTORY)) {
            file_list.push_back(dir_path + sep + file_data.cFileName);
        }
    } while (FindNextFileA(handle, &file_data));
    
    FindClose(handle);
    // 关闭文件句柄，释放系统资源

    return file_list;
    // 返回查找到的文件路径列表
}

// 每个线程的处理函数
void processImages(const std::string& model_dir, const std::vector<std::string>& image_files, const std::string& mode) {
    for (const auto& image_file : image_files) {
        InferThread(model_dir, image_file, mode);
    }
}

int main() {
    // 设置模型目录和图像目录
    std::string model_dir = "E:\\xiaoxiong\\work\\mian_ma_clas\\BUSHU\\fastdeploy-use-test2\\infer_ppcls2\\x64\\Release\\inference";
    std::string image_dir = "F:\\001LWM\\Document\\Desktop\\ceshi_predict\\b1";
    std::string mode = "gpu"; // 或者使用"cpu"

    // 遍历图像目录，获取所有图像文件的路径
    auto image_files = listFiles(image_dir);

    // 指定线程数量
    int num_threads = 1;

    // 创建线程
    std::vector<std::thread> threads;
    int num_images = image_files.size();

    int images_per_thread = num_images / num_threads;
    // 每个线程处理的图像数
    for (int i = 0; i < num_threads; i++) {
        int start_idx = i * images_per_thread;
        int end_idx = (i == num_threads - 1) ? num_images : (i + 1) * images_per_thread;

        std::vector<std::string> thread_image_files(image_files.begin() + start_idx, image_files.begin() + end_idx);

        threads.emplace_back(processImages, model_dir, thread_image_files, mode);
    for (auto& thread : threads) {
        thread.join();
    }
    system("pause");
    return 0;
}`

**Comment by happybear1015** [comment]
[infer_cls_muti_thread_to_paddle.txt](https://github.com/PaddlePaddle/FastDeploy/files/10789552/infer_cls_muad_to_paddle.txt)
代码文件见附件，麻烦大佬了！

**Comment by happybear1015** [comment]
当指定线程数量设置为4时，就会报错。
    // 指定线程数量
    int num_threads = 4;

**Comment by jiangjiajun** [comment]
看起来有可能是模型同时加载并在线执行Paddle2ONNX时，会有冲突。你能这样试下吗，错开每个线程里面模型加载的部分，例如第1个线程正常运行，第二线线程启动后，在函数内部（即模型加载前）先sleep(10秒), 第三个线程sleep(20秒), 第四个线程sleep(30秒)

帮忙测试下这样是否会出问题

**Comment by happybear1015** [comment]
可以直接帮忙给出代码吗？谢谢

**Comment by jiangjiajun** [comment]
<img width="941" alt="image" src="https://user-images.githubusercontent.com/19339784/220291119-4352408a-a728-4c17-9bea-ba664f01bb74.png">
伪代码如上

**Comment by happybear1015** [comment]
谢谢，您好。我修改完之后，编译后运行，这次不报错了，但是中途程序还是会自动退出。这是什么原因呢？

**Comment by happybear1015** [comment]
在大佬指导下已经解决，谢谢😊
