### ISSUE TITLE
文字识别OCR部分支持端侧平台瑞芯微3588吗？

### ISSUE THREAD

**Issue by KongXCai** [PaddlePaddle/FastDeploy#1400]
![image](https://user-images.githubusercontent.com/100198198/220315263-74422a6b-40c6-4abd-a806-62bd22d3cb8f.png)
## 目前显示对平台瑞芯微3588，OCR的支持还在进行中，请问这个支持大概将在未来的多久完成？还是说已经支持了，但是文档暂未更新。

**Comment by Zheng-Bicheng** [comment]
马上将会支持哦，还差一个python支持

**Comment by KongXCai** [comment]
> 非常感谢！！！

**Comment by Zheng-Bicheng** [comment]
关注一下

* https://github.com/PaddlePaddle/FastDeploy/pull/1403#discussion_r1113779730

**Comment by KongXCai** [comment]
> 关注一下
> 
> * [[Hackathon 182 Model] Update PPOCRV3 For RKNPU2 #1403 (comment)](https://github.com/PaddlePaddle/FastDeploy/pull/1403#discussion_r1113779730)

后期会在example中添加ocr的demo吗？

**Comment by Zheng-Bicheng** [comment]
有哦，在审核了，合入就能正常使用了


在 2023年2月22日，13:45，Fu Xiaofeng ***@***.***> 写道：

﻿

关注一下

  *   [Hackathon 182 Model] Update PPOCRV3 For RKNPU2 #1403 (comment)<https://github.com/PaddlePaddle/FastDeploy/pull/1403#discussion_r1113779730>

后期会在example中添加ocr的demo吗？

**Comment by Zheng-Bicheng** [comment]
已经更新
