### ISSUE TITLE
如何在推理时开启paddle.inference.Config()中的配置？

### ISSUE THREAD

**Issue by kehuo** [PaddlePaddle/FastDeploy#1406]
## 环境

- 【FastDeploy版本】： fastdeploy-gpu-python 0.1.0
- 【编译命令】不是自编译的
- 【系统平台】: Linux x64(Ubuntu 18.04.5 LTS)
- 【硬件】： 说明具体硬件型号，如 Nvidia GPU 3090， CUDA 11.2 CUDNN 8.2
- 【编译语言】： Python 3.7

## 问题日志及出现问题的操作流程
【问题】在使用fastdeploy推理时，如何设置 [paddle.inference.Config()](https://paddle-inference.readthedocs.io/en/latest/api_reference/python_api_doc/Config/OtherFunction.html#profile) 中的配置？例如：
paddle inference 可以开启 enable_profile()，用于查看性能；也可以开启enable_memory_optim()，启动内存优化，等等。

请问fastdeploy中如何设置这些paddle inference支持的功能？

感谢。

**Comment by jiangjiajun** [comment]
首先需要安装最新版本1.0.4（这两天会发版，当前可以直接安装nightly build的0.0.0版本）。 Paddle后端的配置定义PaddleBackendOption在如下代码，如若要配置Paddle后端，当前使用如下方式配置
```
runtime_option.paddle_infer_option.gpu_mem_init_size = 200; 
```
如若有你需要的配置参数目前在`PaddleBackendOption`没有提供的，可以在此issue反馈给我（上面提到的内存优化，在FastDeploy中会默认为Paddle Inference开启）

https://github.com/PaddlePaddle/FastDeploy/blob/cc9031c17e5c0819f7142d9859197d390064fc5f/fastdeploy/runtime/backends/paddle/option.h#L50-L76

**Comment by kehuo** [comment]
@jiangjiajun 感谢回复。

现在希望尽快能用的配置有3个：
【开profiler（最高优）】paddle.inference.Config.enable_profile()
【开内存优化（中等优先）】paddle.inference.Config.enable_memory_optim()
【开 IR 优化(最低优)】paddle.inference.Config.switch_ir_optim(x: bool = True)

除了这3个，其他定义在[这里](https://paddle-inference.readthedocs.io/en/latest/api_reference/python_api_doc/Config_index.html) 的配置如果都能支持那肯定更好～

解释一下为什么fastdeploy已经默认开启了enable_memory_optim()，但我还是希望有这个配置：
因为我想比较【打开打开内存优化】和【关闭内存优化】对我的模型而言能节省多少内存。

现在这3个配置 fastdeploy 似乎都没有
