### ISSUE TITLE
支持自己训练的模型 android 端

### ISSUE THREAD

**Issue by sl00001** [PaddlePaddle/FastDeploy#1407]
你好  ，我这边利用 yolov5训练的自定义的数据集  ，部署在android上可以吗 ，有例子吗

**Comment by DefTruth** [comment]
yolov5暂时还没有在android端提供支持，已经支持java api的场景和模型可以参考：  
- https://github.com/PaddlePaddle/FastDeploy/blob/develop/java/android/README_CN.md  

目前，FD在移动端通过Paddle Lite进行推理，onnx模型需要先通过x2paddle转成paddle格式，然后参考JNI调用文档来在android上使用：  
- https://github.com/PaddlePaddle/FastDeploy/blob/develop/docs/cn/faq/use_cpp_sdk_on_android.md
