### ISSUE TITLE
编译DLL 无法使用

### ISSUE THREAD

**Issue by chccc1994** [PaddlePaddle/FastDeploy#1413]
## 环境

- 【FastDeploy版本】： FastDeploy-release-1.0.0 源代码
- 【系统平台】Windows x64(Windows10)
- 【硬件】：Nvidia GPU 3080， CUDA 11.2 CUDNN 8.3
- 【编译语言】： C++ 

编译GPU版本DLL编译成功， 添加到demo程序运行时会把程序卡掉了。也没有报错，任务管理器只显示程序挂起，这是怎么回事？
但是demo程序使用官方编译DLL的没问题。

**CMake配置如下：**，请问编译GPU DLL 时CMake配置有什么问题吗？？
![image](https://user-images.githubusercontent.com/68001817/220580737-4607e130-82d3-48a7-88af-b924fddd9ea6.png)

![image](https://user-images.githubusercontent.com/68001817/220580150-fb616c37-7e16-4451-b7f6-1b10569ad231.png)

**Comment by DefTruth** [comment]
有设置为Release模式吗

**Comment by chccc1994** [comment]
> 有设置为Release模式吗

设置了。visual studio 2019 编译的时候选择了**x64 Release**模式；

GPU版本编译，ENABLE选项中，有必须或者关联的选项吗？ 官方版本 都选择了哪几项？

**Comment by DefTruth** [comment]
win gui方式编译参考这个编译文档吧：  
- https://github.com/PaddlePaddle/FastDeploy/blob/develop/docs/cn/faq/build_on_win_with_gui.md

**Comment by chccc1994** [comment]
> win gui方式编译参考这个编译文档吧：
> 
> * https://github.com/PaddlePaddle/FastDeploy/blob/develop/docs/cn/faq/build_on_win_with_gui.md

是按照[GPU编译教程](https://github.com/PaddlePaddle/FastDeploy/blob/develop/docs/cn/faq/build_on_win_with_gui.md)，但是CMAKE时候没有**ENABLE_PADDLE_FRONTEND** 和**ENABLE_VISION_VISUALIZE**选项。 其他的和教程完全一致。

**Comment by jiangjiajun** [comment]
编译DEMO时，除了设置FASTDEPLOY_INSTALL_DIR，其余的开关不要做配置

**Comment by chccc1994** [comment]
> FASTDEPLOY_INSTALL_DIR

谢谢，找到问题了。
