### ISSUE TITLE
RK3588S PicoDet输入图片识别不到目标时自动退出程序并且不报错

### ISSUE THREAD

**Issue by XDUwsk** [PaddlePaddle/FastDeploy#1419]
## 环境

- 【FastDeploy版本】： develop
- 【编译命令】与官方提供的编译方式相同
- 【系统平台】: ubuntu20.04 RK3588s
- 【编译语言】： C++ / Python 3.9.16

## 问题日志及出现问题的操作流程
自己按照百度paddle对应的方式部署自己训练的PicoDet到RK3588S板上，正常测试运行一切正常。
但在输入批量照片时，发现在图片中能识别到对象时一切正常，能继续运行，当在输入图片中识别不到目标时，python调用对应的c++代码时返回
Process finished with exit code 139(interrupted by signal 11 :SIGSEGV)
并且程序自动退出，不报错

**Comment by Zheng-Bicheng** [comment]
已经解决了，拉最新的仓库看一下哦
