### ISSUE TITLE
Windows sever环境初始化失败

### ISSUE THREAD

**Issue by UstbLjc** [PaddlePaddle/FastDeploy#1425]
## 环境
- 【FastDeploy版本】： fastdeploy-windows-gpu-1.0.3
- 【编译命令】预编译
- 【系统平台】: Windows sever2016
- 【硬件】： CPU hygon C86 7255，如 Nvidia GPU RTX5000， CUDA 11.4 CUDNN 8.2
- 【编译语言】：Python3.9

## 问题日志及出现问题的操作流程
import fastdeploy失败
Traceback (most recent call last):
  File "D:\Anaconda3\envs\fastdeploy\lib\site-packages\fastdeploy\c_lib_wrap.py", line 164, in <module>
    from .libs.fastdeploy_main import *
ImportError: DLL load failed while importing fastdeploy_main: 动态链接库(DLL)初始化例程失败。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\Anaconda3\envs\fastdeploy\lib\site-packages\fastdeploy\__init__.py", line 19, in <module>
    from .c_lib_wrap import (
  File "D:\Anaconda3\envs\fastdeploy\lib\site-packages\fastdeploy\c_lib_wrap.py", line 166, in <module>
    raise RuntimeError("FastDeploy initalized failed!")
RuntimeError: FastDeploy initalized failed!

请问是CPU不支持，还是操作系统的原因呢？

**Comment by jiangjiajun** [comment]
我们没有测试过Windows Server环境，但根据之前Windows上的问题，可能可以从下面两种方式来解决
- 使用管理员权限打开命令终端，再尝试import fastdeploy
- Windows安装fastdeploy-python或fastdeploy-gpu-python后，执行import fastdeploy时，出现提示"DLL Load failed: 找不到指定模块"
- - 解决方式 此问题原因可能在于系统没有安装VS动态库，在此页面根据个人环境下载安装后，重新import解决 https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170

**Comment by wall-git** [comment]
> 我们没有测试过Windows Server环境，但根据之前Windows上的问题，可能可以从下面两种方式来解决
> 
> * 使用管理员权限打开命令终端，再尝试import fastdeploy
> * Windows安装fastdeploy-python或fastdeploy-gpu-python后，执行import fastdeploy时，出现提示"DLL Load failed: 找不到指定模块"
> * * 解决方式 此问题原因可能在于系统没有安装VS动态库，在此页面根据个人环境下载安装后，重新import解决 https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170

Window Server 2012，python3.8,cpu 尝试了此方法，问题没有解决
