### ISSUE TITLE
failed to allocate pinned system memory: no pinned memory pool 可能是什么原因

### ISSUE THREAD

**Issue by cuinfo** [PaddlePaddle/FastDeploy#1427]
使用环境一台阿里云 linux （centos7.2）测试机
运行方式：docker
版本： registry.baidubce.com/paddlepaddle/fastdeploy:1.0.2-cpu-only-21.10 
参照用例部署OCR： FastDeploy/blob/release/1.0.3/examples/vision/ocr/PP-OCRv3/serving/README_CN.md
部署上没有出现错误信息

测试：  python3 client.py
Client返回：
text=    score= 0.0

Server报错：
![image](https://user-images.githubusercontent.com/2025317/220864612-1d78d96f-fd0e-49ef-bbfd-ec95b6133153.png)

**Comment by heliqi** [comment]
这个报错不影响使用。 初始化的时候没有申请到系统的pinned memory
