### ISSUE TITLE
抠图的readme是不是写错？

### ISSUE THREAD

**Issue by wsx958191** [PaddlePaddle/FastDeploy#143]
你好，
      我这边测试matting抠图cpu方案时，按照readme.txt 操作，明明下载的是gpu的依赖包，为啥安装下时候指定cpu的路径？
![企业微信截图_54c40950-aeeb-402d-918c-97c323686c9f](https://user-images.githubusercontent.com/66000167/185962382-164550e6-56fd-4e87-a90d-9cc51be63c69.png)

**Comment by jiangjiajun** [comment]
@wsx958191 谢谢你的反馈。 确实是文档写错了，应该默认给的是CPU下载链接，这个我们尽快修改完成。 当前你可以在预编译库页面自行下载CPU库进行使用

**Comment by wsx958191** [comment]
你好，这里是不是也写错了，执行命令中也不应该加infer.cc吧
![企业微信截图_7fdcbd43-4f60-45ef-957e-4dd9b23acfe9](https://user-images.githubusercontent.com/66000167/186456446-8438053c-93f5-4244-ab44-bd71c28a2fb6.png)

**Comment by jiangjiajun** [comment]
看起来确实有问题，开发的同学在写文档时可能没有检查到，我们都重新再review下哈。

如果使用过程中有发现文档问题，也欢迎通过PR修改文档，成为FastDeploy的contributer 😃

**Comment by wsx958191** [comment]
哈喽，我这边matting时候，发现了一个badcase，麻烦看看是否能解决
<img width="1049" alt="企业微信截图_867a8332-53dc-4b2c-8c48-24ff3f9e2efc" src="https://user-images.githubusercontent.com/66000167/186585689-e415acc7-4154-4199-b554-6b685c0a689e.png">

原图资源：
![image](https://user-images.githubusercontent.com/66000167/186585754-9eefd005-acd6-4ee1-b1b4-67f6b048f2cb.png)

**Comment by wsx958191** [comment]
哈喽，我这边测试matting的时候，发现了一个bad case，看是否能解决？
<img width="1066" alt="企业微信截图_673dd421-bf2e-4501-9bf1-5abdc9383d73" src="https://user-images.githubusercontent.com/66000167/186585959-d2765965-8f82-4f26-ae48-d9d4d69359f4.png">
![image](https://user-images.githubusercontent.com/66000167/186586024-d28ad82c-a595-4d04-895e-c1f860a69e62.png)

**Comment by DefTruth** [comment]
这应该是集成的外部模型本身的效果问题，我们目前正在集成paddle内部的matting模型，效果应该要更好一些

**Comment by wsx958191** [comment]
好的，感谢，建议你们拉个技术沟通群或者服务群，这样各种反馈和沟通比较高效？

**Comment by DefTruth** [comment]
好的哈，欢迎加入README首页的群哈~

**Comment by wsx958191** [comment]
二维码过期了哈

**Comment by jiangjiajun** [comment]
此ISSUE由于一年未更新，将会关闭处理，如有需要，可再次更新打开。
