### ISSUE TITLE
How to use fastdeploy on rknpu2  + android environment ?

### ISSUE THREAD

**Issue by 3togo** [PaddlePaddle/FastDeploy#1434]
I have found documents on how to deploy on rknpu2 and how to deploy on android. But I could not find how to deploy on rk3588 android environment. Any help?

**Comment by Zheng-Bicheng** [comment]
Maybe you can consider "jni" to solve it?

**Comment by 3togo** [comment]
Can you provide me with a detailed procedure on how to do it ?

Thanks in advance for your help.

**Comment by 3togo** [comment]
@Zheng-Bicheng ,

https://github.com/PaddlePaddle/FastDeploy/tree/develop/examples/vision/ocr/PP-OCRv3)/rknpu2/
In  the rknpu2 folder of the above link, there are examples on C++ and Python but unfortunately no examples on Android.

**Comment by Zheng-Bicheng** [comment]
We still have a lot of work to do on RKNPU2. After optimization, we will consider migrating to Android.

**Comment by 3togo** [comment]
@Zheng-Bicheng ,

Many thanks for your prompt reply.  

I'm looking forward to seeing how your excellent work performs when ported to Android.
