### ISSUE TITLE
请问能直接推理gpu地址的图像数据么

### ISSUE THREAD

**Issue by yueyue0574** [PaddlePaddle/FastDeploy#1436]
摄像头数据通过gpu硬解后，数据在gpu里，能直接推理么？不然得copy到cpu再传给fastdeploy去gpu推理

**Comment by wang-xinyu** [comment]
@yueyue0574 你是用FastDeploy的模型吗？如果是的话，具体在用哪个模型？

还是调用FastDeploy的Runtime进行推理，自己写前后处理的代码呢？

**Comment by yueyue0574** [comment]
@wang-xinyu > 

我是用FastDeploy推理yolov5的onnx，使用trt后端，我看了下貌似FastDeploy的yolov5前后处理都是cpu的

**Comment by wang-xinyu** [comment]
@yueyue0574 所以你是调用YOLOv5的Predict()接口来推理，传入的是cv::Mat的数据，对吗？

https://github.com/PaddlePaddle/FastDeploy/blob/b6e8773b2fd45da7f547e5a2537b4529dfae0072/fastdeploy/vision/detection/contrib/yolov5/yolov5.h#L59

我们目前正在对一些模型进行预处理的改造，从而支持CV-CUDA预处理。

例如PaddleClas，可以调用Predict(FDMat)的接口，传入FDMat数据，FDMat可以是GPU的数据。

https://github.com/PaddlePaddle/FastDeploy/blob/b6e8773b2fd45da7f547e5a2537b4529dfae0072/fastdeploy/vision/classification/ppcls/model.h#L84

你有没有兴趣来改造一下YOLOv5?

另外你是用Jetson还是x86 GPU呢？

**Comment by yueyue0574** [comment]
> @yueyue0574 所以你是调用YOLOv5的Predict()接口来推理，传入的是cv::Mat的数据，对吗？
> 
> https://github.com/PaddlePaddle/FastDeploy/blob/b6e8773b2fd45da7f547e5a2537b4529dfae0072/fastdeploy/vision/detection/contrib/yolov5/yolov5.h#L59
> 
> 我们目前正在对一些模型进行预处理的改造，从而支持CV-CUDA预处理。
> 
> 例如PaddleClas，可以调用Predict(FDMat)的接口，传入FDMat数据，FDMat可以是GPU的数据。
> 
> https://github.com/PaddlePaddle/FastDeploy/blob/b6e8773b2fd45da7f547e5a2537b4529dfae0072/fastdeploy/vision/classification/ppcls/model.h#L84
> 
> 不支持你有没有兴趣来改造一下YOLOv5?
> 
> 另外你是用Jetson还是x86 GPU呢？

@wang-xinyu 对的，我是x86 gpu，改造能力估计不太行，我参考PaddleClas学习下
