### ISSUE TITLE
plugins.xml文件编译后会被自动删除

### ISSUE THREAD

**Issue by happybear1015** [PaddlePaddle/FastDeploy#1444]
plugins.xml文件, 为什么每次编译后，都会自动删除这个文件?

每次都要粘贴到文件夹，程序才可以运行，有点麻烦，请问这文件的用处是什么？为何会被自动删除？

**Comment by jiangjiajun** [comment]
Hi，你这里说的是Windows，还是Linux呢？另外说的删除，是指在哪一个步骤被删除，是指fastdeploy编译好的sdk中没有这个文件吗？

**Comment by happybear1015** [comment]
就是预测的cpp源码，在windows中，编译成exe或者是dll后，之前的plugins.xml文件会被自动删除，解决办法是使用重新运行fastdeploy.bat工具，就会生成了。或者把plugins文件复制一份出来，编译之后再拷贝到release目录中。
但是，只要有一个小小的改动(cpp)，再次编译，就会发现缺少了这个plugin文件，还得再重新运行bat工具，就特别麻烦。
因为，每次编译后，plugin s.xml文件内容是没有发生变化的，为什么会自动删除？难道是vs的什么隐藏功能吗？



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年3月6日(周一) 晚上9:09
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [PaddlePaddle/FastDeploy] plugins.xml文件编译后会被自动删除 (Issue #1444)




 
Hi，你这里说的是Windows，还是Linux呢？另外说的删除，是指在哪一个步骤被删除，是指fastdeploy编译好的sdk中没有这个文件吗？

**Comment by jiangjiajun** [comment]
**之前的plugins.xml文件会被自动删除** 是指哪个路径下的plugins.xml文件被删除？

**Comment by happybear1015** [comment]
就是一开始使用bat工具后，生成的



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年3月6日(周一) 晚上9:27
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [PaddlePaddle/FastDeploy] plugins.xml文件编译后会被自动删除 (Issue #1444)




 
之前的plugins.xml文件会被自动删除 是指哪个路径下的plugins.xml文件被删除？

**Comment by jiangjiajun** [comment]
那为啥“解决办法是使用重新运行fastdeploy.bat工具，就会生成了”就会再生成呢，好奇怪？

**Comment by happybear1015** [comment]
每一次运行bat这个工具，就是在将所有的依赖dll全部复制到release目录，同时就会生成plugin.xml文件



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年3月6日(周一) 晚上9:51
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [PaddlePaddle/FastDeploy] plugins.xml文件编译后会被自动删除 (Issue #1444)




 
那为啥“解决办法是使用重新运行fastdeploy.bat工具，就会生成了”就会再生成呢，好奇怪？

**Comment by jiangjiajun** [comment]
我是不是可以这样理解
- 1. fastdeploy的sdk中，其实是包含plugins.xml的
- 2. 编译预测示例infer_demo.cc，并使用fastdeploy.bat工具将lib文件拷贝到exe所在目录，这时是有plugins.xml的
- 3. 修改infer_demo.cc，这里exe所在目录就没有plugins.xml，得手动再拷贝过来

**Comment by happybear1015** [comment]
是的，我觉得应该是vs的原因，因为我尝试过，将一个毫无关系的xml文件放到release目录中，每次编译，都会自动删除xml文件，不知道为啥



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年3月6日(周一) 晚上9:57
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [PaddlePaddle/FastDeploy] plugins.xml文件编译后会被自动删除 (Issue #1444)




 
我是不是可以这样理解
  
  
fastdeploy的sdk中，其实是包含plugins.xml的
  
 
  
编译预测示例infer_demo.cc，并使用fastdeploy.bat工具将lib文件拷贝到exe所在目录，这时是有plugins.xml的
  
 
  
修改infer_demo.cc，这里exe所在目录就没有plugins.xml，得手动再拷贝过来

**Comment by zzaozhuang** [comment]
我也遇到了一摸一样的问题 ，找了好久的原因，只要重新编译，这个文件就会丢失，程序执行就会报错

**Comment by happybear1015** [comment]
嗯呢，把这个xml保存一下就好了



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年6月10日(周六) 晚上7:41
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [PaddlePaddle/FastDeploy] plugins.xml文件编译后会被自动删除 (Issue #1444)




 
我也遇到了一摸一样的问题 ，找了好久的原因，只要重新编译，这个文件就会丢失，程序执行就会报错

**Comment by WilliamQf-AI** [comment]
我是这样解决的：在生成目录下拷贝了一个文件夹“openvino”,包含内容如下：
![image](https://github.com/PaddlePaddle/FastDeploy/assets/40328063/dde3e00d-c817-4d55-b424-684c366fcb7c)
在vs的生成后事件添加如下自动拷贝脚本： xcopy /r /y "$(OutputPath)\openvino\*" "$(OutputPath)\"
