### ISSUE TITLE
mobileseg部署到rv1126上推理时间过慢，256*256图片推理时间800ms

### ISSUE THREAD

**Issue by ZHIZIHUABU** [PaddlePaddle/FastDeploy#1447]
*********************************************
温馨提示：根据社区不完全统计，按照模板提问，可以加快回复和解决问题的速度
*********************************************

## 环境

- 【FastDeploy版本】： 说明具体的版本，如fastdeploy-linux-gpu-0.8.0
- 【编译命令】如果您是自行编译的FastDeploy，请说明您的编译方式（参数命令）
- 【系统平台】: Linux x64(Ubuntu 18.04) / Windows x64(Windows10) / Mac OSX arm(12.0) / Mac OSX intel(12.0)
- 【硬件】： 说明具体硬件型号，如 Nvidia GPU 3080TI， CUDA 11.2 CUDNN 8.3
- 【编译语言】： C++ / Python(3.7或3.8等）

## 问题日志及出现问题的操作流程
- 附上详细的问题日志有助于快速定位分析
- 【模型跑不同】
- - 先执行`examples`下的部署示例，包括使用examples提供的模型，确认是否可以正确执行
- - 如若`examples`下的代码可以运行，但自己的模型，或自己的代码不能运行
- - - 提供复现问题的 代码+模型+错误log，供工程师快速定位问题
- 【模型精度问题】
- - 先执行`examples`下的部署示例，包括使用examples提供的模型，确认是否可以正确执行
- - 如若`examples`下的代码可以运行，但自己的模型，或自己的代码不能运行
- - - 提供复现问题的 代码+模型+错误log，供工程师快速定位问题
- 【性能问题】描述清楚对比的方式
- - 注意性能测试，循环跑N次，取后80%的用时平均（模型启动时，刚开始受限于资源分配，速度会较慢）
- - FastDeploy的Predict包含模型本身之外的数据前后处理用时
- - - 提供复现问题的 代码+模型+错误log，供工程师快速定位问题

**Comment by ZHIZIHUABU** [comment]
[INFO] fastdeploy/runtime/runtime.cc(321)::CreateLiteBackend	Runtime initialized with Backend::PDLITE in Device::TIMVX.
image_resize//S1A5005A_52.jpg
[I  1/ 1 15:22:58.287 ...r/src/driver/verisilicon_timvx/engine.cc:44 Context] properties: 
[I  1/ 1 15:22:58.287 ...r/src/driver/verisilicon_timvx/engine.cc:56 Context] bn_fusion_max_allowed_quant_scale_deviation: -1
[W  1/ 1 15:22:58.288 ...ter/nnadapter/src/runtime/compilation.cc:334 Finish] Warning: Failed to create a program, No model and cache is provided.
[W  1/ 1 15:22:58.288 ...le-Lite/lite/kernels/nnadapter/engine.cc:149 LoadFromCache] Warning: Build model failed(3) !
[W  1/ 1 15:22:58.530 ...nnadapter/nnadapter/src/runtime/model.cc:86 GetSupportedOperations] Warning: Failed to get the supported operations for device 'verisilicon_timvx', because the HAL interface 'validate_program' is not implemented!
[W  1/ 1 15:22:58.530 ...kernels/nnadapter/converter/converter.cc:171 Apply] Warning: Failed to get the supported operations for the selected devices, one or more of the selected devices are not supported!
[I  1/ 1 15:22:58.530 ...r/src/driver/verisilicon_timvx/driver.cc:70 CreateProgram] Create program for verisilicon_timvx.

**Comment by yeliang2258** [comment]
可以跑300次，后面的200次求均值看看性能？

**Comment by ZHIZIHUABU** [comment]
> 可以跑300次，后面的200次求均值看看性能？
是一样的，一直都是800ms一张

**Comment by yeliang2258** [comment]
首先确定几个问题：
1.是否是量化模型？
2.用到了异构计算吗？
3.异构计算的txt是最简的吗？

**Comment by ZHIZIHUABU** [comment]
我用了fastdeploy提供的compress命令进行qat量化，量化过程参照官方提供的pp_liteseg部署教程，没有用到异构计算，未添加subgraph.txt文件

**Comment by ZHIZIHUABU** [comment]
> 首先确定几个问题： 1.是否是量化模型？ 2.用到了异构计算吗？ 3.异构计算的txt是最简的吗？

我用了fastdeploy提供的compress命令进行qat量化，量化过程参照官方提供的pp_liteseg部署教程，没有用到异构计算，未添加subgraph.txt文件

**Comment by ZHIZIHUABU** [comment]
> 首先确定几个问题： 1.是否是量化模型？ 2.用到了异构计算吗？ 3.异构计算的txt是最简的吗？

请问fastdeploy支持部署动态输入模型吗，我在训练模型后导出推理模型设置input_shape参数为(1,3-1,-1)，推理模型也可以进行量化蒸馏训练，然而在开发板上运行模型时没有显示错误，直接终止运行；而且我用paddleseg中的quant_train.py量化训练的模型，再通过fastdeploy compress后量化，也是无法运行的

**Comment by ZHIZIHUABU** [comment]
> 首先确定几个问题： 1.是否是量化模型？ 2.用到了异构计算吗？ 3.异构计算的txt是最简的吗？

您好，请问可以加个联系方式吗，我遇到这个问题比较紧急，如果您有时间的话能帮我分析一下吗，需要模型和代码调试的话我可以传上去

**Comment by ZHIZIHUABU** [comment]
> 首先确定几个问题： 1.是否是量化模型？ 2.用到了异构计算吗？ 3.异构计算的txt是最简的吗？

您好，请问可以加个联系方式吗，我遇到这个问题比较紧急，如果您有时间的话能帮我分析一下吗，需要模型和代码调试的话我可以传上去

**Comment by yeliang2258** [comment]
你好，麻烦提供一下你的模型？我来分析一下原因吧

**Comment by ZHIZIHUABU** [comment]
[model.zip](https://github.com/PaddlePaddle/FastDeploy/files/10905517/model.zip)
您好|
1、mobileseg_qat_self是我们需要部署的模型，通过fastdeploy中的compress命令进行量化训练的，cpu上推理只要250ms，但是npu推理速度很慢，需要850ms，如果是异构文件未提供的问题，能说明一下异构文件的编写原理吗，官方的示例我不太明白；
2、ppliteseg_qat是我在paddleslim库中下载的量化蒸馏模型，cpu上推理550ms，npu上推理250ms，同时我使用paddlite部署方式，同样的模型在paddlite下cpu上550ms，但是npu上能够达到70ms；
3、ppliteseg_self是我自己的训练的模型，按照官方示例使用了paddleslim的auto_compression进行量化，同时也使用了fastdeploy的compress命令进行量化，但是模型只能在cpu上推理,550ms，npu上推理会报上述错误。

**Comment by ZHIZIHUABU** [comment]
> 你好，麻烦提供一下你的模型？我来分析一下原因吧

如果需要提供其他文件，请及时告知我！拜托了，大佬！我摊牌了，卡这很久了。

**Comment by yeliang2258** [comment]
![image](https://user-images.githubusercontent.com/30516196/223360166-c507678f-3832-4483-9bfb-6963f0c723c8.png)
可以进上面的群，我们一起讨论一下
