### ISSUE TITLE
paddle_ocr返回模型无法正常预测

### ISSUE THREAD

**Issue by LiQiang0307** [PaddlePaddle/FastDeploy#1453]
*********************************************
温馨提示：根据社区不完全统计，按照模板提问，可以加快回复和解决问题的速度
*********************************************

## 环境

- 【FastDeploy版本】： fastdeploy-gpu-python-1.0.1
- 【系统平台】:  Windows x64(Windows10)
- 【硬件】：TITAN X ， CUDA 11.3 CUDNN 8.2
- 【编译语言】：Python3.8等
~~~
def modelinit():
    ...
    ppocr_v3 = fd.vision.ocr.PPOCRv3(det_model=det_model, cls_model=cls_model, rec_model=rec_model)
    return ppocr_v3
~~~
封装上述语句后，返回模型无法调用预测函数,在函数内可以正常调用，
程序结束的错误代码为：Process finished with exit code -1073741819 (0xC0000005)

**Comment by jiangjiajun** [comment]
可能是det_model, cls_model, rec_model被释放的问题。试下同时return ppocr_v3, det_model, cls_model, rec_model

**Comment by LiQiang0307** [comment]
同时return det_model,cls_model,rec_model 可以解决 @jiangjiajun  👍👍👍
