### ISSUE TITLE
AttributeError: module 'fastdeploy.c_lib_wrap' has no attribute 'text'

### ISSUE THREAD

**Issue by Juelianqvq** [PaddlePaddle/FastDeploy#1458]
执行 python infer.py --model_dir uie-base/
Traceback (most recent call last):
  File "infer.py", line 134, in <module>
    uie = UIEModel(
  File "/home/kwx/Software/Anaconda/envs/uie/lib/python3.8/site-packages/fastdeploy/text/uie/__init__.py", line 62, in __init__
    schema_tmp += [SchemaNode(key, val)._schema_node]
  File "/home/kwx/Software/Anaconda/envs/uie/lib/python3.8/site-packages/fastdeploy/text/uie/__init__.py", line 34, in __init__
    schema_node_children += [C.text.SchemaNode(child, [])]
AttributeError: module 'fastdeploy.c_lib_wrap' has no attribute 'text'

编译：
按照readme里的python SDK编译然后pip install wheel

**Comment by jiangjiajun** [comment]
编译时，需指定`-DENABLE_TEXT=ON`

**Comment by Juelianqvq** [comment]
> 编译时，需指定`-DENABLE_TEXT=ON`
当我指定backend=paddle_tensorrt or paddle_inference时会有如下错误，可以帮忙看看嘛
C++ Traceback (most recent call last):
--------------------------------------
0   paddle::AnalysisPredictor::ZeroCopyRun()
1   paddle::framework::OperatorBase::Run(paddle::framework::Scope const&, phi::Place const&)
2   paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, phi::Place const&) const
3   paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, phi::Place const&, paddle::framework::RuntimeContext*) const
4   paddle::framework::OperatorWithKernel::PrepareData(paddle::framework::Scope const&, phi::KernelKey const&, std::vector<std::string, std::allocator<std::string > >*, paddle::framework::RuntimeContext*, phi::Place const&) const

----------------------
Error Message Summary:
----------------------
FatalError: `Erroneous arithmetic operation` is detected by the operating system.
  [TimeInfo: *** Aborted at 1677570737 (unix time) try "date -d @1677570737" if you are using GNU date ***]
  [SignalInfo: *** SIGFPE (@0x7ff552fb3862) received by PID 31843 (TID 0x7ff6da3db740) from PID 1392195682 ***]

Floating point exception (core dumped)

**Comment by jiangjiajun** [comment]
直接安装预编译的FastDeploy 1.0.4是否也会有这个问题

**Comment by Juelianqvq** [comment]
> 直接安装预编译的FastDeploy 1.0.4是否也会有这个问题

没有这个问题，但是我想使用tensorrt backend所以就python源码编译了

**Comment by jiangjiajun** [comment]
直接安装的FastDeploy也有内置tensorrt backend

**Comment by Juelianqvq** [comment]
> 直接安装的FastDeploy也有内置tensorrt backend

请问指定backend为trt/paddletrt的时候有办法类似trtexec --verbose那样看到转化时的细节吗？
另外遇到一点就是 trt在fp16的时候会出现精度丢失返回结果为空的情况   paddletrt的fp16则不会，这两者的区别可以简单说一下吗？
