### ISSUE TITLE
PPYOLOE 行人追踪 region_type  region_polygon 参数设置

### ISSUE THREAD

**Issue by chccc1994** [PaddlePaddle/FastDeploy#1462]
[PP-Human检测跟踪模块](https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.6/deploy/pipeline/docs/tutorials/pphuman_mot.md#%E4%BD%BF%E7%94%A8%E6%96%B9%E6%B3%95), [PP-Human检测跟踪模块](https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.6/deploy/pipeline/docs/tutorials/pphuman_mot.md#%E4%BD%BF%E7%94%A8%E6%96%B9%E6%B3%95)中可以设置 `region_type` `region_polygon `区域l类型和坐标，在`fastdeploy`中怎么设置`region_type` `region_polygon `参数？？ 

```python
python deploy/pipeline/pipeline.py --config deploy/pipeline/config/infer_cfg_pphuman.yml \
                                                   --video_file=test_video.mp4 \
                                                   --device=gpu \
                                                   --draw_center_traj \
                                                   --do_break_in_counting \
                                                   --region_type=custom \
                                                   --region_polygon 200 200 400 200 300 400 100 400
```

**Comment by chccc1994** [comment]
@jiangjiajun @DefTruth 求助

**Comment by leiqing1** [comment]
FastDeploy还不支持PP-Human。 可以尝试学习使用FastDeploy支持PP-human哈，也欢迎贡献pr～
