### ISSUE TITLE
fastdeploy compress 报错

### ISSUE THREAD

**Issue by sdreamforchen** [PaddlePaddle/FastDeploy#1469]
您好！我安装了fastdeploy：pip install fastdeploy-gpu-python -f https://www.paddlepaddle.org.cn/whl/fastdeploy.html；以及
pip install fastdeploy-python -f https://www.paddlepaddle.org.cn/whl/fastdeploy.html
也安装了paddle：python -m pip install paddlepaddle-gpu==2.4.2.post117 -f https://www.paddlepaddle.org.cn/whl/linux/mkl/avx/stable.html
目前我可以正常训练模型；但是调用compress进行自动压缩量化时报错（已从头重装过2/3次，报错一致）：
  File "/home/chenailin/.local/lib/python3.8/site-packages/common_tools/auto_compression/fd_auto_compress/fd_auto_compress.py", line 21, in <module>
    import paddle
ModuleNotFoundError: No module named 'paddle'

**Comment by leiqing1** [comment]
@sdreamforchen 你的自动压缩命令是什么？压缩的什么模型。可以分享下你使用的步骤，看看是哪一步有问题
