### ISSUE TITLE
怎么cmake？编译文档

### ISSUE THREAD

**Issue by l7518597** [PaddlePaddle/FastDeploy#147]
怎么cmake？可以像lite.ai.tookit一样出一套流程吗

**Comment by DefTruth** [comment]
@l7518597 您好，源码编译可以查看这里的编译文档：https://github.com/PaddlePaddle/FastDeploy/tree/develop/docs/compile

**Comment by DefTruth** [comment]
* [Linux和Mac下源码编译](https://github.com/PaddlePaddle/FastDeploy/blob/develop/docs/compile/how_to_build_linux_and_mac.md)
* [Windows下源码编译](https://github.com/PaddlePaddle/FastDeploy/blob/develop/docs/compile/how_to_build_windows.md)

**Comment by DefTruth** [comment]
@l7518597 C++目前已经提供了编译好的库可以使用，一般情况下不需要从源码编译，可以从这里下载预编译库。  
* [FastDeploy C++ 预编译库](https://github.com/PaddlePaddle/FastDeploy/blob/develop/docs/quick_start/CPP_prebuilt_libraries.md)

**Comment by l7518597** [comment]
yolo5推理   CPU推理成功   GPU推理卡在CMD窗口（失败）  是否要自己编译opencv GPU版本去替换啊

**Comment by jiangjiajun** [comment]
> yolo5推理 CPU推理成功 GPU推理卡在CMD窗口（失败） 是否要自己编译opencv GPU版本去替换啊

你的环境可以贴一下吗？ 

Windows系统(10/x64等) /CUDA/显卡型号/Python

**Comment by l7518597** [comment]
您好，我的电脑配置：win10 64 ltsc1809  cuda11.4 显卡：1650  用的vs2019

**Comment by l7518597** [comment]
![image](https://user-images.githubusercontent.com/26214901/186176675-d42a0c3a-9fd5-4750-ae78-d3888f222ba7.png)
我自己编译的话  这么配置报错

**Comment by l7518597** [comment]
我继续摸索摸索  新手容易遇到问题^-^

**Comment by jiangjiajun** [comment]
ENABLE_OPENCV_CUDA建议先关闭，这个还未完全测试。

建议打开如下开关
ENABLE_ORT_BACKEND
ENABLE_PADDLE_BACKEND
ENABLE_VISION
其余采用默认配置即可

可参考这个文档进行编译 https://github.com/PaddlePaddle/FastDeploy/blob/develop/docs/compile/how_to_build_windows.md

**Comment by l7518597** [comment]
不开opencv_cuda的话   能支持GPU吗?  我试过fastdeploy-win-x64-gpu-0.2.0的GPU调用有问题  cpu调用正常

**Comment by DefTruth** [comment]
> 不开opencv_cuda的话 能支持GPU吗? 我试过fastdeploy-win-x64-gpu-0.2.0的GPU调用有问题 cpu调用正常

不开opencv_cuda不会影响模型推理，模型推理还是支持GPU的。关于fastdeploy-win-x64-gpu-0.2.0 GPU调用的问题，方便贴一下错误提示吗？有可能是CUDA版本不一致的问题，我看到您这里的是CUDA 11.4，预编译的python包是用CUDA 11.2编译的。

**Comment by l7518597** [comment]
const std::string p = "C:/Users/Administrator/Desktop/yolov5s.onnx";
const std::string p1 = "C:/Users/Administrator/Desktop/000000014439.jpg";
CpuInfer(p, p1);
上面CPU调用时，正常
//=======================
GpuInfer(p, p1);
上面GPU调用时，异常，见下图，控制台无输出
![image](https://user-images.githubusercontent.com/26214901/186191457-3cbbabce-bd5c-417c-b38f-7405b52a8cb6.png)
//=======================
 TrtInfer(p, p1);
失败
![image](https://user-images.githubusercontent.com/26214901/186192300-7bddb4d7-88b3-46a3-8130-2cb0adbaa7c2.png)

**Comment by l7518597** [comment]
GpuInfer(p, p1);调用时，我有尝试在const std::string p行处下断点。  但是只有点击调试  就直接异常   没有机会执行

**Comment by DefTruth** [comment]
@l7518597 感谢您提供的信息，我们会尽快分析这个问题，请您耐心等候 ~

**Comment by l7518597** [comment]
不用称呼您 我做为一个小白会不好意思^-^ 早点休息哦

**Comment by DefTruth** [comment]
@l7518597 我看到提示是无法加载 "nvinfer_builder_resource.dll" 动态库。应该是没指定这些库的搜索路径，在windows下使用 FastDeploy C++ SDK 需要指定这些库的搜索路径，或者将依赖库都拷贝到exe的同级目录下

**Comment by DefTruth** [comment]
可以参考我们的Windows C++ SDK使用示例。
- [如何在Windows下使用FastDeploy C++ SDK](https://github.com/PaddlePaddle/FastDeploy/blob/develop/docs/compile/how_to_use_sdk_on_windows.md)

**Comment by l7518597** [comment]
已经指定过包含目录和库目录,相关dll也复制到exe同目录下.方便加个好友了远程吗,QQ 微信都行

**Comment by DefTruth** [comment]
好的，我和我们PM说一下哈 ~ @leiqing1

**Comment by DefTruth** [comment]
> 已经指定过包含目录和库目录,相关dll也复制到exe同目录下.方便加个好友了远程吗,QQ 微信都行

可以截图看下您的设置，以及exe下的文件情况吗？

**Comment by leiqing1** [comment]
> 已经指定过包含目录和库目录,相关dll也复制到exe同目录下.方便加个好友了远程吗,QQ 微信都行

你好，欢迎加我微信交流FastDeploy使用问题。微信：18813190139

**Comment by l7518597** [comment]
抱歉，是我的疏忽 因为之前GPU不成功  我把opencv替换成了我自己的版本。导致opencv出问题   我刚才删掉opencv文件夹后重新解压。发现正常了。  抱歉抱歉

**Comment by DefTruth** [comment]
好的哈~

**Comment by l7518597** [comment]
抱歉   我继续测试yolo7

**Comment by l7518597** [comment]
给个建议:FastDeploy是岐路. 还是大力发展lite.ai.toolkit吧

**Comment by jiangjiajun** [comment]
此ISSUE由于一年未更新，将会关闭处理，如有需要，可再次更新打开。
