### ISSUE TITLE
ocr serving bug修正

### ISSUE THREAD

**Issue by yywangfei** [PaddlePaddle/FastDeploy#1472]
建议/data/FastDeploy-develop/examples/vision/ocr/PP-OCRv3/serving/models/det_postprocess/1/model.py 第194行修改为：
image_list[index] = image_list[index].astype(np.uint8)
原始的代码为：
image_list[index] = np.astype(np.uint8)

**Comment by leiqing1** [comment]
@yywangfei 你好 欢迎提pr修正
