### ISSUE TITLE
FastDeploy支持PaddleYOLO系列和PaddleDetection系列进行部署吗

### ISSUE THREAD

**Issue by Wei0205** [PaddlePaddle/FastDeploy#1476]
FastDeploy支持PaddleYOLO系列和PaddleDetection系列进行部署吗，小白不知道怎么使用FastDeploy调用PaddleYOLO训练的模型配置文件，使用PaddleYOLO训练之后output里只有pdiparams文件，不知道pdmodel配置文件和infer_cfg.yml文件在哪里

**Comment by jiangjiajun** [comment]
支持

**Comment by NyquistBodeTu** [comment]
> FastDeploy支持PaddleYOLO系列和PaddleDetection系列进行部署吗，小白不知道怎么使用FastDeploy调用PaddleYOLO训练的模型配置文件，使用PaddleYOLO训练之后output里只有pdiparams文件，不知道pdmodel配置文件和infer_cfg.yml文件在哪里

你好，请问你知道infer_cfg.yml在哪里了吗？我也遇到这个问题了
