### ISSUE TITLE
编译fastdeploy streamer出现 <dlpack/dlpack.h><SYCL/sycl.hpp> "unsupported/Eigen/CXX11/Tensor""unsupported/Eigen/CXX11/Tensor"错误

### ISSUE THREAD

**Issue by jiangxinufo** [PaddlePaddle/FastDeploy#1477]
## 环境

- 【FastDeploy版本】： fastdeploy-linux-gpu-1.0.4
- 【编译命令】cmake .. -DFASTDEPLOY_INSTALL_DIR=${PWD}/fastdeploy-linux-x64-x.x.x
                        make -j ------>>>执行此句报出如下错误
- 【系统平台】: wls2 Ubuntu 22.04
- 【硬件】： Nvidia GPU T4， CUDA 11.7 CUDNN 8.8
- 【编译语言】： C++

## 问题日志及出现问题的操作流程
[ 21%] Built target yaml-cpp
[ 22%] Built target yaml-cpp-parse
[ 24%] Built target yaml-cpp-sandbox
[ 25%] Built target yaml-cpp-read
[ 26%] Building CXX object CMakeFiles/fd_streamer.dir/src/dlpack/contrib/mock_main.cc.o
[ 27%] Building CXX object CMakeFiles/fd_streamer.dir/src/eigen/bench/tensors/contraction_benchmarks_cpu.cc.o
[ 28%] Building CXX object CMakeFiles/fd_streamer.dir/src/eigen/bench/tensors/tensor_benchmarks_cpu.cc.o
[ 29%] Building CXX object CMakeFiles/fd_streamer.dir/src/eigen/bench/tensors/tensor_contract_sycl_bench.cc.o
/root/build/FastDeploy/streamer/src/dlpack/contrib/mock_main.cc:2:10: fatal error: dlpack/dlpack.h: No such file or directory
    2 | #include <dlpack/dlpack.h>
      |          ^~~~~~~~~~~~~~~~~
compilation terminated.
/root/build/FastDeploy/streamer/src/eigen/bench/tensors/tensor_contract_sycl_bench.cc:18:10: fatal error: SYCL/sycl.hpp: No such file or directory
   18 | #include <SYCL/sycl.hpp>
      |          ^~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/fd_streamer.dir/build.make:132: CMakeFiles/fd_streamer.dir/src/dlpack/contrib/mock_main.cc.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: *** [CMakeFiles/fd_streamer.dir/build.make:202: CMakeFiles/fd_streamer.dir/src/eigen/bench/tensors/tensor_contract_sycl_bench.cc.o] Error 1
In file included from /root/build/FastDeploy/streamer/src/eigen/bench/tensors/tensor_benchmarks_cpu.cc:5:
/root/build/FastDeploy/streamer/src/eigen/bench/tensors/tensor_benchmarks.h:8:10: fatal error: unsupported/Eigen/CXX11/Tensor: No such file or directory
    8 | #include "unsupported/Eigen/CXX11/Tensor"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
In file included from /root/build/FastDeploy/streamer/src/eigen/bench/tensors/contraction_benchmarks_cpu.cc:5:
/root/build/FastDeploy/streamer/src/eigen/bench/tensors/tensor_benchmarks.h:8:10: fatal error: unsupported/Eigen/CXX11/Tensor: No such file or directory
    8 | #include "unsupported/Eigen/CXX11/Tensor"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/fd_streamer.dir/build.make:174: CMakeFiles/fd_streamer.dir/src/eigen/bench/tensors/tensor_benchmarks_cpu.cc.o] Error 1
make[2]: *** [CMakeFiles/fd_streamer.dir/build.make:160: CMakeFiles/fd_streamer.dir/src/eigen/bench/tensors/contraction_benchmarks_cpu.cc.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:148: CMakeFiles/fd_streamer.dir/all] Error 2
make: *** [Makefile:91: all] Error 2

**Comment by wang-xinyu** [comment]
streamer不依赖Eigen和dlpack，这是你自己加的吗

**Comment by jiangxinufo** [comment]
不是的，FastDeploy里面源码我没有动，在编译streamer时候报的错

**Comment by jiangxinufo** [comment]
> c
非常感谢，确实，现在的问题是：
/root/build/FastDeploy/streamer/src/deepstream/bbox_parser.cc:15:10: fatal error: nvdsinfer_custom_impl.h: No such file or directory
   15 | #include "nvdsinfer_custom_impl.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~
nvdsinfer_custom_impl.h这个头文件哪里有呢？

**Comment by wang-xinyu** [comment]
这个是DeepStream的头文件，需要安装DeepStream
