### ISSUE TITLE
目标检测如何返回目标的类别名称？

### ISSUE THREAD

**Issue by jbnjbn9** [PaddlePaddle/FastDeploy#1478]
DetectionResult 返回的是id，请问如何能返回目标的类别名称？

**Comment by jiangjiajun** [comment]
id即为类别顺序。根据训练数据的标签列表来查找即可。

如果你的模型是PaddleDetection模型，可以打开导出模型的infer.yml文件，里面有一列labels标签，根据id索引其类别标签即可

**Comment by Gentek36** [comment]
您好，为什么我的fastdeploy用不了detectionresult呢？是因为我装的预编译库吗，还是python没有这个api呢？
