### ISSUE TITLE
编译fastdeploy streamer examples ppyoloe示例报错

### ISSUE THREAD

**Issue by zly19540609** [PaddlePaddle/FastDeploy#1488]
【FastDeploy版本】： fastdeploy-linux-gpu-1.0.4
【编译命令】cmake .. -DFASTDEPLOY_INSTALL_DIR=${PWD}/fastdeploy-linux-x64-gpu-1.0.4
make -j ------>>>执行此句报出如下错误
【系统平台】: wls2 Ubuntu 20.04
【硬件】： Nvidia GPU 3070， CUDA 11.7 CUDNN 8.8
【编译语言】： C++
报错如下：
/usr/bin/ld: /root/test/FastDeploy/streamer/examples/ppyoloe/cpp/../../../build/libfd_streamer.so: undefined reference to `YAML::detail::node_data::empty_scalar[abi:cxx11]()'
/usr/bin/ld: /root/test/FastDeploy/streamer/examples/ppyoloe/cpp/../../../build/libfd_streamer.so: undefined reference to `YAML::detail::node_data::convert_to_map(std::shared_ptr<YAML::detail::memory_holder> const&)'
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/streamer_demo.dir/build.make:97: streamer_demo] Error 1
make[1]: *** [CMakeFiles/Makefile2:110: CMakeFiles/streamer_demo.dir/all] Error 2
make: *** [Makefile:91: all] Error 2

**Comment by wang-xinyu** [comment]
ldd libfd_streamer.so看一下链接的.so，看下是否能找到libyaml-cpp

**Comment by zly19540609** [comment]
> ldd libfd_streamer.so看一下链接的.so，看下是否能找到libyaml-cpp
![image](https://user-images.githubusercontent.com/31341706/222599789-c53e5d87-cabc-4058-bc53-4ed6cf5f9268.png)
可以找到libyaml-cpp

**Comment by wang-xinyu** [comment]
@zly19540609 能否描述下环境信息？是WSL2的ubuntu20.04吗

**Comment by zly19540609** [comment]
对 是WSL2的ubuntu20.04

**Comment by wang-xinyu** [comment]
看样子是环境里面有多个libyaml-cpp而导致的冲突

**Comment by zly19540609** [comment]
@wang-xinyu 看样子是环境里面有多个libyaml-cpp而导致的冲突
我查看了下libyaml-cpp已安装的包
![image](https://user-images.githubusercontent.com/31341706/222647247-2eb50940-d255-4cf3-baed-6ab66c055f15.png)

**Comment by wang-xinyu** [comment]
你安装DeepStream了吗？

**Comment by zly19540609** [comment]
安装了
![image](https://user-images.githubusercontent.com/31341706/222648611-fe2ea5eb-4161-458c-a448-2119f4050904.png)

**Comment by wang-xinyu** [comment]
那和我的环境一样的，我这边没遇到YAML的问题，你要不试试把系统的yaml-cpp卸载，自己编译一个，然后改一下streamer/CMakeList.txt去链接自己编译的yaml-cpp

**Comment by zly19540609** [comment]
好的，我试下，麻烦了
