### ISSUE TITLE
我在算能sc7 pcie设备中，循环运行推理， 设备显存会爆然后coredump, 另外还有不能指定运行核心的问题

### ISSUE THREAD

**Issue by wangxu372848892** [PaddlePaddle/FastDeploy#1489]
## 环境

- 【FastDeploy版本】： 说明具体的版本，如fastdeploy-linux-gpu-1.0.3
- 【系统平台】: centos7.8
- 【硬件】： 算能sc7 pcie

## 问题日志及出现问题的操作流程
1.设备显存会爆然后coredump
while( true ){
    model.Predict(&im, &res) 
} ，你们可以跑下试试。

2.而且sc7这种多芯卡，不能指定运行在多核上，之运行在第一个核

![5d570b51bddc9a45e954a99da297bc2](https://user-images.githubusercontent.com/59901551/222374827-cd7da1cc-47f9-43a5-8adf-fea743372e5f.png)

**Comment by KhantiInNaraka** [comment]
收到，我们会尽快修复这两个问题。

**Comment by wangxu372848892** [comment]
你好，我是yolov5,修复之后我还是用这个https://github.com/PaddlePaddle/FastDeploy/tree/develop/examples/vision/detection/yolov5/sophgo/cpp就可以是吧
