### ISSUE TITLE
执行FastDeploy Streamer PP-YOLOE C++ Example中./streamer_demo时报错

### ISSUE THREAD

**Issue by jiangxinufo** [PaddlePaddle/FastDeploy#1497]
## 环境

- 【FastDeploy版本】： fastdeploy-linux-gpu-1.0.4
- 【编译命令】cmke
- 【系统平台】: Linux x64(wls2 Ubuntu 18.04) 
- 【硬件】： Nvidia GPU 3080， CUDA 11.7 CUDNN 8.8
- 【编译语言】： C++ 

## 问题日志及出现问题的操作流程
deepstream6.1，streamer在此之前都已经编译成功，在编译yoloe示例的时候出现以下错误：
root@jiangxin:~/build/FastDeploy/streamer/examples/ppyoloe/cpp/build# ./streamer_demo
app
nvurisrcbin_list
nvstreammux
nvinfer
nvtracker
nvmultistreamtiler
nvosdbin
nvvideoencfilesinkbin
[INFO] /root/build/FastDeploy/streamer/src/gstreamer/utils.cc(60)::CreatePipeline       Trying to launch pipeline: nvurisrcbin uri=file:///opt/nvidia/deepstream/deepstream-6.1/samples/streams/sample_walk.mov gpu-id=0 ! mux.sink_0  nvurisrcbin uri=file:///opt/nvidia/deepstream/deepstream-6.1/samples/streams/sample_walk.mov gpu-id=0 ! mux.sink_1  nvurisrcbin uri=file:///opt/nvidia/deepstream/deepstream-6.1/samples/streams/sample_walk.mov gpu-id=0 ! mux.sink_2  nvurisrcbin uri=file:///opt/nvidia/deepstream/deepstream-6.1/samples/streams/sample_walk.mov gpu-id=0 ! mux.sink_3  nvstreammux name=mux gpu-id=0 batch-size=4 width=1920 height=1080 batched-push-timeout=40000 ! nvinfer gpu-id=0 config-file-path=nvinfer_config.txt ! nvtracker gpu-id=0 tracker-width=640 tracker-height=640 ll-lib-file=/opt/nvidia/deepstream/deepstream/lib/libnvds_nvmultiobjecttracker.so ll-config-file=/opt/nvidia/deepstream/deepstream/samples/configs/deepstream-app/config_tracker_NvDCF_perf.yml enable-batch-process=true ! nvmultistreamtiler gpu-id=0 rows=2 columns=2 ! nvosdbin gpu-id=0 ! nvvideoencfilesinkbin gpu-id=0 bitrate=4000 output-file=out.mp4
[ERROR] /root/build/FastDeploy/streamer/src/app/base_app.cc(112)::SetupPerfMeasurement  Can't find a properly sink bin in the pipeline
Aborted

**Comment by jiangxinufo** [comment]
streamer_cfg.yml该如何修改呢？？？源文件如下：
app:
  type: video_analytics
  enable-perf-measurement: true
  perf-measurement-interval-sec: 5

nvurisrcbin_list:
  uri-list:
  - file:///opt/nvidia/deepstream/deepstream-6.1/samples/streams/sample_ride_bike.mov
  - file:///opt/nvidia/deepstream/deepstream-6.1/samples/streams/sample_ride_bike.mov
  - file:///opt/nvidia/deepstream/deepstream-6.1/samples/streams/sample_ride_bike.mov
  - file:///opt/nvidia/deepstream/deepstream-6.1/samples/streams/sample_ride_bike.mov
  pad-prefix: mux.sink_
  gpu-id: 0

nvstreammux:
  name: mux
  gpu-id: 0
  batch-size: 4
  width: 1920
  height: 1080
  batched-push-timeout: 40000  # 40ms

nvinfer:
  gpu-id: 0
  config-file-path: nvinfer_config.txt

nvtracker:
  gpu-id: 0
  tracker-width: 640
  tracker-height: 640
  ll-lib-file: /opt/nvidia/deepstream/deepstream/lib/libnvds_nvmultiobjecttracker.so
  ll-config-file: /opt/nvidia/deepstream/deepstream/samples/configs/deepstream-app/config_tracker_NvDCF_perf.yml
  enable-batch-process: true

nvmultistreamtiler:
  gpu-id: 0
  rows: 2
  columns: 2

nvosdbin:
  gpu-id: 0

nvvideoencfilesinkbin:
  gpu-id: 0
  bitrate: 4000
  output-file: out.mp4

**Comment by wang-xinyu** [comment]
运行：`gst-inspect-1.0 | grep nv`看一下是否能找到DeepStream的plugin

**Comment by jiangxinufo** [comment]
@wang-xinyu 没有找到。
root@jiangxin:~/build/FastDeploy/streamer/examples/ppyoloe/cpp/build# gst-inspect-1.0 | grep nv
Command 'gst-inspect-1.0' not found, but can be installed with:
apt install gstreamer1.0-tools

**Comment by wang-xinyu** [comment]
安装一下：apt install gstreamer1.0-tools

**Comment by jiangxinufo** [comment]
@wang-xinyu 安装成功了，出现了下面的问题。
root@jiangxin:~/build/FastDeploy/streamer/examples/ppyoloe/cpp/build# ./streamer_demo
app
nvurisrcbin_list
nvstreammux
nvinfer
nvtracker
nvmultistreamtiler
nvosdbin
nvvideoencfilesinkbin
[INFO] /root/build/FastDeploy/streamer/src/gstreamer/utils.cc(60)::CreatePipeline       Trying to launch pipeline: nvurisrcbin uri=file:///opt/nvidia/deepstream/deepstream-6.1/samples/streams/sample_ride_bike.mov gpu-id=0 ! mux.sink_0  nvurisrcbin uri=file:///opt/nvidia/deepstream/deepstream-6.1/samples/streams/sample_ride_bike.mov gpu-id=0 ! mux.sink_1  nvurisrcbin uri=file:///opt/nvidia/deepstream/deepstream-6.1/samples/streams/sample_ride_bike.mov gpu-id=0 ! mux.sink_2  nvurisrcbin uri=file:///opt/nvidia/deepstream/deepstream-6.1/samples/streams/sample_ride_bike.mov gpu-id=0 ! mux.sink_3  nvstreammux name=mux gpu-id=0 batch-size=4 width=1920 height=1080 batched-push-timeout=40000 ! nvinfer gpu-id=0 config-file-path=nvinfer_config.txt ! nvtracker gpu-id=0 tracker-width=640 tracker-height=640 ll-lib-file=/opt/nvidia/deepstream/deepstream-6.1/lib/libnvds_nvmultiobjecttracker.so ll-config-file=/opt/nvidia/deepstream/deepstream-6.1/samples/configs/deepstream-app/config_tracker_NvDCF_perf.yml enable-batch-process=true ! nvmultistreamtiler gpu-id=0 rows=2 columns=2 ! nvosdbin gpu-id=0 ! nvvideoencfilesinkbin gpu-id=0 bitrate=4000 output-file=out.mp4
[ERROR] /root/build/FastDeploy/streamer/src/app/base_app.cc(112)::SetupPerfMeasurement  Can't find a properly sink bin in the pipeline
Aborted

**Comment by wang-xinyu** [comment]
> 运行：`gst-inspect-1.0 | grep nv`看一下是否能找到DeepStream的plugin

还是运行一下这个

**Comment by jiangxinufo** [comment]
root@jiangxin:~/build/FastDeploy/streamer/examples/ppyoloe/cpp/build# gst-inspect-1.0 | grep nv
audioconvert:  audioconvert: Audio converter
nvdsgst_audiotemplate:  nvdsaudiotemplate: DS AUDIO template Plugin for Transform IP use-cases
nvdsgst_dewarper:  nvdewarper: nvdewarper
nvdsgst_dsanalytics:  nvdsanalytics: DsAnalytics plugin
nvdsgst_dsexample:  dsexample: DsExample plugin
nvdsgst_eglglessink:  nveglglessink: EGL/GLES vout Sink
nvdsgst_jpegdec:  nvjpegdec: JPEG image decoder
nvdsgst_logger:  nvdslogger: Nvdslogger
nvdsgst_metamux:  nvdsmetamux: meta muxer
nvdsgst_metautils:  nvdsmetaextract: nvdsmetaextract
nvdsgst_metautils:  nvdsmetainsert: nvdsmetainsert
nvdsgst_msgbroker:  nvmsgbroker: Message Broker
nvdsgst_multistreamtiler:  nvmultistreamtiler: Stream Tiler DS
nvdsgst_nvblender:  nvblender: Compositor
nvdsgst_of:  nvof: nvof
nvdsgst_ofvisual:  nvofvisual: nvofvisual
nvdsgst_osd:  nvdsosd: NvDsOsd plugin
nvdsgst_postprocess:  nvdspostprocess: NvDsPostProcess plugin for Transform/In-Place use-cases
nvdsgst_segvisual:  nvsegvisual: nvsegvisual
nvdsgst_speech:  nvdsasr: DS ASR Plugin for speech use-cases
nvdsgst_text_to_speech:  nvds_text_to_speech: DS Text To Speech Plugin for Conversational AI use cases
nvdsgst_tracker:  nvtracker: NvTracker plugin
nvdsgst_ucx:  nvdsucxclientsink: UCX client sink
nvdsgst_ucx:  nvdsucxclientsrc: UCX client source
nvdsgst_ucx:  nvdsucxserversink: UCX server sink
nvdsgst_ucx:  nvdsucxserversrc: UCX server source
nvdsgst_videotemplate:  nvdsvideotemplate: NvDsVideoTemplate plugin for Transform/In-Place use-cases
nvvideo4linux2:  nvv4l2decoder: NVIDIA v4l2 video decoder
nvvideo4linux2:  nvv4l2h264enc: V4L2 H.264 Encoder
nvvideo4linux2:  nvv4l2h265enc: V4L2 H.265 Encoder
nvvideoconvert:  nvvideoconvert: NvVidConv Plugin
opengl:  glcolorconvert: OpenGL color converter
opengl:  gleffects_blur: Blur with 9x9 separable convolution Effect
opengl:  gleffects_laplacian: Laplacian Convolution Demo Effect
opengl:  glviewconvert: OpenGL Multiview/3D conversion filter
videoconvert:  videoconvert: Colorspace converter

**Comment by wang-xinyu** [comment]
你这里没有nvvideoencfilesinkbin

运行：gst-inspect-1.0 -b 看一下

**Comment by jiangxinufo** [comment]
root@jiangxin:~/build/FastDeploy/streamer/examples/ppyoloe/cpp/build# gst-inspect-1.0 -b
Blacklisted files:
  libcustom2d_preprocess.so
  libnvdsgst_3dfilter.so
  libnvdsgst_deepstream_bins.so
  libnvdsgst_infer.so
  libnvdsgst_inferaudio.so
  libnvdsgst_inferserver.so
  libnvdsgst_msgconv.so
  libnvdsgst_multistream.so
  libnvdsgst_preprocess.so
  libnvdsgst_udp.so

Total count: 10 blacklisted files

**Comment by wang-xinyu** [comment]
libnvdsgst_deepstream_bins、libnvdsgst_infer被黑名单了，DeepStream的依赖项没有安装好。再看看DeepStream的文档重新安装DeepStream吧，或者用docker

**Comment by jiangxinufo** [comment]
@wang-xinyu 好的，感谢，我之前拉了docker，请教下，用docker我还有修改哪些配置吗？

**Comment by wang-xinyu** [comment]
不需要，有问题可以再提个issue哈
