### ISSUE TITLE
不同平台编译问题咨询

### ISSUE THREAD

**Issue by wsx958191** [PaddlePaddle/FastDeploy#150]
你好，
      我这边在搭建环境过程中，看见好多third_party都是需要直接下载使用的，不知道是否可行在不同平台自己拿源码编译，有没有变异文档类似资料？

**Comment by DefTruth** [comment]
可以在这里找到我们的编译文档，目前支持在Linux/Mac/Win下源码编译：
* [FastFeploy C++ 源码编译文档](https://github.com/PaddlePaddle/FastDeploy/tree/develop/docs/compile)

**Comment by DefTruth** [comment]
请问您主要是想在什么平台下使用FastDeploy呢？

**Comment by wsx958191** [comment]
我这边主要想在linux和win平台上？不知道后续是否有计划引入wav2lip的能力

**Comment by DefTruth** [comment]
linux和win上，我们目前有提供了C++的预编译库。
- [FastDeploy C++ SDK 预编译库](https://github.com/PaddlePaddle/FastDeploy/blob/develop/docs/quick_start/CPP_prebuilt_libraries.md)

**Comment by DefTruth** [comment]
关于wav2lip，这应该是语音唇型驱动的模型，请问您主要是想用在什么场景呢？我们目前模型这块，是以CV/NLP为主，但是有计划添加语音相关的模型

**Comment by wsx958191** [comment]
你好，这个预计大概什么时候会有beta版本出来

**Comment by DefTruth** [comment]
预计是下个Q，目前的主打模型是CV/NLP，欢迎持续关注FastDeploy哈 ~

**Comment by wsx958191** [comment]
OK，我看FastdePoly已经支持segmentation，也支持HH-humanSeq，这个我应该怎么测试叠加，背景替换的功能哈

![企业微信截图_d3a9f47f-86c7-40bc-98e8-5ed5ec03665a](https://user-images.githubusercontent.com/66000167/186457530-470acda4-8f58-443f-ac71-6306f4b37a35.png)

**Comment by DefTruth** [comment]
我们的开发人员正在开发相关的辅助功能

**Comment by wsx958191** [comment]
哈喽，这个有预计发布时间吗？

**Comment by DefTruth** [comment]
这些分割和抠图类的辅助函数会逐步添加进来，预计在下个版本会更加完善，但是如果开发好了我们会先提到develop分支，您可以关注develop分支的最新进展哈~

**Comment by jiangjiajun** [comment]
此ISSUE由于一年未更新，将会关闭处理，如有需要，可再次更新打开。
