### ISSUE TITLE
测试调用  编译的so文件出现   undefined reference to `paddle::AnalysisConfig::SetExecStream(void*)'

### ISSUE THREAD

**Issue by kekezhu0000** [PaddlePaddle/FastDeploy#1501]
## 环境

- 【FastDeploy版本】： fastdeploy-linux-x64-1.0.3
- 【编译命令】如果您是自行编译的FastDeploy，请说明您的编译方式（参数命令）
- 【系统平台】: Linux x64(Ubuntu 20.10)
- 【硬件】： CPU
- 【编译语言】： C++ 

## 问题日志及出现问题的操作流程
调用  fastdeploy-linux-x64-1.0.3    matting  编译的SO文件出错，前段事件使用的 fastdeploy-linux-x64-0.2.0 这个版本没有问题！
![微信图片_20230303084524](https://user-images.githubusercontent.com/47800318/222618532-ce5d6ba5-0467-4425-b3a4-a8395da5ea0c.png)
这是编译  libkt_demo.so 的CMakelists.txt
![微信图片_20230303084918](https://user-images.githubusercontent.com/47800318/222618554-814a6bd0-aa21-4d9c-ac30-76357385d4d2.png)
这是编译 测试调用libkt_demo.so的CMakelists.txt
![微信图片_20230303102626](https://user-images.githubusercontent.com/47800318/222618586-338f158d-7ce8-4502-ba73-cc5e5f5160df.png)

**Comment by jiangjiajun** [comment]
这个问题一般在于LD_LIBRARY_PATH中存在其它版本的fastdeploy或paddle inference库导致。 可自行检查下环境，例如ldd libfastdeploy.so，查看其链接的libpaddle_inference.so路径是否正确

**Comment by kekezhu0000** [comment]
今天我又检查了一下，usr/lib目录下删除   libpaddle2onnx.so.1.0 就好了，非常感谢您的提示，谢谢！！
> 这个问题一般在于LD_LIBRARY_PATH中存在其它版本的fastdeploy或paddle inference库导致。 可自行检查下环境，例如ldd libfastdeploy.so，查看其链接的libpaddle_inference.so路径是否正确
