### ISSUE TITLE
什么时候也来个特征图可视化

### ISSUE THREAD

**Issue by monkeycc** [PaddlePaddle/FastDeploy#1502]
https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.6/docs/tutorials/GradCAM_cn.md

**Comment by leiqing1** [comment]
@monkeycc 你好 出这个热力图，在部署时有什么用途吗？

**Comment by monkeycc** [comment]
只是生成热力图的脚本而已

部署不需要这种东西
