### ISSUE TITLE
请问 KIE 任务应该如何配置？

### ISSUE THREAD

**Issue by sunetic** [PaddlePaddle/FastDeploy#1504]
已经根据 https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/ppstructure/kie/README_ch.md 训练好模型。

但现在Fastdeploy 的 API尚未支持？参数只能传 det，cls 这几个模型参数

<img width="802" alt="image" src="https://user-images.githubusercontent.com/2182116/222757852-f5b8414b-2576-4a31-8196-e8d44043eb3f.png">

**Comment by sunetic** [comment]
@jiangjiajun 确认下暂时不支持对吧？需要根据 https://github.com/PaddlePaddle/FastDeploy/blob/develop/docs/cn/faq/develop_a_new_model.md

自行集成？感谢~

**Comment by jiangjiajun** [comment]
是的

**Comment by sunetic** [comment]
收到，请问有计划支持和时间点吗？

**Comment by jiangjiajun** [comment]
目前还没计划，不过如果你有意愿支持，我可以协助解决在集成中的问题（可在微信用户群中找到我的头像加我）
