### ISSUE TITLE
执行FastDeploy Streamer PP-YOLOE C++ Example中./streamer_demo时Can't find a properly sink bin in the pipeline

### ISSUE THREAD

**Issue by jiangxinufo** [PaddlePaddle/FastDeploy#1505]
## 环境

- 【FastDeploy版本】： fastdeploy-linux-gpu-1.0.4
- 【编译命令】cmake
- 【系统平台】: Linux x64(wls Ubuntu 22.04)
- 【硬件】： Nvidia GPU T4， CUDA 11.7 CUDNN 8.8
- 【编译语言】： C++ / Python(3.7或3.8等）

## 问题日志及出现问题的操作流程
*********************************************************************************************************************************************
相关问题已经在#1497中进行了沟通，@wang-xinyu 同学建议重新安装的deepstream或者使用docker，我已经拉了docker，想请教下运行起来这个docker的命令是什么呢？怎么能让我能顺利运行起来示例呢？
*********************************************************************************************************************************************
root@jiangxin:~/build/FastDeploy/streamer/examples/ppyoloe/cpp/build# ./streamer_demo
app
nvurisrcbin_list
nvstreammux
nvinfer
nvtracker
nvmultistreamtiler
nvosdbin
nvvideoencfilesinkbin
[INFO] /root/build/FastDeploy/streamer/src/gstreamer/utils.cc(60)::CreatePipeline       Trying to launch pipeline: nvurisrcbin uri=file:///opt/nvidia/deepstream/deepstream-6.1/samples/streams/sample_ride_bike.mov gpu-id=0 ! mux.sink_0  nvurisrcbin uri=file:///opt/nvidia/deepstream/deepstream-6.1/samples/streams/sample_ride_bike.mov gpu-id=0 ! mux.sink_1  nvurisrcbin uri=file:///opt/nvidia/deepstream/deepstream-6.1/samples/streams/sample_ride_bike.mov gpu-id=0 ! mux.sink_2  nvurisrcbin uri=file:///opt/nvidia/deepstream/deepstream-6.1/samples/streams/sample_ride_bike.mov gpu-id=0 ! mux.sink_3  nvstreammux name=mux gpu-id=0 batch-size=4 width=1920 height=1080 batched-push-timeout=40000 ! nvinfer gpu-id=0 config-file-path=nvinfer_config.txt ! nvtracker gpu-id=0 tracker-width=640 tracker-height=640 ll-lib-file=/opt/nvidia/deepstream/deepstream-6.1/lib/libnvds_nvmultiobjecttracker.so ll-config-file=/opt/nvidia/deepstream/deepstream-6.1/samples/configs/deepstream-app/config_tracker_NvDCF_perf.yml enable-batch-process=true ! nvmultistreamtiler gpu-id=0 rows=2 columns=2 ! nvosdbin gpu-id=0 ! nvvideoencfilesinkbin gpu-id=0 bitrate=4000 output-file=out.mp4
[ERROR] /root/build/FastDeploy/streamer/src/app/base_app.cc(112)::SetupPerfMeasurement  Can't find a properly sink bin in the pipeline
Aborted

**Comment by wang-xinyu** [comment]
和运行其他的GPU docker没什么区别，不需要特殊的命令，例如
```
docker run -it --net=host --gpus all nvcr.io/nvidia/deepstream:6.1.1-devel bash
```

**Comment by jiangxinufo** [comment]
大佬，
root@jiangxin:~/build/FastDeploy/streamer/examples/ppyoloe/cpp# nvcc -V
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2022 NVIDIA Corporation
Built on Tue_May__3_18:49:52_PDT_2022
Cuda compilation tools, release 11.7, V11.7.64
Build cuda_11.7.r11.7/compiler.31294372_0
root@jiangxin:~/build/FastDeploy/streamer/examples/ppyoloe/cpp# docker ps -l
CONTAINER ID   IMAGE                                   COMMAND   CREATED              STATUS    PORTS     NAMES
e9771fd5954c   nvcr.io/nvidia/deepstream:6.1.1-devel   "bash"    About a minute ago   Created             goofy_dubinsky
root@jiangxin:~/build/FastDeploy/streamer/examples/ppyoloe/cpp# docker run -it --net=host --gpus all nvcr.io/nvidia/deepstream:6.1.1-devel bash
docker: Error response from daemon: could not select device driver "" with capabilities: [[gpu]].
ERRO[0000] error waiting for container:
root@jiangxin:~/build/FastDeploy/streamer/examples/ppyoloe/cpp#
