### ISSUE TITLE
C API增加FD_C_CreateDetectionResult

### ISSUE THREAD

**Issue by huipeng8** [PaddlePaddle/FastDeploy#1509]
编译FastDeploy C API发现

 ### Vision Predict函数 ###
```
FD_C_Bool FD_C_PPYOLOEWrapperPredict(
    __fd_take FD_C_PPYOLOEWrapper* fd_c_ppyoloe_wrapper, FD_C_Mat img,
    FD_C_DetectionResult* fd_c_detection_result)
```
传入的是FD_C_DetectionResult*，而并没有相关初始化API，在[paddledetection_c](https://github.com/PaddlePaddle/FastDeploy/blob/develop/examples/vision/detection/paddledetection/c/infer_ppyoloe.c)范例中使用的是malloc来初始化
```
  FD_C_DetectionResult* result =
      (FD_C_DetectionResult*)malloc(sizeof(FD_C_DetectionResult));
```
对于一些无法手动分配内存的语言不太友好，建议增加相关初始化函数以便调用。
```
FD_C_DetectionResult* FD_C_CreateDetectionResult() {
    FD_C_DetectionResult* result = (FD_C_DetectionResult*)malloc(sizeof(FD_C_DetectionResult));
    return  result;
}
```
谢谢。

**Comment by rainyfly** [comment]
已收到反馈，谢谢

**Comment by rainyfly** [comment]
已经添加，下一个小版本进入FastDeploy https://github.com/PaddlePaddle/FastDeploy/pull/1547
