### ISSUE TITLE
fastdeploy编译在jetson nano上，推理examples的yolov5face模型报错

### ISSUE THREAD

**Issue by jm7301** [PaddlePaddle/FastDeploy#1511]
*********************************************
温馨提示：根据社区不完全统计，按照模板提问，可以加快回复和解决问题的速度
*********************************************

## 环境

- 【FastDeploy版本】： git clone https://github.com/PaddlePaddle/FastDeploy.git最新
- 【编译命令】
cd FastDeploy/python
export BUILD_ON_JETSON=ON
export ENABLE_VISION=ON

# ENABLE_PADDLE_BACKEND & PADDLEINFERENCE_DIRECTORY为可选项
export ENABLE_PADDLE_BACKEND=ON
export PADDLEINFERENCE_DIRECTORY=/Download/paddle_inference_jetson

python setup.py build
python setup.py bdist_wheel
安装pip install *****

- 【系统平台】: Linux x64(Ubuntu 18.04) 
- 【硬件】： 说明具体硬件型号，如 Nvidia GPU 3080TI， CUDA 10.2 CUDNN 8.2
- 【编译语言】： Python(3.6）

## 问题日志及出现问题的操作流程
- 附上详细的问题日志有助于快速定位分析
- 【模型跑不通】
- - 执行/FastDeploy/examples/vision/facedet/yolov5face/python
- - 执行： python infer.py --model yolov5s-face.onnx --image a.jpg --device gpu
            **报错**：     WARNING:root:The installed fastdeploy-python package is not built with GPU, will force to use CPU. To use GPU, following the commands to install fas                 tdeploy-gpu-python.
WARNING:root:    ================= Install GPU FastDeploy===============
WARNING:root:    python -m pip uninstall fastdeploy-python
WARNING:root:    python -m pip install fastdeploy-gpu-python -f https://www.paddlepaddle.org.cn/whl/fastdeploy.html
Traceback (most recent call last):
  File "infer.py", line 42, in <module>
    model = fd.vision.facedet.YOLOv5Face(args.model, runtime_option=runtime_option)
  File "/home/dlinano/.local/lib/python3.6/site-packages/fastdeploy/vision/facedet/contrib/yolov5face.py", line 38, in __init__
    self._model = C.vision.facedet.YOLOv5Face(
AttributeError: module 'fastdeploy.c_lib_wrap' has no attribute 'vision'
- - 执行： python infer.py --model yolov5s-face.onnx --image a.jpg --device cpu
- **报错**：Traceback (most recent call last):
  File "infer.py", line 42, in <module>
    model = fd.vision.facedet.YOLOv5Face(args.model, runtime_option=runtime_option)
  File "/home/dlinano/.local/lib/python3.6/site-packages/fastdeploy/vision/facedet/contrib/yolov5face.py", line 38, in __init__
    self._model = C.vision.facedet.YOLOv5Face(
AttributeError: module 'fastdeploy.c_lib_wrap' has no attribute 'vision'

**Comment by jiangjiajun** [comment]
编译时，需要添加编译开关ENABLE_VISION为ON

**Comment by jm7301** [comment]
> 编译时，需要添加编译开关ENABLE_VISION为ON

编译时加了export ENABLE_VISION=ON，但还是不行，我用cpu报下面那段错误

**Comment by jiangjiajun** [comment]
删除缓存，重新编译，注意看编译时打出来的信息，确认开关已经打开

**Comment by jm7301** [comment]
> 删除缓存，重新编译，注意看编译时打出来的信息，确认开关已经打开

> 重新执行
“dlinano@jetson-nano:~$ cd FastDeploy/python
dlinano@jetson-nano:~/FastDeploy/python$ export BUILD_ON_JETSON=ON
dlinano@jetson-nano:~/FastDeploy/python$ export ENABLE_VISION=ON
dlinano@jetson-nano:~/FastDeploy/python$ export ENABLE_PADDLE_BACKEND=ON
dlinano@jetson-nano:~/FastDeploy/python$ export PADDLEINFERENCE_DIRECTORY=/Download/paddle_inference_jetson
dlinano@jetson-nano:~/FastDeploy/python$”
，在执行dlinano@jetson-nano:~/FastDeploy/python$ sudo python setup.py build
看到控制台显示：

> running build
running build_py
running create_version
running cmake_build
Decompress file /home/dlinano/FastDeploy/python/.setuptools-cmake-build/patchelf-0.15.0-aarch64.tar.gz ...
--
-- *************FastDeploy Building Summary**********
--   CMake version             : 3.10.2
--   CMake command             : /usr/bin/cmake
--   System                    : Linux
--   C++ compiler              : /usr/bin/c++
--   C++ compiler version      : 7.5.0
--   CXX flags                 : -Wno-format -g0 -O3
--   EXE linker flags          :
--   Shared linker flags       :
--   Build type                : Release
--   Compile definitions       : _GLIBCXX_USE_CXX11_ABI=1;FASTDEPLOY_LIB;CMAKE_BUILD_TYPE=Release
--   CMAKE_PREFIX_PATH         :
--   CMAKE_INSTALL_PREFIX      : /usr/local
--   CMAKE_MODULE_PATH         :
--
--   FastDeploy version        : 0.0.0
--   ENABLE_ORT_BACKEND        : OFF
--   ENABLE_RKNPU2_BACKEND     : OFF
--   ENABLE_SOPHGO_BACKEND     : OFF
--   ENABLE_PADDLE_BACKEND     : OFF
--   ENABLE_LITE_BACKEND       : OFF
--   ENABLE_POROS_BACKEND      : OFF
--   ENABLE_TRT_BACKEND        : OFF
--   ENABLE_OPENVINO_BACKEND   : OFF
--   ENABLE_BENCHMARK          : OFF
--   ENABLE_VISION             : OFF
--   ENABLE_TEXT               : OFF
--   ENABLE_ENCRYPTION         : OFF
--   ENABLE_FLYCV              : OFF
--   ENABLE_CVCUDA             : OFF
--   WITH_GPU                  : OFF
--   WITH_IPU                  : OFF
--   WITH_TESTING              : OFF
--   WITH_ASCEND               : OFF
--   WITH_DIRECTML             : OFF
--   WITH_TIMVX                : OFF
--   WITH_KUNLUNXIN            : OFF
--   WITH_CAPI                 : OFF
--   WITH_CSHARPAPI            : OFF
--   Python executable         : /usr/bin/python
--   Python includes           : /usr/include/python3.6m
-- Configuring done
-- Generating done
-- Build files have been written to: /home/dlinano/FastDeploy/python/.setuptools-cmake-build
[ 70%] Built target fastdeploy
[100%] Built target fastdeploy_main
[100%] Built target copy_third_libraries
[100%] Built target copy_fd_libraries
creating build
creating build/lib.linux-aarch64-3.6
creating build/lib.linux-aarch64-3.6/fastdeploy
copying fastdeploy/download.py -> build/lib.linux-aarch64-3.6/fastdeploy
copying fastdeploy/code_version.py -> build/lib.linux-aarch64-3.6/fastdeploy
copying fastdeploy/model.py -> build/lib.linux-aarch64-3.6/fastdeploy
copying fastdeploy/runtime.py -> build/lib.linux-aarch64-3.6/fastdeploy
copying fastdeploy/__init__.py -> build/lib.linux-aarch64-3.6/fastdeploy
copying fastdeploy/c_lib_wrap.py -> build/lib.linux-aarch64-3.6/fastdeploy
creating build/lib.linux-aarch64-3.6/fastdeploy/utils
copying fastdeploy/utils/hub_model_server.py -> build/lib.linux-aarch64-3.6/fastdeploy/utils
copying fastdeploy/utils/hub_config.py -> build/lib.linux-aarch64-3.6/fastdeploy/utils
copying fastdeploy/utils/hub_env.py -> build/lib.linux-aarch64-3.6/fastdeploy/utils
copying fastdeploy/utils/__init__.py -> build/lib.linux-aarch64-3.6/fastdeploy/utils
copying fastdeploy/utils/example_resource.py -> build/lib.linux-aarch64-3.6/fastdeploy/utils
creating build/lib.linux-aarch64-3.6/fastdeploy/serving
copying fastdeploy/serving/utils.py -> build/lib.linux-aarch64-3.6/fastdeploy/serving
copying fastdeploy/serving/model_manager.py -> build/lib.linux-aarch64-3.6/fastdeploy/serving
copying fastdeploy/serving/__init__.py -> build/lib.linux-aarch64-3.6/fastdeploy/serving
copying fastdeploy/serving/server.py -> build/lib.linux-aarch64-3.6/fastdeploy/serving
creating build/lib.linux-aarch64-3.6/fastdeploy/text
copying fastdeploy/text/__init__.py -> build/lib.linux-aarch64-3.6/fastdeploy/text
creating build/lib.linux-aarch64-3.6/fastdeploy/pipeline
copying fastdeploy/pipeline/__init__.py -> build/lib.linux-aarch64-3.6/fastdeploy/pipeline
creating build/lib.linux-aarch64-3.6/fastdeploy/vision
copying fastdeploy/vision/utils.py -> build/lib.linux-aarch64-3.6/fastdeploy/vision
copying fastdeploy/vision/__init__.py -> build/lib.linux-aarch64-3.6/fastdeploy/vision
creating build/lib.linux-aarch64-3.6/fastdeploy/libs
copying fastdeploy/libs/__init__.py -> build/lib.linux-aarch64-3.6/fastdeploy/libs
creating build/lib.linux-aarch64-3.6/fastdeploy/encryption
copying fastdeploy/encryption/encryption.py -> build/lib.linux-aarch64-3.6/fastdeploy/encryption
copying fastdeploy/encryption/__init__.py -> build/lib.linux-aarch64-3.6/fastdeploy/encryption
creating build/lib.linux-aarch64-3.6/fastdeploy/serving/router
copying fastdeploy/serving/router/http_router.py -> build/lib.linux-aarch64-3.6/fastdeploy/serving/router
copying fastdeploy/serving/router/base_router.py -> build/lib.linux-aarch64-3.6/fastdeploy/serving/router
copying fastdeploy/serving/router/__init__.py -> build/lib.linux-aarch64-3.6/fastdeploy/serving/router
creating build/lib.linux-aarch64-3.6/fastdeploy/serving/handler
copying fastdeploy/serving/handler/base_handler.py -> build/lib.linux-aarch64-3.6/fastdeploy/serving/handler
copying fastdeploy/serving/handler/vision_model_handler.py -> build/lib.linux-aarch64-3.6/fastdeploy/serving/handler
copying fastdeploy/serving/handler/__init__.py -> build/lib.linux-aarch64-3.6/fastdeploy/serving/handler
creating build/lib.linux-aarch64-3.6/fastdeploy/text/uie
copying fastdeploy/text/uie/__init__.py -> build/lib.linux-aarch64-3.6/fastdeploy/text/uie
creating build/lib.linux-aarch64-3.6/fastdeploy/pipeline/pptinypose
copying fastdeploy/pipeline/pptinypose/__init__.py -> build/lib.linux-aarch64-3.6/fastdeploy/pipeline/pptinypose
creating build/lib.linux-aarch64-3.6/fastdeploy/vision/common
copying fastdeploy/vision/common/manager.py -> build/lib.linux-aarch64-3.6/fastdeploy/vision/common
copying fastdeploy/vision/common/__init__.py -> build/lib.linux-aarch64-3.6/fastdeploy/vision/common
creating build/lib.linux-aarch64-3.6/fastdeploy/vision/generation
copying fastdeploy/vision/generation/__init__.py -> build/lib.linux-aarch64-3.6/fastdeploy/vision/generation
creating build/lib.linux-aarch64-3.6/fastdeploy/vision/sr
copying fastdeploy/vision/sr/__init__.py -> build/lib.linux-aarch64-3.6/fastdeploy/vision/sr
creating build/lib.linux-aarch64-3.6/fastdeploy/vision/facealign
copying fastdeploy/vision/facealign/__init__.py -> build/lib.linux-aarch64-3.6/fastdeploy/vision/facealign
creating build/lib.linux-aarch64-3.6/fastdeploy/vision/classification
copying fastdeploy/vision/classification/__init__.py -> build/lib.linux-aarch64-3.6/fastdeploy/vision/classification
creating build/lib.linux-aarch64-3.6/fastdeploy/vision/headpose
copying fastdeploy/vision/headpose/__init__.py -> build/lib.linux-aarch64-3.6/fastdeploy/vision/headpose
creating build/lib.linux-aarch64-3.6/fastdeploy/vision/segmentation
copying fastdeploy/vision/segmentation/__init__.py -> build/lib.linux-aarch64-3.6/fastdeploy/vision/segmentation
creating build/lib.linux-aarch64-3.6/fastdeploy/vision/evaluation
copying fastdeploy/vision/evaluation/segmentation.py -> build/lib.linux-aarch64-3.6/fastdeploy/vision/evaluation
copying fastdeploy/vision/evaluation/detection.py -> build/lib.linux-aarch64-3.6/fastdeploy/vision/evaluation
copying fastdeploy/vision/evaluation/__init__.py -> build/lib.linux-aarch64-3.6/fastdeploy/vision/evaluation
copying fastdeploy/vision/evaluation/classify.py -> build/lib.linux-aarch64-3.6/fastdeploy/vision/evaluation
creating build/lib.linux-aarch64-3.6/fastdeploy/vision/matting
copying fastdeploy/vision/matting/__init__.py -> build/lib.linux-aarch64-3.6/fastdeploy/vision/matting
creating build/lib.linux-aarch64-3.6/fastdeploy/vision/faceid
copying fastdeploy/vision/faceid/__init__.py -> build/lib.linux-aarch64-3.6/fastdeploy/vision/faceid
creating build/lib.linux-aarch64-3.6/fastdeploy/vision/ocr
copying fastdeploy/vision/ocr/__init__.py -> build/lib.linux-aarch64-3.6/fastdeploy/vision/ocr
creating build/lib.linux-aarch64-3.6/fastdeploy/vision/tracking
copying fastdeploy/vision/tracking/__init__.py -> build/lib.linux-aarch64-3.6/fastdeploy/vision/tracking
creating build/lib.linux-aarch64-3.6/fastdeploy/vision/visualize
copying fastdeploy/vision/visualize/__init__.py -> build/lib.linux-aarch64-3.6/fastdeploy/vision/visualize
creating build/lib.linux-aarch64-3.6/fastdeploy/vision/keypointdetection
copying fastdeploy/vision/keypointdetection/__init__.py -> build/lib.linux-aarch64-3.6/fastdeploy/vision/keypointdetection
creating build/lib.linux-aarch64-3.6/fastdeploy/vision/detection
copying fastdeploy/vision/detection/__init__.py -> build/lib.linux-aarch64-3.6/fastdeploy/vision/detection
creating build/lib.linux-aarch64-3.6/fastdeploy/vision/facedet
copying fastdeploy/vision/facedet/__init__.py -> build/lib.linux-aarch64-3.6/fastdeploy/vision/facedet
creating build/lib.linux-aarch64-3.6/fastdeploy/vision/generation/contrib
copying fastdeploy/vision/generation/contrib/__init__.py -> build/lib.linux-aarch64-3.6/fastdeploy/vision/generation/contrib
copying fastdeploy/vision/generation/contrib/anemigan.py -> build/lib.linux-aarch64-3.6/fastdeploy/vision/generation/contrib
creating build/lib.linux-aarch64-3.6/fastdeploy/vision/sr/ppsr
copying fastdeploy/vision/sr/ppsr/__init__.py -> build/lib.linux-aarch64-3.6/fastdeploy/vision/sr/ppsr
creating build/lib.linux-aarch64-3.6/fastdeploy/vision/facealign/contrib
copying fastdeploy/vision/facealign/contrib/face_landmark_1000.py -> build/lib.linux-aarch64-3.6/fastdeploy/vision/facealign/contrib
copying fastdeploy/vision/facealign/contrib/__init__.py -> build/lib.linux-aarch64-3.6/fastdeploy/vision/facealign/contrib
copying fastdeploy/vision/facealign/contrib/pfld.py -> build/lib.linux-aarch64-3.6/fastdeploy/vision/facealign/contrib
copying fastdeploy/vision/facealign/contrib/pipnet.py -> build/lib.linux-aarch64-3.6/fastdeploy/vision/facealign/contrib
creating build/lib.linux-aarch64-3.6/fastdeploy/vision/classification/ppcls
copying fastdeploy/vision/classification/ppcls/__init__.py -> build/lib.linux-aarch64-3.6/fastdeploy/vision/classification/ppcls
creating build/lib.linux-aarch64-3.6/fastdeploy/vision/classification/contrib
copying fastdeploy/vision/classification/contrib/yolov5cls.py -> build/lib.linux-aarch64-3.6/fastdeploy/vision/classification/contrib
copying fastdeploy/vision/classification/contrib/resnet.py -> build/lib.linux-aarch64-3.6/fastdeploy/vision/classification/contrib
copying fastdeploy/vision/classification/contrib/__init__.py -> build/lib.linux-aarch64-3.6/fastdeploy/vision/classification/contrib
creating build/lib.linux-aarch64-3.6/fastdeploy/vision/headpose/contrib
copying fastdeploy/vision/headpose/contrib/fsanet.py -> build/lib.linux-aarch64-3.6/fastdeploy/vision/headpose/contrib
copying fastdeploy/vision/headpose/contrib/__init__.py -> build/lib.linux-aarch64-3.6/fastdeploy/vision/headpose/contrib
creating build/lib.linux-aarch64-3.6/fastdeploy/vision/segmentation/ppseg
copying fastdeploy/vision/segmentation/ppseg/__init__.py -> build/lib.linux-aarch64-3.6/fastdeploy/vision/segmentation/ppseg
creating build/lib.linux-aarch64-3.6/fastdeploy/vision/evaluation/utils
copying fastdeploy/vision/evaluation/utils/map_utils.py -> build/lib.linux-aarch64-3.6/fastdeploy/vision/evaluation/utils
copying fastdeploy/vision/evaluation/utils/seg_metrics.py -> build/lib.linux-aarch64-3.6/fastdeploy/vision/evaluation/utils
copying fastdeploy/vision/evaluation/utils/coco.py -> build/lib.linux-aarch64-3.6/fastdeploy/vision/evaluation/utils
copying fastdeploy/vision/evaluation/utils/json_results.py -> build/lib.linux-aarch64-3.6/fastdeploy/vision/evaluation/utils
copying fastdeploy/vision/evaluation/utils/cityscapes.py -> build/lib.linux-aarch64-3.6/fastdeploy/vision/evaluation/utils
copying fastdeploy/vision/evaluation/utils/coco_utils.py -> build/lib.linux-aarch64-3.6/fastdeploy/vision/evaluation/utils
copying fastdeploy/vision/evaluation/utils/coco_metrics.py -> build/lib.linux-aarch64-3.6/fastdeploy/vision/evaluation/utils
copying fastdeploy/vision/evaluation/utils/fd_logging.py -> build/lib.linux-aarch64-3.6/fastdeploy/vision/evaluation/utils
copying fastdeploy/vision/evaluation/utils/util.py -> build/lib.linux-aarch64-3.6/fastdeploy/vision/evaluation/utils
copying fastdeploy/vision/evaluation/utils/__init__.py -> build/lib.linux-aarch64-3.6/fastdeploy/vision/evaluation/utils
creating build/lib.linux-aarch64-3.6/fastdeploy/vision/matting/contrib
copying fastdeploy/vision/matting/contrib/rvm.py -> build/lib.linux-aarch64-3.6/fastdeploy/vision/matting/contrib
copying fastdeploy/vision/matting/contrib/__init__.py -> build/lib.linux-aarch64-3.6/fastdeploy/vision/matting/contrib
copying fastdeploy/vision/matting/contrib/modnet.py -> build/lib.linux-aarch64-3.6/fastdeploy/vision/matting/contrib
creating build/lib.linux-aarch64-3.6/fastdeploy/vision/matting/ppmatting
copying fastdeploy/vision/matting/ppmatting/__init__.py -> build/lib.linux-aarch64-3.6/fastdeploy/vision/matting/ppmatting
creating build/lib.linux-aarch64-3.6/fastdeploy/vision/faceid/contrib
copying fastdeploy/vision/faceid/contrib/__init__.py -> build/lib.linux-aarch64-3.6/fastdeploy/vision/faceid/contrib
creating build/lib.linux-aarch64-3.6/fastdeploy/vision/faceid/contrib/insightface
copying fastdeploy/vision/faceid/contrib/insightface/__init__.py -> build/lib.linux-aarch64-3.6/fastdeploy/vision/faceid/contrib/insightface
creating build/lib.linux-aarch64-3.6/fastdeploy/vision/faceid/contrib/adaface
copying fastdeploy/vision/faceid/contrib/adaface/__init__.py -> build/lib.linux-aarch64-3.6/fastdeploy/vision/faceid/contrib/adaface
creating build/lib.linux-aarch64-3.6/fastdeploy/vision/ocr/ppocr
copying fastdeploy/vision/ocr/ppocr/__init__.py -> build/lib.linux-aarch64-3.6/fastdeploy/vision/ocr/ppocr
creating build/lib.linux-aarch64-3.6/fastdeploy/vision/tracking/pptracking
copying fastdeploy/vision/tracking/pptracking/__init__.py -> build/lib.linux-aarch64-3.6/fastdeploy/vision/tracking/pptracking
creating build/lib.linux-aarch64-3.6/fastdeploy/vision/keypointdetection/pptinypose
copying fastdeploy/vision/keypointdetection/pptinypose/__init__.py -> build/lib.linux-aarch64-3.6/fastdeploy/vision/keypointdetection/pptinypose
creating build/lib.linux-aarch64-3.6/fastdeploy/vision/detection/contrib
copying fastdeploy/vision/detection/contrib/fastestdet.py -> build/lib.linux-aarch64-3.6/fastdeploy/vision/detection/contrib
copying fastdeploy/vision/detection/contrib/yolov7end2end_trt.py -> build/lib.linux-aarch64-3.6/fastdeploy/vision/detection/contrib
copying fastdeploy/vision/detection/contrib/yolov5seg.py -> build/lib.linux-aarch64-3.6/fastdeploy/vision/detection/contrib
copying fastdeploy/vision/detection/contrib/yolov7end2end_ort.py -> build/lib.linux-aarch64-3.6/fastdeploy/vision/detection/contrib
copying fastdeploy/vision/detection/contrib/yolov5lite.py -> build/lib.linux-aarch64-3.6/fastdeploy/vision/detection/contrib
copying fastdeploy/vision/detection/contrib/yolox.py -> build/lib.linux-aarch64-3.6/fastdeploy/vision/detection/contrib
copying fastdeploy/vision/detection/contrib/scaled_yolov4.py -> build/lib.linux-aarch64-3.6/fastdeploy/vision/detection/contrib
copying fastdeploy/vision/detection/contrib/yolov7.py -> build/lib.linux-aarch64-3.6/fastdeploy/vision/detection/contrib
copying fastdeploy/vision/detection/contrib/yolor.py -> build/lib.linux-aarch64-3.6/fastdeploy/vision/detection/contrib
copying fastdeploy/vision/detection/contrib/yolov6.py -> build/lib.linux-aarch64-3.6/fastdeploy/vision/detection/contrib
copying fastdeploy/vision/detection/contrib/nanodet_plus.py -> build/lib.linux-aarch64-3.6/fastdeploy/vision/detection/contrib
copying fastdeploy/vision/detection/contrib/__init__.py -> build/lib.linux-aarch64-3.6/fastdeploy/vision/detection/contrib
copying fastdeploy/vision/detection/contrib/yolov8.py -> build/lib.linux-aarch64-3.6/fastdeploy/vision/detection/contrib
copying fastdeploy/vision/detection/contrib/yolov5.py -> build/lib.linux-aarch64-3.6/fastdeploy/vision/detection/contrib
creating build/lib.linux-aarch64-3.6/fastdeploy/vision/detection/ppdet
copying fastdeploy/vision/detection/ppdet/__init__.py -> build/lib.linux-aarch64-3.6/fastdeploy/vision/detection/ppdet
creating build/lib.linux-aarch64-3.6/fastdeploy/vision/detection/contrib/rkyolo
copying fastdeploy/vision/detection/contrib/rkyolo/__init__.py -> build/lib.linux-aarch64-3.6/fastdeploy/vision/detection/contrib/rkyolo
copying fastdeploy/vision/detection/contrib/rkyolo/rkyolov5.py -> build/lib.linux-aarch64-3.6/fastdeploy/vision/detection/contrib/rkyolo
creating build/lib.linux-aarch64-3.6/fastdeploy/vision/facedet/contrib
copying fastdeploy/vision/facedet/contrib/ultraface.py -> build/lib.linux-aarch64-3.6/fastdeploy/vision/facedet/contrib
copying fastdeploy/vision/facedet/contrib/scrfd.py -> build/lib.linux-aarch64-3.6/fastdeploy/vision/facedet/contrib
copying fastdeploy/vision/facedet/contrib/yolov5face.py -> build/lib.linux-aarch64-3.6/fastdeploy/vision/facedet/contrib
copying fastdeploy/vision/facedet/contrib/blazeface.py -> build/lib.linux-aarch64-3.6/fastdeploy/vision/facedet/contrib
copying fastdeploy/vision/facedet/contrib/__init__.py -> build/lib.linux-aarch64-3.6/fastdeploy/vision/facedet/contrib
copying fastdeploy/vision/facedet/contrib/retinaface.py -> build/lib.linux-aarch64-3.6/fastdeploy/vision/facedet/contrib
copying fastdeploy/vision/facedet/contrib/centerface.py -> build/lib.linux-aarch64-3.6/fastdeploy/vision/facedet/contrib
copying fastdeploy/vision/facedet/contrib/yolov7face.py -> build/lib.linux-aarch64-3.6/fastdeploy/vision/facedet/contrib
running build_ext
copying /home/dlinano/FastDeploy/python/.setuptools-cmake-build/fastdeploy_main.cpython-36m-aarch64-linux-gnu.so -> /home/dlinano/FastDeploy/python/build/lib.linux-aarch64-3.6/fastdeploy
> 
好像没有打开export ENABLE_VISION=ON这个开关

**Comment by jm7301** [comment]
我不用gpu推理，使用cpu推理，也是报错

dlinano@jetson-nano:~/FastDeploy/examples/vision/facedet/yolov5face/python$ python infer.py --model yolov5s-face.onnx --image a.jpg --device cpu                     Traceback (most recent call last):
  File "infer.py", line 42, in <module>
    model = fd.vision.facedet.YOLOv5Face(args.model, runtime_option=runtime_option)
  File "/home/dlinano/.local/lib/python3.6/site-packages/fastdeploy/vision/facedet/contrib/yolov5face.py", line 38, in __init__
    self._model = C.vision.facedet.YOLOv5Face(
AttributeError: module 'fastdeploy.c_lib_wrap' has no attribute 'vision'

**Comment by vamoslc** [comment]
请问解决了吗？

**Comment by jiangjiajun** [comment]
@jm7301 我看贴出的日志中显示 `-- ENABLE_VISION : OFF`说明编译时没有开启VISION模块

**Comment by vamoslc** [comment]
> @jm7301 我看贴出的日志中显示 `-- ENABLE_VISION : OFF`说明编译时没有开启VISION模块



> 删除缓存，重新编译，注意看编译时打出来的信息，确认开关已经打开

请问怎样删除缓存

**Comment by vamoslc** [comment]
> @jm7301 我看贴出的日志中显示 `-- ENABLE_VISION : OFF`说明编译时没有开启VISION模块

root@linaro-alip:/home/linaro/LC/FastDeploy/python# export ENABLE_ORT_BACKEND=ON
root@linaro-alip:/home/linaro/LC/FastDeploy/python# export ENABLE_RKNPU2_BACKEND=ON
root@linaro-alip:/home/linaro/LC/FastDeploy/python# export ENABLE_VISION=ON
root@linaro-alip:/home/linaro/LC/FastDeploy/python# export RKNN2_TARGET_SOC=RK3588
root@linaro-alip:/home/linaro/LC/FastDeploy/python# python3 setup.py build
running build
running build_py
running create_version
running cmake_build
CMake Warning (dev) at CMakeLists.txt:15 (PROJECT):
  Policy CMP0048 is not set: project() command manages VERSION variables.
  Run "cmake --help-policy CMP0048" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.

  The following variable(s) would be set to empty:

    CMAKE_PROJECT_VERSION
    CMAKE_PROJECT_VERSION_MAJOR
    CMAKE_PROJECT_VERSION_MINOR
    CMAKE_PROJECT_VERSION_PATCH
This warning is for project developers.  Use -Wno-dev to suppress it.

Decompress file /home/linaro/LC/FastDeploy/python/.setuptools-cmake-build/patchelf-0.15.0-aarch64.tar.gz ...
-- Use the default onnxruntime lib. The ONNXRuntime path: /home/linaro/LC/FastDeploy/python/.setuptools-cmake-build/third_libs/install/onnxruntime
Decompress file /home/linaro/LC/FastDeploy/python/.setuptools-cmake-build/rknpu2_runtime-linux-aarch64-1.4.2b0-RK3588.tgz ...
-- Use the default OpenCV lib from: https://bj.bcebos.com/paddle2onnx/libs/opencv-linux-aarch64-3.4.14.tgz
Decompress file /home/linaro/LC/FastDeploy/python/.setuptools-cmake-build/opencv-linux-aarch64-3.4.14.tgz ...
--
-- *************FastDeploy Building Summary**********
--   CMake version             : 3.18.4
--   CMake command             : /usr/bin/cmake
--   System                    : Linux
--   C++ compiler              : /usr/bin/c++
--   C++ compiler version      : 10.2.1
--   CXX flags                 : -Wno-format -g0 -O3
--   EXE linker flags          :
--   Shared linker flags       :
--   Build type                : Release
--   Compile definitions       : _GLIBCXX_USE_CXX11_ABI=1;FASTDEPLOY_LIB;CMAKE_BUILD_TYPE=Release;ENABLE_ORT_BACKEND;ENABLE_RKNPU2_BACKEND;ENABLE_VISION;ENABLE_PADDLE2ONNX
--   CMAKE_PREFIX_PATH         :
--   CMAKE_INSTALL_PREFIX      : /usr/local
--   CMAKE_MODULE_PATH         :
--
--   FastDeploy version        : 0.0.0
--   ENABLE_ORT_BACKEND        : ON
--   ENABLE_RKNPU2_BACKEND     : ON
--   ENABLE_SOPHGO_BACKEND     : OFF
--   ENABLE_PADDLE_BACKEND     : OFF
--   ENABLE_LITE_BACKEND       : OFF
--   ENABLE_POROS_BACKEND      : OFF
--   ENABLE_TRT_BACKEND        : OFF
--   ENABLE_OPENVINO_BACKEND   : OFF
--   ENABLE_BENCHMARK          : OFF
--   ENABLE_VISION             : ON
--   ENABLE_TEXT               : OFF
--   ENABLE_ENCRYPTION         : OFF
--   ENABLE_FLYCV              : OFF
--   ENABLE_CVCUDA             : OFF
--   WITH_GPU                  : OFF
--   WITH_IPU                  : OFF
--   WITH_TESTING              : OFF
--   WITH_ASCEND               : OFF
--   WITH_DIRECTML             : OFF
--   WITH_TIMVX                : OFF
--   WITH_KUNLUNXIN            : OFF
--   WITH_CAPI                 : OFF
--   WITH_CSHARPAPI            : OFF
--   ONNXRuntime version       : 1.12.0
--   Python executable         : /usr/bin/python3
--   Python includes           : /usr/include/python3.9
-- Configuring done
-- Generating done
-- Build files have been written to: /home/linaro/LC/FastDeploy/python/.setuptools-cmake-build
[  2%] Built target extern_onnxruntime
[  8%] Built target extern_paddle2onnx
[ 16%] Built target yaml-cpp
[ 17%] Built target yaml-cpp-read
[ 18%] Built target yaml-cpp-parse
[ 18%] Built target yaml-cpp-sandbox
[ 77%] Built target fastdeploy
[100%] Built target fastdeploy_main
[100%] Built target copy_fd_libraries
[100%] Built target copy_third_libraries
copying fastdeploy/code_version.py -> build/lib.linux-aarch64-3.9/fastdeploy
running build_ext
root@linaro-alip:/home/linaro/LC/FastDeploy/python# cd /home/linaro/LC/FastDeploy/examples/vision/detection/paddledetection/rknpu2/python/
root@linaro-alip:/home/linaro/LC/FastDeploy/examples/vision/detection/paddledetection/rknpu2/python# python3 infer.py --model_file config/picodet_l_640_lcnet_rk3588_unquantized.rknn --config_file config/infer_cfg.yml --image config/0000364_01177_d_0000799_320_0_960_540.jpg
Traceback (most recent call last):
  File "/home/linaro/LC/FastDeploy/examples/vision/detection/paddledetection/rknpu2/python/infer.py", line 50, in <module>
    model = fd.vision.detection.PPYOLOE(
  File "/usr/local/lib/python3.9/dist-packages/fastdeploy/vision/detection/ppdet/__init__.py", line 101, in __init__
    self._model = C.vision.detection.PPYOLOE(
AttributeError: module 'fastdeploy.c_lib_wrap' has no attribute 'vision'
我这边开启了  但还是报错

**Comment by jiangjiajun** [comment]
编译完后，有重新pip install吗？

**Comment by vamoslc** [comment]
> 编译完后，有重新pip install吗？

请问需要重新install 哪些包？

**Comment by jiangjiajun** [comment]
`python setup.py build` -> `python setup.py bdist_wheel` -> `python -m pip install dist/fastdeploy.....whl`

**Comment by vamoslc** [comment]
> python setup.py bdist_wheel

还是报同样的错误

**Comment by jm7301** [comment]
> > 编译完后，有重新pip install吗？
> 
> 请问需要重新install 哪些包？

重新pip install 了

**Comment by jm7301** [comment]
> > 编译完后，有重新pip install吗？
> 
> 请问需要重新install 哪些包？

Duplicate of #

**Comment by jm7301** [comment]
> `python setup.py build` -> `python setup.py bdist_wheel` -> `python -m pip install dist/fastdeploy.....whl`

也是这样安装的

**Comment by jm7301** [comment]
> > python setup.py bdist_wheel
> 
> 还是报同样的错误

是的，报同样的错误

**Comment by vamoslc** [comment]
> Duplicate of #



> > > 编译完后，有重新pip install吗？
> > 
> > 
> > 请问需要重新install 哪些包？
> 
> Duplicate of #

Duplicate of 是一个指令码？

**Comment by jm7301** [comment]
还是不行
