### ISSUE TITLE
paddle ocr什么时候可以支持rk3588 npu？

### ISSUE THREAD

**Issue by leokwu** [PaddlePaddle/FastDeploy#1513]
paddle ocr什么时候可以支持rk3588 npu？

**Comment by Zheng-Bicheng** [comment]
已经支持了呀，看一下PPOCRv3的example

**Comment by leokwu** [comment]
https://github.com/PaddlePaddle/FastDeploy/blob/develop/examples/docs/en/build_and_install/download_prebuilt_libraries.md
这边已经是404？有新地址？

**Comment by jiangjiajun** [comment]
从来没有这个地址，是下面这个地址
https://github.com/PaddlePaddle/FastDeploy/blob/develop/docs/en/build_and_install/download_prebuilt_libraries.md

**Comment by leokwu** [comment]
https://github.com/PaddlePaddle/FastDeploy/blob/develop/docs/en/build_and_install/download_prebuilt_libraries.md
这个链接没看到有rknpu支持的包下载，是否需要自行编译？

**Comment by leokwu** [comment]
# 转换模型到ONNX格式的模型
paddle2onnx --model_dir ch_PP-OCRv3_det_infer \
            --model_filename inference.pdmodel \
            --params_filename inference.pdiparams \
            --save_file ch_PP-OCRv3_det_infer/ch_PP-OCRv3_det_infer.onnx \
            --enable_dev_version True
paddle2onnx --model_dir ch_ppocr_mobile_v2.0_cls_infer \
            --model_filename inference.pdmodel \
            --params_filename inference.pdiparams \
            --save_file ch_ppocr_mobile_v2.0_cls_infer/ch_ppocr_mobile_v2.0_cls_infer.onnx \
            --enable_dev_version True
paddle2onnx --model_dir ch_PP-OCRv3_rec_infer \
            --model_filename inference.pdmodel \
            --params_filename inference.pdiparams \
            --save_file ch_PP-OCRv3_rec_infer/ch_PP-OCRv3_rec_infer.onnx \
            --enable_dev_version True

另外，请教下，paddle2onnx  这个工具在哪里可以编译出来？或者找到？

**Comment by jiangjiajun** [comment]
参考这个文档说明吧 https://github.com/PaddlePaddle/FastDeploy/blob/develop/docs/en/build_and_install/rknpu2.md

**Comment by leokwu** [comment]
pip install paddle2onnx
安装完，找不到paddle2onnx这个bin，是否需要源码编译？
https://github.com/PaddlePaddle/Paddle2ONNX

**Comment by leokwu** [comment]
试了源码安装也没有paddle2onnx这个bin，请教下，这个bin从哪里编出来，或者哪里可以下到？

**Comment by leokwu** [comment]
在x86上安装可以有这个bin了。  感谢。
