### ISSUE TITLE
RK3588 PPOCRv3出现CPU速度快过NPU速度的问题

### ISSUE THREAD

**Issue by Zheng-Bicheng** [PaddlePaddle/FastDeploy#1515]
- 【FastDeploy版本】： develop
- 【编译命令】aarch-64
- 【系统平台】: Linux x64(Debian 10)
- 【硬件】： RK3588
- 【编译语言】： C++ / Python(3.7或3.8等）

**Comment by Zheng-Bicheng** [comment]
@KongXCai 在这里讨论吧。

**Comment by Zheng-Bicheng** [comment]
你能把你的设备具体信息发一下吗？包括芯片型号等等。

**Comment by KongXCai** [comment]
firefly的 ROC-RK3588S-PC
8G内存
设备信息：
https://wiki.t-firefly.com/zh_CN/ROC-RK3588S-PC/index.html#


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/FastDeploy"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月6日(星期一) 上午9:55
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/FastDeploy] RK3588 PPOCRv3出现CPU速度快过NPU速度的问题 (Issue #1515)





 
你能把你的设备具体信息发一下吗？包括芯片型号等等。

**Comment by Zheng-Bicheng** [comment]
> https://wiki.t-firefly.com/zh_CN/ROC-RK3588S-PC/index.html#

3588s下确实加速效果不明显，已经在准备做量化了，给些时间

**Comment by KongXCai** [comment]
好的，非常感谢！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/FastDeploy"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月6日(星期一) 上午10:30
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/FastDeploy] RK3588 PPOCRv3出现CPU速度快过NPU速度的问题 (Issue #1515)





  
https://wiki.t-firefly.com/zh_CN/ROC-RK3588S-PC/index.html#
  
3588s下确实加速效果不明显，已经在准备做量化了，给些时间
