### ISSUE TITLE
gpu docker 部署 cup占用高

### ISSUE THREAD

**Issue by zhangshengsheng** [PaddlePaddle/FastDeploy#1521]
registry.baidubce.com/paddlepaddle/fastdeploy:1.0.4-gpu-cuda11.4-trt8.5-21.10
1.0.4 版本  部署正常 调用报错
1.0.2 版本  部署正常 调用正常
1.0.2 版本  空闲时cup占用过大  4核处理器 cup持续占用30%左右  8核处理器 持续占用15%左右
https://github.com/triton-inference-server/server/issues/3779  这里可能是triton-inference-server解决方案 
希望飞浆可以尽快更新到 triton-inference-server 可以正常使用的版本

**Comment by zhangshengsheng** [comment]
https://github.com/triton-inference-server/python_backend/pull/112

**Comment by heliqi** [comment]
@zhangshengsheng 请问下用1.04报错是哪个模型？ 如果有修改config，把配置也贴下。
让我们能复现你说的问题。

我们预计月底前会把FastDeploy升级适配到较新的22.10/22.12

**Comment by zhangshengsheng** [comment]
@heliqi ppyoloe_plus_crn_x_80e_coco

**Comment by teymur-git** [comment]
@zhangshengsheng  请问你解决了吗？应该如何解决，和你一样的问题。https://github.com/triton-inference-server/server/issues/5942

**Comment by teymur-git** [comment]
> @zhangshengsheng 请问下用1.04报错是哪个模型？ 如果有修改config，把配置也贴下。 让我们能复现你说的问题。
> 
> 我们预计月底前会把FastDeploy升级适配到较新的22.10/22.12

@heliqi  请问下为什么没有将titrion serving升级？有cpu空闲占用bug

**Comment by polarisunny** [comment]
有22.10/22.12 的cpu镜像了吗
