### ISSUE TITLE
Seg模型  without-argmax with-argmax  有什么不同吗

### ISSUE THREAD

**Issue by monkeycc** [PaddlePaddle/FastDeploy#1524]
Seg模型

without-argmax
with-argmax
有什么不同吗

**Comment by jiangjiajun** [comment]
如果只需要分割模型得到最终的图像中各个像素的类别（即mask），则建议导出with-argmax的模型，性能会更优。

如果需要得到分割模型最终图像各个像素的类别（即mask），以及各个像素分类的置信度，则导出without-argmax的模型，但性能不如上面（因为需要后处理额外再做argmax操作，且对于置信度float数据的resize等处理更耗时）
