### ISSUE TITLE
rk3588 3核npu的分配问题

### ISSUE THREAD

**Issue by XDUwsk** [PaddlePaddle/FastDeploy#1525]
rk3588，使用的是ROC-rk3588s-pc，是firefly的板子，希望能在目前的fastdeploy的默认分配核心的基础上添加自定义核心分配的功能。

**Comment by jiangjiajun** [comment]
- C++接口： https://github.com/PaddlePaddle/FastDeploy/blob/develop/fastdeploy/runtime/runtime_option.h#L73
- Python接口：https://github.com/PaddlePaddle/FastDeploy/blob/develop/python/fastdeploy/runtime.py#L255

不知道上述两个接口是否能满足分配核心的配置

**Comment by Zheng-Bicheng** [comment]
这个核心功能我需要点时间测试下哈
