### ISSUE TITLE
FastDeploy 有没手部关键点检测,或者有没考虑手部关键点模型

### ISSUE THREAD

**Issue by monkeycc** [PaddlePaddle/FastDeploy#1526]
https://github.com/PaddlePaddle/PaddleHub/tree/develop/modules/image/keypoint_detection/hand_pose_localization

我看PaddleHub有个手部关键点检测
但是 FastDeploy PaddleDetection 都没

PaddleDetection  
关键点教程 也是云里雾里的

希望FastDeploy 增加手部关键点模型,
这样开箱即用

**Comment by jiangjiajun** [comment]
目前优先在支持飞桨各个CV套件的模型。其它模型暂时还没有计划，欢迎参与FastDeploy一起开源贡献：）
