### ISSUE TITLE
安装的gpu版本，但是使用的却是cpu

### ISSUE THREAD

**Issue by kankanjiuzou123** [PaddlePaddle/FastDeploy#1529]
怎么使用model在gpu上运行

**Comment by jiangjiajun** [comment]
需要通过RuntimeOption进行配置，具体可参考example下各示例代码

**Comment by kankanjiuzou123** [comment]
好的，感谢，我试一下

**Comment by kankanjiuzou123** [comment]
> 需要通过RuntimeOption进行配置，具体可参考example下各示例代码

您好，打扰了，没看明白如何设置。fastdeploy.RuntimeOption应该传入什么参数才能设置gpu呢，我设置gpu后将option传入PPYOLOE接口，报错'function' object has no attribute '_option'

**Comment by jiangjiajun** [comment]
https://github.com/PaddlePaddle/FastDeploy/blob/0687d3b0ad7bde71b8a9d7e083506195735a5917/examples/vision/detection/paddledetection/python/infer_ppyoloe.py#L30-L44 参考这个代码示例吧

**Comment by kankanjiuzou123** [comment]
> https://github.com/PaddlePaddle/FastDeploy/blob/0687d3b0ad7bde71b8a9d7e083506195735a5917/examples/vision/detection/paddledetection/python/infer_ppyoloe.py#L30-L44
> 
> 参考这个代码示例吧
好的，多谢。

**Comment by kankanjiuzou123** [comment]
> 需要通过RuntimeOption进行配置，具体可参考example下各示例代码
您好，再次打扰，我今天在nvidia jeston orin中安装fastdeploy,使用命令行安装无法import，是因为架构不同有别的安装方式么？
