### ISSUE TITLE
FastDeploy或者Paddle支持从内存加载推理模型吗？

### ISSUE THREAD

**Issue by Ruanlt** [PaddlePaddle/FastDeploy#1536]

**Comment by jiangjiajun** [comment]
现在仅当使用Runtime时，提供了RuntimeOption.SetModelBuffer接口来支持

**Comment by Ruanlt** [comment]
> 现在仅当使用Runtime时，提供了RuntimeOption.SetModelBuffer接口来支持

这是C++版的接口吗？没找到这个接口信息

**Comment by Ruanlt** [comment]
> 现在仅当使用Runtime时，提供了RuntimeOption.SetModelBuffer接口来支持

这是C++版的接口吗？没找到这个接口信息
