### ISSUE TITLE
Serving 部署 PPHGNet 报错

### ISSUE THREAD

**Issue by laugh12321** [PaddlePaddle/FastDeploy#1537]
## 环境

- 【FastDeploy版本】： docker 1.0.4-gpu-cuda11.4-trt8.5-21.10、1.0.2-gpu-cuda11.4-trt8.4-21.10
- 【硬件】： Nvidia GPU 3060TI
- 【编译语言】： C++ / Python

## 问题日志及出现问题的操作流程
- 直接复制[models](https://github.com/PaddlePaddle/FastDeploy/tree/develop/examples/vision/classification/paddleclas/serving/models)所有文件，运行报错如下
![image](https://user-images.githubusercontent.com/38065710/223348190-4c96bc94-314e-4660-a0da-66a1f03f6d42.png)
- 将`models/runtime/config.pbtxt`中
```
# Input configuration of the model
input [
  {
    # input name
    name: "inputs"
    # input type such as TYPE_FP32、TYPE_UINT8、TYPE_INT8、TYPE_INT16、TYPE_INT32、TYPE_INT64、TYPE_FP16、TYPE_STRING
    data_type: TYPE_FP32
    # input shape， The batch dimension is omitted and the actual shape is [batch, c, h, w]
    dims: [ 3, 224, 224 ]
  }
]
```
改为
```
# Input configuration of the model
input [
  {
    # input name
    name: "x"
    # input type such as TYPE_FP32、TYPE_UINT8、TYPE_INT8、TYPE_INT16、TYPE_INT32、TYPE_INT64、TYPE_FP16、TYPE_STRING
    data_type: TYPE_FP32
    # input shape， The batch dimension is omitted and the actual shape is [batch, c, h, w]
    dims: [ 3, 224, 224 ]
  }
]
```
报错如下：
![image](https://user-images.githubusercontent.com/38065710/223348714-3276f2dc-1d47-46ce-bb7b-6e571802a4a9.png)
- 将`models/runtime/config.pbtxt`中
```
# The output of the model is configured in the same format as the input
output [
  {
    name: "save_infer_model/scale_0.tmp_1"
    data_type: TYPE_FP32
    dims: [ 1000 ]
  }
]
```
改为
```
# The output of the model is configured in the same format as the input
output [
  {
    name: "softmax_1.tmp_0"
    data_type: TYPE_FP32
    dims: [ 1000 ]
  }
]
```
报错如下：
![image](https://user-images.githubusercontent.com/38065710/223349199-3bf1e5e0-acdf-4eac-81e5-39d80127010b.png)

**Comment by heliqi** [comment]
@laugh12321 你最后修改models/runtime/config.pbtxt 中output的name后，有改pipeline中的name吗？

比如 ppcls还需要改这个config: https://github.com/PaddlePaddle/FastDeploy/blob/0687d3b0ad7bde71b8a9d7e083506195735a5917/examples/vision/classification/paddleclas/serving/models/paddlecls/config.pbtxt#L40

**Comment by laugh12321** [comment]
好的谢谢，可能是这个问题

**Comment by chengshaoxi0** [comment]
> 好的谢谢，可能是这个问题

请问你解决了吗，可否分享下最后配置好的config文件
