### ISSUE TITLE
cuda_runtime_api.h file not found error

### ISSUE THREAD

**Issue by UygarUsta99** [PaddlePaddle/FastDeploy#1539]
## Environment

FastDeploy version: 1.0
OS Platform:  Windows x64 
Hardware: e.g. Nvidia GPU 2080Ti  CUDA 11.6 CUDNN 8.3
Program Language: C++

## Problem description
When trying to include "fastdeploy/vision.h" I receive 'cuda_runtime_api.h' file not found error.I have checked and there is cuda_runtime_api.h in my cuda/include folder.I have also added cuda/include to system variables path.

Thank you for your time.

**Comment by UygarUsta99** [comment]
Setting cuda directory in cmake solved it.

**Comment by yywangfei** [comment]
i have the same question, how can i set cuda in camke?
my cmake setting as fllows: 
cmake .. -DENABLE_ORT_BACKEND=ON \
         -DENABLE_PADDLE_BACKEND=ON \
         -DENABLE_OPENVINO_BACKEND=ON \
         -DWITH_GPU=ON \
         -DCUDA_DIRECTORY=/usr/local/cuda \
         -DCMAKE_INSTALL_PREFIX=${PWD}/compiled_fastdeploy_sdk \
         -DENABLE_VISION=ON \
         -DOPENCV_DIRECTORY=/usr/local/lib/ \
         -DENABLE_TEXT=ON \

**Comment by UygarUsta99** [comment]
> i have the same question, how can i set cuda in camke? my cmake setting as fllows: cmake .. -DENABLE_ORT_BACKEND=ON -DENABLE_PADDLE_BACKEND=ON -DENABLE_OPENVINO_BACKEND=ON -DWITH_GPU=ON -DCUDA_DIRECTORY=/usr/local/cuda -DCMAKE_INSTALL_PREFIX=${PWD}/compiled_fastdeploy_sdk -DENABLE_VISION=ON -DOPENCV_DIRECTORY=/usr/local/lib/ -DENABLE_TEXT=ON \

try this:
set(CUDA_DIRECTORY "C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v11.6")
