### ISSUE TITLE
PaddleX导出的模型,怎么办

### ISSUE THREAD

**Issue by monkeycc** [PaddlePaddle/FastDeploy#154]
PaddleX导出的模型,怎么办

配置文件 只有
model.yml
pipeline.yml

**Comment by jiangjiajun** [comment]
你平时使用PaddleX的哪些模型呢

**Comment by monkeycc** [comment]
都有 4大模型 都有用

分类 目标 语义 实例

因为paddleX是通用的  比较好用

希望能增加paddleX模型的预测

主要是方便打包部署

这样就不需要打包整个paddle和paddleX
很麻烦

**Comment by jiangjiajun** [comment]
你在使用的是PaddleX哪个版本呢（客户端还是PaddleX Python API， 版本号）

**Comment by monkeycc** [comment]
客户端训练

部署是PaddleX Python API

版本最新  2.1.0

python打包多费劲

paddle + paddleX 都要打包进去
各种报错
而且我只需要预测而已

如果FastDeploy能实现paddleX模型预测
那么部署打包 
只需要部署FastDeploy就行了
这样就方便多了
