### ISSUE TITLE
rk3588 推理 picodet模型出错 生成的图片中无框

### ISSUE THREAD

**Issue by vamoslc** [PaddlePaddle/FastDeploy#1540]
*********************************************
温馨提示：根据社区不完全统计，按照模板提问，可以加快回复和解决问题的速度
*********************************************

## 环境

- 【FastDeploy版本】： git clone [https://github.com/PaddlePaddle/FastDeploy.git最新](https://github.com/PaddlePaddle/FastDeploy.git%E6%9C%80%E6%96%B0)
- 【编译命令】如果您是自行编译的FastDeploy，请说明您的编译方式（参数命令）
- 【系统平台】:  debian
- 【硬件】： rk3588
- 【编译语言】： Python(3.9）

## 问题日志及出现问题的操作流程
- 附上详细的问题日志有助于快速定位分析
- 【模型跑不通】
- - 按照教程下载的picodet模型 在pc端导出生成rknn之后放在板子上推理出错 错误信息为
- root@linaro-alip:/home/linaro/LC/FastDeploy/examples/vision/detection/paddledetection/rknpu2/python# python3 infer.py --modefile picodet_s_416_coco_lcnet/picodet_s_416_coco_lcnet_rk3588_unquantized.rknn --config_file picodet_s_416_coco_lcnet/infer_g.yml --image picodet_s_416_coco_lcnet/11479-0000364_01177_d_0000799_320_0_960_540.jpg
[INFO] fastdeploy/vision/common/processors/transform.cc(45)::FuseNormalizeCast  Normalize and Cast are fused to Normalize inreprocessing pipeline.
[INFO] fastdeploy/vision/common/processors/transform.cc(93)::FuseNormalizeHWC2CHW       Normalize and HWC2CHW are fused to NmalizeAndPermute  in preprocessing pipeline.
[INFO] fastdeploy/vision/common/processors/transform.cc(159)::FuseNormalizeColorConvert BGR2RGB and NormalizeAndPermute are sed to NormalizeAndPermute with swap_rb=1
[INFO] fastdeploy/runtime/backends/rknpu2/rknpu2_backend.cc(57)::GetSDKAndDeviceVersion rknn_api/rknnrt version: 1.4.2b0 (c59ccf9@2023-02-14T17:55:39), driver version: 0.8.0
index=0, name=image, n_dims=4, dims=[1, 416, 416, 3], n_elems=519168, size=1038336, fmt=NHWC, type=FP16, qnt_type=AFFINE, zp, scale=1.000000, pass_through=0
index=0, name=p2o.Mul.79, n_dims=4, dims=[1, 96, 52, 52], n_elems=259584, size=519168, fmt=NCHW, type=FP16, qnt_type=AFFINE,p=0, scale=1.000000, pass_through=0
index=1, name=p2o.Concat.9, n_dims=4, dims=[1, 80, 3598, 1], n_elems=287840, size=575680, fmt=NCHW, type=FP16, qnt_type=AFFI, zp=0, scale=1.000000, pass_through=0
[INFO] fastdeploy/runtime/runtime.cc(334)::CreateRKNPU2Backend  Runtime initialized with Backend::RKNPU2 in Device::RKNPU.
[WARNING] fastdeploy/runtime/backends/rknpu2/rknpu2_backend.cc(326)::Infer      The input tensor type != model's inputs typehe input_type need FP16,but inputs[0].type is UINT8
[ERROR] fastdeploy/vision/detection/ppdet/ppdet_decode.cc(115)::DecodeAndNMS    The shape of boxes and scores should be [bat, boxes_num, 4], [batch, classes_num, boxes_num]
DetectionResult: [xmin, ymin, xmax, ymax, score, label_id]

Visualized result save in ./visualized_result.jpg

在生成的visualized_result.jpg中没有框显示。

**Comment by Zheng-Bicheng** [comment]
我这边复现不出来你的问题，你用c++ 文档里已经转好的模型试下。

**Comment by Zheng-Bicheng** [comment]
```bash
wget https://bj.bcebos.com/paddlehub/fastdeploy/rknpu2/picodet_s_416_coco_lcnet.zip
unzip picodet_s_416_coco_lcnet.zip
```

**Comment by Zheng-Bicheng** [comment]
能解决吗？

**Comment by vamoslc** [comment]
你好 已经解决了 非常感谢！
