### ISSUE TITLE
在飞腾平台下编译xpu版报错不通过

### ISSUE THREAD

**Issue by oushilu** [PaddlePaddle/FastDeploy#1545]
## 环境

- 【FastDeploy版本】： develop版本
- 【编译命令】cmake -DWITH_KUNLUNXIN=ON -DWITH_GPU=OFF -DENABLE_ORT_BACKEND=ON -DENABLE_VISION=ON -DENABLE_TEXT=ON- -DCMAKE_INSTALL_PREFIX=fastdeploy-kunlunxin -DENABLE_VISION=ON ..

- 【系统平台】: 银河麒麟v10 Linux localhost.localdomain 4.19.90-25.2.v2101.gfb01.ky10.aarch64
- 【硬件】： 飞腾2000+CPU  昆仑k200xpu
- 【编译语言】： C++  && Python3.7

## 问题日志及出现问题的操作流程
在上述环境下进行依靠Paddlelite后端的FastDeploy编译时出现报错：
[root@localhost build]# cmake -DWITH_KUNLUNXIN=ON -DWITH_GPU=OFF -DENABLE_ORT_BACKEND=ON -DENABLE_VISION=ON -DENABLE_TEXT=ON- -DCMAKE_INSTALL_PREFIX=fastdeploy-kunlunxin -DENABLE_VISION=ON ..
Decompress file /root/fast/FastDeploy/build/patchelf-0.15.0-aarch64.tar.gz ...
CMake Error at cmake/kunlunxin.cmake:7 (message):
  KunlunXin XPU is only supported on Linux x64 platform
Call Stack (most recent call first):
  CMakeLists.txt:132 (include)

-- Configuring incomplete, errors occurred!
See also "/root/fast/FastDeploy/build/CMakeFiles/CMakeOutput.log".

**Comment by yeliang2258** [comment]
可以试试这个PR是否可以编译并运行：https://github.com/PaddlePaddle/FastDeploy/pull/1701
