### ISSUE TITLE
对于有多个box的图片，grpclient每次只能获取检测模型的一个box，而且返回的唯一的box的logits是完全正确的

### ISSUE THREAD

**Issue by aixuedegege** [PaddlePaddle/FastDeploy#1557]
*********************************************
温馨提示：根据社区不完全统计，按照模板提问，可以加快回复和解决问题的速度
*********************************************

## 环境

- 【FastDeploy版本】： 使用docker构建，镜像是：registry.baidubce.com/paddlepaddle/fastdeploy:1.0.2-gpu-cuda11.4-trt8.4-21.10
- 【编译命令】如果您是自行编译的FastDeploy，请说明您的编译方式（参数命令）
- 【系统平台】: (gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
- 【硬件】： 说明具体硬件型号，如 Nvidia GPU 3090TI
- 【编译语言】： 

## 问题日志及出现问题的操作流程
- 附上详细的问题日志有助于快速定位分析
- 【模型跑不通】
- - 使用paddleDetection的ppyoloe_plus_crn_l_80e_coco.yml 训练一个检测模型
- - 通过官方脚本export成 ".pdiparams"、"pdmodel"两个推理用文件
- -  使用paddleDetection的 deploy/python/infer.py中的Detector类加载检测模型，推理正常
- -  使用fastdeploy部署service，配置文件如下：
>input [
  {
    name: "image"
    data_type: TYPE_FP32]
    dims: [ 3, 640, 640 ]
  },
  {
    name: "scale_factor"
    data_type: TYPE_FP32
    dims: [ 2 ]
  }
]
output [
  {
    name: "multiclass_nms3_0.tmp_0"
    data_type: TYPE_FP32
    dims: [ -1, 6 ]
  },
  {
    name: "multiclass_nms3_0.tmp_2"
    data_type: TYPE_INT32
    dims: [-1, 2 ]
  }

]

通过grpcclient能够正常调用模型，调用代码：
```python
            inputs = []
            infer_input0 = grpcclient.InferInput('image', model_inputs['image'].shape, 'FP32')
            infer_input0.set_data_from_numpy(model_inputs['image'])  # 载入输入数据
            infer_input1 = grpcclient.InferInput('scale_factor', model_inputs['scale_factor'].shape, 'FP32')
            infer_input1.set_data_from_numpy(model_inputs['scale_factor'])
            inputs.append(infer_input0)
            inputs.append(infer_input1)

            outputs = []
            infer_output0 = grpcclient.InferRequestedOutput('multiclass_nms3_0.tmp_0')
            infer_output1 = grpcclient.InferRequestedOutput('multiclass_nms3_0.tmp_2')
            outputs.append(infer_output0)
            outputs.append(infer_output1)```

但是有一个问题，用grpc获取的图片无论配置文件的output的维度怎么设置，始终返回维度为[1,6]和[1]的两个输出，但是正常用Detector类预测，同一张图片，Detector会给出[64,6]维度的box结果和box个数[64]。换图片Detector都能给出正确的所有box（box数量大于1），而grpc客户端每次都只返回一个box，并且这个box的logits与Detector类返回的第一个box完全一致，两者只有box数量不同区别。

请问如何解决？

**Comment by aixuedegege** [comment]
multiclass_nms3_0.tmp_0的dims改为[6]，[-1,-1, 6]等等，都存在这个问题。

**Comment by aixuedegege** [comment]
如果送进去两个图片 返回维度为[2,6]

**Comment by rainyfly** [comment]
Hi, 能不能提供以下你完整的pbtxt的配置内容，我这边使用FastDeploy里的ppyoloe的示例，发现multiclass_nms3_0.tmp_0的shape是正常的，比如[300, 6]

**Comment by aixuedegege** [comment]
好的 
[config.txt](https://github.com/PaddlePaddle/FastDeploy/files/10928649/config.txt)

**Comment by rainyfly** [comment]
grpc client的程序也请发给我看一下

**Comment by aixuedegege** [comment]
好的，基本上把paddlleDetector的Detector抄过来的，主要从285行开始
[stamp_det_grpc.txt](https://github.com/PaddlePaddle/FastDeploy/files/10928786/stamp_det_grpc.txt)

**Comment by rainyfly** [comment]
感觉应该没写错config才是，如果把config改成下面这样呢：
```text
name: "STAMP_DET"
backend: "fastdeploy"

# Input configuration of the model
input [
  {
    # input name
    name: "image"
    # input type such as TYPE_FP32、TYPE_UINT8、TYPE_INT8、TYPE_INT16、TYPE_INT32、TYPE_INT64、TYPE_FP16、TYPE_STRING
    data_type: TYPE_FP32
    # input shape， The batch dimension is omitted and the actual shape is [batch, c, h, w]
    dims: [-1, 3, 640, 640 ]
  },
  {
    name: "scale_factor"
    data_type: TYPE_FP32
    dims: [-1, 2 ]
  }
]

# The output of the model is configured in the same format as the input
output [
  {
    name: "multiclass_nms3_0.tmp_0"
    data_type: TYPE_FP32
    dims: [-1, -1, 6 ]
  },
  {
    name: "multiclass_nms3_0.tmp_2"
    data_type: TYPE_INT32
    dims: [-1, -1, 2 ]
  }

]

# Number of instances of the model
instance_group [
  {
    # The number of instances is 1
    count: 1
    # Use GPU, CPU inference option is:KIND_CPU
    kind: KIND_GPU
    # The instance is deployed on the 0th GPU card
    gpus: [0]
  }
]

optimization {
  execution_accelerators {
    # GPU推理配置， 配合KIND_GPU使用
    gpu_execution_accelerator : [
      {
        name : "paddle"
        # 设置推理并行计算线程数为1
        parameters { key: "cpu_threads" value: "24" }
        # 开启mkldnn加速，设置为0关闭mkldnn
        parameters { key: "use_mkldnn" value: "1" }
      }
    ]
  }
}

```

**Comment by rainyfly** [comment]
更改config后使用fastdeployserver重新载入试试

**Comment by aixuedegege** [comment]
可以了 非常感谢，请问这个是什么原因导致的？不是batch_size可以不用写的么？

**Comment by rainyfly** [comment]
理论上设置了max_batch_size字段，会自动在前面帮忙加上一个batch的维度，不清楚你之前的配置是不是因为输入输出没有完全保持一致导致的，你自己再看看。我给你的那个把max_batch_size字段删掉了，完全自己控制shape

**Comment by aixuedegege** [comment]
好的 明白了，多谢啦。奖励一个鸡腿

**Comment by impl1874** [comment]
> 理论上设置了max_batch_size字段，会自动在前面帮忙加上一个batch的维度，不清楚你之前的配置是不是因为输入输出没有完全保持一致导致的，你自己再看看。我给你的那个把max_batch_size字段删掉了，完全自己控制shape

去掉max_batch_size解决了，否则总是会出现不一致的情况。
