### ISSUE TITLE
paddleocr3在rk3588 npu上推理时间和cpu推理时间无明显提升

### ISSUE THREAD

**Issue by leokwu** [PaddlePaddle/FastDeploy#1565]
rk3588 cpu推理：
![58d7c6de5bec6a5e138ef22561bb9c1](https://user-images.githubusercontent.com/26742943/223942402-fea1f242-d72e-4535-9589-4307cf8ae4c1.png)
rk3588 npu推理：
![908e390d9a08946c6bca0e37d8f734a](https://user-images.githubusercontent.com/26742943/223942481-7a036170-e8c4-42a1-b593-d49e1aee8805.png)

图像输入是640x640；

**Comment by leokwu** [comment]
送推理前会resize到640x640；
原始图片如下：
<img width="960" alt="6e2ce8d52ed9c1327907932711bd45c" src="https://user-images.githubusercontent.com/26742943/223943957-15be6562-e14f-4aba-a3a6-29c3811c4aa0.png">

**Comment by Zheng-Bicheng** [comment]
这个已经在和RK那边做优化了哈！

**Comment by zhouweic36** [comment]
怎么开启RK3588多核心NPU运行单一模型呢

**Comment by zhouweic36** [comment]
ubuntu 交叉编译 Fastdeploy 编译选项中  ENABLE_RKNPU2_BACKEND 开启   得到库    可以在RK3588 NPU上跑通，运行测试图，时间与官方差不多，那么怎么开启RK3588多核心NPU运行单一模型呢？但是我还想在CPU上跑，ubuntu 交叉编译 Fastdeploy  编译选项中 把ENABLE_ORT_BACKEND开启，他们自动下载linux X64的ONNX Runtime，因格式不符合导致链接失败？为了解决这个问题，这是先要交叉编译ONNX Runtime吗？
