### ISSUE TITLE
在RK3588上跑paddledetection/rknpu2示例报错反馈

### ISSUE THREAD

**Issue by eyu11** [PaddlePaddle/FastDeploy#1568]
在RK3588上跑paddledetection/rknpu2示例 ，会报fastdeploy.libs.fastdeploy_main.vision.detection.P' object has no attribute 'apply_decode_and_nms'，这个是啥情况？没编译好？（操作系统 kylin）
![image](https://user-images.githubusercontent.com/61813449/223953838-7ebbf036-eb72-4e6d-97c7-93075046d7a5.png)

**Comment by wjj19950828** [comment]
@eyu11 目前ApplyDecodeAndNMS已经全部换成ApplyNMS

**Comment by Zheng-Bicheng** [comment]
需要用apply_nms()

**Comment by eyu11** [comment]
收到，谢谢~~




饿鱼
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/FastDeploy"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月9日(星期四) 下午4:07
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/FastDeploy] 在RK3588上跑paddledetection/rknpu2示例报错反馈 (Issue #1568)





 
@eyu11 目前ApplyDecodeAndNMS已经全部换成ApplyNMS
