### ISSUE TITLE
segmentation中的infer错误

### ISSUE THREAD

**Issue by qiyuezhiguang** [PaddlePaddle/FastDeploy#1571]
*********************************************
温馨提示：根据社区不完全统计，按照模板提问，可以加快回复和解决问题的速度
*********************************************

## 环境

- 【FastDeploy版本】： 说明具体的版本，最新的预编译包
- 【编译命令】如果您是自行编译的FastDeploy，请说明您的编译方式（参数命令）
- 【系统平台】: Linux x64(Ubuntu 18.04) 
- 【硬件】： 说明具体硬件型号，如 Nvidia GPU 2080TI， CUDA 11.2 CUDNN 8.4
- 【编译语言】： Python 3.8

## 问题日志及出现问题的操作流程
- 附上详细的问题日志有助于快速定位分析
- 【模型跑不通】
- - 先执行`examples`下的部署示例，包括使用examples提供的模型，确认是否可以正确执行
- - 如若`examples`下的代码可以运行，但自己的模型，或自己的代码不能运行
- - - 提供复现问题的 代码+模型+错误log，供工程师快速定位问题
执行examples下的infer代码，具体位置为segmentation下的cpu-gpu----python------infer.py
由于使用的tensorrt原始后端，因此将部分代码修改如下：

    if args.use_trt:
        option.use_trt_backend()
        # If use original Tensorrt, not Paddle-TensorRT,
        # comment the following two lines
        # option.enable_paddle_to_trt()
        # option.enable_paddle_trt_collect_shape()
        # option.set_trt_input_shape("x", [1, 3, 256, 256], [1, 3, 1024, 1024],
        #                            [1, 3, 2048, 2048])
        option.set_trt_input_shape(tensor_name="image", min_shape=[1, 3, 512, 512], opt_shape=[1, 3, 512, 512],
                                   max_shape=[1, 3, 512, 512])
        # option.set_trt_input_shape(tensor_name="scale_factor", min_shape=[1, 2], opt_shape=[1, 2], max_shape=[1, 2])
        option.set_trt_cache_file(os.path.join(args.model, "model.trt"))

运行错误提示：
[INFO] fastdeploy/runtime.cc(585)::Init Runtime initialized with Backend::TRT in Device::GPU.
[ERROR] fastdeploy/backends/tensorrt/trt_backend.cc(238)::log   3: [executionContext.cpp::setBindingDimensions::944] Error Code 3: API Usage Error (Parameter check failed at: runtime/api/executionContext.cpp::setBindingDimensions::944, condition: profileMinDims.d[i] <= dimensions.d[i]. Supplied binding dimension [1,3,512,512] for bindings[0] exceed min ~ max range at index 2, maximum dimension in profile is 1024, minimum dimension in profile is 1024, but supplied dimension is 512.
)
[ERROR] fastdeploy/backends/tensorrt/trt_backend.cc(345)::Infer [ERROR] Error occurs while copy memory from GPU to CPU.
但能够正常输出结果：

但如果将上述代码修改为：

    if args.use_trt:
…………
        option.set_trt_input_shape(tensor_name="image", min_shape=[1, 3, 256, 256], opt_shape=[1, 3, 1024, 1024],
                                   max_shape=[1, 3, 2048, 2048])
……
则会报错，且不输出结果

由于deploy.yaml文件中没有图像尺寸大小：
Deploy:
  model: model.pdmodel
  params: model.pdiparams
  transforms:
  - type: Normalize

所以这种情况该如何设置？

模型下载地址：
链接: https://pan.baidu.com/s/19YfrbrO5CIWTCd5NzeFV_Q  密码: e8ps

**Comment by qiyuezhiguang** [comment]
使用visualdl查看网络结果，发现输入的尺寸为1024*1024，因此将deploy内容修改如下：
Deploy:
#  model: model.pdmodel
#  params: model.pdiparams
#  transforms:
#  - type: Normalize
#  input_shape:
#  - -1
#  - 3
#  - -1
#  - -1
  model: model.pdmodel
  output_dtype: float32
  output_op: none
  params: model.pdiparams
  transforms:
  - interp: 2
    keep_ratio: false
    target_size:
      - 1024
      - 1024
    type: Resize
  - type: Normalize
即增加了resize内容，代码可以正常运行。

还有一点不明白的是：在visualdl中输入的名字为“x”，但使用tensor_name="x"则报错，需要修改为：option.set_trt_input_shape(tensor_name="image", min_shape=[1, 3, 256, 256], opt_shape=[1, 3, 1024, 1024],
max_shape=[1, 3, 2048, 2048])，请问这种情况下，怎么能自行查看tensor_name呢？

**Comment by jiangjiajun** [comment]
如果名字是"x"，而你设置的是"image",这行代码虽然设置了Shape，但其实没生效（即是否有添加`option.set_trt_input_shape(tensor_name="image", min_shape=[1, 3, 256, 256], opt_shape=[1, 3, 1024, 1024],
max_shape=[1, 3, 2048, 2048]`)这行代码没有影响）

现在这里的模型问题是模型的Shape已经是固定了，此时已经无需再自行设置trt shape了，反而设置了提示出错
