### ISSUE TITLE
编译C#api过程报错

### ISSUE THREAD

**Issue by zhinangubei** [PaddlePaddle/FastDeploy#1572]
*********************************************
温馨提示：根据社区不完全统计，按照模板提问，可以加快回复和解决问题的速度
*********************************************

## 环境

cudn11.2,cudnn8.4,windows10, c++,cmake gui 编译，vs2019生成了fastdeploy.dll,未生成fastdeploy csharp.dll, 成功生成13，失败1，但没报错

**Comment by rainyfly** [comment]
请问有没有报错信息呢，WITH_CSHARPAPI开启了么，请给我看一下报错信息以便查看原因

**Comment by zhinangubei** [comment]
> 请问有没有报错信息呢，WITH_CSHARPAPI开启了么，请给我看一下报错信息以便查看原因

已经解决了，编译好了，谢谢
