### ISSUE TITLE
rv1126,rk3568,rk3588 等用例子都需要修改异构文件subgraph.txt

### ISSUE THREAD

**Issue by liruiyan** [PaddlePaddle/FastDeploy#1582]
rv1126,rk3568,rk3588 等用例子都需要修改异构文件subgraph.txt但是对于小白来说这个很难快速验证请增加一些快速验证例如人脸识别这种不需要修改异构文件的例子

**Comment by yeliang2258** [comment]
在RV1126上，分类的模型是不需要异构文件的，可以尝试运行一下

**Comment by Zheng-Bicheng** [comment]
rk3568,rk3588没有异构文件哦
