### ISSUE TITLE
基于飞腾S2500/64，昆仑xpuR200编译报错

### ISSUE THREAD

**Issue by HustleOoo** [PaddlePaddle/FastDeploy#1588]
根据官方示例(https://github.com/PaddlePaddle/FastDeploy/tree/develop/docs/cn/build_and_install)/kunlunxin.md执行报错如下：

Will force to set ENABLE_LITE_BACKEND when build with KunlunXin.
CMake Error at cmake/kunlunxin.cmake:7 (message):
  KunlunXin XPU is only supported on Linux x64 platform
Call Stack (most recent call first):
  CMakeLists.txt:132 (include)

显示fastdeploy只支持x64架构，想确定一下fastdeploy是不是不支持arm架构呢？

**Comment by DefTruth** [comment]
FastDeploy支持arm架构，但是目前只在linux x64 cpu + xpu下进行了适配和测试，请问您是想在 Linux arm64 cpu + xpu下使用FastDeploy是吗？

**Comment by HustleOoo** [comment]
> FastDeploy支持arm架构，但是目前只在linux x64 cpu + xpu下进行了适配和测试，请问您是想在 Linux arm64 cpu + xpu下使用FastDeploy是吗？

是的，目前是想基于飞腾S2500/64，昆仑xpuR200环境下使用

**Comment by jiangjiajun** [comment]
目前提供了昆仑+x64 CPU的编译支持。 飞腾arm cpu + 昆仑的编译正在支持中

**Comment by HustleOoo** [comment]
> 目前提供了昆仑+x64 CPU的编译支持。 飞腾arm cpu + 昆仑的编译正在支持中

好的，明白了

**Comment by 108851027** [comment]
**_以下编译方案在FT2000+/64服务器上测试通过，供大家参考：_**

## 环境信息

|      | 内容         |
|------|------------|
| CPU  | FT2000+/64 |
| 操作系统 | 麒麟V10      |
|cmake | \>=3.10    |
|gcc | 7.3.0      |
| g++ | 7.3.0      |
| 加速卡 | 昆仑芯R200    |


## 编译过程

1. 编译paddle_lite

    ```shell
    git clone https://github.com/PaddlePaddle/Paddle-Lite.git
    git checkout release/v2.13
    cd Paddle-Lite
    export CC=/usr/bin/gcc
    export CXX=/usr/bin/g++
    ./lite/tools/build_linux.sh --arch=armv8 --with_kunlunxin_xpu=ON
    ```
    编译完成后，在下面的文件夹下会看到头文件和库文件
    ```text
    build.lite.linux.armv8.gcc.kunlunxin_xpu/inference_lite_lib.armlinux.armv8.xpu/cxx
    ```
    文件结构如下所示：
    ```text
    .
    ├── include
    │   ├── paddle_api.h
    │   ├── paddle_image_preprocess.h
    │   ├── paddle_lite_factory_helper.h
    │   ├── paddle_place.h
    │   ├── paddle_use_kernels.h
    │   ├── paddle_use_ops.h
    │   └── paddle_use_passes.h
    └── lib
        ├── libpaddle_api_full_bundled.a
        ├── libpaddle_api_light_bundled.a
        ├── libpaddle_full_api_shared.so
        └── libpaddle_light_api_shared.so
    ```

2. 制作paddlelite预编译包，也就是一个压缩包

    ```text
    mkdir ~/prebuild/paddlelite
    cd build.lite.linux.armv8.gcc.kunlunxin_xpu/inference_lite_lib.armlinux.armv8.xpu/cxx
    cp -r lib/ include/ ~/prebuild/paddlelite
    cd ~/prebuild/paddlelite
    tar -czvf paddlelite.tgz paddlelite
    ```
    压缩包里的资源如下所示：
    
    ```text
    paddlelite/
    paddlelite/lib/
    paddlelite/lib/libpaddle_api_full_bundled.a
    paddlelite/lib/libpaddle_api_light_bundled.a
    paddlelite/lib/libpaddle_light_api_shared.so
    paddlelite/lib/libpaddle_full_api_shared.so
    paddlelite/include/
    paddlelite/include/paddle_api.h
    paddlelite/include/paddle_lite_factory_helper.h
    paddlelite/include/paddle_place.h
    paddlelite/include/paddle_use_passes.h
    paddlelite/include/paddle_use_kernels.h
    paddlelite/include/paddle_use_ops.h
    paddlelite/include/paddle_image_preprocess.h
    ```
3. 编译FastDeploy
   1. 下载FastDeploy
    ```
   git clone https://github.com/PaddlePaddle/FastDeploy.git
   ```
   2. 修改cmake/kunlunxin.cmake ，内容如下
   ```text
    if(NOT ENABLE_LITE_BACKEND)
    message("Will force to set ENABLE_LITE_BACKEND when build with KunlunXin.")
    set(ENABLE_LITE_BACKEND ON)
    endif()
    ```
   3. 编译FastDeploy C++ SDK 编译完成后就可以使用了
   ```text
    mkdir build && cd build
    cmake .. -DENABLE_LITE_BACKEND=ON \
    -DWITH_KUNLUNXIN=ON  \
    -DENABLE_VISION=ON \
    -DENABLE_TEXT=ON \
    -DPADDLELITE_URL=/your/path/to/prebuild/paddlelite.tgz \
    -DWITH_GPU=OFF  \
    -DCMAKE_INSTALL_PREFIX=${PWD}/fastdeploy-kunlunxin
    ```

**Comment by HustleOoo** [comment]
> 

大佬，有没有python编译的呢？谢谢

**Comment by HustleOoo** [comment]
> **_以下译例在FT2000+/64服务器上测试通过，供大家参考：_**
> 
> ## 环境信息
> 内容
> 中央处理器	FT2000+/64
> 操作系统	麒麟V10
> 制作	>=3.10
> 海合会	7.3.0
> 克++	7.3.0
> 加速卡	昆仑芯R200
> ## 编辑过程
> 1. 译paddle_lite
>    ```shell
>    git clone https://github.com/PaddlePaddle/Paddle-Lite.git
>    git checkout release/v2.13
>    cd Paddle-Lite
>    export CC=/usr/bin/gcc
>    export CXX=/usr/bin/g++
>    ./lite/tools/build_linux.sh --arch=armv8 --with_kunlunxin_xpu=ON
>    ```
>    
>    
>        
>          
>        
>    
>          
>        
>    
>        
>      
>    编译完成后，在下面的文件夹下会看到头文件和库文件
>    ```
>    build.lite.linux.armv8.gcc.kunlunxin_xpu/inference_lite_lib.armlinux.armv8.xpu/cxx
>    ```
>    
>    
>        
>          
>        
>    
>          
>        
>    
>        
>      
>    文件结构如下所示：
>    ```
>    .
>    ├── include
>    │   ├── paddle_api.h
>    │   ├── paddle_image_preprocess.h
>    │   ├── paddle_lite_factory_helper.h
>    │   ├── paddle_place.h
>    │   ├── paddle_use_kernels.h
>    │   ├── paddle_use_ops.h
>    │   └── paddle_use_passes.h
>    └── lib
>        ├── libpaddle_api_full_bundled.a
>        ├── libpaddle_api_light_bundled.a
>        ├── libpaddle_full_api_shared.so
>        └── libpaddle_light_api_shared.so
>    ```
> 2. 制作paddlelite预编译包，也就是一个压缩包
>    ```
>    mkdir ~/prebuild/paddlelite
>    cd build.lite.linux.armv8.gcc.kunlunxin_xpu/inference_lite_lib.armlinux.armv8.xpu/cxx
>    cp -r lib/ include/ ~/prebuild/paddlelite
>    cd ~/prebuild/paddlelite
>    tar -czvf paddlelite.tgz paddlelite
>    ```
>    
>    
>        
>          
>        
>    
>          
>        
>    
>        
>      
>    压缩包里的资源如下所示：
>    ```
>    paddlelite/
>    paddlelite/lib/
>    paddlelite/lib/libpaddle_api_full_bundled.a
>    paddlelite/lib/libpaddle_api_light_bundled.a
>    paddlelite/lib/libpaddle_light_api_shared.so
>    paddlelite/lib/libpaddle_full_api_shared.so
>    paddlelite/include/
>    paddlelite/include/paddle_api.h
>    paddlelite/include/paddle_lite_factory_helper.h
>    paddlelite/include/paddle_place.h
>    paddlelite/include/paddle_use_passes.h
>    paddlelite/include/paddle_use_kernels.h
>    paddlelite/include/paddle_use_ops.h
>    paddlelite/include/paddle_image_preprocess.h
>    ```
> 3. 译FastDeploy
>    
>    1. 下载快速部署
>    
>    ```
>    git clone https://github.com/PaddlePaddle/FastDeploy.git
>    ```
>    
>    
>        
>          
>        
>    
>          
>        
>    
>        
>      
>    
>    2. 修改cmake/kunlunxin.cmake ，内容如下
>    
>    ```
>     if(NOT ENABLE_LITE_BACKEND)
>     message("Will force to set ENABLE_LITE_BACKEND when build with KunlunXin.")
>     set(ENABLE_LITE_BACKEND ON)
>     endif()
>    ```
>    
>    
>        
>          
>        
>    
>          
>        
>    
>        
>      
>    
>    3. 编译FastDeploy C++ SDK 编译完成后就可以使用了
>    
>    ```
>     mkdir build && cd build
>     cmake .. -DENABLE_LITE_BACKEND=ON \
>     -DWITH_KUNLUNXIN=ON  \
>     -DENABLE_VISION=ON \
>     -DENABLE_TEXT=ON \
>     -DPADDLELITE_URL=/your/path/to/prebuild/paddlelite.tgz \
>     -DWITH_GPU=OFF  \
>     -DCMAKE_INSTALL_PREFIX=${PWD}/fastdeploy-kunlunxin
>    ```

大佬，有没有python编译版本的呢？谢谢
