### ISSUE TITLE
RK3588使用提供的rknn模型运行infer.py报错segmentation fault

### ISSUE THREAD

**Issue by Shifiter** [PaddlePaddle/FastDeploy#1591]
*********************************************
温馨提示：根据社区不完全统计，按照模板提问，可以加快回复和解决问题的速度
*********************************************

## 环境

- 【FastDeploy版本】： 2023年3月13日最新git https://github.com/PaddlePaddle/FastDeploy.git
- 【编译命令】官方提供“编译FastDeploy Python SDK”方法
- 【系统平台】: debian11.6
- 【硬件】： rk3588 4G+8G
- 【编译语言】： Python3.9

## 问题日志及出现问题的操作流程
- 附上详细的问题日志有助于快速定位分析
- 【模型跑不通】
- - RK3588 debian 4G+8G 
先安装了python SDK，再安装了板端推理rknpu2_install_rk3588.sh
下载fast deploy提供的yolov5s_relu_tk2_RK3588_i8.rknn
运行/example/vision/detection/rkyolo/python中的infer.py，命令python3 infer.py --model_file ./model/ --image 6770.jpg
显示信息Segmentation fault，无其他任何提示信息

**Comment by Zheng-Bicheng** [comment]
你随便写个hello world能运行吗？直接显示Segmentation fault感觉上更像是环境的问题

**Comment by Shifiter** [comment]
> 你随便写个hello world能运行吗？直接显示Segmentation fault感觉上更像是环境的问题

print("hello world")可以运行输出

**Comment by Zheng-Bicheng** [comment]
我晚上回去复现一下看看哈

**Comment by Shifiter** [comment]
> 我晚上回去复现一下看看哈

所有的操作步骤里面只有git checkout develop没有输入

**Comment by Shifiter** [comment]
> 我晚上回去复现一下看看哈

解决了
将python3 infer.py --model_file ./model/ --image 6770.jpg修改为python3 infer.py --model_file ./model/yolov5********.rknn --image 6770.jpg
需要精确到模型文件

**Comment by Zheng-Bicheng** [comment]
好的哟，祝您生活愉快
