### ISSUE TITLE
UIE经过数据蒸馏后的模型，如何使用fastdeploy方式部署

### ISSUE THREAD

**Issue by adatwfx** [PaddlePaddle/FastDeploy#1599]
*********************************************
温馨提示：根据社区不完全统计，按照模板提问，可以加快回复和解决问题的速度
*********************************************

## 环境

- 【FastDeploy版本】： fastdeploy:1.0.4-cpu-only-21.10
- 【系统平台】:  Windows x64(Windows10) 
- 【编译语言】： python3.8
因直接使用UIE模型在CPU上推理较慢，所以按照下面的文档进行了数据蒸馏，推理速度有很大提升。
[UIE数据蒸馏](https://github.com/PaddlePaddle/PaddleNLP/tree/a13e8776d2032f8e1fbac0958a7d2109fe61b10c/applications/information_extraction/text/data_distill)
我的问题是如何把数据蒸馏后的模型通过fastdeploy方式部署？在UIE的fastdeploy部署示例中，都有传递schema参数，而数据蒸馏后的模型不需要传递schema参数

**Comment by zwjwhxz** [comment]
请问这个解决了吗？
