### ISSUE TITLE
我可以在昇腾310上使用fastdeploy 部署uie吗？或者使用lite后端？

### ISSUE THREAD

**Issue by apexg** [PaddlePaddle/FastDeploy#1601]
*********************************************
温馨提示：根据社区不完全统计，按照模板提问，可以加快回复和解决问题的速度
*********************************************

## 环境

- 【FastDeploy版本】： 说明具体的版本，如fastdeploy-linux-gpu-0.8.0
- 【编译命令】如果您是自行编译的FastDeploy，请说明您的编译方式（参数命令）
- 【系统平台】: Linux x64(Ubuntu 18.04) / Windows x64(Windows10) / Mac OSX arm(12.0) / Mac OSX intel(12.0)
- 【硬件】： 昇腾310
- 【编译语言】： C++ / Python(3.7或3.8等）

## 问题日志及出现问题的操作流程
- 附上详细的问题日志有助于快速定位分析
- 【模型跑不通】
- - 先执行`examples`下的部署示例，包括使用examples提供的模型，确认是否可以正确执行
- - 如若`examples`下的代码可以运行，但自己的模型，或自己的代码不能运行
- - - 提供复现问题的 代码+模型+错误log，供工程师快速定位问题
我可以在昇腾310上使用fastdeploy 部署uie吗？或者使用lite后端？

**Comment by jiangjiajun** [comment]
可以

**Comment by apexg** [comment]
具体如何做，给个例子？

**Comment by jccg** [comment]
> 可以

我看FastDeploy文档里面UIE和ERNIE-3.0对Huawei Ascend的支持还都是问号，是已经可以支持了吗？

**Comment by apexg** [comment]
> 具体如何做，给个例子？
我跟上述老哥同样问题，怎么支持的，有操作步骤吗
