### ISSUE TITLE
自己训练的yolov5模型，检测segmentation fault问题

### ISSUE THREAD

**Issue by Shifiter** [PaddlePaddle/FastDeploy#1606]
*********************************************
温馨提示：根据社区不完全统计，按照模板提问，可以加快回复和解决问题的速度
*********************************************

## 环境

- 【FastDeploy版本】： 2023年3月13日最新git https://github.com/PaddlePaddle/FastDeploy.git
- 【编译命令】官方提供“编译FastDeploy Python SDK”方法
- 【系统平台】: debian11.6
- 【硬件】： rk3588 4G+8G
- 【编译语言】： Python3.9

## 问题日志及出现问题的操作流程
- 附上详细的问题日志有助于快速定位分析
- 【模型跑不通】
利用airockship提供的yolov5训练（https://github.com/airockchip/yolov5），利用其中的python export.py --rknpu RK3588转换得到onnx，利用（https://github.com/rockchip-linux/rknn-toolkit2/tree/master/examples/onnx/yolov5）中的test.py将onnx转换为rknn，成功转换且输出了检测结果，运行/example/vision/detection/rkyolo/python中的infer.py，命令python3 infer.py --model_file ./model/best.rknn --image 6770.jpg，输出如下：
[INFO] fastdeploy/runtime/backends/rknpu2/rknpu2_backend.cc(57)::GetSDKAndDeviceVersion	rknn_api/rknnrt version: 1.4.2b0 (c5d79ccf9@2023-02-14T17:55:39), driver version: 0.7.2
index=0, name=images, n_dims=4, dims=[1, 640, 640, 3], n_elems=1228800, size=1228800, fmt=NHWC, type=INT8, qnt_type=AFFINE, zp=-128, scale=0.003922, pass_through=0
index=0, name=output, n_dims=4, dims=[1, 36, 80, 80], n_elems=230400, size=230400, fmt=NCHW, type=INT8, qnt_type=AFFINE, zp=-128, scale=0.003919, pass_through=0
index=1, name=272, n_dims=4, dims=[1, 36, 40, 40], n_elems=57600, size=57600, fmt=NCHW, type=INT8, qnt_type=AFFINE, zp=-128, scale=0.003910, pass_through=0
index=2, name=274, n_dims=4, dims=[1, 36, 20, 20], n_elems=14400, size=14400, fmt=NCHW, type=INT8, qnt_type=AFFINE, zp=-128, scale=0.003921, pass_through=0
[INFO] fastdeploy/runtime/runtime.cc(334)::CreateRKNPU2Backend	Runtime initialized with Backend::RKNPU2 in Device::RKNPU.
[WARNING] fastdeploy/runtime/backends/rknpu2/rknpu2_backend.cc(326)::Infer	The input tensor type != model's inputs type.The input_type need INT8,but inputs[0].type is UINT8
Segmentation fault

**Comment by Zheng-Bicheng** [comment]
看一下这个issues
* https://github.com/PaddlePaddle/FastDeploy/issues/1315

**Comment by Shifiter** [comment]
> 看一下这个issues
> 
> * [RK3568部署自训练YOLO模型中遇到的segmentation fault问题(rkyolo部署)! #1315](https://github.com/PaddlePaddle/FastDeploy/issues/1315)

已解决，添加model.postprocessor.class_num = 7，感谢
