### ISSUE TITLE
c版本的yolov5文档没有编译demo的步骤

### ISSUE THREAD

**Issue by wangxu372848892** [PaddlePaddle/FastDeploy#1609]
https://github.com/PaddlePaddle/FastDeploy/blob/develop/examples/vision/detection/yolov5/c/README_CN.md

**Comment by rainyfly** [comment]
请先参考一下 https://github.com/PaddlePaddle/FastDeploy/blob/develop/examples/vision/detection/paddledetection/c/README_CN.md 其实都是一样的
