### ISSUE TITLE
Meet unsupported output dtype for Cast 

### ISSUE THREAD

**Issue by PinkPanther-ny** [PaddlePaddle/FastDeploy#1618]
I converted pp_lite_seg_stdc1 and pp_lite_seg_stdc2 model to rknn (with target platform set to rk3588s) using rknn-toolkit2 on linux x86_64 PC, the conversion process is fine and the result rknn model can infer without error. But as I transfer the rknn model to rk3588s board, below error occured:
```
--> Load RKNN model
load_rknn done
--> Init runtime environment
I RKNN: [14:47:19.457] RKNN Runtime Information: librknnrt version: 1.4.0 (a10f100eb@2022-09-09T09:07:14)
I RKNN: [14:47:19.457] RKNN Driver Information: version: 0.8.2
I RKNN: [14:47:19.457] RKNN Model Information: version: 1, toolkit version: 1.4.0-22dcfef4(compiler version: 1.4.0 (3b4520e4f@2022-09-05T12:50:09)), target: RKNPU v2, target platform: rk3588, framework name: ONNX, framework layout: NCHW
Init runtime done
--> Running model
E RKNN: [14:47:19.564] Meet unsupported output dtype for all Cast nodes
Aborted (core dumped)
```
1, Tried using both py3.7 and py3.9 rknn_toolkit_lite2 environment
2, Tried to change onnx cast datatype
Error persists.

我在linux x86_64电脑上用rknn-toolkit2把pp_lite_seg_stdc1和pp_lite_seg_stdc2模型转换为rknn（目标平台设置为rk3588s），但当我把rknn模型转移到rk3588s板上时，发生了以下错误。
```
同上
```

1, 尝试了使用py3.7和py3.9 rknn_toolkit_lite2环境
2, 尝试了改变onnx cast节点的数据类型
错误持续存在。

**Comment by Zheng-Bicheng** [comment]
Can you give me the model?

**Comment by Zheng-Bicheng** [comment]
Please update your version of FastDeploy and use the develop branch.

**Comment by jiangq195** [comment]
> Can you give me the model?

I meet same error,can you try my model? And how to give you the model

**Comment by Zheng-Bicheng** [comment]
> > Can you give me the model?
> 
> I meet same error,can you try my model? And how to give you the model

Please propose a new issue with a description of your problem
