### ISSUE TITLE
win 7 下运行fastdeploy的onnx推理缺失api-ms-win-core-libraryloader-l1-2-0.dll

### ISSUE THREAD

**Issue by SchrodingerLLX** [PaddlePaddle/FastDeploy#1620]
【FastDeploy版本】：1.0.3-cpu-only-21.10
【系统平台】: Windows x64(Windows7)
运行vision_detection_paddledetection_infer_ppyoloe.exe会提示缺失api-ms-win-core-libraryloader-l1-2-0.dll。
![CC729867-2488-4f75-9C7E-F45582FE2A40](https://user-images.githubusercontent.com/34128317/225225394-8dfb49ef-58d7-4cc5-b243-f84c1b9283eb.png)。
从网上下载了缺失的依赖库后，最终在加入api-ms-win-core-heap-l2-1-0.dll时提示无法找到入口；测试了多个不同版本的api-ms-win-core-heap-l2-1-0.dll，都报了这个错误，可能是二进制版本不兼容。
![2070730F-D35C-402d-BD13-C97A0DD9EB77](https://user-images.githubusercontent.com/34128317/225226253-9e8c08a1-96b9-4eb1-88d7-8a1fcc0ae98e.png)
请问在win7下如果想要运行onnx runtime推理有什么方法？

**Comment by jiangjiajun** [comment]
Window 7没有支持。需升级到Windows 10
