### ISSUE TITLE
华为昇腾+鲲鹏环境，部署ocr，推理一张发票10几秒太慢了

### ISSUE THREAD

**Issue by apexg** [PaddlePaddle/FastDeploy#1621]
*********************************************
温馨提示：根据社区不完全统计，按照模板提问，可以加快回复和解决问题的速度
*********************************************

## 环境

- 【FastDeploy版本】：如fastdeploy-linux-develop
- 【编译命令】自行编译，按照昇腾手册，构建了docker，然后使用如下命令编译：
-                           export WITH_ASCEND=ON
                            export ENABLE_VISION=ON
                            export ENABLE_PADDLE_BACKEND=OFF
                            export ENABLE_ORT_BACKEND=ON
                            export ENABLE_LITE_BACKEND=ON
                            export ENABLE_TEXT=ON
                            
                            python setup.py build
                            python setup.py bdist_wheel
- 【系统平台】: Linux arch64(Ubuntu 18.04) 
- 【硬件】： 昇腾310
- 【编译语言】： Python3.7

## 问题日志及出现问题的操作流程
- 附上详细的问题日志有助于快速定位分析
- 【模型正常跑，但有性能问题，推理一张发票大概需要10秒以上】
- - 先执行`examples`下的部署示例，FastDeploy/examples/vision/ocr/PP-OCRv2/python/infer_static_shape.py，修改了部分代码：
- 在107行后面增加：目的是检测第二次推理耗时
- 
                                              #预测并打印结果
                                              result = ppocr_v2.predict(im)
                                              
                                              print(result)
                                              
                                              #如下是自己增加的代码：目的是检测第二次推理耗时：
                                              import time
                                              total_time = 0
                                              
                                              _st = time.time()
                                              # 预测图片准备
                                              im = cv2.imread('微信图片_20230314114908.png')
                                              result = ppocr_v2.predict(im)
                                              elapse = time.time() - _st
                                              total_time += elapse
                                              print('总时间：'+str(total_time))
                                              # 可视化结果
                                              vis_im = fd.vision.vis_ppocr(im, result)
                                              cv2.imwrite("visualized_result.jpg", vis_im)
没有使用cls模型，det模型用3.0：
wget https://paddleocr.bj.bcebos.com/PP-OCRv3/chinese/ch_PP-OCRv3_det_infer.tar
tar xvf ch_PP-OCRv3_det_infer.tar
rec模型用server 2.0
如下是调用命令：
python3 infer_static_shape.py --det_model ch_PP-OCRv3_det_infer --cls_model ch_ppocr_mobile_v2.0_cls_infer --rec_model ch_ppocr_server_v2.0_rec_infer --rec_label_file ppocr_keys_v1.txt --image test.png --device ascend

推理图片：
![微信图片_20230314114908](https://user-images.githubusercontent.com/6739219/225229437-d57ee326-14ae-4282-8498-68308932bff1.png)
![test](https://user-images.githubusercontent.com/6739219/225229454-c882085e-abc4-4b17-a61b-c11d80aeafe0.png)
运行日志：
[log.log](https://github.com/PaddlePaddle/FastDeploy/files/10976788/log.log)

**Comment by yunyaoXYY** [comment]
你全部换用v3试试呢， v3的代码，v3的模型。

**Comment by apexg** [comment]
一样慢

**Comment by minboo** [comment]
您好，问题解决了吗，我也是特别慢，日志执行到`[I  3/20  7:24:38.950 ...r/src/driver/huawei_ascend_npu/driver.cc:70 CreateProgram] Create program for huawei_ascend_npu.`的时候要等很长时间。

**Comment by Serenagirl** [comment]
楼主解决了吗？我看没有解决方案就closed了
