### ISSUE TITLE
关于Serving加载openvino IR模型的问题

### ISSUE THREAD

**Issue by flamebox** [PaddlePaddle/FastDeploy#1623]
请问fastdeploy里面的Triton服务器怎么使用量化后的openvino IR格式模型呢？
我放到模型目录里面加载会提示没有model文件。
但我去看Triton的文档，里面提到是可以直接支持加载IR格式模型的
<img width="437" alt="1678866794017" src="https://user-images.githubusercontent.com/18228342/225243001-f6a06fb8-39a2-4494-ad71-2cc5a26f7986.png">

**Comment by jiangjiajun** [comment]
目前在FastDeploy Serving提供的镜像中仅支持了Paddle/ONNX两种格式支持

**Comment by flamebox** [comment]
> 目前在FastDeploy Serving提供的镜像中仅支持了Paddle/ONNX两种格式支持

那请问在Serving里面cpu使用yolov5的量化模型有什么思路吗？
