### ISSUE TITLE
FastDeploy是否支持在Atlas 200 DK开发者套件上进行模型部署(工作方式为RC模式)？

### ISSUE THREAD

**Issue by MrMzl** [PaddlePaddle/FastDeploy#1625]
测试平台:全爱科技QA200RC Atlas 200 DK
工作方式为RC模式，非fastdeploy官方提供的搭配鲲鹏920CPU，EP模式下的晟腾部署

**Comment by yunyaoXYY** [comment]
可以 参考鲲鹏920的文档来就行

**Comment by MrMzl** [comment]
> 可以 参考鲲鹏920的文档来就行

好的，感谢回复
