### ISSUE TITLE
Windows11，docker环境部署UIE模型运行失败

### ISSUE THREAD

**Issue by lucky0604** [PaddlePaddle/FastDeploy#1631]
## 环境

- 【FastDeploy版本】： fastdeploy1.0.4-cpu-only-21.10
- 【系统平台】: Windows x64(Windows11) docker

## 问题日志及出现问题的操作流程
- 【模型跑不通】
- - 在cpu环境下部署yolov5成功，但部署`uie`模型时，完全按照[文档](https://github.com/PaddlePaddle/FastDeploy/blob/develop/examples/text/uie/serving/README_CN.md)操作，运行服务报错
```shell
E0316 02:18:58.105748 78 model_repository_manager.cc:1890] Poll failed for model directory 'uie': instance group uie_0 of model uie has kind KIND_GPU but server does not support GPUs
```
部署文档，包括uie模型的文档并没有说明必须在gpu环境下运行

**Comment by jiangjiajun** [comment]
需要修改配置文件，将KIND_GPU改为KIND_CPU

**Comment by lucky0604** [comment]
按照配置文档修改了
```shell
instance_group [
  {
      count: 1
      # Use GPU, CPU inference option is:KIND_CPU
      kind: KIND_CPU
      # The instance is deployed on the 0th GPU card
  }
]
```
再次运行` fastdeployserver --model-repository=./models --backend-config=python,shm-default-byte-size=10485760`报错
```shell
[ERROR] fastdeploy/fastdeploy_model.cc(218)::CreateCpuBackend   Found no valid backend for model: UIEModel
0317 01:40:38.052857 83 pb_stub.cc:352] Failed to initialize Python stub: AssertionError: UIEModel initialize failed.

At:
  /usr/local/lib/python3.8/dist-packages/fastdeploy/text/uie/__init__.py(71): __init__
  /root/FastDeploy/examples/text/uie/serving/./models/uie/1/model.py(99): initialize

E0317 01:40:38.053458 81 model_repository_manager.cc:1186] failed to load 'uie' version 1: Internal: AssertionError: UIEModel initialize failed.

At:
  /usr/local/lib/python3.8/dist-packages/fastdeploy/text/uie/__init__.py(71): __init__
  /root/FastDeploy/examples/text/uie/serving/./models/uie/1/model.py(99): initialize
```

**Comment by heliqi** [comment]
镜像中fastdeploy的python包版本较低，UIE模型需要卸载掉安装最新的fastdeploy-python包

**Comment by lucky0604** [comment]
谢谢 我再试一下

**Comment by TherChenYang** [comment]
> 镜像中fastdeploy的python包版本较低，UIE模型需要卸载掉安装最新的fastdeploy-python包
大佬 能咨询下 当时执行的命令嘛 
python3 -m pip install --upgrade --force-reinstall fastdeploy-python 
我执行了这个 重新安装 还是报错

**Comment by heliqi** [comment]
先卸载再安装试试 @TherChenYang 
python3 -m pip uninstall fastdeploy-python

**Comment by TherChenYang** [comment]
![image](https://user-images.githubusercontent.com/124348939/233815456-63688012-b218-4552-95d4-b159a8fe6b65.png)
@heliqi 好像还是报相同的错误 我用gpu的机器再试下
请问下大佬 如果gpu的机器没问题后 该如何替换grpc client为http 请求呢

**Comment by heliqi** [comment]
client中的 from tritonclient.grpc import InferenceServerClient, InferInput, InferRequestedOutput 改成：
from tritonclient.http import InferenceServerClient, InferInput, InferRequestedOutput

执行时 def __init__ 函数会报错， 报错地方由 proto的"xx.a"改成json形势"xx['a']"就行。

比如： 
self._inputs = {tm.name: tm for tm in model_metadata.inputs}  
改成：
self._inputs = {tm['name']: tm for tm in model_metadata['inputs']}

**Comment by heliqi** [comment]
@TherChenYang 你要在docker容器内重装FastDeploy
