### ISSUE TITLE
在jetson orin中怎么安装fastdeploy gpu版本

### ISSUE THREAD

**Issue by kankanjiuzou123** [PaddlePaddle/FastDeploy#1633]
使用命令行装了之后，无法import fastdeploy

**Comment by jiangjiajun** [comment]
参考这个文档编译 https://github.com/PaddlePaddle/FastDeploy/blob/develop/docs/en/build_and_install/jetson.md

编译时可集成的后端Paddle Inference/TensorRT可支持GPU

**Comment by kankanjiuzou123** [comment]
> 参考这个文档编译 https://github.com/PaddlePaddle/FastDeploy/blob/develop/docs/en/build_and_install/jetson.md
> 
> 编译时可集成的后端Paddle Inference/TensorRT可支持GPU
好的，已经编译好了python版本的，感谢！
