### ISSUE TITLE
Linux FastDeploy docker启动服务失败

### ISSUE THREAD

**Issue by kerry-weic** [PaddlePaddle/FastDeploy#1635]
*********************************************
温馨提示：根据社区不完全统计，按照模板提问，可以加快回复和解决问题的速度
*********************************************

## 环境

- 【FastDeploy版本】：fastdeploy镜像包版本: 1.0.4-cpu-only-21.10
- 
![image](https://user-images.githubusercontent.com/49382323/225523533-13bfe0de-2b49-46ad-9b3e-952494eec4d5.png)

- 【系统平台】: Linux x64
- 【硬件】： Intel(R) Xeon(R) CPU E5-2620 v2
- 【编译语言】：Python 3.8.5

按照https://github.com/PaddlePaddle/PaddleOCR/tree/dygraph/deploy/fastdeploy/serving/fastdeploy_serving文档进行操作。
执行fastdeployserver --model-repository=/ocr_serving/models 启动服务时出错 ，日志如下：

r0316 06:33:56.232776 165 model_repository_manager.cc:1890] Poll failed for model directory 'cls_runtime': instance group cls_runtime_0 of model cls_runtime has kind KIND_GPU but server does not support GPUs
E0316 06:33:56.233814 165 model_repository_manager.cc:1890] Poll failed for model directory 'det_runtime': instance group det_runtime_0 of model det_runtime has kind KIND_GPU but server does not support GPUs
E0316 06:33:56.234847 165 model_repository_manager.cc:1890] Poll failed for model directory 'rec_runtime': instance group rec_runtime_0 of model rec_runtime has kind KIND_GPU but server does not support GPUs
E0316 06:33:56.235118 165 model_repository_manager.cc:1375] Invalid argument: ensemble pp_ocr contains models that are not available: det_runtime
E0316 06:33:56.235235 165 model_repository_manager.cc:1375] Invalid argument: ensemble rec_pp contains models that are not available: rec_runtime
E0316 06:33:56.235302 165 model_repository_manager.cc:1375] Invalid argument: ensemble cls_pp contains models that are not available: cls_runtime
I0316 06:33:56.235421 165 model_repository_manager.cc:1022] loading: rec_postprocess:1
I0316 06:33:56.335945 165 model_repository_manager.cc:1022] loading: det_postprocess:1
I0316 06:33:56.343297 165 python.cc:1875] TRITONBACKEND_ModelInstanceInitialize: rec_postprocess_0 (CPU device 0)
I0316 06:33:56.436638 165 model_repository_manager.cc:1022] loading: det_preprocess:1
I0316 06:33:56.537053 165 model_repository_manager.cc:1022] loading: cls_postprocess:1
/usr/lib/python3/dist-packages/requests/__init__.py:89: RequestsDependencyWarning: urllib3 (1.26.14) or chardet (3.0.4) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({}) doesn't match a supported "
model_config: {'name': 'rec_postprocess', 'platform': '', 'backend': 'python', 'version_policy': {'latest': {'num_versions': 1}}, 'max_batch_size': 128, 'input': [{'name': 'POST_INPUT_0', 'data_type': 'TYPE_FP32', 'format': 'FORMAT_NONE', 'dims': [-1, 6625], 'is_shape_tensor': False, 'allow_ragged_batch': False}], 'output': [{'name': 'POST_OUTPUT_0', 'data_type': 'TYPE_STRING', 'dims': [1], 'label_filename': '', 'is_shape_tensor': False}, {'name': 'POST_OUTPUT_1', 'data_type': 'TYPE_FP32', 'dims': [1], 'label_filename': '', 'is_shape_tensor': False}], 'batch_input': [], 'batch_output': [], 'optimization': {'priority': 'PRIORITY_DEFAULT', 'input_pinned_memory': {'enable': True}, 'output_pinned_memory': {'enable': True}, 'gather_kernel_buffer_threshold': 0, 'eager_batching': False}, 'instance_group': [{'name': 'rec_postprocess_0', 'kind': 'KIND_CPU', 'count': 1, 'gpus': [], 'secondary_devices': [], 'profile': [], 'passive': False, 'host_policy': ''}], 'default_model_filename': '', 'cc_model_filenames': {}, 'metric_tags': {}, 'parameters': {}, 'model_warmup': []}
postprocess input names: ['POST_INPUT_0']
postprocess output names: ['POST_OUTPUT_0', 'POST_OUTPUT_1']
I0316 06:33:57.401222 165 model_repository_manager.cc:1183] successfully loaded 'rec_postprocess' version 1
I0316 06:33:57.402776 165 python.cc:1875] TRITONBACKEND_ModelInstanceInitialize: det_postprocess_0 (CPU device 0)
/usr/lib/python3/dist-packages/requests/__init__.py:89: RequestsDependencyWarning: urllib3 (1.26.14) or chardet (3.0.4) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({}) doesn't match a supported "
model_config: {'name': 'det_postprocess', 'platform': '', 'backend': 'python', 'version_policy': {'latest': {'num_versions': 1}}, 'max_batch_size': 128, 'input': [{'name': 'POST_INPUT_0', 'data_type': 'TYPE_FP32', 'format': 'FORMAT_NONE', 'dims': [1, -1, -1], 'is_shape_tensor': False, 'allow_ragged_batch': False}, {'name': 'POST_INPUT_1', 'data_type': 'TYPE_INT32', 'format': 'FORMAT_NONE', 'dims': [4], 'is_shape_tensor': False, 'allow_ragged_batch': False}, {'name': 'ORI_IMG', 'data_type': 'TYPE_UINT8', 'format': 'FORMAT_NONE', 'dims': [-1, -1, 3], 'is_shape_tensor': False, 'allow_ragged_batch': False}], 'output': [{'name': 'POST_OUTPUT_0', 'data_type': 'TYPE_STRING', 'dims': [-1, 1], 'label_filename': '', 'is_shape_tensor': False}, {'name': 'POST_OUTPUT_1', 'data_type': 'TYPE_FP32', 'dims': [-1, 1], 'label_filename': '', 'is_shape_tensor': False}, {'name': 'POST_OUTPUT_2', 'data_type': 'TYPE_FP32', 'dims': [-1, -1, 1], 'label_filename': '', 'is_shape_tensor': False}], 'batch_input': [], 'batch_output': [], 'optimization': {'priority': 'PRIORITY_DEFAULT', 'input_pinned_memory': {'enable': True}, 'output_pinned_memory': {'enable': True}, 'gather_kernel_buffer_threshold': 0, 'eager_batching': False}, 'instance_group': [{'name': 'det_postprocess_0', 'kind': 'KIND_CPU', 'count': 1, 'gpus': [], 'secondary_devices': [], 'profile': [], 'passive': False, 'host_policy': ''}], 'default_model_filename': '', 'cc_model_filenames': {}, 'metric_tags': {}, 'parameters': {}, 'model_warmup': []}
postprocess input names: ['POST_INPUT_0', 'POST_INPUT_1', 'ORI_IMG']
postprocess output names: ['POST_OUTPUT_0', 'POST_OUTPUT_1', 'POST_OUTPUT_2']
I0316 06:33:58.523082 165 python.cc:1875] TRITONBACKEND_ModelInstanceInitialize: det_preprocess_0 (CPU device 0)
I0316 06:33:58.523395 165 model_repository_manager.cc:1183] successfully loaded 'det_postprocess' version 1
/usr/lib/python3/dist-packages/requests/__init__.py:89: RequestsDependencyWarning: urllib3 (1.26.14) or chardet (3.0.4) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({}) doesn't match a supported "
model_config: {'name': 'det_preprocess', 'platform': '', 'backend': 'python', 'version_policy': {'latest': {'num_versions': 1}}, 'max_batch_size': 1, 'input': [{'name': 'INPUT_0', 'data_type': 'TYPE_UINT8', 'format': 'FORMAT_NONE', 'dims': [-1, -1, 3], 'is_shape_tensor': False, 'allow_ragged_batch': False}], 'output': [{'name': 'OUTPUT_0', 'data_type': 'TYPE_FP32', 'dims': [3, -1, -1], 'label_filename': '', 'is_shape_tensor': False}, {'name': 'OUTPUT_1', 'data_type': 'TYPE_INT32', 'dims': [4], 'label_filename': '', 'is_shape_tensor': False}], 'batch_input': [], 'batch_output': [], 'optimization': {'priority': 'PRIORITY_DEFAULT', 'input_pinned_memory': {'enable': True}, 'output_pinned_memory': {'enable': True}, 'gather_kernel_buffer_threshold': 0, 'eager_batching': False}, 'instance_group': [{'name': 'det_preprocess_0', 'kind': 'KIND_CPU', 'count': 1, 'gpus': [], 'secondary_devices': [], 'profile': [], 'passive': False, 'host_policy': ''}], 'default_model_filename': '', 'cc_model_filenames': {}, 'metric_tags': {}, 'parameters': {}, 'model_warmup': []}
preprocess input names: ['INPUT_0']
preprocess output names: ['OUTPUT_0', 'OUTPUT_1']
I0316 06:33:59.523855 165 python.cc:1875] TRITONBACKEND_ModelInstanceInitialize: cls_postprocess_0 (CPU device 0)
I0316 06:33:59.524233 165 model_repository_manager.cc:1183] successfully loaded 'det_preprocess' version 1
/usr/lib/python3/dist-packages/requests/__init__.py:89: RequestsDependencyWarning: urllib3 (1.26.14) or chardet (3.0.4) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({}) doesn't match a supported "
model_config: {'name': 'cls_postprocess', 'platform': '', 'backend': 'python', 'version_policy': {'latest': {'num_versions': 1}}, 'max_batch_size': 128, 'input': [{'name': 'POST_INPUT_0', 'data_type': 'TYPE_FP32', 'format': 'FORMAT_NONE', 'dims': [2], 'is_shape_tensor': False, 'allow_ragged_batch': False}], 'output': [{'name': 'POST_OUTPUT_0', 'data_type': 'TYPE_INT32', 'dims': [1], 'label_filename': '', 'is_shape_tensor': False}, {'name': 'POST_OUTPUT_1', 'data_type': 'TYPE_FP32', 'dims': [1], 'label_filename': '', 'is_shape_tensor': False}], 'batch_input': [], 'batch_output': [], 'optimization': {'priority': 'PRIORITY_DEFAULT', 'input_pinned_memory': {'enable': True}, 'output_pinned_memory': {'enable': True}, 'gather_kernel_buffer_threshold': 0, 'eager_batching': False}, 'instance_group': [{'name': 'cls_postprocess_0', 'kind': 'KIND_CPU', 'count': 1, 'gpus': [], 'secondary_devices': [], 'profile': [], 'passive': False, 'host_policy': ''}], 'default_model_filename': '', 'cc_model_filenames': {}, 'metric_tags': {}, 'parameters': {}, 'model_warmup': []}
postprocess input names: ['POST_INPUT_0']
postprocess output names: ['POST_OUTPUT_0', 'POST_OUTPUT_1']
I0316 06:34:00.546161 165 model_repository_manager.cc:1183] successfully loaded 'cls_postprocess' version 1
I0316 06:34:00.546492 165 server.cc:522] 
+------------------+------+
| Repository Agent | Path |
+------------------+------+
+------------------+------+

I0316 06:34:00.546641 165 server.cc:549] 
+---------+-------------------------------------------------------+--------+
| Backend | Path                                                  | Config |
+---------+-------------------------------------------------------+--------+
| python  | /opt/tritonserver/backends/python/libtriton_python.so | {}     |
+---------+-------------------------------------------------------+--------+

I0316 06:34:00.546807 165 server.cc:592] 
+-----------------+---------+--------+
| Model           | Version | Status |
+-----------------+---------+--------+
| cls_postprocess | 1       | READY  |
| det_postprocess | 1       | READY  |
| det_preprocess  | 1       | READY  |
| rec_postprocess | 1       | READY  |
+-----------------+---------+--------+

I0316 06:34:00.547184 165 tritonserver.cc:1920] 
+----------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Option                           | Value                                                                                                                                                                        |
+----------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| server_id                        | triton                                                                                                                                                                       |
| server_version                   | 2.15.0                                                                                                                                                                       |
| server_extensions                | classification sequence model_repository model_repository(unload_dependents) schedule_policy model_configuration system_shared_memory cuda_shared_memory binary_tensor_data  |
|                                  | statistics                                                                                                                                                                   |
| model_repository_path[0]         | /ocr_serving/models                                                                                                                                                          |
| model_control_mode               | MODE_NONE                                                                                                                                                                    |
| strict_model_config              | 1                                                                                                                                                                            |
| rate_limit                       | OFF                                                                                                                                                                          |
| pinned_memory_pool_byte_size     | 268435456                                                                                                                                                                    |
| response_cache_byte_size         | 0                                                                                                                                                                            |
| min_supported_compute_capability | 0.0                                                                                                                                                                          |
| strict_readiness                 | 1                                                                                                                                                                            |
| exit_timeout                     | 30                                                                                                                                                                           |
+----------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+

I0316 06:34:00.547466 165 server.cc:252] Waiting for in-flight requests to complete.
I0316 06:34:00.547507 165 model_repository_manager.cc:1055] unloading: rec_postprocess:1
I0316 06:34:00.547588 165 model_repository_manager.cc:1055] unloading: det_preprocess:1
I0316 06:34:00.547689 165 model_repository_manager.cc:1055] unloading: det_postprocess:1
I0316 06:34:00.547770 165 model_repository_manager.cc:1055] unloading: cls_postprocess:1
I0316 06:34:00.547871 165 server.cc:267] Timeout 30: Found 4 live models and 0 in-flight non-inference requests
Cleaning up...
Cleaning up...
Cleaning up...
I0316 06:34:01.548107 165 server.cc:267] Timeout 29: Found 4 live models and 0 in-flight non-inference requests
Cleaning up...
I0316 06:34:01.769178 165 model_repository_manager.cc:1166] successfully unloaded 'rec_postprocess' version 1
I0316 06:34:01.777994 165 model_repository_manager.cc:1166] successfully unloaded 'cls_postprocess' version 1
I0316 06:34:01.851643 165 model_repository_manager.cc:1166] successfully unloaded 'det_postprocess' version 1
I0316 06:34:01.853469 165 model_repository_manager.cc:1166] successfully unloaded 'det_preprocess' version 1
I0316 06:34:02.548376 165 server.cc:267] Timeout 28: Found 0 live models and 0 in-flight non-inference requests
error: creating server: Internal - failed to load all models

**Comment by heliqi** [comment]
@kerry-weic 
你使用的cpu镜像，但是ocr例子中默认使用的gpu. 有两个方式解决:
1. 使用GPU的镜像
2. 将配置中kind由KIND_GPU改成KIND_CPU，比如: https://github.com/PaddlePaddle/PaddleOCR/blob/dygraph/deploy/fastdeploy/serving/fastdeploy_serving/models/cls_runtime/config.pbtxt   中 kind的配置

**Comment by kerry-weic** [comment]
修改配置后，服务已经能正常启动和推理，但推理速度很慢，尝试启用use_mkldnn但视乎没有效果，识别速度跟没开启use_mkldnn基本一致。修改rec_runtime/det_run_time/cls_runtime目录下的config.pbtxt配置:
![image](https://user-images.githubusercontent.com/49382323/225808317-3fa7d377-d458-4842-8837-4da8807bf9e2.png)
启动日志片段:
I0317 03:03:26.098106 1125 model_repository_manager.cc:1183] successfully loaded 'det_preprocess' version 1
I0317 03:03:26.098888 1125 fastdeploy_runtime.cc:1255] TRITONBACKEND_ModelInitialize: det_runtime (version 1)
[WARNING] fastdeploy/runtime/runtime_option.cc(189)::SetPaddleMKLDNN	`RuntimeOption::SetPaddleMKLDNN` will be removed in v1.2.0, please modify its member variable directly, e.g `option.paddle_infer_option.enable_mkldnn = true`
I0317 03:03:26.101156 1125 fastdeploy_runtime.cc:1255] TRITONBACKEND_ModelInitialize: rec_runtime (version 1)
[WARNING] fastdeploy/runtime/runtime_option.cc(189)::SetPaddleMKLDNN	`RuntimeOption::SetPaddleMKLDNN` will be removed in v1.2.0, please modify its member variable directly, e.g `option.paddle_infer_option.enable_mkldnn = true`
I0317 03:03:26.102358 1125 fastdeploy_runtime.cc:1255] TRITONBACKEND_ModelInitialize: cls_runtime (version 1)
[WARNING] fastdeploy/runtime/runtime_option.cc(189)::SetPaddleMKLDNN	`RuntimeOption::SetPaddleMKLDNN` will be removed in v1.2.0, please modify its member variable directly, e.g `option.paddle_infer_option.enable_mkldnn = true`
I0317 03:03:26.103318 1125 python.cc:1875] TRITONBACKEND_ModelInstanceInitialize: rec_postprocess_0 (CPU device 0)

**Comment by heliqi** [comment]
1. CPU相比GPU是偏慢一点
2. 可以尝试使用ONNXRuntime和Openvino后端，速度应该更快点。如果资源足够可以多开几个线程
具体配置看这个文档： https://github.com/PaddlePaddle/FastDeploy/blob/develop/serving/docs/EN/model_configuration-en.md

**Comment by kerry-weic** [comment]
有预测性能相关日志吗？像Paddle Serving pipeline部署时，可以通过PipelineServingLogs/pipeline.tracer查看。

**Comment by heliqi** [comment]
1. 可以用fastdeployserve --help 打开trace日志
2. 你也可以通过triton的perf_analyzer来压测性能，会输出各阶段的耗时: https://github.com/triton-inference-server/client/blob/main/src/c++/perf_analyzer/README.md

**Comment by xiaomi0922** [comment]
> 修改配置后，服务已经能正常启动和推理，但推理速度很慢，尝试启用use_mkldnn但视乎没有效果，识别速度跟没开启use_mkldnn基本一致。修改rec_runtime/det_run_time/cls_runtime目录下的config.pbtxt配置: ![image](https://user-images.githubusercontent.com/49382323/225808317-3fa7d377-d458-4842-8837-4da8807bf9e2.png) 启动日志片段: I0317 03:03:26.098106 1125 model_repository_manager.cc:1183] successfully loaded 'det_preprocess' version 1 I0317 03:03:26.098888 1125 fastdeploy_runtime.cc:1255] TRITONBACKEND_ModelInitialize: det_runtime (version 1) [WARNING] fastdeploy/runtime/runtime_option.cc(189)::SetPaddleMKLDNN `RuntimeOption::SetPaddleMKLDNN` will be removed in v1.2.0, please modify its member variable directly, e.g `option.paddle_infer_option.enable_mkldnn = true` I0317 03:03:26.101156 1125 fastdeploy_runtime.cc:1255] TRITONBACKEND_ModelInitialize: rec_runtime (version 1) [WARNING] fastdeploy/runtime/runtime_option.cc(189)::SetPaddleMKLDNN `RuntimeOption::SetPaddleMKLDNN` will be removed in v1.2.0, please modify its member variable directly, e.g `option.paddle_infer_option.enable_mkldnn = true` I0317 03:03:26.102358 1125 fastdeploy_runtime.cc:1255] TRITONBACKEND_ModelInitialize: cls_runtime (version 1) [WARNING] fastdeploy/runtime/runtime_option.cc(189)::SetPaddleMKLDNN `RuntimeOption::SetPaddleMKLDNN` will be removed in v1.2.0, please modify its member variable directly, e.g `option.paddle_infer_option.enable_mkldnn = true` I0317 03:03:26.103318 1125 python.cc:1875] TRITONBACKEND_ModelInstanceInitialize: rec_postprocess_0 (CPU device 0)


-------------------------------------------------------------------------------------------------------------------------------------------
修改了配置文件后，运行python3 client.py报错，请问遇到过嘛，ps（我将batch_texts、batch_scores、batch_bboxes的结果打印出来了，为空）

报错内容如下：  
[[b'']]
[[0.]]
[]
Traceback (most recent call last):
  File "client.py", line 112, in <module>
    scores[i_box], '  bbox=', bboxes[i_box])
IndexError: index 0 is out of bounds for axis 0 with size 0

**Comment by kerry-weic** [comment]
没有哦

**Comment by wuqiu-ai** [comment]
> @kerry-weic 你使用的cpu镜像，但是ocr例子中默认使用的gpu. 有两个方式解决:
> 
> 1. 使用GPU的镜像
> 2. 将配置中kind由KIND_GPU改成KIND_CPU，比如: https://github.com/PaddlePaddle/PaddleOCR/blob/dygraph/deploy/fastdeploy/serving/fastdeploy_serving/models/cls_runtime/config.pbtxt   中 kind的配置

我这边调整成kind_cpu之后还是有报错
```less
root@master-ocr-test-1:/ocr_serving# fastdeployserver --model-repository=/ocr_serving/models
E0419 07:30:46.584787 29 model_repository_manager.cc:1890] Poll failed for model directory 'cls_runtime': instance group cls_runtime_0 of model cls_runtime has kind KIND_CPU but specifies one or more GPUs
E0419 07:30:46.585299 29 model_repository_manager.cc:1890] Poll failed for model directory 'det_runtime': instance group det_runtime_0 of model det_runtime has kind KIND_CPU but specifies one or more GPUs
E0419 07:30:46.585787 29 model_repository_manager.cc:1890] Poll failed for model directory 'rec_runtime': instance group rec_runtime_0 of model rec_runtime has kind KIND_CPU but specifies one or more GPUs
E0419 07:30:46.585886 29 model_repository_manager.cc:1375] Invalid argument: ensemble pp_ocr contains models that are not available: det_runtime
E0419 07:30:46.585898 29 model_repository_manager.cc:1375] Invalid argument: ensemble rec_pp contains models that are not available: rec_runtime
E0419 07:30:46.585904 29 model_repository_manager.cc:1375] Invalid argument: ensemble cls_pp contains models that are not available: cls_runtime
I0419 07:30:46.585949 29 model_repository_manager.cc:1022] loading: rec_postprocess:1
I0419 07:30:46.686221 29 model_repository_manager.cc:1022] loading: det_postprocess:1
I0419 07:30:46.690046 29 python.cc:1875] TRITONBACKEND_ModelInstanceInitialize: rec_postprocess_0 (CPU device 0)
I0419 07:30:46.786507 29 model_repository_manager.cc:1022] loading: det_preprocess:1
I0419 07:30:46.886764 29 model_repository_manager.cc:1022] loading: cls_postprocess:1
/usr/lib/python3/dist-packages/requests/__init__.py:89: RequestsDependencyWarning: urllib3 (1.26.14) or chardet (3.0.4) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({}) doesn't match a supported "
model_config: {'name': 'rec_postprocess', 'platform': '', 'backend': 'python', 'version_policy': {'latest': {'num_versions': 1}}, 'max_batch_size': 128, 'input': [{'name': 'POST_INPUT_0', 'data_type': 'TYPE_FP32', 'format': 'FORMAT_NONE', 'dims': [-1, 6625], 'is_shape_tensor': False, 'allow_ragged_batch': False}], 'output': [{'name': 'POST_OUTPUT_0', 'data_type': 'TYPE_STRING', 'dims': [1], 'label_filename': '', 'is_shape_tensor': False}, {'name': 'POST_OUTPUT_1', 'data_type': 'TYPE_FP32', 'dims': [1], 'label_filename': '', 'is_shape_tensor': False}], 'batch_input': [], 'batch_output': [], 'optimization': {'priority': 'PRIORITY_DEFAULT', 'input_pinned_memory': {'enable': True}, 'output_pinned_memory': {'enable': True}, 'gather_kernel_buffer_threshold': 0, 'eager_batching': False}, 'instance_group': [{'name': 'rec_postprocess_0', 'kind': 'KIND_CPU', 'count': 1, 'gpus': [], 'secondary_devices': [], 'profile': [], 'passive': False, 'host_policy': ''}], 'default_model_filename': '', 'cc_model_filenames': {}, 'metric_tags': {}, 'parameters': {}, 'model_warmup': []}
postprocess input names: ['POST_INPUT_0']
postprocess output names: ['POST_OUTPUT_0', 'POST_OUTPUT_1']
I0419 07:30:47.030829 29 model_repository_manager.cc:1183] successfully loaded 'rec_postprocess' version 1
```

**Comment by xiaomi0922** [comment]
> > @kerry-weic 你使用的cpu镜像，但是ocr例子中默认使用的gpu. 有两个方式解决:
> > 
> > 1. 使用GPU的镜像
> > 2. 将配置中kind由KIND_GPU改成KIND_CPU，比如: https://github.com/PaddlePaddle/PaddleOCR/blob/dygraph/deploy/fastdeploy/serving/fastdeploy_serving/models/cls_runtime/config.pbtxt   中 kind的配置
> 
> 我这边调整成kind_cpu之后还是有报错
> 
> ```css-less
> root@master-ocr-test-1:/ocr_serving# fastdeployserver --model-repository=/ocr_serving/models
> E0419 07:30:46.584787 29 model_repository_manager.cc:1890] Poll failed for model directory 'cls_runtime': instance group cls_runtime_0 of model cls_runtime has kind KIND_CPU but specifies one or more GPUs
> E0419 07:30:46.585299 29 model_repository_manager.cc:1890] Poll failed for model directory 'det_runtime': instance group det_runtime_0 of model det_runtime has kind KIND_CPU but specifies one or more GPUs
> E0419 07:30:46.585787 29 model_repository_manager.cc:1890] Poll failed for model directory 'rec_runtime': instance group rec_runtime_0 of model rec_runtime has kind KIND_CPU but specifies one or more GPUs
> E0419 07:30:46.585886 29 model_repository_manager.cc:1375] Invalid argument: ensemble pp_ocr contains models that are not available: det_runtime
> E0419 07:30:46.585898 29 model_repository_manager.cc:1375] Invalid argument: ensemble rec_pp contains models that are not available: rec_runtime
> E0419 07:30:46.585904 29 model_repository_manager.cc:1375] Invalid argument: ensemble cls_pp contains models that are not available: cls_runtime
> I0419 07:30:46.585949 29 model_repository_manager.cc:1022] loading: rec_postprocess:1
> I0419 07:30:46.686221 29 model_repository_manager.cc:1022] loading: det_postprocess:1
> I0419 07:30:46.690046 29 python.cc:1875] TRITONBACKEND_ModelInstanceInitialize: rec_postprocess_0 (CPU device 0)
> I0419 07:30:46.786507 29 model_repository_manager.cc:1022] loading: det_preprocess:1
> I0419 07:30:46.886764 29 model_repository_manager.cc:1022] loading: cls_postprocess:1
> /usr/lib/python3/dist-packages/requests/__init__.py:89: RequestsDependencyWarning: urllib3 (1.26.14) or chardet (3.0.4) doesn't match a supported version!
>   warnings.warn("urllib3 ({}) or chardet ({}) doesn't match a supported "
> model_config: {'name': 'rec_postprocess', 'platform': '', 'backend': 'python', 'version_policy': {'latest': {'num_versions': 1}}, 'max_batch_size': 128, 'input': [{'name': 'POST_INPUT_0', 'data_type': 'TYPE_FP32', 'format': 'FORMAT_NONE', 'dims': [-1, 6625], 'is_shape_tensor': False, 'allow_ragged_batch': False}], 'output': [{'name': 'POST_OUTPUT_0', 'data_type': 'TYPE_STRING', 'dims': [1], 'label_filename': '', 'is_shape_tensor': False}, {'name': 'POST_OUTPUT_1', 'data_type': 'TYPE_FP32', 'dims': [1], 'label_filename': '', 'is_shape_tensor': False}], 'batch_input': [], 'batch_output': [], 'optimization': {'priority': 'PRIORITY_DEFAULT', 'input_pinned_memory': {'enable': True}, 'output_pinned_memory': {'enable': True}, 'gather_kernel_buffer_threshold': 0, 'eager_batching': False}, 'instance_group': [{'name': 'rec_postprocess_0', 'kind': 'KIND_CPU', 'count': 1, 'gpus': [], 'secondary_devices': [], 'profile': [], 'passive': False, 'host_policy': ''}], 'default_model_filename': '', 'cc_model_filenames': {}, 'metric_tags': {}, 'parameters': {}, 'model_warmup': []}
> postprocess input names: ['POST_INPUT_0']
> postprocess output names: ['POST_OUTPUT_0', 'POST_OUTPUT_1']
> I0419 07:30:47.030829 29 model_repository_manager.cc:1183] successfully loaded 'rec_postprocess' version 1
> ```



#### 
rec_runtime/det_run_time/cls_runtime这三个目录下的目录下的config.pbtxt都修改了嘛，文件中需要修改的地方有两处，一个是KIND_GPU改为KIND_CPU，一个是gpu_execution_accelerator改为cpu_execution_accelerator

**Comment by kerry-weic** [comment]
@wuqiu-ai @xiaomi0922 
嗯， 三个目录下的config.pbtxt都需要改。如果你使用的是cpu版本另外还需注释gpus: [0]。

> /usr/lib/python3/dist-packages/requests/__init__.py:89: RequestsDependencyWarning: urllib3 (1.26.14) or chardet (3.0.4) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({}) doesn't match a supported "

urllib3 、chardet 这两个包版本不匹配，可以尝试重新安装这两个包，或者把chardet 卸载掉再启动试试。

**Comment by pangdahua** [comment]
@kerry-weic 已解决，感谢

**Comment by sheiy** [comment]
@pangdahua 我启起来图片长一点就会报错`TritonModelException: inference request batch-size must be <= 128 for 'cls_pp'` 知道怎么解决不？
