### ISSUE TITLE
jetson依赖库问题

### ISSUE THREAD

**Issue by ShawnXsw** [PaddlePaddle/FastDeploy#1641]
## 环境

- 【FastDeploy版本】：fastdeploy-linux-gpu-dev
- 【系统平台】: jetpack 5.1
- 【硬件】： ORIN NX
- 【编译语言】： C++

host编译正常，docker（nvcr.io/nvidia/l4t-jetpack:r35.2.1）中编译后，缺失部分so
![image](https://user-images.githubusercontent.com/33308054/225653099-02df9f9d-265d-4b41-8c88-6f2b99a387b6.png)

上述缺失so不在docker中编译时，链接如下：
![image](https://user-images.githubusercontent.com/33308054/225653797-14521aea-5edd-4c29-9c62-560c902a300b.png)

**Comment by wang-xinyu** [comment]
运行docker的时候是否加--runtime nvidia了？

```
sudo docker run -it --rm --net=host --runtime nvidia -e DISPLAY=$DISPLAY -v /tmp/.X11-unix/:/tmp/.X11-unix nvcr.io/nvidia/l4t-jetpack:r35.2.1
```

**Comment by ShawnXsw** [comment]
> --runtime nvidia

我的

**Comment by ShawnXsw** [comment]
> 运行docker的时候是否加--runtime nvidia了？
> 
> ```
> sudo docker run -it --rm --net=host --runtime nvidia -e DISPLAY=$DISPLAY -v /tmp/.X11-unix/:/tmp/.X11-unix nvcr.io/nvidia/l4t-jetpack:r35.2.1
> ```

我的
