### ISSUE TITLE
昇腾NPU使用Docker编译安装FastDeploy部署OCR报错[ERROR] fastdeploy/runtime/runtime_option.cc(133)::UsePaddleBackend     The FastDeploy didn't compile with Paddle Inference.

### ISSUE THREAD

**Issue by minboo** [PaddlePaddle/FastDeploy#1661]
*********************************************
温馨提示：根据社区不完全统计，按照模板提问，可以加快回复和解决问题的速度
*********************************************

## 环境
- 【FastDeploy版本】： 说明具体的版本，如fastdeploy-linux-gpu-0.8.0
- 【编译命令】如果您是自行编译的FastDeploy，请说明您的编译方式（参数命令）
```
# Download the latest source code
git clone https://github.com/PaddlePaddle/FastDeploy.git
cd FastDeploy/python
export WITH_ASCEND=ON
export ENABLE_VISION=ON

python setup.py build
python setup.py bdist_wheel

```
- 【系统平台】: Linux x64(Ubuntu 18.04) / Windows x64(Windows10) / Mac OSX arm(12.0) / Mac OSX intel(12.0)
宿主机UOS v20  容器 Ubuntu 18.04
- 【硬件】： 说明具体硬件型号，如 Nvidia GPU 3080TI， CUDA 11.2 CUDNN 8.3
昇腾310
- 【编译语言】： C++ / Python(3.7或3.8等）

## 问题日志及出现问题的操作流程
**请问我根据文档：[华为昇腾NPU 部署环境编译准备](https://github.com/PaddlePaddle/FastDeploy/blob/develop/docs/cn/build_and_install/huawei_ascend.md)的步骤编译安装完成后
使用脚本：`python infer_static_shape.py --det_model ch_PP-OCRv3_det_infer --cls_model ch_ppocr_mobile_v2.0_cls_infer --rec_model ch_PP-OCRv3_rec_infer --rec_label_file ppocr_keys_v1.txt --image 12.jpg --device ascend`可以进行推理出结果。**
![image](https://user-images.githubusercontent.com/69302396/226298730-d5df8a3a-419b-42d7-920b-4e6613c05e3d.png)

**但是按照文档[PP-OCRv3 Python轻量服务化部署示例](https://github.com/PaddlePaddle/FastDeploy/blob/develop/examples/vision/ocr/PP-OCRv3/python/serving/README_CN.md)中使用`fastdeploy simple_serving --app server:app`启动服务失败，报错显示**
![image](https://user-images.githubusercontent.com/69302396/226298904-45e73688-1cab-4770-bb02-fbde7a8c0624.png)

```
root@localhost:/home/FastDeploy/examples/vision/ocr/PP-OCRv3/python/serving# fastdeploy simple_serving --app server:app
[ERROR] fastdeploy/runtime/runtime_option.cc(133)::UsePaddleBackend     The FastDeploy didn't compile with Paddle Inference.
Aborted (core dumped)
```
**请问我是漏了什么步骤没有做吗？求解。**

**Comment by yunyaoXYY** [comment]
https://github.com/PaddlePaddle/FastDeploy/blob/develop/examples/vision/ocr/PP-OCRv3/python/serving/server.py#:~:text=%23%20Setup%20runtime%20option%20to%20select%20hardware%2C%20backend%2C%20etc.

你把这部分的runtime option，参考昇腾的python来设置昇腾的runtime

**Comment by minboo** [comment]
> https://github.com/PaddlePaddle/FastDeploy/blob/develop/examples/vision/ocr/PP-OCRv3/python/serving/server.py#:~:text=%23%20Setup%20runtime%20option%20to%20select%20hardware%2C%20backend%2C%20etc.
> 
> 你把这部分的runtime option，参考昇腾的python来设置昇腾的runtime

**您好，我把[server.py](https://github.com/PaddlePaddle/FastDeploy/blob/develop/examples/vision/ocr/PP-OCRv3/python/serving/server.py#:~:text=%23%20Setup%20runtime%20option%20to%20select%20hardware%2C%20backend%2C%20etc.)里的原代码**
```
device = 'cpu'

....

option = fd.RuntimeOption()
if device.lower() == 'gpu':
    option.use_gpu()
if backend == 'trt':
    option.use_trt_backend()
else:
    option.use_paddle_infer_backend()
```
**改为了**
```
device = 'ascend'

......

option = fd.RuntimeOption()
if device.lower() == 'ascend':
    option.use_ascend()
```
**您看是否正确？**
