### ISSUE TITLE
segmentation task in streamer[deepstream]?

### ISSUE THREAD

**Issue by YoungjaeDev** [PaddlePaddle/FastDeploy#1663]
## Environment

FastDeploy version: e.g 0.8.0 or the latest code in develop branch
OS Platform: e.g. Linux x64 / Windows x64 / Mac OSX 12.1(arm or intel)
Hardware: e.g. Nvidia GPU 3080Ti  CUDA 11.2 CUDNN 8.3
Program Language: e.g. Python 3.8

## Problem description
Please attach the log file if there's problem happend.

hello,
I'd like to run a semantic model supported by paddleseg in deepstream base, is there any restriction?
Or can't I expect a big speed difference from what Deepstream itself runs on Paddle Trt backend from a different perspective?

@wang-xinyu

**Comment by wang-xinyu** [comment]
We don't have segmentation example in streamer as of now. Can you please tell your application and use case? We will be considering add such example.

**Comment by YoungjaeDev** [comment]
@wang-xinyu 
Rather than specifying it in my application, I think it would be good to organize the application based on the cityscape model and related images or videos
I was curious about how config has a model trained in paddleseg and configures other config values such as `offset, scale-factor, etc`. in nvinfer_config!
