### ISSUE TITLE
Ubuntu 编译 CPU C++ 版本时失败

### ISSUE THREAD

**Issue by Fancy-hjyp** [PaddlePaddle/FastDeploy#1671]
*********************************************
温馨提示：根据社区不完全统计，按照模板提问，可以加快回复和解决问题的速度
*********************************************

## 环境

- 【编译命令】cmake .. -DENABLE_ORT_BACKEND=ON     -DENABLE_PADDLE_BACKEND=ON         
                                      -DENABLE_OPENVINO_BACKEND=OFF          
                                      -DCMAKE_INSTALL_PREFIX=${PWD}/compiled_fastdeploy_sdk          
                                      -DENABLE_VISION=ON          
                                      -DOPENCV_DIRECTORY=/usr/lib/x86_64-linux-gnu/cmake/opencv4         
                                      -DENABLE_TEXT=ON
- 【系统平台】: Linux x64(Ubuntu 22.04) 
- 【硬件】： 想要编译CPU
- 【编译语言】： C++ 

## 问题日志及出现问题的操作流程

我想使用 Java 调用 FastDeploy 的接口，所以得先编译 C++ 版本的 FastDeploy ，然后想编译好后作为 库 引入到 JNI 里面，但是在编译 C++ 版本时报如下错误：
```shell
100%] Linking CXX shared library libfastdeploy.so
[100%] Built target fastdeploy
bash: line 1: python: command not found
make[2]: *** [CMakeFiles/patchelf_paddle_inference.dir/build.make:70: CMakeFiles/patchelf_paddle_inference] Error 127
make[1]: *** [CMakeFiles/Makefile2:273: CMakeFiles/patchelf_paddle_inference.dir/all] Error 2
make: *** [Makefile:156: all] Error 2

```
![1679405860745](https://user-images.githubusercontent.com/53164956/226624731-5fd3c47e-bb12-426f-ab62-4592186bec49.png)
编译过程中还有一段这样的提示：
```shell
In file included from /home/hjyp/code/DeepLearning/FastDeploy/third_party/onnx/onnx/common/ir_pb_converter.h:10,
                 from /home/hjyp/code/DeepLearning/FastDeploy/third_party/onnx/onnx/common/ir_pb_converter.cc:8:
In constructor ‘paddle2onnx::Dimension::Dimension(paddle2onnx::Dimension&&)’,
    inlined from ‘void __gnu_cxx::new_allocator<_Tp>::construct(_Up*, _Args&& ...) [with _Up = paddle2onnx::Dimension; _Args = {paddle2onnx::Dimension}; _Tp = paddle2onnx::Dimension]’ at /usr/include/c++/11/ext/new_allocator.h:162:4,
    inlined from ‘static void std::allocator_traits<std::allocator<_CharT> >::construct(std::allocator_traits<std::allocator<_CharT> >::allocator_type&, _Up*, _Args&& ...) [with _Up = paddle2onnx::Dimension; _Args = {paddle2onnx::Dimension}; _Tp = paddle2onnx::Dimension]’ at /usr/include/c++/11/bits/alloc_traits.h:516:17,
    inlined from ‘void std::vector<_Tp, _Alloc>::emplace_back(_Args&& ...) [with _Args = {paddle2onnx::Dimension}; _Tp = paddle2onnx::Dimension; _Alloc = std::allocator<paddle2onnx::Dimension>]’ at /usr/include/c++/11/bits/vector.tcc:115:30,
    inlined from ‘void std::vector<_Tp, _Alloc>::push_back(std::vector<_Tp, _Alloc>::value_type&&) [with _Tp = paddle2onnx::Dimension; _Alloc = std::allocator<paddle2onnx::Dimension>]’ at /usr/include/c++/11/bits/stl_vector.h:1204:21,
    inlined from ‘std::vector<paddle2onnx::Dimension> paddle2onnx::tensorShapeProtoToDimensions(const paddle2onnx::TensorShapeProto&)’ at /home/hjyp/code/DeepLearning/FastDeploy/third_party/onnx/onnx/common/ir_pb_converter.cc:201:21:
/home/hjyp/code/DeepLearning/FastDeploy/third_party/onnx/onnx/common/ir.h:74:8: warning: ‘<unnamed>.paddle2onnx::Dimension::dim’ may be used uninitialized [-Wmaybe-uninitialized]
   74 | struct Dimension final {
      |        ^~~~~~~~~
/home/hjyp/code/DeepLearning/FastDeploy/third_party/onnx/onnx/common/ir_pb_converter.cc: In function ‘std::vector<paddle2onnx::Dimension> paddle2onnx::tensorShapeProtoToDimensions(const paddle2onnx::TensorShapeProto&)’:
/home/hjyp/code/DeepLearning/FastDeploy/third_party/onnx/onnx/common/ir_pb_converter.cc:201:32: note: ‘<anonymous>’ declared here
  201 |       dims.push_back(Dimension());
      |                                ^

```
![image](https://user-images.githubusercontent.com/53164956/226625120-4fef456d-686a-41a5-8bbd-bbe2097855cc.png)

**Comment by jiangjiajun** [comment]
添加-DBUILD_PADDLE2ONNX=OFF试下

**Comment by Fancy-hjyp** [comment]
您好，添加后还是报一样的错误，中间的报错也一样，添加后执行的指令为：
cmake .. -DENABLE_ORT_BACKEND=ON  
              -DENABLE_PADDLE_BACKEND=ON
              -DENABLE_OPENVINO_BACKEND=OFF 
              -DCMAKE_INSTALL_PREFIX=${PWD}/compiled_fastdeploy_sdk
              -DENABLE_VISION=ON
              -DOPENCV_DIRECTORY=/usr/lib/x86_64-linux-gnu/cmake/opencv4
              -DENABLE_TEXT=ON
              -DBUILD_PADDLE2ONNX=OFF

**Comment by jiangjiajun** [comment]
删除缓存后再编译哈，传入-DBUILD_PADDLE2ONNX为OFF后，应该是不会触发上面的代码编译流程的。另外我不确认上面的代码是编译warning，还是error

**Comment by FeatherZhong** [comment]
Use linking to solve problem.
`sudo ln -s /usr/bin/python3 /usr/bin/python`

**Comment by caicaicai** [comment]
> Use linking to solve problem. `sudo ln -s /usr/bin/python3 /usr/bin/python`

老哥，你太牛逼了
