### ISSUE TITLE
PPOCR fastdeployserver 解析莫名乱码和Failed to perform CUDA copy

### ISSUE THREAD

**Issue by xlvy** [PaddlePaddle/FastDeploy#1672]
*********************************************
温馨提示：根据社区不完全统计，按照模板提问，可以加快回复和解决问题的速度
*********************************************

## 环境

- 【FastDeploy版本】： docker镜像fastdeploy:1.0.4-gpu-cuda11.4-trt8.5-21.10，使用develop分支
- 【编译命令】）官方部署步骤
- 【系统平台】: Linux x64(Ubuntu 18.04)
- 【硬件】： Nvidia GPU 3090
- 【编译语言】：python3.8

## 问题日志及出现问题的操作流程
- 附上详细的问题日志有助于快速定位分析
按照[](https://github.com/PaddlePaddle/FastDeploy/blob/develop/examples/vision/ocr/PP-OCRv3/serving/README_CN.md)的步骤部署进行服务化部署。示例图片解析成功，在解析几张图片之后，再解析就会偶尔出现如下错误：
![image](https://user-images.githubusercontent.com/51997291/226783055-4124b991-eaf7-4046-9985-b107df3ae12f.png)
但是重新启动fastdeployserver服务后，还是使用出现上述错误的同样的图片解析又成功了。

另外，在出现CUDA_MEMORY警告后
![image](https://user-images.githubusercontent.com/51997291/226785567-f3b2076b-d7ef-454e-bfeb-3e9ca2d9e506.png)
再解析示例图片，会出现
![image](https://user-images.githubusercontent.com/51997291/226785642-fdab129c-b252-4f67-ab13-c60e49471281.png)
部分全英文图片解析会出现乱码
![image](https://user-images.githubusercontent.com/51997291/226786110-fb65fb6e-a28a-4191-9feb-82b95228c665.png)

**Comment by yunyaoXYY** [comment]
后面我复现一下哈. 
顺便能提供一下这个 解析乱码的英文图片吗

**Comment by xlvy** [comment]
@yunyaoXYY 谢谢你的回复。这个英文图片在重启服务后都是能够解析成功的，只是在服务被调用多次后会出现乱码的情况，中文图片和英文图片交替解析。所以应该不是图片的问题
