### ISSUE TITLE
多进程任务报错

### ISSUE THREAD

**Issue by ChaoII** [PaddlePaddle/FastDeploy#168]
fastdeploy人脸识别python部署，采用多进程进行人脸特征提取及人脸比对，实现通过主进程开启摄像头，获取帧，裁剪人脸roi存到Queue中，识别进程从Queue中获取人脸数据最后报错。
核心代码如下：
<img width="624" alt="image" src="https://user-images.githubusercontent.com/44053467/187147584-67e0fd59-ed80-4a98-87f2-f978dcbe4055.png">
报错代码：
[ERROR] csrc/fastdeploy/pybind/main.cc(94)::NumpyDataTypeToOpenCvType	NumpyDataTypeToOpenCvType() only support int32/int8/uint8/float32 now.

ps：目前fastdeploy python不熟不支持多线程么，我尝试多线程处理，速度并没有提升。是不是pybind进行耗时处理的方法绑定中没释放gil？

**Comment by DefTruth** [comment]
能给下复现的示例代码吗？

现在是如果单进程可以跑，但是改成多进程就不行是吗？同时建议也试下在上图中的`predict`前，将`cur_face`打印出来看下数据是否合法

**Comment by ChaoII** [comment]
> 

好的，发您邮箱，麻烦您提供一下邮箱

**Comment by jiangjiajun** [comment]
发到jiangjiajun@baidu.com

**Comment by ChaoII** [comment]
> jiangjiajun@baidu.com

已经发了，麻烦帮忙看下

**Comment by DefTruth** [comment]
您好，请问您的测试环境是什么呢？另外就是，单进程的时候是正常的吗？
- 操作系统/硬件: Windows 10 |  Windows 11 | Linux | Mac OSX Intel | Mac OSX M1 |  ...
- python版本：3.8 | 3.9 | ...
- fastdeploy版本: cpu | gpu 
- 是否为anaconda环境: 是 | 否  
- 详细的报错信息：log

**Comment by ChaoII** [comment]
> 您好，请问您的测试环境是什么呢？另外就是，单进程的时候是正常的吗？
> 
> * 操作系统/硬件: Windows 10 |  Windows 11 | Linux | Mac OSX Intel | Mac OSX M1 |  ...
> * python版本：3.8 | 3.9 | ...
> * fastdeploy版本: cpu | gpu
> * 是否为anaconda环境: 是 | 否

操作系统:MacOS Monterey intel 八代i5
python：3.8
fastdeploy：cpu
anaconda：是
详细报错信息：无（就是最开始的error我看是c++ pybind11 类型判断那里的错误）
单进程正常，但是人脸检测换位scrfd后就报错。
目前python cpu推理支持多线程加速么？（非多进程）

**Comment by DefTruth** [comment]
另外就是人脸检测换成scrfd之后报错的信息是啥呢

**Comment by ChaoII** [comment]
> 另外就是人脸检测换成scrfd之后报错的信息是啥呢

<img width="1146" alt="image" src="https://user-images.githubusercontent.com/44053467/187652989-09e97b6b-b1a4-49cb-8f9b-075acec42b2c.png">

**Comment by DefTruth** [comment]
这个应该是由于你的用模型时不带关键点的，需要设置use_kps=False，以及landmarks_per_face=0
```python
del_model.use_kps=False
del_model.landmarks_per_face=0
```
具体可以参考SCRFD使用文档中的可设置参数说明：  
- [SCRFD使用文档-可设置参数说明](https://github.com/PaddlePaddle/FastDeploy/tree/develop/examples/vision/facedet/scrfd/python#%E9%A2%84%E5%A4%84%E7%90%86%E5%8F%82%E6%95%B0)

**Comment by DefTruth** [comment]
> > 您好，请问您的测试环境是什么呢？另外就是，单进程的时候是正常的吗？
> > 
> > * 操作系统/硬件: Windows 10 |  Windows 11 | Linux | Mac OSX Intel | Mac OSX M1 |  ...
> > * python版本：3.8 | 3.9 | ...
> > * fastdeploy版本: cpu | gpu
> > * 是否为anaconda环境: 是 | 否
> 
> 操作系统:MacOS Monterey intel 八代i5 python：3.8 fastdeploy：cpu anaconda：是 详细报错信息：无（就是最开始的error我看是c++ pybind11 类型判断那里的错误） 单进程正常，但是人脸检测换位scrfd后就报错。 目前python cpu推理支持多线程加速么？（非多进程）

由于python gil的存在，多线程加速可能需要进一步测试下

**Comment by ChaoII** [comment]
> 这个应该是由于你的用模型时不带关键点的，需要设置use_kps=False，以及landmarks_per_face=0
> 
> ```python
> del_model.use_kps=False
> del_model.landmarks_per_face=0
> ```
> 
> 具体可以参考SCRFD使用文档中的可设置参数说明：
> 
> * [SCRFD使用文档-可设置参数说明](https://github.com/PaddlePaddle/FastDeploy/tree/develop/examples/vision/facedet/scrfd/python#%E9%A2%84%E5%A4%84%E7%90%86%E5%8F%82%E6%95%B0)

好的，谢谢！scrfd可以用了

**Comment by AI-Mart** [comment]
fastdeloy目前支持人脸姿态角的检测输出吗？

**Comment by jiangjiajun** [comment]
此ISSUE由于一年未更新，将会关闭处理，如有需要，可再次更新打开。
