### ISSUE TITLE
使用镜像起容器，然后git代码后，跑示例出错

### ISSUE THREAD

**Issue by liuyiche** [PaddlePaddle/FastDeploy#1681]
1、
docker pull registry.baidubce.com/paddlepaddle/fastdeploy:1.0.4-gpu-cuda11.4-trt8.4-21.10
2、
docker run -it --net=host --name fastdeploy --gpus all --shm-size='10g' registry.baidubce.com/paddlepaddle/fastdeploy:1.0.4-gpu-cuda11.4-trt8.5-21.10 /bin/bash

3、
容器内git clone https://github.com/PaddlePaddle/FastDeploy.git

4、之后跑yolov8示例代码，

cpu报错如下：
root@b385c568c32b:/FastDeploy/examples/vision/detection/yolov8/python# python3 infer.py --model yolov8.onnx --image 000000014439.jpg --device cpu
[ERROR] fastdeploy/fastdeploy_model.cc(191)::CreateCpuBackend   Found no valid backend for model: yolov8
[ERROR] fastdeploy/vision/detection/contrib/yolov8/yolov8.cc(40)::Initialize    Failed to initialize fastdeploy backend.
Traceback (most recent call last):
  File "infer.py", line 45, in <module>
    model = fd.vision.detection.YOLOv8(args.model, runtime_option=runtime_option)
  File "/usr/local/lib/python3.8/dist-packages/fastdeploy/vision/detection/contrib/yolov8.py", line 181, in __init__
    assert self.initialized, "YOLOv8 initialize failed."
AssertionError: YOLOv8 initialize failed.

gpu报错如下：
root@b385c568c32b:/FastDeploy/examples/vision/detection/yolov8/python# python3 infer.py --model yolov8.onnx --image 000000014439.jpg --device gpu
[ERROR] fastdeploy/fastdeploy_model.cc(214)::CreateGpuBackend   Cannot find an available gpu backend to load this model.
[ERROR] fastdeploy/vision/detection/contrib/yolov8/yolov8.cc(40)::Initialize    Failed to initialize fastdeploy backend.
Traceback (most recent call last):
  File "infer.py", line 45, in <module>
    model = fd.vision.detection.YOLOv8(args.model, runtime_option=runtime_option)
  File "/usr/local/lib/python3.8/dist-packages/fastdeploy/vision/detection/contrib/yolov8.py", line 181, in __init__
    assert self.initialized, "YOLOv8 initialize failed."
AssertionError: YOLOv8 initialize failed.

**Comment by DefTruth** [comment]
请问用的fastdeploy是安装的哪个版本呢？

**Comment by liuyiche** [comment]
> 请问用的fastdeploy是安装的哪个版本呢？

docker pull registry.baidubce.com/paddlepaddle/fastdeploy:1.0.4-gpu-cuda11.4-trt8.4-21.10
直接拉的这个镜像，1.0.4和1.0.3都试了

**Comment by liuyiche** [comment]
> /FastDeploy/examples/vision/detection/yolov8/python# python3 infer.py --model yolov8.onnx --image 000000014439.jpg --device cpu



> 请问用的fastdeploy是安装的哪个版本呢？

示例代码就是按这个跑的：
https://github.com/PaddlePaddle/FastDeploy/tree/develop/examples/vision/detection/yolov8/python

**Comment by fanruifeng** [comment]
解决了嘛 老哥 我现在问题也是和你一模一样

**Comment by fanruifeng** [comment]
是环境问题还是别的原因呢

**Comment by heliqi** [comment]
拉最新1.0.5的镜像还有问题吗？

**Comment by xzk-seu** [comment]
遇到一样的问题了，有没有好心人解答一下
