### ISSUE TITLE
Fastdeploy二次开发推理报段错误

### ISSUE THREAD

**Issue by pangchao-git** [PaddlePaddle/FastDeploy#1685]
*********************************************
温馨提示：根据社区不完全统计，按照模板提问，可以加快回复和解决问题的速度
*********************************************

## 环境

- 【FastDeploy版本】：fastdeploy-linux-x64-gpu-1.0.4/
- 【编译命令】如果您是自行编译的FastDeploy，请说明您的编译方式（参数命令）
- 【系统平台】:CentOS Linux release 7.9.2009 (Core) x86
- 【硬件】：Nvidia GPU Tesla P4， CUDA 11.2 CUDNN 8.3
- 【编译语言】： C++ gcc 8.2

## 问题日志及出现问题的操作流程
1 操作步骤
按照fastdeploy的sdk中ppocr的sample配置好cmakelists,正常运行没问题，后面自己修改代码，将代码封装成初始化，检测接口时候，在其他函数调用detect就会报段错误，麻烦工程师看看是哪里的问题
[test_ocr.tar.gz](https://github.com/PaddlePaddle/FastDeploy/files/11046076/test_ocr.tar.gz)

**Comment by DefTruth** [comment]
我们先具体看下哈，方便贴一些具体的报错信息吗？

**Comment by pangchao-git** [comment]
> 我们先具体看下哈，方便贴一些具体的报错信息吗？

![图片](https://user-images.githubusercontent.com/59760495/227121425-4d47e6ca-3d2e-45b6-9d35-3db340b2e49d.png)
具体是这个报错

**Comment by pangchao-git** [comment]
这个问题有啥结论么,啥原因?
