### ISSUE TITLE
yolov8 rknn 部署

### ISSUE THREAD

**Issue by zhu709654396** [PaddlePaddle/FastDeploy#1692]
可以使用yolov8官网模型转rknn然后部署吗

**Comment by Zheng-Bicheng** [comment]
暂时不行哦，已经在和Rockchip那边对了，后面会把他们优化过的YOLOv8移植过来

**Comment by zhu709654396** [comment]
其实我更想知道官方 yolov8 为啥不能转 rknn 部署



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年3月25日(周六) 凌晨0:01
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [PaddlePaddle/FastDeploy] yolov8 rknn 部署 (Issue #1692)




 
暂时不行哦，已经在和Rockchip那边对了，后面会把他们优化过的YOLOv8移植过来

**Comment by Zheng-Bicheng** [comment]
官方的yolov8有个算子rknn 不支持

**Comment by zhu709654396** [comment]
但是我昨天转成功 rknn 了，并且在模拟器跑通了



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年3月25日(周六) 上午8:19
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [PaddlePaddle/FastDeploy] yolov8 rknn 部署 (Issue #1692)




 
官方的yolov8有个算子rknn 不支持

**Comment by Zheng-Bicheng** [comment]
板端会有问题

**Comment by zhu709654396** [comment]
好的



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年3月25日(周六) 上午8:57
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [PaddlePaddle/FastDeploy] yolov8 rknn 部署 (Issue #1692)




 
板端会有问题

**Comment by ilbash** [comment]
Hello, @Zheng-Bicheng @zhu709654396 ! Did you solve the problem with PaddleYolov8 to RKNN?
