### ISSUE TITLE
jetson orin上如何部署fastdeploy?模型初始化失败

### ISSUE THREAD

**Issue by cunjing56** [PaddlePaddle/FastDeploy#1694]
我现在用jetson orin agx, 已经刷上jetpack 5.1, 参考jetson 编译fd并安装。https://github.com/PaddlePaddle/FastDeploy/blob/develop/docs/cn/build_and_install/jetson.md

![image](https://user-images.githubusercontent.com/112528302/229712623-85e57089-ba6f-4a70-8cf4-ba45c50abc75.png)
![image](https://user-images.githubusercontent.com/112528302/229712766-3962486b-408c-46e6-8d93-67688ebd4dc7.png)

尝试部署失败
![image](https://user-images.githubusercontent.com/112528302/229712846-25399438-42d4-4e6a-90f6-713f6815e6ce.png)

模型调用代码如下：
import fastdeploy as fd
import cv2
import os
model_path = "rice_frcnn"
model_file = os.path.join(model_path, "model.pdmodel")
params_file = os.path.join(model_path, "model.pdiparams")
infer_cfg_file = os.path.join(model_path, "infer_cfg.yml")

option = fd.RuntimeOption()
option.use_gpu()

model = fd.vision.detection.FasterRCNN(model_file, params_file, infer_cfg_file, option)

im = cv2.imread("image/uva0005.jpg")

result = model.predict(im)
print(result)

**Comment by DefTruth** [comment]
这个模型暂时还不支持ORT推理。
```c++
class FASTDEPLOY_DECL FasterRCNN : public PPDetBase {
 public:
  FasterRCNN(const std::string& model_file, const std::string& params_file,
             const std::string& config_file,
             const RuntimeOption& custom_option = RuntimeOption(),
             const ModelFormat& model_format = ModelFormat::PADDLE)
      : PPDetBase(model_file, params_file, config_file, custom_option,
                  model_format) {
    valid_cpu_backends = {Backend::PDINFER, Backend::LITE};
    valid_gpu_backends = {Backend::PDINFER};
    valid_kunlunxin_backends = {Backend::LITE};
    initialized = Initialize();
  }
```
目前只支持paddle和paddle lite

**Comment by cunjing56** [comment]
> ORT推理

什么叫ort推理，安装fastdeploy的时候说目前不支持paddle inference后端，tensorrt也不行，不应该还剩个onnx吗，你这里说的paddle 和paddle lite是什么？我没开tensorrt 用的gpu也不行啊
![image](https://user-images.githubusercontent.com/112528302/229796205-b6aefa1f-5fe9-4e50-836d-7a5241921366.png)
![image](https://user-images.githubusercontent.com/112528302/229796700-d557af1a-33f0-4d29-a909-419fc83e5c57.png)
![image](https://user-images.githubusercontent.com/112528302/229796979-1ce922eb-5bcd-4453-bc1d-36378217bee6.png)

**Comment by cunjing56** [comment]
> 这个模型暂时还不支持ORT推理。
> 
> ```c++
> class FASTDEPLOY_DECL FasterRCNN : public PPDetBase {
>  public:
>   FasterRCNN(const std::string& model_file, const std::string& params_file,
>              const std::string& config_file,
>              const RuntimeOption& custom_option = RuntimeOption(),
>              const ModelFormat& model_format = ModelFormat::PADDLE)
>       : PPDetBase(model_file, params_file, config_file, custom_option,
>                   model_format) {
>     valid_cpu_backends = {Backend::PDINFER, Backend::LITE};
>     valid_gpu_backends = {Backend::PDINFER};
>     valid_kunlunxin_backends = {Backend::LITE};
>     initialized = Initialize();
>   }
> ```
> 
> 目前只支持paddle和paddle lite

可以回复我，用哪个模型能在jetson orin上运行吗？开gpu跟tensorRT的。
此外，fastdeploy编译需要开enable_trt_backend, with_gpu, cuda_directory, trt_directory, opencv_directory这些吗？
谢谢您的回复，我已经部署两周多了，还没搞好。。

**Comment by leiqing1** [comment]
能支持在GPU上跑的后端有Paddle Inference、TensorRT、ONNX Runtime(ort)，这个模型也可以切换其他后端跑。
可以尝试yolo系列在Jetson上。

**Comment by cunjing56** [comment]
> 

我重新训练了yolov5, 也导出成onnx了---看着fd的文档说yolov5需要使用onnx格式的模型。现在开始部署。我连在win, linux 的gpu, cpu环境都跑不了了。
在linux gpu pd镜像下训练，导出的环境里安装了Successfully installed asgiref-3.6.0 fastdeploy-gpu-python-1.0.5 fastdeploy-tools-0.0.5 uvicorn-0.16.0
然后运行fd代码失败。
![image](https://user-images.githubusercontent.com/112528302/230535641-e8e7797e-67fd-4e15-add5-64c1fa973858.png)

yolov5代码

import fastdeploy as fd
import os
from PIL import Image
model_file = os.path.join("yolov5", "yolov5.onnx")
YOLOv5 = fd.vision.detection.YOLOv5(model_file, params_file=None, runtime_option=None, model_format=fd.ModelFormat.ONNX)
image_data = Image.open(r"image/uva0006.jpg")
result = YOLOv5.predict(image_data, conf_threshold=0.25, nms_iou_threshold=0.5)

print(result.boxes)
