### ISSUE TITLE
rk3588  PP_LiteSeg_T_STDC1_cityscapes_without_argmax_infer 没分割出效果

### ISSUE THREAD

**Issue by jiangq195** [PaddlePaddle/FastDeploy#1697]
链接: https://pan.baidu.com/s/1_Vwb-zpgfOhVSmurRW4uxA?pwd=vkww 提取码: vkww 
--来自百度网盘超级会员v5的分享

能帮我跑不跑吗，看看是不是我模型转换的问题，采用的官方pbmodel-onnx-rknn

**Comment by Zheng-Bicheng** [comment]
我这两天看看哈

**Comment by Zheng-Bicheng** [comment]
你的Python能编译了吗？

* https://github.com/PaddlePaddle/FastDeploy/issues/1676
