### ISSUE TITLE
部署ernie模型报错

### ISSUE THREAD

**Issue by LouisHeck** [PaddlePaddle/FastDeploy#1704]
*********************************************
按照ernie-3.0部署案例，下载提供的模型和参数，执行命令。fastdeplpyserver服务端可以启动。客户端调用报错。
*********************************************

## 环境

- 【FastDeploy版本】： 1.0.4
- 【编译命令】# 进入serving目录执行脚本编译fastdeploy和服务化的backend
        cd serving
        bash scripts/build_fd_cuda_11_2.sh
        
        # 退出到FastDeploy主目录，制作镜像
        cd ../
        docker build -t paddlepaddle/fastdeploy:1.0.3-gpu-cuda11.2-trt8.4-21.10 -f serving/Dockerfile_CUDA_11_2 .
- 【系统平台】: Linux x64(Ubuntu 20.04) 
- 【硬件】： Nvidia GPU 3080TI， CUDA 11.2 CUDNN 8.3
- 【编译语言】： C++ / Python(3.7或3.8等）

## 问题日志及出现问题的操作流程
- 按照ernie-3.0部署案例，下载提供的模型和参数，执行命令。fastdeplpyserver服务端可以启动。客户端调用报错。
- 【模型跑不通】
- - 先执行`examples`下的部署示例，包括使用examples提供的模型，服务端可以启动。客户端调用报错。
- -服务端启动截图如下：
-`I0325 00:58:57.080611 1493 grpc_server.cc:4117] Started GRPCInferenceService at 0.0.0.0:8001
I0325 00:58:57.080752 1493 http_server.cc:2815] Started HTTPService at 0.0.0.0:8000
I0325 00:58:57.121637 1493 http_server.cc:167] Started Metrics Service at 0.0.0.0:8002`
![1679706012207](https://user-images.githubusercontent.com/38588261/227671560-d2d72c20-c58f-4ba1-94cf-dda3c8ac193b.png)
![1679706041246](https://user-images.githubusercontent.com/38588261/227671671-ed45c607-3256-4321-898b-7f61169fd387.png)

- -客户端请求截图报错如下：
`Traceback (most recent call last):
  File "seq_cls_grpc_client.py", line 146, in <module>
    result = runner.Run([text])
  File "seq_cls_grpc_client.py", line 85, in Run
    results = self._client.infer(
  File "/usr/local/lib/python3.8/dist-packages/tritonclient/grpc/__init__.py", line 1446, in infer
    raise_error_grpc(rpc_error)
  File "/usr/local/lib/python3.8/dist-packages/tritonclient/grpc/__init__.py", line 76, in raise_error_grpc
    raise get_error_grpc(rpc_error) from None
tritonclient.utils.InferenceServerException: [StatusCode.UNAVAILABLE] Socket closed
`
![1679706094760](https://user-images.githubusercontent.com/38588261/227671901-7b78ca4b-750d-4364-b15d-1d454838f7f3.png)

- -客户端请求时，服务端截图报错如下：
- `I0325 00:58:57.080611 1493 grpc_server.cc:4117] Started GRPCInferenceService at 0.0.0.0:8001
I0325 00:58:57.080752 1493 http_server.cc:2815] Started HTTPService at 0.0.0.0:8000
I0325 00:58:57.121637 1493 http_server.cc:167] Started Metrics Service at 0.0.0.0:8002
terminate called after throwing an instance of 'ov::Exception'
  what():  Using Blob on external nullptr memory
Signal (6) received.
 0# 0x000055D6A915E3A9 in fastdeployserver
 1# 0x00007F32FEF13090 in /usr/lib/x86_64-linux-gnu/libc.so.6
 2# gsignal in /usr/lib/x86_64-linux-gnu/libc.so.6
 3# abort in /usr/lib/x86_64-linux-gnu/libc.so.6
 4# 0x00007F32FF2CC911 in /usr/lib/x86_64-linux-gnu/libstdc++.so.6
 5# 0x00007F32FF2D838C in /usr/lib/x86_64-linux-gnu/libstdc++.so.6
 6# 0x00007F32FF2D83F7 in /usr/lib/x86_64-linux-gnu/libstdc++.so.6
 7# 0x00007F32FF2D86A9 in /usr/lib/x86_64-linux-gnu/libstdc++.so.6
 8# 0x00007F32D10CEF8F in /opt/fastdeploy/third_libs/install/openvino/runtime/lib/libopenvino.so
 9# fastdeploy::OpenVINOBackend::Infer(std::vector<fastdeploy::FDTensor, std::allocator<fastdeploy::FDTensor> >&, std::vector<fastdeploy::FDTensor, std::allocator<fastdeploy::FDTensor> >*, bool) in /opt/fastdeploy/lib/libfastdeploy_runtime.so.1.0.4
10# fastdeploy::Runtime::Infer() in /opt/fastdeploy/lib/libfastdeploy_runtime.so.1.0.4
11# 0x00007F32FC051BC4 in /opt/tritonserver/backends/fastdeploy/libtriton_fastdeploy.so
12# 0x00007F32FC055456 in /opt/tritonserver/backends/fastdeploy/libtriton_fastdeploy.so
13# TRITONBACKEND_ModelInstanceExecute in /opt/tritonserver/backends/fastdeploy/libtriton_fastdeploy.so
14# 0x00007F32FFA0801A in /opt/tritonserver/bin/../lib/libtritonserver.so
15# 0x00007F32FFA0882D in /opt/tritonserver/bin/../lib/libtritonserver.so
16# 0x00007F32FF8C2F91 in /opt/tritonserver/bin/../lib/libtritonserver.so
17# 0x00007F32FFA025A7 in /opt/tritonserver/bin/../lib/libtritonserver.so
18# 0x00007F32FF304DE4 in /usr/lib/x86_64-linux-gnu/libstdc++.so.6
19# 0x00007F32FF782609 in /usr/lib/x86_64-linux-gnu/libpthread.so.0
20# clone in /usr/lib/x86_64-linux-gnu/libc.so.6

Aborted (core dumped)
0325 01:00:59.617412 1551 pb_stub.cc:777] Non-graceful termination detected. 0325 01:00:59.617415 1505 pb_stub.cc:777] Non-graceful termination detected. root@2b3149713bf0:/home/FastDeploy/examples/text/ernie-3.0/serving# 
`
![1679706164656](https://user-images.githubusercontent.com/38588261/227672218-b569017b-5ee9-4fd8-b286-be809f972139.png)
这个是什么原因？该怎么解决

**Comment by ted8201** [comment]
How did you solved this? really appreciate your response.

**Comment by huangjun11** [comment]
你好，请问你的问题最后解决了吗
