### ISSUE TITLE
不支持yolov5模型的openvino加速吗？

### ISSUE THREAD

**Issue by kankanjiuzou123** [PaddlePaddle/FastDeploy#1707]
如题，trt加速没问题，想在cpu设备中部署，openvino是不能用么？

**Comment by DefTruth** [comment]
fd支持openvino加速，请问是具体报什么错误呢?

**Comment by kankanjiuzou123** [comment]
> fd支持openvino加速，请问是具体报什么错误呢?

就是显示不支持openvino的初始化，[ERROR] fastdeploy/fastdeploy_model.cc(144)::InitRuntimeWithSpecifiedBackend    The valid cpu backends of model yolov5 are [ Backend::PDINFER ,Backend::ORT ,Backend::PDLITE ], Backend::OPENVINO is not supported.

**Comment by kankanjiuzou123** [comment]
是我哪里搞错了么

**Comment by DefTruth** [comment]
这是我们先前在测试后端覆盖率的时候，对各个模型能跑通的后端做的一个限制，集成YOLOv5的时候，OV后端还没有接入。您可以通过RuntimeOption来取消这个后端覆盖检查。  
```c++
option.DisableValidBackendCheck();
```

**Comment by kankanjiuzou123** [comment]
> 这是我们先前在测试后端覆盖率的时候，对各个模型能跑通的后端做的一个限制，集成YOLOv5的时候，OV后端还没有接入。您可以通过RuntimeOption来取消这个后端覆盖检查。
> 
> ```c++
> option.DisableValidBackendCheck();
> ```
好的，我试一下，感谢！

**Comment by kankanjiuzou123** [comment]
> 这是我们先前在测试后端覆盖率的时候，对各个模型能跑通的后端做的一个限制，集成YOLOv5的时候，OV后端还没有接入。您可以通过RuntimeOption来取消这个后端覆盖检查。
> 
> ```c++
> option.DisableValidBackendCheck();
> ```

AttributeError: 'RuntimeOption' object has no attribute 'DisableValidBackendCheck'，python接口没这个么

**Comment by kankanjiuzou123** [comment]
刚试了下picodet是支持的
