### ISSUE TITLE
在cpu端部署目标检测模型，实时检测并且cpu占用不那么高，推荐哪个模型？

### ISSUE THREAD

**Issue by kankanjiuzou123** [PaddlePaddle/FastDeploy#1708]
fastdeploy目前支持的目标检测模型，哪一个符合在cpu端占用率不那么高，并且能实时检测呢？支持trt的测试过了，效果不错，就是部署在cpu端占用率太高了。。

**Comment by DefTruth** [comment]
picodet可以尝试下

**Comment by kankanjiuzou123** [comment]
> picodet可以尝试下
好的。多谢！
