### ISSUE TITLE
多线程模式 VS2019 Release X64 编译  提示错误：std::invoke”: 未找到匹配的重载函数

### ISSUE THREAD

**Issue by xzxjysgd** [PaddlePaddle/FastDeploy#1709]
## 环境
WIN10 VS2019
- 【FastDeploy版本】： 如fastdeploy-linux-gpu-1.0.4
- 【编译命令】VS2019  Release X64
- 【系统平台】:  Windows x64(Windows10) / Mac OSX arm(12.0) / Mac OSX intel(12.0)
- 【硬件】： Nvidia GPU 1660TI， CUDA 11.2 CUDNN 8
- 【编译语言】： C++ 

## 问题
我参考c++ 多线程模式示例代码 如下所示   在 VS2019 Release X64 编译
编译提示两个错误：
 C2672“std::invoke”: 未找到匹配的重载函数
 C2893	未能使函数模板“unknown-type std::invoke(_Callable &&,_Types &&...) noexcept(<expr>)”专用化
这两个错误 应该均与：语句  
     void Predict(fastdeploy::vision::detection::YOLOv7End2EndTRT* model, int thread_id) 
和 threads.emplace_back(Predict, models[i].get(), i); 有关 ； model的类型不对么？
我该怎么做呢？
另外：auto model = fastdeploy::vision::detection::YOLOv7End2EndTRT(model_file, "", option);中
model的具体类型是什么呢，实例代码不用auto这种 对我们用户而言会更好。

谢谢   期待您的回答！

代码：
```c++
void Predict(fastdeploy::vision::detection::YOLOv7End2EndTRT* model, int thread_id) {
    auto im = cv::imread("D:\\images\\1.bmp");
    fastdeploy::vision::DetectionResult res;
    if (!model->Predict(&im, &res)) {
        std::cerr << "Failed to predict." << std::endl;
        return;
    }
    // print res
    std::cout << "Thread Id: " << thread_id << std::endl;
    std::cout << res.Str() << std::endl;
}


void TrtInfer(const std::string& model_file, int thread_num) {
    std::string cachefile = model_file.substr(0, model_file.find_last_of("\\/")) + "/yolov7x.trt";
    auto option = fastdeploy::RuntimeOption();
    option.UseGpu();
    option.UseTrtBackend();
    option.SetTrtCacheFile(cachefile);
    option.SetTrtInputShape("images", { 1, 3, 640, 640 });
    auto model = fastdeploy::vision::detection::YOLOv7End2EndTRT(model_file, "", option);
    if (!model.Initialized()) {
        std::cerr << "Failed to initialize." << std::endl;
        return;
    }
    std::vector<decltype(model.Clone())> models;
    for (int i = 0; i < thread_num; ++i) {
        models.emplace_back(std::move(model.Clone()));
    }
    std::vector<std::thread> threads;
    for (int i = 0; i < thread_num; ++i) {
        threads.emplace_back(Predict, models[i].get(), i); 
       //std::thread thread(Predict,  models[i].get(), i); 
    }
    for (int i = 0; i < thread_num; ++i) {
        threads[i].join();
    }
}

int main(int argc, char** argv) {   
    TrtInfer("D:\\best.onnx", 2);        
    return 0;
}
```

**Comment by jiangjiajun** [comment]
这一行代码`auto model = fastdeploy::vision::detection::YOLOv7End2EndTRT(model_file, "", option);`可以改成
`fastdeploy::vision::detection::YOLOv7End2EndTRT model(model_file, "", option);`

上面的invoke错误无法判断，推测可能`std::vector<decltype`那行代码的问题

**Comment by xzxjysgd** [comment]
按照您的方法： 将这一行代码auto model = fastdeploy::vision::detection::YOLOv7End2EndTRT(model_file, "", option);改成
fastdeploy::vision::detection::YOLOv7End2EndTRT model(model_file, "", option);
编译结果依旧是：  C2672“std::invoke”: 未找到匹配的重载函数
真的不知该怎么办：   
另外 请考虑 例如 我要做个接口 dll  我常常会把 
把上面的 fastdeploy::vision::detection::YOLOv7End2EndTRT model  或者 *model
或者  std::vector<decltype(model.Clone())> models;   声明为全局 但目前似乎也行不通

期待解决办法

**Comment by xzxjysgd** [comment]
另外我曾试过   
用              std::vector<std::unique_ptr<fastdeploy::vision::detection::YOLOv7End2EndTRT>> models;
或者用       std::vector<std::unique_ptr<fastdeploy::FastDeployModel>> models;   
将models声明为全局，但都不能编译成功  大致也是  C2672“std::invoke”: 未找到匹配的重载函数

针对YOLOv7End2EndTRT   很希望 得到  将 models 声明为全局的办法。
