### ISSUE TITLE
分类模型得出的结果python是什么类型？

### ISSUE THREAD

**Issue by intjun** [PaddlePaddle/FastDeploy#1715]
ClassifyResult(
label_ids: 153, 204, 
scores: 0.686230, 0.095325, 
)
如上，python需要怎么解析这个结果？字典还是数组？

**Comment by jiangjiajun** [comment]
可以查阅下API文档
<img width="849" alt="image" src="https://user-images.githubusercontent.com/19339784/227970136-55948820-72b1-4174-babe-8470dfacc6e1.png">

**Comment by intjun** [comment]
> 可以查阅下API文档 <img alt="image" width="849" src="https://user-images.githubusercontent.com/19339784/227970136-55948820-72b1-4174-babe-8470dfacc6e1.png">

好的，谢谢！已解决。是它的一个变量，label=result.label_ids就可以读取
