### ISSUE TITLE
intel 显卡 能部署检测不

### ISSUE THREAD

**Issue by monkeycc** [PaddlePaddle/FastDeploy#1725]
intel  Arc A380
Intel  Arc A750 

intel 显卡 能部署检测不
想入手intel 显卡

**Comment by DefTruth** [comment]
支持，可以参考文档：  
- https://github.com/PaddlePaddle/FastDeploy/blob/develop/tutorials/intel_gpu/README_CN.md

**Comment by junruizh2021** [comment]
> 支持，可以参考文档：
> 
> * https://github.com/PaddlePaddle/FastDeploy/blob/develop/tutorials/intel_gpu/README_CN.md

@DefTruth 你好，FastDeploy预编译安装文档里好像只支持CUDA，Intel Arc GPU应该怎么预编译呢？

https://github.com/PaddlePaddle/FastDeploy/blob/develop/docs/cn/build_and_install/download_prebuilt_libraries.md
