### ISSUE TITLE
default cuda directory does not exists

### ISSUE THREAD

**Issue by WanderAlphonse** [PaddlePaddle/FastDeploy#1727]
--- FastDeploy was built with gpu,                     
--- but the default cuda directory does not exists.                     
--- Please setup one of ['CUDA_DIRECTORY', 'CUDA_HOME', 'CUDA_ROOT', 'CUDA_PATH'] manually,                     
--- this path should look like: C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v11.2.                     
--- Check FAQ: https://github.com/PaddlePaddle/FastDeploy/blob/develop/docs/FAQ.md(这个文件不存在)
  logging.warnings.warn(f"\n--- FastDeploy was built with gpu, \

CUDA_HOME文件夹应该设置在哪个位置？

**Comment by DefTruth** [comment]
请问您使用的是操作系统、CUDA版本、以及fastdeploy的库版本分别是什么呢？

**Comment by WanderAlphonse** [comment]
> 请问您使用的是操作系统、CUDA版本、以及fastdeploy的库版本分别是什么呢？

操作系统：win11
cuda版本：12.0
fastdeploy版本：我调用fastdeploy.__version__查看版本任然会报上面的错误，所以我无法知道版本，但我是最近两天安装的fastdeploy，所以应该是最新版
