### ISSUE TITLE
使用你们的demo 交叉编译（infer_ppyoloe.cc），目标平台bm1684，在目标平台运行报错 Illegal instruction

### ISSUE THREAD

**Issue by XiaBing992** [PaddlePaddle/FastDeploy#1729]
## 环境

- 【系统平台】: Linux x64(Ubuntu 20.04) 
- 【编译语言】： C++
- 【目标平台】：算丰bm1684

**Comment by DefTruth** [comment]
你好，请问可以提供下报错信息和复现流程吗？

**Comment by XiaBing992** [comment]
> 你好，请问可以提供下报错信息和复现流程吗？

void SophgoInfer(const std::string& model_dir, const std::string& image_file) {
  auto model_file = model_dir + "/ppyoloe_crn_s_300e_coco_1684x_f32.bmodel";
  auto params_file = "";
  auto config_file = model_dir + "/infer_cfg.yml";

  auto option = fastdeploy::RuntimeOption();
  option.UseSophgo();

  auto format = fastdeploy::ModelFormat::SOPHGO;

  auto model = fastdeploy::vision::detection::PPYOLOE(
      model_file, params_file, config_file, option, format);

  model.GetPostprocessor().ApplyNMS();

  auto im = cv::imread(image_file);

  fastdeploy::vision::DetectionResult res;
  if (!model.Predict(&im, &res)) {
    std::cerr << "Failed to predict." << std::endl;
    return;
  }



经过我的测试，是加载模型这句话导致的非法指令错误：
  auto model = fastdeploy::vision::detection::PPYOLOE(
      model_file, params_file, config_file, option, format);
你们的demo代码我只改了：
 model.GetPostprocessor().ApplyNMS();
你们之前的代码用的是：
model.GetPostprocessor().ApplyDecodeAndNMS();
但是我查看了你们的接口，根本就没有这个接口，我觉得是你们官方代码有问题

算丰平台运行报错信息：
Illegal instruction

**Comment by XiaBing992** [comment]
另外我想问下模型加载时/infer_cfg.yml 是个什么文件，我在文档并没有看到描述

**Comment by DefTruth** [comment]
是的，最新的接口需要改成：ApplyNMS();
infer_cfg.yml 是paddle套件导出模型时带的预处理config文件，在FD中需要用到

**Comment by XiaBing992** [comment]
> 是的，最新的接口需要改成：ApplyNMS();
> infer_cfg.yml 是paddle套件导出模型时带的预处理config文件，在FD中需要用到

非法指令有方法解决吗

**Comment by Yi-sir** [comment]
> > 是的，最新的接口需要改成：ApplyNMS();
> > infer_cfg.yml 是paddle套件导出模型时带的预处理config文件，在FD中需要用到
> 
> 非法指令有方法解决吗

您好，使用TPU-MLIR工具编译得到的bmodel不支持bm1684平台，您可以尝试使用TPU-NNTC进行编译
