### ISSUE TITLE
FastDeploy无法正常部署

### ISSUE THREAD

**Issue by bxjxxyy** [PaddlePaddle/FastDeploy#1735]
*********************************************
温馨提示：根据社区不完全统计，按照模板提问，可以加快回复和解决问题的速度
*********************************************

## 环境
- 【系统平台】: Linux x64(Ubuntu 20.04) 
- 【硬件】： 说明具体硬件型号，8核16G 
- 【编译语言】：  Python 3.8
- 根据文档https://github.com/PaddlePaddle/FastDeploy/tree/develop/examples/vision/ocr/PP-OCR/serving/fastdeploy_serving
没有使用docker
安装paddle
pip install paddlepaddle==2.4.2 -i https://pypi.tuna.tsinghua.edu.cn/simple
安装fastdeploy
pip install fastdeploy-python==1.0.4
获取FastDeploy仓库
git clone https://github.com/PaddlePaddle/FastDeploy.git
解决libgl1.so报错
apt-get install libgl1
直接执行正常
```
root@iZbp19wu4707e6xaoyzx3gZ:~/FastDeploy/examples/vision/ocr/PP-OCR/cpu-gpu/python# python3 infer.py --det_model ch_PP-OCRv3_det_infer --cls_model ch_ppocr_mobile_v2.0_cls_infer --rec_model ch_PP-OCRv3_rec_infer --rec_label_file ppocr_keys_v1.txt --image 12.jpg --device cpu --backend paddle
WARNING: Logging before InitGoogleLogging() is written to STDERR
W0329 13:51:06.211759 11016 analysis_config.cc:972] It is detected that mkldnn and memory_optimize_pass are enabled at the same time, but they are not supported yet. Currently, memory_optimize_pass is explicitly disabled
[INFO] fastdeploy/runtime/runtime.cc(309)::CreatePaddleBackend  Runtime initialized with Backend::PDINFER in Device::CPU.
[INFO] fastdeploy/runtime/runtime.cc(309)::CreatePaddleBackend  Runtime initialized with Backend::PDINFER in Device::CPU.
[INFO] fastdeploy/runtime/runtime.cc(309)::CreatePaddleBackend  Runtime initialized with Backend::PDINFER in Device::CPU.
det boxes: [[42,413],[483,391],[484,428],[43,450]]rec text: 上海斯格威铂尔大酒店 rec score:0.980085 cls label: 0 cls score: 1.000000
det boxes: [[187,456],[399,448],[400,480],[188,488]]rec text: 打浦路15号 rec score:0.964993 cls label: 0 cls score: 1.000000
det boxes: [[23,507],[513,488],[515,529],[24,548]]rec text: 绿洲仕格维花园公寓 rec score:0.993727 cls label: 0 cls score: 1.000000
det boxes: [[74,553],[427,542],[428,571],[75,582]]rec text: 打浦路252935号 rec score:0.947723 cls label: 0 cls score: 1.000000
```

## 问题日志及出现问题的操作流程
尝试启动服务执行```fastdeployserver --model-repository=/ocr_serving/models```
会报错```fastdeployserver: command not found```

如果使用visualdl配置，启动服务时会报错
![image](https://user-images.githubusercontent.com/26214176/228442207-e1cf58bd-e22e-42ac-8376-3382e75dec19.png)

**Comment by rainyfly** [comment]
这个功能需要用fastdeployserver命令，这个命令是开启一个服务器。想要使用这个命令，需要在fastdeploy提供的镜像里进行使用，可以按照文档使用FastDeploy提供的镜像哈，https://github.com/PaddlePaddle/FastDeploy/tree/develop/examples/vision/detection/yolov5/serving 比如参考这个文档，使用docker pull可以拉下镜像，里面有打包好这个服务器的命令

**Comment by bxjxxyy** [comment]
> 这个功能需要用fastdeployserver命令，这个命令是开启一个服务器。想要使用这个命令，需要在fastdeploy提供的镜像里进行使用，可以按照文档使用FastDeploy提供的镜像哈，https://github.com/PaddlePaddle/FastDeploy/tree/develop/examples/vision/detection/yolov5/serving 比如参考这个文档，使用docker pull可以拉下镜像，里面有打包好这个服务器的命令

主要是不想使用docker，docker配置mkldnn有点太麻烦了，怕配置的不对
