### ISSUE TITLE
 自己编译的时候报错：Paddle Backend doesn't support linux aarch64 now. 

### ISSUE THREAD

**Issue by aixuedegege** [PaddlePaddle/FastDeploy#1743]
*********************************************
温馨提示：根据社区不完全统计，按照模板提问，可以加快回复和解决问题的速度
*********************************************

## 环境

- 【FastDeploy版本】： [说明具体的版本，拉的最新的代码]使用下面的命令进行c++编译：(https://github.com/PaddlePaddle/FastDeploy/blob/develop/docs/cn/build_and_install/cpu.md)
- 【编译命令】
```bash
git clone https://github.com/PaddlePaddle/FastDeploy.git
cd FastDeploy
mkdir build && cd build
cmake .. -DENABLE_ORT_BACKEND=ON \
         -DENABLE_PADDLE_BACKEND=ON \
         -DENABLE_OPENVINO_BACKEND=ON \
         -DCMAKE_INSTALL_PREFIX=${PWD}/compiled_fastdeploy_sdk \
         -DENABLE_VISION=ON \
         -DOPENCV_DIRECTORY=/usr/lib/x86_64-linux-gnu/cmake/opencv4 \
         -DENABLE_TEXT=ON
make -j12
make install
```
- 【系统平台】:  Linux localhost.localdomain 4.19.90-24.4.v2101.ky10.aarch64 #1 SMP Mon May 24 14:45:37 CST 2021 aarch64 aarch64 aarch64 GNU/Linux
- 【硬件】： 说明具体硬件型号，kunpeng 920
- 【编译语言】： gcc(7.3.0) / Python(3.7.4）

请问如何用fastdeploy安装在kunpeng920 cpu上，如果paddle backend不支持，可以支持onnx么？仅用fastdeploy的onnx backend如何自己编译？

**Comment by DefTruth** [comment]
aarch64暂时不支持paddle后端，可以关掉编译选项： 
```bash 
-DENABLE_PADDLE_BACKEND=OFF
```

**Comment by aixuedegege** [comment]
好的 谢谢
