### ISSUE TITLE
GPU版本  FastDeploy simple_serving部署启动失败( initalized failed )

### ISSUE THREAD

**Issue by kerry-weic** [PaddlePaddle/FastDeploy#1747]
环境信息:centos7(64)、python3.8、CUDA 11.7、cuDNN 8.4.1、NVIDIA RTX A4000（gpu）、cmake 3.18.0
目标为部署ocr的推理服务，总体参考流程:https://github.com/PaddlePaddle/PaddleOCR/tree/dygraph/deploy/fastdeploy/serving/simple_serving#paddleocr-python%E8%BD%BB%E9%87%8F%E6%9C%8D%E5%8A%A1%E5%8C%96%E9%83%A8%E7%BD%B2%E7%A4%BA%E4%BE%8B
尝试使用自编译和官方提供预编译fastdeploy-gpu-python启动推理服务均失败。
自编译参考文档流程:https://github.com/PaddlePaddle/FastDeploy/blob/develop/docs/cn/build_and_install/gpu.md#python%E7%BC%96%E8%AF%91%E5%AE%89%E8%A3%85
编译后的版本信息: 
![image](https://user-images.githubusercontent.com/49382323/228808202-089d0751-f1e8-4a3e-aeb6-fd089aac9956.png)
启动报错日志如下:
![image](https://user-images.githubusercontent.com/49382323/228998227-ed6939c4-b4b6-4a60-ab88-abdfae87b71c.png)

使用官方预编译版本:pip3 install fastdeploy-gpu-python -f https://www.paddlepaddle.org.cn/whl/fastdeploy.html
编译后的版本信息: 
![image](https://user-images.githubusercontent.com/49382323/228809565-9c45c979-a7b4-4376-9180-dc7d782a1cd8.png)
启动报错日志如下:
![image](https://user-images.githubusercontent.com/49382323/228809202-aaf1fb68-5e89-40d1-937b-0d823f2e2326.png)

**Comment by kerry-weic** [comment]
使用paddle包版本

> [root@localhost fastdeploy]# pip3 list | grep padd
paddle-bfloat         0.1.7
paddlepaddle-gpu      2.4.2.post117

**Comment by fanruifeng** [comment]
怎么官方人也不回复, 最后解决了嘛

**Comment by kerry-weic** [comment]
没， 现在还是不行。部署cpu的版本可以用

**Comment by fanruifeng** [comment]
> 

![image](https://user-images.githubusercontent.com/42561039/229049797-935a4593-abc0-475b-832c-977db1545238.png)


我现在也是在Linux X86机器上 部署fastdeploy ，下载的cpu版本, 在启动的时候也报错

**Comment by kerry-weic** [comment]
你有调参数吗？ 无效key。 cpu的版本我是前几天部署的，一次性就成功

**Comment by fanruifeng** [comment]
> 你有调参数吗？ 无效key。 cpu的版本我是前几天部署的，一次性就成功

暂时没调参数, 就是直接用 fastdeploy simple_serving  来启动的, server.py设置的使用cpu  txt=False

**Comment by kerry-weic** [comment]
那就不清楚了，可以提个问题让官方的人看下呗。我之前cpu的版本没改过参数



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年3月31日(星期五) 下午3:18
收件人: ***@***.***&gt;; 
抄送: " ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [PaddlePaddle/FastDeploy] GPU版本  FastDeploy simple_serving部署启动失败( initalized failed ) (Issue #1747)





  
你有调参数吗？ 无效key。 cpu的版本我是前几天部署的，一次性就成功
  
暂时没调参数, 就是直接用 fastdeploy simple_serving  来启动的, server.py设置的使用cpu  txt=False
