### ISSUE TITLE
UTF-8 Encoding Error for English Inference

### ISSUE THREAD

**Issue by arsenignatosyan** [PaddlePaddle/FastDeploy#1750]
## Environment

FastDeploy version: 1.0.5
OS Platform: Mac OSX
Hardware: M1 Chip
Program Language: Python 3.7

## Problem description
I am trying to replicate the [this](https://github.com/PaddlePaddle/PaddleOCR/blob/dygraph/deploy/fastdeploy/cpu-gpu/python/infer.py) example of fastdeploy locally. I passed the English detection and recognition models, also English recognition label file to the argument parser in the example. Here are the links to models: [detection model](https://paddleocr.bj.bcebos.com/PP-OCRv3/english/en_PP-OCRv3_det_infer.tar), [recognition model](https://paddleocr.bj.bcebos.com/PP-OCRv3/english/en_PP-OCRv3_rec_infer.tar), [recognition label file](https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/ppocr/utils/en_dict.txt). 

The code works for the image given in the example (with Chinese text), but for other images, such as the German image again in PaddleOCR's examples ([this image](https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/doc/imgs/ger_1.jpg)) the code gives unicode error. I removed the `print(result)` part and added 
`print(result.boxes)`
`print(result.rec_scores)`
`result_text = result.text ` 
these parts to locate the issue. The error is the following:
<img width="1332" alt="image" src="https://user-images.githubusercontent.com/22133074/228895712-94104ab0-0ec4-41d8-8c7f-e623dae744e5.png">

**Comment by garikdza** [comment]
我也有同样的问题。
