### ISSUE TITLE
picodet_l_640_coco_lcnet转rknn失败

### ISSUE THREAD

**Issue by vamoslc** [PaddlePaddle/FastDeploy#1752]
*********************************************
温馨提示：根据社区不完全统计，按照模板提问，可以加快回复和解决问题的速度
*********************************************

## 环境

- 【FastDeploy版本】： 与origin/develop一致
- 【编译命令】python ../export.py --config_path=./config.yaml --target_platform rk3588
- 【系统平台】: Linux x64(Ubuntu 18.04) 
- 【硬件】：
- 【编译语言】：Python(3.7）

## 问题日志及出现问题的操作流程
- 附上详细的问题日志有助于快速定位分析
- 【转换模型出错】
- 自己的模型不能转成rknn 
- root@94cc3f5f3ccc:/home/paddleDets/FastDeploy/tools/rknpu2/picodet_l_640_coco_lcnet# python ../export.py --config_path=./config.yaml --target_platform rk3588
{'mean': [123.675, 116.28, 103.53], 'std': [58.395, 57.12, 57.375], 'model_path': './picodet_l_640_coco_lcnet.onnx', 'target_platform': 'RK3588', 'outputs_nodes': None, 'do_quantization': False, 'dataset': None, 'output_folder': './'}
W __init__: rknn-toolkit2 version: 1.4.0-22dcfef4
I base_optimize ...
I base_optimize done.
I
I fold_constant ...
I fold_constant done.
I
I correct_ops ...
I correct_ops done.
I
I fuse_ops ...
I fuse_ops results:
I     fuse_bn_into_conv: remove node = ['p2o.BatchNormalization.0', 'p2o.BatchNormalization.1', 'p2o.BatchNormalization.2', 'p2o.BatchNormalization.3', 'p2o.BatchNormalization.4', 'p2o.BatchNormalization.5', 'p2o.BatchNormalization.6', 'p2o.BatchNormalization.7', 'p2o.BatchNormalization.8', 'p2o.BatchNormalization.9', 'p2o.BatchNormalization.10', 'p2o.BatchNormalization.11', 'p2o.BatchNormalization.12', 'p2o.BatchNormalization.13', 'p2o.BatchNormalization.14', 'p2o.BatchNormalization.15', 'p2o.BatchNormalization.16', 'p2o.BatchNormalization.17', 'p2o.BatchNormalization.18', 'p2o.BatchNormalization.19', 'p2o.BatchNormalization.20', 'p2o.BatchNormalization.21', 'p2o.BatchNormalization.22', 'p2o.BatchNormalization.23', 'p2o.BatchNormalization.24', 'p2o.BatchNormalization.25', 'p2o.BatchNormalization.26', 'p2o.BatchNormalization.29', 'p2o.BatchNormalization.50', 'p2o.BatchNormalization.51', 'p2o.BatchNormalization.28', 'p2o.BatchNormalization.30', 'p2o.BatchNormalization.31', 'p2o.BatchNormalization.32', 'p2o.BatchNormalization.33', 'p2o.BatchNormalization.27', 'p2o.BatchNormalization.34', 'p2o.BatchNormalization.35', 'p2o.BatchNormalization.36', 'p2o.BatchNormalization.37', 'p2o.BatchNormalization.38', 'p2o.BatchNormalization.39', 'p2o.BatchNormalization.40', 'p2o.BatchNormalization.41', 'p2o.BatchNormalization.42', 'p2o.BatchNormalization.43', 'p2o.BatchNormalization.44', 'p2o.BatchNormalization.45', 'p2o.BatchNormalization.46', 'p2o.BatchNormalization.47', 'p2o.BatchNormalization.48', 'p2o.BatchNormalization.49', 'p2o.BatchNormalization.52', 'p2o.BatchNormalization.53', 'p2o.BatchNormalization.87', 'p2o.BatchNormalization.88', 'p2o.BatchNormalization.89', 'p2o.BatchNormalization.90', 'p2o.BatchNormalization.91', 'p2o.BatchNormalization.92', 'p2o.BatchNormalization.93', 'p2o.BatchNormalization.94', 'p2o.BatchNormalization.95', 'p2o.BatchNormalization.96', 'p2o.BatchNormalization.97', 'p2o.BatchNormalization.76', 'p2o.BatchNormalization.77', 'p2o.BatchNormalization.78', 'p2o.BatchNormalization.79', 'p2o.BatchNormalization.80', 'p2o.BatchNormalization.81', 'p2o.BatchNormalization.82', 'p2o.BatchNormalization.83', 'p2o.BatchNormalization.84', 'p2o.BatchNormalization.85', 'p2o.BatchNormalization.86', 'p2o.BatchNormalization.65', 'p2o.BatchNormalization.66', 'p2o.BatchNormalization.67', 'p2o.BatchNormalization.68', 'p2o.BatchNormalization.69', 'p2o.BatchNormalization.70', 'p2o.BatchNormalization.71', 'p2o.BatchNormalization.72', 'p2o.BatchNormalization.73', 'p2o.BatchNormalization.74', 'p2o.BatchNormalization.75', 'p2o.BatchNormalization.54', 'p2o.BatchNormalization.55', 'p2o.BatchNormalization.56', 'p2o.BatchNormalization.57', 'p2o.BatchNormalization.58', 'p2o.BatchNormalization.59', 'p2o.BatchNormalization.60', 'p2o.BatchNormalization.61', 'p2o.BatchNormalization.62', 'p2o.BatchNormalization.63', 'p2o.BatchNormalization.64']
I     convert_div_to_mul: remove node = ['p2o.Div.0'], add node = ['p2o.Div.0_2mul']
I     convert_div_to_mul: remove node = ['p2o.Div.1'], add node = ['p2o.Div.1_2mul']
I     convert_div_to_mul: remove node = ['p2o.Div.2'], add node = ['p2o.Div.2_2mul']
I     convert_div_to_mul: remove node = ['p2o.Div.3'], add node = ['p2o.Div.3_2mul']
I     convert_div_to_mul: remove node = ['p2o.Div.4'], add node = ['p2o.Div.4_2mul']
I     convert_div_to_mul: remove node = ['p2o.Div.5'], add node = ['p2o.Div.5_2mul']
I     convert_div_to_mul: remove node = ['p2o.Div.6'], add node = ['p2o.Div.6_2mul']
I     convert_div_to_mul: remove node = ['p2o.Div.7'], add node = ['p2o.Div.7_2mul']
I     convert_div_to_mul: remove node = ['p2o.Div.8'], add node = ['p2o.Div.8_2mul']
I     convert_div_to_mul: remove node = ['p2o.Div.9'], add node = ['p2o.Div.9_2mul']
I     convert_div_to_mul: remove node = ['p2o.Div.10'], add node = ['p2o.Div.10_2mul']
I     convert_div_to_mul: remove node = ['p2o.Div.11'], add node = ['p2o.Div.11_2mul']
I     convert_div_to_mul: remove node = ['p2o.Div.12'], add node = ['p2o.Div.12_2mul']
I     convert_div_to_mul: remove node = ['p2o.Div.13'], add node = ['p2o.Div.13_2mul']
I     convert_div_to_mul: remove node = ['p2o.Div.14'], add node = ['p2o.Div.14_2mul']
I     convert_div_to_mul: remove node = ['p2o.Div.15'], add node = ['p2o.Div.15_2mul']
I     convert_div_to_mul: remove node = ['p2o.Div.16'], add node = ['p2o.Div.16_2mul']
I     convert_div_to_mul: remove node = ['p2o.Div.17'], add node = ['p2o.Div.17_2mul']
I     convert_div_to_mul: remove node = ['p2o.Div.18'], add node = ['p2o.Div.18_2mul']
I     convert_div_to_mul: remove node = ['p2o.Div.19'], add node = ['p2o.Div.19_2mul']
I     convert_div_to_mul: remove node = ['p2o.Div.20'], add node = ['p2o.Div.20_2mul']
I     convert_div_to_mul: remove node = ['p2o.Div.21'], add node = ['p2o.Div.21_2mul']
I     convert_div_to_mul: remove node = ['p2o.Div.22'], add node = ['p2o.Div.22_2mul']
I     convert_div_to_mul: remove node = ['p2o.Div.23'], add node = ['p2o.Div.23_2mul']
I     convert_global_avgpool_to_conv: remove node = ['p2o.GlobalAveragePool.0'], add node = ['p2o.GlobalAveragePool.0_2conv_0', 'p2o.GlobalAveragePool.1']
I     convert_div_to_mul: remove node = ['p2o.Div.24'], add node = ['p2o.Div.24_2mul']
I     convert_div_to_mul: remove node = ['p2o.Div.25'], add node = ['p2o.Div.25_2mul']
I     convert_global_avgpool_to_conv: remove node = ['p2o.GlobalAveragePool.2'], add node = ['p2o.GlobalAveragePool.2_2conv_0', 'p2o.GlobalAveragePool.3']
I     convert_div_to_mul: remove node = ['p2o.Div.26'], add node = ['p2o.Div.26_2mul']
I     convert_div_to_mul: remove node = ['p2o.Div.29'], add node = ['p2o.Div.29_2mul']
E build: Catch exception when building RKNN model!
E build: Traceback (most recent call last):
E build:   File "rknn/api/rknn_base.py", line 1546, in rknn.api.rknn_base.RKNNBase.build
E build:   File "rknn/api/graph_optimizer.py", line 1276, in rknn.api.graph_optimizer.GraphOptimizer.fuse_ops
E build:   File "rknn/api/fuse_rules.py", line 2138, in rknn.api.fuse_rules._p_convert_resize_to_deconv
E build: TypeError: unsupported operand type(s) for /: 'NoneType' and 'int'
Traceback (most recent call last):
  File "../export.py", line 64, in <module>
    assert ret == 0, "Build model failed!"
AssertionError: Build model failed!

**Comment by Zheng-Bicheng** [comment]
固定shape了吗？

**Comment by vamoslc** [comment]
> 固定shape了吗？

转出onnx的时候已经固定了

**Comment by lizheng-1** [comment]
我遇到了同样的错误，请问问题解决了吗？

**Comment by Zheng-Bicheng** [comment]
参考以下文档，看一下输出节点指定的是否和你们的模型一致

https://github.com/PaddlePaddle/FastDeploy/tree/develop/examples/vision/detection/paddledetection/rknpu2

**Comment by vamoslc** [comment]
> 参考以下文档，看一下输出节点指定的是否和你们的模型一致
> 
> https://github.com/PaddlePaddle/FastDeploy/tree/develop/examples/vision/detection/paddledetection/rknpu2

你好 ，其实您推荐这篇文档有些地方我感到疑惑，就是图上写的input[0]为p2o.Div.179 然后下面代码中写的input[0]为p2o.Mul.179  这个对我造成了一些疑惑 还有我在netrom上看到我的input[0]为 tmp_17 
![屏幕截图 2023-04-11 092123](https://user-images.githubusercontent.com/15844169/231030809-0721513f-543a-4c8e-9d42-736a4b050c4f.png)

不知道这个是否有影响？

**Comment by Zheng-Bicheng** [comment]
> https://github.com/PaddlePaddle/FastDeploy/tree/develop/examples/vision/detection/paddledetection/rknpu2

* 针对第一个问题。是这样，由于paddle2onnx版本的不同，导出后的onnx模型的节点名称也可能存在差异，所以你应该对应着找自己模型对应的输出节点的name。
* 针对第二个问题。按照正常的逻辑，确实应该使用`tmp_17`和`concat_9`作为输出节点，但是瑞芯微电子对`Div`这个op的支持度有点小问题，不兼容`Mul`下面的这个`Div`节点，所以只能退而求其次，使用`Mul`节点做输出。
* 至于会不会有影响，fastdeploy的逻辑现在是这样，如果输入的tensor数量为两个，默认不做scale操作，输入tensor为一个时，默认做scale操作。指定输入节点为`Mul`节点，你可以简单的理解为FastDeploy在CPU上做了`Div`这个OP的操作，速度会稍微慢一丢丢。
