### ISSUE TITLE
之前提的问题没有回复

### ISSUE THREAD

**Issue by pangchao-git** [PaddlePaddle/FastDeploy#1753]
这个是两周前提的问题:https://github.com/PaddlePaddle/FastDeploy/issues/1685
一直没有下文,有工程师帮忙看过么

**Comment by DefTruth** [comment]
您好，您提供的代码含有较多自己添加的逻辑，无法判断是FD的问题，还是您代码集成的问题。请问可以提供一个可复现问题的最小代码吗？

**Comment by pangchao-git** [comment]
我给的代码没有很多逻辑吧,其实我只是想把 std::shared_ptr<fastdeploy::pipeline::PPOCRv3> m_ppocr 这个作为一个成员给其他类使用,因为正常集成肯定是初始化模型和推理分开的

**Comment by pangchao-git** [comment]
这个是只封装了一个类的demo,你们看看这个问题.
[test_ocr.tar.gz](https://github.com/PaddlePaddle/FastDeploy/files/11118939/test_ocr.tar.gz)
