### ISSUE TITLE
Jetson Nano编译python版本报错：'CMakeFiles/copy_third_libraries' failed

### ISSUE THREAD

**Issue by Yuening-Ma** [PaddlePaddle/FastDeploy#1757]
## 环境

- 【FastDeploy版本】： 拉取最新源码自行编译的python版本
- 【编译命令】: sudo python3 setup.py build
- 【系统平台】: Ubuntu 18.04, Jetpack 4.6
- 【硬件】： Jetson Nano 4GB
- 【编译语言】： Python 3.6
- 【cmake版本】：3.25

## 问题日志及出现问题的操作流程
- 【编译失败】
执行sudo python3 setup.py build进行编译，环境变量为：
export BUILD_ON_JETSON=ON
export ENABLE_VISION=ON
export ENABLE_TRT_BACKEND=ON

编译报错：
(前面进度都正常，省略)
[100%] Built target fastdeploy_main
Error copying directory from "/home/xxx/FastDeploy/python/.setuptools-cmake-build/third_libs/install" to "/home/xxx/FastDeploy/python/fastdeploy/libs/third_libs".
CMakeFiles/copy_third_libraries.dir/build.make:70: recipe for target 'CMakeFiles/copy_third_libraries' failed

**Comment by tongxiaohua** [comment]
碰到一样的问题，没法解决，直接创建了install这个目录
好像没啥问题了。
