### ISSUE TITLE
使用fastapi和websocket协议将推理的视频帧推送到客户端，运行报错

### ISSUE THREAD

**Issue by Shifiter** [PaddlePaddle/FastDeploy#1762]
*********************************************
温馨提示：根据社区不完全统计，按照模板提问，可以加快回复和解决问题的速度
*********************************************

## 环境

- 【FastDeploy版本】： 最新git https://github.com/PaddlePaddle/FastDeploy.git
- 【编译命令】pyhton SDK
- 【系统平台】: Linux arm(Ubuntu 20.04) 
- 【硬件】： rk3588
- 【编译语言】：Python(3.8）

## 问题日志及出现问题的操作流程
使用fastapi和websocket协议将推理的视频帧推送到客户端，运行报错
-INFO:     Started server process [3726]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
INFO:     127.0.0.1:40102 - "GET / HTTP/1.1" 200 OK
INFO:     ('127.0.0.1', 40110) - "WebSocket /ws" [accepted]
[INFO] fastdeploy/runtime/backends/rknpu2/rknpu2_backend.cc(57)::GetSDKAndDeviceVersion	rknn_api/rknnrt version: 1.4.2b0 (c5d79ccf9@2023-02-14T17:55:39), driver version: 0.7.2
index=0, name=images, n_dims=4, dims=[1, 640, 640, 3], n_elems=1228800, size=1228800, fmt=NHWC, type=INT8, qnt_type=AFFINE, zp=-128, scale=0.003922, pass_through=0
index=0, name=output, n_dims=4, dims=[1, 18, 80, 80], n_elems=115200, size=115200, fmt=NCHW, type=INT8, qnt_type=AFFINE, zp=-128, scale=0.003922, pass_through=0
index=1, name=272, n_dims=4, dims=[1, 18, 40, 40], n_elems=28800, size=28800, fmt=NCHW, type=INT8, qnt_type=AFFINE, zp=-128, scale=0.003922, pass_through=0
index=2, name=274, n_dims=4, dims=[1, 18, 20, 20], n_elems=7200, size=7200, fmt=NCHW, type=INT8, qnt_type=AFFINE, zp=-128, scale=0.003922, pass_through=0
[INFO] fastdeploy/runtime/runtime.cc(334)::CreateRKNPU2Backend	Runtime initialized with Backend::RKNPU2 in Device::RKNPU.
[INFO] fastdeploy/runtime/backends/rknpu2/rknpu2_backend.cc(57)::GetSDKAndDeviceVersion	rknn_api/rknnrt version: 1.4.2b0 (c5d79ccf9@2023-02-14T17:55:39), driver version: 0.7.2
index=0, name=images, n_dims=4, dims=[1, 640, 640, 3], n_elems=1228800, size=1228800, fmt=NHWC, type=INT8, qnt_type=AFFINE, zp=-128, scale=0.003922, pass_through=0
index=0, name=output, n_dims=4, dims=[1, 36, 80, 80], n_elems=230400, size=230400, fmt=NCHW, type=INT8, qnt_type=AFFINE, zp=-128, scale=0.003919, pass_through=0
index=1, name=272, n_dims=4, dims=[1, 36, 40, 40], n_elems=57600, size=57600, fmt=NCHW, type=INT8, qnt_type=AFFINE, zp=-128, scale=0.003910, pass_through=0
index=2, name=274, n_dims=4, dims=[1, 36, 20, 20], n_elems=14400, size=14400, fmt=NCHW, type=INT8, qnt_type=AFFINE, zp=-128, scale=0.003921, pass_through=0
[INFO] fastdeploy/runtime/runtime.cc(334)::CreateRKNPU2Backend	Runtime initialized with Backend::RKNPU2 in Device::RKNPU.
[WARNING] fastdeploy/runtime/backends/rknpu2/rknpu2_backend.cc(326)::Infer	The input tensor type != model's inputs type.The input_type need INT8,but inputs[0].type is UINT8
E RKNN: [19:47:04.881] can not find memory for freeing
Segmentation fault (core dumped)

**Comment by Shifiter** [comment]
硬件配置8+128

**Comment by Zheng-Bicheng** [comment]
排查一下下面几个问题
* 单独推理图片有没有问题
* 去掉websocket推理视频有没有问题
* 加上websocket有没有问题

**Comment by Shifiter** [comment]
看起来这样一段代码能够成功运行并保存结果，但会报错

```
model_file = './models/PPE3-best.rknn'
model_file_hand = './models/hand_detection.rknn'

# 定义ROI区域坐标
roi_coords = [(450, 100), (600, 300)]

# 配置runtime，加载模型
runtime_option = fd.RuntimeOption()
runtime_option.use_rknpu2()

model_hand = fd.vision.detection.RKYOLOV5(
    model_file_hand,
    runtime_option=runtime_option,
    model_format=fd.ModelFormat.RKNN)

model = fd.vision.detection.RKYOLOV5(
    model_file,
    runtime_option=runtime_option,
    model_format=fd.ModelFormat.RKNN)

model.postprocessor.class_num = 7
IMG = './IMG_3809.jpg'
IMG = cv2.imread(IMG)
result_hand = model.predict(IMG)
vis_im = fd.vision.vis_detection(IMG, result_hand, score_threshold=0.5)
cv2.imwrite("visualized_result.jpg", vis_im)
```
##############################################################################################################################################################################################
报错信息如下：
[INFO] fastdeploy/runtime/backends/rknpu2/rknpu2_backend.cc(57)::GetSDKAndDeviceVersion	rknn_api/rknnrt version: 1.4.2b0 (c5d79ccf9@2023-02-14T17:55:39), driver version: 0.7.2
index=0, name=images, n_dims=4, dims=[1, 640, 640, 3], n_elems=1228800, size=1228800, fmt=NHWC, type=INT8, qnt_type=AFFINE, zp=-128, scale=0.003922, pass_through=0
index=0, name=output, n_dims=4, dims=[1, 18, 80, 80], n_elems=115200, size=115200, fmt=NCHW, type=INT8, qnt_type=AFFINE, zp=-128, scale=0.003922, pass_through=0
index=1, name=272, n_dims=4, dims=[1, 18, 40, 40], n_elems=28800, size=28800, fmt=NCHW, type=INT8, qnt_type=AFFINE, zp=-128, scale=0.003922, pass_through=0
index=2, name=274, n_dims=4, dims=[1, 18, 20, 20], n_elems=7200, size=7200, fmt=NCHW, type=INT8, qnt_type=AFFINE, zp=-128, scale=0.003922, pass_through=0
[INFO] fastdeploy/runtime/runtime.cc(334)::CreateRKNPU2Backend	Runtime initialized with Backend::RKNPU2 in Device::RKNPU.
[INFO] fastdeploy/runtime/backends/rknpu2/rknpu2_backend.cc(57)::GetSDKAndDeviceVersion	rknn_api/rknnrt version: 1.4.2b0 (c5d79ccf9@2023-02-14T17:55:39), driver version: 0.7.2
index=0, name=images, n_dims=4, dims=[1, 640, 640, 3], n_elems=1228800, size=1228800, fmt=NHWC, type=INT8, qnt_type=AFFINE, zp=-128, scale=0.003922, pass_through=0
index=0, name=output, n_dims=4, dims=[1, 36, 80, 80], n_elems=230400, size=230400, fmt=NCHW, type=INT8, qnt_type=AFFINE, zp=-128, scale=0.003919, pass_through=0
index=1, name=272, n_dims=4, dims=[1, 36, 40, 40], n_elems=57600, size=57600, fmt=NCHW, type=INT8, qnt_type=AFFINE, zp=-128, scale=0.003910, pass_through=0
index=2, name=274, n_dims=4, dims=[1, 36, 20, 20], n_elems=14400, size=14400, fmt=NCHW, type=INT8, qnt_type=AFFINE, zp=-128, scale=0.003921, pass_through=0
[INFO] fastdeploy/runtime/runtime.cc(334)::CreateRKNPU2Backend	Runtime initialized with Backend::RKNPU2 in Device::RKNPU.
[WARNING] fastdeploy/runtime/backends/rknpu2/rknpu2_backend.cc(326)::Infer	The input tensor type != model's inputs type.The input_type need INT8,but inputs[0].type is UINT8
E RKNN: [09:29:31.225] can not find memory for freeing
E RKNN: [09:29:31.225] can not find memory for freeing
Segmentation fault (core dumped)
##############################################################################################################################################################################################
如果将其中没有用到的一个模型初始化注释掉，可以运行并不报错，但有意思的是，在我的另外一段代码中，可以同时初始化两个模型，并分别检测视频帧并输出，部分代码如下：
```
def parse_arguments():
    import argparse
    import ast
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--model_file", default='./models/PPE3-best.rknn', required=False, help="Path of rknn model.")
    parser.add_argument(
        "--model_file_hand", default='./models/hand_detection.rknn', required=False, help="Path of rknn model.")
    parser.add_argument(
        "--image", default='./IMG_3929.jpg', type=str, required=False, help="Path of test image file.")
    return parser.parse_args()

if __name__ == "__main__":
    args = parse_arguments()

    model_file = args.model_file
    model_file_hand = args.model_file_hand
    params_file = ""

    # 定义ROI区域坐标
    roi_coords = [(450, 100), (600, 300)]

    # 配置runtime，加载模型
    runtime_option = fd.RuntimeOption()
    runtime_option.use_rknpu2()

    model_hand = fd.vision.detection.RKYOLOV5(
        model_file_hand,
        runtime_option=runtime_option,
        model_format=fd.ModelFormat.RKNN)

    model = fd.vision.detection.RKYOLOV5(
        model_file,
        runtime_option=runtime_option,
        model_format=fd.ModelFormat.RKNN)

    model_hand.postprocessor.class_num = 1

    # 模型检测类别
    if model_file == './models/mask-best.rknn':
        model.postprocessor.class_num = 3
    elif model_file == './models/PPE3-best.rknn': 
        model.postprocessor.class_num = 7
    elif model_file == './models/mask2_class3.rknn':
        model.postprocessor.class_num = 3

    cap = cv2.VideoCapture(0)
    cap.set(cv2.CAP_PROP_FPS, 30)
    ret, frame = cap.read()
    result_hand = model_hand.predict(frame)
    vis_im = fd.vision.vis_detection(frame, result_hand, score_threshold=0.5)
    cv2.imshow("Video", vis_im)
        if cv2.waitKey(1) == ord('q'):
            break
    cap.release()
    cv2.destroyAllWindows()
```

**Comment by Zheng-Bicheng** [comment]
这个报错我这边复现了，应该是模型析构释放内存的时候出现了问题，理论上应该不影响使用，后面会修复的。

**Comment by Shifiter** [comment]
需要将检测到的图片推送到web端，这个错误会导致图片推不过去

**Comment by Zheng-Bicheng** [comment]
测一下如下PR哈

* https://github.com/PaddlePaddle/FastDeploy/pull/1772

**Comment by Zheng-Bicheng** [comment]
可以用了吗

**Comment by Shifiter** [comment]
我用了之前的方法实现了，暂时去忙另一个项目了，还没有尝试
