### ISSUE TITLE
RKNPU2 板端推理报错: Invalid RKNN format!

### ISSUE THREAD

**Issue by ZHR1997** [PaddlePaddle/FastDeploy#1763]
- 【模型跑不通】
环境：py38   rknn-toolkit2  ----- 1.4.2b0-df08fb60，在RK3588板端运行的时候报错
模型：用的你们给的resent50，先paddle2onnx（1.0.6），再用export.py转成rknn模型
最终在板端运行出现如下错误
./rknpu_test ./demo_model ./demo_model/ILSVRC2012_val_00000010.jpeg
[INFO] fastdeploy/vision/common/processors/transform.cc(93)::FuseNormalizeHWC2CHW       Normalize and HWC2CHW are fused to NormalizeAndPermute  in preprocessing pipeline.
[INFO] fastdeploy/vision/common/processors/transform.cc(159)::FuseNormalizeColorConvert BGR2RGB and NormalizeAndPermute are fused to NormalizeAndPermute with swap_rb=1
E RKNN: [13:57:54.317] parseRKNN from path: Invalid RKNN format!
E RKNN: [13:57:54.317] rknn_init, load model failed!
[ERROR] fastdeploy/runtime/backends/rknpu2/rknpu2_backend.cc(157)::LoadModel    rknn_init fail! ret=-1
[ERROR] fastdeploy/runtime/backends/rknpu2/rknpu2_backend.cc(100)::Init load model failed
[ERROR] fastdeploy/runtime/runtime.cc(328)::CreateRKNPU2Backend Failed to initialize RKNPU2 backend.
Aborted

**Comment by Zheng-Bicheng** [comment]
板子具体型号是啥？尝试运行程序的时候加个sudo

**Comment by ZHR1997** [comment]
> 板子具体型号是啥？尝试运行程序的时候加个sudo

rk3588的板子，是在root权限下运行的程序

**Comment by Zheng-Bicheng** [comment]
你这个看上去是模型地址错误，rknn模型地址有配对了吗？

**Comment by Zheng-Bicheng** [comment]
看一下infer_xxx.cc文件里面的rknn地址是不是你的模型地址

**Comment by ZHR1997** [comment]
> 看一下infer_xxx.cc文件里面的rknn地址是不是你的模型地址
我把读取模型的字符串打印出来，看着像是没问题的诶

[root@RK3588:/tmp/zhanghongrui]# ls demo_model/
ILSVRC2012_val_00000010.jpeg  ResNet50_vd_infer_rk3588_unquantized.rknn  deploy_rk3588_unquantized.rknn  inference_cls.yaml

[root@RK3588:/tmp/zhanghongrui]# ./rknpu_test ./demo_model ./demo_model/ILSVRC2012_val_00000010.jpeg
model_file: ./demo_model/ResNet50_vd_infer_rk3588_unquantized.rknn
config_file: ./demo_model/inference_cls.yaml
[INFO] fastdeploy/vision/common/processors/transform.cc(93)::FuseNormalizeHWC2CHW       Normalize and HWC2CHW are fused to NormalizeAndPermute  in preprocessing pipeline.
[INFO] fastdeploy/vision/common/processors/transform.cc(159)::FuseNormalizeColorConvert BGR2RGB and NormalizeAndPermute are fused to NormalizeAndPermute with swap_rb=1
E RKNN: [04:19:55.887] parseRKNN from path: Invalid RKNN format!
E RKNN: [04:19:55.887] rknn_init, load model failed!
[ERROR] fastdeploy/runtime/backends/rknpu2/rknpu2_backend.cc(157)::LoadModel    rknn_init fail! ret=-1
[ERROR] fastdeploy/runtime/backends/rknpu2/rknpu2_backend.cc(100)::Init load model failed
[ERROR] fastdeploy/runtime/runtime.cc(328)::CreateRKNPU2Backend Failed to initialize RKNPU2 backend.
Aborted

**Comment by Zheng-Bicheng** [comment]
我的意思是，你修改一下`examples/vision/classification/paddleclas/rockchip/rknpu2/cpp/infer.cc`里面的模型配置参数，修改成你自己的。

```cpp
void RKNPU2Infer(const std::string &model_dir, const std::string &image_file) {
auto model_file = model_dir + "/ResNet50_vd_infer_rk3588.rknn";
auto config_file = model_dir + "/inference_cls.yaml";
}
```

**Comment by ZHR1997** [comment]
> model_file: ./demo_model/ResNet50_vd_infer_rk3588_unquantized.rknn
> config_file: ./demo_model/inference_cls.yaml

我已经改了呀。
板端程序打印出来的下面两个字符串，就是我的模型路径，是对的诶
model_file: ./demo_model/ResNet50_vd_infer_rk3588_unquantized.rknn
config_file: ./demo_model/inference_cls.yaml

**Comment by Zheng-Bicheng** [comment]
我复现一下吧。

**Comment by ZHR1997** [comment]
> 我复现一下吧。

您好，请问能够复现出来吗，具体是什么原因造成这个错误的

**Comment by Zheng-Bicheng** [comment]
我这边是正常的，这个错误只在模型地址错误时会出现，可能是以下原因:

* 模型地址错误
* 模型没有放到build目录下

**Comment by ZHR1997** [comment]
> 我这边是正常的，这个错误只在模型地址错误时会出现，可能是以下原因:
> 
> * 模型地址错误
> * 模型没有放到build目录下

模型没有放到build目录下是指什么，我是直接把传出来的rknn模型直接拷贝到板子上的，没经过build目录

**Comment by Zheng-Bicheng** [comment]
你把model和config的路径改为绝对路径吧，不要用相对路径试试

**Comment by ZHR1997** [comment]
> 你把model和config的路径改为绝对路径吧，不要用相对路径试试

感觉不是路径的问题哇，我改成绝对路径还是一样的结果，根据报错信息来看，先读到了config的信息，后面读取模型出错了，照理说config都读到了，模型怎么会读不到0.0

**Comment by Zheng-Bicheng** [comment]
> 感觉不是路径的问题哇，我改成绝对路径还是一样的结果，根据报错信息来看，先读到了config的信息，后面读取模型出错了，照理说config都读到了，模型怎么会读不到0.0

有试过重新转换一下模型吗？可以用文档里提供的百度网盘链接，安装最新的测试版rknntoolkit2转换下试试

**Comment by ZHR1997** [comment]
> > 感觉不是路径的问题哇，我改成绝对路径还是一样的结果，根据报错信息来看，先读到了config的信息，后面读取模型出错了，照理说config都读到了，模型怎么会读不到0.0
> 
> 有试过重新转换一下模型吗？可以用文档里提供的百度网盘链接，安装最新的测试版rknntoolkit2转换下试试

刚刚试了，用了py38-1.4.2b5+3d5e66cb版本的toolkit2  都不行，其他版本的toolkit2没有py38的包，1.4.2b5最新了还是不行.......

**Comment by ZHR1997** [comment]
破案了。。。NPU的lib路径没export。。。。。之前opencv的库路径没export的时候报错了，npu的lib没export运行的时候没报错0.0

**Comment by Zheng-Bicheng** [comment]
解决了就好，npu的lib没报错是正常的，系统本身出厂就会自带一个npu的lib，会指向这个默认的lib

**Comment by ZHR1997** [comment]
> 解决了就好，npu的lib没报错是正常的，系统本身出厂就会自带一个npu的lib，会指向这个默认的lib

怪不得，所以用默认的那个lib，然后可能是版本对不上，才说RKNN模型的format有问题

**Comment by ZHR1997** [comment]
您好，还想问一下，为什么转模型的时候InputOperator 的Target是CPU   而不是跟conv一样是NPU呢？这个具体的配置是在哪？我用的是你们的ResNet50_vd_infer_rknn.yaml

**Comment by Zheng-Bicheng** [comment]
> 您好，还想问一下，为什么转模型的时候InputOperator 的Target是CPU 而不是跟conv一样是NPU呢？这个具体的配置是在哪？我用的是你们的ResNet50_vd_infer_rknn.yaml

InputOperator应该是normalize、permute操作，int8的情况下会跑在NPU上，fp16应该是cpu。

**Comment by ZHR1997** [comment]
> 

了解了，softmax这种也是一样是吧，int8才是NPU，FP16就是CPU
