### ISSUE TITLE
package_data must be a dictionary mapping package names to lists of wildcard patterns

### ISSUE THREAD

**Issue by jia0511** [PaddlePaddle/FastDeploy#1768]
我根据源码流程安装在altas 300I 显卡上按照https://github.com/PaddlePaddle/FastDeploy/blob/develop/docs/en/build_and_install/huawei_ascend.md
方式安装python包时候遇到了标题问题，请问如何解决？

[root@localhost python]# export ENABLE_VISION=ON
[root@localhost python]# export WITH_ASCEND=ON
[root@localhost python]# python setup.py build
error in fastdeploy-python setup command: package_data must be a dictionary mapping package names to lists of wildcard patterns

**Comment by DefTruth** [comment]
你的python版本是多少呢？

**Comment by jia0511** [comment]
python 3.8

**Comment by jia0511** [comment]
这个问题有人更新吗？新增信息，我用的centos7.6系统

**Comment by jia0511** [comment]
已经换到ubuntu18.04
