### ISSUE TITLE
fastdeploy ocr推理精度丢失

### ISSUE THREAD

**Issue by kerry-weic** [PaddlePaddle/FastDeploy#1775]
通过PaddleOCR.ocr python脚本运行的推理结果和fastDeploy ocr推理结果不一致。
PaddleCOR.ocr推理脚本参考:https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/doc/doc_ch/quickstart.md#221-%E4%B8%AD%E8%8B%B1%E6%96%87%E4%B8%8E%E5%A4%9A%E8%AF%AD%E8%A8%80%E4%BD%BF%E7%94%A8 
fastDeploy ocr推理参考文档:https://github.com/PaddlePaddle/PaddleOCR/tree/dygraph/deploy/fastdeploy/cpu-gpu/python#paddleocr-cpu-gpu-python%E9%83%A8%E7%BD%B2%E7%A4%BA%E4%BE%8B 

PaddleCOR ocr推理结果日志输出如下:
> [2023/04/06 14:34:37] ppocr DEBUG: Namespace(help='==SUPPRESS==', use_gpu=False, use_xpu=False, use_npu=False, ir_optim=True, use_tensorrt=False, min_subgraph_size=15, precision='fp32', gpu_mem=500, image_dir=None, page_num=0, det_algorithm='DB', det_model_dir='C:\\Users\\Administrator/.paddleocr/whl\\det\\ch\\ch_PP-OCRv3_det_infer', det_limit_side_len=960, det_limit_type='max', det_box_type='quad', det_db_thresh=0.3, det_db_box_thresh=0.6, det_db_unclip_ratio=1.5, max_batch_size=10, **use_dilation=True**, **det_db_score_mode='slow'**, det_east_score_thresh=0.8, det_east_cover_thresh=0.1, det_east_nms_thresh=0.2, det_sast_score_thresh=0.5, det_sast_nms_thresh=0.2, det_pse_thresh=0, det_pse_box_thresh=0.85, det_pse_min_area=16, det_pse_scale=1, scales=[8, 16, 32], alpha=1.0, beta=1.0, fourier_degree=5, rec_algorithm='SVTR_LCNet', rec_model_dir='C:\\Users\\Administrator/.paddleocr/whl\\rec\\ch\\ch_PP-OCRv3_rec_infer', rec_image_inverse=True, rec_image_shape='3, 48, 320', rec_batch_num=6, max_text_length=25, rec_char_dict_path='D:\\ProgramData\\Anaconda3\\lib\\site-packages\\paddleocr\\ppocr\\utils\\ppocr_keys_v1.txt', use_space_char=True, vis_font_path='./doc/fonts/simfang.ttf', drop_score=0.5, e2e_algorithm='PGNet', e2e_model_dir=None, e2e_limit_side_len=768, e2e_limit_type='max', e2e_pgnet_score_thresh=0.5, e2e_char_dict_path='./ppocr/utils/ic15_dict.txt', e2e_pgnet_valid_set='totaltext', e2e_pgnet_mode='fast', use_angle_cls=True, cls_model_dir='C:\\Users\\Administrator/.paddleocr/whl\\cls\\ch_ppocr_mobile_v2.0_cls_infer', cls_image_shape='3, 48, 192', label_list=['0', '180'], cls_batch_num=6, cls_thresh=0.9, enable_mkldnn=True, cpu_threads=10, use_pdserving=False, warmup=False, sr_model_dir=None, sr_image_shape='3, 32, 128', sr_batch_num=1, draw_img_save_dir='./inference_results', save_crop_res=False, crop_res_save_dir='./output', use_mp=False, total_process_num=1, process_id=0, benchmark=False, save_log_path='./log_output/', show_log=True, use_onnx=False, output='./output', table_max_len=488, table_algorithm='TableAttn', table_model_dir=None, merge_no_span_structure=True, table_char_dict_path=None, layout_model_dir=None, layout_dict_path=None, layout_score_threshold=0.5, layout_nms_threshold=0.5, kie_algorithm='LayoutXLM', ser_model_dir=None, re_model_dir=None, use_visual_backbone=True, ser_dict_path='../train_data/XFUND/class_list_xfun.txt', ocr_order_method=None, mode='structure', image_orientation=False, layout=True, table=True, ocr=True, recovery=False, use_pdf2docx_api=False, lang='ch', det=True, rec=True, type='ocr', ocr_version='PP-OCRv3', structure_version='PP-StructureV2')
[2023/04/06 14:36:18] ppocr DEBUG: dt_boxes num : 5, elapse : 0.31116414070129395
[2023/04/06 14:36:18] ppocr DEBUG: cls num  : 5, elapse : 0.052858829498291016
[2023/04/06 14:36:18] ppocr DEBUG: rec_res num  : 5, elapse : 0.2293851375579834
[[[137.0, 119.0], [732.0, 119.0], [732.0, 162.0], [137.0, 162.0]], ('哈哈哈哈哈哈哈哈哈哈或', 0.9856414198875427)]
[[[137.0, 189.0], [732.0, 189.0], [732.0, 229.0], [137.0, 229.0]], ('或或或或或或或或或或或', 0.9473259449005127)]
**[[[137.0, 257.0], [731.0, 257.0], [731.0, 297.0], [137.0, 297.0]], ('或或或或或或或或或或或', 0.9495126605033875)]**
[[[133.0, 322.0], [288.0, 322.0], [288.0, 368.0], [133.0, 368.0]], ('或或或', 0.8740523457527161)]

fastDeploy ocr推理结果日志如下:
> WARNING: Logging before InitGoogleLogging() is written to STDERR
W0406 14:36:30.014596   944 analysis_config.cc:972] It is detected that mkldnn and memory_optimize_pass are enabled at the same time, but they are not supported yet. Currently, memory_optimize_pass is explicitly disabled
[INFO] fastdeploy/runtime/runtime.cc(309)::fastdeploy::Runtime::CreatePaddleBackend     Runtime initialized with Backend::PDINFER in Device::CPU.
[INFO] fastdeploy/runtime/runtime.cc(309)::fastdeploy::Runtime::CreatePaddleBackend     Runtime initialized with Backend::PDINFER in Device::CPU.
[INFO] fastdeploy/runtime/runtime.cc(309)::fastdeploy::Runtime::CreatePaddleBackend     Runtime initialized with Backend::PDINFER in Device::CPU.
det boxes: [[136,118],[732,118],[732,162],[136,162]]rec text: 哈哈哈哈哈哈哈哈哈哈或 rec score:0.952564 cls label: 0 cls score: 1.000000
det boxes: [[136,189],[732,189],[732,228],[136,228]]rec text: 或或或或或或或或或或或 rec score:0.834911 cls label: 1 cls score: 0.764378
**det boxes: [[136,256],[731,256],[731,296],[136,296]]rec text: 尚验指指务指验指 rec score:0.065504 cls label: 1 cls score: 0.958775**
det boxes: [[133,322],[288,322],[288,368],[133,368]]rec text: 或或或 rec score:0.869063 cls label: 0 cls score: 1.000000
det boxes: [[158,382],[344,382],[344,613],[158,613]]rec text: 車 rec score:0.358460 cls label: 0 cls score: 0.925917

fastDeploy ocr推理执行脚本:

> python infer.py --det_model ch_PP-OCRv3_det_infer --cls_model ch_ppocr_mobile_v2.0_cls_infer --rec_model ch_PP-OCRv3_rec_infer --rec_label_file ppocr_keys_v1.txt --image bbbb.jpg --device cpu --backend paddle --rec_bs 10 --cls_bs 6 

对应推理所使用参数如下:
> rec_model:{
	is_scale: True
	mean: [0.5, 0.5, 0.5]
	rec_image_shape: [3, 48, 320]
	scale: [0.5, 0.5, 0.5]
	static_shape_infer: False
}
det_model:{
	det_db_box_thresh: 0.6
	**det_db_score_mode: 'slow'**
	det_db_thresh: 0.3
	det_db_unclip_ratio: 1.5
	is_scale: True
	max_side_len: 960
	scale: [0.2290000021457672, 0.2240000069141388, 0.22499999403953552]
	**use_dilation: 1**
}
cls_model:{
	cls_image_shape: [3, 48, 192]
	cls_thresh: 0.8999999761581421
	is_scale: True
	mean: [0.5, 0.5, 0.5]
}
ppocr:{
	cls_batch_size: 6
	rec_batch_size: 10
}

paddleocr本机版本为:2.6.1.2 ,fastDeploy ocr推理把第三行文本"或或或或或或或或或或或"识别成了“尚验指指务指验指”。对比过两者所使用的推理参数，在fastdeploy直接暴露可设置的参数均和前者一致。附件为ocr对应的原始图片
![bbbb](https://user-images.githubusercontent.com/49382323/230296314-a68ff408-68d0-4d2d-8fcb-8708bc4a5f58.jpg)

**Comment by yunyaoXYY** [comment]
由于某些第三方库的使用不同，FastDeploy的ppocr和PaddleOCR套件的C++部署结果是对齐的.  和PaddleOCR套件的python没有完全对齐

**Comment by kerry-weic** [comment]
@yunyaoXYY  FastDeploy ppocr C++版本支持服务化部署吗？

**Comment by kerry-weic** [comment]
好像就看到服务化部署的python版本，后续有计划对齐没

**Comment by yunyaoXYY** [comment]
服务化就使用 serving文件夹里的。

**Comment by xujiang1** [comment]
在 OCR 中 我们可以配置 e2e_char_dict_path 和 max_text_length vis_font_path 请问 fastDeploy  这边如何配置 是否可以开放配置
