### ISSUE TITLE
量化训练

### ISSUE THREAD

**Issue by zerobest** [PaddlePaddle/FastDeploy#1776]
WARNING:root:cannot import name 'layers' from 'parl' (G:\anaconda\envs\paddle_slim\lib\site-packages\parl\__init__.py)
G:\anaconda\envs\paddle_slim\lib\site-packages\_distutils_hack\__init__.py:33: UserWarning: Setuptools is replacing distutils.
  warnings.warn("Setuptools is replacing distutils.")
2023-04-06 15:23:01,526-WARNING: post-quant-hpo is not support in system other than linux
Welcome to use FastDeploy Auto Compression Toolkit!
Finish Compression, total time used is :  0.0 seconds.

**Comment by DefTruth** [comment]
```bash
post-quant-hpo is not support in system other than linux
``` 
根据提示，目前只在Linux下支持post-quant-hpo量化训练哈
