### ISSUE TITLE
请问使用runtime的时候，如何将实际输入的cv::Mat类型转为对应的tensor呢?

### ISSUE THREAD

**Issue by jasper-cell** [PaddlePaddle/FastDeploy#1777]
*********************************************
温馨提示：根据社区不完全统计，按照模板提问，可以加快回复和解决问题的速度
*********************************************

## 环境

- 【FastDeploy版本】： 说明具体的版本，如fastdeploy-linux-gpu-0.8.0
- 【系统平台】: Linux x64(Ubuntu 18.04) 
- 【硬件】： jetson
- 【编译语言】： C++

请问使用runtime的时候，如何将实际输入的cv::Mat类型转为对应的tensor呢?

<img width="716" alt="fd66ee085ad632f345f55d414886adc" src="https://user-images.githubusercontent.com/54393886/230326705-0c612a7d-7190-44de-98d1-f3bd190befad.png">

**Comment by DefTruth** [comment]
预处理的使用，可以参考yolov5cls中的写法：
https://github.com/PaddlePaddle/FastDeploy/blob/7b0c55d0c5535b9be0f20065d5a9dff7445f975b/fastdeploy/vision/classification/contrib/yolov5cls/preprocessor.cc#L41  
关于在c++如何使用runtime直接推理，可以参考这个文档：  
- https://github.com/PaddlePaddle/FastDeploy/blob/7b0c55d0c5535b9be0f20065d5a9dff7445f975b/docs/cn/quick_start/runtime/cpp.md  
逻辑上，预处理怎么做是由用户决定的，您可以采用任何的方式完成前处理，然后将数据传入FDTensor即可
