### ISSUE TITLE
Illegal instruction (core dumped)/RuntimeError: FastDeploy initalized failed!  Jetson Nano

### ISSUE THREAD

**Issue by ZnSn399379** [PaddlePaddle/FastDeploy#1779]
*********************************************
温馨提示：根据社区不完全统计，按照模板提问，可以加快回复和解决问题的速度
*********************************************

## 环境

- 【FastDeploy版本】： 说明具体的版本，如fastdeploy-linux-gpu-0.8.0
- 【编译命令】官方历程编译
- 【系统平台】: Linux x64(Ubuntu 18.04) 
- 【硬件】： Jetson Nano Developer Kit / JetPack4.6.1 / CUDA10.2 
- 【编译语言】： Python3.6.9

- 【模型跑不通】
官方例程中
ppyoloe模型无法正常编译，报错
Illegal instruction (core dumped)
尝试import fastdeploy
报错
RuntimeError: FastDeploy initalized failed!
通过nano ~/.bashrc并在最后一行加入export OPENBLAS_CORETYPE=ARMV8后再次运行出现如下错误
  File "infer_picodet.py", line 1, in <module>
    import fastdeploy as fd
ModuleNotFoundError: No module named 'fastdeploy'

**Comment by ZnSn399379** [comment]
> 

下面那个是由于使用python3导致的ModuleNotFoundError: No module named 'fastdeploy'
是否因为安装时直接使用的pip install安装wheel文件导致fastdeploy安装在了python2.7下，而python2.7不支持fastdeploy，造成的报错呢

**Comment by DefTruth** [comment]
是的，目前只支持python3.6-python3.10

**Comment by juddvinet** [comment]
`(paddle_env) ubuntu@ubuntu:~/rknn/FastDeploy/examples/vision/facedet/scrfd/python$ python3 -V
Python 3.10.10
(paddle_env) ubuntu@ubuntu:~/rknn/FastDeploy/examples/vision/facedet/scrfd/python$ python infer.py --model scrfd_500m_bnkps_shape640x640.onnx --image test_lite_face_detector_3.jpg --device cpu
Traceback (most recent call last):
  File "/home/ubuntu/rknn/FastDeploy/examples/vision/facedet/scrfd/python/infer.py", line 1, in <module>
    import fastdeploy as fd
ModuleNotFoundError: No module named 'fastdeploy'
(paddle_env) ubuntu@ubuntu:~/rknn/FastDeploy/examples/vision/facedet/scrfd/python$
(paddle_env) ubuntu@ubuntu:~/rknn/FastDeploy/examples/vision/facedet/scrfd/python$ uname -a
Linux ubuntu 5.15.0-69-generic #76~20.04.1-Ubuntu SMP Mon Mar 20 15:54:19 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
`

用python3.10 也出现同样的问题
