### ISSUE TITLE
[windows] fastdeploy PPOCRv3 按照示例代码运行后有glog的WARNING

### ISSUE THREAD

**Issue by dongwlin** [PaddlePaddle/FastDeploy#1783]
*********************************************
温馨提示：根据社区不完全统计，按照模板提问，可以加快回复和解决问题的速度
*********************************************

## 环境

- 【FastDeploy版本】： [fastdeploy-win-x64-1.0.5.zip](https://bj.bcebos.com/fastdeploy/release/cpp/fastdeploy-win-x64-1.0.5.zip)
- 【系统平台】: Windows x64(Windows10)
- 【硬件】： cpu
- 【编译语言】： C++

## 问题日志及出现问题的操作流程

代码是用的PPOCRv3的这份示例代码 [infer_rec.cc](https://github.com/PaddlePaddle/PaddleOCR/blob/dygraph/deploy/fastdeploy/cpu-gpu/cpp/infer_rec.cc)
模型是用 中英文超轻量PP-OCRv3模型的  [识别模型](https://paddleocr.bj.bcebos.com/PP-OCRv3/chinese/ch_PP-OCRv3_rec_infer.tar)
字典文件 [字典](https://gitee.com/paddlepaddle/PaddleOCR/raw/release/2.6/ppocr/utils/ppocr_keys_v1.txt)
vs2022 编译

代码可以正常运行，但是会出现下面这个glog的WARNING

![image](https://user-images.githubusercontent.com/97545700/230734837-91423bb5-36bf-43fc-b79d-841f3b6250eb.png)

**Comment by jiangjiajun** [comment]
忽略即可，不影响
