### ISSUE TITLE
请问Release和Develop有什么区别

### ISSUE THREAD

**Issue by Dandelion111** [PaddlePaddle/FastDeploy#1787]
![image](https://user-images.githubusercontent.com/48303408/230836290-b1d262a5-6af9-438a-8df1-b70dcc20f850.png)

**Comment by leiqing1** [comment]
release是正式版本，发版前会进行充分测试。
develop是基于开发版本，每天跟进提交代码自动编译的包，会包含新功能，但是存在不稳定的情况。
