### ISSUE TITLE
segment-anything 能否支持

### ISSUE THREAD

**Issue by monkeycc** [PaddlePaddle/FastDeploy#1791]
https://github.com/facebookresearch/segment-anything
![微信截图_20230410112431](https://user-images.githubusercontent.com/6490927/230864550-7d241b7b-621c-4ab1-ab19-9a0b1a7a8779.png)

一切都能分割

分割任何模型 （SAM） 根据输入提示（如点或框）生成高质量的对象蒙版，并可用于为图像中的所有对象生成蒙版。它已经在 11 万张图像和 1 亿个掩码的[数据集](https://segment-anything.com/dataset/index.html)上进行了训练，并且在各种分割任务上具有强大的零镜头性能。

这个已经转换为onnx
怎么用？

**Comment by DefTruth** [comment]
目前暂时不支持哈。

**Comment by umie0128** [comment]
@DefTruth 
目前分类模型的部署C++都不支持.onnx吗？
我需要用HRNet的语义分割来部署.onnx C++
