### ISSUE TITLE
FD onnx推理 报错

### ISSUE THREAD

**Issue by MarsMeng1994** [PaddlePaddle/FastDeploy#1793]
我直接用onnxruntime跑这个模型，可以跑通
然后我自己指定这个跑通的onnxruntime目录，从新编的fd
数据也是一样的
不理解为啥，fd就跑不通了
`
#include "fastdeploy/runtime.h"
#include "/mnt/masimeng/workspace/FastDeploy/build/Linux/x86_64/install/third_libs/install/onnxruntime/include/onnxruntime_cxx_api.h"  // NOLINT

int main(){
    //onnxruntime
    {
    Ort::Env env_ = Ort::Env(ORT_LOGGING_LEVEL_WARNING, "");
    Ort::SessionOptions session_options_ = Ort::SessionOptions();
    std::shared_ptr<Ort::Session> rescore_session_ = std::make_shared<Ort::Session>(
            env_, "asr-test/onnx_model_cpu/decoder.onnx", session_options_);

    Ort::MemoryInfo memory_info =
        Ort::MemoryInfo::CreateCpu(OrtDeviceAllocator, OrtMemTypeCPU);

    std::vector<int64_t> hyps_pad(10*23, 5537);

    std::vector<int64_t> hyps_lens(10, 0);

    std::vector<float> rescore_input(223*512, 0);

    const int64_t decode_input_shape[] = {1, 223, 512};

    const int64_t hyps_pad_shape[] = {10, 23};

    const int64_t hyps_lens_shape[] = {10};

    Ort::Value decode_input_tensor_ = Ort::Value::CreateTensor<float>(
        memory_info, rescore_input.data(), rescore_input.size(),
        decode_input_shape, 3);
    Ort::Value hyps_pad_tensor_ = Ort::Value::CreateTensor<int64_t>(
        memory_info, hyps_pad.data(), hyps_pad.size(), hyps_pad_shape, 2);
    Ort::Value hyps_lens_tensor_ = Ort::Value::CreateTensor<int64_t>(
        memory_info, hyps_lens.data(), hyps_lens.size(), hyps_lens_shape, 1);

    std::vector<Ort::Value> rescore_inputs;

    rescore_inputs.emplace_back(std::move(hyps_pad_tensor_));
    rescore_inputs.emplace_back(std::move(hyps_lens_tensor_));
    rescore_inputs.emplace_back(std::move(decode_input_tensor_));

    std::vector<const char*> rescore_in_names_ = {"hyps","hyps_lens","encoder_out"};
    std::vector<const char*> rescore_out_names_ = {"score","r_score"};
    std::vector<Ort::Value> rescore_outputs = rescore_session_->Run(
        Ort::RunOptions{nullptr}, rescore_in_names_.data(), rescore_inputs.data(),
        rescore_inputs.size(), rescore_out_names_.data(),
        rescore_out_names_.size());
    printf("done\n");
    }
    {
    //fd
    fastdeploy::RuntimeOption runtime_option;
    runtime_option.UseOrtBackend();
    runtime_option.UseCpu();
    runtime_option.SetCpuThreadNum(1);
    runtime_option.SetModelPath("asr-test/onnx_model_cpu/decoder.onnx", "", fastdeploy::ModelFormat::ONNX);
    std::shared_ptr<fastdeploy::Runtime> rescore_ = std::make_shared<fastdeploy::Runtime>();
    rescore_->Init(runtime_option);

    std::vector<int64_t> hyps_pad(10*23, 5537);

    std::vector<int64_t> hyps_lens(10, 0);

    std::vector<float> rescore_input(223*512, 0);

    const std::vector<int64_t> hyps_pad_shape = {10, 23};

    const std::vector<int64_t> hyps_lens_shape = {10};

    const std::vector<int64_t> decode_input_shape = {1, 223, 512};

    fastdeploy::FDTensor hyps_pad_tensor_;
    hyps_pad_tensor_.SetData({10, 23}, fastdeploy::FDDataType::INT64, &hyps_pad);
    fastdeploy::FDTensor hyps_lens_tensor_;
    hyps_lens_tensor_.SetData({10}, fastdeploy::FDDataType::INT64, &hyps_lens);
    fastdeploy::FDTensor decode_input_tensor_;
    decode_input_tensor_.SetData({1, 223, 512}, fastdeploy::FDDataType::FP32, &rescore_input);

    std::vector<fastdeploy::FDTensor> rescore_inputs(3);
    rescore_inputs[0] = std::move(hyps_pad_tensor_);
    rescore_inputs[0].name = "hyps";
    rescore_inputs[1] = std::move(hyps_lens_tensor_);
    rescore_inputs[1].name = "hyps_lens";
    rescore_inputs[2] = std::move(decode_input_tensor_);
    rescore_inputs[2].name = "encoder_out";

    std::vector<fastdeploy::FDTensor> rescore_outputs;
    rescore_->Infer(rescore_inputs, &rescore_outputs);
    }
    return 0;
}
`
![d071ce228e25665d4a29b13953980ad9](https://user-images.githubusercontent.com/24523981/230894158-01990501-7866-4683-b23e-d699f4243e54.png)
![16842e7835f77968c015f354918be953](https://user-images.githubusercontent.com/24523981/230894186-57b652c8-3b7d-43b3-a6c9-550ac949b040.png)

**Comment by DefTruth** [comment]
正在排查中

**Comment by GodIsBoom** [comment]
创建输入的FDTensor时请将data_buffer设置为`vector.data()`
例如：
```
hyps_pad_tensor_.SetData({10, 23}, fastdeploy::FDDataType::INT64, &hyps_pad);
```

改为
```
hyps_pad_tensor_.SetData({10, 23}, fastdeploy::FDDataType::INT64, hyps_pad.data());
```

即可正常进行推理
