### ISSUE TITLE
rk3568板内编译fastdeploy库时报错

### ISSUE THREAD

**Issue by LiangYongAI** [PaddlePaddle/FastDeploy#1794]
root@localhost:/opt/FastDeploy-develop/build# cmake ..  -DENABLE_ORT_BACKEND=ON \
>       -DENABLE_RKNPU2_BACKEND=ON \
>       -DENABLE_VISION=ON \
>       -DRKNN2_TARGET_SOC=RK356X \
>           -DCMAKE_INSTALL_PREFIX=${PWD}/fastdeploy-0.0.0 \
>   -DOPENCV_DIRECTORY=/usr/local
-- The C compiler identification is GNU 9.4.0
-- The CXX compiler identification is GNU 9.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
Downloading file from https://bj.bcebos.com/fastdeploy/third_libs/patchelf-0.15.0-aarch64.tar.gz to /opt/FastDeploy-develop/build/patchelf-0.15.0-aarch64.tar.gz ...
-- [download 5% complete]
-- [download 10% complete]
-- [download 15% complete]
-- [download 20% complete]
-- [download 26% complete]
-- [download 31% complete]
-- [download 36% complete]
-- [download 41% complete]
-- [download 46% complete]
-- [download 51% complete]
-- [download 56% complete]
-- [download 61% complete]
-- [download 67% complete]
-- [download 72% complete]
-- [download 77% complete]
-- [download 82% complete]
-- [download 87% complete]
-- [download 92% complete]
-- [download 97% complete]
-- [download 100% complete]
Decompress file /opt/FastDeploy-develop/build/patchelf-0.15.0-aarch64.tar.gz ...
-- Use the default onnxruntime lib. The ONNXRuntime path: /opt/FastDeploy-develop/build/third_libs/install/onnxruntime
Downloading file from https://bj.bcebos.com/fastdeploy/third_libs/rknpu2_runtime-linux-aarch64-1.4.2b0-RK356X.tgz to /opt/FastDeploy-develop/build/rknpu2_runtime-linux-aarch64-1.4.2b0-RK356X.tgz ...
-- [download 0% complete]
-- [download 1% complete]
-- [download 3% complete]
-- [download 4% complete]
-- [download 5% complete]
-- [download 6% complete]
-- [download 8% complete]
-- [download 9% complete]
-- [download 10% complete]
-- [download 11% complete]
-- [download 12% complete]
-- [download 14% complete]
-- [download 15% complete]
-- [download 16% complete]
-- [download 17% complete]
-- [download 19% complete]
-- [download 20% complete]
-- [download 21% complete]
-- [download 22% complete]
-- [download 24% complete]
-- [download 25% complete]
-- [download 26% complete]
-- [download 27% complete]
-- [download 28% complete]
-- [download 30% complete]
-- [download 31% complete]
-- [download 32% complete]
-- [download 33% complete]
-- [download 35% complete]
-- [download 36% complete]
-- [download 37% complete]
-- [download 38% complete]
-- [download 39% complete]
-- [download 41% complete]
-- [download 42% complete]
-- [download 43% complete]
-- [download 44% complete]
-- [download 46% complete]
-- [download 47% complete]
-- [download 48% complete]
-- [download 49% complete]
-- [download 50% complete]
-- [download 52% complete]
-- [download 53% complete]
-- [download 54% complete]
-- [download 55% complete]
-- [download 57% complete]
-- [download 58% complete]
-- [download 59% complete]
-- [download 60% complete]
-- [download 62% complete]
-- [download 63% complete]
-- [download 64% complete]
-- [download 65% complete]
-- [download 66% complete]
-- [download 68% complete]
-- [download 69% complete]
-- [download 70% complete]
-- [download 71% complete]
-- [download 73% complete]
-- [download 74% complete]
-- [download 75% complete]
-- [download 76% complete]
-- [download 77% complete]
-- [download 79% complete]
-- [download 80% complete]
-- [download 81% complete]
-- [download 82% complete]
-- [download 84% complete]
-- [download 85% complete]
-- [download 86% complete]
-- [download 87% complete]
-- [download 88% complete]
-- [download 90% complete]
-- [download 91% complete]
-- [download 92% complete]
-- [download 93% complete]
-- [download 95% complete]
-- [download 96% complete]
-- [download 97% complete]
-- [download 98% complete]
-- [download 100% complete]
Decompress file /opt/FastDeploy-develop/build/rknpu2_runtime-linux-aarch64-1.4.2b0-RK356X.tgz ...
-- Use the opencv lib specified by user. The OpenCV path: /usr/local
-- Found OpenCV: /usr/local (found version "4.5.1") 
Downloading file from https://bj.bcebos.com/fastdeploy/third_libs/protobuf-linux-aarch64-3.16.0.tgz to /opt/FastDeploy-develop/build/protobuf-linux-3.16.0.tgz ...
-- [download 0% complete]
-- [download 1% complete]
-- [download 2% complete]
-- [download 3% complete]
-- [download 4% complete]
-- [download 5% complete]
-- [download 6% complete]
-- [download 7% complete]
-- [download 8% complete]
-- [download 9% complete]
-- [download 10% complete]
-- [download 11% complete]
-- [download 12% complete]
-- [download 13% complete]
-- [download 14% complete]
-- [download 15% complete]
-- [download 16% complete]
-- [download 17% complete]
-- [download 18% complete]
-- [download 19% complete]
-- [download 20% complete]
-- [download 21% complete]
-- [download 22% complete]
-- [download 23% complete]
-- [download 24% complete]
-- [download 25% complete]
-- [download 26% complete]
-- [download 27% complete]
-- [download 28% complete]
-- [download 29% complete]
-- [download 30% complete]
-- [download 31% complete]
-- [download 32% complete]
-- [download 33% complete]
-- [download 34% complete]
-- [download 35% complete]
-- [download 36% complete]
-- [download 37% complete]
-- [download 38% complete]
-- [download 39% complete]
-- [download 40% complete]
-- [download 41% complete]
-- [download 42% complete]
-- [download 43% complete]
-- [download 44% complete]
-- [download 45% complete]
-- [download 46% complete]
-- [download 47% complete]
-- [download 48% complete]
-- [download 49% complete]
-- [download 50% complete]
-- [download 51% complete]
-- [download 52% complete]
-- [download 53% complete]
-- [download 54% complete]
-- [download 55% complete]
-- [download 56% complete]
-- [download 57% complete]
-- [download 58% complete]
-- [download 59% complete]
-- [download 60% complete]
-- [download 61% complete]
-- [download 62% complete]
-- [download 63% complete]
-- [download 64% complete]
-- [download 65% complete]
-- [download 66% complete]
-- [download 67% complete]
-- [download 68% complete]
-- [download 69% complete]
-- [download 70% complete]
-- [download 71% complete]
-- [download 72% complete]
-- [download 73% complete]
-- [download 74% complete]
-- [download 75% complete]
-- [download 76% complete]
-- [download 77% complete]
-- [download 78% complete]
-- [download 79% complete]
-- [download 80% complete]
-- [download 81% complete]
-- [download 82% complete]
-- [download 83% complete]
-- [download 84% complete]
-- [download 85% complete]
-- [download 86% complete]
-- [download 87% complete]
-- [download 88% complete]
-- [download 89% complete]
-- [download 90% complete]
-- [download 91% complete]
-- [download 92% complete]
-- [download 93% complete]
-- [download 94% complete]
-- [download 95% complete]
-- [download 96% complete]
-- [download 97% complete]
-- [download 98% complete]
-- [download 99% complete]
-- [download 100% complete]
Decompress file /opt/FastDeploy-develop/build/protobuf-linux-3.16.0.tgz ...
-- Build type not set - defaulting to Release
-- Found PythonInterp: /usr/bin/python (found version "2.7.18") 
-- Found PythonLibs: /usr/lib/aarch64-linux-gnu/libpython2.7.so (found version "2.7.18") 
-- Found Protobuf: /opt/FastDeploy-develop/build/third_libs/protobuf/lib/libprotobuf.a (found version "3.16.0") 
Generated: /opt/FastDeploy-develop/build/third_party/onnx/onnx/onnx_paddle2onnx-ml.proto
Generated: /opt/FastDeploy-develop/build/third_party/onnx/onnx/onnx-operators_paddle2onnx-ml.proto
Generated: /opt/FastDeploy-develop/build/third_party/onnx/onnx/onnx-data_paddle2onnx.proto
-- 
-- ******** Summary ********
--   CMake version             : 3.16.3
--   CMake command             : /usr/bin/cmake
--   System                    : Linux
--   C++ compiler              : /usr/bin/c++
--   C++ compiler version      : 9.4.0
--   CXX flags                 : -Wno-format -g0 -O3 -Wnon-virtual-dtor
--   Build type                : Release
--   Compile definitions       : _GLIBCXX_USE_CXX11_ABI=1;FASTDEPLOY_LIB;CMAKE_BUILD_TYPE=Release;ENABLE_ORT_BACKEND;ENABLE_RKNPU2_BACKEND;ENABLE_VISION;ENABLE_PADDLE2ONNX;MAX_ONNX_OPSET_VERSION=16;PADDLE2ONNX_LIB;ONNX_NAMESPACE=paddle2onnx;__STDC_FORMAT_MACROS
--   CMAKE_PREFIX_PATH         : 
--   CMAKE_INSTALL_PREFIX      : /opt/FastDeploy-develop/build/fastdeploy-0.0.0
--   CMAKE_MODULE_PATH         : 
-- 
--   ONNX version              : 1.11.0
--   ONNX NAMESPACE            : paddle2onnx
--   ONNX_USE_LITE_PROTO       : OFF
--   USE_PROTOBUF_SHARED_LIBS  : OFF
--   Protobuf_USE_STATIC_LIBS  : ON
--   ONNX_DISABLE_EXCEPTIONS   : OFF
--   ONNX_WERROR               : OFF
--   ONNX_BUILD_TESTS          : OFF
--   ONNX_BUILD_BENCHMARKS     : OFF
--   ONNXIFI_DUMMY_BACKEND     : OFF
--   ONNXIFI_ENABLE_EXT        : OFF
-- 
--   Protobuf compiler         : /opt/FastDeploy-develop/build/third_libs/protobuf/bin/protoc
--   Protobuf includes         : /opt/FastDeploy-develop/build/third_libs/protobuf/include
--   Protobuf libraries        : /opt/FastDeploy-develop/build/third_libs/protobuf/lib/libprotobuf.a
--   BUILD_ONNX_PYTHON         : OFF
-- 
-- *************FastDeploy Building Summary**********
--   CMake version             : 3.16.3
--   CMake command             : /usr/bin/cmake
--   System                    : Linux
--   C++ compiler              : /usr/bin/c++
--   C++ compiler version      : 9.4.0
--   CXX flags                 : -Wno-format -g0 -O3
--   EXE linker flags          : 
--   Shared linker flags       : 
--   Build type                : Release
--   Compile definitions       : _GLIBCXX_USE_CXX11_ABI=1;FASTDEPLOY_LIB;CMAKE_BUILD_TYPE=Release;ENABLE_ORT_BACKEND;ENABLE_RKNPU2_BACKEND;ENABLE_VISION;ENABLE_PADDLE2ONNX;MAX_ONNX_OPSET_VERSION=16;PADDLE2ONNX_LIB;ONNX_NAMESPACE=paddle2onnx
--   CMAKE_PREFIX_PATH         : 
--   CMAKE_INSTALL_PREFIX      : /opt/FastDeploy-develop/build/fastdeploy-0.0.0
--   CMAKE_MODULE_PATH         : 
-- 
--   FastDeploy version        : 0.0.0
--   ENABLE_ORT_BACKEND        : ON
--   ENABLE_RKNPU2_BACKEND     : ON
--   ENABLE_SOPHGO_BACKEND     : OFF
--   ENABLE_PADDLE_BACKEND     : OFF
--   ENABLE_LITE_BACKEND       : OFF
--   ENABLE_POROS_BACKEND      : OFF
--   ENABLE_TRT_BACKEND        : OFF
--   ENABLE_OPENVINO_BACKEND   : OFF
--   ENABLE_BENCHMARK          : OFF
--   ENABLE_VISION             : ON
--   ENABLE_TEXT               : OFF
--   ENABLE_ENCRYPTION         : OFF
--   ENABLE_FLYCV              : OFF
--   ENABLE_CVCUDA             : OFF
--   WITH_GPU                  : OFF
--   WITH_IPU                  : OFF
--   WITH_TESTING              : OFF
--   WITH_ASCEND               : OFF
--   WITH_DIRECTML             : OFF
--   WITH_TIMVX                : OFF
--   WITH_KUNLUNXIN            : OFF
--   WITH_CAPI                 : OFF
--   WITH_CSHARPAPI            : OFF
--   ONNXRuntime version       : 1.12.0
-- Configuring done
-- Generating done
-- Build files have been written to: /opt/FastDeploy-develop/build
root@localhost:/opt/FastDeploy-develop/build# make -j4
[  0%] Running cpp protocol buffer compiler on p2o_paddle.proto
Scanning dependencies of target extern_onnxruntime
Scanning dependencies of target gen_onnx_proto
Scanning dependencies of target yaml-cpp
[  0%] Running gen_proto.py on onnx/onnx.in.proto
[  0%] Creating directories for 'extern_onnxruntime'
  File "/opt/FastDeploy-develop/third_party/onnx/onnx/gen_proto.py", line 36
    def process_ifs(lines: Iterable[Text], onnx_ml: bool) -> Iterable[Text]:
                         ^
SyntaxError: invalid syntax
make[2]: *** [third_party/onnx/CMakeFiles/gen_onnx_proto.dir/build.make:69: third_party/onnx/onnx/onnx_paddle2onnx-ml.proto] Error 1
make[1]: *** [CMakeFiles/Makefile2:581: third_party/onnx/CMakeFiles/gen_onnx_proto.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[  0%] Building CXX object third_party/yaml-cpp/CMakeFiles/yaml-cpp.dir/src/contrib/graphbuilder.cpp.o
[  1%] Building CXX object third_party/yaml-cpp/CMakeFiles/yaml-cpp.dir/src/contrib/graphbuilderadapter.cpp.o
Scanning dependencies of target p2o_paddle_proto
[  1%] Building CXX object paddle2onnx/proto/CMakeFiles/p2o_paddle_proto.dir/p2o_paddle.pb.cc.o
[  1%] Performing download step (download, verify and extract) for 'extern_onnxruntime'
-- Downloading...
   dst='/opt/FastDeploy-develop/build/third_libs/onnxruntime/src/onnxruntime-linux-aarch64-1.12.0.tgz'
   timeout='none'
-- Using src='https://bj.bcebos.com/paddle2onnx/libs/onnxruntime-linux-aarch64-1.12.0.tgz'
[  1%] Building CXX object third_party/yaml-cpp/CMakeFiles/yaml-cpp.dir/src/binary.cpp.o
[  1%] Building CXX object third_party/yaml-cpp/CMakeFiles/yaml-cpp.dir/src/convert.cpp.o
[  1%] Building CXX object third_party/yaml-cpp/CMakeFiles/yaml-cpp.dir/src/depthguard.cpp.o
-- Downloading... done
-- extracting...
     src='/opt/FastDeploy-develop/build/third_libs/onnxruntime/src/onnxruntime-linux-aarch64-1.12.0.tgz'
     dst='/opt/FastDeploy-develop/build/third_libs/onnxruntime/src/extern_onnxruntime'
-- extracting... [tar xfz]
-- extracting... [analysis]
-- extracting... [rename]
-- extracting... [clean up]
-- extracting... done
[  1%] No patch step for 'extern_onnxruntime'
[  2%] No update step for 'extern_onnxruntime'
[  2%] No configure step for 'extern_onnxruntime'
[  2%] No build step for 'extern_onnxruntime'
[  2%] Performing install step for 'extern_onnxruntime'
[  2%] Completed 'extern_onnxruntime'
[  2%] Built target extern_onnxruntime
[  3%] Building CXX object third_party/yaml-cpp/CMakeFiles/yaml-cpp.dir/src/directives.cpp.o
[  3%] Building CXX object third_party/yaml-cpp/CMakeFiles/yaml-cpp.dir/src/emit.cpp.o
[  3%] Building CXX object third_party/yaml-cpp/CMakeFiles/yaml-cpp.dir/src/emitfromevents.cpp.o
[  3%] Building CXX object third_party/yaml-cpp/CMakeFiles/yaml-cpp.dir/src/emitter.cpp.o
[  4%] Building CXX object third_party/yaml-cpp/CMakeFiles/yaml-cpp.dir/src/emitterstate.cpp.o
[  4%] Building CXX object third_party/yaml-cpp/CMakeFiles/yaml-cpp.dir/src/emitterutils.cpp.o
[  4%] Building CXX object third_party/yaml-cpp/CMakeFiles/yaml-cpp.dir/src/exceptions.cpp.o
[  4%] Building CXX object third_party/yaml-cpp/CMakeFiles/yaml-cpp.dir/src/exp.cpp.o
[  5%] Building CXX object third_party/yaml-cpp/CMakeFiles/yaml-cpp.dir/src/memory.cpp.o
[  5%] Building CXX object third_party/yaml-cpp/CMakeFiles/yaml-cpp.dir/src/node.cpp.o
[  5%] Building CXX object third_party/yaml-cpp/CMakeFiles/yaml-cpp.dir/src/node_data.cpp.o
[  5%] Building CXX object third_party/yaml-cpp/CMakeFiles/yaml-cpp.dir/src/nodebuilder.cpp.o
[  6%] Building CXX object third_party/yaml-cpp/CMakeFiles/yaml-cpp.dir/src/nodeevents.cpp.o
[  6%] Building CXX object third_party/yaml-cpp/CMakeFiles/yaml-cpp.dir/src/null.cpp.o
[  6%] Building CXX object third_party/yaml-cpp/CMakeFiles/yaml-cpp.dir/src/ostream_wrapper.cpp.o
[  6%] Linking CXX static library libp2o_paddle_proto.a
[  6%] Built target p2o_paddle_proto
[  6%] Building CXX object third_party/yaml-cpp/CMakeFiles/yaml-cpp.dir/src/parse.cpp.o
[  7%] Building CXX object third_party/yaml-cpp/CMakeFiles/yaml-cpp.dir/src/parser.cpp.o
[  7%] Building CXX object third_party/yaml-cpp/CMakeFiles/yaml-cpp.dir/src/regex_yaml.cpp.o
[  7%] Building CXX object third_party/yaml-cpp/CMakeFiles/yaml-cpp.dir/src/scanner.cpp.o
[  7%] Building CXX object third_party/yaml-cpp/CMakeFiles/yaml-cpp.dir/src/scanscalar.cpp.o
[  8%] Building CXX object third_party/yaml-cpp/CMakeFiles/yaml-cpp.dir/src/scantag.cpp.o
[  8%] Building CXX object third_party/yaml-cpp/CMakeFiles/yaml-cpp.dir/src/scantoken.cpp.o
[  8%] Building CXX object third_party/yaml-cpp/CMakeFiles/yaml-cpp.dir/src/simplekey.cpp.o
[  8%] Building CXX object third_party/yaml-cpp/CMakeFiles/yaml-cpp.dir/src/singledocparser.cpp.o
[  9%] Building CXX object third_party/yaml-cpp/CMakeFiles/yaml-cpp.dir/src/stream.cpp.o
[  9%] Building CXX object third_party/yaml-cpp/CMakeFiles/yaml-cpp.dir/src/tag.cpp.o
[  9%] Linking CXX static library libyaml-cpp.a
[  9%] Built target yaml-cpp
make: *** [Makefile:152: all] Error 2

**Comment by Zheng-Bicheng** [comment]
用交叉编译试一下

**Comment by Zheng-Bicheng** [comment]
`docs/cn/build_and_install/rknpu2.md`
