### ISSUE TITLE
fastdeploy import 导入期 提示 初始化失败

### ISSUE THREAD

**Issue by sanbuphy** [PaddlePaddle/FastDeploy#1798]
*********************************************
温馨提示：根据社区不完全统计，按照模板提问，可以加快回复和解决问题的速度
*********************************************

## 环境

- 【FastDeploy版本】： fastdeploy-linux-gpu-1.0.5

- 【系统平台】: Linux x64(Ubuntu 20.04)
- 【硬件】： 3060 
- 【编译语言】：python3.7

## 问题日志及出现问题的操作流程
安装fd结束后，如果不安装paddle可以正常import，
如果装了paddle（无论是2.4.2还是2.4.0，无论是gpu还是cpu），就会import期出错：（有可能遇到这两种错误）
![8db913d4a2280d9ebaa436219022d64](https://user-images.githubusercontent.com/96160062/231103243-9dab3a5c-e481-49c1-8f73-52674aaa85ab.png)

![727be60d0389da08e91d710fcf17edf](https://user-images.githubusercontent.com/96160062/231103317-73cf1019-dab7-46f4-b1b5-bc340e988ef4.png)

怀疑是paddleinfer相关出现冲突，**不过1.0.4版本是可以正常使用的**

**Comment by DefTruth** [comment]
目前需要升级paddle到最新版本，这个问题，我们正在优化中。

**Comment by sanbuphy** [comment]
> 目前需要升级paddle到最新版本，这个问题，我们正在优化中。

收到，请问最新版本指的是develop吗？我试试看

**Comment by sanbuphy** [comment]
刚测试了，develop也挂了，报错是：
![e78c129f61871a56c589de1ada4cd7e](https://user-images.githubusercontent.com/96160062/231114925-73143f10-1111-45ad-8d85-7e6abf8c4bef.png)

**Comment by DefTruth** [comment]
可以安装FD dev包试一下哈：
```bash
pip install fastdeploy-gpu-python==0.0.0 -f https://www.paddlepaddle.org.cn/whl/fastdeploy_nightly_build.html --no-cache
```

**Comment by DefTruth** [comment]
paddle dev安装可以运行：  
```bash
python -m pip install paddlepaddle-gpu==0.0.0.post112 -f https://www.paddlepaddle.org.cn/whl/linux/gpu/develop.html --no-cache
```

**Comment by sanbuphy** [comment]
dev安装版的可以正常导入 👍
