### ISSUE TITLE
python 3.10 for windows 64bit的版本的whl安装包,谢谢!

### ISSUE THREAD

**Issue by blueicesir** [PaddlePaddle/FastDeploy#180]
不知道合适方便编译一个 python 3.10 for windows 64bit的版本的whl安装包,谢谢!

**Comment by DefTruth** [comment]
请问您是希望使用cpu版本的包还是gpu版本的呢？

**Comment by jiangjiajun** [comment]
此ISSUE由于一年未更新，将会关闭处理，如有需要，可再次更新打开。
