### ISSUE TITLE
YOLOV8 ONNX 分类 ,怎么获取标签名

### ISSUE THREAD

**Issue by monkeycc** [PaddlePaddle/FastDeploy#1801]
YOLOV8 ONNX 分类 ,怎么获取标签名

我看都是 0 1  2  3  4  5

怎么看 对应的标签名称

yolov8中的数据集 
是分类的数据集

那么是按照什么排序的名称？

**Comment by smalie2222** [comment]
您好，我也想知道这个，请问您解决了吗
