### ISSUE TITLE
Jetson Xavier NX部署PP-OCRv3模型过程中出现的问题?

### ISSUE THREAD

**Issue by MrMzl** [PaddlePaddle/FastDeploy#1802]
## 环境

- 【FastDeploy版本】：fastdeploy-develop最新版
- 【硬件】： Jetson Xavier NX（Linux aarch64）
- 【编译语言】： Python
- 【其他环境包】：Jetpack 4.6.3、CUDA：10.2.300、cuDNN：8.2.1.32、TensorRT：8.2、OpenCV：4.1.1

## 问题日志及出现问题的操作流程
- 【模型跑不通】
- - 按照[Jetson环境部署文档](https://github.com/PaddlePaddle/FastDeploy/blob/develop/docs/cn/build_and_install/jetson.md)正常实现环境编译与安装。
- - [按照官方提供的部署文档](https://github.com/PaddlePaddle/FastDeploy/tree/develop/examples/vision/ocr/PP-OCR/cpu-gpu/python)，执行`examples`下的部署示例，CPU下用Paddle Inference、ONNX Runtime；GPU下用ONNX Runtime 可以正常推理。但是利用其他推理后端进行推理有问题，具体如下：
- - 错误一：GPU上利用Paddle Inference推理，识别结果是乱码，图片上检测框错误；
- - 推理代码：`python infer.py --det_model ch_PP-OCRv3_det_infer --cls_model ch_ppocr_mobile_v2.0_cls_infer --rec_model ch_PP-OCRv3_rec_infer --rec_label_file ppocr_keys_v1.txt --image 12.jpg --device gpu --backend paddle`
- - 推理结果：`[INFO] fastdeploy/runtime/runtime.cc(266)::CreatePaddleBackend	Runtime initialized with Backend::PDINFER in Device::GPU.
[INFO] fastdeploy/runtime/runtime.cc(266)::CreatePaddleBackend	Runtime initialized with Backend::PDINFER in Device::GPU.
[INFO] fastdeploy/runtime/runtime.cc(266)::CreatePaddleBackend	Runtime initialized with Backend::PDINFER in Device::GPU.
Predict Time: 5268.916845321655
det boxes: [[0,22],[719,21],[719,33],[0,34]]rec text: 愛榈丫榈梦跆榈’榈語榈恢術榈协榈’榈租榈撕榈甜榈é＃榈±石甜榈é rec score:0.000509 cls label: 0 cls score: 0.000000
det boxes: [[0,107],[719,106],[719,118],[0,119]]rec text: 榈恢術榈恢梵榈俭榈俭榈泌榈榈撑飛榈俭榈跆榈é榈恢榈團榈俭榈俭榈語榈恢榈恢榈丫榈△榈俭榈恢榈紊榈網榈鉴榈纵榈榈#闯榈俭榈甜榈é洞榈丫榈甜榈é榈恢榈’洞榈俪榈 rec score:0.000292 cls label: 0 cls score: 0.000000
det boxes: [[0,111],[719,111],[719,642],[0,642]]rec text: 榈榈'丫汪藤榈μｅ次梵榈鏡榈撑俭榈鏡榈忌榈éμe单β楼旗交愛榈丫榈粱榈闯榈纵榈=榈汪榈紊榈次梵榈丫榈語榈恢術榈协跆榈撑榈庐榈紊榈#丫紊榈俭鏡ｌ榈纵榈租榈撑甜榈é洞榈俭榈丫宋焗榈甜榈é丫紊榈汪鏡榈协##網榈 rec score:0.000370 cls label: 0 cls score: 0.000000
det boxes: [[0,123],[719,123],[719,131],[0,131]]rec text: 榈恢術榈恢梵榈俭榈俭榈泌榈榈撑飛榈俭榈跆榈é榈恢榈團榈俭榈俭榈語榈恢榈恢榈丫榈△榈俭榈恢榈紊榈網榈鉴榈纵榈榈#闯榈俭榈甜榈é洞榈丫榈甜榈é榈恢榈’洞榈俪榈 rec score:0.000292 cls label: 0 cls score: 0.000000
det boxes: [[0,162],[719,162],[719,249],[0,249]]rec text: 榈榈'榈次梵榈鏡榈撑榈忌榈0A拉交愛榈丫榈粱榈闯榈纵榈=榈次梵榈丫榈語榈恢術榈协跆榈撑榈庐榈#榈ｌ榈纵榈租榈撑甜榈é洞榈俭榈丫宋焗榈甜榈é榈协網榈 rec score:0.000457 cls label: 0 cls score: 0.000000 `
- - 推理结果图：
![ffa028abe6b12b8ca08ad7a7ae0ff6b](https://user-images.githubusercontent.com/85120075/231191864-8a3d11f7-92f2-4a04-a02e-578dffd02e0a.jpg)

- - 错误二：GPU上使用Paddle TensorRT进行推理，出现推理错误：Segmentation fault (core dumped) 
- - 推理代码：`python infer.py --det_model ch_PP-OCRv3_det_infer --cls_model ch_ppocr_mobile_v2.0_cls_infer --rec_model ch_PP-OCRv3_rec_infer --rec_label_file ppocr_keys_v1.txt --image 12.jpg --device gpu --backend pptrt`
- - 推理结果：`WARNING:root:`RuntimeOption.set_trt_input_shape` will be deprecated in v1.2.0, please use `RuntimeOption.trt_option.set_shape()` instead.
WARNING:root:`RuntimeOption.set_trt_input_shape` will be deprecated in v1.2.0, please use `RuntimeOption.trt_option.set_shape()` instead.
WARNING:root:`RuntimeOption.set_trt_input_shape` will be deprecated in v1.2.0, please use `RuntimeOption.trt_option.set_shape()` instead.
WARNING:root:`RuntimeOption.set_trt_cache_file` will be deprecated in v1.2.0, please use `RuntimeOption.trt_option.serialize_file = ch_PP-OCRv3_det_infer` instead.
WARNING:root:`RuntimeOption.set_trt_cache_file` will be deprecated in v1.2.0, please use `RuntimeOption.trt_option.serialize_file = ch_ppocr_mobile_v2.0_cls_infer` instead.
WARNING:root:`RuntimeOption.set_trt_cache_file` will be deprecated in v1.2.0, please use `RuntimeOption.trt_option.serialize_file = ch_PP-OCRv3_rec_infer` instead.
[INFO] fastdeploy/runtime/backends/paddle/paddle_backend.cc(37)::BuildOption	Will try to use tensorrt inference with Paddle Backend.
[WARNING] fastdeploy/runtime/backends/paddle/paddle_backend.cc(49)::BuildOption	Detect that tensorrt cache file has been set to ch_PP-OCRv3_det_infer, but while enable paddle2trt, please notice that the cache file will save to the directory where paddle model saved.
[INFO] fastdeploy/runtime/backends/paddle/paddle_backend.cc(395)::GetDynamicShapeFromOption	x: the max shape = [1, 3, 960, 960], the min shape = [1, 3, 64, 64], the opt shape = [1, 3, 640, 640]
[INFO] fastdeploy/runtime/backends/paddle/paddle_backend.cc(358)::SetTRTDynamicShapeToConfig	Start setting trt dynamic shape.
[INFO] fastdeploy/runtime/backends/paddle/paddle_backend.cc(360)::SetTRTDynamicShapeToConfig	Finish setting trt dynamic shape.
[INFO] fastdeploy/runtime/backends/paddle/paddle_backend.cc(235)::InitFromPaddle	Start loading shape range info file ch_PP-OCRv3_det_infer/shape_range_info.pbtxt to set TensorRT dynamic shape.
6_gpu_infer_ptrt.sh: line 1:   565 Segmentation fault      (core dumped) python infer.py --det_model ch_PP-OCRv3_det_infer --cls_model ch_ppocr_mobile_v2.0_cls_infer --rec_model ch_PP-OCRv3_rec_infer --rec_label_file ppocr_keys_v1.txt --image 12.jpg --device gpu --backend pptrt`

- - 错误三：GPU上使用TensorRT进行推理，出现TRTBackend SetInputs not find name:x的错误
- - 推理代码：`python infer.py --det_model ch_PP-OCRv3_det_infer --cls_model ch_ppocr_mobile_v2.0_cls_infer --rec_model ch_PP-OCRv3_rec_infer --rec_label_file ppocr_keys_v1.txt --image 12.jpg --device gpu --backend trt`
- - 推理结果：`WARNING:root:`RuntimeOption.set_trt_input_shape` will be deprecated in v1.2.0, please use `RuntimeOption.trt_option.set_shape()` instead.
WARNING:root:`RuntimeOption.set_trt_input_shape` will be deprecated in v1.2.0, please use `RuntimeOption.trt_option.set_shape()` instead.
WARNING:root:`RuntimeOption.set_trt_input_shape` will be deprecated in v1.2.0, please use `RuntimeOption.trt_option.set_shape()` instead.
WARNING:root:`RuntimeOption.set_trt_cache_file` will be deprecated in v1.2.0, please use `RuntimeOption.trt_option.serialize_file = ch_PP-OCRv3_det_infer/det_trt_cache.trt` instead.
WARNING:root:`RuntimeOption.set_trt_cache_file` will be deprecated in v1.2.0, please use `RuntimeOption.trt_option.serialize_file = ch_ppocr_mobile_v2.0_cls_infer/cls_trt_cache.trt` instead.
WARNING:root:`RuntimeOption.set_trt_cache_file` will be deprecated in v1.2.0, please use `RuntimeOption.trt_option.serialize_file = ch_PP-OCRv3_rec_infer/rec_trt_cache.trt` instead.
[INFO] fastdeploy/runtime/backends/tensorrt/trt_backend.cc(702)::CreateTrtEngineFromOnnx	Detect serialized TensorRT Engine file in ch_PP-OCRv3_det_infer/det_trt_cache.trt, will load it directly.
[INFO] fastdeploy/runtime/backends/tensorrt/trt_backend.cc(108)::LoadTrtCache	Build TensorRT Engine from cache file: ch_PP-OCRv3_det_infer/det_trt_cache.trt with shape range information as below,
[INFO] fastdeploy/runtime/backends/tensorrt/trt_backend.cc(111)::LoadTrtCache	Input name: x, shape=[-1, 3, -1, -1], min=[1, 3, 64, 64], max=[1, 3, 960, 960]

[INFO] fastdeploy/runtime/runtime.cc(306)::CreateTrtBackend	Runtime initialized with Backend::TRT in Device::GPU.
[INFO] fastdeploy/runtime/backends/tensorrt/trt_backend.cc(702)::CreateTrtEngineFromOnnx	Detect serialized TensorRT Engine file in ch_ppocr_mobile_v2.0_cls_infer/cls_trt_cache.trt, will load it directly.
[INFO] fastdeploy/runtime/backends/tensorrt/trt_backend.cc(108)::LoadTrtCache	Build TensorRT Engine from cache file: ch_ppocr_mobile_v2.0_cls_infer/cls_trt_cache.trt with shape range information as below,
[INFO] fastdeploy/runtime/backends/tensorrt/trt_backend.cc(111)::LoadTrtCache	Input name: x, shape=[-1, 3, -1, -1], min=[1, 3, 48, 10], max=[1, 3, 48, 1024]

`[INFO] fastdeploy/runtime/runtime.cc(306)::CreateTrtBackend	Runtime initialized with Backend::TRT in Device::GPU.
[INFO] fastdeploy/runtime/backends/tensorrt/trt_backend.cc(556)::BuildTrtEngine	Start to building TensorRT Engine...
[ERROR] fastdeploy/runtime/backends/tensorrt/trt_backend.cc(239)::log	10: [optimizer.cpp::computeCosts::2011] Error Code 10: Internal Error (Could not find any implementation for node {ForeignNode[linear_13.w_0 + (Unnamed Layer* 321) [Shuffle]...p2o.Reshape.23 + p2o.Transpose.7]}.)
[ERROR] fastdeploy/runtime/backends/tensorrt/trt_backend.cc(239)::log	2: [builder.cpp::buildSerializedNetwork::609] Error Code 2: Internal Error (Assertion enginePtr != nullptr failed. )
[ERROR] fastdeploy/runtime/backends/tensorrt/trt_backend.cc(619)::BuildTrtEngine	Failed to call buildSerializedNetwork().
[ERROR] fastdeploy/runtime/backends/tensorrt/trt_backend.cc(735)::CreateTrtEngineFromOnnx	Failed to build tensorrt engine.
[INFO] fastdeploy/runtime/runtime.cc(306)::CreateTrtBackend	Runtime initialized with Backend::TRT in Device::GPU.
[ERROR] fastdeploy/runtime/backends/tensorrt/trt_backend.cc(447)::SetInputs	TRTBackend SetInputs not find name:x
5_gpu_infer_trt.sh: line 1:   974 Aborted                 (core dumped) python infer.py --det_model ch_PP-OCRv3_det_infer --cls_model ch_ppocr_mobile_v2.0_cls_infer --rec_model ch_PP-OCRv3_rec_infer --rec_label_file ppocr_keys_v1.txt --image 12.jpg --device gpu --backend trt

C++方式下的部署，上述三种推理后端进行推理也存在相同问题。

**Comment by MrMzl** [comment]
@DefTruth @wang-xinyu 两位老师，这个问题能复现嘛？

**Comment by DefTruth** [comment]
使用的模型是FD里边提供的吗？

**Comment by MrMzl** [comment]
是的，用官方模型跑的example



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年04月17日 12:53 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [PaddlePaddle/FastDeploy] Jetson Xavier NX部署PP-OCRv3模型过程中出现的问题? (Issue #1802) |

使用的模型是FD里边提供的吗？

**Comment by DefTruth** [comment]
CUDA 11.2 +有试过吗？我们暂时没有适配CUDA 10.2，目前的测试都是基于CUDA 11.2+的

**Comment by jiangjiajun** [comment]
看起来出现乱码是你的环境编码问题，建议检查下命令终端的编码设置
