### ISSUE TITLE
请问自己编译的x86 cpu版本怎么用不了呢

### ISSUE THREAD

**Issue by Dandelion111** [PaddlePaddle/FastDeploy#1803]
![image](https://user-images.githubusercontent.com/48303408/231319988-2473bae3-1716-4214-a149-56c7c6d6ce56.png)
分别用x64 Native Tools Command Prompt for VS 2019和cmake-gui的方式编译了，都报这个错误，而且把编译完的所有dll都拷贝到了程序的根目录
![image](https://user-images.githubusercontent.com/48303408/231320222-2a382444-d467-4fb3-be55-03a5230cec91.png)
编译过程都是按照文档一步一步走的，请大佬帮忙分析一下
我试了下预编译的库也是这个问题，代码中只要包含fastdeploy::RuntimeOption option;就不行

**Comment by DefTruth** [comment]
源码都改成英文试一下？

**Comment by DefTruth** [comment]
依赖库的管理可以参考这个文档：
- https://github.com/PaddlePaddle/FastDeploy/blob/develop/docs/cn/faq/usage_of_fastdeploy_init_bat.md

**Comment by Dandelion111** [comment]
> 依赖库的管理可以参考这个文档：
> 
> * https://github.com/PaddlePaddle/FastDeploy/blob/develop/docs/cn/faq/usage_of_fastdeploy_init_bat.md

谢谢大佬，刚刚根据这个文档操作了一下可以了，之前应该是有一些依赖文件没有处理好
