### ISSUE TITLE
用paddlelite做为后端编译的fastdeploy推理时遇到问题。

### ISSUE THREAD

**Issue by 996-icu-FuJian** [PaddlePaddle/FastDeploy#1814]
使用fastdeployserver命令运行在ARMV8处理器的设备上（aarch64 ubuntu18.04 triton22.05 无gpu）时产生了这个报错“UNAVAILABLE: Invalid argument: unknown cpu_execution_accelerator name 'paddle-lite' is provided. Available choices are [onnxruntime, paddle, openvino]” 我的模型无法转为onnxruntime，paddle不支持aarch。要怎么解决使用paddle-lite后端的问题呢？

**Comment by DefTruth** [comment]
FD是可以通过paddlelite来支持在aarch64上推理的。请问您的CPU型号、fastdeploy编译命令以及跑的模型是什么呢？

**Comment by 996-icu-FuJian** [comment]
> FD是可以通过paddlelite来支持在aarch64上推理的。请问您的CPU型号、fastdeploy编译命令以及跑的模型是什么呢？

你好！感谢你的回复！这是我的CPU型号、编译命令、跑的模型：
1、CPU型号：
    鲲鹏920
2、编译命令：

    # cd /workspace/FastDeploy/build
    # cmake .. -DENABLE_TRT_BACKEND=OFF -DCMAKE_INSTALL_PREFIX=${PWD}/fastdeploy_install -DWITH_GPU=OFF -DENABLE_PADDLE_BACKEND=OFF -DENABLE_LITE_BACKEND=ON -DENABLE_ORT_BACKEND=ON -DENABLE_OPENVINO_BACKEND=OFF -DENABLE_VISION=OFF -DBUILD_FASTDEPLOY_PYTHON=OFF -DENABLE_PADDLE2ONNX=ON -DENABLE_TEXT=OFF -DLIBRARY_NAME=fastdeploy_runtime
    # make TARGET=ARMV8 -j$(nproc)
    # make install

    # cd /workspace/FastDeploy/serving/build
    # cmake .. -DTRITON_ENABLE_GPU=OFF -DFASTDEPLOY_DIR=/workspace/FastDeploy/build/fastdeploy_install -DTRITON_COMMON_REPO_TAG=r22.05 -DTRITON_CORE_REPO_TAG=r22.05 -DTRITON_BACKEND_REPO_TAG=r22.05
    # make -j`nproc`
3、跑的模型是paddlenlp的"dependency_parsing"模型，该模型在 FD 的x86环境下已经验证过可以运行
4、运行方式

    fastdeployserver --model-repository=/serving/models/ --model-control-mode=explicit --load-model=dependency --http-port=9000 --grpc-port=9001
