### ISSUE TITLE
训练picodet_s_416目标检测模型，只检测一类数据，在RK3588上使用Python推理，报错 Segmentation fault

### ISSUE THREAD

**Issue by lizheng-1** [PaddlePaddle/FastDeploy#1821]
按照[PaddleDetection RKNPU2部署示例](https://github.com/PaddlePaddle/FastDeploy/blob/develop/examples/vision/detection/paddledetection/rknpu2/README_CN.md)
进行onnx和rknn模型的转换，修改了infer_cfg.yml文件中的label_list，将coco的80类别换成自己一类，其他没改
![image](https://user-images.githubusercontent.com/63158425/231963616-b4e57571-7cee-42fe-84e7-5ec9be259d41.png)

开发板使用Python运行报错如下：
![image](https://user-images.githubusercontent.com/63158425/231962524-0d0cb1bd-f271-4d55-b938-faee5c576505.png)

他输出predict image time了，应该检测成功了吧？但输出目标时为什么报错 Segmentation fault？
-----
我在使用瑞芯微官方给的c++代码部署时，也出现 Segmentation fault 错误了，是修改了postprocess.h中的 OBJ_CLASS_NUM参数，将80改为1就成功了。
这里我是不是也要修改类别参数，应该从哪里修改呢？

**Comment by Zheng-Bicheng** [comment]
`examples/vision/detection/rkyolo/python/README_CN.md`中有介绍

**Comment by Zheng-Bicheng** [comment]
不好意思，我理解错了。你这个picodet是用rknn_model_zoo里的转换脚本转换的模型放到fastdeploy下来部署是吗？
