### ISSUE TITLE
FastDeploy Streamer如何在Edgeboard上使用？

### ISSUE THREAD

**Issue by wpfnlp** [PaddlePaddle/FastDeploy#1825]
您好，我是广东工业大学的老师，我们采购了30套贵公司的Edgeboard，请问FastDeploy Streamer这种视频流方案可以部署到Edgeboard FZ3上吗？请问有没教程，主要为了开设实验课【智慧工厂、智慧工地、智慧校园、等视频监测实验】，锻炼本科学生的动手实践能力。谢谢

**Comment by jiangjiajun** [comment]
目前streamer还没有支持Jetson之外的系列硬件
