### ISSUE TITLE
自己编译完成的fastdeploy python安装包无法正常安装

### ISSUE THREAD

**Issue by Caoxiaocao** [PaddlePaddle/FastDeploy#1828]
![image](https://user-images.githubusercontent.com/15075323/232718323-e8c5e107-416f-4abc-a17d-128e10adba4b.png)
提示fastdeploy-tools>=0.0.5，但是最高只有0.0.2版的

**Comment by liuyingtao941212** [comment]
我也遇到了相同的问题
