### ISSUE TITLE
error: creating server: Internal - failed to load all models

### ISSUE THREAD

**Issue by Cheng-x-c** [PaddlePaddle/FastDeploy#1829]
*********************************************
温馨提示：根据社区不完全统计，按照模板提问，可以加快回复和解决问题的速度
*********************************************

## 环境

- 【FastDeploy版本】： 说明具体的版本，如fastdeploy:1.0.4-cpu-only-21.10
- 【编译命令】如果您是自行编译的FastDeploy，请说明您的编译方式（参数命令）
- 【系统平台】: centos 8 
- 【硬件】： 说明具体硬件型号，如 Nvidia GPU 3080TI， CUDA 11.2 CUDNN 8.3
- 【编译语言】： Python(3.7或3.8等）

## 问题日志及出现问题的操作流程
   按照官方的步骤，用VisualDL可视化界面运行模型跑不起来
- 【模型跑不通】
   
![ecde359c5365c2ce795efd4763d8e10](https://user-images.githubusercontent.com/59717369/232722952-591165ac-1d77-4716-befd-87468c10042e.png)

**Comment by Cheng-x-c** [comment]
完整信息：
E0420 06:26:52.377616 117 model_repository_manager.cc:1890] Poll failed for model directory 'cls_runtime': instance group cls_runtime_0 of model cls_runtime has kind KIND_GPU but server does not support GPUs
E0420 06:26:52.378182 117 model_repository_manager.cc:1890] Poll failed for model directory 'det_runtime': instance group det_runtime_0 of model det_runtime has kind KIND_GPU but server does not support GPUs
E0420 06:26:52.378673 117 model_repository_manager.cc:1890] Poll failed for model directory 'rec_runtime': instance group rec_runtime_0 of model rec_runtime has kind KIND_GPU but server does not support GPUs
E0420 06:26:52.378714 117 model_repository_manager.cc:1375] Invalid argument: ensemble cls_pp contains models that are not available: cls_runtime
E0420 06:26:52.378719 117 model_repository_manager.cc:1375] Invalid argument: ensemble rec_pp contains models that are not available: rec_runtime
E0420 06:26:52.378724 117 model_repository_manager.cc:1375] Invalid argument: ensemble pp_ocr contains models that are not available: det_runtime
I0420 06:26:52.378760 117 model_repository_manager.cc:1022] loading: cls_postprocess:1
I0420 06:26:52.479569 117 model_repository_manager.cc:1022] loading: rec_postprocess:1
I0420 06:26:52.494576 117 python.cc:1875] TRITONBACKEND_ModelInstanceInitialize: cls_postprocess_0 (CPU device 0)
I0420 06:26:52.580598 117 model_repository_manager.cc:1022] loading: det_postprocess:1
I0420 06:26:52.681596 117 model_repository_manager.cc:1022] loading: det_preprocess:1
I0420 06:26:52.955362 117 python.cc:1875] TRITONBACKEND_ModelInstanceInitialize: rec_postprocess_0 (CPU device 0)
I0420 06:26:52.955496 117 model_repository_manager.cc:1183] successfully loaded 'cls_postprocess' version 1
I0420 06:26:53.323405 117 python.cc:1875] TRITONBACKEND_ModelInstanceInitialize: det_preprocess_0 (CPU device 0)
I0420 06:26:53.323423 117 model_repository_manager.cc:1183] successfully loaded 'rec_postprocess' version 1
I0420 06:26:53.666746 117 model_repository_manager.cc:1183] successfully loaded 'det_preprocess' version 1I0420 06:26:53.666961 117 python.cc:1875] TRITONBACKEND_ModelInstanceInitialize: det_postprocess_0 (CPU device 0)

I0420 06:26:53.965936 117 model_repository_manager.cc:1183] successfully loaded 'det_postprocess' version 1
I0420 06:26:53.966220 117 server.cc:522] 
+------------------+------+
| Repository Agent | Path |
+------------------+------+
+------------------+------+

I0420 06:26:53.966247 117 server.cc:549] 
+---------+-------------------------------------------------------+--------------------------------------------------+
| Backend | Path                                                  | Config                                           |
+---------+-------------------------------------------------------+--------------------------------------------------+
| python  | /opt/tritonserver/backends/python/libtriton_python.so | {"cmdline":{"shm-default-byte-size":"10485760"}} |
+---------+-------------------------------------------------------+--------------------------------------------------+

I0420 06:26:53.966273 117 server.cc:592] 
+-----------------+---------+--------+
| Model           | Version | Status |
+-----------------+---------+--------+
| cls_postprocess | 1       | READY  |
| det_postprocess | 1       | READY  |
| det_preprocess  | 1       | READY  |
| rec_postprocess | 1       | READY  |
+-----------------+---------+--------+

I0420 06:26:53.966387 117 tritonserver.cc:1920] 
+----------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Option                           | Value                                                                                                                                                                                  |
+----------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| server_id                        | triton                                                                                                                                                                                 |
| server_version                   | 2.15.0                                                                                                                                                                                 |
| server_extensions                | classification sequence model_repository model_repository(unload_dependents) schedule_policy model_configuration system_shared_memory cuda_shared_memory binary_tensor_data statistics |
| model_repository_path[0]         | ./vision/ocr/PP-OCR/serving/fastdeploy_serving/models                                                                                                                                  |
| model_control_mode               | MODE_NONE                                                                                                                                                                              |
| strict_model_config              | 1                                                                                                                                                                                      |
| rate_limit                       | OFF                                                                                                                                                                                    |
| pinned_memory_pool_byte_size     | 268435456                                                                                                                                                                              |
| response_cache_byte_size         | 0                                                                                                                                                                                      |
| min_supported_compute_capability | 0.0                                                                                                                                                                                    |
| strict_readiness                 | 1                                                                                                                                                                                      |
| exit_timeout                     | 30                                                                                                                                                                                     |
+----------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+

I0420 06:26:53.966408 117 server.cc:252] Waiting for in-flight requests to complete.
I0420 06:26:53.966414 117 model_repository_manager.cc:1055] unloading: rec_postprocess:1
I0420 06:26:53.966486 117 model_repository_manager.cc:1055] unloading: det_preprocess:1
I0420 06:26:53.966555 117 model_repository_manager.cc:1055] unloading: det_postprocess:1
I0420 06:26:53.966591 117 model_repository_manager.cc:1055] unloading: cls_postprocess:1
I0420 06:26:53.966616 117 server.cc:267] Timeout 30: Found 4 live models and 0 in-flight non-inference requests
I0420 06:26:54.966846 117 server.cc:267] Timeout 29: Found 4 live models and 0 in-flight non-inference requests
/usr/lib/python3/dist-packages/requests/__init__.py:89: RequestsDependencyWarning: urllib3 (1.26.14) or chardet (3.0.4) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({}) doesn't match a supported "
model_config: {'name': 'cls_postprocess', 'platform': '', 'backend': 'python', 'version_policy': {'latest': {'num_versions': 1}}, 'max_batch_size': 128, 'input': [{'name': 'POST_INPUT_0', 'data_type': 'TYPE_FP32', 'format': 'FORMAT_NONE', 'dims': [2], 'is_shape_tensor': False, 'allow_ragged_batch': False}], 'output': [{'name': 'POST_OUTPUT_0', 'data_type': 'TYPE_INT32', 'dims': [1], 'label_filename': '', 'is_shape_tensor': False}, {'name': 'POST_OUTPUT_1', 'data_type': 'TYPE_FP32', 'dims': [1], 'label_filename': '', 'is_shape_tensor': False}], 'batch_input': [], 'batch_output': [], 'optimization': {'priority': 'PRIORITY_DEFAULT', 'input_pinned_memory': {'enable': True}, 'output_pinned_memory': {'enable': True}, 'gather_kernel_buffer_threshold': 0, 'eager_batching': False}, 'instance_group': [{'name': 'cls_postprocess_0', 'kind': 'KIND_CPU', 'count': 1, 'gpus': [], 'secondary_devices': [], 'profile': [], 'passive': False, 'host_policy': ''}], 'default_model_filename': '', 'cc_model_filenames': {}, 'metric_tags': {}, 'parameters': {}, 'model_warmup': []}
postprocess input names: ['POST_INPUT_0']
postprocess output names: ['POST_OUTPUT_0', 'POST_OUTPUT_1']
Cleaning up...
/usr/lib/python3/dist-packages/requests/__init__.py:89: RequestsDependencyWarning: urllib3 (1.26.14) or chardet (3.0.4) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({}) doesn't match a supported "
model_config: {'name': 'det_preprocess', 'platform': '', 'backend': 'python', 'version_policy': {'latest': {'num_versions': 1}}, 'max_batch_size': 1, 'input': [{'name': 'INPUT_0', 'data_type': 'TYPE_UINT8', 'format': 'FORMAT_NONE', 'dims': [-1, -1, 3], 'is_shape_tensor': False, 'allow_ragged_batch': False}], 'output': [{'name': 'OUTPUT_0', 'data_type': 'TYPE_FP32', 'dims': [3, -1, -1], 'label_filename': '', 'is_shape_tensor': False}, {'name': 'OUTPUT_1', 'data_type': 'TYPE_INT32', 'dims': [4], 'label_filename': '', 'is_shape_tensor': False}], 'batch_input': [], 'batch_output': [], 'optimization': {'priority': 'PRIORITY_DEFAULT', 'input_pinned_memory': {'enable': True}, 'output_pinned_memory': {'enable': True}, 'gather_kernel_buffer_threshold': 0, 'eager_batching': False}, 'instance_group': [{'name': 'det_preprocess_0', 'kind': 'KIND_CPU', 'count': 1, 'gpus': [], 'secondary_devices': [], 'profile': [], 'passive': False, 'host_policy': ''}], 'default_model_filename': '', 'cc_model_filenames': {}, 'metric_tags': {}, 'parameters': {}, 'model_warmup': []}
preprocess input names: ['INPUT_0']
preprocess output names: ['OUTPUT_0', 'OUTPUT_1']
Cleaning up...
/usr/lib/python3/dist-packages/requests/__init__.py:89: RequestsDependencyWarning: urllib3 (1.26.14) or chardet (3.0.4) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({}) doesn't match a supported "
model_config: {'name': 'rec_postprocess', 'platform': '', 'backend': 'python', 'version_policy': {'latest': {'num_versions': 1}}, 'max_batch_size': 128, 'input': [{'name': 'POST_INPUT_0', 'data_type': 'TYPE_FP32', 'format': 'FORMAT_NONE', 'dims': [-1, 6625], 'is_shape_tensor': False, 'allow_ragged_batch': False}], 'output': [{'name': 'POST_OUTPUT_0', 'data_type': 'TYPE_STRING', 'dims': [1], 'label_filename': '', 'is_shape_tensor': False}, {'name': 'POST_OUTPUT_1', 'data_type': 'TYPE_FP32', 'dims': [1], 'label_filename': '', 'is_shape_tensor': False}], 'batch_input': [], 'batch_output': [], 'optimization': {'priority': 'PRIORITY_DEFAULT', 'execution_accelerators': {'gpu_execution_accelerator': [], 'cpu_execution_accelerator': []}, 'input_pinned_memory': {'enable': True}, 'output_pinned_memory': {'enable': True}, 'gather_kernel_buffer_threshold': 0, 'eager_batching': False}, 'instance_group': [{'name': 'rec_postprocess_0', 'kind': 'KIND_CPU', 'count': 1, 'gpus': [], 'secondary_devices': [], 'profile': [], 'passive': False, 'host_policy': ''}], 'default_model_filename': '', 'cc_model_filenames': {}, 'metric_tags': {}, 'parameters': {}, 'model_warmup': []}
postprocess input names: ['POST_INPUT_0']
postprocess output names: ['POST_OUTPUT_0', 'POST_OUTPUT_1']
Cleaning up...
/usr/lib/python3/dist-packages/requests/__init__.py:89: RequestsDependencyWarning: urllib3 (1.26.14) or chardet (3.0.4) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({}) doesn't match a supported "
model_config: {'name': 'det_postprocess', 'platform': '', 'backend': 'python', 'version_policy': {'latest': {'num_versions': 1}}, 'max_batch_size': 128, 'input': [{'name': 'POST_INPUT_0', 'data_type': 'TYPE_FP32', 'format': 'FORMAT_NONE', 'dims': [1, -1, -1], 'is_shape_tensor': False, 'allow_ragged_batch': False}, {'name': 'POST_INPUT_1', 'data_type': 'TYPE_INT32', 'format': 'FORMAT_NONE', 'dims': [4], 'is_shape_tensor': False, 'allow_ragged_batch': False}, {'name': 'ORI_IMG', 'data_type': 'TYPE_UINT8', 'format': 'FORMAT_NONE', 'dims': [-1, -1, 3], 'is_shape_tensor': False, 'allow_ragged_batch': False}], 'output': [{'name': 'POST_OUTPUT_0', 'data_type': 'TYPE_STRING', 'dims': [-1, 1], 'label_filename': '', 'is_shape_tensor': False}, {'name': 'POST_OUTPUT_1', 'data_type': 'TYPE_FP32', 'dims': [-1, 1], 'label_filename': '', 'is_shape_tensor': False}, {'name': 'POST_OUTPUT_2', 'data_type': 'TYPE_FP32', 'dims': [-1, -1, 1], 'label_filename': '', 'is_shape_tensor': False}], 'batch_input': [], 'batch_output': [], 'optimization': {'priority': 'PRIORITY_DEFAULT', 'input_pinned_memory': {'enable': True}, 'output_pinned_memory': {'enable': True}, 'gather_kernel_buffer_threshold': 0, 'eager_batching': False}, 'instance_group': [{'name': 'det_postprocess_0', 'kind': 'KIND_CPU', 'count': 1, 'gpus': [], 'secondary_devices': [], 'profile': [], 'passive': False, 'host_policy': ''}], 'default_model_filename': '', 'cc_model_filenames': {}, 'metric_tags': {}, 'parameters': {}, 'model_warmup': []}
postprocess input names: ['POST_INPUT_0', 'POST_INPUT_1', 'ORI_IMG']
postprocess output names: ['POST_OUTPUT_0', 'POST_OUTPUT_1', 'POST_OUTPUT_2']
Cleaning up...
I0420 06:26:55.025715 117 model_repository_manager.cc:1166] successfully unloaded 'cls_postprocess' version 1
I0420 06:26:55.027201 117 model_repository_manager.cc:1166] successfully unloaded 'rec_postprocess' version 1
I0420 06:26:55.027759 117 model_repository_manager.cc:1166] successfully unloaded 'det_preprocess' version 1
I0420 06:26:55.031797 117 model_repository_manager.cc:1166] successfully unloaded 'det_postprocess' version 1
I0420 06:26:55.967217 117 server.cc:267] Timeout 28: Found 0 live models and 0 in-flight non-inference requests
error: creating server: Internal - failed to load all models

**Comment by Jaccica** [comment]
我安装的cpu版本的，也是出现了这个问题，请问怎么解决？谢谢！

**Comment by Cheng-x-c** [comment]
> 

![image](https://user-images.githubusercontent.com/59717369/233533489-7e938e8c-c894-4db0-8597-40c2eac92500.png)
注意这一段描述，这几个模型开启了GPU，但是CPU版本不支持GPU，在模型里面选择CPU，不要选择GPU就好了
![image](https://user-images.githubusercontent.com/59717369/233533918-28cf2f6d-2fc2-47d2-a7c6-02139be8a598.png)

**Comment by Jaccica** [comment]
您好，我是新手。如何在模型里关掉GPU，模型文件都打不开。我的是ubuntu系统。谢谢！


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/FastDeploy"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月21日(星期五) 中午11:24
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/FastDeploy] error: creating server: Internal - failed to load all models (Issue #1829)





   

 注意这一段描述，这几个模型开启了GPU，但是CPU版本不支持GPU，在模型里面关掉GPU就好了

**Comment by sheiy** [comment]
告知后来也有这个问题的人；CPU需要修改配置；参考https://blog.csdn.net/qq_30946821/article/details/131408693

如果使用gpu配置的话 文档里那个启动docker的命令要加上--gpus all
