### ISSUE TITLE
fastdeploy  使用lite后端报Illegal instruction

### ISSUE THREAD

**Issue by liushuai35** [PaddlePaddle/FastDeploy#1834]
问题描述：使用树莓派4B编译安装，带有vision，以及ort和lite后端，设置了opencv路径，并成功安装python版本的fastdeploy。
但在执行提供的参考代码时报错，能够使用ort后端，但是使用lite后端出现Illegal instruction。

test.py:
_____________________________________________________________________________________________________________________
import fastdeploy as fd
import numpy as np
option = fd.RuntimeOption()
model_url = "https://bj.bcebos.com/fastdeploy/models/mobilenetv2.tgz"
fd.download_and_decompress(model_url, path=".")
option.set_model_path("mobilenetv2/inference.pdmodel",
                      "mobilenetv2/inference.pdiparams")

option.use_lite_backend() 
#option.use_ort_backend() 

#Initialise runtime
runtime = fd.Runtime(option)

#Get model input name
input_name = runtime.get_input_info(0).name

#Constructing random data for inference
results = runtime.infer({
    input_name: np.random.rand(1, 3, 224, 224).astype("float32")
})

print(results[0].shape)
_____________________________________________________________________________________________________________________

lite后端运行结果：
File is donwloaded, now extracting...
[I  4/18 12:41:50. 68 ...ild/Paddle-Lite/lite/core/device_info.cc:1275 Setup] ARM multiprocessors name: HARDWARE : BCM2835

[I  4/18 12:41:50. 68 ...ild/Paddle-Lite/lite/core/device_info.cc:1276 Setup] ARM multiprocessors number: 4
[I  4/18 12:41:50. 68 ...ild/Paddle-Lite/lite/core/device_info.cc:1278 Setup] ARM multiprocessors ID: 0, max freq: 1500, min freq: 1500, cluster ID: 0, CPU ARCH: A72
[I  4/18 12:41:50. 68 ...ild/Paddle-Lite/lite/core/device_info.cc:1278 Setup] ARM multiprocessors ID: 1, max freq: 1500, min freq: 1500, cluster ID: 0, CPU ARCH: A72
[I  4/18 12:41:50. 68 ...ild/Paddle-Lite/lite/core/device_info.cc:1278 Setup] ARM multiprocessors ID: 2, max freq: 1500, min freq: 1500, cluster ID: 0, CPU ARCH: A72
[I  4/18 12:41:50. 68 ...ild/Paddle-Lite/lite/core/device_info.cc:1278 Setup] ARM multiprocessors ID: 3, max freq: 1500, min freq: 1500, cluster ID: 0, CPU ARCH: A72
[I  4/18 12:41:50. 68 ...ild/Paddle-Lite/lite/core/device_info.cc:1284 Setup] L1 DataCache size is: 
[I  4/18 12:41:50. 68 ...ild/Paddle-Lite/lite/core/device_info.cc:1286 Setup] 48 KB
[I  4/18 12:41:50. 68 ...ild/Paddle-Lite/lite/core/device_info.cc:1286 Setup] 48 KB
[I  4/18 12:41:50. 68 ...ild/Paddle-Lite/lite/core/device_info.cc:1286 Setup] 48 KB
[I  4/18 12:41:50. 68 ...ild/Paddle-Lite/lite/core/device_info.cc:1286 Setup] 48 KB
[I  4/18 12:41:50. 68 ...ild/Paddle-Lite/lite/core/device_info.cc:1288 Setup] L2 Cache size is: 
[I  4/18 12:41:50. 68 ...ild/Paddle-Lite/lite/core/device_info.cc:1290 Setup] 1024 KB
[I  4/18 12:41:50. 68 ...ild/Paddle-Lite/lite/core/device_info.cc:1290 Setup] 1024 KB
[I  4/18 12:41:50. 68 ...ild/Paddle-Lite/lite/core/device_info.cc:1290 Setup] 1024 KB
[I  4/18 12:41:50. 68 ...ild/Paddle-Lite/lite/core/device_info.cc:1290 Setup] 1024 KB
[I  4/18 12:41:50. 68 ...ild/Paddle-Lite/lite/core/device_info.cc:1292 Setup] L3 Cache size is: 
[I  4/18 12:41:50. 68 ...ild/Paddle-Lite/lite/core/device_info.cc:1294 Setup] 0 KB
[I  4/18 12:41:50. 68 ...ild/Paddle-Lite/lite/core/device_info.cc:1294 Setup] 0 KB
[I  4/18 12:41:50. 68 ...ild/Paddle-Lite/lite/core/device_info.cc:1294 Setup] 0 KB
[I  4/18 12:41:50. 68 ...ild/Paddle-Lite/lite/core/device_info.cc:1294 Setup] 0 KB
[I  4/18 12:41:50. 68 ...ild/Paddle-Lite/lite/core/device_info.cc:1296 Setup] Total memory: 3885396KB
[I  4/18 12:41:50. 68 ...ild/Paddle-Lite/lite/core/device_info.cc:1297 Setup] SVE2 support: 0
[I  4/18 12:41:50. 69 ...ild/Paddle-Lite/lite/core/device_info.cc:1298 Setup] SVE2 f32mm support: 0
[I  4/18 12:41:50. 69 ...ild/Paddle-Lite/lite/core/device_info.cc:1299 Setup] SVE2 i8mm support: 0
[I  4/18 12:41:50. 76 ...ly_build/Paddle-Lite/lite/api/cxx_api.cc:366 Build] Load model from file.
[I  4/18 12:41:50. 79 ...e-Lite/lite/model_parser/model_parser.cc:241 LoadModelPb] Loading topology data from mobilenetv2/inference.pdmodel
[I  4/18 12:41:50.143 ...e-Lite/lite/model_parser/model_parser.cc:259 LoadModelPb] Loading params data from mobilenetv2/inference.pdiparams
[I  4/18 12:41:50.470 ...e-Lite/lite/model_parser/model_parser.cc:269 LoadModelPb] 1. Model is successfully loaded!
Illegal instruction
_____________________________________________________________________________________________________________________
ort后端运行结果
File is donwloaded, now extracting...
[INFO] fastdeploy/runtime/runtime.cc(293)::CreateOrtBackend Runtime initialized with Backend::ORT in Device::CPU.
(1, 1000)

**Comment by DefTruth** [comment]
可以看下编译的log，确认下载的lite库的具体url是哪个不？

**Comment by woodrex83** [comment]
我用的树莓派Zero2W，成功安装python版本的fastdeploy预编译的wheel
同样是执行提供的参考代码时报错，能够使用ort后端，但是使用lite后端出现Illegal instruction

运行结果
[I  5/16 23:52: 0.410 ...ild/Paddle-Lite/lite/core/device_info.cc:1275 Setup] ARM multiprocessors name: HARDWARE        : BCM2835

[I  5/16 23:52: 0.410 ...ild/Paddle-Lite/lite/core/device_info.cc:1276 Setup] ARM multiprocessors number: 4
[I  5/16 23:52: 0.410 ...ild/Paddle-Lite/lite/core/device_info.cc:1278 Setup] ARM multiprocessors ID: 0, max freq: 1000, min freq: 1000, cluster ID: 0, CPU ARCH: A53
[I  5/16 23:52: 0.410 ...ild/Paddle-Lite/lite/core/device_info.cc:1278 Setup] ARM multiprocessors ID: 1, max freq: 1000, min freq: 1000, cluster ID: 0, CPU ARCH: A53
[I  5/16 23:52: 0.410 ...ild/Paddle-Lite/lite/core/device_info.cc:1278 Setup] ARM multiprocessors ID: 2, max freq: 1000, min freq: 1000, cluster ID: 0, CPU ARCH: A53
[I  5/16 23:52: 0.410 ...ild/Paddle-Lite/lite/core/device_info.cc:1278 Setup] ARM multiprocessors ID: 3, max freq: 1000, min freq: 1000, cluster ID: 0, CPU ARCH: A53
[I  5/16 23:52: 0.410 ...ild/Paddle-Lite/lite/core/device_info.cc:1284 Setup] L1 DataCache size is:
[I  5/16 23:52: 0.410 ...ild/Paddle-Lite/lite/core/device_info.cc:1286 Setup] 32 KB
[I  5/16 23:52: 0.410 ...ild/Paddle-Lite/lite/core/device_info.cc:1286 Setup] 32 KB
[I  5/16 23:52: 0.410 ...ild/Paddle-Lite/lite/core/device_info.cc:1286 Setup] 32 KB
[I  5/16 23:52: 0.410 ...ild/Paddle-Lite/lite/core/device_info.cc:1286 Setup] 32 KB
[I  5/16 23:52: 0.410 ...ild/Paddle-Lite/lite/core/device_info.cc:1288 Setup] L2 Cache size is:
[I  5/16 23:52: 0.410 ...ild/Paddle-Lite/lite/core/device_info.cc:1290 Setup] 512 KB
[I  5/16 23:52: 0.410 ...ild/Paddle-Lite/lite/core/device_info.cc:1290 Setup] 512 KB
[I  5/16 23:52: 0.410 ...ild/Paddle-Lite/lite/core/device_info.cc:1290 Setup] 512 KB
[I  5/16 23:52: 0.410 ...ild/Paddle-Lite/lite/core/device_info.cc:1290 Setup] 512 KB
[I  5/16 23:52: 0.410 ...ild/Paddle-Lite/lite/core/device_info.cc:1292 Setup] L3 Cache size is:
[I  5/16 23:52: 0.411 ...ild/Paddle-Lite/lite/core/device_info.cc:1294 Setup] 0 KB
[I  5/16 23:52: 0.411 ...ild/Paddle-Lite/lite/core/device_info.cc:1294 Setup] 0 KB
[I  5/16 23:52: 0.411 ...ild/Paddle-Lite/lite/core/device_info.cc:1294 Setup] 0 KB
[I  5/16 23:52: 0.411 ...ild/Paddle-Lite/lite/core/device_info.cc:1294 Setup] 0 KB
[I  5/16 23:52: 0.411 ...ild/Paddle-Lite/lite/core/device_info.cc:1296 Setup] Total memory: 429396KB
[I  5/16 23:52: 0.411 ...ild/Paddle-Lite/lite/core/device_info.cc:1297 Setup] SVE2 support: 0
[I  5/16 23:52: 0.411 ...ild/Paddle-Lite/lite/core/device_info.cc:1298 Setup] SVE2 f32mm support: 0
[I  5/16 23:52: 0.411 ...ild/Paddle-Lite/lite/core/device_info.cc:1299 Setup] SVE2 i8mm support: 0
[I  5/16 23:52: 0.411 ...ly_build/Paddle-Lite/lite/api/cxx_api.cc:366 Build] Load model from file.
[I  5/16 23:52: 0.411 ...e-Lite/lite/model_parser/model_parser.cc:241 LoadModelPb] Loading topology data from ch_PP-OCRv3_det_infer/inference.pdmodel
[I  5/16 23:52: 0.546 ...e-Lite/lite/model_parser/model_parser.cc:259 LoadModelPb] Loading params data from ch_PP-OCRv3_det_infer/inference.pdiparams
[I  5/16 23:52: 0.554 ...e-Lite/lite/model_parser/model_parser.cc:269 LoadModelPb] 1. Model is successfully loaded!
Illegal instruction

**Comment by qianbin1989228** [comment]
> 

我也遇到跟你一样的问题

**Comment by mahesh11T** [comment]
same issue faced,
any update?
