### ISSUE TITLE
国产操作系统：openEuler20.03 中，编译c版本 compiled_fastdeploy_sdk 时,make -j12报错

### ISSUE THREAD

**Issue by wangxu372848892** [PaddlePaddle/FastDeploy#1836]
## 环境
- 【系统平台】: openEuler20.03，gcc版本7.3.0
       现在大型国企央要求的国产化操作系统麒麟等操作系统都是基于openEuler的，所以感觉解决这个问题很有必要性。
- 【FastDeploy版本】： fastdeploy-release-1.0.5 、 1.0.6分支代码
- 【编译命令】

     cd FastDeploy
     mkdir build && cd build
     
     cmake .. -DENABLE_ORT_BACKEND=ON \
         -DENABLE_PADDLE_BACKEND=ON \
         -DENABLE_OPENVINO_BACKEND=ON \
         -DCMAKE_INSTALL_PREFIX=${PWD}/compiled_fastdeploy_sdk \
         -DENABLE_VISION=ON \
         -DENABLE_TEXT=ON \
         -DWITH_CAPI=ON 
         
        make -j12
        make install

【问题】：compiled_fastdeploy_sdk，cmake没问题，make -j12报错，1.0.4代码没有问题

![image](https://user-images.githubusercontent.com/59901551/232983611-23dfb8d0-67de-49ee-95dc-7a70207ea30d.png)

**Comment by wangxu372848892** [comment]
1.0.4代码没有问题，gcc版本7.3.0

**Comment by DefTruth** [comment]
升级一下python为python3
