### ISSUE TITLE
segment直接输出是列表，转成矩阵花费时间太多了

### ISSUE THREAD

**Issue by kkpssr** [PaddlePaddle/FastDeploy#1850]
使用fd部署后输出是列表，为了对应切割位置使用numpy.reshape转换，速度太慢了，一张3000x2000的图，转换耗时70ms，模型才10ms

**Comment by kkpssr** [comment]
> 使用fd部署后输出是列表，为了对应切割位置使用numpy.reshape转换，速度太慢了，一张3000x2000的图，转换耗时70ms，模型才10ms

排查后发现耗时是在numpy.array这一步

**Comment by Dandelion111** [comment]
> > 使用fd部署后输出是列表，为了对应切割位置使用numpy.reshape转换，速度太慢了，一张3000x2000的图，转换耗时70ms，模型才10ms
> 
> 排查后发现耗时是在numpy.array这一步

请问大佬python版本SegmentationResult怎么转成掩模图
