### ISSUE TITLE
CPU版本UIE示例无法跑通

### ISSUE THREAD

**Issue by TherChenYang** [PaddlePaddle/FastDeploy#1854]
- 【模型跑不通】
UIE模型的示例代码跑不通，安装的是cpu版本
https://github.com/PaddlePaddle/FastDeploy/blob/develop/examples/text/uie/serving/README_CN.md
镜像版本：registry.baidubce.com/paddlepaddle/fastdeploy:1.0.3-cpu-only-21.10
机器：centos7.9
看到之前的Issues说镜像中的FastDeploy的python版本有问题 已重新安装
python3 -m pip install --upgrade --force-reinstall fastdeploy-python

执行fastdeployserver --model-repository=/uie_serving/models --backend-config=python,shm-default-byte-size=10485760
有如下错误

![image](https://user-images.githubusercontent.com/124348939/233597670-5e717988-4269-49d7-8b46-a82cb610aee7.png)

**Comment by TherChenYang** [comment]
![image](https://user-images.githubusercontent.com/124348939/233598584-f7818d82-2176-4236-8ca7-71910b987ce3.png)

**Comment by huangjun11** [comment]
你好，请问你的问题解决了吗

**Comment by TherChenYang** [comment]
已解决 在容器中重新安装fastdeploy的1.0.3版本即可

**Comment by huangjun11** [comment]
> 已解决 在容器中重新安装fastdeploy的1.0.3版本即可

那请问您的配置文件是什么？我可以参考一下吗，因为我又显示报错：The FastDeploy didn't compile with Paddle Inference.

**Comment by TherChenYang** [comment]
不可以使用paddle推理，1.0.3版本中默认没有安装paddle inference 我是用的是onnx
<img width="606" alt="image" src="https://github.com/PaddlePaddle/FastDeploy/assets/124348939/6d2a9dfc-be7b-477b-ae52-1a495e99cb55">

**Comment by huangjun11** [comment]
> 不可以使用paddle推理，1.0.3版本中默认没有安装paddle inference 我是用的是onnx <img alt="image" width="606" src="https://user-images.githubusercontent.com/124348939/284268500-6d2a9dfc-be7b-477b-ae52-1a495e99cb55.png">

好的，我尝试一下使用您提供的版本
