### ISSUE TITLE
CMake Error: Found relative path while evaluating include directories

### ISSUE THREAD

**Issue by unblock7** [PaddlePaddle/FastDeploy#1855]
## Environment

FastDeploy version: 1.0.0
OS Platform: Windows x64
Hardware: CPU noavx
Program Language: C++
CMake: 3.18, 3.25
Visual Studio: 2019

## Problem description
Can't generate Visual Studio project with CMAKE, while set ENABLE_PADDLE_BACKEND=ON.
CMake Error in CMakeLists.txt:
  Found relative path while evaluating include directories

[cmake_log.txt](https://github.com/PaddlePaddle/FastDeploy/files/11298613/cmake_log.txt)

**Comment by DreamMaker777** [comment]
Download the latest version.

**Comment by DefTruth** [comment]
see #1860
