### ISSUE TITLE
部署ppocrv2服务出错，调用不起来。

### ISSUE THREAD

**Issue by Jaccica** [PaddlePaddle/FastDeploy#1864]
*********************************************
温馨提示：根据社区不完全统计，按照模板提问，可以加快回复和解决问题的速度
*********************************************

## 环境

- 【FastDeploy版本】： fastdeploy-linux-cpu-1.0.6
- 【系统平台】: Ubuntu 18.04
- 【编译语言】： Python

调用的是docker的CPU版本：docker pull registry.baidubce.com/paddlepaddle/fastdeploy:1.0.6-cpu-only-21.10，换成官网下载的ppocrv2模型，运行 fastdeployserver –model-repository=/ocr_serving/models 出错。
I0424 08:22:34.715656 2414 model_repository_manager.cc:1022] loading: cls_runtime:1
I0424 08:22:34.816187 2414 model_repository_manager.cc:1022] loading: det_preprocess:1
I0424 08:22:34.891727 2414 fastdeploy_runtime.cc:1207] TRITONBACKEND_Initialize: fastdeploy
I0424 08:22:34.891743 2414 fastdeploy_runtime.cc:1216] Triton TRITONBACKEND API version: 1.6
I0424 08:22:34.891746 2414 fastdeploy_runtime.cc:1221] 'fastdeploy' TRITONBACKEND API version: 1.6
I0424 08:22:34.891748 2414 fastdeploy_runtime.cc:1250] backend configuration:
{}
I0424 08:22:34.891778 2414 fastdeploy_runtime.cc:1280] TRITONBACKEND_ModelInitialize: cls_runtime (version 1)
[WARNING] fastdeploy/runtime/runtime_option.cc(189)::SetPaddleMKLDNN	`RuntimeOption::SetPaddleMKLDNN` will be removed in v1.2.0, please modify its member variable directly, e.g `option.paddle_infer_option.enable_mkldnn = true`
I0424 08:22:34.892541 2414 fastdeploy_runtime.cc:1319] TRITONBACKEND_ModelInstanceInitialize: cls_runtime_0 (CPU device 0)
[INFO] fastdeploy/runtime/backends/openvino/ov_backend.cc(218)::InitFromPaddle	number of streams:1.
[INFO] fastdeploy/runtime/backends/openvino/ov_backend.cc(228)::InitFromPaddle	affinity:YES.
[INFO] fastdeploy/runtime/backends/openvino/ov_backend.cc(240)::InitFromPaddle	Compile OpenVINO model on device_name:CPU.
I0424 08:22:34.916415 2414 model_repository_manager.cc:1022] loading: det_runtime:1
[INFO] fastdeploy/runtime/runtime.cc(279)::CreateOpenVINOBackend	Runtime initialized with Backend::OPENVINO in Device::CPU.
I0424 08:22:34.997248 2414 model_repository_manager.cc:1183] successfully loaded 'cls_runtime' version 1
I0424 08:22:34.998388 2414 python.cc:1875] TRITONBACKEND_ModelInstanceInitialize: det_preprocess_0 (CPU device 0)
I0424 08:22:35.016748 2414 model_repository_manager.cc:1022] loading: rec_postprocess:1
I0424 08:22:35.116930 2414 model_repository_manager.cc:1022] loading: det_postprocess:1
/usr/lib/python3/dist-packages/requests/__init__.py:89: RequestsDependencyWarning: urllib3 (1.26.15) or chardet (3.0.4) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({}) doesn't match a supported "
I0424 08:22:35.217217 2414 model_repository_manager.cc:1022] loading: cls_postprocess:1
model_config: {'name': 'det_preprocess', 'platform': '', 'backend': 'python', 'version_policy': {'latest': {'num_versions': 1}}, 'max_batch_size': 1, 'input': [{'name': 'INPUT_0', 'data_type': 'TYPE_UINT8', 'format': 'FORMAT_NONE', 'dims': [-1, -1, 3], 'is_shape_tensor': False, 'allow_ragged_batch': False}], 'output': [{'name': 'OUTPUT_0', 'data_type': 'TYPE_FP32', 'dims': [3, -1, -1], 'label_filename': '', 'is_shape_tensor': False}, {'name': 'OUTPUT_1', 'data_type': 'TYPE_INT32', 'dims': [4], 'label_filename': '', 'is_shape_tensor': False}], 'batch_input': [], 'batch_output': [], 'optimization': {'priority': 'PRIORITY_DEFAULT', 'input_pinned_memory': {'enable': True}, 'output_pinned_memory': {'enable': True}, 'gather_kernel_buffer_threshold': 0, 'eager_batching': False}, 'instance_group': [{'name': 'det_preprocess_0', 'kind': 'KIND_CPU', 'count': 1, 'gpus': [], 'secondary_devices': [], 'profile': [], 'passive': False, 'host_policy': ''}], 'default_model_filename': '', 'cc_model_filenames': {}, 'metric_tags': {}, 'parameters': {}, 'model_warmup': []}
preprocess input names: ['INPUT_0']
preprocess output names: ['OUTPUT_0', 'OUTPUT_1']
I0424 08:22:35.242377 2414 fastdeploy_runtime.cc:1280] TRITONBACKEND_ModelInitialize: det_runtime (version 1)
I0424 08:22:35.242415 2414 model_repository_manager.cc:1183] successfully loaded 'det_preprocess' version 1
[WARNING] fastdeploy/runtime/runtime_option.cc(189)::SetPaddleMKLDNN	`RuntimeOption::SetPaddleMKLDNN` will be removed in v1.2.0, please modify its member variable directly, e.g `option.paddle_infer_option.enable_mkldnn = true`
I0424 08:22:35.243649 2414 python.cc:1875] TRITONBACKEND_ModelInstanceInitialize: det_postprocess_0 (CPU device 0)
I0424 08:22:35.317457 2414 model_repository_manager.cc:1022] loading: rec_runtime:1
/usr/lib/python3/dist-packages/requests/__init__.py:89: RequestsDependencyWarning: urllib3 (1.26.15) or chardet (3.0.4) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({}) doesn't match a supported "
model_config: {'name': 'det_postprocess', 'platform': '', 'backend': 'python', 'version_policy': {'latest': {'num_versions': 1}}, 'max_batch_size': 128, 'input': [{'name': 'POST_INPUT_0', 'data_type': 'TYPE_FP32', 'format': 'FORMAT_NONE', 'dims': [1, -1, -1], 'is_shape_tensor': False, 'allow_ragged_batch': False}, {'name': 'POST_INPUT_1', 'data_type': 'TYPE_INT32', 'format': 'FORMAT_NONE', 'dims': [4], 'is_shape_tensor': False, 'allow_ragged_batch': False}, {'name': 'ORI_IMG', 'data_type': 'TYPE_UINT8', 'format': 'FORMAT_NONE', 'dims': [-1, -1, 3], 'is_shape_tensor': False, 'allow_ragged_batch': False}], 'output': [{'name': 'POST_OUTPUT_0', 'data_type': 'TYPE_STRING', 'dims': [-1, 1], 'label_filename': '', 'is_shape_tensor': False}, {'name': 'POST_OUTPUT_1', 'data_type': 'TYPE_FP32', 'dims': [-1, 1], 'label_filename': '', 'is_shape_tensor': False}, {'name': 'POST_OUTPUT_2', 'data_type': 'TYPE_FP32', 'dims': [-1, -1, 1], 'label_filename': '', 'is_shape_tensor': False}], 'batch_input': [], 'batch_output': [], 'optimization': {'priority': 'PRIORITY_DEFAULT', 'input_pinned_memory': {'enable': True}, 'output_pinned_memory': {'enable': True}, 'gather_kernel_buffer_threshold': 0, 'eager_batching': False}, 'instance_group': [{'name': 'det_postprocess_0', 'kind': 'KIND_CPU', 'count': 1, 'gpus': [], 'secondary_devices': [], 'profile': [], 'passive': False, 'host_policy': ''}], 'default_model_filename': '', 'cc_model_filenames': {}, 'metric_tags': {}, 'parameters': {}, 'model_warmup': []}
postprocess input names: ['POST_INPUT_0', 'POST_INPUT_1', 'ORI_IMG']
postprocess output names: ['POST_OUTPUT_0', 'POST_OUTPUT_1', 'POST_OUTPUT_2']
I0424 08:22:35.469041 2414 python.cc:1875] TRITONBACKEND_ModelInstanceInitialize: rec_postprocess_0 (CPU device 0)
I0424 08:22:35.469148 2414 model_repository_manager.cc:1183] successfully loaded 'det_postprocess' version 1
/usr/lib/python3/dist-packages/requests/__init__.py:89: RequestsDependencyWarning: urllib3 (1.26.15) or chardet (3.0.4) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({}) doesn't match a supported "
model_config: {'name': 'rec_postprocess', 'platform': '', 'backend': 'python', 'version_policy': {'latest': {'num_versions': 1}}, 'max_batch_size': 128, 'input': [{'name': 'POST_INPUT_0', 'data_type': 'TYPE_FP32', 'format': 'FORMAT_NONE', 'dims': [-1, 6625], 'is_shape_tensor': False, 'allow_ragged_batch': False}], 'output': [{'name': 'POST_OUTPUT_0', 'data_type': 'TYPE_STRING', 'dims': [1], 'label_filename': '', 'is_shape_tensor': False}, {'name': 'POST_OUTPUT_1', 'data_type': 'TYPE_FP32', 'dims': [1], 'label_filename': '', 'is_shape_tensor': False}], 'batch_input': [], 'batch_output': [], 'optimization': {'priority': 'PRIORITY_DEFAULT', 'input_pinned_memory': {'enable': True}, 'output_pinned_memory': {'enable': True}, 'gather_kernel_buffer_threshold': 0, 'eager_batching': False}, 'instance_group': [{'name': 'rec_postprocess_0', 'kind': 'KIND_CPU', 'count': 1, 'gpus': [], 'secondary_devices': [], 'profile': [], 'passive': False, 'host_policy': ''}], 'default_model_filename': '', 'cc_model_filenames': {}, 'metric_tags': {}, 'parameters': {}, 'model_warmup': []}
postprocess input names: ['POST_INPUT_0']
postprocess output names: ['POST_OUTPUT_0', 'POST_OUTPUT_1']
I0424 08:22:35.686333 2414 fastdeploy_runtime.cc:1319] TRITONBACKEND_ModelInstanceInitialize: det_runtime_0 (CPU device 0)
I0424 08:22:35.686457 2414 model_repository_manager.cc:1183] successfully loaded 'rec_postprocess' version 1
[INFO] fastdeploy/runtime/backends/openvino/ov_backend.cc(218)::InitFromPaddle	number of streams:1.
[INFO] fastdeploy/runtime/backends/openvino/ov_backend.cc(228)::InitFromPaddle	affinity:YES.
[INFO] fastdeploy/runtime/backends/openvino/ov_backend.cc(240)::InitFromPaddle	Compile OpenVINO model on device_name:CPU.
[INFO] fastdeploy/runtime/runtime.cc(279)::CreateOpenVINOBackend	Runtime initialized with Backend::OPENVINO in Device::CPU.
I0424 08:22:35.812596 2414 model_repository_manager.cc:1183] successfully loaded 'det_runtime' version 1
I0424 08:22:35.812914 2414 fastdeploy_runtime.cc:1280] TRITONBACKEND_ModelInitialize: rec_runtime (version 1)
[WARNING] fastdeploy/runtime/runtime_option.cc(189)::SetPaddleMKLDNN	`RuntimeOption::SetPaddleMKLDNN` will be removed in v1.2.0, please modify its member variable directly, e.g `option.paddle_infer_option.enable_mkldnn = true`
I0424 08:22:35.813652 2414 python.cc:1875] TRITONBACKEND_ModelInstanceInitialize: cls_postprocess_0 (CPU device 0)
/usr/lib/python3/dist-packages/requests/__init__.py:89: RequestsDependencyWarning: urllib3 (1.26.15) or chardet (3.0.4) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({}) doesn't match a supported "
model_config: {'name': 'cls_postprocess', 'platform': '', 'backend': 'python', 'version_policy': {'latest': {'num_versions': 1}}, 'max_batch_size': 128, 'input': [{'name': 'POST_INPUT_0', 'data_type': 'TYPE_FP32', 'format': 'FORMAT_NONE', 'dims': [2], 'is_shape_tensor': False, 'allow_ragged_batch': False}], 'output': [{'name': 'POST_OUTPUT_0', 'data_type': 'TYPE_INT32', 'dims': [1], 'label_filename': '', 'is_shape_tensor': False}, {'name': 'POST_OUTPUT_1', 'data_type': 'TYPE_FP32', 'dims': [1], 'label_filename': '', 'is_shape_tensor': False}], 'batch_input': [], 'batch_output': [], 'optimization': {'priority': 'PRIORITY_DEFAULT', 'input_pinned_memory': {'enable': True}, 'output_pinned_memory': {'enable': True}, 'gather_kernel_buffer_threshold': 0, 'eager_batching': False}, 'instance_group': [{'name': 'cls_postprocess_0', 'kind': 'KIND_CPU', 'count': 1, 'gpus': [], 'secondary_devices': [], 'profile': [], 'passive': False, 'host_policy': ''}], 'default_model_filename': '', 'cc_model_filenames': {}, 'metric_tags': {}, 'parameters': {}, 'model_warmup': []}
postprocess input names: ['POST_INPUT_0']
postprocess output names: ['POST_OUTPUT_0', 'POST_OUTPUT_1']
I0424 08:22:36.070492 2414 fastdeploy_runtime.cc:1319] TRITONBACKEND_ModelInstanceInitialize: rec_runtime_0 (CPU device 0)
I0424 08:22:36.070592 2414 model_repository_manager.cc:1183] successfully loaded 'cls_postprocess' version 1
[INFO] fastdeploy/runtime/backends/openvino/ov_backend.cc(218)::InitFromPaddle	number of streams:1.
[INFO] fastdeploy/runtime/backends/openvino/ov_backend.cc(228)::InitFromPaddle	affinity:YES.
[INFO] fastdeploy/runtime/backends/openvino/ov_backend.cc(240)::InitFromPaddle	Compile OpenVINO model on device_name:CPU.
[INFO] fastdeploy/runtime/runtime.cc(279)::CreateOpenVINOBackend	Runtime initialized with Backend::OPENVINO in Device::CPU.
I0424 08:22:36.447470 2414 fastdeploy_runtime.cc:1351] TRITONBACKEND_ModelInstanceFinalize: delete instance state
I0424 08:22:36.447530 2414 fastdeploy_runtime.cc:1300] TRITONBACKEND_ModelFinalize: delete model state
**E0424 08:22:36.447556 2414 model_repository_manager.cc:1186] failed to load 'rec_runtime' version 1: Invalid argument: unexpected inference input 'softmax_5.tmp_0', allowed inputs are: softmax_0.tmp_0
E0424 08:22:36.447754 2414 model_repository_manager.cc:1375] Invalid argument: ensemble 'rec_pp' depends on 'rec_runtime' which has no loaded version**
I0424 08:22:36.448036 2414 model_repository_manager.cc:1022] loading: cls_pp:1
I0424 08:22:36.548360 2414 model_repository_manager.cc:1022] loading: pp_ocr:1
I0424 08:22:36.648521 2414 model_repository_manager.cc:1183] successfully loaded 'cls_pp' version 1
I0424 08:22:36.648607 2414 model_repository_manager.cc:1183] successfully loaded 'pp_ocr' version 1
I0424 08:22:36.648670 2414 server.cc:522] 
+------------------+------+
| Repository Agent | Path |
+------------------+------+
+------------------+------+

I0424 08:22:36.648692 2414 server.cc:549] 
+------------+---------------------------------------------------------------+--------+
| Backend    | Path                                                          | Config |
+------------+---------------------------------------------------------------+--------+
| fastdeploy | /opt/tritonserver/backends/fastdeploy/libtriton_fastdeploy.so | {}     |
| python     | /opt/tritonserver/backends/python/libtriton_python.so         | {}     |
+------------+---------------------------------------------------------------+--------+

I0424 08:22:36.648741 2414 server.cc:592] 
+-----------------+---------+-------------------------------------------------------------------------------------+
| Model           | Version | Status                                                                              |
+-----------------+---------+-------------------------------------------------------------------------------------+
| cls_postprocess | 1       | READY                                                                               |
| cls_pp          | 1       | READY                                                                               |
| cls_runtime     | 1       | READY                                                                               |
| det_postprocess | 1       | READY                                                                               |
| det_preprocess  | 1       | READY                                                                               |
| det_runtime     | 1       | READY                                                                               |
| pp_ocr          | 1       | READY                                                                               |
| rec_postprocess | 1       | READY                                                                               |
| rec_runtime     | 1       | UNAVAILABLE: Invalid argument: unexpected inference input 'softmax_5.tmp_0', allowe |
|                 |         | d inputs are: softmax_0.tmp_0                                                       |
+-----------------+---------+-------------------------------------------------------------------------------------+

I0424 08:22:36.648803 2414 tritonserver.cc:1920] 
+----------------------------------+------------------------------------------------------------------------------+
| Option                           | Value                                                                        |
+----------------------------------+------------------------------------------------------------------------------+
| server_id                        | triton                                                                       |
| server_version                   | 2.15.0                                                                       |
| server_extensions                | classification sequence model_repository model_repository(unload_dependents) |
|                                  |  schedule_policy model_configuration system_shared_memory cuda_shared_memory |
|                                  |  binary_tensor_data statistics                                               |
| model_repository_path[0]         | /ocr_serving/models                                                          |
| model_control_mode               | MODE_NONE                                                                    |
| strict_model_config              | 1                                                                            |
| rate_limit                       | OFF                                                                          |
| pinned_memory_pool_byte_size     | 268435456                                                                    |
| response_cache_byte_size         | 0                                                                            |
| min_supported_compute_capability | 0.0                                                                          |
| strict_readiness                 | 1                                                                            |
| exit_timeout                     | 30                                                                           |
+----------------------------------+------------------------------------------------------------------------------+

I0424 08:22:36.648815 2414 server.cc:252] Waiting for in-flight requests to complete.
I0424 08:22:36.648821 2414 model_repository_manager.cc:1055] unloading: rec_postprocess:1
I0424 08:22:36.648860 2414 model_repository_manager.cc:1055] unloading: pp_ocr:1
I0424 08:22:36.648875 2414 model_repository_manager.cc:1055] unloading: det_runtime:1
I0424 08:22:36.648887 2414 model_repository_manager.cc:1055] unloading: det_preprocess:1
I0424 08:22:36.648894 2414 model_repository_manager.cc:1166] successfully unloaded 'pp_ocr' version 1
I0424 08:22:36.648902 2414 model_repository_manager.cc:1055] unloading: det_postprocess:1
I0424 08:22:36.648948 2414 model_repository_manager.cc:1055] unloading: cls_pp:1
I0424 08:22:36.648960 2414 model_repository_manager.cc:1055] unloading: cls_runtime:1
I0424 08:22:36.648984 2414 model_repository_manager.cc:1055] unloading: cls_postprocess:1
I0424 08:22:36.649028 2414 model_repository_manager.cc:1166] successfully unloaded 'cls_pp' version 1
I0424 08:22:36.649060 2414 fastdeploy_runtime.cc:1351] TRITONBACKEND_ModelInstanceFinalize: delete instance state
I0424 08:22:36.649037 2414 server.cc:267] Timeout 30: Found 7 live models and 0 in-flight non-inference requests
I0424 08:22:36.649258 2414 fastdeploy_runtime.cc:1351] TRITONBACKEND_ModelInstanceFinalize: delete instance state
I0424 08:22:36.653471 2414 fastdeploy_runtime.cc:1300] TRITONBACKEND_ModelFinalize: delete model state
I0424 08:22:36.653493 2414 model_repository_manager.cc:1166] successfully unloaded 'cls_runtime' version 1
I0424 08:22:36.655704 2414 fastdeploy_runtime.cc:1300] TRITONBACKEND_ModelFinalize: delete model state
I0424 08:22:36.655827 2414 model_repository_manager.cc:1166] successfully unloaded 'det_runtime' version 1
Cleaning up...
I0424 08:22:37.649199 2414 server.cc:267] Timeout 29: Found 4 live models and 0 in-flight non-inference requests
Cleaning up...
Cleaning up...
Cleaning up...
I0424 08:22:37.691590 2414 model_repository_manager.cc:1166] successfully unloaded 'cls_postprocess' version 1
I0424 08:22:37.692992 2414 model_repository_manager.cc:1166] successfully unloaded 'det_postprocess' version 1
I0424 08:22:37.705958 2414 model_repository_manager.cc:1166] successfully unloaded 'rec_postprocess' version 1
I0424 08:22:37.706510 2414 model_repository_manager.cc:1166] successfully unloaded 'det_preprocess' version 1
I0424 08:22:38.649406 2414 server.cc:267] Timeout 28: Found 0 li

请问如何解决？谢谢！

**Comment by jiyulongxu** [comment]
同问，这边部署也是遇见这个报错，有解决方案吗？
