### ISSUE TITLE
win10 cpu环境下部署C++版本ppyoloe_r的预测结果不正确

### ISSUE THREAD

**Issue by DreamMaker777** [PaddlePaddle/FastDeploy#1872]
fastdeploy是2023.4.25的版本，编译环境：win10，vs2019，cmake；连同example编译成功；预测时出现错误。

vision_detection_paddledetection_infer_ppyoloe_r.exe输出结果错乱：
![2](https://user-images.githubusercontent.com/31379701/234246807-2b67c4de-8350-4312-8ee3-532f6e8050d0.jpg)
python训练和预测的结果都正确，按照教程导出的文件：
![3](https://user-images.githubusercontent.com/31379701/234247192-67c3f7d1-c06c-4781-9ec0-ac9f5e56f9d1.jpg)
看了一下源码，DetectionResult::Str()和VisDetection()是支持rotated box的：
![4](https://user-images.githubusercontent.com/31379701/234247816-062fd7d3-4c13-43cd-a4eb-1fa03d307ef2.jpg)
![5](https://user-images.githubusercontent.com/31379701/234247861-7a29d86d-d45b-4f97-88bd-9bd1b78d81b8.jpg)

同一图像，用vision_detection_paddledetection_infer_yolov3.exe输出结果正确：
![6](https://user-images.githubusercontent.com/31379701/234248025-f6758c0b-e460-43a0-a559-d122b75ff22b.jpg)

请大佬帮助解决一下，谢谢！

**Comment by DefTruth** [comment]
可视化结果是正常的吗？应该是这个结果的Str逻辑有问题

**Comment by DefTruth** [comment]
可以提供一下您导出的模型吗？

**Comment by DefTruth** [comment]
这log结果看起来像是后处理没有走ppyoloer的逻辑，而是走了通用检测模型的逻辑

**Comment by DefTruth** [comment]
另外，请问下你跑的推理后端是什么呢？

**Comment by DreamMaker777** [comment]
> 可视化结果是正常的吗？应该是这个结果的Str逻辑有问题

可视化的结果也不正常，完全错乱。

**Comment by DreamMaker777** [comment]
> 另外，请问下你跑的推理后端是什么呢？

![8](https://user-images.githubusercontent.com/31379701/234270975-4c7e14af-c8b4-426a-a284-ac768765a434.jpg)
勾选了paddle、openvino、ort  backend

**Comment by DreamMaker777** [comment]
> 可以提供一下您导出的模型吗？

怎样提供？

**Comment by DreamMaker777** [comment]
@DefTruth

**Comment by DefTruth** [comment]
百度网盘或者提供一个下载链接都可以（包含yml配置文件）

**Comment by DefTruth** [comment]
> > 另外，请问下你跑的推理后端是什么呢？
> 
> ![8](https://user-images.githubusercontent.com/31379701/234270975-4c7e14af-c8b4-426a-a284-ac768765a434.jpg) 勾选了paddle、openvino、ort backend

看下运行exe的log，提示用的是什么推理后端

**Comment by DreamMaker777** [comment]
> 

![10](https://user-images.githubusercontent.com/31379701/234277714-f6aeb6c6-2043-4c9c-8d20-25ffc0ec8199.jpg)

**Comment by DreamMaker777** [comment]
运行成功的vision_detection_paddledetection_infer_yolov3.exe的log：

![11](https://user-images.githubusercontent.com/31379701/234278090-9375f68e-0d2b-4a3f-b7b0-c7f08cf170bb.jpg)

**Comment by DreamMaker777** [comment]
> 百度网盘或者提供一个下载链接都可以（包含yml配置文件）

链接：https://pan.baidu.com/s/1K6iJGZdKfBJaSNh21yRQFg 
提取码：uxmq 
--来自百度网盘超级会员V5的分享
@DefTruth

**Comment by DefTruth** [comment]
好的，我们复现一下这个问题哈 @linyangshi @thunder95

**Comment by DreamMaker777** [comment]
提供一张测试原图以及python预测的结果：

链接：https://pan.baidu.com/s/18id7-lLF2NekaZf-7LKpzQ 
提取码：hfp4 
--来自百度网盘超级会员V5的分享
@DefTruth

**Comment by thunder95** [comment]
> 好的，我们复现一下这个问题哈 @linyangshi @thunder95

@DreamMaker777 @DefTruth 
从官网下载的l和s模型，用这张测试图片测试没有发现有什么问题。
对比了官网的模型和 @DreamMaker777 给到的模型，我对比了下网络结构在输出节点有明显的差异。
官网的模型输出节点是：
name: tmp_76
type: float32[?,?,8]
name: concat_19.tmp_0
type: float32[?,15,?]

而 @DreamMaker777 给出的模型包含了节点multiclass_nms3，所以输出是:
name: multiclass_nms3_0.tmp_0
type: float32[?,10]
name: multiclass_nms3_0.tmp_2
type: int32[?]

multiclass_nms3里面的算子可能在很多硬件平台上不支持，例如比特大陆的，所以在fastdeploy里将这个算子放在了后处理进行单独计算。

我这导出模型的命令是：
`python tools/export_model.py -c configs/rotate/ppyoloe_r/ppyoloe_r_crn_l_3x_dota.yml -o weights=https://paddledet.bj.bcebos.com/models/ppyoloe_r_crn_l_3x_dota.pdparams export_onnx=True`

请问您导出模型的命令是怎样的？

**Comment by DreamMaker777** [comment]
> > 好的，我们复现一下这个问题哈 @linyangshi @thunder95
> 
> @DreamMaker777 @DefTruth 从官网下载的l和s模型，用这张测试图片测试没有发现有什么问题。 对比了官网的模型和 @DreamMaker777 给到的模型，我对比了下网络结构在输出节点有明显的差异。 官网的模型输出节点是： name: tmp_76 type: float32[?,?,8] name: concat_19.tmp_0 type: float32[?,15,?]
> 
> 而 @DreamMaker777 给出的模型包含了节点multiclass_nms3，所以输出是: name: multiclass_nms3_0.tmp_0 type: float32[?,10] name: multiclass_nms3_0.tmp_2 type: int32[?]
> 
> multiclass_nms3里面的算子可能在很多硬件平台上不支持，例如比特大陆的，所以在fastdeploy里将这个算子放在了后处理进行单独计算。
> 
> 我这导出模型的命令是： `python tools/export_model.py -c configs/rotate/ppyoloe_r/ppyoloe_r_crn_l_3x_dota.yml -o weights=https://paddledet.bj.bcebos.com/models/ppyoloe_r_crn_l_3x_dota.pdparams export_onnx=True`
> 
> 请问您导出模型的命令是怎样的？

您好，我导出模型的指令是：
python tools/export_model.py -c configs/xx/0_wood_ppyoloe_r.yml -o weights=output/xx/best_model.pdparams  无export_onnx=True参数，paddledetection版本是2023.3.14，是否需要提供原始python训练的模型和configs文件？ @thunder95 @DefTruth

**Comment by thunder95** [comment]
@DreamMaker777 建议您那先加上export_onnx=True试试，若还有问题，就麻烦发一下相关文件 我这复现一下

**Comment by thunder95** [comment]
另外对比下官方的yml，是不是有什么差异 @DreamMaker777

**Comment by DreamMaker777** [comment]
> @DreamMaker777 建议您那先加上export_onnx=True试试，若还有问题，就麻烦发一下相关文件 我这复现一下

感谢大佬，加上这个参数就正常了，可视化也正常：
![12](https://user-images.githubusercontent.com/31379701/234442109-6b8aaedf-fd7b-4eb9-bb0c-623609665795.jpg)

建议在ppyoloe_r的教程中加上这个参数：
https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.6/configs/rotate/ppyoloe_r
原导出指令中也无export_onnx=True。
非常感谢二位的帮助！@DefTruth @thunder95

**Comment by huyunlei** [comment]
亲测：ppyoloe_r导出fastdeploy推理模型，得加export_onnx参数
