### ISSUE TITLE
支持Atlas 200的边缘装置上吗？

### ISSUE THREAD

**Issue by eyu11** [PaddlePaddle/FastDeploy#1874]
如题

**Comment by psnow** [comment]
我也计划在Atlas200dk上使用，目前状态是本地编译fastdeploy后能够cpu推理，但是使用huawei_ascend_npu推理报错：
...nadapter/nnadapter/src/runtime/device.cc:529 Find] Failed to load the nnadapter device HAL library for 'huawei_ascend_npu' from libhuawei_ascend_npu.so, libge_compiler.so: cannot open shared object file: No such file or directory

我猜测主要原因是cann的版本不对，fastdeploy使用的是cann5.0.1，我本地升级到cann6.0.1了。不知道如何配置能够重新编译。
备注：使用cann6.0.1已编译成功paddle lite，不知道如何配合fastdeploy使用？

请求帮助！

**Comment by psnow** [comment]
我也计划在Atlas200dk上使用，目前状态是本地编译fastdeploy后能够cpu推理，但是使用huawei_ascend_npu推理报错：
...nadapter/nnadapter/src/runtime/device.cc:529 Find] Failed to load the nnadapter device HAL library for 'huawei_ascend_npu' from libhuawei_ascend_npu.so, libge_compiler.so: cannot open shared object file: No such file or directory

我猜测主要原因是cann的版本不对，fastdeploy使用的是cann5.0.1，我本地升级到cann6.0.1了。不知道如何配置能够重新编译。
备注：使用cann6.0.1已编译成功paddle lite，不知道如何配合fastdeploy使用？

请求帮助！
