### ISSUE TITLE
【 跑官方ARM CPU demo报错 Illegal instruction 】

### ISSUE THREAD

**Issue by Taichipeace** [PaddlePaddle/FastDeploy#1892]
## 环境

- 【FastDeploy版本】： fastdeploy-1.0.6 自行编译的。（因为直接下载预编译包，报同样错误）
- 【编译命令】cmake -B build -DCMAKE_TOOLCHAIN_FILE=./cmake/toolchain.cmake -DWITH_TIMVX=OFF  -DTARGET_ABI=arm64 -DENABLE_FLYCV=ON -DCMAKE_INSTALL_PREFIX=fastdeploy-timvx -DENABLE_VISION=ON -DENABLE_LITE_BACKEND=ON -Wno-dev
- 【系统平台】: Linux x64(Ubuntu 18.04)
- 【硬件】： 荣品A311D，ARM CPU， 4G内存
- 【编译语言】： C++ 

## 问题日志及出现问题的操作流程
- 附上详细的问题日志有助于快速定位分析
- 【模型跑不通】
- - 执行`examples`下的部署示例时，报错Illegal instruction。步骤都是按照这个链接里的教程一步一步操作的：https://github.com/PaddlePaddle/FastDeploy/tree/develop/examples/vision/ocr/PP-OCR/cpu-gpu/cpp
- 模型等文件，也是按照教程下载的，FD库和Demo编译过程都没有报错。
- 执行后，报错如下：

./build/infer_demo ./ch_PP-OCRv3_det_infer ./ch_ppocr_mobile_v2.0_cls_infer ./ch_PP-OCRv3_rec_infer ./ppocr_keys_v1.txt ./12.jpg 3
[WARNING] fastdeploy/runtime/runtime_option.cc(376)::SetTrtInputShape   `RuntimeOption::SetTrtInputShape` will be removed in v1.2.0, please use `RuntimeOption.trt_option.SetShape()` instead.
[WARNING] fastdeploy/runtime/runtime_option.cc(376)::SetTrtInputShape   `RuntimeOption::SetTrtInputShape` will be removed in v1.2.0, please use `RuntimeOption.trt_option.SetShape()` instead.
[WARNING] fastdeploy/runtime/runtime_option.cc(376)::SetTrtInputShape   `RuntimeOption::SetTrtInputShape` will be removed in v1.2.0, please use `RuntimeOption.trt_option.SetShape()` instead.
[I  5/ 3  9:12:45.445 ...ild/Paddle-Lite/lite/core/device_info.cc:1275 Setup] ARM multiprocessors name: HARDWARE        : AMLOGIC

[I  5/ 3  9:12:45.445 ...ild/Paddle-Lite/lite/core/device_info.cc:1276 Setup] ARM multiprocessors number: 6
[I  5/ 3  9:12:45.445 ...ild/Paddle-Lite/lite/core/device_info.cc:1278 Setup] ARM multiprocessors ID: 0, max freq: 2208, min freq: 2208, cluster ID: 1, CPU ARCH: A53
[I  5/ 3  9:12:45.445 ...ild/Paddle-Lite/lite/core/device_info.cc:1278 Setup] ARM multiprocessors ID: 1, max freq: 2208, min freq: 2208, cluster ID: 1, CPU ARCH: A53
[I  5/ 3  9:12:45.445 ...ild/Paddle-Lite/lite/core/device_info.cc:1278 Setup] ARM multiprocessors ID: 2, max freq: 2400, min freq: 2400, cluster ID: 0, CPU ARCH: A73
[I  5/ 3  9:12:45.445 ...ild/Paddle-Lite/lite/core/device_info.cc:1278 Setup] ARM multiprocessors ID: 3, max freq: 2400, min freq: 2400, cluster ID: 0, CPU ARCH: A73
[I  5/ 3  9:12:45.445 ...ild/Paddle-Lite/lite/core/device_info.cc:1278 Setup] ARM multiprocessors ID: 4, max freq: 2400, min freq: 2400, cluster ID: 0, CPU ARCH: A73
[I  5/ 3  9:12:45.445 ...ild/Paddle-Lite/lite/core/device_info.cc:1278 Setup] ARM multiprocessors ID: 5, max freq: 2400, min freq: 2400, cluster ID: 0, CPU ARCH: A73
[I  5/ 3  9:12:45.445 ...ild/Paddle-Lite/lite/core/device_info.cc:1284 Setup] L1 DataCache size is:
[I  5/ 3  9:12:45.445 ...ild/Paddle-Lite/lite/core/device_info.cc:1286 Setup] 32 KB
[I  5/ 3  9:12:45.445 ...ild/Paddle-Lite/lite/core/device_info.cc:1286 Setup] 32 KB
[I  5/ 3  9:12:45.445 ...ild/Paddle-Lite/lite/core/device_info.cc:1286 Setup] 32 KB
[I  5/ 3  9:12:45.445 ...ild/Paddle-Lite/lite/core/device_info.cc:1286 Setup] 32 KB
[I  5/ 3  9:12:45.445 ...ild/Paddle-Lite/lite/core/device_info.cc:1286 Setup] 32 KB
[I  5/ 3  9:12:45.445 ...ild/Paddle-Lite/lite/core/device_info.cc:1286 Setup] 32 KB
[I  5/ 3  9:12:45.445 ...ild/Paddle-Lite/lite/core/device_info.cc:1288 Setup] L2 Cache size is:
[I  5/ 3  9:12:45.445 ...ild/Paddle-Lite/lite/core/device_info.cc:1290 Setup] 512 KB
[I  5/ 3  9:12:45.445 ...ild/Paddle-Lite/lite/core/device_info.cc:1290 Setup] 512 KB
[I  5/ 3  9:12:45.445 ...ild/Paddle-Lite/lite/core/device_info.cc:1290 Setup] 512 KB
[I  5/ 3  9:12:45.445 ...ild/Paddle-Lite/lite/core/device_info.cc:1290 Setup] 512 KB
[I  5/ 3  9:12:45.445 ...ild/Paddle-Lite/lite/core/device_info.cc:1290 Setup] 512 KB
[I  5/ 3  9:12:45.445 ...ild/Paddle-Lite/lite/core/device_info.cc:1290 Setup] 512 KB
[I  5/ 3  9:12:45.445 ...ild/Paddle-Lite/lite/core/device_info.cc:1292 Setup] L3 Cache size is:
[I  5/ 3  9:12:45.445 ...ild/Paddle-Lite/lite/core/device_info.cc:1294 Setup] 0 KB
[I  5/ 3  9:12:45.445 ...ild/Paddle-Lite/lite/core/device_info.cc:1294 Setup] 0 KB
[I  5/ 3  9:12:45.445 ...ild/Paddle-Lite/lite/core/device_info.cc:1294 Setup] 0 KB
[I  5/ 3  9:12:45.445 ...ild/Paddle-Lite/lite/core/device_info.cc:1294 Setup] 0 KB
[I  5/ 3  9:12:45.445 ...ild/Paddle-Lite/lite/core/device_info.cc:1294 Setup] 0 KB
[I  5/ 3  9:12:45.445 ...ild/Paddle-Lite/lite/core/device_info.cc:1294 Setup] 0 KB
[I  5/ 3  9:12:45.445 ...ild/Paddle-Lite/lite/core/device_info.cc:1296 Setup] Total memory: 3839260KB
[I  5/ 3  9:12:45.445 ...ild/Paddle-Lite/lite/core/device_info.cc:1297 Setup] SVE2 support: 0
[I  5/ 3  9:12:45.445 ...ild/Paddle-Lite/lite/core/device_info.cc:1298 Setup] SVE2 f32mm support: 0
[I  5/ 3  9:12:45.445 ...ild/Paddle-Lite/lite/core/device_info.cc:1299 Setup] SVE2 i8mm support: 0
[I  5/ 3  9:12:45.445 ...ly_build/Paddle-Lite/lite/api/cxx_api.cc:366 Build] Load model from file.
[I  5/ 3  9:12:45.445 ...e-Lite/lite/model_parser/model_parser.cc:241 LoadModelPb] Loading topology data from ./ch_PP-OCRv3_det_infer/inference.pdmodel
[I  5/ 3  9:12:45.479 ...e-Lite/lite/model_parser/model_parser.cc:259 LoadModelPb] Loading params data from ./ch_PP-OCRv3_det_infer/inference.pdiparams
[I  5/ 3  9:12:45.482 ...e-Lite/lite/model_parser/model_parser.cc:269 LoadModelPb] 1. Model is successfully loaded!
Illegal instruction

**Comment by DefTruth** [comment]
A311D可以参考编译文档：
- https://github.com/PaddlePaddle/FastDeploy/blob/develop/docs/cn/build_and_install/a311d.md  

编译 A311D 部署库时WITH_TIMVX需要设置为 ON

**Comment by Taichipeace** [comment]
解决了！感谢 ！
