### ISSUE TITLE
如果提高FastDeploy Serving 的QPS。

### ISSUE THREAD

**Issue by cumthxy** [PaddlePaddle/FastDeploy#1894]
使用默认设置 FastDeploy Serving C++部署 ppocr_v3  qps最大只有4 左右。如果提升？

**Comment by xiaomi0922** [comment]
我正在尝试部署多个ppocr，nginx负载均衡提高并发

**Comment by cumthxy** [comment]
> 我正在尝试部署多个ppocr，nginx负载均衡提高并发

你是多机吧。你单机测过qps 么

**Comment by xiaomi0922** [comment]
> 

我是基于python部署的，单机的话在cpu上图片文字在40-50个的情况下勉强达到2，多开实例个数和增加线程数对qps的提升效果不明显
