### ISSUE TITLE
在vs2022使用预编译库的程序无法正常启动(0xc0000142)

### ISSUE THREAD

**Issue by 1821746019** [PaddlePaddle/FastDeploy#1898]
## 环境
![fastdeploy预编译库1 0 6](https://user-images.githubusercontent.com/107804044/236193616-9d021fb4-3b9b-41fc-83ca-953f7b66dce4.png)
- 【FastDeploy版本】：[Visual Studio 16 2019编译产出的fastdeploy-win-x64-1.0.6,官方预编译库](https://github.com/PaddlePaddle/FastDeploy/blob/develop/docs/cn/build_and_install/download_prebuilt_libraries.md)

- 【系统平台】: win10_20H2;vs2022
- 【硬件】： cpu: i5-12400f
- 【编译语言】： C++ 

## 问题日志及出现问题的操作流程
尝试用fastdeploy部署模型
已经正确链接lib,并拷贝对应的dll到项目,
控制台无任何输出,运行程序直接弹窗报错:`应用程序无法正常启动(0xc0000142)。请单击“确定”关闭应用程序。 `.
调用堆栈,使用dll和lib如下

![应用程序无法正常启动](https://user-images.githubusercontent.com/107804044/236193594-178a47a8-8d6b-412f-8d66-22aaa05d5d9e.png)
![调用堆栈](https://user-images.githubusercontent.com/107804044/236193611-69278ccb-d95d-4395-8772-5b31fbe5f472.png)
![断点没有断下来,异常发生在调用main前](https://user-images.githubusercontent.com/107804044/236193602-18c843d1-4368-46e6-999d-1e01146e209b.png)
![把预编译库下的所有dll拷贝到项目](https://user-images.githubusercontent.com/107804044/236193581-2f75bf62-5392-468f-8d8e-c54ed3b1cd1d.png)
![链接的lib](https://user-images.githubusercontent.com/107804044/236193618-ab8d8709-be59-40f0-af39-075d0ff6d578.png)

## 排查问题
尝试安装微软常用运行时库重启无解,拷贝项目的x64\Debug目录到vm虚拟机win11报相同错误,初步判断是编译出来的程序有问题,也就是说预编译库和vs2022不兼容?
难道我需要自己编译fastdeploy?

**Comment by DefTruth** [comment]
暂时不支持debug模式

**Comment by DefTruth** [comment]
windows下可以使用依赖库管理工具来管理fd的依赖库：  
- https://github.com/PaddlePaddle/FastDeploy/blob/develop/docs/cn/faq/usage_of_fastdeploy_init_bat.md

**Comment by 1821746019** [comment]
> 暂时不支持debug模式

release模式下编译运行保同样的错误

**Comment by 1821746019** [comment]
> windows下可以使用依赖库管理工具来管理fd的依赖库：
> 
> * https://github.com/PaddlePaddle/FastDeploy/blob/develop/docs/cn/faq/usage_of_fastdeploy_init_bat.md

我尝试过用fastdeploy_init.bat一键复制dll,但是报错`The system cannot find the file specified.`,只好自己手动复制

![fastdeploy_init bat无法正常复制dll到指定目录](https://user-images.githubusercontent.com/107804044/236454983-96eb867c-1b62-4da9-b94f-cb53175c021a.png)

**Comment by DefTruth** [comment]
用管理员权限打开终端试一下

**Comment by 1821746019** [comment]
> 用管理员权限打开终端试一下

我的`以管理员批准模式运行所有管理员`是关闭的,所以我运行任何程序默认都是管理员身份,不存在权限不够的问题.另外附上详细日志:
![开启info的日志,目录确实存在,但是就是复制不了 png](https://user-images.githubusercontent.com/107804044/236457754-b74c3077-c6c3-46e9-898e-897e69a1997e.png)

**Comment by alasox** [comment]
如果包含OpenVINO后端，还需要将他的plugins.xml拷贝到exe所在的目录；
把“.\third_libs\install\openvino\runtime\bin"里的所有文件都复制过去

**Comment by 1821746019** [comment]
> 如果包含OpenVINO后端，还需要将他的plugins.xml拷贝到exe所在的目录； 把“.\third_libs\install\openvino\runtime\bin"里的所有文件都复制过去

谢谢哥们,程序终于可以正常运行了

**Comment by WilliamQf-AI** [comment]
刚刚解决了这个问题，在这里又看到

**Comment by universea** [comment]
<img width="375" alt="1684364195918" src="https://github.com/PaddlePaddle/FastDeploy/assets/13444641/227f0449-b524-4378-acd1-7c8035051c16">
我使用QT，也出现了错误，编译能通过，运行出错，也尝试了吧openvino的bin全复制过去也不行
