### ISSUE TITLE
FastDeploy模型预测耗时过长

### ISSUE THREAD

**Issue by Mysister** [PaddlePaddle/FastDeploy#1908]
## 环境
- 【FastDeploy版本】： fastdeploy- Windows-gpu-1.0.6
- 【系统平台】: Windows x64(Windows10)
- 【硬件】： 笔记本电脑 Nvidia GPU 2060 6G显存， CUDA 11.2  CUDNN 8.2
- 【编译语言】： Python(3.9）

## 问题
- 【性能问题】
- - 在使用语义分割模型（PP_LiteSeg_B_STDC2_cityscapes_without_argmax_infer）每张图像耗时约600ms，
- - 分类模型（ResNet50_vd_infer）耗时6ms，
- - 检测模型（ppyoloe_plus_crn_m_80e_coco）耗时1400ms（模型均是模型库中下载）
- - 分割和检测耗时很长，请问哪方面可能影响了速度，如何排查和解决长耗时

**Comment by DefTruth** [comment]
模型测速，请参考相关issue: 
- https://github.com/PaddlePaddle/FastDeploy/issues/1690

**Comment by tigflanker** [comment]
@Mysister 楼主，请问一下您这边是咋估算每个子模型耗时的呀？
