### ISSUE TITLE
from .libs.fastdeploy_main import * ImportError: /.local/lib/python3.10/site-packages/fastdeploy/libs/third_libs/paddle_inference/paddle/lib/libpaddle_inference.so: undefined symbol: dnnl_layer_normalization_v2_forward_desc_init

### ISSUE THREAD

**Issue by cqray1990** [PaddlePaddle/FastDeploy#1910]
*********************************************
温馨提示：根据社区不完全统计，按照模板提问，可以加快回复和解决问题的速度
*********************************************

## 环境

- 【FastDeploy版本】： 说明具体的版本，如fastdeploy-linux-gpu-0.8.0
- 【编译命令】如果您是自行编译的FastDeploy，请说明您的编译方式（参数命令）
- 【系统平台】: Linux x64(Ubuntu 18.04) / Windows x64(Windows10) / Mac OSX arm(12.0) / Mac OSX intel(12.0)
- 【硬件】： 说明具体硬件型号，如 Nvidia GPU 3080TI， CUDA 11.2 CUDNN 8.3
- 【编译语言】： C++ / Python 3.10

## 问题日志及出现问题的操作流程
- 附上详细的问题日志有助于快速定位分析
- 【模型跑不通】
- - 先执行`examples`下的部署示例，包括使用examples提供的模型，确认是否可以正确执行
- - 如若`examples`下的代码可以运行，但自己的模型，或自己的代码不能运行
- - - 提供复现问题的 代码+模型+错误log，供工程师快速定位问题
- 【模型精度问题】
- - 先执行`examples`下的部署示例，包括使用examples提供的模型，确认是否可以正确执行
- - 如若`examples`下的代码可以运行，但自己的模型，或自己的代码不能运行
- - - 提供复现问题的 代码+模型+错误log，供工程师快速定位问题
- 【性能问题】描述清楚对比的方式
- - 注意性能测试，循环跑N次，取后80%的用时平均（模型启动时，刚开始受限于资源分配，速度会较慢）
- - FastDeploy的Predict包含模型本身之外的数据前后处理用时
- - - 提供复现问题的 代码+模型+错误log，供工程师快速定位问题

paddlepaddle-gpu 2.4.2 post116
FastDeploy 1.0.6

代码脚本导入就出错
from pprint import pprint
from paddlenlp import Taskflow
import argparse
import distutils.util
import math
import os
import re
from pprint import pprint
import fastdeploy as fd
import six
from paddlenlp.transformers import AutoTokenizer
from paddlenlp.utils.tools import get_bool_ids_greater_than, get_span

 

错误：
from .libs.fastdeploy_main import *
ImportError:.local/lib/python3.10/site-packages/fastdeploy/libs/third_libs/paddle_inference/paddle/lib/libpaddle_inference.so: undefined symbol: dnnl_layer_normalization_v2_forward_desc_init

**Comment by DefTruth** [comment]
升级fd到最新版本

**Comment by DefTruth** [comment]
升级paddle到develop版本：  
```bash
python -m pip install paddlepaddle-gpu==0.0.0.post112 -f https://www.paddlepaddle.org.cn/whl/linux/gpu/develop.html
```

**Comment by DefTruth** [comment]
由于paddle升级了protobuf，所以目前fd默认支持的是最新的paddle版本
