### ISSUE TITLE
c++部署如何只保存分割结果

### ISSUE THREAD

**Issue by guoyunqingyue** [PaddlePaddle/FastDeploy#1911]
看到有函数VisSegmentation可以得到分割效果，使用哪个函数可以只保存分割的灰度图结果（即每个像素的标签，res.Str()中二维矩阵的部分）

**Comment by DefTruth** [comment]
可以参考API文档：https://baidu-paddle.github.io/fastdeploy-api/cpp/html/structfastdeploy_1_1vision_1_1SegmentationResult.html
