### ISSUE TITLE
TensorRT后端压测报错

### ISSUE THREAD

**Issue by Lennon-cheng** [PaddlePaddle/FastDeploy#1912]
## 环境
- 【FastDeploy版本】： 说明具体的版本，如fastdeploy-linux-gpu-1.0.3

## 问题日志及出现问题的操作流程
部署 TensorRT bert 模型后，进行压测，一压测就会有如下报错
<img width="944" alt="image" src="https://user-images.githubusercontent.com/33142144/236716433-e1a8bd75-02ca-4ce3-bfa0-8376890dca89.png">
尝试用onnx推理后端，是可以进行压测

**Comment by DefTruth** [comment]
可以用最新的1.0.6版本尝试下

**Comment by Lennon-cheng** [comment]
@DefTruth  想问下，更新1.0.6GPU版本后，git clone、apt-get等操作都会显示连接 某 ip 报错，这个是在哪配置吗？
<img width="752" alt="image" src="https://user-images.githubusercontent.com/33142144/236750020-4c5a149a-f49d-48f0-9ebe-f95c7f40221c.png">

**Comment by pangdahua** [comment]
@Lennon-cheng 
进入容器内
 unset http_proxy
unset https_proxy
