### ISSUE TITLE
rk3588编译后报错FastDeploy initalized failed！

### ISSUE THREAD

**Issue by 376428152** [PaddlePaddle/FastDeploy#1917]
*********************************************
温馨提示：根据社区不完全统计，按照模板提问，可以加快回复和解决问题的速度
*********************************************

## 环境

- 【FastDeploy版本】： 说明具体的版本，如fastdeploy-linux-gpu-0.8.0
- 【编译命令】：
              export ENABLE_RKNPU2_BACKEND=ON
              export ENABLE_VISION=ON
              export RKNN2_TARGET_SOC=RK3588
              python3 setup.py build
              python3 setup.py bdist_wheel
- 【系统平台】: Linux x64(Ubuntu 20.04)
- 【硬件】：rk3588
- 【编译语言】： python3.8 / python3.9

## 问题日志及出现问题的操作流程  （pytho3.8\3.9都编译过，都报这个错误，但是用https://wiki.t-firefly.com/zh_CN/Core-3588J/usage_fastdeploy.html   里面给的预编译包是不会报错的，不过这是老版本的没有rkyolo）
   cd dist
   pip3 install fastdeploy_python-0.0.0-cp39-cp39-linux_aarch64.whl
  安装了这个编译好的包之后，我进入python导入fastdeploy报错:FastDeploy initalized failed!

![5ee48918d44ef90e6ccf5cb454f32b7](https://user-images.githubusercontent.com/117901756/236792478-8e9618c1-522b-4f2a-a583-0e3ed64f032d.jpg)

**Comment by 376428152** [comment]
python3.8\python3.9都试过了，都不行

**Comment by zg651413411** [comment]
你好有解决嘛，我现在也遇到这个问题
