### ISSUE TITLE
能不能给个java调用fastdeploy服务化serving的示例呀，grpc或者http的都可以晒，这个也莫有接口文档，脑袋有点疼呀

### ISSUE THREAD

**Issue by xiac72145** [PaddlePaddle/FastDeploy#1921]
## Environment

FastDeploy version: e.g 0.8.0 or the latest code in develop branch
OS Platform: e.g. Linux x64 / Windows x64 / Mac OSX 12.1(arm or intel)
Hardware: e.g. Nvidia GPU 3080Ti  CUDA 11.2 CUDNN 8.3
Program Language: e.g. Python 3.8

## Problem description
Please attach the log file if there's problem happend.

**Comment by polarisunny** [comment]
一直都没有，我也在研究怎么用java调用serving，实在不行就用DJL去了

**Comment by sniperking1234** [comment]
+1，希望能出http的接口文档
