### ISSUE TITLE
ocr识别出来的结果为乱码

### ISSUE THREAD

**Issue by WilliamQf-AI** [PaddlePaddle/FastDeploy#1928]
windows环境下ocr识别出来的结果为乱码，模型为 ch_PP-OCRv3_，已经检查并替换过ppocr_keys_v1.txt
如下图：
![image](https://github.com/PaddlePaddle/FastDeploy/assets/40328063/e520aa4b-cd2a-4ddc-86df-7750278e6125)

**Comment by WilliamQf-AI** [comment]
@DefTruth

**Comment by DefTruth** [comment]
设置一下源码文件的字符集的编码格式

**Comment by DefTruth** [comment]
参考： 
- https://github.com/PaddlePaddle/FastDeploy/blob/develop/docs/cn/faq/build_on_win_with_gui.md#%E7%89%B9%E5%88%AB%E6%8F%90%E7%A4%BA

**Comment by WilliamQf-AI** [comment]
设置后还是乱码，设置如下：
![image](https://github.com/PaddlePaddle/FastDeploy/assets/40328063/1eb9d94e-b156-47c9-8944-48842816aa3e)
@DefTruth

**Comment by WilliamQf-AI** [comment]
谢谢老师耐心答复，这个“ppocr_keys_v1.txt”字典文件用记事本另存ansi编码后解决了。
