### ISSUE TITLE
 multimodal stable_diffusion cpp无法编译

### ISSUE THREAD

**Issue by tobzk** [PaddlePaddle/FastDeploy#1946]
- 【FastDeploy版本】： 所有版本
- 【编译命令】cmake .. -DFASTDEPLOY_INSTALL_DIR=D:\Paddle\compiled_fastdeploy -DTRT_DIRECTORY="C:\Program Files\NVIDIA GPU Computing Toolkit\TensorRT-8.4.2.4" -DCUDA_DIRECTORY="C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.7"
msbuild main.sln /m /p:Configuration=Release /p:Platform=x64
- 【系统平台】: Windows x64(Windows11) 
- 【硬件】：Nvidia GPU 3080， CUDA 11.7 TensorRT-8.4.2.4
- 【编译语言】： C++ vs2022

## 问题说明
编译fastdeploy以及其它cpp examples都没问题，只有multimodal下stable_diffusion cpp无法link。

## 错误信息
 “D:\project\ai\FastDeploy\examples\multimodal\stable_diffusion\cpp\build\main.sln”(默认目标) (1) ->
       “D:\project\ai\FastDeploy\examples\multimodal\stable_diffusion\cpp\build\main.vcxproj.metaproj”(默认目标) (2) ->
       “D:\project\ai\FastDeploy\examples\multimodal\stable_diffusion\cpp\build\main.vcxproj”(默认目标) (4) ->
       (Link 目标) ->
         pipeline_stable_diffusion_inpaint.obj : error LNK2019: 无法解析的外部符号 "void __cdecl fastdeploy::function::GaussianR
       andom(class std::vector<__int64,class std::allocator<__int64> > const &,struct fastdeploy::FDTensor *,enum fastd
       eploy::FDDataType,float,float,int)" (?GaussianRandom@function@fastdeploy@@YAXAEBV?$vector@_JV?$allocator@_J@std@
       @@std@@PEAUFDTensor@2@W4FDDataType@2@MMH@Z)，函数 "public: void __cdecl fastdeploy::StableDiffusionInpaintPipeline:
       :Predict(class std::vector<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char>
        >,class std::allocator<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >
       > > const &,class cv::Mat const &,class cv::Mat const &,class std::vector<struct fastdeploy::FDTensor,class std:
       :allocator<struct fastdeploy::FDTensor> > *,int,int,int,float,class std::vector<class std::basic_string<char,str
       uct std::char_traits<char>,class std::allocator<char> >,class std::allocator<class std::basic_string<char,struct
        std::char_traits<char>,class std::allocator<char> > > > const &,int,float,unsigned int,struct fastdeploy::FDTen
       sor const *,bool,void (__cdecl*)(int,int,struct fastdeploy::FDTensor *),int)" (?Predict@StableDiffusionInpaintPi
       peline@fastdeploy@@QEAAXAEBV?$vector@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@V?$allocator@
       V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@2@@std@@AEBVMat@cv@@1PEAV?$vector@UFDTensor@fastd
       eploy@@V?$allocator@UFDTensor@fastdeploy@@@std@@@4@HHHM0HMIPEBUFDTensor@2@_NP6AXHHPEAU82@@ZH@Z) 中引用了该符号 [D:\proj
       ect\ai\FastDeploy\examples\multimodal\stable_diffusion\cpp\build\main.vcxproj]
         D:\project\ai\FastDeploy\examples\multimodal\stable_diffusion\cpp\build\Release\main.exe : fatal error LNK1120
       : 1 个无法解析的外部命令 [D:\project\ai\FastDeploy\examples\multimodal\stable_diffusion\cpp\build\main.vcxproj]

**Comment by DefTruth** [comment]
c++版本暂不支持

**Comment by tobzk** [comment]
请问是暂不支持vs2022，还是stable_diffusion暂不支持c++，如果是前者，我可以花点时间修改代码。
如果是后者，我就不折腾了。

**Comment by DefTruth** [comment]
c++不支持
