### ISSUE TITLE
执行完成没有报告返回Runtime(ms): 0.0

### ISSUE THREAD

**Issue by verseboys** [PaddlePaddle/FastDeploy#1947]
*********************************************
温馨提示：根据社区不完全统计，按照模板提问，可以加快回复和解决问题的速度
*********************************************

## 环境

- 【FastDeploy版本】： 说明具体的版本，如fastdeploy-linux-gpu-0.8.0
- 【编译命令】如果您是自行编译的FastDeploy，请说明您的编译方式（参数命令）
- 【系统平台】: Linux x64(Ubuntu 20.04) / Windows x64(Windows10) 
- 【硬件】： 说明具体硬件型号，如 Nvidia GPU 3080TI， CUDA 11.2 CUDNN 8.3
- 【编译语言】： C++ / Python(3.9）

## 问题日志及出现问题的操作流程  
- 附上详细的问题日志有助于快速定位分析
只有日志
执行 性能测试
[Benchmark Testing](https://github.com/PaddlePaddle/FastDeploy/blob/develop/benchmark)
~~~shell
python benchmark_ppcls.py --model MobileNetV1_x0_25_infer --image ILSVRC2012_val_00000010.jpeg --cpu_num_thread 8 --iter_num 2000 --backend paddle
~~~

[INFO] fastdeploy/vision/common/processors/transform.cc(93)::fastdeploy::vision::FuseNormalizeHWC2CHW   Normalize and HWC2CHW are fused to NormalizeAndPermute  in preprocessing pipeline.
[INFO] fastdeploy/vision/common/processors/transform.cc(159)::fastdeploy::vision::FuseNormalizeColorConvert     BGR2RGB and NormalizeAndPermute are fused to NormalizeAndPermute with swap_rb=1
WARNING: Logging before InitGoogleLogging() is written to STDERR
W0516 16:18:09.791821 43208 analysis_config.cc:972] It is detected that mkldnn and memory_optimize_pass are enabled at the same time, but they are not supported yet. Currently, memory_optimize_pass is explicitly disabled
[INFO] fastdeploy/runtime/runtime.cc(266)::fastdeploy::Runtime::CreatePaddleBackend     Runtime initialized with Backend::PDINFER in Device::CPU.
Runtime(ms): 0.0

**Comment by DefTruth** [comment]
python benchmark已经弃用，请使用c++ benchmark:  
- https://github.com/PaddlePaddle/FastDeploy/tree/develop/benchmark/cpp
