### ISSUE TITLE
请问版面分析的返回字段DetectionResult的字段到底是什么意思？

### ISSUE THREAD

**Issue by WilliamQf-AI** [PaddlePaddle/FastDeploy#1948]
如下图：
问题1：label_ids被解释为“目标类别”，但是其数据类型为int32_t,请问其值具体代表的意思是什么？目前猜测是 {"text",  "title", "figure", 
    "figure_caption","table",  "table_caption", "header", "footer", "reference", "equation"} 或者{"text", "title", "list", "table", "figure"}的 
     index，但是实际测试好像对应不上。
问题2：label_ids的描述对象，是否是同一个index的boxes的成员（例如：label_ids[i]描述了boxes[i]的类型）？
![image](https://github.com/PaddlePaddle/FastDeploy/assets/40328063/a195480a-c062-40a3-96c9-f46f93e53b64)
唯一找到的文档没有看到具体说明。
https://github.com/PaddlePaddle/FastDeploy/blob/develop/docs/api/vision_results/detection_result_CN.md

**Comment by WilliamQf-AI** [comment]
@DefTruth

**Comment by WilliamQf-AI** [comment]
@DefTruth

**Comment by WilliamQf-AI** [comment]
@jiangjiajun

**Comment by DefTruth** [comment]
label_ids代表的就是类别的标签id，每个box对应一个预测的标签，fd的result只输出预测到的数值id，不处理具体的标签内容，比如标签0代表的是什么含义。这个不属于后处理的部分。

**Comment by WilliamQf-AI** [comment]
> label_ids代表的就是类别的标签id，每个box对应一个预测的标签，fd的result只输出预测到的数值id，不处理具体的标签内容，比如标签0代表的是什么含义。这个不属于后处理的部分。

如图：
那我现在boxes[0]的标签是啥？是否label_ids[0]?那么label_ids[0]的值在这里是0，那这个0是什么标签？
boxes：
![image](https://github.com/PaddlePaddle/FastDeploy/assets/40328063/d6f29625-a3eb-4c41-b019-26d0808f68ca)
label_ids：
![image](https://github.com/PaddlePaddle/FastDeploy/assets/40328063/955c9bbb-a775-49ed-9d57-8b9e56b5bd80)

**Comment by WilliamQf-AI** [comment]
@DefTruth

**Comment by WilliamQf-AI** [comment]
忽然想起查看fastdeploy::vision::VisDetection函数的源代码找到了答案，确实是我猜测的对应方式，之前感觉不对，应该是boxes里面是没有排序的，
![Uploading image.png…]()
