### ISSUE TITLE
android平台使用nb模型

### ISSUE THREAD

**Issue by WilliamQf-AI** [PaddlePaddle/FastDeploy#1949]
如下图所示:
官方示例代码，是否这样修改后就可以在直接使用nb模型？
![image](https://github.com/PaddlePaddle/FastDeploy/assets/40328063/fb10e5e6-3374-4c3f-90f8-6df340eaf48f)

**Comment by DefTruth** [comment]
暂时不支持，目前只支持Paddle Lite Full API

**Comment by WilliamQf-AI** [comment]
> 暂时不支持，目前只支持Paddle Lite Full API

好的，谢谢
