### ISSUE TITLE
fastdeploy部署paddleClas,无法加载模型

### ISSUE THREAD

**Issue by jiyulongxu** [PaddlePaddle/FastDeploy#1954]
## 环境

- 【FastDeploy版本】： [说明具体的版本，如fastdeploy-linux-gpu-0.8.0](fastdeploy:1.0.4-cpu-only-21.10)
- 【系统平台】: Centos7
- 【硬件】： CPU
- 【编译语言】： Python(3.7或3.8等）

E0517 08:58:57.562967 604 model_repository_manager.cc:1890] Poll failed for model directory 'runtime': instance group runtime_0 of model runtime has kind KIND_CPU but specifies one or more GPUs
E0517 08:58:57.563080 604 model_repository_manager.cc:1375] Invalid argument: ensemble paddlecls contains models that are not available: runtime
I0517 08:58:57.563135 604 model_repository_manager.cc:1022] loading: postprocess:1
I0517 08:58:57.663327 604 model_repository_manager.cc:1022] loading: preprocess:1
I0517 08:58:57.665970 604 python.cc:1875] TRITONBACKEND_ModelInstanceInitialize: postprocess_0 (CPU device 0)
model_config: {'name': 'postprocess', 'platform': '', 'backend': 'python', 'version_policy': {'latest': {'num_versions': 1}}, 'max_batch_size': 16, 'input': [{'name': 'post_input', 'data_type': 'TYPE_FP32', 'format': 'FORMAT_NONE', 'dims': [1000], 'is_shape_tensor': False, 'allow_ragged_batch': False}], 'output': [{'name': 'post_output', 'data_type': 'TYPE_STRING', 'dims': [-1], 'label_filename': '', 'is_shape_tensor': False}], 'batch_input': [], 'batch_output': [], 'optimization': {'priority': 'PRIORITY_DEFAULT', 'input_pinned_memory': {'enable': True}, 'output_pinned_memory': {'enable': True}, 'gather_kernel_buffer_threshold': 0, 'eager_batching': False}, 'instance_group': [{'name': 'postprocess_0', 'kind': 'KIND_CPU', 'count': 1, 'gpus': [], 'secondary_devices': [], 'profile': [], 'passive': False, 'host_policy': ''}], 'default_model_filename': '', 'cc_model_filenames': {}, 'metric_tags': {}, 'parameters': {}, 'model_warmup': []}
postprocess input names: ['post_input']
postprocess output names: ['post_output']
I0517 08:58:57.897360 604 model_repository_manager.cc:1183] successfully loaded 'postprocess' version 1
I0517 08:58:57.897528 604 python.cc:1875] TRITONBACKEND_ModelInstanceInitialize: preprocess_0 (CPU device 0)
model_config: {'name': 'preprocess', 'platform': '', 'backend': 'python', 'version_policy': {'latest': {'num_versions': 1}}, 'max_batch_size': 16, 'input': [{'name': 'preprocess_input', 'data_type': 'TYPE_UINT8', 'format': 'FORMAT_NONE', 'dims': [-1, -1, 3], 'is_shape_tensor': False, 'allow_ragged_batch': False}], 'output': [{'name': 'preprocess_output', 'data_type': 'TYPE_FP32', 'dims': [3, 224, 224], 'label_filename': '', 'is_shape_tensor': False}], 'batch_input': [], 'batch_output': [], 'optimization': {'priority': 'PRIORITY_DEFAULT', 'input_pinned_memory': {'enable': True}, 'output_pinned_memory': {'enable': True}, 'gather_kernel_buffer_threshold': 0, 'eager_batching': False}, 'instance_group': [{'name': 'preprocess_0', 'kind': 'KIND_CPU', 'count': 1, 'gpus': [], 'secondary_devices': [], 'profile': [], 'passive': False, 'host_policy': ''}], 'default_model_filename': '', 'cc_model_filenames': {}, 'metric_tags': {}, 'parameters': {}, 'model_warmup': []}
preprocess input names: ['preprocess_input']
preprocess output names: ['preprocess_output']
[INFO] fastdeploy/vision/common/processors/transform.cc(93)::FuseNormalizeHWC2CHW       Normalize and HWC2CHW are fused to NormalizeAndPermute  in preprocessing pipeline.
[INFO] fastdeploy/vision/common/processors/transform.cc(159)::FuseNormalizeColorConvert BGR2RGB and NormalizeAndPermute are fused to NormalizeAndPermute with swap_rb=1
I0517 08:58:58.124272 604 model_repository_manager.cc:1183] successfully loaded 'preprocess' version 1
I0517 08:58:58.124385 604 server.cc:522] 
+------------------+------+
| Repository Agent | Path |
+------------------+------+
+------------------+------+

I0517 08:58:58.124451 604 server.cc:549] 
+---------+-------------------------------------------------------+--------------------------------------------------+
| Backend | Path                                                  | Config                                           |
+---------+-------------------------------------------------------+--------------------------------------------------+
| python  | /opt/tritonserver/backends/python/libtriton_python.so | {"cmdline":{"shm-default-byte-size":"10485760"}} |
+---------+-------------------------------------------------------+--------------------------------------------------+

I0517 08:58:58.124522 604 server.cc:592] 
+-------------+---------+--------+
| Model       | Version | Status |
+-------------+---------+--------+
| postprocess | 1       | READY  |
| preprocess  | 1       | READY  |
+-------------+---------+--------+

I0517 08:58:58.124636 604 tritonserver.cc:1920] 
+----------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------+
| Option                           | Value                                                                                                                                        |
+----------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------+
| server_id                        | triton                                                                                                                                       |
| server_version                   | 2.15.0                                                                                                                                       |
| server_extensions                | classification sequence model_repository model_repository(unload_dependents) schedule_policy model_configuration system_shared_memory cuda_s |
|                                  | hared_memory binary_tensor_data statistics                                                                                                   |
| model_repository_path[0]         | /serving/models                                                                                                                              |
| model_control_mode               | MODE_NONE                                                                                                                                    |
| strict_model_config              | 1                                                                                                                                            |
| rate_limit                       | OFF                                                                                                                                          |
| pinned_memory_pool_byte_size     | 268435456                                                                                                                                    |
| response_cache_byte_size         | 0                                                                                                                                            |
| min_supported_compute_capability | 0.0                                                                                                                                          |
| strict_readiness                 | 1                                                                                                                                            |
| exit_timeout                     | 30                                                                                                                                           |
+----------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------+

I0517 08:58:58.124741 604 server.cc:252] Waiting for in-flight requests to complete.
I0517 08:58:58.124752 604 model_repository_manager.cc:1055] unloading: preprocess:1
I0517 08:58:58.124783 604 model_repository_manager.cc:1055] unloading: postprocess:1
I0517 08:58:58.124834 604 server.cc:267] Timeout 30: Found 2 live models and 0 in-flight non-inference requests
I0517 08:58:59.124954 604 server.cc:267] Timeout 29: Found 2 live models and 0 in-flight non-inference requests
Cleaning up...
Cleaning up...
I0517 08:58:59.172150 604 model_repository_manager.cc:1166] successfully unloaded 'preprocess' version 1
I0517 08:58:59.172710 604 model_repository_manager.cc:1166] successfully unloaded 'postprocess' version 1
I0517 08:59:00.125229 604 server.cc:267] Timeout 28: Found 0 live models and 0 in-flight non-inference requests
error: creating server: Internal - failed to load all models

**Comment by whisky-12** [comment]
您好 同样的问题，请问解决了嘛
