### ISSUE TITLE
请问添加自定义推理后端？

### ISSUE THREAD

**Issue by hellojiabin** [PaddlePaddle/FastDeploy#1958]
你好，请问如何添加自定义后端？有相关文档吗？

**Comment by DefTruth** [comment]
可以参考：https://github.com/PaddlePaddle/FastDeploy/blob/develop/docs/cn/faq/how_to_add_backend.md

**Comment by hellojiabin** [comment]
> 可以参考：https://github.com/PaddlePaddle/FastDeploy/blob/develop/docs/cn/faq/how_to_add_backend.md

多谢
