### ISSUE TITLE
PaddleSeg/PP-Matting  示例文档打开404了

### ISSUE THREAD

**Issue by HuiTurn** [PaddlePaddle/FastDeploy#1964]
![image](https://github.com/PaddlePaddle/FastDeploy/assets/28799892/560b86ee-d61e-4015-8f1f-f627b197804a)

![image](https://github.com/PaddlePaddle/FastDeploy/assets/28799892/2c01aa71-3a5b-46cc-bc9d-54e17e43869a)

**Comment by DefTruth** [comment]
参考这个文档：https://github.com/PaddlePaddle/FastDeploy/tree/develop/examples/vision/segmentation/paddleseg/matting
