### ISSUE TITLE
部署实例分割模型如何获取mask和轮廓contours

### ISSUE THREAD

**Issue by happybear1015** [PaddlePaddle/FastDeploy#1965]
我用paddledection训练好的实例分割模型（mask rcnn算法），采用fastdeploy部署，想要得到实际的mask和轮廓contours，写了如下代码。但是最终得到结果不对，保存的轮廓图mask_big如下：
![1 jpgmask_43](https://github.com/PaddlePaddle/FastDeploy/assets/66996161/fad18e5c-3355-45d9-a363-bef5802eb798)，是不对的，请问怎么修改代码？
#include "fastdeployision.h"

#ifdef WIN32
const char sep = '\\';
#else
const char sep = '/';
#endif

__declspec(dllexport) void main(const std::string& model_dir, const std::string& image_dir, int run_option);

void main(const std::string& model_dir, const std::string& image_file, int run_option) {
    auto model_file = model_dir + sep + "model.pdmodel";
    auto params_file = model_dir + sep + "model.pdiparams";
    auto config_file = model_dir + sep + "infer_cfg.yml";
    auto option = fastdeploy::RuntimeOption();

    if (run_option == 0) {
        option.UseCpu();
    }
    else if (run_option == 1) {
        option.UseGpu();
    }
    else {
        std::cerr << "Invalid run option." << std::endl;
        return;
    }

    auto model = fastdeploy::vision::detection::MaskRCNN(model_file, params_file,
        config_file, option);
    if (!model.Initialized()) {
        std::cerr << "Failed to initialize." << std::endl;
        return;
    }

    auto im = cv::imread(image_file);
    int img_h = im.rows;
    int img_w = im.cols;
    fastdeploy::vision::DetectionResult res;
    if (!model.Predict(im, &res)) {
        std::cerr << "Failed to predict." << std::endl;
        return;
    }

    std::cout << res.Str() << std::endl;
    for (int i = 0; i < res.masks.size(); ++i) {
        const auto& mask = res.masks[i];
        cv::Mat mask_big = cv::Mat(img_h, img_w, CV_32S);
        if (i==0){
        std::cout << "mask.data.data()====>"<<  mask.data.data() << std::endl;
        }

        std::memcpy(mask_big.data, mask.data.data(), mask.data.size() * sizeof(int));

        std::string filename1 = image_file + "mask_" + std::to_string(i + 1) + ".jpg";
        // 保存当前轮廓图像
        cv::imwrite(filename1, mask_big);

        std::vector<std::vector<cv::Point>> contours;
        cv::Mat hierarchy;
        // 将掩码矩阵的数据类型从32位整数转换为8位无符号整数。这通常是为了后续的处理和显示需要。
        mask_big.convertTo(mask_big, CV_8U);
        cv::findContours(mask_big, contours, hierarchy, cv::RETR_CCOMP, cv::CHAIN_APPROX_SIMPLE);
        // Print contour coordinates
        if (i == 0) {
            std::cout << "Contour coordinates id is " << i << std::endl;
            std::cout << "Contours.size(): " << contours.size() << std::endl;
            std::cout << "Contours.data(): " << contours.data() << std::endl;;
        }

        for (const auto& contour : contours) {

            cv::Mat result(img_h, img_w, CV_8UC3, cv::Scalar(0, 0, 0));
            // 绘制轮廓
            cv::drawContours(result, contours, -1, cv::Scalar(255, 255, 255));
            // 生成文件名
            std::string filename = image_file + "contour_" + std::to_string(i + 1) + ".jpg";

            // 保存当前轮廓图像
            cv::imwrite(filename, result);

            for (const auto& point : contour) {
                if (i == 0) {
                    std::cout << "point===>" << point << std::endl;
                    std::cout << "(" << point.x << ", " << point.y << ") " << std::endl;
                }

            }
        }
    }
    auto vis_im = fastdeploy::vision::VisDetection(im, res, 0.5);
    cv::imwrite("vis_result.jpg", vis_im);
    std::cout << "Visualized result saved in ./vis_result.jpg" << std::endl;

}

我查看了官当文档，没看懂mask.data()和mask.data.data()分别是指什么？
struct FASTDEPLOY_DECL Mask : public BaseResult {
  /// Mask data buffer
  std::vector<uint8_t> data;
  /// Shape of mask
  std::vector<int64_t> shape;  // (H,W) ...
  ResultType type = ResultType::MASK;

  /// clear Mask result
  void Clear();

  /// Clear Mask result and free the memory
  void Free();

  /// Return a mutable pointer of the mask data buffer
  void* Data() { return data.data(); }

  /// Return a pointer of the mask data buffer for read only
  const void* Data() const { return data.data(); }

  /// Reserve size for mask data buffer
  void Reserve(int size);

  /// Resize the mask data buffer
  void Resize(int size);

  /// Debug function, convert the result to string to print
  std::string Str();
};

**Comment by qianbin1989228** [comment]
debug进去发现mask算是0  说明值没有传出来

**Comment by zhouweic36** [comment]
我用pplite seg  也同样想得到 区域与区域坐标，没有看懂 NPU端推理得到的结构 体
