### ISSUE TITLE
Docker容器内不能联网

### ISSUE THREAD

**Issue by loneclown** [PaddlePaddle/FastDeploy#1975]
#镜像名称 
registry.baidubce.com/paddlepaddle/fastdeploy:1.0.4-gpu-cuda11.4-trt8.5-21.10
# 运行容器命令
docker run -it --gpus all --ipc=host --name fd_serving -v `pwd`/:/FastDeploy registry.baidubce.com/paddlepaddle/fastdeploy:1.0.4-gpu-cuda11.4-trt8.5-21.10  bash

--------------------------------------------------------------------------------------------------
root@dcc9bc64f269:/# visualdl --version
VisualDL 2.4.2
--------------------------------------------------------------------------------------------------
【github文档】本文假定用户已经启动了fastdeploy的镜像，环境中拥有了fastdeployserver命令，并且安装了**visualdl>=2.5.0**，以便能够正常使用VisualDL进行serving可视化部署。
--------------------------------------------------------------------------------------------------

安装visualdl>=2.5.0时候发现apt-get不能使用网络。

报错：
root@dcc9bc64f269:/# apt-get update
Err:1 http://archive.ubuntu.com/ubuntu focal InRelease
  Could not connect to 172.19.56.199:3128 (172.19.56.199), connection timed out
Err:2 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64  InRelease
  Could not connect to 172.19.56.199:3128 (172.19.56.199), connection timed out
Err:3 http://archive.ubuntu.com/ubuntu focal-updates InRelease
  Unable to connect to 172.19.56.199:3128:
Err:4 http://archive.ubuntu.com/ubuntu focal-backports InRelease
  Unable to connect to 172.19.56.199:3128:
Err:5 http://security.ubuntu.com/ubuntu focal-security InRelease
  Could not connect to 172.19.56.199:3128 (172.19.56.199), connection timed out
Reading package lists... Done
W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/focal/InRelease  Could not connect to 172.19.56.199:3128 (172.19.56.199), connection timed out
W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/focal-updates/InRelease  Unable to connect to 172.19.56.199:3128:
W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/focal-backports/InRelease  Unable to connect to 172.19.56.199:3128:
W: Failed to fetch http://security.ubuntu.com/ubuntu/dists/focal-security/InRelease  Could not connect to 172.19.56.199:3128 (172.19.56.199), connection timed out
W: Failed to fetch https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64/InRelease  Could not connect to 172.19.56.199:3128 (172.19.56.199), connection timed out
W: Some index files failed to download. They have been ignored, or old ones used instead.
----------------------------------------------------------------------------------------------------------------------------------------------

报错：
root@dcc9bc64f269:/# python3 -m pip install visualdl==2.5.2
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f5b6529ec40>, 'Connection to 172.19.56.199 timed out. (connect timeout=15)')': /simple/visualdl/
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f5b6529edc0>, 'Connection to 172.19.56.199 timed out. (connect timeout=15)')': /simple/visualdl/
WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f5b6529ee80>, 'Connection to 172.19.56.199 timed out. (connect timeout=15)')': /simple/visualdl/
WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f5b6529ee50>, 'Connection to 172.19.56.199 timed out. (connect timeout=15)')': /simple/visualdl/
WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f5b652c6040>, 'Connection to 172.19.56.199 timed out. (connect timeout=15)')': /simple/visualdl/
ERROR: Could not find a version that satisfies the requirement visualdl==2.5.2 (from versions: none)
ERROR: No matching distribution found for visualdl==2.5.2
------------------------------------------------------------------------------------------------------------------------------------------------

在使用nvidia triton镜像时可以直接进行联网操作

**Comment by fuloong** [comment]
fastdeploy的docker镜像设置了http_proxy和https_proxy环境变量，需要在 docker容器内 将这两个变量置空才能访问外网

``` bash
 unset http_proxy
 unset https_proxy
```
