### ISSUE TITLE
C#部署fastdeploy所需的动态库问题

### ISSUE THREAD

**Issue by sanyangAZ** [PaddlePaddle/FastDeploy#1979]
cudn11.2,cudnn8.4,windows10, c++,cmake gui 编译，编译后vs2019生成fastdeploy csharp.dll和fastdeploy.dll，调用时提示无法加载  #DLL“fastdeploy.dll”，此动态库依赖项很多，应该怎么把其所需的子项一并生成输出到指定目录，其一共有多少动态库。目前使用Paddle Inference和TensorRT两种
![无标题](https://github.com/PaddlePaddle/FastDeploy/assets/126551342/8fe9840c-a772-4530-b959-5845e9c675b7)

**Comment by DefTruth** [comment]
参考这个文档：  
- https://github.com/PaddlePaddle/FastDeploy/blob/develop/docs/cn/faq/usage_of_fastdeploy_init_bat.md

**Comment by guoyunqingyue** [comment]
请问解决无法加载 #DLL“fastdeploy.dll”的问题了吗

**Comment by guoyunqingyue** [comment]
> 参考这个文档：
> 
>     * https://github.com/PaddlePaddle/FastDeploy/blob/develop/docs/cn/faq/usage_of_fastdeploy_init_bat.md

请问c#版本的TensorRT如何使用？例程中只有使用CPU和GPU的版本，c#接口中没有给TenorRT添加shape的代码
