### ISSUE TITLE
API调用运行崩溃

### ISSUE THREAD

**Issue by fenxiangwpp** [PaddlePaddle/FastDeploy#1985]
## 环境

- 【FastDeploy版本】：fastdeploy-win-x64-1.0.6
- 【编译命令】通过两种方式：1）下载编译好的fastdeploy-win-x64-1.0.6的包；2）下载源码，用VS2019编译不包含GPU、TensorRT的fastdeploy版本
- 【系统平台】: Windows x64(Windows11) 
- 【编译语言】： C++(VS2019)

测试fastdeploy C++ API的调用正确性
只包含一行代码：
#include "fastdeploy/runtime.h"
namespace fd = fastdeploy;

int main()
{
     //setup option
    fd::RuntimeOption runtime_option;
   
    return 0；
}
- 【运行崩溃】
- - 编译没有问题，运行时出错，错误信息：
- 0x00007FFD266F40AC 处引发的异常: Microsoft C++ 异常: InferenceEngine::GeneralError，位于内存位置 0x0000004B21AFE710 处。
0x00007FFD266F40AC 处引发的异常: Microsoft C++ 异常: ov::Exception，位于内存位置 0x0000004B21AFEC50 处。
0x00007FFD266F40AC 处有未经处理的异常: Microsoft C++ 异常: ov::Exception，位于内存位置 0x0000004B21AFEC50 处。

**Comment by WilliamQf-AI** [comment]
可能是执行目录下缺少dll，还有plugins.xml文件

**Comment by DefTruth** [comment]
参考这个文档：

https://github.com/PaddlePaddle/FastDeploy/blob/develop/docs/cn/faq/usage_of_fastdeploy_init_bat.md

**Comment by allanpk716** [comment]
遇到的问题类似，第一次用示例代码编译是通过，且运行通过，支持库是用 fastdeploy_init_bat install 过去的。然后只要修改示例代码，哪怕是加一个打印输出，编译通过后，再次运行就崩溃。程序是连 main 都没进去就挂了。然后，如果删除所有的支持库，不用编译程序，再次用 fastdeploy_init_bat install 过去的就好了···所以怎么定位问题？

用的是 VS2019 编译的示例。

**Comment by allanpk716** [comment]
> 遇到的问题类似，第一次用示例代码编译是通过，且运行通过，支持库是用 fastdeploy_init_bat install 过去的。然后只要修改示例代码，哪怕是加一个打印输出，编译通过后，再次运行就崩溃。程序是连 main 都没进去就挂了。然后，如果删除所有的支持库，不用编译程序，再次用 fastdeploy_init_bat install 过去的就好了···所以怎么定位问题？
> 
> 用的是 VS2019 编译的示例。

找到问题了，重新生成程序的时候，plugins.xml 被清理了···
