### ISSUE TITLE
ocr的demo编译后代码报错

### ISSUE THREAD

**Issue by kc-w** [PaddlePaddle/FastDeploy#199]
![image](https://user-images.githubusercontent.com/39193398/188798450-8a382d68-459d-40ab-8164-1098a86636c3.png)
ocr的PPOCRSystemv3编译完成后打开出现上述错误,其他demo比如classification可以正常Release生成infer_demo.exe,是否完成ocr的支持?

**Comment by jiangjiajun** [comment]
你好，能截一下全部的错误信息吗，是出现"Failed to initalize det_model"这行日志吗？

也可同时加入微信群，更快实时与工程师交流
 <img src=https://user-images.githubusercontent.com/19339784/188805172-0ce483a6-08aa-460d-b5f5-7ad82ebaa401.png width = "300" height = "400" alt="图片名称" align=center />

**Comment by kc-w** [comment]
编译完成后,打开文件代码下标变红

**Comment by kc-w** [comment]
严重性	代码	说明	项目	文件	行	禁止显示状态
错误	C2039	"ocr": 不是 "fastdeploy::vision" 的成员	infer_demo	E:\projectTest\FastDeploy-develop\examples\vision\ocr\PPOCRSystemv3\cpp\infer.cc	37

**Comment by jiangjiajun** [comment]
这个的原因是OCR没在0.2的版本里面支持，你方便参考这个文档自行编译一个最新的fastdeploy吗

https://github.com/PaddlePaddle/FastDeploy/blob/develop/docs/compile/how_to_build_windows.md

**Comment by kc-w** [comment]
谢谢,成功完成编译
