### ISSUE TITLE
和paddlex有什么区别？

### ISSUE THREAD

**Issue by gxwyxajh88** [PaddlePaddle/FastDeploy#2]
大概看了一下，功能各方面好像和paddlex有很多重复，而且貌似paddle系列的很多东西都有类似重复的东西

**Comment by jiangjiajun** [comment]
HI, @gxwyxajh88  你肯定是飞桨的老用户了！

PaddleX是一款快速低门槛的训练+部署工具。 当初在开发时，基于PaddleDetection，PaddleSeg和PaddleClas封装了上层的训练接口，同时针对PaddleX的训练产出模型，提供了部署的代码封装，此后也再拓展支持了PaddleDetection、PaddleSeg和PaddleClas的模型部署。但整体而言，PaddleX定位还是CV传统几大任务的的训练+部署。 

FastDeploy则是专门推出的一款部署套件，除了CV几大任务，同时还会支持NLP、语音等多种领域的模型部署。 在部署能力上后面会融合PaddleX已有的一些设计，让大家更快，更方便把模型部署起来！

FastDeploy刚开源，相信会有很多可优化迭代的地方，可以加我们微信群进行交流 :)

**Comment by wanghaisheng** [comment]
请保持这个响应速度

**Comment by ZeyuChen** [comment]
@wanghaisheng 没问题，欢迎多多issues反馈需求与问题讨论！

**Comment by Pointvar** [comment]
刷OKR的产物， paddlerocr 本身不好好维护。同一件事情，周边搞一堆。实际上没什么用。部署优化来 优化去 有什么用呢。就算本身部署很麻烦。现在都是容器和镜像迁移。 不去支持python3.11 3.12 去弄一堆部署～
