### ISSUE TITLE
FastDeploy和python ocr PPocr3推理结果不一致

### ISSUE THREAD

**Issue by Edwina414** [PaddlePaddle/FastDeploy#2012]
自己构建的测试集，分别用python和fastdploy推理结果不一致，要修改fastdploy的推理求请教

**Comment by dizhenx** [comment]
> 自己构建的测试集，分别用python和fastdploy推理结果不一致，要修改fastdploy的推理求请教

是不是fastdploy使用的模型版本跟python ocr PPocr3不一样？fastdeploy是不是效果比那个差一些，最后怎么解决的？

**Comment by gl94** [comment]
用官方的模型推理结果也不一致
