### ISSUE TITLE
不改变代码的情况下直接输入yolov5s6模型是否支持？

### ISSUE THREAD

**Issue by jia0511** [PaddlePaddle/FastDeploy#2021]
我 如果直接使用1280分辨率训练的yolov5s6模型，前处理还是用编译好的库，看起来可以直接运行，推理时间也有所增加，但是前处理代码没做任何修改，默认yolov5原始代码使用32倍下采样，不是64倍，这样会对精度产生一定影响？但是我比较下来比640分辨率结果有所提升，如果修改前处理代码中32倍下采样，和init中分辨率默认值，是否还有所提升？或者直接问支持1280分辨率下yolov5s6推理吗？

**Comment by jiangjiajun** [comment]
可以直接，我不确认你这里用的是C++还是Python， 你可以看下FastDeploy里面相应的YOLOv5或者YOLOv6的类，它提供了相应的函数，支持修改输入的分辨率

**Comment by jia0511** [comment]
目前看下来没法直接改，我用的C++

**Comment by jiangjiajun** [comment]
YOLOv5有如下成员函数，可以获取预处理成员类
https://github.com/PaddlePaddle/FastDeploy/blob/7b58387d3c9a5bcdfd325997350689051141c43e/fastdeploy/vision/detection/contrib/yolov5/yolov5.h#L71-L73

而该成员类，有相应成员函数修改输入图像大小，默认640
https://github.com/PaddlePaddle/FastDeploy/blob/7b58387d3c9a5bcdfd325997350689051141c43e/fastdeploy/vision/detection/contrib/yolov5/preprocessor.h#L41-L43

**Comment by jia0511** [comment]
只要改分辨率？stride要不要改？后处理改不改？

**Comment by jiangjiajun** [comment]
其它根据训练时的配置相应修改，如果训练时没改，就不改

**Comment by jia0511** [comment]
网络没有做任何修改的情况下，只改size和stride就够了吧？目前测试下来精度已经有所提升

**Comment by jia0511** [comment]
认为部分回答了问题
