### ISSUE TITLE
  fd_serving 启动服务后，为什么CPU会有占用？是哪里来的占用？

### ISSUE THREAD

**Issue by teymur-git** [PaddlePaddle/FastDeploy#2028]
*********************************************
温馨提示：根据社区不完全统计，按照模板提问，可以加快回复和解决问题的速度
*********************************************

## 环境

- 【FastDeploy版本】：fastdeploy:1.0.2-gpu-cuda11.4-trt8.4-21.10   官方镜像
- 【系统平台】: linux Ubuntu 18.04
- 【硬件】： 说明具体硬件型号，如 Nvidia GPU 1060I， CUDA 11.4

启动服务后，CPU持续占用8%。
就是不明白，还没开始预测为什么会持续占用

**Comment by teymur-git** [comment]
@jiangjiajun

**Comment by teymur-git** [comment]
root@PC-202302261439:/# CUDA_VISIBLE_DEVICES=0 fastdeployserver --model-repository=/ai/models --backend-config=python,shm-default-byte-size=10485760  --http-port=8000 --grpc-port=8001  --metrics-port=8002
I0613 02:50:41.660391 124 metrics.cc:298] Collecting metrics for GPU 0: NVIDIA GeForce GTX 1060 6GB
W0613 02:50:41.660838 124 metrics.cc:370] Cannot start watching fields: NVML error
I0613 02:50:41.828435 124 pinned_memory_manager.cc:240] Pinned memory pool is created at '0x3037f0000' with size 268435456
I0613 02:50:41.828484 124 cuda_memory_manager.cc:105] CUDA memory pool is created on device 0 with size 67108864
I0613 02:50:41.990690 124 model_repository_manager.cc:1022] loading: preprocess:1
I0613 02:50:42.095996 124 python.cc:1875] TRITONBACKEND_ModelInstanceInitialize: preprocess_0 (CPU device 0)
I0613 02:50:42.097038 124 model_repository_manager.cc:1022] loading: postprocess:1
I0613 02:50:42.208290 124 model_repository_manager.cc:1022] loading: runtime:1
model_config: {'name': 'preprocess', 'platform': '', 'backend': 'python', 'version_policy': {'latest': {'num_versions': 1}}, 'max_batch_size': 0, 'input': [{'name': 'preprocess_input', 'data_type': 'TYPE_UINT8', 'format': 'FORMAT_NONE', 'dims': [-1, -1, -1, 3], 'is_shape_tensor': False, 'allow_ragged_batch': False}], 'output': [{'name': 'preprocess_output_1', 'data_type': 'TYPE_FP32', 'dims': [-1, 3, -1, -1], 'label_filename': '', 'is_shape_tensor': False}, {'name': 'preprocess_output_2', 'data_type': 'TYPE_STRING', 'dims': [-1], 'label_filename': '', 'is_shape_tensor': False}], 'batch_input': [], 'batch_output': [], 'optimization': {'priority': 'PRIORITY_DEFAULT', 'input_pinned_memory': {'enable': True}, 'output_pinned_memory': {'enable': True}, 'gather_kernel_buffer_threshold': 0, 'eager_batching': False}, 'instance_group': [{'name': 'preprocess_0', 'kind': 'KIND_CPU', 'count': 1, 'gpus': [], 'secondary_devices': [], 'profile': [], 'passive': False, 'host_policy': ''}], 'default_model_filename': '', 'cc_model_filenames': {}, 'metric_tags': {}, 'parameters': {}, 'model_warmup': []}
preprocess input names: ['preprocess_input']
preprocess output names: ['preprocess_output_1', 'preprocess_output_2']
[INFO] fastdeploy/vision/common/processors/transform.cc(93)::FuseNormalizeHWC2CHW       Normalize and HWC2CHW are fused to NormalizeAndPermute  in preprocessing pipeline.
[INFO] fastdeploy/vision/common/processors/transform.cc(159)::FuseNormalizeColorConvert BGR2RGB and NormalizeAndPermute are fused to NormalizeAndPermute with swap_rb=1
I0613 02:50:42.453052 124 model_repository_manager.cc:1183] successfully loaded 'preprocess' version 1
I0613 02:50:42.606481 124 fastdeploy_runtime.cc:1173] TRITONBACKEND_Initialize: fastdeploy
I0613 02:50:42.606511 124 fastdeploy_runtime.cc:1182] Triton TRITONBACKEND API version: 1.6
I0613 02:50:42.606528 124 fastdeploy_runtime.cc:1187] 'fastdeploy' TRITONBACKEND API version: 1.6
I0613 02:50:42.606532 124 fastdeploy_runtime.cc:1216] backend configuration:
{}
I0613 02:50:42.606560 124 python.cc:1875] TRITONBACKEND_ModelInstanceInitialize: postprocess_0 (CPU device 0)
model_config: {'name': 'postprocess', 'platform': '', 'backend': 'python', 'version_policy': {'latest': {'num_versions': 1}}, 'max_batch_size': 0, 'input': [{'name': 'post_input_1', 'data_type': 'TYPE_INT32', 'format': 'FORMAT_NONE', 'dims': [-1, -1, -1], 'is_shape_tensor': False, 'allow_ragged_batch': False}, {'name': 'post_input_2', 'data_type': 'TYPE_STRING', 'format': 'FORMAT_NONE', 'dims': [-1], 'is_shape_tensor': False, 'allow_ragged_batch': False}], 'output': [{'name': 'post_output', 'data_type': 'TYPE_STRING', 'dims': [-1], 'label_filename': '', 'is_shape_tensor': False}], 'batch_input': [], 'batch_output': [], 'optimization': {'priority': 'PRIORITY_DEFAULT', 'input_pinned_memory': {'enable': True}, 'output_pinned_memory': {'enable': True}, 'gather_kernel_buffer_threshold': 0, 'eager_batching': False}, 'instance_group': [{'name': 'postprocess_0', 'kind': 'KIND_CPU', 'count': 1, 'gpus': [], 'secondary_devices': [], 'profile': [], 'passive': False, 'host_policy': ''}], 'default_model_filename': '', 'cc_model_filenames': {}, 'metric_tags': {}, 'parameters': {}, 'model_warmup': []}
postprocess input names: ['post_input_1', 'post_input_2']
postprocess output names: ['post_output']
I0613 02:50:42.948547 124 fastdeploy_runtime.cc:1246] TRITONBACKEND_ModelInitialize: runtime (version 1)
I0613 02:50:42.948713 124 model_repository_manager.cc:1183] successfully loaded 'postprocess' version 1
I0613 02:50:42.951027 124 fastdeploy_runtime.cc:1285] TRITONBACKEND_ModelInstanceInitialize: runtime_0 (GPU device 0)
[WARN][Paddle2ONNX] [pool2d: pool2d_4.tmp_0] Pool2d is exported as custom operator: AdaptivePool2d
[WARN][Paddle2ONNX] [pool2d: pool2d_5.tmp_0] Pool2d is exported as custom operator: AdaptivePool2d
[INFO] fastdeploy/backends/tensorrt/trt_backend.cc(514)::BuildTrtEngine Start to building TensorRT Engine...
[INFO] fastdeploy/backends/tensorrt/trt_backend.cc(600)::BuildTrtEngine TensorRT Engine is built successfully.
[INFO] fastdeploy/runtime.cc(625)::Init Runtime initialized with Backend::TRT in Device::GPU.
I0613 02:51:12.795684 124 model_repository_manager.cc:1183] successfully loaded 'runtime' version 1
I0613 02:51:12.802090 124 model_repository_manager.cc:1022] loading: paddleseg:1
I0613 02:51:12.902375 124 model_repository_manager.cc:1183] successfully loaded 'paddleseg' version 1
I0613 02:51:12.902468 124 server.cc:522]
+------------------+------+
| Repository Agent | Path |
+------------------+------+
+------------------+------+

I0613 02:51:12.902508 124 server.cc:549]
+------------+----------------------------------------------------+--------------------------------------------------+
| Backend    | Path                                               | Config                                           |
+------------+----------------------------------------------------+--------------------------------------------------+
| python     | /opt/tritonserver/backends/python/libtriton_python | {"cmdline":{"shm-default-byte-size":"10485760"}} |
|            | .so                                                |                                                  |
| fastdeploy | /opt/tritonserver/backends/fastdeploy/libtriton_fa | {}                                               |
|            | stdeploy.so                                        |                                                  |
+------------+----------------------------------------------------+--------------------------------------------------+

I0613 02:51:12.902544 124 server.cc:592]
+-------------+---------+--------+
| Model       | Version | Status |
+-------------+---------+--------+
| paddleseg   | 1       | READY  |
| postprocess | 1       | READY  |
| preprocess  | 1       | READY  |
| runtime     | 1       | READY  |
+-------------+---------+--------+

I0613 02:51:12.902635 124 tritonserver.cc:1920]
+----------------------------------+----------------------------------------------------------------------------------+
| Option                           | Value                                                                            |
+----------------------------------+----------------------------------------------------------------------------------+
| server_id                        | triton                                                                           |
| server_version                   | 2.15.0                                                                           |
| server_extensions                | classification sequence model_repository model_repository(unload_dependents) sch |
|                                  | edule_policy model_configuration system_shared_memory cuda_shared_memory binary_ |
|                                  | tensor_data statistics                                                           |
| model_repository_path[0]         | /ai/models                                                                       |
| model_control_mode               | MODE_NONE                                                                        |
| strict_model_config              | 1                                                                                |
| rate_limit                       | OFF                                                                              |
| pinned_memory_pool_byte_size     | 268435456                                                                        |
| cuda_memory_pool_byte_size{0}    | 67108864                                                                         |
| response_cache_byte_size         | 0                                                                                |
| min_supported_compute_capability | 6.0                                                                              |
| strict_readiness                 | 1                                                                                |
| exit_timeout                     | 30                                                                               |
+----------------------------------+----------------------------------------------------------------------------------+

I0613 02:51:12.903743 124 grpc_server.cc:4117] Started GRPCInferenceService at 0.0.0.0:8001
I0613 02:51:12.903915 124 http_server.cc:2815] Started HTTPService at 0.0.0.0:8000
I0613 02:51:12.945145 124 http_server.cc:167] Started Metrics Service at 0.0.0.0:8002

**Comment by fuloong** [comment]
这是由于镜像中包含的triton旧版本21.10中的bug,需要升级triton版本到22新版本才能解决  #1521

**Comment by teymur-git** [comment]
@fuloong 
![image](https://github.com/PaddlePaddle/FastDeploy/assets/60127735/c5a4bd0e-5b92-45e7-ab61-d0f955d023a8)

**Comment by teymur-git** [comment]
> 这是由于镜像中包含的triton旧版本21.10中的bug,需要升级triton版本到22新版本才能解决 #1521
@fuloong 请问下如果要升级到22新版本需要自行编译镜像？

**Comment by fuloong** [comment]
GPU的可以拉这个镜像

docker pull paddlepaddle/fastdeploy:1.0.7-gpu-cuda11.6-trt8.5-22.12

CPU的暂时没找到官方镜像，只能自己编

**Comment by teymur-git** [comment]
@fuloong 这个镜像启动会报错？缺库？
![image](https://github.com/PaddlePaddle/FastDeploy/assets/60127735/8b785df4-e141-4b31-939a-06948c144c7b)

**Comment by teymur-git** [comment]
> @fuloong 这个镜像启动会报错？缺库？ ![image](https://user-images.githubusercontent.com/60127735/249044601-8b785df4-e141-4b31-939a-06948c144c7b.png)

![image](https://github.com/PaddlePaddle/FastDeploy/assets/60127735/77239f2a-1e46-4acd-9258-66eb3ae79d06)
镜像只存在libdcgm.so.3库，没有libdcgm.so.2

**Comment by fuloong** [comment]
这个有镜像是有点问题，需要改一些东西，我是在这个镜像上基础上制作的新的镜像用的，主要省去编译的麻烦，这个报错是需要降级到 datacenter-gpu-manager=1:2.2.9  这个版本，你可以参照官方的dockerfile内容制作可用的镜像

你也可以试试最新的镜像，这个是没有TensortRT 需要自己装
docker pull paddlepaddle/fastdeploy:1.0.7-gpu-cuda11.6-23.04

**Comment by polarisunny** [comment]
CPU版本的基于Fastdeploy:1.0.7-cpu-only 自己编译个 22.12版本的server，CPU占用正常了

**Comment by teymur-git** [comment]
> CPU版本的基于Fastdeploy:1.0.7-cpu-only 自己编译个 22.12版本的server，CPU占用正常了

@faquir-sun .如何自己编译的的triton 22.12版本，分享一下参考文档

**Comment by polarisunny** [comment]
我用的方法比较笨，参考官方https://github.com/PaddlePaddle/FastDeploy/blob/develop/serving/docs/zh_CN/compile_without_docker_centos.md
在ubuntu 20.04 上进行CPU版本编译，GCC 使用 apt install gcc 默认安装的9.4.0版本，其他依赖库安装对应的ubuntu版本，然后把编译后的文件拷贝到 21.10-cpu-only 的镜像里。然后再导出镜像。
<img width="541" alt="image" src="https://github.com/PaddlePaddle/FastDeploy/assets/16932704/5f325c85-bfa4-44a6-9fba-38329b57d616">
