### ISSUE TITLE
How to run ocr detection or recognition on AWS Lambda?

### ISSUE THREAD

**Issue by pepperav** [PaddlePaddle/FastDeploy#2029]
👋 Hello there,
I found this amazing ml work done by you and it seems incredible!! 🎊

I'm going to experiment it on a full backend service, like a AWS Lambda. Is it possible?

Starting a basic Node JS app, I get some **webgl errors**.

`
Loading ocr_detect model...
[conv2d]: TypeError: Cannot read property 'frameBufferSupportFloat' of undefined
webgl createProgram: conv2d -- Error: TypeError: Cannot read property 'FRAGMENT_SHADER' of null
[batchnorm]: TypeError: Cannot read property 'frameBufferSupportFloat' of undefined
webgl createProgram: batchnorm -- Error: TypeError: Cannot read property 'FRAGMENT_SHADER' of null
[hard_swish]: TypeError: Cannot read property 'frameBufferSupportFloat' of undefined
webgl createProgram: hard_swish -- Error: TypeError: Cannot read property 'FRAGMENT_SHADER' of null
[conv2d]: TypeError: Cannot read property 'frameBufferSupportFloat' of undefined
webgl createProgram: conv2d -- Error: TypeError: Cannot read property 'FRAGMENT_SHADER' of null
[batchnorm]: TypeError: Cannot read property 'frameBufferSupportFloat' of undefined
webgl createProgram: batchnorm -- Error: TypeError: Cannot read property 'FRAGMENT_SHADER' of null
[conv2d_depthwise]: TypeError: Cannot read property 'frameBufferSupportFloat' of undefined
webgl createProgram: conv2d_depthwise -- Error: TypeError: Cannot read property 'FRAGMENT_SHADER' of null
`

Here my files:

**index.ts**
`

              import '@paddlejs/paddlejs-backend-webgl';

              const { Canvas, createCanvas, loadImage, Image2, ImageData2 } = require('canvas');
              const { JSDOM } = require('jsdom');

              
              const installDOM = (): void => {
                  const dom = new JSDOM();
                  global.document = dom.window.document;
              
                  // The rest enables DOM image and canvas and is provided by node-canvas
                  global.Image = Image2;
                  global.HTMLCanvasElement = Canvas;
                  global.ImageData = ImageData2;
                  global.HTMLImageElement = Image;
                  global.Headers = dom.window.Headers;
                  global.window = dom.window;
              
                  global.window.fetch = require('node-fetch')
              };

              (async () => {
                  installDOM();
              
                  const ocr = require('@paddlejs-models/ocrdet');
                  
                  console.log("Loading Model...");
                  await ocr.load();
                  console.log("Model loaded.");
              })();
`

**package.json**
`

              {
                "name": "ocrdet",
                "version": "1.0.0",
                "description": "",
                "main": "index.js",
                "scripts": {
                  "test": "echo \"Error: no test specified\" && exit 1",
                  "dev": "tsc && node dist/index.js"
                },
                "keywords": [],
                "author": "",
                "license": "ISC",
                "dependencies": {
                  "@paddlejs-models/ocrdet": "^1.1.1",
                  "@paddlejs/paddlejs-backend-webgl": "^1.2.9",
                  "@paddlejs/paddlejs-core": "^2.2.0",
                  "@types/node": "^20.3.1",
                  "canvas": "^2.11.0",
                  "jsdom": "^21.1.0",
                  "typescript": "^4.3.5"
                },
                "devDependencies": {}
              }

`

Any idea how to solve it?

Thank you in advance 🙏

**Comment by chenqianhe** [comment]
To be honest, Paddle.js is designed to serve AI model inference on the front-end browser environment, so it has not been tested for running in a Node.js environment (I assume you understand the difference I'm trying to express here, even though both involve JavaScript), especially with the WebGL inference method you mentioned. 

Personally, to implement model inference in a Node.js environment, I have used an addon solution for the underlying model logic, with the inference part implemented in C++ (regardless of GPU usage). JavaScript is only responsible for the higher-level invocation. This approach is generally more efficient.

Regarding your specific issue, I believe the errors you encountered in the initialization or settings related to WebGL are likely due to the differences in the environment. It may involve discrepancies between the DOM and WebGL in different environments.
