### ISSUE TITLE
The FastDeploy didn't compile with GPU, will force to use CPU.

### ISSUE THREAD

**Issue by NicoSaronAI** [PaddlePaddle/FastDeploy#203]
[WARNING] csrc/fastdeploy/fastdeploy_runtime.cc(141)::fastdeploy::RuntimeOption::UseGpu The FastDeploy didn't compile with GPU, will force to use CPU.

**Comment by jiangjiajun** [comment]
Please download GPU wheel/library if you need to deploy your model on GPU, refer this document for more details https://github.com/PaddlePaddle/FastDeploy/tree/develop/docs/quick_start

**Comment by jiangjiajun** [comment]
此ISSUE由于一年未更新，将会关闭处理，如有需要，可再次更新打开。
