### ISSUE TITLE
使用example中的 rkyolo/cpp  在瑞星微板端编译、推理，Score远大于1 

### ISSUE THREAD

**Issue by cafreyyao** [PaddlePaddle/FastDeploy#2036]
*********************************************
温馨提示：根据社区不完全统计，按照模板提问，可以加快回复和解决问题的速度
*********************************************
## 环境
- 【FastDeploy版本】： git clone https://github.com/PaddlePaddle/FastDeploy.git 最新代码
- 【编译命令】板端编译FastDeploy C++ SDK
- git clone https://github.com/PaddlePaddle/FastDeploy.git
cd FastDeploy
git checkout develop
mkdir build && cd build
cmake ..  -DENABLE_ORT_BACKEND=OFF \
	      -DENABLE_RKNPU2_BACKEND=ON \
	      -DENABLE_VISION=ON \
	      -DRKNN2_TARGET_SOC=RK3588 \
          -DCMAKE_INSTALL_PREFIX=${PWD}/fastdeploy-0.0.3
make -j8
make install
cd  ../examples/vision/detection/rkyolo/cpp
mkdir build
mkdir images
mkdir model
mkdir thirdpartys
copy fastdeploy-0.0.3 至  thirdpartys
cd build
cmake  ..
make -j8 
make  install
cd install
source ../../thirdpartys/fastdeploy-0.0.3
./infer_rkyolov5  model/0616.rknn  images/bus.jpg
- 
- 【系统平台】: Linux x64(Ubuntu 22.04) 
- 【硬件】： Rockchip  rk3588  debian 11
- 【编译语言】： C++
## 问题日志及出现问题的操作流程
- 附上详细的问题日志有助于快速定位分析
- 【模型精度问题】
`examples`下的rkyolo/cpp 可以正确执行   使用自己的onnx转rknn模型  score远大于1
rknn模型使用 瑞芯微 官方的  rknpu2 在 设备端可以正常推理识别

**rkyolo 推理日志如下：
linaro@linaro-alip:~/rknn/FastDeploy/examples/vision/detection/rkyolo/cpp/build/install$ ./infer_rkyolov5 model/0616.rknn images/bus.jpg 
[INFO] fastdeploy/runtime/backends/rknpu2/rknpu2_backend.cc(81)::GetSDKAndDeviceVersion	rknpu2 runtime version: 1.4.2b0 (c5d79ccf9@2023-02-14T17:55:39)
[INFO] fastdeploy/runtime/backends/rknpu2/rknpu2_backend.cc(82)::GetSDKAndDeviceVersion	rknpu2 driver version: 0.8.2
index=0, name=images, n_dims=4, dims=[1, 640, 640, 3], n_elems=1228800, size=1228800, fmt=NHWC, type=INT8, qnt_type=AFFINE, zp=-128, scale=0.003922, pass_through=0
index=0, name=output, n_dims=4, dims=[1, 24, 80, 80], n_elems=153600, size=153600, fmt=NCHW, type=FP32, qnt_type=AFFINE, zp=63, scale=0.131856, pass_through=0
index=1, name=273, n_dims=4, dims=[1, 24, 40, 40], n_elems=38400, size=38400, fmt=NCHW, type=FP32, qnt_type=AFFINE, zp=58, scale=0.130438, pass_through=0
index=2, name=274, n_dims=4, dims=[1, 24, 20, 20], n_elems=9600, size=9600, fmt=NCHW, type=FP32, qnt_type=AFFINE, zp=12, scale=0.163191, pass_through=0
[INFO] fastdeploy/runtime/runtime.cc(341)::CreateRKNPU2Backend	Runtime initialized with Backend::RKNPU2 in Device::RKNPU.
[WARNING] fastdeploy/runtime/backends/rknpu2/rknpu2_backend.cc(420)::InitRKNNTensorMemory	The input tensor type != model's inputs type.The input_type need INT8,but inputs[0].type is UINT8
[FastDeploy] RKYOLOV5 in RKNN duration = 0.02885s.
DetectionResult: [xmin, ymin, xmax, ymax, score, label_id]
187.604065,238.120667, 293.092041, 241.183228, 8.677237, 1
233.081009,242.554581, 242.260818, 282.542419, 8.293127, 1
235.190704,214.689728, 244.370514, 254.677551, 7.823704, 1
239.327194,220.970367, 241.368896, 258.333527, 7.809513, 1
193.487061,160.840317, 277.635376, 364.256653, 7.510757, 1
190.156189,41.232483, 290.539917, 438.071411, 7.503257, 1
226.659576,253.160049, 244.462860, 271.936951, 7.371669, 1
228.769272,230.511002, 246.572540, 238.856293, 6.954404, 1
183.430038,311.306580, 288.917999, 311.306580, 6.550463, 1
239.327194,292.625000, 241.368896, 329.988159, 5.614682, 1
164.519394,231.349030, 164.519394, 247.954880, 5.308427, 1
114.327538,93.874374, 214.711243, 385.429504, 5.206342, 1
111.775406,239.651947, 217.263367, 239.651947, 5.206342, 1
9.760071,123.748032, 318.681946, 210.033112, 2.237020, 0
129.534256,263.860962, 167.509918, 266.923523, 2.041703, 0
144.742828,181.828308, 147.037781, 284.197144, 1.999391, 0
100.825768,216.322159, 190.954834, 249.703308, 1.825531, 0
245.297852,256.266144, 273.115479, 264.611420, 1.808145, 1
254.616760,240.444870, 263.796570, 280.432678, 1.808145, 1
0.000000,237.966888, 308.237732, 324.251984, 1.731028, 0
133.708282,208.902451, 171.683960, 211.965012, 1.701419, 0
144.438690,263.316498, 152.605499, 267.467957, 1.684405, 0
148.612717,208.358002, 156.779526, 212.509460, 1.684405, 0
130.453033,119.614670, 166.591171, 411.169800, 1.531277, 0**

**Comment by tongxiaohua** [comment]
碰到同样的问题，请问是否解决了
