### ISSUE TITLE
PaddleOCR not able to recognize a simple preprocessed image. 

### ISSUE THREAD

**Issue by ArivCR7** [PaddlePaddle/FastDeploy#2037]
## Environment

FastDeploy version: latest code in develop branch
OS Platform: e.g. Linux x64
Hardware: e.g. Nvidia GPU 3070Ti  CUDA 11.2 CUDNN 8.3
Program Language: e.g. Python 3.8

## Problem description
I used fast delpoy to deploy the 
![white_on_blkbg](https://github.com/PaddlePaddle/FastDeploy/assets/28477568/672f9a46-af16-480a-832d-30a0ccf8ec9d)
Paddle OCR model on my x86 Linux machine. PaddleOCR works out of the box for the tested label receipts. However, for the attached simple preprocessed image, paddleOCR doesn't work. The OCR result is as below for the attached image: 
det boxes: [[152,174],[376,163],[378,207],[154,218]]rec text: NERPI6IZLIL rec score:0.463849 cls label: 0 cls score: 0.947102

Does paddleOCR has any limitation on the image to be processed? If so, can something be done to this pre-processed image to improve the recognition accuracy?

**Comment by ArivCR7** [comment]
Hi Team, Any clue on this please.

**Comment by jiangjiajun** [comment]
Please submit an issue for consultation under the [PaddleOCR project](https://github.com/PaddlePaddle/PaddleOCR) regarding the effectiveness of the model
