### ISSUE TITLE
编译fastdeploy的C#库,出现报错

### ISSUE THREAD

**Issue by dilsm56-github** [PaddlePaddle/FastDeploy#2039]
【FastDeploy】https://github.com/PaddlePaddle/FastDeploy/tree/develop
【C++ SDK安装 Release版本】 fastdeploy-win-x64-gpu-1.0.7
【系统】:win10
【显卡】:NVIDIA GeForce RTX 3050 Laptop GPU
【CUDA版本】11.2
【CUDNN版本】11.3
【VS版本】:VS2019

【具体报错信息】
----------------------------------------------------------------------------------------------------------------------------------
【严重性	代码	说明	项目	文件	行	禁止显示状态】
错误	CS1617	/langversion 的选项“10”无效。使用 "/langversion:?" 列出支持的值。	fastdeploy_csharp	D:\PaddleX\PaddleDeploy\fastdeploy_develop\build\csharp\CSC	1	活动

【严重性	代码	说明	项目	文件	行	禁止显示状态】
错误	LNK1181	无法打开输入文件“CUDA_LIB-NOTFOUND.lib”	fastdeploy	D:\PaddleX\PaddleDeploy\fastdeploy_develop\build\LINK	1	
---------------------------------------------------------------------------------------------------------------------------------
【参考编译的文档路径：https://github.com/PaddlePaddle/FastDeploy/tree/develop/csharp/】
![f78200381abee5d61a63353d9aa9b59](https://github.com/PaddlePaddle/FastDeploy/assets/134047873/53d32b25-478d-4888-a87c-32afc93def60)
【出错图片】
![8bc8ae099fdc8468cd3800d932c8214](https://github.com/PaddlePaddle/FastDeploy/assets/134047873/31f03895-2e56-4f91-9333-b4b751f950c1)

![0aad6b28fd7304713c680a73e2d61cf](https://github.com/PaddlePaddle/FastDeploy/assets/134047873/2afb3e0d-06a8-45ed-acec-029cc8534ab1)
![688a2afe4245f5cc2e5815c3ea47398](https://github.com/PaddlePaddle/FastDeploy/assets/134047873/ba3baacf-05a9-4d21-aa3e-836eceb97e3e)

**Comment by Duhanfeng** [comment]
需要vs2022

**Comment by guoyunqingyue** [comment]
cmakelist里面有一个“set(CMAKE_CSharp_FLAGS "/langversion:10")”，改成9就行了，改成8及以下会报另一个错

**Comment by pcycccccc** [comment]
我是直接用命令行去编译cmakelist文件，编译的时候需指定cuda的安装路径，不然使用gpu版本的代码会出现报错
