### ISSUE TITLE
ARM 1.0.7版预编译库无法下载

### ISSUE THREAD

**Issue by jia0511** [PaddlePaddle/FastDeploy#2040]
## Environment

FastDeploy version: e.g 0.8.0 or the latest code in develop branch
OS Platform: e.g. Linux x64 / Windows x64 / Mac OSX 12.1(arm or intel)
Hardware: e.g. Nvidia GPU 3080Ti  CUDA 11.2 CUDNN 8.3
Program Language: e.g. Python 3.8

## Problem description
[fastdeploy-linux-aarch64-1.0.7.tgz](https://github.com/PaddlePaddle/FastDeploy/blob/develop/docs/en/build_and_install/download_prebuilt_libraries.md)
{"code":"NoSuchKey","message":"The specified key does not exist.","requestId":"68d2612c-ee2f-4fa0-83f7-7e762a9e07e4"}

**Comment by jia0511** [comment]
https://bj.bcebos.com/fastdeploy/release/cpp/fastdeploy-linux-aarch64-1.0.7.tgz 
这个问题有人处理下吗？

**Comment by jia0511** [comment]
--2023-07-22 19:57:16--  https://bj.bcebos.com/fastdeploy/release/cpp/fastdeploy-linux-aarch64-1.0.7.tgz
正在解析主机 bj.bcebos.com (bj.bcebos.com)... 111.63.96.3, 2409:8c04:1001:1002:0:ff:b001:368a
正在连接 bj.bcebos.com (bj.bcebos.com)|111.63.96.3|:443... 已连接。
已发出 HTTP 请求，正在等待回应... 404 Not Found
2023-07-22 19:57:16 错误 404：Not Found。

**Comment by jia0511** [comment]
[https://github.com/PaddlePaddle/FastDeploy/issues/2086](url)

**Comment by jia0511** [comment]
有没有人解决这个下载连接失效问题 @edwardzhou @ZeyuChen @llxxxll @kuizhiqing

**Comment by jiangjiajun** [comment]
目前没有提供arm上预编译的最新库，需要自行编译

**Comment by jia0511** [comment]
只能说维护力度跟不上
