### ISSUE TITLE
FastDeploy下的YoloV5服务化后，客户端怎么获得推理后有标注的图片？

### ISSUE THREAD

**Issue by 19245222** [PaddlePaddle/FastDeploy#2041]
*********************************************
温馨提示：根据社区不完全统计，按照模板提问，可以加快回复和解决问题的速度
*********************************************

## 环境

- 【FastDeploy版本】： fastdeploy:1.0.--gpu-cuda11.7-trt8.5-21.10
- 【编译命令】: 参考这篇文档->https://github.com/PaddlePaddle/FastDeploy/blob/develop/serving/docs/zh_CN/compile.md , 
- 【系统平台】: Linux x64(Ubuntu 18.04)
- 【硬件】：  Nvidia GPU TITIAN X， CUDA 11.7
- 【编译语言】： Python 3.8

## 问题
- 我参考了https://github.com/PaddlePaddle/FastDeploy/blob/develop/examples/vision/detection/yolov5/serving/README_CN.md      这份文档在docker里部署了一个yolov5的服务后，我调用 python3 yolov5_grpc_client.py 发送了一个图片目标检测的请求。
以下是我得到的输出，我很想知道的是，这只是输出，但我怎么才能够获得有标注的图片呢？
FastDeploy/examples/vision/detection/yolov5/serving$ python3 yolov5_grpc_client.py
tm: name: "INPUT"
datatype: "UINT8"
shape: -1
shape: -1
shape: -1
shape: 3

output_name: detction_result
{'boxes': [[188.49755859375, 331.054931640625, 418.91778564453125, 351.24371337890625], [436.3992614746094, 308.8633117675781, 535.6851196289062, 332.1841735839844], [138.71661376953125, 268.9527587890625, 373.19927978515625, 288.5521240234375], [99.02114868164062, 329.9296875, 151.0340576171875, 351.8544921875], [132.05865478515625, 458.33148193359375, 554.5450439453125, 497.2388916015625]], 'scores': [0.7492504715919495, 0.7485949993133545, 0.6756349205970764, 0.6652286052703857, 0.25799834728240967], 'label_ids': [0, 0, 0, 0, 0], 'masks': [], 'contain_masks': False}

**Comment by njflove** [comment]
这个问题有解决方法吗？我也有同样的需求
