### ISSUE TITLE
Combining Object Detection and OCR into a Network-Accessible Service

### ISSUE THREAD

**Issue by 19245222** [PaddlePaddle/FastDeploy#2043]
Hello, I want to combine the functionalities of object detection and OCR into a new feature. For instance, after object detection, I get several bounding boxes, and then I use OCR to extract the text within these boxes. Moreover, I want to package this functionality into a service interface that can be used by other machines in the local area network. How should I go about doing this?

**Comment by leiqing1** [comment]
Hello, you can refer to[ FastDeploy's service-oriented deployment](https://github.com/PaddlePaddle/FastDeploy/blob/e171710044280b4807628c02464f0bad65904ef5/examples/vision/ocr/PP-OCR/serving/simple_serving/README.md) document to achieve the final deployment as a service. If the service is called by a large number of people and QPS needs to be considered, [the fastdeploy Serving](https://github.com/PaddlePaddle/FastDeploy/tree/develop/serving) method can be used. If it is only deployed as a service and there are not many users, the [simple serving](https://github.com/PaddlePaddle/FastDeploy/blob/e171710044280b4807628c02464f0bad65904ef5/examples/vision/ocr/PP-OCR/serving/simple_serving/README.md) method can be used. If there are too many models connected in series, OCR itself is a multi model connected system, which can be completed by referring to the deployment service of OCR.

**Comment by MikeLud** [comment]
> Hello, I want to combine the functionalities of object detection and OCR into a new feature. For instance, after object detection, I get several bounding boxes, and then I use OCR to extract the text within these boxes. Moreover, I want to package this functionality into a service interface that can be used by other machines in the local area network. How should I go about doing this?

You can look at using CodeProject.AI as your server. I am doing this with the ALPR module. I first detect the license plate using YOLOv5 object detection then use PaddleOCR to read the license plate.

https://www.codeproject.com/Articles/5322557/CodeProject-AI-Server-AI-the-easy-way
