### ISSUE TITLE
在AIxBoard爱克斯板 无法调用fastdeploy

### ISSUE THREAD

**Issue by 534114658** [PaddlePaddle/FastDeploy#2045]
*********************************************
温馨提示：根据社区不完全统计，按照模板提问，可以加快回复和解决问题的速度
*********************************************

## 环境

- 【FastDeploy版本】： fastdeploy-win-x64-1.0.7
- 【系统平台】: Windows x64(Windows10)
- 【硬件】： CPU Intel(R) Celeron(R) N5105 @ 2.00GHz
- 【编译语言】： C++ 

## 问题日志及出现问题的操作流程
- 【exe运行报错】
- - 在AIxBoard上运行生成的exe报0xc0000142
- 
![image](https://github.com/PaddlePaddle/FastDeploy/assets/88479008/15395075-92bb-4b2c-b349-5f4742b92d5d)

- 【在vs报错】
- - 在vs里面报  没有为 paddle_inference.dll 加载的符号文件
- 是CPU的指令集不支持吗？
- 
![image](https://github.com/PaddlePaddle/FastDeploy/assets/88479008/85c85ef3-3fa5-4da1-b9ab-4949e211d770)

- 【在其他电脑正常】
- - 其他电脑测试正常 i7-8700k  i3-7100
- 【其他测试】
- 在AIxBoard上只要不调用paddle_inference.dll，opencv openvino都可以正常调用

**Comment by jiangjiajun** [comment]
Windows使用注意拷贝相应dll文件到exe所在目录，避免因为dll找不到出错https://github.com/PaddlePaddle/FastDeploy/blob/develop/docs/cn/faq/use_sdk_on_windows.md

**Comment by 534114658** [comment]
dll都拷过去了   cpu   在i7-8700k i3-7100都能正常运行  在AIxBoard上报错

**Comment by 534114658** [comment]
我在AIxBoard上安装python cpu版本也无法运行
![image](https://github.com/PaddlePaddle/FastDeploy/assets/88479008/ab34b663-30de-4afe-8f9b-193dfd8d66fe)

python安装命令
![image](https://github.com/PaddlePaddle/FastDeploy/assets/88479008/edece457-8f5e-4bae-9105-5fdd90f6041c)

**Comment by jiangjiajun** [comment]
@534114658 AIxBoard的CPU支持avx指令吗？ 可尝试自行编译一下FD，只启用ORT后端，再测试看是否可以运行

**Comment by 534114658** [comment]
错误是paddle_inference.dll报出来的

**Comment by jiangjiajun** [comment]
你可以自行编译FD，不集成Paddle后端，再进行测试

**Comment by 534114658** [comment]
自行编译FD，不集成Paddle后端   可以使用

**Comment by 534114658** [comment]
在使用CPU推理  使用如下代码可以正常调用模型推理
auto option = fastdeploy::RuntimeOption();
option.UseCpu();
option.UseOpenVINOBackend();
option.openvino_option.SetDevice("CPU");
auto model = fastdeploy::vision::detection::PPYOLOE(model_filename, params_filename, cfg_file, option);

但是把CPU改为GPU时，下面的代码会报错
auto model = fastdeploy::vision::detection::PPYOLOE(model_filename, params_filename, cfg_file, option);

测试过纯openvino的demo代码device可以设置GPU使用
上面的代码是不是少设置了什么参数？ 需要怎么设置？  有没有范例？

**Comment by 534114658** [comment]
非常感谢

https://github.com/PaddlePaddle/FastDeploy/blob/develop/tutorials/intel_gpu/README_CN.md

**Comment by tonyfung820** [comment]
請問為何在bios找不到 M2 nvme 裝置？
