### ISSUE TITLE
gpu环境，T4的卡，进行OCR推理，显存持续增加导致程序崩溃

### ISSUE THREAD

**Issue by ytzhang** [PaddlePaddle/FastDeploy#2053]
*********************************************
温馨提示：根据社区不完全统计，按照模板提问，可以加快回复和解决问题的速度
*********************************************

## 环境

- 【FastDeploy版本】： fastdeploy-linux-gpu-1.0.6
- 【编译命令】如果您是自行编译的FastDeploy，请说明您的编译方式（参数命令），参数命令完全按照官方给的指导编译的。
- 【系统平台】: Linux x64(Ubuntu 20.04) 
- 【硬件】： 说明具体硬件型号，如 Nvidia GPU T4， CUDA 11.2 CUDNN 8.3
- 【编译语言】： C++ 

## 问题日志及出现问题的操作流程

- 使用官方的推理例子，https://github.com/PaddlePaddle/FastDeploy/blob/develop/examples/vision/ocr/PP-OCR/cpu-gpu/cpp/infer.cc

如果模型初始化后，循环进行图片的推理调用，显存会持续增加，导致程序最终崩溃，不能使用

**Comment by Cute-Yang** [comment]
不如自己重写吧，而且这个似乎只是单线程版本，我没有看到多线程的写法
