### ISSUE TITLE
onnx转rknn遇到的疑问。YOLOV5训练出来的权重怎么知道normalize中的std和mean是多少？

### ISSUE THREAD

**Issue by ijiami-01** [PaddlePaddle/FastDeploy#2054]
如下图，需要我填写std和mean，我不知道该怎么填这里面的数字啊。
![image](https://github.com/PaddlePaddle/FastDeploy/assets/129148313/6caea79f-a23f-43d7-9662-7325617132c7)

**Comment by zg651413411** [comment]
使用V5能转成RKNN模型吗
