### ISSUE TITLE
推理的时候可以实现多卡推理，提供web服务吗

### ISSUE THREAD

**Issue by liuzhipengchd** [PaddlePaddle/FastDeploy#2068]
目前问题：一个卡的显存不够用，需要把一个模型拆分到2个卡中进行推理。。提供web服务。
看到paddlenlp推荐采用fastdeploy进行推理。

**Comment by jiangjiajun** [comment]
要部署什么模型，我们很快会有专门针对生成式大模型的多卡部署支持

**Comment by liuzhipengchd** [comment]
> 要部署什么模型，我们很快会有专门针对生成式大模型的多卡部署支持

部署chatglm6b的模型（想用2个3060的12g卡部署，但是paddle不支持，目前只能采用transformer的），paddlenlp的分布式训练很好，但是多卡部署功能有点不足。。大佬，什么时候会支持多卡部署推理的功能呀

**Comment by jiangjiajun** [comment]
chatGLM-6B应该会在下个月有版本来支持
