### ISSUE TITLE
fastdeploy使用web_demo上传图片进行文字识别，识别正确率低于paddleocr中推理的精度，而且速度很慢

### ISSUE THREAD

**Issue by dizhenx** [PaddlePaddle/FastDeploy#2071]
使用web_demo，安装npm套件，上传图片进行文字识别，识别正确率低于paddleocr中推理的精度，而且速度很慢。
是不是因为fastdeploy集成的前端paddle-js-models/ocr模型包跟paddleocr中paddleocr>=2.0.1使用的模型PP-OCRv3版本不一样，精度下降造成的？怎么解决？
而且我安装的是fastdeploy-gpu-python，图片识别的时候，没有看到后台使用gpu显存，速度很慢是否是因为没有用gpu？怎么解决

**Comment by chenqianhe** [comment]
web 版本的模型经过了调整，确实在某些情况下精度会下降；可以选择使用旧版本的模型看看。

web 版本的不依赖你本地安装 fastdeploy-gpu-python；是你本地 python 跑推理存在问题吗

**Comment by dizhenx** [comment]
> web 版本的模型经过了调整，确实在某些情况下精度会下降；可以选择使用旧版本的模型看看。
> 
> web 版本的不依赖你本地安装 fastdeploy-gpu-python；是你本地 python 跑推理存在问题吗

那怎么使用旧版本的模型？我感觉web版的精度下降挺大，不是某些情况下，而是下降了30%左右，尤其是在字符较小的情况下下降更多。
本地 python 跑推理没有问题。那我用web版的上传图片2.6m大小，识别要等待接近一分钟怎么回事？web版识别不需要gpu吗？我没看到识别过程中占用gpu显存

**Comment by chenqianhe** [comment]
> > web 版本的模型经过了调整，确实在某些情况下精度会下降；可以选择使用旧版本的模型看看。
> > web 版本的不依赖你本地安装 fastdeploy-gpu-python；是你本地 python 跑推理存在问题吗
> 
> 那怎么使用旧版本的模型？我感觉web版的精度下降挺大，不是某些情况下，而是下降了30%左右，尤其是在字符较小的情况下下降更多。 本地 python 跑推理没有问题。那我用web版的上传图片2.6m大小，识别要等待接近一分钟怎么回事？web版识别不需要gpu吗？我没看到识别过程中占用gpu显存

模型替换：https://github.com/PaddlePaddle/FastDeploy/blob/develop/examples/application/js/WebDemo_CN.md#3-%E6%A8%A1%E5%9E%8B%E6%9B%BF%E6%8D%A2

修改推理后端的话就不能直接使用封装好的 库，需要修改源码https://github.com/PaddlePaddle/FastDeploy/blob/4c3e7030e151528d304619901c794481bb2f6037/examples/application/js/package/packages/paddlejs-models/ocr/src/index.ts#L7
支持
[paddlejs-backend-webgl](https://github.com/PaddlePaddle/Paddle.js/blob/release/v2.2.5/packages/paddlejs-backend-webgl/README.md), webgl backend, the main backend for Paddle.js, [ops supported](https://github.com/PaddlePaddle/Paddle.js/blob/release/v2.2.5/packages/paddlejs-backend-webgl/src/ops/index.ts) size downloads downloads
[paddlejs-backend-webgpu](https://github.com/PaddlePaddle/Paddle.js/blob/release/v2.2.5/packages/paddlejs-backend-webgpu/README.md), webgpu backend, an experimental backend, [WebGPU draft](https://gpuweb.github.io/gpuweb/), [ops supported](https://github.com/PaddlePaddle/Paddle.js/blob/release/v2.2.5/packages/paddlejs-backend-webgpu/src/ops/index.ts)
[paddlejs-backend-wasm](https://github.com/PaddlePaddle/Paddle.js/blob/release/v2.2.5/packages/paddlejs-backend-wasm/README_cn.md), WebAssembly backend, [ops supported](https://github.com/PaddlePaddle/Paddle.js/blob/release/v2.2.5/packages/paddlejs-backend-wasm/src/ops.ts)
[paddlejs-backend-cpu](https://github.com/PaddlePaddle/Paddle.js/blob/release/v2.2.5/packages/paddlejs-backend-cpu/README.md), cpu backend, [ops supported](https://github.com/PaddlePaddle/Paddle.js/blob/release/v2.2.5/packages/paddlejs-backend-cpu/src/ops/index.ts)
[paddlejs-backend-nodegl](https://github.com/PaddlePaddle/Paddle.js/blob/release/v2.2.5/packages/paddlejs-backend-nodegl/README.md), nodegl backend, a backend in Node.js for Paddle.js, using the webgl backend ops. [ops supported](https://github.com/PaddlePaddle/Paddle.js/blob/release/v2.2.5/packages/paddlejs-backend-webgl/src/ops/index.ts)

**Comment by dizhenx** [comment]
> > > web 版本的模型经过了调整，确实在某些情况下精度会下降；可以选择使用旧版本的模型看看。
> > > web 版本的不依赖你本地安装 fastdeploy-gpu-python；是你本地 python 跑推理存在问题吗
> > 
> > 
> > 那怎么使用旧版本的模型？我感觉web版的精度下降挺大，不是某些情况下，而是下降了30%左右，尤其是在字符较小的情况下下降更多。 本地 python 跑推理没有问题。那我用web版的上传图片2.6m大小，识别要等待接近一分钟怎么回事？web版识别不需要gpu吗？我没看到识别过程中占用gpu显存
> 
> 模型替换：https://github.com/PaddlePaddle/FastDeploy/blob/develop/examples/application/js/WebDemo_CN.md#3-%E6%A8%A1%E5%9E%8B%E6%9B%BF%E6%8D%A2
> 
> 修改推理后端的话就不能直接使用封装好的 库，需要修改源码
> 
> https://github.com/PaddlePaddle/FastDeploy/blob/4c3e7030e151528d304619901c794481bb2f6037/examples/application/js/package/packages/paddlejs-models/ocr/src/index.ts#L7
> 
> 
> 支持
> [paddlejs-backend-webgl](https://github.com/PaddlePaddle/Paddle.js/blob/release/v2.2.5/packages/paddlejs-backend-webgl/README.md), webgl backend, the main backend for Paddle.js, [ops supported](https://github.com/PaddlePaddle/Paddle.js/blob/release/v2.2.5/packages/paddlejs-backend-webgl/src/ops/index.ts) size downloads downloads
> [paddlejs-backend-webgpu](https://github.com/PaddlePaddle/Paddle.js/blob/release/v2.2.5/packages/paddlejs-backend-webgpu/README.md), webgpu backend, an experimental backend, [WebGPU draft](https://gpuweb.github.io/gpuweb/), [ops supported](https://github.com/PaddlePaddle/Paddle.js/blob/release/v2.2.5/packages/paddlejs-backend-webgpu/src/ops/index.ts)
> [paddlejs-backend-wasm](https://github.com/PaddlePaddle/Paddle.js/blob/release/v2.2.5/packages/paddlejs-backend-wasm/README_cn.md), WebAssembly backend, [ops supported](https://github.com/PaddlePaddle/Paddle.js/blob/release/v2.2.5/packages/paddlejs-backend-wasm/src/ops.ts)
> [paddlejs-backend-cpu](https://github.com/PaddlePaddle/Paddle.js/blob/release/v2.2.5/packages/paddlejs-backend-cpu/README.md), cpu backend, [ops supported](https://github.com/PaddlePaddle/Paddle.js/blob/release/v2.2.5/packages/paddlejs-backend-cpu/src/ops/index.ts)
> [paddlejs-backend-nodegl](https://github.com/PaddlePaddle/Paddle.js/blob/release/v2.2.5/packages/paddlejs-backend-nodegl/README.md), nodegl backend, a backend in Node.js for Paddle.js, using the webgl backend ops. [ops supported](https://github.com/PaddlePaddle/Paddle.js/blob/release/v2.2.5/packages/paddlejs-backend-webgl/src/ops/index.ts)

推理后端修改有啥用？感觉webgl改为webgpu没啥区别。而且识别的时候没发现gpu显存占用是怎么回事？另外图片识别精度降低是因为模型的原因还是因为图片传进去缩放造成的？还有只能识别图片，不能识别pdf

**Comment by chenqianhe** [comment]
> 

图片识别精读降低的话你说的两个点都会有影响；目前要支持 pdf 需要自己增加 pdf 相关处理

不同后端对应不同的实现方式；显存没有占用的话就可能需要具体去分析看看了，比如驱动啥的问题之类的导致没有成功调取 gpu；您这边控制台有什么报错或者警告吗

**Comment by dizhenx** [comment]
> 

控制台没有报错，跟驱动没关系，我用别的方式调用paddleocr就可以看到gpu显存有占用，用这个web_demo调用就看不到gpu显存变化

**Comment by chenqianhe** [comment]
我这边测试了一下，是有显卡占用的，可能需要您再看一下 webgpu 要求的相关环境配置等
