### ISSUE TITLE
复现FastDeploy Serving中的PaddleDetection 服务化部署失败

### ISSUE THREAD

**Issue by LUOQING1994** [PaddlePaddle/FastDeploy#2072]
## 环境

- 【FastDeploy版本】： docker镜像  registry.baidubce.com/paddlepaddle/fastdeploy:x.y.z-gpu-cuda11.4-trt8.4-21.10
- 【系统平台】: Linux x64(Ubuntu 18.04) 
- 【硬件】： Nvidia GPU 3050TI， CUDA 11.7  CUDNN 8.4
- 【编译语言】：Python3.8

## 问题日志及出现问题的操作流程
- 【模型跑不通】
我按照[此处](https://github.com/PaddlePaddle/FastDeploy/blob/develop/examples/vision/detection/paddledetection/serving/README_CN.md)进行FastDeploy Serving中的PaddleDetection 服务化部署，进入docker镜像后运行如下命令
```
CUDA_VISIBLE_DEVICES=0 fastdeployserver --model-repository=/serving/models
```
无法启动模型，具体日志如下
```
I0629 04:47:53.767341 117 metrics.cc:298] Collecting metrics for GPU 0: NVIDIA GeForce RTX 3050
I0629 04:47:53.888306 117 pinned_memory_manager.cc:240] Pinned memory pool is created at '0x7fe9ac000000' with size 268435456
I0629 04:47:53.888427 117 cuda_memory_manager.cc:105] CUDA memory pool is created on device 0 with size 67108864
I0629 04:47:53.889543 117 model_repository_manager.cc:1022] loading: postprocess:1
I0629 04:47:53.990155 117 model_repository_manager.cc:1022] loading: preprocess:1
I0629 04:47:53.996255 117 python.cc:1875] TRITONBACKEND_ModelInstanceInitialize: postprocess_0 (CPU device 0)
I0629 04:47:54.090382 117 model_repository_manager.cc:1022] loading: runtime:1
model_config: {'name': 'postprocess', 'platform': '', 'backend': 'python', 'version_policy': {'latest': {'num_versions': 1}}, 'max_batch_size': 0, 'input': [{'name': 'post_input1', 'data_type': 'TYPE_FP32', 'format': 'FORMAT_NONE', 'dims': [-1, 6], 'is_shape_tensor': False, 'allow_ragged_batch': False}, {'name': 'post_input2', 'data_type': 'TYPE_INT32', 'format': 'FORMAT_NONE', 'dims': [-1], 'is_shape_tensor': False, 'allow_ragged_batch': False}], 'output': [{'name': 'post_output', 'data_type': 'TYPE_STRING', 'dims': [-1], 'label_filename': '', 'is_shape_tensor': False}], 'batch_input': [], 'batch_output': [], 'optimization': {'priority': 'PRIORITY_DEFAULT', 'input_pinned_memory': {'enable': True}, 'output_pinned_memory': {'enable': True}, 'gather_kernel_buffer_threshold': 0, 'eager_batching': False}, 'instance_group': [{'name': 'postprocess_0', 'kind': 'KIND_CPU', 'count': 1, 'gpus': [], 'secondary_devices': [], 'profile': [], 'passive': False, 'host_policy': ''}], 'default_model_filename': '', 'cc_model_filenames': {}, 'metric_tags': {}, 'parameters': {}, 'model_warmup': []}
postprocess input names: ['post_input1', 'post_input2']
postprocess output names: ['post_output']
I0629 04:47:54.203991 117 model_repository_manager.cc:1183] successfully loaded 'postprocess' version 1
I0629 04:47:54.335351 117 fastdeploy_runtime.cc:1173] TRITONBACKEND_Initialize: fastdeploy
I0629 04:47:54.335382 117 fastdeploy_runtime.cc:1182] Triton TRITONBACKEND API version: 1.6
I0629 04:47:54.335386 117 fastdeploy_runtime.cc:1187] 'fastdeploy' TRITONBACKEND API version: 1.6
I0629 04:47:54.335388 117 fastdeploy_runtime.cc:1216] backend configuration:
{}
I0629 04:47:54.335410 117 python.cc:1875] TRITONBACKEND_ModelInstanceInitialize: preprocess_0 (CPU device 0)
model_config: {'name': 'preprocess', 'platform': '', 'backend': 'python', 'version_policy': {'latest': {'num_versions': 1}}, 'max_batch_size': 0, 'input': [{'name': 'preprocess_input', 'data_type': 'TYPE_UINT8', 'format': 'FORMAT_NONE', 'dims': [-1, -1, -1, 3], 'is_shape_tensor': False, 'allow_ragged_batch': False}], 'output': [{'name': 'preprocess_output1', 'data_type': 'TYPE_FP32', 'dims': [-1, 3, -1, -1], 'label_filename': '', 'is_shape_tensor': False}, {'name': 'preprocess_output2', 'data_type': 'TYPE_FP32', 'dims': [-1, 2], 'label_filename': '', 'is_shape_tensor': False}, {'name': 'preprocess_output3', 'data_type': 'TYPE_FP32', 'dims': [-1, 2], 'label_filename': '', 'is_shape_tensor': False}], 'batch_input': [], 'batch_output': [], 'optimization': {'priority': 'PRIORITY_DEFAULT', 'input_pinned_memory': {'enable': True}, 'output_pinned_memory': {'enable': True}, 'gather_kernel_buffer_threshold': 0, 'eager_batching': False}, 'instance_group': [{'name': 'preprocess_0', 'kind': 'KIND_CPU', 'count': 1, 'gpus': [], 'secondary_devices': [], 'profile': [], 'passive': False, 'host_policy': ''}], 'default_model_filename': '', 'cc_model_filenames': {}, 'metric_tags': {}, 'parameters': {}, 'model_warmup': []}
preprocess input names: ['preprocess_input']
preprocess output names: ['preprocess_output1', 'preprocess_output2', 'preprocess_output3']
[INFO] fastdeploy/vision/common/processors/transform.cc(45)::FuseNormalizeCast	Normalize and Cast are fused to Normalize in preprocessing pipeline.
[INFO] fastdeploy/vision/common/processors/transform.cc(93)::FuseNormalizeHWC2CHW	Normalize and HWC2CHW are fused to NormalizeAndPermute  in preprocessing pipeline.
[INFO] fastdeploy/vision/common/processors/transform.cc(159)::FuseNormalizeColorConvert	BGR2RGB and NormalizeAndPermute are fused to NormalizeAndPermute with swap_rb=1
I0629 04:47:54.523955 117 fastdeploy_runtime.cc:1246] TRITONBACKEND_ModelInitialize: runtime (version 1)
I0629 04:47:54.524059 117 model_repository_manager.cc:1183] successfully loaded 'preprocess' version 1
I0629 04:47:54.524807 117 fastdeploy_runtime.cc:1285] TRITONBACKEND_ModelInstanceInitialize: runtime_0 (GPU device 0)
[INFO] fastdeploy/runtime.cc(517)::Init	Runtime initialized with Backend::PDINFER in Device::GPU.
I0629 04:47:56.292450 117 model_repository_manager.cc:1183] successfully loaded 'runtime' version 1
I0629 04:47:56.292627 117 model_repository_manager.cc:1022] loading: ppdet:1
I0629 04:47:56.393060 117 model_repository_manager.cc:1183] successfully loaded 'ppdet' version 1
I0629 04:47:56.393241 117 server.cc:522] 
+------------------+------+
| Repository Agent | Path |
+------------------+------+
+------------------+------+

I0629 04:47:56.393341 117 server.cc:549] 
+------------+---------------------------------------------------------------+--------+
| Backend    | Path                                                          | Config |
+------------+---------------------------------------------------------------+--------+
| python     | /opt/tritonserver/backends/python/libtriton_python.so         | {}     |
| fastdeploy | /opt/tritonserver/backends/fastdeploy/libtriton_fastdeploy.so | {}     |
+------------+---------------------------------------------------------------+--------+

I0629 04:47:56.393434 117 server.cc:592] 
+-------------+---------+--------+
| Model       | Version | Status |
+-------------+---------+--------+
| postprocess | 1       | READY  |
| ppdet       | 1       | READY  |
| preprocess  | 1       | READY  |
| runtime     | 1       | READY  |
+-------------+---------+--------+

I0629 04:47:56.393658 117 tritonserver.cc:1920] 
+----------------------------------+----------------------------------------------------------------------------------------------------------------------------------------+
| Option                           | Value                                                                                                                                  |
+----------------------------------+----------------------------------------------------------------------------------------------------------------------------------------+
| server_id                        | triton                                                                                                                                 |
| server_version                   | 2.15.0                                                                                                                                 |
| server_extensions                | classification sequence model_repository model_repository(unload_dependents) schedule_policy model_configuration system_shared_memory  |
|                                  | cuda_shared_memory binary_tensor_data statistics                                                                                       |
| model_repository_path[0]         | /serving/models                                                                                                                        |
| model_control_mode               | MODE_NONE                                                                                                                              |
| strict_model_config              | 1                                                                                                                                      |
| rate_limit                       | OFF                                                                                                                                    |
| pinned_memory_pool_byte_size     | 268435456                                                                                                                              |
| cuda_memory_pool_byte_size{0}    | 67108864                                                                                                                               |
| response_cache_byte_size         | 0                                                                                                                                      |
| min_supported_compute_capability | 6.0                                                                                                                                    |
| strict_readiness                 | 1                                                                                                                                      |
| exit_timeout                     | 30                                                                                                                                     |
+----------------------------------+----------------------------------------------------------------------------------------------------------------------------------------+

E0629 12:47:56.394712287     117 server_chttp2.cc:40]        {"created":"@1688014076.394608102","description":"No address added out of total 1 resolved","file":"/tmp/tritonbuild/tritonserver/build/_deps/repo-third-party-build/grpc-repo/src/grpc/src/core/ext/transport/chttp2/server/chttp2_server.cc","file_line":394,"referenced_errors":[{"created":"@1688014076.394604893","description":"Failed to add any wildcard listeners","file":"/tmp/tritonbuild/tritonserver/build/_deps/repo-third-party-build/grpc-repo/src/grpc/src/core/lib/iomgr/tcp_server_posix.cc","file_line":340,"referenced_errors":[{"created":"@1688014076.394584447","description":"Unable to configure socket","fd":31,"file":"/tmp/tritonbuild/tritonserver/build/_deps/repo-third-party-build/grpc-repo/src/grpc/src/core/lib/iomgr/tcp_server_utils_posix_common.cc","file_line":207,"referenced_errors":[{"created":"@1688014076.394580766","description":"Address already in use","errno":98,"file":"/tmp/tritonbuild/tritonserver/build/_deps/repo-third-party-build/grpc-repo/src/grpc/src/core/lib/iomgr/tcp_server_utils_posix_common.cc","file_line":181,"os_error":"Address already in use","syscall":"bind"}]},{"created":"@1688014076.394604329","description":"Unable to configure socket","fd":31,"file":"/tmp/tritonbuild/tritonserver/build/_deps/repo-third-party-build/grpc-repo/src/grpc/src/core/lib/iomgr/tcp_server_utils_posix_common.cc","file_line":207,"referenced_errors":[{"created":"@1688014076.394601805","description":"Address already in use","errno":98,"file":"/tmp/tritonbuild/tritonserver/build/_deps/repo-third-party-build/grpc-repo/src/grpc/src/core/lib/iomgr/tcp_server_utils_posix_common.cc","file_line":181,"os_error":"Address already in use","syscall":"bind"}]}]}]}
Signal (11) received.
 0# 0x000055D9456968A9 in fastdeployserver
 1# 0x00007FEA03C6D210 in /usr/lib/x86_64-linux-gnu/libc.so.6
 2# 0x000055D94599ED78 in fastdeployserver
 3# 0x000055D94577B341 in fastdeployserver
 4# 0x000055D945785998 in fastdeployserver
 5# 0x000055D9457981B2 in fastdeployserver
 6# 0x00007FEA0405BDE4 in /usr/lib/x86_64-linux-gnu/libstdc++.so.6
 7# 0x00007FEA044D9609 in /usr/lib/x86_64-linux-gnu/libpthread.so.0
 8# clone in /usr/lib/x86_64-linux-gnu/libc.so.6

Segmentation fault (core dumped)
```

**Comment by teymur-git** [comment]
@LUOQING1994 尝试分配共享内存试下

**Comment by youqugit** [comment]
> ## 环境
> * 【FastDeploy版本】： docker镜像  registry.baidubce.com/paddlepaddle/fastdeploy:x.y.z-gpu-cuda11.4-trt8.4-21.10
> * 【系统平台】: Linux x64(Ubuntu 18.04)
> * 【硬件】： Nvidia GPU 3050TI， CUDA 11.7  CUDNN 8.4
> * 【编译语言】：Python3.8
> 
> ## 问题日志及出现问题的操作流程
> * 【模型跑不通】
>   我按照[此处](https://github.com/PaddlePaddle/FastDeploy/blob/develop/examples/vision/detection/paddledetection/serving/README_CN.md)进行FastDeploy Serving中的PaddleDetection 服务化部署，进入docker镜像后运行如下命令
> 
> ```
> CUDA_VISIBLE_DEVICES=0 fastdeployserver --model-repository=/serving/models
> ```
> 
> 无法启动模型，具体日志如下
> 
> ```
> I0629 04:47:53.767341 117 metrics.cc:298] Collecting metrics for GPU 0: NVIDIA GeForce RTX 3050
> I0629 04:47:53.888306 117 pinned_memory_manager.cc:240] Pinned memory pool is created at '0x7fe9ac000000' with size 268435456
> I0629 04:47:53.888427 117 cuda_memory_manager.cc:105] CUDA memory pool is created on device 0 with size 67108864
> I0629 04:47:53.889543 117 model_repository_manager.cc:1022] loading: postprocess:1
> I0629 04:47:53.990155 117 model_repository_manager.cc:1022] loading: preprocess:1
> I0629 04:47:53.996255 117 python.cc:1875] TRITONBACKEND_ModelInstanceInitialize: postprocess_0 (CPU device 0)
> I0629 04:47:54.090382 117 model_repository_manager.cc:1022] loading: runtime:1
> model_config: {'name': 'postprocess', 'platform': '', 'backend': 'python', 'version_policy': {'latest': {'num_versions': 1}}, 'max_batch_size': 0, 'input': [{'name': 'post_input1', 'data_type': 'TYPE_FP32', 'format': 'FORMAT_NONE', 'dims': [-1, 6], 'is_shape_tensor': False, 'allow_ragged_batch': False}, {'name': 'post_input2', 'data_type': 'TYPE_INT32', 'format': 'FORMAT_NONE', 'dims': [-1], 'is_shape_tensor': False, 'allow_ragged_batch': False}], 'output': [{'name': 'post_output', 'data_type': 'TYPE_STRING', 'dims': [-1], 'label_filename': '', 'is_shape_tensor': False}], 'batch_input': [], 'batch_output': [], 'optimization': {'priority': 'PRIORITY_DEFAULT', 'input_pinned_memory': {'enable': True}, 'output_pinned_memory': {'enable': True}, 'gather_kernel_buffer_threshold': 0, 'eager_batching': False}, 'instance_group': [{'name': 'postprocess_0', 'kind': 'KIND_CPU', 'count': 1, 'gpus': [], 'secondary_devices': [], 'profile': [], 'passive': False, 'host_policy': ''}], 'default_model_filename': '', 'cc_model_filenames': {}, 'metric_tags': {}, 'parameters': {}, 'model_warmup': []}
> postprocess input names: ['post_input1', 'post_input2']
> postprocess output names: ['post_output']
> I0629 04:47:54.203991 117 model_repository_manager.cc:1183] successfully loaded 'postprocess' version 1
> I0629 04:47:54.335351 117 fastdeploy_runtime.cc:1173] TRITONBACKEND_Initialize: fastdeploy
> I0629 04:47:54.335382 117 fastdeploy_runtime.cc:1182] Triton TRITONBACKEND API version: 1.6
> I0629 04:47:54.335386 117 fastdeploy_runtime.cc:1187] 'fastdeploy' TRITONBACKEND API version: 1.6
> I0629 04:47:54.335388 117 fastdeploy_runtime.cc:1216] backend configuration:
> {}
> I0629 04:47:54.335410 117 python.cc:1875] TRITONBACKEND_ModelInstanceInitialize: preprocess_0 (CPU device 0)
> model_config: {'name': 'preprocess', 'platform': '', 'backend': 'python', 'version_policy': {'latest': {'num_versions': 1}}, 'max_batch_size': 0, 'input': [{'name': 'preprocess_input', 'data_type': 'TYPE_UINT8', 'format': 'FORMAT_NONE', 'dims': [-1, -1, -1, 3], 'is_shape_tensor': False, 'allow_ragged_batch': False}], 'output': [{'name': 'preprocess_output1', 'data_type': 'TYPE_FP32', 'dims': [-1, 3, -1, -1], 'label_filename': '', 'is_shape_tensor': False}, {'name': 'preprocess_output2', 'data_type': 'TYPE_FP32', 'dims': [-1, 2], 'label_filename': '', 'is_shape_tensor': False}, {'name': 'preprocess_output3', 'data_type': 'TYPE_FP32', 'dims': [-1, 2], 'label_filename': '', 'is_shape_tensor': False}], 'batch_input': [], 'batch_output': [], 'optimization': {'priority': 'PRIORITY_DEFAULT', 'input_pinned_memory': {'enable': True}, 'output_pinned_memory': {'enable': True}, 'gather_kernel_buffer_threshold': 0, 'eager_batching': False}, 'instance_group': [{'name': 'preprocess_0', 'kind': 'KIND_CPU', 'count': 1, 'gpus': [], 'secondary_devices': [], 'profile': [], 'passive': False, 'host_policy': ''}], 'default_model_filename': '', 'cc_model_filenames': {}, 'metric_tags': {}, 'parameters': {}, 'model_warmup': []}
> preprocess input names: ['preprocess_input']
> preprocess output names: ['preprocess_output1', 'preprocess_output2', 'preprocess_output3']
> [INFO] fastdeploy/vision/common/processors/transform.cc(45)::FuseNormalizeCast	Normalize and Cast are fused to Normalize in preprocessing pipeline.
> [INFO] fastdeploy/vision/common/processors/transform.cc(93)::FuseNormalizeHWC2CHW	Normalize and HWC2CHW are fused to NormalizeAndPermute  in preprocessing pipeline.
> [INFO] fastdeploy/vision/common/processors/transform.cc(159)::FuseNormalizeColorConvert	BGR2RGB and NormalizeAndPermute are fused to NormalizeAndPermute with swap_rb=1
> I0629 04:47:54.523955 117 fastdeploy_runtime.cc:1246] TRITONBACKEND_ModelInitialize: runtime (version 1)
> I0629 04:47:54.524059 117 model_repository_manager.cc:1183] successfully loaded 'preprocess' version 1
> I0629 04:47:54.524807 117 fastdeploy_runtime.cc:1285] TRITONBACKEND_ModelInstanceInitialize: runtime_0 (GPU device 0)
> [INFO] fastdeploy/runtime.cc(517)::Init	Runtime initialized with Backend::PDINFER in Device::GPU.
> I0629 04:47:56.292450 117 model_repository_manager.cc:1183] successfully loaded 'runtime' version 1
> I0629 04:47:56.292627 117 model_repository_manager.cc:1022] loading: ppdet:1
> I0629 04:47:56.393060 117 model_repository_manager.cc:1183] successfully loaded 'ppdet' version 1
> I0629 04:47:56.393241 117 server.cc:522] 
> +------------------+------+
> | Repository Agent | Path |
> +------------------+------+
> +------------------+------+
> 
> I0629 04:47:56.393341 117 server.cc:549] 
> +------------+---------------------------------------------------------------+--------+
> | Backend    | Path                                                          | Config |
> +------------+---------------------------------------------------------------+--------+
> | python     | /opt/tritonserver/backends/python/libtriton_python.so         | {}     |
> | fastdeploy | /opt/tritonserver/backends/fastdeploy/libtriton_fastdeploy.so | {}     |
> +------------+---------------------------------------------------------------+--------+
> 
> I0629 04:47:56.393434 117 server.cc:592] 
> +-------------+---------+--------+
> | Model       | Version | Status |
> +-------------+---------+--------+
> | postprocess | 1       | READY  |
> | ppdet       | 1       | READY  |
> | preprocess  | 1       | READY  |
> | runtime     | 1       | READY  |
> +-------------+---------+--------+
> 
> I0629 04:47:56.393658 117 tritonserver.cc:1920] 
> +----------------------------------+----------------------------------------------------------------------------------------------------------------------------------------+
> | Option                           | Value                                                                                                                                  |
> +----------------------------------+----------------------------------------------------------------------------------------------------------------------------------------+
> | server_id                        | triton                                                                                                                                 |
> | server_version                   | 2.15.0                                                                                                                                 |
> | server_extensions                | classification sequence model_repository model_repository(unload_dependents) schedule_policy model_configuration system_shared_memory  |
> |                                  | cuda_shared_memory binary_tensor_data statistics                                                                                       |
> | model_repository_path[0]         | /serving/models                                                                                                                        |
> | model_control_mode               | MODE_NONE                                                                                                                              |
> | strict_model_config              | 1                                                                                                                                      |
> | rate_limit                       | OFF                                                                                                                                    |
> | pinned_memory_pool_byte_size     | 268435456                                                                                                                              |
> | cuda_memory_pool_byte_size{0}    | 67108864                                                                                                                               |
> | response_cache_byte_size         | 0                                                                                                                                      |
> | min_supported_compute_capability | 6.0                                                                                                                                    |
> | strict_readiness                 | 1                                                                                                                                      |
> | exit_timeout                     | 30                                                                                                                                     |
> +----------------------------------+----------------------------------------------------------------------------------------------------------------------------------------+
> 
> E0629 12:47:56.394712287     117 server_chttp2.cc:40]        {"created":"@1688014076.394608102","description":"No address added out of total 1 resolved","file":"/tmp/tritonbuild/tritonserver/build/_deps/repo-third-party-build/grpc-repo/src/grpc/src/core/ext/transport/chttp2/server/chttp2_server.cc","file_line":394,"referenced_errors":[{"created":"@1688014076.394604893","description":"Failed to add any wildcard listeners","file":"/tmp/tritonbuild/tritonserver/build/_deps/repo-third-party-build/grpc-repo/src/grpc/src/core/lib/iomgr/tcp_server_posix.cc","file_line":340,"referenced_errors":[{"created":"@1688014076.394584447","description":"Unable to configure socket","fd":31,"file":"/tmp/tritonbuild/tritonserver/build/_deps/repo-third-party-build/grpc-repo/src/grpc/src/core/lib/iomgr/tcp_server_utils_posix_common.cc","file_line":207,"referenced_errors":[{"created":"@1688014076.394580766","description":"Address already in use","errno":98,"file":"/tmp/tritonbuild/tritonserver/build/_deps/repo-third-party-build/grpc-repo/src/grpc/src/core/lib/iomgr/tcp_server_utils_posix_common.cc","file_line":181,"os_error":"Address already in use","syscall":"bind"}]},{"created":"@1688014076.394604329","description":"Unable to configure socket","fd":31,"file":"/tmp/tritonbuild/tritonserver/build/_deps/repo-third-party-build/grpc-repo/src/grpc/src/core/lib/iomgr/tcp_server_utils_posix_common.cc","file_line":207,"referenced_errors":[{"created":"@1688014076.394601805","description":"Address already in use","errno":98,"file":"/tmp/tritonbuild/tritonserver/build/_deps/repo-third-party-build/grpc-repo/src/grpc/src/core/lib/iomgr/tcp_server_utils_posix_common.cc","file_line":181,"os_error":"Address already in use","syscall":"bind"}]}]}]}
> Signal (11) received.
>  0# 0x000055D9456968A9 in fastdeployserver
>  1# 0x00007FEA03C6D210 in /usr/lib/x86_64-linux-gnu/libc.so.6
>  2# 0x000055D94599ED78 in fastdeployserver
>  3# 0x000055D94577B341 in fastdeployserver
>  4# 0x000055D945785998 in fastdeployserver
>  5# 0x000055D9457981B2 in fastdeployserver
>  6# 0x00007FEA0405BDE4 in /usr/lib/x86_64-linux-gnu/libstdc++.so.6
>  7# 0x00007FEA044D9609 in /usr/lib/x86_64-linux-gnu/libpthread.so.0
>  8# clone in /usr/lib/x86_64-linux-gnu/libc.so.6
> 
> Segmentation fault (core dumped)
> ```

这个问题有解决吗
