### ISSUE TITLE
Windows下利用QT编写的包含paddl推理模型的软件发行到其他电脑中软件会闪退。（加载模型正常，使用模型推理会闪退，但发行的软件在开发电脑中正常运行）

### ISSUE THREAD

**Issue by elkslanlanlan** [PaddlePaddle/FastDeploy#2083]
*********************************************
温馨提示：根据社区不完全统计，按照模板提问，可以加快回复和解决问题的速度
*********************************************

- 【系统平台】: Windows x64(Windows10)
- 【硬件】：  Nvidia GPU 1050ti Nvidia GPU 1650， CUDA 10.1 CUDNN 7.6.5
- 【编译语言】： C++ /python

## 问题日志及出现问题的操作流程

利用QT编写的包含paddle推理模型的软件发行到其他电脑中软件会闪退。（加载模型正常，使用模型推理会闪退，但发行的软件在开发电脑中正常运行）
排除了海康SDK、opencv等的问题，要发行的电脑中配置了和开发电脑一致的cuda和cudnn，软件在新电脑中其他功能包括相机取图及显示，opencv处理等功能均正常，但加载模型后调用模型进行推理就会闪退。
发行软件的文件夹中包含的paddle动态库如下：
test_seg.dll、test_seg.lib、libiomp5md.dll、mkldnn.dll 、mklml.dll 、paddle_inference.dll
其中，test_seg.dll为使用VS生成的模型载入内存的动态库。
是否缺少了其他paddle推理模型必备的动态库导致发行的软件闪退呢？

**Comment by teymur-git** [comment]
@elkslanlanlan 和你出现过一样的问题，猜测是你cuda的问题，将cuda里bin文件下的所有dll复制到项目里。
