### ISSUE TITLE
Win10, 开启ENABLE_ENCRYPTION编译报错

### ISSUE THREAD

**Issue by elky98** [PaddlePaddle/FastDeploy#2091]
*********************************************
温馨提示：根据社区不完全统计，按照模板提问，可以加快回复和解决问题的速度
*********************************************

## 环境

- 【FastDeploy版本】： 最新develop分支
- 【编译命令】使用教程中的编译命令，设置 ENABLE_ENCRYPTION=ON
- 【系统平台】: Windows x64(Windows10)
- 【硬件】： CPU（i5-13400）
- 【编译语言】： Python(3.10）

## 问题日志及出现问题的操作流程
C:\Users\ht\Desktop\FastDeploy\.\fastdeploy/encryption/include/encrypt.h(51,42): error C2526: “Encrypt”: C 链接函数无法返回 C++
 类“std::vector<std::string,std::allocator<std::string>>” [C:\Users\ht\Desktop\FastDeploy\python\.setuptools-cmake-build
\fastdeploy.vcxproj]
C:\Users\ht\Desktop\FastDeploy\.\fastdeploy/encryption/include/encrypt.h(51,22): message : 参见“std::vector<std::string,s
td::allocator<std::string>>”的声明 [C:\Users\ht\Desktop\FastDeploy\python\.setuptools-cmake-build\fastdeploy.vcxproj]
C:\Users\ht\Desktop\FastDeploy\fastdeploy\encryption\src\encrypt.cc(61,21): warning C4267: “参数”: 从“size_t”转换到“const int
”，可能丢失数据 [C:\Users\ht\Desktop\FastDeploy\python\.setuptools-cmake-build\fastdeploy.vcxproj]
C:\Users\ht\Desktop\FastDeploy\fastdeploy\encryption\src\encrypt.cc(91,43): error C2556: “std::vector<std::string,std::
allocator<std::string>> fastdeploy::Encrypt(const std::string &,const std::string &)”: 重载函数与“void fastdeploy::Encrypt(c
onst std::string &,const std::string &)”只是在返回类型上不同 [C:\Users\ht\Desktop\FastDeploy\python\.setuptools-cmake-build\fastd
eploy.vcxproj]
C:\Users\ht\Desktop\FastDeploy\.\fastdeploy/encryption/include/encrypt.h(51,42): message : 参见“fastdeploy::Encrypt”的声明 [
C:\Users\ht\Desktop\FastDeploy\python\.setuptools-cmake-build\fastdeploy.vcxproj]
C:\Users\ht\Desktop\FastDeploy\fastdeploy\encryption\src\encrypt.cc(90,26): error C2371: “fastdeploy::Encrypt”: 重定义；不同的
基类型 [C:\Users\ht\Desktop\FastDeploy\python\.setuptools-cmake-build\fastdeploy.vcxproj]

**Comment by zhoujun0715** [comment]
我也是一样，请问你解决了吗

**Comment by elky98** [comment]
Windows 编译: 
1. 在cmake/openssl.cmake 41行shlwapi 后面添加 crypt32 ws2_32
2. 将fastdeploy/encryption/include/encrypt.h 25行的extern "C" { 和 下面的 } 去掉不使用C扩展  

MacOS 编译:
1. 在cmake/openssl.cmake 50行位置插入
```cmake
ELSEIF(CMAKE_SYSTEM_NAME MATCHES "Darwin")
        # brew --prefix openssl 查看Homebrew安装的openssl路径
        set(OPENSSL_ROOT_DIR "/opt/homebrew/opt/openssl")
        SET(OPENSSL_INCLUDE_DIR "${OPENSSL_ROOT_DIR}/include" CACHE PATH "openssl include directory." FORCE)
        include_directories(${OPENSSL_INCLUDE_DIR})
        set(OPENSSL_LIBRARIES
                "${OPENSSL_ROOT_DIR}/lib/libssl.dylib"
                "${OPENSSL_ROOT_DIR}/lib/libcrypto.dylib"
                ${GFLAGS_LIBRARIES}
                CACHE FILEPATH "OPENSSL_LIBRARIES" FORCE)
```
ARM - Linux，也需要另外配置自己的openssl

**Comment by zhoujun0715** [comment]
您好，你完成模型的加解密了吗？效果如何，openvino和tensorrt都适用吗，有相关教程吗？
非常感谢回复，很感谢，我vx：15236442125,希望能有个你的联系方式，共同学习进步

**Comment by elky98** [comment]
我自己只在onnx上加密模型并使用了，还是很好用的，其他的没有测试。

**Comment by zhoujun0715** [comment]
我也是准备对onnx模型加解密，请问您是在python上面实现的吗？我准备在c++上实现，您加解密的大致步骤是怎么实现的呀，我看这个上面的教程太过简短，希望能得到您的帮助，谢谢！

**Comment by elky98** [comment]
我是在python上用的，但c++也差不多，我目前只有python实现的代码可以给你参考一下，c++的我还没用。
```python
def encrypt_file(key: str, original_file: str | Path, encrypt_file: str | Path) -> None:
    """
    加密文件
    :param key: 加密密钥
    :param original_file: 原文件路径
    :param encrypt_file: 加密文件输出路径
    """
    original_file = Path(original_file).expanduser()
    encrypt_file = Path(encrypt_file).expanduser()
    with original_file.open('rb') as org_f:
        # 如果没有传入key, _则是加密密钥
        encrypted_content, _ = fd.encryption.encrypt(org_f.read(), key)
        with encrypt_file.open('w') as enc_f:
            enc_f.write(encrypted_content)
```

**Comment by zhoujun0715** [comment]
好的，非常感谢

**Comment by elky98** [comment]
解密的话就是:
```python
# yolov8
model = fd.vision.detection.YOLOv8(enc_onnx_file.as_posix(), "", runtime_option, fd.ModelFormat.ONNX)
```

**Comment by zhoujun0715** [comment]
好的，非常感谢，我去试试

**Comment by zhoujun0715** [comment]
python版本的编译出现下面错误，您那边遇到过吗
D:\1工作资料\A-2023.08.14深度学习部署\代码\deploy\下载\FastDeploy\FastDeploy\fastdeploy\encryption\encryption_pybind.cc(21,15): **error C3861: “Encrypt”: 找不到标识符** [D:\1工作资料\A-2023.08.14深度学习部署\代码\deploy\下载\FastDeploy\FastDeploy\python\.setuptools-cmake-bu
ild\fastdeploy_main.vcxproj]
D:\1工作资料\A-2023.08.14深度学习部署\代码\deploy\下载\FastDeploy\FastDeploy\fastdeploy\encryption\encryption_pybind.cc(27,15): error C3861**: “GenerateRandomKey”: 找不到标识符** [D:\1工作资料\A-2023.08.14深度学习部署\代码\deploy\下载\FastDeploy\FastDeploy\python\.setuptool
s-cmake-build\fastdeploy_main.vcxproj]

**Comment by zhoujun0715** [comment]
应该是fastdeploy\encryption\encryption_pybind.cc这个文件内容的问题，现在的是这样，请问你的是怎么写的：
namespace fastdeploy {

void BindEncryption(pybind11::module& m) {
  m.def("encrypt", [](const std::string& input, const std::string& key) {
       return Encrypt(input, key);
  });
  m.def("decrypt", [](const std::string& cipher, const std::string& key) {
       return Decrypt(cipher, key);
  });
  m.def("generate_key", []() {
       return GenerateRandomKey();
  });
}
}  // namespace fastdeploy

**Comment by elky98** [comment]
我为了最小改动git仓库代码 只做了上面讲的两点改动，能正常编译使用。

**Comment by elky98** [comment]
我vx: 1018480585  不一定能帮到你

**Comment by elky98** [comment]
```c++
#include "fastdeploy/encryption/include/encrypt.h"
void encrypt(){
    auto key = fastdeploy::GenerateRandomKey();
//    std::cout << "key: " << key << std::endl;
    std::string modelPath = "../assets/models/yolov6_1204/inference.onnx";
    std::string outPath = "../assets/models/yolov6_1204/onnx.encrypted";

    // 读模型
    std::ifstream infile(modelPath, std::ios::binary);
    std::string content((std::istreambuf_iterator<char>(infile)), std::istreambuf_iterator<char>());
    infile.close();

    // 返回值：[model, key]
    auto results = fastdeploy::Encrypt(content, key);
    std::cout << "key: " << results[1] << std::endl;

    // 保存加密后的模型
    std::ofstream outfile(outPath);
    outfile << results[0];
    outfile.close();
}
```
