### ISSUE TITLE
为什么使用GPU编译库编译完成后出现error while loading shared libraries: libonnxruntime.so.1.12.0:

### ISSUE THREAD

**Issue by vivienness** [PaddlePaddle/FastDeploy#2093]
## 环境

- 【FastDeploy版本】： 自行编译环境
- 【编译命令】cmake .. -DENABLE_ORT_BACKEND=ON \
         -DENABLE_PADDLE_BACKEND=ON \
         -DENABLE_OPENVINO_BACKEND=ON \
         -DENABLE_TRT_BACKEND=ON \
         -DWITH_GPU=ON \
         -DTRT_DIRECTORY=/home/xx/dev-file/deploy-file/TensorRT-8.6.0.12 \
         -DCUDA_DIRECTORY=/usr/local/cuda-11.8 \
         -DCMAKE_INSTALL_PREFIX=${PWD}/compiled_fastdeploy_sdk \
         -DENABLE_VISION=ON \
         -DOPENCV_DIRECTORY=/usr/lib/x86_64-linux-gnu/cmake/opencv4 \
         -DORT_DIRECTORY=/home/xx/dev-file/deploy-file/onnxruntime-linux-x64-1.12.0 \
         -DENABLE_TEXT=ON
- 【系统平台】: Linux x64(Ubuntu 20.04)
- 【硬件】：  Nvidia GPU 3070， CUDA 11.8 CUDNN 8.6
- 【编译语言】： C++ 

编译正常进行，但运行demo提示：error while loading shared libraries: libonnxruntime.so.1.12.0: cannot open shared object file: No such file or directory

CMakeLists结果:
-- Found OpenCV: /home/chenzhen/dev-file/fastdeploy-linux-x64-gpu-1.0.7/third_libs/install/opencv (found version "3.4.16") 
-- The path of ONNXRuntime is /home/chenzhen/dev-file/deploy-file/onnxruntime-linux-x64-1.12.0/lib.
-- OPENVINO_LIBS = /home/chenzhen/work-code/Paddle/FastDeploy/build/compiled_fastdeploy_sdk/third_libs/install/openvino/runtime/lib/libopenvino.so;TBB::tbb;TBB::tbbmalloc;TBB::tbbmalloc_proxy
-- The path of OpenCV is /usr/lib/x86_64-linux-gnu/cmake/opencv4.
-- Found OpenCV: /usr (found version "4.2.0") 
-- 
-- *************FastDeploy Building Summary**********
--   CMake version             : 3.24.2
--   CMake command             : /home/chenzhen/dev-file/clion-2022.3.3/bin/cmake/linux/x64/bin/cmake
--   System                    : Linux
--   C++ compiler              : /usr/bin/g++
--   C++ standard              : 11
--   C++ cuda standard         : 
--   C++ compiler version      : 9.4.0
--   CXX flags                 : -Wno-format
--   EXE linker flags          : 
--   Shared linker flags       : 
--   Build type                : Release
--   Compile definitions       : _GLIBCXX_USE_CXX11_ABI=1
--   CMAKE_PREFIX_PATH         : 
--   CMAKE_INSTALL_PREFIX      : /usr/local
--   CMAKE_MODULE_PATH         : 
-- 
--   FastDeploy version        : 0.0.0
--   ENABLE_ORT_BACKEND        : ON
--   ENABLE_RKNPU2_BACKEND     : OFF
--   ENABLE_HORIZON_BACKEND    : OFF
--   ENABLE_SOPHGO_BACKEND     : OFF
--   ENABLE_PADDLE_BACKEND     : ON
--   ENABLE_LITE_BACKEND       : OFF
--   ENABLE_POROS_BACKEND      : OFF
--   ENABLE_TRT_BACKEND        : ON
--   ENABLE_OPENVINO_BACKEND   : ON
--   ENABLE_TVM_BACKEND        : OFF
--   ENABLE_BENCHMARK          : OFF
--   ENABLE_VISION             : ON
--   ENABLE_TEXT               : ON
--   ENABLE_ENCRYPTION         : OFF
--   ENABLE_FLYCV              : OFF
--   ENABLE_CVCUDA             : OFF
--   WITH_GPU                  : ON
--   WITH_IPU                  : OFF
--   WITH_OPENCL               : OFF
--   WITH_TESTING              : OFF
--   WITH_ASCEND               : OFF
--   WITH_DIRECTML             : OFF
--   WITH_TIMVX                : OFF
--   WITH_KUNLUNXIN            : OFF
--   WITH_CAPI                 : OFF
--   WITH_CSHARPAPI            : OFF
--   ONNXRuntime version       : 
--   Paddle Inference version  : 2.5.0.558ae9cd11
--   PADDLE_WITH_ENCRYPT       : OFF
--   PADDLE_WITH_AUTH          : OFF
--   OpenVINO version          : dev.2023.03.2
--   CUDA_DIRECTORY            : /usr/local/cuda
--   TRT_DRECTORY              : 
--   DEPENDENCY_LIBS           : /home/chenzhen/work-code/Paddle/FastDeploy/build/compiled_fastdeploy_sdk/lib/libfastdeploy.so;/home/chenzhen/dev-file/deploy-file/onnxruntime-linux-x64-1.12.0/lib/libonnxruntime.so;/home/chenzhen/work-code/Paddle/FastDeploy/build/compiled_fastdeploy_sdk/third_libs/install/paddle_inference/paddle/lib/libpaddle_inference.so;/home/chenzhen/work-code/Paddle/FastDeploy/build/compiled_fastdeploy_sdk/third_libs/install/paddle_inference/third_party/install/mkldnn/lib/libmkldnn.so.0;/home/chenzhen/work-code/Paddle/FastDeploy/build/compiled_fastdeploy_sdk/third_libs/install/paddle_inference/third_party/install/mklml/lib/libiomp5.so;/home/chenzhen/work-code/Paddle/FastDeploy/build/compiled_fastdeploy_sdk/third_libs/install/openvino/runtime/lib/libopenvino.so;TBB::tbb;TBB::tbbmalloc;TBB::tbbmalloc_proxy;/usr/local/cuda/lib64/libcudart.so;/usr/local/cuda/lib64/libnvjpeg.so;/home/chenzhen/work-code/Paddle/FastDeploy/build/compiled_fastdeploy_sdk/third_libs/install/tensorrt/lib/libnvinfer.so;/home/chenzhen/work-code/Paddle/FastDeploy/build/compiled_fastdeploy_sdk/third_libs/install/tensorrt/lib/libnvonnxparser.so;/home/chenzhen/work-code/Paddle/FastDeploy/build/compiled_fastdeploy_sdk/third_libs/install/tensorrt/lib/libnvinfer_plugin.so;opencv_calib3d;opencv_core;opencv_dnn;opencv_features2d;opencv_flann;opencv_highgui;opencv_imgcodecs;opencv_imgproc;opencv_ml;opencv_objdetect;opencv_photo;opencv_shape;opencv_stitching;opencv_superres;opencv_video;opencv_videoio;opencv_videostab;opencv_aruco;opencv_bgsegm;opencv_bioinspired;opencv_ccalib;opencv_datasets;opencv_dnn_objdetect;opencv_dnn_superres;opencv_dpm;opencv_face;opencv_freetype;opencv_fuzzy;opencv_hdf;opencv_hfs;opencv_img_hash;opencv_line_descriptor;opencv_optflow;opencv_phase_unwrapping;opencv_plot;opencv_quality;opencv_reg;opencv_rgbd;opencv_saliency;opencv_stereo;opencv_structured_light;opencv_surface_matching;opencv_text;opencv_tracking;opencv_viz;opencv_ximgproc;opencv_xobjdetect;opencv_xphoto;/home/chenzhen/work-code/Paddle/FastDeploy/build/compiled_fastdeploy_sdk/third_libs/install/fast_tokenizer/lib/libcore_tokenizers.so;/home/chenzhen/work-code/Paddle/FastDeploy/build/compiled_fastdeploy_sdk/third_libs/install/paddle2onnx/lib/libpaddle2onnx.so
-- Configuring done
-- Generating done

**Comment by rainyfly** [comment]
检查一下有没有libonnxruntime.so.1.12.0这个so存在

**Comment by chlg** [comment]
> ## 环境
> * 【FastDeploy版本】： 自行编译环境
> * 【编译命令】cmake .. -DENABLE_ORT_BACKEND=ON 
>   -DENABLE_PADDLE_BACKEND=ON 
>   -DENABLE_OPENVINO_BACKEND=ON 
>   -DENABLE_TRT_BACKEND=ON 
>   -DWITH_GPU=ON 
>   -DTRT_DIRECTORY=/home/xx/dev-file/deploy-file/TensorRT-8.6.0.12 
>   -DCUDA_DIRECTORY=/usr/local/cuda-11.8 
>   -DCMAKE_INSTALL_PREFIX=${PWD}/compiled_fastdeploy_sdk 
>   -DENABLE_VISION=ON 
>   -DOPENCV_DIRECTORY=/usr/lib/x86_64-linux-gnu/cmake/opencv4 
>   -DORT_DIRECTORY=/home/xx/dev-file/deploy-file/onnxruntime-linux-x64-1.12.0 
>   -DENABLE_TEXT=ON
> * 【系统平台】: Linux x64(Ubuntu 20.04)
> * 【硬件】：  Nvidia GPU 3070， CUDA 11.8 CUDNN 8.6
> * 【编译语言】： C++
> 
> 编译正常进行，但运行demo提示：error while loading shared libraries: libonnxruntime.so.1.12.0: cannot open shared object file: No such file or directory
> 
> ## CMakeLists结果:
> -- Found OpenCV: /home/chenzhen/dev-file/fastdeploy-linux-x64-gpu-1.0.7/third_libs/install/opencv (found version "3.4.16")
> -- The path of ONNXRuntime is /home/chenzhen/dev-file/deploy-file/onnxruntime-linux-x64-1.12.0/lib.
> -- OPENVINO_LIBS = /home/chenzhen/work-code/Paddle/FastDeploy/build/compiled_fastdeploy_sdk/third_libs/install/openvino/runtime/lib/libopenvino.so;TBB::tbb;TBB::tbbmalloc;TBB::tbbmalloc_proxy
> -- The path of OpenCV is /usr/lib/x86_64-linux-gnu/cmake/opencv4.
> -- Found OpenCV: /usr (found version "4.2.0")
> ## -- *****FastDeploy Building Summary**
> -- CMake version : 3.24.2
> -- CMake command : /home/chenzhen/dev-file/clion-2022.3.3/bin/cmake/linux/x64/bin/cmake
> -- System : Linux
> -- C++ compiler : /usr/bin/g++
> -- C++ standard : 11
> -- C++ cuda standard :
> -- C++ compiler version : 9.4.0
> -- CXX flags : -Wno-format
> -- EXE linker flags :
> -- Shared linker flags :
> -- Build type : Release
> -- Compile definitions : _GLIBCXX_USE_CXX11_ABI=1
> -- CMAKE_PREFIX_PATH :
> -- CMAKE_INSTALL_PREFIX : /usr/local
> -- CMAKE_MODULE_PATH :
> -- FastDeploy version : 0.0.0 -- ENABLE_ORT_BACKEND : ON -- ENABLE_RKNPU2_BACKEND : OFF -- ENABLE_HORIZON_BACKEND : OFF -- ENABLE_SOPHGO_BACKEND : OFF -- ENABLE_PADDLE_BACKEND : ON -- ENABLE_LITE_BACKEND : OFF -- ENABLE_POROS_BACKEND : OFF -- ENABLE_TRT_BACKEND : ON -- ENABLE_OPENVINO_BACKEND : ON -- ENABLE_TVM_BACKEND : OFF -- ENABLE_BENCHMARK : OFF -- ENABLE_VISION : ON -- ENABLE_TEXT : ON -- ENABLE_ENCRYPTION : OFF -- ENABLE_FLYCV : OFF -- ENABLE_CVCUDA : OFF -- WITH_GPU : ON -- WITH_IPU : OFF -- WITH_OPENCL : OFF -- WITH_TESTING : OFF -- WITH_ASCEND : OFF -- WITH_DIRECTML : OFF -- WITH_TIMVX : OFF -- WITH_KUNLUNXIN : OFF -- WITH_CAPI : OFF -- WITH_CSHARPAPI : OFF -- ONNXRuntime version : -- Paddle Inference version : 2.5.0.558ae9cd11 -- PADDLE_WITH_ENCRYPT : OFF -- PADDLE_WITH_AUTH : OFF -- OpenVINO version : dev.2023.03.2 -- CUDA_DIRECTORY : /usr/local/cuda -- TRT_DRECTORY : -- DEPENDENCY_LIBS : /home/chenzhen/work-code/Paddle/FastDeploy/build/compiled_fastdeploy_sdk/lib/libfastdeploy.so;/home/chenzhen/dev-file/deploy-file/onnxruntime-linux-x64-1.12.0/lib/libonnxruntime.so;/home/chenzhen/work-code/Paddle/FastDeploy/build/compiled_fastdeploy_sdk/third_libs/install/paddle_inference/paddle/lib/libpaddle_inference.so;/home/chenzhen/work-code/Paddle/FastDeploy/build/compiled_fastdeploy_sdk/third_libs/install/paddle_inference/third_party/install/mkldnn/lib/libmkldnn.so.0;/home/chenzhen/work-code/Paddle/FastDeploy/build/compiled_fastdeploy_sdk/third_libs/install/paddle_inference/third_party/install/mklml/lib/libiomp5.so;/home/chenzhen/work-code/Paddle/FastDeploy/build/compiled_fastdeploy_sdk/third_libs/install/openvino/runtime/lib/libopenvino.so;TBB::tbb;TBB::tbbmalloc;TBB::tbbmalloc_proxy;/usr/local/cuda/lib64/libcudart.so;/usr/local/cuda/lib64/libnvjpeg.so;/home/chenzhen/work-code/Paddle/FastDeploy/build/compiled_fastdeploy_sdk/third_libs/install/tensorrt/lib/libnvinfer.so;/home/chenzhen/work-code/Paddle/FastDeploy/build/compiled_fastdeploy_sdk/third_libs/install/tensorrt/lib/libnvonnxparser.so;/home/chenzhen/work-code/Paddle/FastDeploy/build/compiled_fastdeploy_sdk/third_libs/install/tensorrt/lib/libnvinfer_plugin.so;opencv_calib3d;opencv_core;opencv_dnn;opencv_features2d;opencv_flann;opencv_highgui;opencv_imgcodecs;opencv_imgproc;opencv_ml;opencv_objdetect;opencv_photo;opencv_shape;opencv_stitching;opencv_superres;opencv_video;opencv_videoio;opencv_videostab;opencv_aruco;opencv_bgsegm;opencv_bioinspired;opencv_ccalib;opencv_datasets;opencv_dnn_objdetect;opencv_dnn_superres;opencv_dpm;opencv_face;opencv_freetype;opencv_fuzzy;opencv_hdf;opencv_hfs;opencv_img_hash;opencv_line_descriptor;opencv_optflow;opencv_phase_unwrapping;opencv_plot;opencv_quality;opencv_reg;opencv_rgbd;opencv_saliency;opencv_stereo;opencv_structured_light;opencv_surface_matching;opencv_text;opencv_tracking;opencv_viz;opencv_ximgproc;opencv_xobjdetect;opencv_xphoto;/home/chenzhen/work-code/Paddle/FastDeploy/build/compiled_fastdeploy_sdk/third_libs/install/fast_tokenizer/lib/libcore_tokenizers.so;/home/chenzhen/work-code/Paddle/FastDeploy/build/compiled_fastdeploy_sdk/third_libs/install/paddle2onnx/lib/libpaddle2onnx.so -- Configuring done -- Generating done

我也遇到了同样的问题  请问下 你解决了吗？

**Comment by vivienness** [comment]
> > ## 环境
> > 
> > * 【FastDeploy版本】： 自行编译环境
> > * 【编译命令】cmake .. -DENABLE_ORT_BACKEND=ON
> >   -DENABLE_PADDLE_BACKEND=ON
> >   -DENABLE_OPENVINO_BACKEND=ON
> >   -DENABLE_TRT_BACKEND=ON
> >   -DWITH_GPU=ON
> >   -DTRT_DIRECTORY=/home/xx/dev-file/deploy-file/TensorRT-8.6.0.12
> >   -DCUDA_DIRECTORY=/usr/local/cuda-11.8
> >   -DCMAKE_INSTALL_PREFIX=${PWD}/compiled_fastdeploy_sdk
> >   -DENABLE_VISION=ON
> >   -DOPENCV_DIRECTORY=/usr/lib/x86_64-linux-gnu/cmake/opencv4
> >   -DORT_DIRECTORY=/home/xx/dev-file/deploy-file/onnxruntime-linux-x64-1.12.0
> >   -DENABLE_TEXT=ON
> > * 【系统平台】: Linux x64(Ubuntu 20.04)
> > * 【硬件】：  Nvidia GPU 3070， CUDA 11.8 CUDNN 8.6
> > * 【编译语言】： C++
> > 
> > 编译正常进行，但运行demo提示：error while loading shared libraries: libonnxruntime.so.1.12.0: cannot open shared object file: No such file or directory
> > ## CMakeLists结果:
> > -- Found OpenCV: /home/chenzhen/dev-file/fastdeploy-linux-x64-gpu-1.0.7/third_libs/install/opencv (found version "3.4.16")
> > -- The path of ONNXRuntime is /home/chenzhen/dev-file/deploy-file/onnxruntime-linux-x64-1.12.0/lib.
> > -- OPENVINO_LIBS = /home/chenzhen/work-code/Paddle/FastDeploy/build/compiled_fastdeploy_sdk/third_libs/install/openvino/runtime/lib/libopenvino.so;TBB::tbb;TBB::tbbmalloc;TBB::tbbmalloc_proxy
> > -- The path of OpenCV is /usr/lib/x86_64-linux-gnu/cmake/opencv4.
> > -- Found OpenCV: /usr (found version "4.2.0")
> > ## -- *****FastDeploy Building Summary**
> > -- CMake version : 3.24.2
> > -- CMake command : /home/chenzhen/dev-file/clion-2022.3.3/bin/cmake/linux/x64/bin/cmake
> > -- System : Linux
> > -- C++ compiler : /usr/bin/g++
> > -- C++ standard : 11
> > -- C++ cuda standard :
> > -- C++ compiler version : 9.4.0
> > -- CXX flags : -Wno-format
> > -- EXE linker flags :
> > -- Shared linker flags :
> > -- Build type : Release
> > -- Compile definitions : _GLIBCXX_USE_CXX11_ABI=1
> > -- CMAKE_PREFIX_PATH :
> > -- CMAKE_INSTALL_PREFIX : /usr/local
> > -- CMAKE_MODULE_PATH :
> > -- FastDeploy version : 0.0.0 -- ENABLE_ORT_BACKEND : ON -- ENABLE_RKNPU2_BACKEND : OFF -- ENABLE_HORIZON_BACKEND : OFF -- ENABLE_SOPHGO_BACKEND : OFF -- ENABLE_PADDLE_BACKEND : ON -- ENABLE_LITE_BACKEND : OFF -- ENABLE_POROS_BACKEND : OFF -- ENABLE_TRT_BACKEND : ON -- ENABLE_OPENVINO_BACKEND : ON -- ENABLE_TVM_BACKEND : OFF -- ENABLE_BENCHMARK : OFF -- ENABLE_VISION : ON -- ENABLE_TEXT : ON -- ENABLE_ENCRYPTION : OFF -- ENABLE_FLYCV : OFF -- ENABLE_CVCUDA : OFF -- WITH_GPU : ON -- WITH_IPU : OFF -- WITH_OPENCL : OFF -- WITH_TESTING : OFF -- WITH_ASCEND : OFF -- WITH_DIRECTML : OFF -- WITH_TIMVX : OFF -- WITH_KUNLUNXIN : OFF -- WITH_CAPI : OFF -- WITH_CSHARPAPI : OFF -- ONNXRuntime version : -- Paddle Inference version : 2.5.0.558ae9cd11 -- PADDLE_WITH_ENCRYPT : OFF -- PADDLE_WITH_AUTH : OFF -- OpenVINO version : dev.2023.03.2 -- CUDA_DIRECTORY : /usr/local/cuda -- TRT_DRECTORY : -- DEPENDENCY_LIBS : /home/chenzhen/work-code/Paddle/FastDeploy/build/compiled_fastdeploy_sdk/lib/libfastdeploy.so;/home/chenzhen/dev-file/deploy-file/onnxruntime-linux-x64-1.12.0/lib/libonnxruntime.so;/home/chenzhen/work-code/Paddle/FastDeploy/build/compiled_fastdeploy_sdk/third_libs/install/paddle_inference/paddle/lib/libpaddle_inference.so;/home/chenzhen/work-code/Paddle/FastDeploy/build/compiled_fastdeploy_sdk/third_libs/install/paddle_inference/third_party/install/mkldnn/lib/libmkldnn.so.0;/home/chenzhen/work-code/Paddle/FastDeploy/build/compiled_fastdeploy_sdk/third_libs/install/paddle_inference/third_party/install/mklml/lib/libiomp5.so;/home/chenzhen/work-code/Paddle/FastDeploy/build/compiled_fastdeploy_sdk/third_libs/install/openvino/runtime/lib/libopenvino.so;TBB::tbb;TBB::tbbmalloc;TBB::tbbmalloc_proxy;/usr/local/cuda/lib64/libcudart.so;/usr/local/cuda/lib64/libnvjpeg.so;/home/chenzhen/work-code/Paddle/FastDeploy/build/compiled_fastdeploy_sdk/third_libs/install/tensorrt/lib/libnvinfer.so;/home/chenzhen/work-code/Paddle/FastDeploy/build/compiled_fastdeploy_sdk/third_libs/install/tensorrt/lib/libnvonnxparser.so;/home/chenzhen/work-code/Paddle/FastDeploy/build/compiled_fastdeploy_sdk/third_libs/install/tensorrt/lib/libnvinfer_plugin.so;opencv_calib3d;opencv_core;opencv_dnn;opencv_features2d;opencv_flann;opencv_highgui;opencv_imgcodecs;opencv_imgproc;opencv_ml;opencv_objdetect;opencv_photo;opencv_shape;opencv_stitching;opencv_superres;opencv_video;opencv_videoio;opencv_videostab;opencv_aruco;opencv_bgsegm;opencv_bioinspired;opencv_ccalib;opencv_datasets;opencv_dnn_objdetect;opencv_dnn_superres;opencv_dpm;opencv_face;opencv_freetype;opencv_fuzzy;opencv_hdf;opencv_hfs;opencv_img_hash;opencv_line_descriptor;opencv_optflow;opencv_phase_unwrapping;opencv_plot;opencv_quality;opencv_reg;opencv_rgbd;opencv_saliency;opencv_stereo;opencv_structured_light;opencv_surface_matching;opencv_text;opencv_tracking;opencv_viz;opencv_ximgproc;opencv_xobjdetect;opencv_xphoto;/home/chenzhen/work-code/Paddle/FastDeploy/build/compiled_fastdeploy_sdk/third_libs/install/fast_tokenizer/lib/libcore_tokenizers.so;/home/chenzhen/work-code/Paddle/FastDeploy/build/compiled_fastdeploy_sdk/third_libs/install/paddle2onnx/lib/libpaddle2onnx.so -- Configuring done -- Generating done
> 
> 我也遇到了同样的问题 请问下 你解决了吗？

我是在运行demo之前 source 了一下位于FastDeploy/build/compiled_fastdeploy_sdk/fastdeploy_init.sh 的文件就好了

**Comment by chlg** [comment]
确实有效 感谢

**Comment by chlg** [comment]
https://github.com/PaddlePaddle/FastDeploy/blob/develop/docs/cn/quick_start/models/cpp.md#linux--mac
这个文档也有说明
