### ISSUE TITLE
编译C# API 报错未能找到类型或命名空间名int64_t

### ISSUE THREAD

**Issue by liang-stu** [PaddlePaddle/FastDeploy#2094]
- 【编译命令】
cd FastDeploy-develop
mkdir build && cd build
cmake .. -G "Visual Studio 17 2022" -A x64 -DENABLE_ORT_BACKEND=ON -DENABLE_PADDLE_BACKEND=ON -DENABLE_OPENVINO_BACKEND=ON -DENABLE_VISION=ON -DENABLE_TEXT=ON -DWITH_CAPI=ON -DWITH_CSHARPAPI=ON -DCMAKE_INSTALL_PREFIX="D:\Paddle\compiled_fastdeploy"
nuget restore
msbuild Project.sln /m /p:Configuration=Release /p:Platform=x64
- 【系统平台】:  Windows x64(Windows10) cpu
- 【编译语言】：C#
执行 msbuild Project.sln /m /p:Configuration=Release /p:Platform=x64后：
- 【报错】：
       “C:\Users\xxl\Desktop\FastDeploy-develop\build\fastdeploy.sln”(默认目标) (1) ->
       “C:\Users\xxl\Desktop\FastDeploy-develop\build\ALL_BUILD.vcxproj.metaproj”(默认目标) (2) ->
       “C:\Users\xxl\Desktop\FastDeploy-develop\build\csharp\fastdeploy_csharp.csproj.metaproj”(默认目标) (11) ->
       “C:\Users\xxl\Desktop\FastDeploy-develop\build\csharp\fastdeploy_csharp.csproj”(默认目标) (16) ->
       (CoreCompile 目标) ->
         C:\Users\xxl\Desktop\FastDeploy-develop\csharp\fastdeploy\runtime_option.cs(113,16): error CS0246: 未能找到类 型或命名空
       间名“int64_t”(是否缺少 using 指令或程序集引用?) [C:\Users\xxl\Desktop\FastDeploy-develop\build\csharp\fastdeploy_csharp.cspro
       j]
         C:\Users\xxl\Desktop\FastDeploy-develop\csharp\fastdeploy\runtime_option.cs(113,24): error CS1750: 不能将“int”类型
       的值用作默认参数，因为没有到类型“int64_t”的标准转换 [C:\Users\xxl\Desktop\FastDeploy-develop\build\csharp\fastdeploy_csharp.csproj]

    1189 个警告
    2 个错误

**Comment by 903142301** [comment]
改成INT64

**Comment by liang-stu** [comment]
改为INT64，仍然报错：未能找到类型或命名空间。
将“int64_t”改为"long"，可以通过，能编译通过获得dll。

**Comment by 903142301** [comment]
Int64
