### ISSUE TITLE
链接失效，编译时，setup.py里的paddle2onnx包的链接失效了

### ISSUE THREAD

**Issue by LXXIANG12** [PaddlePaddle/FastDeploy#2107]
--- LOG END ---
         error: downloading 'https://bj.bcebos.com/fastdeploy/third_libs/paddle2onnx-linux-aarch64-1.0.8rc.tgz' failed
         status_code: 22
         status_string: "HTTP response code said error"

**Comment by leiqing1** [comment]
快速解决办法，
1. 自己下载一个paddle2onnx仓库下载一个或者编译一个。
2. 或者如果不需要paddle2onnx功能，可以修改编译脚本，注销这部分功能。

**Comment by jiangjiajun** [comment]
编译时打开BUILD_PADDLE2ONNX=ON

**Comment by LXXIANG12** [comment]
> 编译时打开BUILD_PADDLE2ONNX=ON

你好，编译时开启了这个选项，上个星期还能成功编译，但今天就不行了。因为编译脚本里的链接失效了https://bj.bcebos.com/fastdeploy/third_libs/paddle2onnx-linux-aarch64-1.0.8rc.tgz这是一个无效网址

**Comment by LXXIANG12** [comment]
> 快速解决办法，
> 
> 1. 自己下载一个paddle2onnx仓库下载一个或者编译一个。
> 2. 或者如果不需要paddle2onnx功能，可以修改编译脚本，注销这部分功能。

你好，我在jetson nano上部署，只支持paddle、onnxruntime部署方式，我尝试注销paddle2onnx后使用paddle推理，但编译paddle时报了另外一个错：Cannot compile with onnxruntime-gpu while in linux-aarch64 platform, fallback to onnxruntime-cpu
CMake Error at cmake/paddle_inference.cmake:57 (find_package):
  By not providing "FindPython.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "Python", but
  CMake did not find one.

  Could not find a package configuration file provided by "Python" with any
  of the following names:

    PythonConfig.cmake
    python-config.cmake

**Comment by LXXIANG12** [comment]
> 快速解决办法，
> 
> 1. 自己下载一个paddle2onnx仓库下载一个或者编译一个。
> 2. 或者如果不需要paddle2onnx功能，可以修改编译脚本，注销这部分功能。

同时，我尝试直接pip install paddle2onnx安装，即使成功安装依旧无法运行infer.py文件
(base) lx@lx-desktop:~/FastDeploy/python$ pip install paddle2onnx
Defaulting to user installation because normal site-packages is not writeable
Collecting paddle2onnx
  Using cached paddle2onnx-1.0.5-cp310-cp310-manylinux_2_27_aarch64.whl (2.8 MB)
Requirement already satisfied: six in /home/lx/.local/lib/python3.10/site-packages (from paddle2onnx) (1.16.0)
Installing collected packages: paddle2onnx
  WARNING: The script paddle2onnx is installed in '/home/lx/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
Successfully installed paddle2onnx-1.0.5

**Comment by jiangjiajun** [comment]
> > 编译时打开BUILD_PADDLE2ONNX=ON
> 
> 你好，编译时开启了这个选项，上个星期还能成功编译，但今天就不行了。因为编译脚本里的链接失效了[https://bj.bcebos.com/fastdeploy/third_libs/paddle2onnx-linux-aarch64-1.0.8rc.tgz这是一个无效网址](https://bj.bcebos.com/fastdeploy/third_libs/paddle2onnx-linux-aarch64-1.0.8rc.tgz%E8%BF%99%E6%98%AF%E4%B8%80%E4%B8%AA%E6%97%A0%E6%95%88%E7%BD%91%E5%9D%80)
编译时打开BUILD_PADDLE2ONNX=ON 就不会下载这个包，会从源码开始编译Paddle2ONNX。确认下编译开关是否打开吧

**Comment by elky98** [comment]
根据commit记录 如果不需要ort fp16支持的话 可以把 cmake/paddle2onnx.cmake 中的版本改为1.0.7

**Comment by LXXIANG12** [comment]
> > > 编译时打开BUILD_PADDLE2ONNX=ON
> > 
> > 
> > 你好，编译时开启了这个选项，上个星期还能成功编译，但今天就不行了。因为编译脚本里的链接失效了[https://bj.bcebos.com/fastdeploy/third_libs/paddle2onnx-linux-aarch64-1.0.8rc.tgz这是一个无效网址](https://bj.bcebos.com/fastdeploy/third_libs/paddle2onnx-linux-aarch64-1.0.8rc.tgz%E8%BF%99%E6%98%AF%E4%B8%80%E4%B8%AA%E6%97%A0%E6%95%88%E7%BD%91%E5%9D%80)
> > 编译时打开BUILD_PADDLE2ONNX=ON 就不会下载这个包，会从源码开始编译Paddle2ONNX。确认下编译开关是否打开吧

![image](https://github.com/PaddlePaddle/FastDeploy/assets/103343903/4d46767c-a8b7-4719-883b-55d52e0a30be)
按这个官方流程编译，依旧报错：
![image](https://github.com/PaddlePaddle/FastDeploy/assets/103343903/0cc87562-a1e1-4597-b0bb-09f6d8039237)
环境：gcc=7.3.1  jetpack=4.6.1   cmake=3.26.4   python=3.10.12

**Comment by jryxxx** [comment]
我有相同的问题，希望官方尽快解决，谢谢！

**Comment by LXXIANG12** [comment]
> 我有相同的问题，希望官方尽快解决，谢谢！

编译时只能用国内的ip，挂了梯子就会报这个错。如果关掉梯子仍不行，请重新克隆下这个项目，我是这样解决的。但后面报了新的错误

**Comment by jryxxx** [comment]
> > > > 编译时打开BUILD_PADDLE2ONNX=ON
> > > 
> > > 
> > > 你好，编译时开启了这个选项，上个星期还能成功编译，但今天就不行了。因为编译脚本里的链接失效了[https://bj.bcebos.com/fastdeploy/third_libs/paddle2onnx-linux-aarch64-1.0.8rc.tgz这是一个无效网址](https://bj.bcebos.com/fastdeploy/third_libs/paddle2onnx-linux-aarch64-1.0.8rc.tgz%E8%BF%99%E6%98%AF%E4%B8%80%E4%B8%AA%E6%97%A0%E6%95%88%E7%BD%91%E5%9D%80)
> > > 编译时打开BUILD_PADDLE2ONNX=ON 就不会下载这个包，会从源码开始编译Paddle2ONNX。确认下编译开关是否打开吧
> 
> ![image](https://user-images.githubusercontent.com/103343903/253475947-4d46767c-a8b7-4719-883b-55d52e0a30be.png) 按这个官方流程编译，依旧报错： ![image](https://user-images.githubusercontent.com/103343903/253476196-0cc87562-a1e1-4597-b0bb-09f6d8039237.png) 环境：gcc=7.3.1 jetpack=4.6.1 cmake=3.26.4 python=3.10.12

请问您找到解决方法了吗？我有和您一样的问题

> 

您后面这个问题我也遇到了，我是设置paddle2onnx=on,在make的时候遇到了这个问题

**Comment by LXXIANG12** [comment]
> > > > > 编译时打开BUILD_PADDLE2ONNX=ON
> > > > 
> > > > 
> > > > 你好，编译时开启了这个选项，上个星期还能成功编译，但今天就不行了。因为编译脚本里的链接失效了[https://bj.bcebos.com/fastdeploy/third_libs/paddle2onnx-linux-aarch64-1.0.8rc.tgz这是一个无效网址](https://bj.bcebos.com/fastdeploy/third_libs/paddle2onnx-linux-aarch64-1.0.8rc.tgz%E8%BF%99%E6%98%AF%E4%B8%80%E4%B8%AA%E6%97%A0%E6%95%88%E7%BD%91%E5%9D%80)
> > > > 编译时打开BUILD_PADDLE2ONNX=ON 就不会下载这个包，会从源码开始编译Paddle2ONNX。确认下编译开关是否打开吧
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/103343903/253475947-4d46767c-a8b7-4719-883b-55d52e0a30be.png) 按这个官方流程编译，依旧报错： ![image](https://user-images.githubusercontent.com/103343903/253476196-0cc87562-a1e1-4597-b0bb-09f6d8039237.png) 环境：gcc=7.3.1 jetpack=4.6.1 cmake=3.26.4 python=3.10.12
> 
> 请问您找到解决方法了吗？我有和您一样的问题
> 
> > 
> 
> 您后面这个问题我也遇到了，我是设置paddle2onnx=on,在make的时候遇到了这个问题

抱歉，我还没解决这个问题，你可以尝试下编译c++环境。两个星期前我在另一块jetson nano成功部署python环境，可能是官方更新了之后出现了bug吧。

**Comment by jryxxx** [comment]
> 

好的，我现在就是在编译c++环境，等等官方回复吧

**Comment by jiangjiajun** [comment]
@LXXIANG12 @Zxhhhjry 
拉一下这个PR的最新代码 https://github.com/PaddlePaddle/FastDeploy/pull/2112

编译时打开BUILD_PADDLE2ONNX=ON

**Comment by jryxxx** [comment]
> @LXXIANG12 @Zxhhhjry 拉一下这个PR的最新代码 #2112
> 
> 编译时打开BUILD_PADDLE2ONNX=ON

好的，我试一下

**Comment by LXXIANG12** [comment]
> > @LXXIANG12 @Zxhhhjry 拉一下这个PR的最新代码 #2112
> > 编译时打开BUILD_PADDLE2ONNX=ON
> 
> 好的，我试一下

您好，请问您拉取最新代码后解决了吗？

**Comment by jryxxx** [comment]
> > > @LXXIANG12 @Zxhhhjry 拉一下这个PR的最新代码 #2112
> > > 编译时打开BUILD_PADDLE2ONNX=ON
> > 
> > 
> > 好的，我试一下
> 
> 您好，请问您拉取最新代码后解决了吗？

是的，请稍等我将我的处理方法发出来

**Comment by Zxhhhjry** [comment]
> > > > @LXXIANG12 @Zxhhhjry 拉一下这个PR的最新代码 #2112
> > > > 编译时打开BUILD_PADDLE2ONNX=ON
> > > 
> > > 
> > > 好的，我试一下
> > 
> > 
> > 您好，请问您拉取最新代码后解决了吗？
> 
![IMG_EE7B5A864F83-1](https://github.com/PaddlePaddle/FastDeploy/assets/64191196/0fb0a2e6-9d93-4c29-9d43-279f980bf853)

> 是的，请稍等我将我的处理方法发出来



> > > > @LXXIANG12 @Zxhhhjry 拉一下这个PR的最新代码 #2112
> > > > 编译时打开BUILD_PADDLE2ONNX=ON
> > > 
> > > 
> > > 好的，我试一下
> > 
> > 
> > 您好，请问您拉取最新代码后解决了吗？
> 
> 是的，请稍等我将我的处理方法发出来，编译时打开BUILD_PADDLE2ONNX=ON
![IMG_EE7B5A864F83-1](https://github.com/PaddlePaddle/FastDeploy/assets/64191196/63397f91-14b2-47c6-a507-4f3882035d3f)
请将此处的源码下载下来并编译，

**Comment by jryxxx** [comment]
> ![IMG_EE7B5A864F83-1](https://user-images.githubusercontent.com/64191196/253569743-63397f91-14b2-47c6-a507-4f3882035d3f.jpeg)
> 请将此处的源码下载下来并编译，编译时打开BUILD_PADDLE2ONNX=ON

@LXXIANG12

**Comment by jryxxx** [comment]
> @LXXIANG12 @Zxhhhjry 拉一下这个PR的最新代码 #2112
> 
> 编译时打开BUILD_PADDLE2ONNX=ON

我在kylin上编译时，出现了这个警告，请问aarch64上不支持onnxruntime-gpu吗？
![image](https://github.com/PaddlePaddle/FastDeploy/assets/64191196/41b4b696-6921-4527-85a8-1ded5c4d29cf)
我按照这个步骤编译下来，在运行官方例子时，又遇到了另一个问题，我也检查了确实没有生成这个文件。
![image](https://github.com/PaddlePaddle/FastDeploy/assets/64191196/667e436c-0ab0-4da6-8f1a-64f25ee78b5a)
谢谢！

**Comment by jiangjiajun** [comment]
有source /path/to/fastdeploy_SDK/fastdeploy_init.sh吗， 这个会将库路径导入到LD_LIBRARY_PATH

**Comment by jryxxx** [comment]
> 有source /path/to/fastdeploy_SDK/fastdeploy_init.sh吗， 这个会将库路径导入到LD_LIBRARY_PATH

感谢您的回复，第二个问题我已经解决。请问第一个问题是个什么情况呢？

**Comment by jiangjiajun** [comment]
aarch64上不支持onnxruntime-gpu（原因在于onnxruntime并没有release出支持jetson的gpu C++包）。

如果你自行编译了onnxrntime-gpu在aarch64的包，可以通过编译时的ORT_DIRECTORY来指定自定义的库路径。

**Comment by jryxxx** [comment]
> aarch64上不支持onnxruntime-gpu（原因在于onnxruntime并没有release出支持jetson的gpu C++包）。
> 
> 如果你自行编译了onnxrntime-gpu在aarch64的包，可以通过编译时的ORT_DIRECTORY来指定自定义的库路径。

好的，感谢您的回复！

**Comment by jryxxx** [comment]
> > aarch64上不支持onnxruntime-gpu（原因在于onnxruntime并没有release出支持jetson的gpu C++包）。
> > 如果你自行编译了onnxrntime-gpu在aarch64的包，可以通过编译时的ORT_DIRECTORY来指定自定义的库路径。
> 
> 好的，感谢您的回复！

您好，再打扰您了，请问你有在aarch64平台编译onnxruntime-gpu的相关参考吗？谢谢！

**Comment by Miller-em** [comment]
这个包的链接：https://bj.bcebos.com/fastdeploy/third_libs/paddle2onnx-linux-aarch64-1.0.8rc.tgz   失效了，有没有新的替代方法？

**Comment by jiangjiajun** [comment]
[](url)

> 这个包的链接：https://bj.bcebos.com/fastdeploy/third_libs/paddle2onnx-linux-aarch64-1.0.8rc.tgz 失效了，有没有新的替代方法？

编译时，打开编译开关 BUILD_PADDLE2ONNX=ON

**Comment by Miller-em** [comment]
感谢，已解决



> > 这个包的链接：https://bj.bcebos.com/fastdeploy/third_libs/paddle2onnx-linux-aarch64-1.0.8rc.tgz 失效了，有没有新的替代方法？
> 
> 编译时，打开编译开关 BUILD_PADDLE2ONNX=ON
