### ISSUE TITLE
MCFairMOT多类别目标追踪模型推理问题，识别效果差，检测框固定在图像左上角

### ISSUE THREAD

**Issue by kev1n77** [PaddlePaddle/FastDeploy#2115]
*********************************************
MCFairMOT多类别目标追踪模型推理问题
*********************************************

## 环境

- 【FastDeploy版本】： develop
- 【系统平台】: Windows x64(Windows10)
- 【硬件】： Nvidia GPU 1050TI， CUDA 11.2 CUDNN 8.2
- 【编译语言】： Python(3.8）

## 问题日志及出现问题的操作流程
推理MCFairMOT模型只能识别一两个目标，而且检测框的左上角会固定在图像左上角。
确定模型没有问题，使用PaddleDetection的推理代码结果是正常的。

**Comment by kev1n77** [comment]
已解决，是训练与推理的paddle版本不一致导致的。训练在aistudio上，用的是2.3的版本，推理在本地用的2.4

**Comment by jack00000** [comment]
fastdeploy怎么跑FairMot目标追踪模型   下面的报错是表示不支持吗？
[ERROR] fastdeploy/vision/detection/ppdet/preprocessor.cc(113)::BuildPreprocessPipelineFromConfig	Unexcepted preprocess operator: LetterBoxResize.
[ERROR] fastdeploy/vision/detection/ppdet/preprocessor.cc(28)::PaddleDetPreprocessor	Failed to create PaddleDetPreprocessor.

**Comment by kev1n77** [comment]
> fastdeploy怎么跑FairMot目标追踪模型 下面的报错是表示不支持吗？ [ERROR] fastdeploy/vision/detection/ppdet/preprocessor.cc(113)::BuildPreprocessPipelineFromConfig Unexcepted preprocess operator: LetterBoxResize. [ERROR] fastdeploy/vision/detection/ppdet/preprocessor.cc(28)::PaddleDetPreprocessor Failed to create PaddleDetPreprocessor.

抱歉朋友，这个报错我不太清楚。fastdeploy是可以跑fairMot模型的，具体可以看项目主页列的文档。如果本地跑不起来，可以先上百度的aistudio上试试看，上面环境是配置好的，自己装一下模型就行
