### ISSUE TITLE
PP-MobileSeg使用FastDeploy部署问题

### ISSUE THREAD

**Issue by ashe2333** [PaddlePaddle/FastDeploy#2117]
- 【FastDeploy版本】： 说明具体的版本，如fastdeploy-window-cpu-1.0.7
- 【编译命令】如果您是自行编译的FastDeploy，请说明您的编译方式（参数命令）
- 【系统平台】: Windows x64(Windows10) 
- 【硬件】： cpu
- 【编译语言】： python3.9

## 问题日志及出现问题的操作流程
- 附上详细的问题日志有助于快速定位分析
- 【模型跑不通】
    PP-MobileSeg 训练完导出的模型使用下面代码运行报错：
  ```
    model = fd.vision.segmentation.PaddleSegModel(
    "model.pdmodel", "model.pdiparams", "deploy.yaml", runtime_option=option)
    im = cv2.imread("1.jpg")
    result = model.predict(im)
    print(result)
 报错：
```
RuntimeError: Check 'false' failed at C:\Jenkins\workspace\private-ci\ie\build-windows-vs2019\b\repos\openvino\src\frontends\paddle\src\frontend.cpp:60:
FrontEnd API failed with OpConversionFailure: :
Fail to convert linear_interp_v2 Exception Check 'scale.size() > 0 && scale.size() <= scale_size' failed at C:\Jenkins\workspace\private-ci\ie\build-windows-vs2019\b\repos\openvino\src\frontends\paddle\src\op\interp.cpp:19:
FrontEnd API failed with GeneralFailure: 
```


- 【直接使用PP-MobileSeg 导出的模型】
   直接使用PP-MobileSeg 导出的模型运行报错：
  ```
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site- 
  packages\fastdeploy\vision\segmentation\ppseg\__init__.py", line 40, in __init__
   self._model = C.vision.segmentation.PaddleSegModel(RuntimeError: Check 'm_fw_ptr->ParseFromIstream(streams[0])' failed at 
   C:\Jenkins\workspace\private-ci\ie\build-windows-vs2019\b\repos\openvino\src\frontends\paddle\src\input_model.cpp:342:
  FrontEnd API failed with GeneralFailure: :
  Model can't be parsed
  ```

- 【直接使用PP-MobileSeg 导出的模型】
 ```
model = fd.vision.matting.PPMatting(
    "model.pdmodel", "model.pdiparams", "deploy.yaml", runtime_option=option)

```
可得到MattingResult，正常运行，但和预期不符合

**Comment by jiangjiajun** [comment]
看起来是跑cpu openvino时，不支持。可以在初始化`PaddleSegModel`时前，配置runtime_option，例如
```
 option.use_paddle_infer_backend()
  model = fd.vision.segmentation.PaddleSegModel(
  "model.pdmodel", "model.pdiparams", "deploy.yaml", runtime_option=option)
  im = cv2.imread("1.jpg")
  result = model.predict(im)
  print(result)
```

**Comment by ashe2333** [comment]
好的，已经可以正常推理了，谢谢。
