### ISSUE TITLE
咨询PaddleOCR在RKNPU2上的量化精度

### ISSUE THREAD

**Issue by XiaotaoChen** [PaddlePaddle/FastDeploy#2121]
1. 我们测试 [PaddleOCR模型](https://github.com/PaddlePaddle/FastDeploy/blob/develop/examples/vision/ocr/PP-OCR/rockchip/README.md#paddleocr-%E6%A8%A1%E5%9E%8B%E5%9C%A8rknpu2%E4%B8%8A%E9%83%A8%E7%BD%B2%E6%96%B9%E6%A1%88-fastdeploy) 发现只有fp16的模型，并没有int8模型，想了解一下模型在int8量化情况的精度问题，望分享。
2. 我们想在端侧NPU上尝试部署OCR算法，但不知是否可行，所以想了解业界相关ocr量化精度，确定可行性。

**Comment by xuxiaolon** [comment]
英文的量化精度还比较ok，中文的非常差。
