### ISSUE TITLE
有考虑 Rust 吗

### ISSUE THREAD

**Issue by monkeycc** [PaddlePaddle/FastDeploy#2126]
高性能
低资源占用
可以部署在 桌面端   WebAssembly   嵌入式开发板  服务器
服务器合适大规模并发推理

有深度学习的框架示例等等
https://github.com/LaurentMazare/tch-rs
https://github.com/burn-rs/burn

https://github.com/pykeio/ort
https://github.com/microsoft/onnxruntime/tree/main/rust

WebAssembly   演示
https://burn-rs.github.io/demo

Rust paddle_inference库  是对百度飞浆推理库C接口的封装
https://docs.rs/paddle_inference/latest/paddle_inference
https://github.com/ZB94/paddle_inference

**Comment by leiqing1** [comment]
@monkeycc 主用应用场景的需求在哪些地方呢？

**Comment by monkeycc** [comment]
主要是客户端和网页端

主要是用来推理的
客户端要打包给客户安装
网页端直接上传图检测


客户端
比Python有优势
1.打包方便, Python全家桶都要打包,还有一系列的问题
2.Python伪多线程,多进程耗资源

网页端
直接可以部署为 WebAssembly
GUI框架 和 网页端 客户端 全通用

Rust WEB API传递速度 也比python快
Python的Serving  部署多费劲 麻烦

嵌入式开发板部署
Rust可以搞定

安卓开发现在也支持Rust

一个Rust   跨平台
可以搞定 客户端 网页端 嵌入式 APP这些
完全通用  速度又快 
没有C++的内存安全问题 C++的臃肿问题

既然Rust可以全方面的部署起来  速度又快  体积又小
Rust完全是可以考虑的

只需要Rust调用FastDeploy C接口的封装就行了
@leiqing1

**Comment by monkeycc** [comment]
https://github.com/PaddlePaddle/FastDeploy/tree/develop/examples/application/rust
