### ISSUE TITLE
FastDeploy是否支持在华为昇腾Atlas 200I DK A2开发板上的编译与模型推理部署

### ISSUE THREAD

**Issue by MrMzl** [PaddlePaddle/FastDeploy#2127]
FastDeploy是否支持板端编译部署FastDeploy？
我这边在编译过程中直接会在编译到26%多的时候卡住，不报错也不会停止编译，查看板端CPU使用情况，依然是正在占用中。
(base) root@davinci-mini:/home/data/FastDeploy-develop/build# cmake .. -DWITH_ASCEND=ON -DCMAKE_INSTALL_PREFIX=fastdeploy-ascend -DENABLE_VISION=ON
-- The C compiler identification is GNU 12.1.0
-- The CXX compiler identification is GNU 12.1.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
Downloading file from https://bj.bcebos.com/fastdeploy/third_libs/patchelf-0.15.0-aarch64.tar.gz to /home/data/FastDeploy-develop/build/patchelf-0.15.0-aarch64.tar.gz ...
-- [download 1% complete]
-- [download 6% complete]
-- [download 11% complete]
-- [download 16% complete]
-- [download 21% complete]
-- [download 27% complete]
-- [download 32% complete]
-- [download 37% complete]
-- [download 42% complete]
-- [download 47% complete]
-- [download 52% complete]
-- [download 57% complete]
-- [download 63% complete]
-- [download 68% complete]
-- [download 73% complete]
-- [download 78% complete]
-- [download 83% complete]
-- [download 88% complete]
-- [download 93% complete]
-- [download 98% complete]
-- [download 100% complete]
Decompress file /home/data/FastDeploy-develop/build/patchelf-0.15.0-aarch64.tar.gz ...
-- Build FastDeploy Ascend C++ library on aarch64 platform.
-- Use the default OpenCV lib from: https://bj.bcebos.com/paddle2onnx/libs/opencv-linux-aarch64-3.4.14.tgz
Downloading file from https://bj.bcebos.com/paddle2onnx/libs/opencv-linux-aarch64-3.4.14.tgz to /home/data/FastDeploy-develop/build/opencv-linux-aarch64-3.4.14.tgz ...
-- [download 0% complete]
-- [download 1% complete]
-- [download 2% complete]
-- [download 3% complete]
-- [download 4% complete]
-- [download 5% complete]
-- [download 6% complete]
-- [download 7% complete]
-- [download 8% complete]
-- [download 9% complete]
-- [download 10% complete]
-- [download 11% complete]
-- [download 12% complete]
-- [download 13% complete]
-- [download 14% complete]
-- [download 15% complete]
-- [download 16% complete]
-- [download 17% complete]
-- [download 18% complete]
-- [download 19% complete]
-- [download 20% complete]
-- [download 21% complete]
-- [download 22% complete]
-- [download 23% complete]
-- [download 24% complete]
-- [download 25% complete]
-- [download 26% complete]
-- [download 27% complete]
-- [download 28% complete]
-- [download 29% complete]
-- [download 30% complete]
-- [download 31% complete]
-- [download 32% complete]
-- [download 33% complete]
-- [download 34% complete]
-- [download 35% complete]
-- [download 36% complete]
-- [download 37% complete]
-- [download 38% complete]
-- [download 39% complete]
-- [download 40% complete]
-- [download 41% complete]
-- [download 42% complete]
-- [download 43% complete]
-- [download 44% complete]
-- [download 45% complete]
-- [download 46% complete]
-- [download 47% complete]
-- [download 48% complete]
-- [download 49% complete]
-- [download 50% complete]
-- [download 51% complete]
-- [download 52% complete]
-- [download 53% complete]
-- [download 54% complete]
-- [download 55% complete]
-- [download 56% complete]
-- [download 57% complete]
-- [download 58% complete]
-- [download 59% complete]
-- [download 60% complete]
-- [download 61% complete]
-- [download 62% complete]
-- [download 63% complete]
-- [download 64% complete]
-- [download 65% complete]
-- [download 66% complete]
-- [download 67% complete]
-- [download 68% complete]
-- [download 69% complete]
-- [download 70% complete]
-- [download 71% complete]
-- [download 72% complete]
-- [download 73% complete]
-- [download 74% complete]
-- [download 75% complete]
-- [download 76% complete]
-- [download 77% complete]
-- [download 78% complete]
-- [download 79% complete]
-- [download 80% complete]
-- [download 81% complete]
-- [download 82% complete]
-- [download 83% complete]
-- [download 84% complete]
-- [download 85% complete]
-- [download 86% complete]
-- [download 87% complete]
-- [download 88% complete]
-- [download 89% complete]
-- [download 90% complete]
-- [download 91% complete]
-- [download 92% complete]
-- [download 93% complete]
-- [download 94% complete]
-- [download 95% complete]
-- [download 96% complete]
-- [download 97% complete]
-- [download 98% complete]
-- [download 99% complete]
-- [download 100% complete]
Decompress file /home/data/FastDeploy-develop/build/opencv-linux-aarch64-3.4.14.tgz ...
-- Found OpenCV: /home/data/FastDeploy-develop/build/third_libs/install/opencv (found version "3.4.14")
--
-- *************FastDeploy Building Summary**********
--   CMake version             : 3.22.1
--   CMake command             : /usr/bin/cmake
--   System                    : Linux
--   C++ compiler              : /usr/bin/c++
--   C++ standard              : 11
--   C++ cuda standard         :
--   C++ compiler version      : 12.1.0
--   CXX flags                 : -Wno-format -g0 -O3
--   EXE linker flags          :
--   Shared linker flags       :
--   Build type                :
--   Compile definitions       : _GLIBCXX_USE_CXX11_ABI=1;FASTDEPLOY_LIB;CMAKE_BUILD_TYPE=Release;ENABLE_LITE_BACKEND;ENABLE_VISION
--   CMAKE_PREFIX_PATH         :
--   CMAKE_INSTALL_PREFIX      : /home/data/FastDeploy-develop/build/fastdeploy-ascend
--   CMAKE_MODULE_PATH         :
--
--   FastDeploy version        : 0.0.0
--   ENABLE_ORT_BACKEND        : OFF
--   ENABLE_RKNPU2_BACKEND     : OFF
--   ENABLE_HORIZON_BACKEND    : OFF
--   ENABLE_SOPHGO_BACKEND     : OFF
--   ENABLE_PADDLE_BACKEND     : OFF
--   ENABLE_LITE_BACKEND       : ON
--   ENABLE_POROS_BACKEND      : OFF
--   ENABLE_TRT_BACKEND        : OFF
--   ENABLE_OPENVINO_BACKEND   : OFF
--   ENABLE_TVM_BACKEND        : OFF
--   ENABLE_BENCHMARK          : OFF
--   ENABLE_VISION             : ON
--   ENABLE_TEXT               : OFF
--   ENABLE_ENCRYPTION         : OFF
--   ENABLE_FLYCV              : OFF
--   ENABLE_CVCUDA             : OFF
--   WITH_GPU                  : OFF
--   WITH_IPU                  : OFF
--   WITH_OPENCL               : OFF
--   WITH_TESTING              : OFF
--   WITH_ASCEND               : ON
--   WITH_DIRECTML             : OFF
--   WITH_TIMVX                : OFF
--   WITH_KUNLUNXIN            : OFF
--   WITH_CAPI                 : OFF
--   WITH_CSHARPAPI            : OFF
--   Paddle Lite version       :
-- Configuring done
-- Generating done
-- Build files have been written to: /home/data/FastDeploy-develop/build
(base) root@davinci-mini:/home/data/FastDeploy-develop/build# make -j8
[  0%] Creating directories for 'extern_paddlelite'
[  0%] Building CXX object third_party/yaml-cpp/CMakeFiles/yaml-cpp.dir/src/binary.cpp.o
[  1%] Building CXX object third_party/yaml-cpp/CMakeFiles/yaml-cpp.dir/src/contrib/graphbuilder.cpp.o
[  1%] Building CXX object third_party/yaml-cpp/CMakeFiles/yaml-cpp.dir/src/contrib/graphbuilderadapter.cpp.o
[  2%] Building CXX object third_party/yaml-cpp/CMakeFiles/yaml-cpp.dir/src/convert.cpp.o
[  2%] Building CXX object third_party/yaml-cpp/CMakeFiles/yaml-cpp.dir/src/depthguard.cpp.o
[  3%] Building CXX object third_party/yaml-cpp/CMakeFiles/yaml-cpp.dir/src/directives.cpp.o
[  3%] Building CXX object third_party/yaml-cpp/CMakeFiles/yaml-cpp.dir/src/emit.cpp.o
[  3%] Performing download step (download, verify and extract) for 'extern_paddlelite'
-- Downloading...
   dst='/home/data/FastDeploy-develop/build/third_libs/paddlelite/src/FastDeploy.CPP.inference_lite_lib.ubuntu.armv8.huawei_ascend_npu.CANN5.1.RC2.alpha001.tar.gz'
   timeout='none'
   inactivity timeout='none'
-- Using src='https://paddle-qa.bj.bcebos.com/Paddle-Lite/DevelopDailyBuild/FastDeploy.CPP.inference_lite_lib.ubuntu.armv8.huawei_ascend_npu.CANN5.1.RC2.alpha001.tar.gz'
[  3%] Building CXX object third_party/yaml-cpp/CMakeFiles/yaml-cpp.dir/src/emitfromevents.cpp.o
[  4%] Building CXX object third_party/yaml-cpp/CMakeFiles/yaml-cpp.dir/src/emitter.cpp.o
[  4%] Building CXX object third_party/yaml-cpp/CMakeFiles/yaml-cpp.dir/src/emitterstate.cpp.o
[  5%] Building CXX object third_party/yaml-cpp/CMakeFiles/yaml-cpp.dir/src/emitterutils.cpp.o
[  5%] Building CXX object third_party/yaml-cpp/CMakeFiles/yaml-cpp.dir/src/exceptions.cpp.o
[  5%] Building CXX object third_party/yaml-cpp/CMakeFiles/yaml-cpp.dir/src/exp.cpp.o
-- Downloading... done
-- extracting...
     src='/home/data/FastDeploy-develop/build/third_libs/paddlelite/src/FastDeploy.CPP.inference_lite_lib.ubuntu.armv8.huawei_ascend_npu.CANN5.1.RC2.alpha001.tar.gz'
     dst='/home/data/FastDeploy-develop/build/third_libs/paddlelite/src/extern_paddlelite'
-- extracting... [tar xfz]
[  6%] Building CXX object third_party/yaml-cpp/CMakeFiles/yaml-cpp.dir/src/memory.cpp.o
[  6%] Building CXX object third_party/yaml-cpp/CMakeFiles/yaml-cpp.dir/src/node.cpp.o
[  7%] Building CXX object third_party/yaml-cpp/CMakeFiles/yaml-cpp.dir/src/node_data.cpp.o
[  7%] Building CXX object third_party/yaml-cpp/CMakeFiles/yaml-cpp.dir/src/nodebuilder.cpp.o
[  7%] Building CXX object third_party/yaml-cpp/CMakeFiles/yaml-cpp.dir/src/nodeevents.cpp.o
[  8%] Building CXX object third_party/yaml-cpp/CMakeFiles/yaml-cpp.dir/src/null.cpp.o
[  8%] Building CXX object third_party/yaml-cpp/CMakeFiles/yaml-cpp.dir/src/ostream_wrapper.cpp.o
[  9%] Building CXX object third_party/yaml-cpp/CMakeFiles/yaml-cpp.dir/src/parse.cpp.o
[  9%] Building CXX object third_party/yaml-cpp/CMakeFiles/yaml-cpp.dir/src/parser.cpp.o
[ 10%] Building CXX object third_party/yaml-cpp/CMakeFiles/yaml-cpp.dir/src/scanner.cpp.o
[ 10%] Building CXX object third_party/yaml-cpp/CMakeFiles/yaml-cpp.dir/src/regex_yaml.cpp.o
[ 10%] Building CXX object third_party/yaml-cpp/CMakeFiles/yaml-cpp.dir/src/scanscalar.cpp.o
[ 11%] Building CXX object third_party/yaml-cpp/CMakeFiles/yaml-cpp.dir/src/scantag.cpp.o
-- extracting... [analysis]
-- extracting... [rename]
-- extracting... [clean up]
-- extracting... done
[ 11%] Building CXX object third_party/yaml-cpp/CMakeFiles/yaml-cpp.dir/src/scantoken.cpp.o
[ 11%] Building CXX object third_party/yaml-cpp/CMakeFiles/yaml-cpp.dir/src/simplekey.cpp.o
[ 12%] No update step for 'extern_paddlelite'
[ 12%] No patch step for 'extern_paddlelite'
[ 13%] No configure step for 'extern_paddlelite'
[ 14%] Building CXX object third_party/yaml-cpp/CMakeFiles/yaml-cpp.dir/src/singledocparser.cpp.o
[ 14%] No build step for 'extern_paddlelite'
[ 15%] Performing install step for 'extern_paddlelite'
[ 15%] Completed 'extern_paddlelite'
[ 15%] Built target extern_paddlelite
[ 15%] Building CXX object third_party/yaml-cpp/CMakeFiles/yaml-cpp.dir/src/stream.cpp.o
[ 16%] Building CXX object third_party/yaml-cpp/CMakeFiles/yaml-cpp.dir/src/tag.cpp.o
[ 16%] Linking CXX static library libyaml-cpp.a
[ 16%] Built target yaml-cpp
[ 16%] Building CXX object third_party/yaml-cpp/util/CMakeFiles/yaml-cpp-sandbox.dir/sandbox.cpp.o
[ 16%] Building CXX object third_party/yaml-cpp/util/CMakeFiles/yaml-cpp-read.dir/read.cpp.o
[ 16%] Building CXX object third_party/yaml-cpp/util/CMakeFiles/yaml-cpp-parse.dir/parse.cpp.o
[ 17%] Building CXX object CMakeFiles/fastdeploy.dir/fastdeploy/core/allocate.cc.o
[ 17%] Building CXX object CMakeFiles/fastdeploy.dir/fastdeploy/core/fd_type.cc.o
[ 17%] Building CXX object CMakeFiles/fastdeploy.dir/fastdeploy/benchmark/utils.cc.o
[ 17%] Building CXX object CMakeFiles/fastdeploy.dir/fastdeploy/core/fd_tensor.cc.o
[ 18%] Building CXX object CMakeFiles/fastdeploy.dir/fastdeploy/fastdeploy_model.cc.o
[ 18%] Building CXX object CMakeFiles/fastdeploy.dir/fastdeploy/function/cast.cc.o
[ 19%] Linking CXX executable parse
[ 19%] Built target yaml-cpp-parse
[ 20%] Building CXX object CMakeFiles/fastdeploy.dir/fastdeploy/function/clip.cc.o
[ 20%] Building CXX object CMakeFiles/fastdeploy.dir/fastdeploy/function/concat.cc.o
[ 21%] Linking CXX executable read
[ 22%] Linking CXX executable sandbox
[ 22%] Built target yaml-cpp-read
[ 22%] Building CXX object CMakeFiles/fastdeploy.dir/fastdeploy/function/cumprod.cc.o
[ 22%] Built target yaml-cpp-sandbox
[ 23%] Building CXX object CMakeFiles/fastdeploy.dir/fastdeploy/function/eigen.cc.o
[ 23%] Building CXX object CMakeFiles/fastdeploy.dir/fastdeploy/function/elementwise.cc.o
[ 24%] Building CXX object CMakeFiles/fastdeploy.dir/fastdeploy/function/full.cc.o
[ 24%] Building CXX object CMakeFiles/fastdeploy.dir/fastdeploy/function/gather_scatter_along_axis.cc.o
[ 24%] Building CXX object CMakeFiles/fastdeploy.dir/fastdeploy/function/gaussian_random.cc.o
[ 25%] Building CXX object CMakeFiles/fastdeploy.dir/fastdeploy/function/isfinite.cc.o
[ 25%] Building CXX object CMakeFiles/fastdeploy.dir/fastdeploy/function/linspace.cc.o
[ 26%] Building CXX object CMakeFiles/fastdeploy.dir/fastdeploy/function/math.cc.o
[ 26%] Building CXX object CMakeFiles/fastdeploy.dir/fastdeploy/function/pad.cc.o
[ 26%] Building CXX object CMakeFiles/fastdeploy.dir/fastdeploy/function/quantile.cc.o
[ 27%] Building CXX object CMakeFiles/fastdeploy.dir/fastdeploy/function/reduce.cc.o
[ 27%] Building CXX object CMakeFiles/fastdeploy.dir/fastdeploy/function/slice.cc.o
[ 28%] Building CXX object CMakeFiles/fastdeploy.dir/fastdeploy/function/softmax.cc.o
[ 28%] Building CXX object CMakeFiles/fastdeploy.dir/fastdeploy/function/sort.cc.o
[ 28%] Building CXX object CMakeFiles/fastdeploy.dir/fastdeploy/function/split.cc.o
^Cmake[2]: *** [CMakeFiles/fastdeploy.dir/build.make:216: CMakeFiles/fastdeploy.dir/fastdeploy/function/elementwise.cc.o] Interrupt
make[2]: *** [CMakeFiles/fastdeploy.dir/build.make:300: CMakeFiles/fastdeploy.dir/fastdeploy/function/math.cc.o] Interrupt
make[2]: *** [CMakeFiles/fastdeploy.dir/build.make:314: CMakeFiles/fastdeploy.dir/fastdeploy/function/pad.cc.o] Interrupt
make[2]: *** [CMakeFiles/fastdeploy.dir/build.make:342: CMakeFiles/fastdeploy.dir/fastdeploy/function/reduce.cc.o] Interrupt
make[2]: *** [CMakeFiles/fastdeploy.dir/build.make:356: CMakeFiles/fastdeploy.dir/fastdeploy/function/slice.cc.o] Interrupt
make[2]: *** [CMakeFiles/fastdeploy.dir/build.make:370: CMakeFiles/fastdeploy.dir/fastdeploy/function/softmax.cc.o] Interrupt
make[2]: *** [CMakeFiles/fastdeploy.dir/build.make:384: CMakeFiles/fastdeploy.dir/fastdeploy/function/sort.cc.o] Interrupt
make[2]: *** [CMakeFiles/fastdeploy.dir/build.make:398: CMakeFiles/fastdeploy.dir/fastdeploy/function/split.cc.o] Interrupt
make[1]: *** [CMakeFiles/Makefile2:195: CMakeFiles/fastdeploy.dir/all] Interrupt
make: *** [Makefile:156: all] Interrupt

(base) root@davinci-mini:/home/data/FastDeploy-develop/build#

**Comment by leiqing1** [comment]
FastDeploy中通过Paddle Lite后端支撑昇腾部署硬件。可以参考这篇文档重新编译https://github.com/PaddlePaddle/FastDeploy/blob/develop/docs/cn/build_and_install/huawei_ascend.md
