### ISSUE TITLE
日志怎么关闭

### ISSUE THREAD

**Issue by ericperfect** [PaddlePaddle/FastDeploy#2137]
I0726 16:11:18.357290 1111698 stats.h:78] HostMemoryStatAllocated0: Update current_value with -8, after update, current value = 469423112
uie预测时这种日志怎么取消掉

**Comment by rainyfly** [comment]
https://github.com/PaddlePaddle/FastDeploy/blob/llm/fastdeploy/utils/utils.h#L222 这个接口可以设置屏蔽掉info和warning信息
