### ISSUE TITLE
FP32、FP16、INT8速度测试

### ISSUE THREAD

**Issue by qinxianyuzi** [PaddlePaddle/FastDeploy#2147]
## 环境
- 【FastDeploy版本】： develop
- 【编译命令】cmake .. -DENABLE_PADDLE_BACKEND=ON -DENABLE_OPENVINO_BACKEND=ON -DENABLE_TRT_BACKEND=ON -DWITH_GPU=ON -DTRT_DIRECTORY=/home/huangry/project/TensorRT-8.6.1.6 -DCUDA_DIRECTORY=/usr/local/cuda -DCMAKE_INSTALL_PREFIX=/usr/local/compiled_fastdeploy_sdk -DENABLE_VISION=ON -DOPENCV_DIRECTORY=/usr/lib/x86_64-linux-gnu/cmake/opencv4 -DENABLE_TEXT=ON
- 【系统平台】: Linux x64(Ubuntu 22.04)
- 【硬件】：  Nvidia GPU 4090， CUDA 11.7 CUDNN 8.9
- 【编译语言】： C++

## 问题日志及出现问题的操作流程
- 【性能问题】使用下面代码测试FP32、FP16、INT8模型速度，FP32的时间为5200，FP16的时间为4600，INT8的时间为4550，差距很小，请问代码是否有问题？
****

> 

#include "fastdeploy/vision.h"
#include <chrono>
int main() 
{
  // FP32 及 FP16
  std::string model_file = "ppyoloe_plus_crn_s_80e_coco/model.pdmodel";
  std::string params_file = "ppyoloe_plus_crn_s_80e_coco/model.pdiparams";
  std::string infer_cfg_file = "ppyoloe_plus_crn_s_80e_coco/infer_cfg.yml";

  // // INT8
  // std::string model_file = "ppyoloe_plus_crn_s_80e_coco_qat/model.pdmodel";
  // std::string params_file = "ppyoloe_plus_crn_s_80e_coco_qat/model.pdiparams";
  // std::string infer_cfg_file = "ppyoloe_plus_crn_s_80e_coco_qat/infer_cfg.yml";
  // 模型推理的配置信息
  fastdeploy::RuntimeOption option;
  option.UseGpu();
  option.UseTrtBackend();
  option.EnableTrtFP16(); //FP16时开启
  // option.trt_option.serialize_file = "trt_serialized.trt";
  auto model = fastdeploy::vision::detection::PPYOLOE(model_file, params_file, infer_cfg_file, option);

  if(!model.Initialized()) // 判断模型是否初始化成功
  {
    std::cout << "Failed to initalize" << std::endl;
    return -1;
  }

  std::cout << "******************************************" << std::endl;

  cv::Mat im = cv::imread("test_det.jpg");
  fastdeploy::vision::DetectionResult result;
  
  if(!model.Predict(&im, &result)) // 判断是否预测成功
  {
    std::cout << "Failed to predict" << std::endl;
    return -1;
  }
  std::cout << result.Str() << std::endl;

  
  std::cout << "============================================" << std::endl;
  auto startTime = std::chrono::high_resolution_clock::now();
  int epo = 1000;
  while(epo-- > 0)
  {
    cv::Mat im = cv::imread("test_det.jpg");
    fastdeploy::vision::DetectionResult result;
    
    if (!model.Predict(&im, &result)) // 判断是否预测成功
    {
      std::cout << "Failed to predict" << std::endl;
      return -1;
    }
  }
  auto stopTime = std::chrono::high_resolution_clock::now();
  auto duration = std::chrono::duration_cast<std::chrono::microseconds>(stopTime - startTime);
  std::cout << "执行的时间为：" << duration.count() / 1000 << std::endl;

  return 0;
}

**Comment by rainyfly** [comment]
测试代码应该没啥问题
