### ISSUE TITLE
https://github.com/PaddlePaddle/FastDeploy/blob/develop/docs/en/build_and_install/huawei_ascend.md

### ISSUE THREAD

**Issue by ruijie123** [PaddlePaddle/FastDeploy#2150]
请问在华为鲲鹏中部署paddleocr的文档是没有呢，还是跳转出错呢https://github.com/PaddlePaddle/FastDeploy/blob/develop/docs/en/build_and_install/huawei_ascend.md

页面404
![image](https://github.com/PaddlePaddle/FastDeploy/assets/48897529/29924ec8-c580-41eb-b005-9a24a1f33eff)

**Comment by rainyfly** [comment]
https://github.com/PaddlePaddle/FastDeploy/blob/develop/examples/vision/ocr/PP-OCR/ascend/README.md  这个文档吧
