### ISSUE TITLE
C# Fastdeploy部署PaddleOCR 结果无法显示

### ISSUE THREAD

**Issue by chccc1994** [PaddlePaddle/FastDeploy#2152]
**版本：fastdeploy 1.0.7
硬件 :CPU**
1. 按照PaddleOCR c#部署教程链接：`https://github.com/PaddlePaddle/PaddleOCR/tree/dygraph/deploy/fastdeploy/cpu-gpu/csharp`，但是C#使用FastDeploy推理PaddleOCR的ch_PP-OCRv3模型不出结果.

**Comment by BigerPatax** [comment]
老哥  怎么解决的？
