### ISSUE TITLE
请问uiex有什么好的方法可以进行部署？

### ISSUE THREAD

**Issue by aixuedegege** [PaddlePaddle/FastDeploy#2155]

**Comment by aixuedegege** [comment]
fastdeploy 现在支持uiex了么

**Comment by neo502721** [comment]
好像没有啊我也在找

**Comment by aixuedegege** [comment]
可以跑的，导出模型后然后可以用fd进行load推理

**Comment by neo502721** [comment]
> 可以跑的，导出模型后然后可以用fd进行load推理

在哪里导出的

**Comment by aixuedegege** [comment]
使用paddle.jit.to_static导出：
```python
model = UIEX.from_pretrained(model_name_or_path)
model = paddle.jit.to_static(model, input_spec=input_spec)
paddle.jit.save(model, save_path)
```
input_spec用这里的：
(https://github.com/PaddlePaddle/PaddleNLP/blob/develop/paddlenlp/taskflow/information_extraction.py#L559)

上了triton部署之后你打算怎么调？

**Comment by neo502721** [comment]
> 使用paddle.jit.to_static导出：
> 
> ```python
> model = UIEX.from_pretrained(model_name_or_path)
> model = paddle.jit.to_static(model, input_spec=input_spec)
> paddle.jit.save(model, save_path)
> ```
> 
> input_spec用这里的： (https://github.com/PaddlePaddle/PaddleNLP/blob/develop/paddlenlp/taskflow/information_extraction.py#L559)
> 
> 上了triton部署之后你打算怎么调？

好的，多谢。我看了一些uiex的文档，好像还是kie方式性能要好一点。
https://blog.csdn.net/z5z5z5z56/article/details/130346646
