### ISSUE TITLE
鲲鹏ascend c++部署paddleocr make-j报错

### ISSUE THREAD

**Issue by ruijie123** [PaddlePaddle/FastDeploy#2159]
- 【FastDeploy版本】：![image](https://github.com/PaddlePaddle/FastDeploy/assets/48897529/37eb04c6-6884-46d6-801d-f023dcee0b79)
- 【系统平台】: Linux x64(Ubuntu 18.04)
- 【硬件】： 鲲鹏920，
![image](https://github.com/PaddlePaddle/PaddleOCR/assets/48897529/a1acbf23-5952-4153-898b-9df7ca6d4d81)
- 【编译语言】： C++ 
报错：
![image](https://github.com/PaddlePaddle/PaddleOCR/assets/48897529/5450de83-2fe4-454c-8509-9fafa019a026)
[ 50%] Building CXX object CMakeFiles/infer_demo.dir/infer.cc.o
/root/workspace/FastDeploy/examples/vision/ocr/PP-OCR/ascend/cpp/infer.cc: In function 'void AscendInfer(const string&, const string&, const string&, const string&, const string&, const fastdeploy::RuntimeOption&)':
/root/workspace/FastDeploy/examples/vision/ocr/PP-OCR/ascend/cpp/infer.cc:37:29: error: declaration of 'fastdeploy::RuntimeOption option' shadows a parameter
   fastdeploy::RuntimeOption option;
                             ^~~~~~
/root/workspace/FastDeploy/examples/vision/ocr/PP-OCR/ascend/cpp/infer.cc: In function 'int main(int, char**)':
/root/workspace/FastDeploy/examples/vision/ocr/PP-OCR/ascend/cpp/infer.cc:106:25: error: too few arguments to function 'void AscendInfer(const string&, const string&, const string&, const string&, const string&, const fastdeploy::RuntimeOption&)'
               test_image);
                         ^
/root/workspace/FastDeploy/examples/vision/ocr/PP-OCR/ascend/cpp/infer.cc:22:6: note: declared here
 void AscendInfer(const std::string &det_model_dir,
      ^~~~~~~~~~~
CMakeFiles/infer_demo.dir/build.make:65: recipe for target 'CMakeFiles/infer_demo.dir/infer.cc.o' failed
make[2]: *** [CMakeFiles/infer_demo.dir/infer.cc.o] Error 1
CMakeFiles/Makefile2:106: recipe for target 'CMakeFiles/infer_demo.dir/all' failed
make[1]: *** [CMakeFiles/infer_demo.dir/all] Error 2
Makefile:86: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by zaicyxu** [comment]
我也遇到了一模一样的错误，之后我又用python编译，发现报错原因是，"Paddle Backend doesn't support linux aarch64 now."也就是说目前paddle框架不再支持jetson的aarch64架构。

**Comment by mytk2012** [comment]
解决了吗
