### ISSUE TITLE
facedet和faceid咨询

### ISSUE THREAD

**Issue by AI-Mart** [PaddlePaddle/FastDeploy#216]
1、能否检测人脸的姿态角
2、能否做一个python和c++的检测和识别串起来的案例，比如输入一张图片，图片里面有多个人脸，能分别输出每个人脸的的坐标和每个人脸的向量，做一个整体的案例最大化的压缩预测的时间

**Comment by DefTruth** [comment]
1. 关于人脸姿态角的模型，后续会陆续集成进来，比如FSANet等
2. 关于模型串联，这个后续会添加一些案例，也很欢迎开发者来贡献案例哈

**Comment by AI-Mart** [comment]
感谢回复，因为涉及到批量的预测，这个串联的效率应该有很多的点需要考虑，可以集成以下

**Comment by jiangjiajun** [comment]
此ISSUE由于一年未更新，将会关闭处理，如有需要，可再次更新打开。
