### ISSUE TITLE
ascend 310 鲲鹏920部署报错

### ISSUE THREAD

**Issue by yywangfei** [PaddlePaddle/FastDeploy#2162]
*********************************************
温馨提示：根据社区不完全统计，按照模板提问，可以加快回复和解决问题的速度
*********************************************

## 环境

- 【FastDeploy版本】： fastdeploy-python  0.0.0
- 【编译命令】如果您是自行编译的FastDeploy，
- 【系统平台】: 银河麒麟sp3
- 【硬件】： ascend 310p
- 【编译语言】： Python(3.7）

## 问题日志及出现问题的操作流程
- 附上详细的问题日志有助于快速定位分析
- 【模型跑不通】
- - 先执行`examples`下的部署示例，包括使用examples提供的模型，确认是否可以正确执行
- - 如若`examples`下的代码可以运行，但自己的模型，或自己的代码不能运行
- - - 提供复现问题的 代码+模型+错误log，供工程师快速定位问题  

[W  8/14  7:57:37.535 .../src/driver/huawei_ascend_npu/utility.cc:57 InitializeAscendCL] CANN version mismatch. The build version is 0.0.0, but the current environment version is 5.1.2.
[I  8/14  7:57:37.578 ...r/src/driver/huawei_ascend_npu/engine.cc:41 Context] properties: 
[I  8/14  7:57:37.578 ...r/src/driver/huawei_ascend_npu/engine.cc:66 Context] selected device ids: 
[I  8/14  7:57:37.578 ...r/src/driver/huawei_ascend_npu/engine.cc:68 Context] 0
[I  8/14  7:57:37.578 ...r/src/driver/huawei_ascend_npu/engine.cc:78 Context] profiling path: 
[I  8/14  7:57:37.578 ...r/src/driver/huawei_ascend_npu/engine.cc:88 Context] dump model path: 
[I  8/14  7:57:37.578 ...r/src/driver/huawei_ascend_npu/engine.cc:98 Context] precision mode: 
[I  8/14  7:57:37.578 ...r/src/driver/huawei_ascend_npu/engine.cc:120 Context] op select impl mode: 
[I  8/14  7:57:37.578 ...r/src/driver/huawei_ascend_npu/engine.cc:130 Context] op type list for impl mode: 
[I  8/14  7:57:37.578 ...r/src/driver/huawei_ascend_npu/engine.cc:140 Context] enable compressw weight: 
[I  8/14  7:57:37.578 ...r/src/driver/huawei_ascend_npu/engine.cc:150 Context] auto tune mode: 
[I  8/14  7:57:37.578 ...r/src/driver/huawei_ascend_npu/engine.cc:160 Context] enable dynamic shape range: 
[I  8/14  7:57:37.578 ...r/src/driver/huawei_ascend_npu/engine.cc:176 Context] initial buffer length of dynamic shape range: -1
[W  8/14  7:57:37.578 ...ter/nnadapter/src/runtime/compilation.cc:334 Finish] Warning: Failed to create a program, No model and cache is provided.
[W  8/14  7:57:37.578 ...le-Lite/lite/kernels/nnadapter/engine.cc:149 LoadFromCache] Warning: Build model failed(3) !
[W  8/14  7:57:37.598 ...nnadapter/nnadapter/src/runtime/model.cc:86 GetSupportedOperations] Warning: Failed to get the supported operations for device 'huawei_ascend_npu', because the HAL interface 'validate_program' is not implemented!
[W  8/14  7:57:37.598 ...kernels/nnadapter/converter/converter.cc:171 Apply] Warning: Failed to get the supported operations for the selected devices, one or more of the selected devices are not supported!
[I  8/14  7:57:37.598 ...r/src/driver/huawei_ascend_npu/driver.cc:70 CreateProgram] Create program for huawei_ascend_npu.
^C/usr/local/python3.7.5/lib/python3.7/multiprocessing/semaphore_tracker.py:144: UserWarning: semaphore_tracker: There appear to be 91 leaked semaphores to clean up at shutdown

**Comment by leiqing1** [comment]
@yywangfei 都是warning，然后直接ctrl+c终端了吗？ 具体的错误是啥？

**Comment by jiangjiajun** [comment]
initial buffer length of dynamic shape range: -1
[W 8/14 7:57:37.578 ...ter/nnadapter/src/runtime/compilation.cc:334 Finish] Warning: Failed to create a program, No model and cache is provided. 

不确认跑的是啥模型，但看起来跟输入的Shape有关

**Comment by yywangfei** [comment]
> 
跑的是yoloe模型，参考的示例是:https://github.com/PaddlePaddle/FastDeploy/blob/develop/examples/vision/detection/paddledetection/python/README.md
执行命令如下：
cd FastDeploy/examples/vision/detection/paddledetection/python/
python infer_ppyoloe.py --model_dir ppyoloe_crn_l_300e_coco --image 000000014439.jpg --device ascend
请教一下我如何去排查呢？

**Comment by yywangfei** [comment]
> @yywangfei 都是warning，然后直接ctrl+c终端了吗？ 具体的错误是啥？
![image](https://github.com/PaddlePaddle/FastDeploy/assets/22832382/bfdd8008-6315-47e5-83cd-4b165779fd0d)
运行到这里就卡住了

**Comment by deshuai666** [comment]
> > @yywangfei 都是warning，然后直接ctrl+c终端了吗？ 具体的错误是啥？
> > ![image](https://user-images.githubusercontent.com/22832382/262543802-bfdd8008-6315-47e5-83cd-4b165779fd0d.png)
> > 运行到这里就卡住了

我也遇到了相同的问题，请问您解决了吗？

**Comment by louwenjie123** [comment]
有人解决一下吗，同样的问题
