### ISSUE TITLE
PPOCRV4 初始化后的 predictor 不能重复使用

### ISSUE THREAD

**Issue by ViewWholeWorld** [PaddlePaddle/FastDeploy#2170]
*********************************************
温馨提示：根据社区不完全统计，按照模板提问，可以加快回复和解决问题的速度
*********************************************

## 环境

- 【FastDeploy版本】： fastdeploy-linux-gpu-0.0.0
- 【编译命令】如果您是自行编译的FastDeploy，请说明您的编译方式（参数命令）
- 【系统平台】: Linux x64(Ubuntu 18.04)
- 【硬件】： Nvidia GPU P40， CUDA 11.7 CUDNN 8.3
- 【编译语言】： Python3.8

## 问题日志及出现问题的操作流程
使用PP-Chat-OCR给出的 demo，使用如下方式是可以完成推理的
<img width="435" alt="image" src="https://github.com/PaddlePaddle/FastDeploy/assets/19160255/dc835dac-86fe-4dc7-b1b1-0e50ba6a1ded">
但是，一旦将图中的ppocr_v4 作为函数传递出来（图中ppocr_pred返回ppocr_v4），再次调用 predict，就会出现 Segmentation Fault，调用方式如下图
<img width="560" alt="image" src="https://github.com/PaddlePaddle/FastDeploy/assets/19160255/12cd6a9f-d7ea-4b43-852f-c7b00788f0a5">

**Comment by jiangjiajun** [comment]
因为predictor作为函数内创建的临时变量，在返回后，有一些内部的指针因为出作用域被释放了

**Comment by ViewWholeWorld** [comment]
> 因为predictor作为函数内创建的临时变量，在返回后，有一些内部的指针因为出作用域被释放了

那想做个单例复用一下，怎么来实现呢？请问下有 demo 嘛？

**Comment by Frosty-GTRIIP** [comment]
您好，我也遇见了同样的问题，请问有没有什么比较好的解决方案呀？
