### ISSUE TITLE
跪求添加YOLOv8seg部署接口

### ISSUE THREAD

**Issue by panp4n** [PaddlePaddle/FastDeploy#2172]
跪求添加YOLOv8seg部署接口 
![1](https://github.com/PaddlePaddle/FastDeploy/assets/40445051/3bfa67b2-b70e-4145-9288-ee67ced5ea78)

**Comment by universea** [comment]
同问，是否支持yolov8seg?

**Comment by jiangjiajun** [comment]
要不一起来开发下，我可以帮忙Review代码 :)

**Comment by universea** [comment]
> 要不一起来开发下，我可以帮忙Review代码 :)

可以试试啊

**Comment by universea** [comment]
> 要不一起来开发下，我可以帮忙Review代码 :)

加个联系方式？

**Comment by jiangjiajun** [comment]
> > 要不一起来开发下，我可以帮忙Review代码 :)
> 
> 加个联系方式？

在任何FastDeploy的微信群里，在成员里面找到跟我头像一致的即可

**Comment by jiangjiajun** [comment]
![11408C19305247491A078CA562EF86DB](https://github.com/PaddlePaddle/FastDeploy/assets/19339784/8446f9b5-eac8-4173-b2a5-4ce3d016bc74)
