### ISSUE TITLE
yolo系列paddle格式在tensorrt后端推理不成功，输入不匹配

### ISSUE THREAD

**Issue by chenhao-stick-to** [PaddlePaddle/FastDeploy#2175]
## 环境
- 【FastDeploy版本】： fastdeploy develop版本 
- 【编译命令】
- cmake .. -DENABLE_ORT_BACKEND=ON \
         -DENABLE_OPENVINO_BACKEND=ON \
         -DENABLE_TRT_BACKEND=ON \
         -DWITH_GPU=ON \
         -DTRT_DIRECTORY=/usr/local/TensorRT-8.5.1.7 \
         -DCUDA_DIRECTORY=/usr/local/cuda-11.3 \
         -DENABLE_VISION=ON \
         -DCMAKE_INSTALL_PREFIX=${PWD}/compiled_fastdeploy_sdk \
- 【系统平台】: Linux x64(Ubuntu 20.04）
- 【硬件】：  Nvidia GPU 3080TI， CUDA 11.3 CUDNN 8.6.0 TensorRT8.5.1.7 gcc/g++ 9.4.0
- 【编译语言】： C++ 
##具体问题
- 【模型跑不通】
--example下的yolov7示例，前端是paddle格式模型，后端选择tensorrt，在跑示例时，以及自己实现的一版示例时都出现：
![yolov7](https://github.com/PaddlePaddle/FastDeploy/assets/64945280/b5eb3c9c-2c83-456c-b05b-ca3c28a31211)
后面自己实现了yolov8的也一样的错：
![yolov8](https://github.com/PaddlePaddle/FastDeploy/assets/64945280/d818dc2f-b8c2-4245-87d3-edfb971b6457)
看结果好像是输入不匹配，但我记得输入应该只需要设置图片，而不需要scale_factor。
看结果是在底层trt_backend中的paddle转onnx，onnx序列化为trt文件这个转化时，输入的转化问题。

**Comment by jiangjiajun** [comment]
因为paddledetection训练的模型导出会有一个输入scale_factor，所以需要指定这个输入

**Comment by kkpssr** [comment]
> 因为paddledetection训练的模型导出会有一个输入scale_factor，所以需要指定这个输入

请问这个怎么指定呢
