### ISSUE TITLE
jetson AGX Xavier怎么安装fastdeploy?

### ISSUE THREAD

**Issue by truthsun22** [PaddlePaddle/FastDeploy#2176]
执行pip install fastdeploy-gpu-python -f https://www.paddlepaddle.org.cn/whl/fastdeploy.html
然后import fastdeploy报错如下：
WARNING:root:Due to the package size limitation, we have not provide fastdeploy-gpu-python on pypi yet, please execute the following commands to reinstall fastdeploy-gpu-python.
WARNING:root:   =================== Reinstall fastdeploy-gpu-python commands ==================
WARNING:root:   python -m pip uninstall fastdeploy-gpu-python
WARNING:root:   python -m pip install fastdeploy-gpu-python -f https://www.paddlepaddle.org.cn/whl/fastdeploy.html
Traceback (most recent call last):
  File "infer_arcface_me.py", line 1, in <module>
    import fastdeploy as fd
  File "/home/deepnature/anaconda3/envs/paddle2.4/lib/python3.7/site-packages/fastdeploy/__init__.py", line 22, in <module>
    raise Exception("Failed to import fastdeploy module.")
Exception: Failed to import fastdeploy module.

另外，我对安装fastdeploy的说明文档感到迷惑
有的地方说安装python sdk即可，有的地方说要编译安装，麻烦说明一下，谢谢

**Comment by jiangjiajun** [comment]
预编译的里面提供的不包括Jetson平台，Jetson平台需自行编译安装
