### ISSUE TITLE
求助，有没有大神可以告知如何将C++中Matting.MODNet模型增加C#的API方法

### ISSUE THREAD

**Issue by yangyunyi** [PaddlePaddle/FastDeploy#2178]
求助，有没有大神可以告知如何将C++中Matting.MODNet模型增加C#的API方法

**Comment by rainyfly** [comment]
参考这个文档https://github.com/PaddlePaddle/FastDeploy/blob/develop/docs/cn/faq/develop_c_sharp_api_for_a_new_model.md 和 这个PR https://github.com/PaddlePaddle/FastDeploy/pull/1424
