### ISSUE TITLE
C++环境下执行fastdeploy库中的  paddle  Segmentation来预测分割模型，执行到model.Predict(&im, &res)报错，求问

### ISSUE THREAD

**Issue by zhigangjun** [PaddlePaddle/FastDeploy#2182]
- 【FastDeploy版本】： fastdeploy-linux-gpu-1.0.7
- 【编译命令】
- 【系统平台】: Windows x64(Windows10) 
- 【硬件】： Nvidia GPU 4080， CUDA 11.8 CUDNN 8.9
- 【编译语言】： C++

- 【模型跑不通】
- - 执行`examples`下的部署示例，在执行到model.Predict(&im, &res)时报错。
- - - 
- 执行代码：
--------------------------------------
 	auto model_file = model_dir + sep + "model.pdmodel";
 	auto params_file = model_dir + sep + "model.pdiparams";
 	auto config_file = model_dir + sep + "deploy.yaml";
 
 	auto option = fastdeploy::RuntimeOption();
  	option.UseGpu();
 	auto model = fastdeploy::vision::segmentation::PaddleSegModel(
 	model_file, params_file, config_file, option);
 
  
 	if (!model.Initialized()) {
	        std::cerr << "Failed to initialize." << std::endl;
		return;
	}
 
 	//计时
	auto start = std::chrono::system_clock::now();
	auto im = cv::imread(image_file);

 	fastdeploy::vision::SegmentationResult res;
	if (!model.Predict(&im, &res)) {
  		std::cerr << "Failed to predict." << std::endl;
 		return;
	}
--------------------------------------
（gpu环境激活成功，模型初始化成功，但执行预测的时候报错）
--------------------------------------
- [INFO] fastdeploy/vision/common/processors/transform.cc(93)::fastdeploy::vision::FuseNormalizeHWC2CHW   Normalize and HWC2CHW are fused to NormalizeAndPermute  in preprocessing pipeline.
[INFO] fastdeploy/vision/common/processors/transform.cc(159)::fastdeploy::vision::FuseNormalizeColorConvert     BGR2RGB and NormalizeAndPermute are fused to NormalizeAndPermute with swap_rb=1
[INFO] fastdeploy/runtime/runtime.cc(273)::fastdeploy::Runtime::CreatePaddleBackend     Runtime initialized with Backend::PDINFER in Device::GPU.

--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
Not support stack backtrace yet.

----------------------
Error Message Summary:
----------------------
ExternalError: CUDNN error(9), CUDNN_STATUS_NOT_SUPPORTED.
  [Hint: Please search for the error code(9) on website (https://docs.nvidia.com/deeplearning/cudnn/api/index.html#cudnnStatus_t) to get Nvidia's official solution and advice about CUDNN Error.] (at ../paddle/phi/kernels/fusion/gpu/conv_fusion_kernel.cu:609)

![image](https://github.com/PaddlePaddle/FastDeploy/assets/29684893/784560b4-3faa-4f4e-b5d6-45d1c253a2bb)

![image](https://github.com/PaddlePaddle/FastDeploy/assets/29684893/fbb076a2-92ed-411f-a720-6ebcc1d6a451)

**Comment by zhigangjun** [comment]
cudnn版本问题，回退到cuda11.8+cudnn8.6.0推理正常。

**Comment by pcycccccc** [comment]
> cudnn版本问题，回退到cuda11.8+cudnn8.6.0推理正常。

好人！！我找了一圈没太明白到底需要什么样版本的cudnn，害怕需要再重新安装cuda，我cuda用的也是11.8，cudnn用的8.7.0，看到你这条，果断10分钟搞定！

**Comment by WangShengFeng1** [comment]
> > cudnn版本问题，回退到cuda11.8+cudnn8.6.0推理正常。
> 
> 好人！！我找了一圈没太明白到底需要什么样版本的cudnn，害怕需要再重新安装cuda，我cuda用的也是11.8，cudnn用的8.7.0，看到你这条，果断10分钟搞定！



> > cudnn版本问题，回退到cuda11.8+cudnn8.6.0推理正常。
> 
> 好人！！我找了一圈没太明白到底需要什么样版本的cudnn，害怕需要再重新安装cuda，我cuda用的也是11.8，cudnn用的8.7.0，看到你这条，果断10分钟搞定！

额，小白问，怎么退回去，我在aistodis平台上跑的
