### ISSUE TITLE
Cannot compile with openvino while in linux-aarch64 platform

### ISSUE THREAD

**Issue by dengmingD** [PaddlePaddle/FastDeploy#2212]
ver:fastdeploy-release-1.0.7
cpu:飞腾 ft2000
统统：uos
python: 3.9
编译：
cmake .. -DENABLE_ORT_BACKEND=OFF \
-DENABLE_OPENVINO_BACKEND=ON \
-DCMAKE_INSTALL_PREFIX=${PWD}/compiled_fastdeploy_sdk \
-DENABLE_VISION=OFF \
-DENABLE_TEXT=OFF \

问题，编译时如果加下面这个就会报错：Cannot compile with openvino while in linux-aarch64 platform
-DENABLE_OPENVINO_BACKEND=ON

当然如果换成
-DENABLE_PADDLE_BACKEND=ON，会报如下错误：
  Paddle Backend doesn't support linux aarch64 now.

如果上面两个选项OFF是可以编译通过的，但是预测速度非常慢（cpp/python）
如果没有cpu加速，一个完整的ocr大约会在20s左右，同样的图片，有加速的（win）只要500ms
希望官方支持支持openvino
谢谢，祝国庆快乐

**Comment by rainyfly** [comment]
已收到反馈
