### ISSUE TITLE
在VS中使用C++接口报错

### ISSUE THREAD

**Issue by qinlihaoWork** [PaddlePaddle/FastDeploy#222]
**新手求助**
配置：win+VS 2019
按照教程，C++SDK成功运行后想通过C++接口来使用
(SDK参照Windows C++SDK教程实现)
使用教程中的代码(在Debug模式下)：
![image](https://user-images.githubusercontent.com/111327813/190044725-8182cb9c-ff48-404a-8a0a-05884a590c4a.png)

新建的项目没有配置目录，配置信息如下：
VC++包含目录
![image](https://user-images.githubusercontent.com/111327813/190044908-ec908580-9f2e-4fd3-ac8e-073459808f9b.png)

VC++库目录
![image](https://user-images.githubusercontent.com/111327813/190045017-12605909-5d1c-412b-9d33-403a6bcd074d.png)

C/C++常规、附加包含目录
![image](https://user-images.githubusercontent.com/111327813/190045097-c91a9c76-69f8-454c-8f47-ac9b4032bf2f.png)

配置可以找到fastdeploy、opencv等源文件，运行后报错
**错误	LNK1104	无法打开文件“C:\Users\lihao.qin\paddle\FastDeploy\build\fastdeploy-win-x64-gpu-0.2.0\lib.obj”**

![image](https://user-images.githubusercontent.com/111327813/190045336-ef5ea553-6dda-411a-b587-45af0140531e.png)

查看预编译库中没有错误信息中提到的文件，请问该如何解决这个问题？谢谢！

=================================================================================
更换为Release模式，出现新的报错信息。
![image](https://user-images.githubusercontent.com/111327813/190055822-d7933dd7-2adc-43a1-9b58-d21826632746.png)

**Comment by DefTruth** [comment]
感谢您的反馈，我们将尽快跟进这个问题 ~

**Comment by qinlihaoWork** [comment]
反复检查后，发现是dll配置问题，已解决。
