### ISSUE TITLE
pp-Tracking 推理报错     出现异常。 Segmentation fault

### ISSUE THREAD

**Issue by 294978174** [PaddlePaddle/FastDeploy#2224]
std::shared_ptr<fastdeploy::vision::tracking::PPTracking> model;
model = std::make_shared<fastdeploy::vision::tracking::PPTracking>(model_file, params_file, config_file, option);
初始化正常
if (!model->Predict(&img &result))
{
  std::cerr << "Failed to predict." << std::endl;
  return;
}
执行predict时候 报错  出现异常。 Segmentation fault

不使用指针实例化不报错   检查了输入图片和指针都正常
定义在类内
std::shared_ptr<fastdeploy::vision::tracking::PPTracking> model;
调用构造部分在我类内的init函数
model = std::make_shared<fastdeploy::vision::tracking::PPTracking>(model_file, params_file, config_file, option);
predict调用在我类内的predict函数  
当初始化和推理写在一个函数内是正常不报错

**Comment by ChaoII** [comment]
有没有看一下example中的例子，是不是那样写的，先确认一下。
