### ISSUE TITLE
PaddlePaddle/FastDeploy/tree/develop/examples/application/js/web_demo   GPU加速

### ISSUE THREAD

**Issue by lymgithub** [PaddlePaddle/FastDeploy#2225]
(https://github.com/PaddlePaddle/FastDeploy/tree/develop/examples/application/js)
/web_demo/

这个项目的ocr可以利用 nodejs webgl 进行 gpu加速吗？如果可以，怎么用呢

**Comment by chenqianhe** [comment]
https://github.com/PaddlePaddle/FastDeploy/blob/aab27b3db5d685b58837ff78ac1587be39966aa1/examples/application/js/package/packages/paddlejs-models/ocr/src/index.ts#L7

修改这里的 backend 即可

可选择的 backend https://github.com/PaddlePaddle/Paddle.js?tab=readme-ov-file#backends
