### ISSUE TITLE
TensorRT and GPU performance is much slower than CPU on C++

### ISSUE THREAD

**Issue by mohblnk** [PaddlePaddle/FastDeploy#2238]
## Environment

FastDeploy version: 0.0.0 compiled locally from repo (latest) (compile flags below)
OS Platform: Linux x64 debian 11 OS
Hardware: tested on NVIDIA RTX A4000 & NVIDIA RTX 3050 with same environment CUDA 11.6 CUDNN 8.7.0.84 tensorRT 8.5.3.1
Program Language: C++

## Problem description

I ran the example [here](https://github.com/PaddlePaddle/FastDeploy/tree/develop/examples/vision/ocr/PP-OCR/cpu-gpu/cpp) and when I use a CPU option the performance in much faster around 0.5 seconds while using GPU option (either TRT or paddle GPU) the infer time is about 3-4 seconds after reading from a serialized cached file.
TensorRT or the GPU option should be much faster than the CPU however my results differ.

## Things I have tried

 - use the precompiled fastdeploy library instead of building one locally 
 - use different GPU
 - use paddle GPU & paddle TRT  & TRT same results which is slower than CPU

I wanted to try cuda 11.2 but it is not available on my OS debian 11
any help is appreciated.

**Comment by mohblnk** [comment]
I just tried python fastdeploy lib and had the same results i.e. GPU is slower than CPU

**Comment by jiangjiajun** [comment]
Please benchmark the performance with the following step

- Initialize the model in CPU or GPU(TensorRT)
- Inference m times for warm up, e.g m=20
- Inference n times, and recording the cost time

**Comment by mohblnk** [comment]
The initialization time of the model on the TRT GPU back end takes long time,but once it is initialized the inference time is the quickest. 

close this, as it is not an issue but a misunderstanding on my part.
