### ISSUE TITLE
请问升腾npu编译的时候，paddlelite怎么和fastdeploy进行结合？

### ISSUE THREAD

**Issue by xiaomujiang** [PaddlePaddle/FastDeploy#2259]
## 环境
ascend 310p  On X86_64 platform

## 方法
（1）https://github.com/PaddlePaddle/FastDeploy/blob/develop/docs/en/build_and_install/huawei_ascend.md 按照这个官方文档讲到了自己编译的方法，成功后会在 Paddle-Lite/build.lite.linux.x86.gcc/inference_lite_lib/ 生成 Paddle Lite 编译包
（2）C++ FastDeploy library compilation based on Paddle Lite
         这一节中按照命令进行编译，但是没有看到如何关联上一步自己编译的Paddle Lite 编译包，而cmake中默认用的是https://paddle-qa.bj.bcebos.com/Paddle-Lite/DevelopDailyBuild/FastDeploy.CPP.inference_lite_lib.ubuntu.x86.huawei_ascend_npu.CANN5.1.RC2.alpha001.tar.gz
## 问题
怎么编译fastdelpoy的时候，用上自己在ascend上编译出来的paddlelite编译包，而不是用默认的

**Comment by rainyfly** [comment]
如果你找到了CMake中用的默认包的位置，是不是修改一下CMake替换成自己的就行
