### ISSUE TITLE
ERROR: No matching distribution found for fast-tokenizer-python

### ISSUE THREAD

**Issue by Lowpower** [PaddlePaddle/FastDeploy#2261]
*********************************************
温馨提示：根据社区不完全统计，按照模板提问，可以加快回复和解决问题的速度
*********************************************

## 环境

- 【FastDeploy版本】： master
- 【编译命令】FastDeploy/examples/text/ernie-3.0/python 
- 【系统平台】:  mac M2 OSX 13.4 (22F66)
- 【编译语言】：Python 3.11.4

## 问题日志及出现问题的操作流程
- 附上详细的问题日志有助于快速定位分析
pip install -r requirements.txt

**Comment by sususnow** [comment]
请问怎么解决这个问题。No matching distribution found for fast-tokenizer-python 。
