### ISSUE TITLE
ENABLE_ENCRYPTION=ON 在windows x64 平台编译报错及解决

### ISSUE THREAD

**Issue by qx1216** [PaddlePaddle/FastDeploy#2273]
*********************************************
温馨提示：开启 ENABLE_ENCRYPTION 时在windows x64 平台编译报错及解决方式，本人参试可行，仅作参考
*********************************************

## 环境

- 【FastDeploy版本】： fastdeploy-win-x64-gpu-1.0.7
- 【编译命令】: mkdir build && cd build
   cmake .. -G "Visual Studio 16 2019" -A x64   ^
                 -DENABLE_ORT_BACKEND=ON   ^
                 -DENABLE_VISION=ON   ^
                 -DENABLE_TEXT=ON   ^
                 -DWITH_GPU=ON   ^
                 -DCUDA_DIRECTORY="C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.6"   ^
                 -DENABLE_ENCRYPTION=ON  ^
                 -DCMAKE_INSTALL_PREFIX="fastdeploy-win-x64-ort-gpu-1.0.7"
   msbuild fastdeploy.sln /m /p:Configuration=Release /p:Platform=x64
   msbuild INSTALL.vcxproj /m /p:Configuration=Release /p:Platform=x64
- 【系统平台】: Windows x64(Windows10)
- 【硬件】： Nvidia GPU 3050， CUDA 11.6 CUDNN 8.9
- 【编译语言】： C++

## 问题及解决方法
- - 【加上 -DENABLE_ENCRYPTION=ON 后编译报错】
- - 【问题-1】C 不支持 std::vector<std::string> 返回
- - 【解决-1】更改 "fastdeploy/encryption/include/encrypt.h":
- - 原函数 FASTDEPLOY_DECL std::vector<std::string> Encrypt(const std::string& input, const std::string& key);
- - 更改为 FASTDEPLOY_DECL std::string Encrypt(const std::string& input, const std::string& key);
- - 对应的 encrypt.cc 文件相应函数更改为：
- -  std::string Encrypt(const std::string& input,  const std::string& key) {
    std::istringstream isst(input);
    std::ostringstream osst;
    int ret =  EncryptStream(isst, osst, key);
    if (ret != 0) {
       FDERROR << ret << ", Failed encrypt " << std::endl;
       return {"", ""};
    }
  
   return baidu::base::base64::base64_encode(osst.str());
  }
- - 【问题-2】libcrypto_static.lib(b_sock.obj) : error LNK2019: 无法解析的外部符号 
- - 【解决-2】 "cmake/openssl.cmake" 设置 OPENSSL_LIBRARIES 时加入 ws2_32，具体为：
- -  IF(CMAKE_SYSTEM_NAME MATCHES "Windows")
        set(OPENSSL_LIBRARIES
                        "${OPENSSL_ROOT_DIR}/lib/libssl_static.lib"
                        "${OPENSSL_ROOT_DIR}/lib/libcrypto_static.lib"
                        ${GFLAGS_LIBRARIES}
                        shlwapi
                        ws2_32
                        CACHE FILEPATH "OPENSSL_LIBRARIES" FORCE)

**Comment by jiangjiajun** [comment]
欢迎帮忙提PR修复，我可以帮忙Review，及合入
