### ISSUE TITLE
C++ SDK在linux服务端部署，支持服务化部署吗？

### ISSUE THREAD

**Issue by AI-Mart** [PaddlePaddle/FastDeploy#228]
C++ SDK在linux服务端部署，支持服务化部署吗，服务端用C++服务化部署，客户端用python写，服务端和客户端通过rpc通信，这样能否支持？

**Comment by jiangjiajun** [comment]
服务端的部署正在支持中，预计下个月会发布。

你当前有哪些模型的服务化部署需求吗？

**Comment by AI-Mart** [comment]
人脸检测和识别，最好把人脸姿态角也加上，把检测和识别的模型串联也加上，如果支持C++服务化部署的话，我到时候尝试下，比对下和python，sdk部署的性能差异，客户端代码都是python编写的

**Comment by AI-Mart** [comment]
目前c++ sdk的方式调用，是不是客户端的代码都需要用C++重新写一遍？

**Comment by jiangjiajun** [comment]
> 目前c++ sdk的方式调用，是不是客户端的代码都需要用C++重新写一遍？

你是指如果迁移到服务化部署吗？

如果是服务化部署，那所有的代码都运行在服务端，客户端发送请求和获取请求即可

**Comment by heliqi** [comment]
> 目前c++ sdk的方式调用，是不是客户端的代码都需要用C++重新写一遍？

@AI-Mart 
不需要。 客户端支持使用python发送grpc或http请求

**Comment by heliqi** [comment]
已经支持服务化部署： 
https://github.com/PaddlePaddle/FastDeploy/tree/develop/serving

**Comment by jiangjiajun** [comment]
此ISSUE由于一年未更新，将会关闭处理，如有需要，可再次更新打开。
