### ISSUE TITLE
 rk3588交叉编译问题：collect2: error: ld returned 1 exit status

### ISSUE THREAD

**Issue by catofyuanyuan** [PaddlePaddle/FastDeploy#2282]
*********************************************
温馨提示：根据社区不完全统计，按照模板提问，可以加快回复和解决问题的速度
*********************************************

## 环境
- 【FastDeploy版本】： fastdeploy-1.0.7
- 【编译命令】
        cd FastDeploy-release-1.0.7/build
        sudo cmake .. \
        -DCMAKE_C_COMPILER=/opt/gcc-linaro-7.4.1-2019.02-x86_64_aarch64-linux-gnu/bin/aarch64-linux-gnu-gcc \
        -DCMAKE_CXX_COMPILER=/opt/gcc-linaro-7.4.1-2019.02-x86_64_aarch64-linux-gnu/bin/aarch64-linux-gnu-g++ \
        -DCMAKE_TOOLCHAIN_FILE=./../cmake/toolchain.cmake -DTARGET_ABI=arm64 \
        -DENABLE_ORT_BACKEND=ON \
        -DENABLE_RKNPU2_BACKEND=ON \
        -DENABLE_VISION=ON \
        -DRKNN2_TARGET_SOC=RK3588 \
        -DCMAKE_INSTALL_PREFIX=${PWD}/fastdeploy-0.0.0

- 【系统平台】: Linux x64(Ubuntu 20.04)
- 【硬件】： 无GPU， CUDA 11.1
- 【编译语言】： C++ 

## rk3588编译问题
sudo make -j8 编译运行至100%，出现问题如下：
...
[ 99%] Building CXX object CMakeFiles/fastdeploy.dir/fastdeploy/vision/visualize/visualize.cc.o
[ 99%] Building CXX object CMakeFiles/fastdeploy.dir/fastdeploy/pipeline/pptinypose/pipeline.cc.o
[100%] Linking CXX shared library libfastdeploy.so
third_libs/install/onnxruntime/lib/libonnxruntime.so: error adding symbols: File in wrong format
@collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/fastdeploy.dir/build.make:3098: libfastdeploy.so.1.0.7] Error 1
make[1]: *** [CMakeFiles/Makefile2:148: CMakeFiles/fastdeploy.dir/all] Error 2
make: *** [Makefile:152: all] Error 2

**Comment by catofyuanyuan** [comment]
已经解决 -DENABLE_ORT_BACKEND=ON需要设置为OFF

**Comment by Luo73** [comment]
请问以上编译命令中的gcc-linaro-7.4.1-2019.02-x86_64_aarch64-linux-gnu是怎么获取的呢？按照仓库文档里提供下载的gcc-linaro-6.3.1-2017.05-x86_64_aarch64-linux-gnu在x86 ubuntu20.04进行交叉编译时，会报错
`/usr/bin/ld: /home/FastDeploy/build/fastdeploy-0.0.0/lib/libfastdeploy.so: error adding symbols: file in wrong format
collect2: error: ld returned 1 exit status`
