### ISSUE TITLE
Compile with OpenVINO

### ISSUE THREAD

**Issue by n3ry7** [PaddlePaddle/FastDeploy#229]
I am trying to run the \examples\runtime\python\infer_onnx_openvino.py on Windows 10

And I get the folowwing error:
[ERROR] csrc/fastdeploy/fastdeploy_runtime.cc(193)::fastdeploy::RuntimeOption::UseOpenVINOBackend       The FastDeploy didn't compile with OpenVINO.

How do I compile with OpenVINO backend?

**Comment by jiangjiajun** [comment]
Hi， This require rebuild Fasdtdeploy， just follow this doc to build

https://www.github.com/PaddlePaddle/FastDeploy/tree/develop/docs%2Fdocs_en%2Fcompile%2Fhow_to_build_windows.md

but need to set ENABLE_OPENVINO_BACKEND=ON

**Comment by n3ry7** [comment]
Thanks! 

I tried to follow this:

git clone https://github.com/PaddlePaddle/FastDeploy.git
cd FastDeploy && git checkout develop

set ENABLE_ORT_BACKEND=ON
set ENABLE_PADDLE_BACKEND=ON
set ENABLE_VISION=ON
set ENABLE_VISION_VISUALIZE=ON
set ENABLE_OPENVINO_BACKEND=ON

% 这里指定用户自己的python解释器 以python3.8为例 %
C:\Python38\python.exe setup.py build
C:\Python38\python.exe setup.py bdist_wheel

But there is no sertup.py file

**Comment by n3ry7** [comment]
I tried this:

git clone https://github.com/PaddlePaddle/FastDeploy.git
cd FastDeploy && git checkout develop

set ENABLE_ORT_BACKEND=ON
set ENABLE_PADDLE_BACKEND=ON
set ENABLE_VISION=ON
set ENABLE_VISION_VISUALIZE=ON

% 这里指定用户自己的python解释器 以python3.8为例 %
C:\Python38\python.exe setup.py build
C:\Python38\python.exe setup.py bdist_wheel

But there is no setup.py when the repo is clonned.

So I took the release files which have a setup.py, then I got the following error:

" Found OpenCV Windows Pack but it has no binaries compatible with your
  configuration.

  You should manually point CMake variable OpenCV_DIR to your build of OpenCV
  library."
  
  And another thing the worries me is that I could not find anything related to ENABLE_OPENVINO_BACKEND=ON on setup.py

**Comment by jiangjiajun** [comment]
It your windows win32 or x64?, currently only `x64` is supported.

If you need to build with python, just like enable other backend

```
set ENABLE_OPENVINO_BACKEND=ON
```
and then `python setup.py build`, it will download openvino automatically.

By the way, you can pull the latest code of FastDeploy, clear the cache during building(directory `build` & `.setuptools-cmake-build`, then build fastdeploy again.

**Comment by jiangjiajun** [comment]
此ISSUE由于一年未更新，将会关闭处理，如有需要，可再次更新打开。
