### ISSUE TITLE
window10 运行崩溃

### ISSUE THREAD

**Issue by qx1216** [PaddlePaddle/FastDeploy#2304]
*********************************************
温馨提示：根据社区不完全统计，按照模板提问，可以加快回复和解决问题的速度
*********************************************

## 环境

- 【FastDeploy版本】： fastdeploy-linux-gpu-1.0.7
- 【编译命令】官方提供预编译sdk
- 【系统平台】: Windows x64(Windows10)
- 【硬件】：  Nvidia GPU 3050， CUDA 11.6  CUDNN 8.9
- 【编译语言】： C++ 

## 问题日志及出现问题的操作流程
- 【模型跑不通】
- - 运行demo: infer_onnx_onnxruntime.cc，程序执行到这一步时崩溃：std::vector<fd::TensorInfo> inputs_info = runtime.GetInputInfos();
- - 无任何报错，直接崩溃，用官方预编译或自行编译的fastdeploy都一样。

**Comment by qx1216** [comment]
去源码调试发现信息打印不出来，最后发现是 assert()  的问题/(ㄒoㄒ)/~~，，去掉 #include <cassert> 和 assert() 函数即可
#include <cassert>
assert(runtime.Init(runtime_option));
...

**Comment by rainyfly** [comment]
感谢你的使用
