### ISSUE TITLE
有支持C#部署的打算吗

### ISSUE THREAD

**Issue by futureflsl** [PaddlePaddle/FastDeploy#231]
有支持C#部署的打算吗

**Comment by ZeyuChen** [comment]
有的，敬请期待。请问你们是什么业务场景需要C#部署呢

**Comment by monkeycc** [comment]
建议增加C#部署

**Comment by 1316540491** [comment]
强烈建议增加C#部署，工业C#用的比较多

**Comment by dogpandacat** [comment]
> 

工控机上用C# Winform做用户界面，然后调用FastDeploy，请问对C#的支持大概什么时候可以出来

**Comment by jiangjiajun** [comment]
预计在这个月底会有一个版本支持PaddleDetection/PaddleOCR模型部署
