### ISSUE TITLE
飞桨啊飞桨请问我解决！PaddleLite  ConvertConv2D] Check failed: IsSameSymmQuantParams(input_scales, quan

### ISSUE THREAD

**Issue by shengzhe8688** [PaddlePaddle/FastDeploy#2313]
使用的环境：Ascend huawei 300i  cann6.0RC1alph005
使用paddleLite库：下载官方inference_lite_lib.ky10.armv8.huawei_ascend_npu.CANN6.0.0.alpha006.tar.gz 和对应opt
我的服务器：华为鲲鹏服务器，查了一下就是armv8的
模型转换：./opt_linux_aarch64 --model_file=./model/ch_ppocr_mobile_v2.0_det_slim_infer/inference.pdmodel --param_file=./model/ch_ppocr_mobile_v2.0_det_slim_infer/inference.pdiparams --optimize_out=./model/ch_ppocr_mobile_v2.0_det_slim_npu --valid_targets=huawei_ascend_npu,arm --optimize_out_type=naive_buffer
./opt_linux_aarch64 --model_file=./model/ch_ppocr_mobile_v2.0_rec_slim_infer/inference.pdmodel --param_file=./model/ch_ppocr_mobile_v2.0_rec_slim_infer/inference.pdiparams --optimize_out=./model/ch_ppocr_mobile_v2.0_rec_slim_npu --valid_targets=huawei_ascend_npu,arm --optimize_out_type=naive_buffer
./opt_linux_aarch64 --model_file=./model/ch_ppocr_mobile_v2.0_cls_slim_infer/inference.pdmodel --param_file=./model/ch_ppocr_mobile_v2.0_cls_slim_infer/inference.pdiparams --optimize_out=./model/ch_ppocr_mobile_v2.0_cls_slim_npu --valid_targets=huawei_ascend_npu,arm --optimize_out_type=naive_buffer

c++代码：
![image](https://github.com/PaddlePaddle/FastDeploy/assets/16428236/629e3c48-5113-4d1e-b18f-ff4e3a1674cf)
错误代码：
![image](https://github.com/PaddlePaddle/FastDeploy/assets/16428236/03dabf89-cfb1-46f5-9e96-0bd8d39f21a7)

**Comment by rainyfly** [comment]
建议去PaddleLite 询问一下这个问题
