### ISSUE TITLE
编译FastDeploy/examples/vision/facedet/scrfd/cpp报错

### ISSUE THREAD

**Issue by XiaBing992** [PaddlePaddle/FastDeploy#2331]
*********************************************
温馨提示：根据社区不完全统计，按照模板提问，可以加快回复和解决问题的速度
*********************************************

## 环境
- 【编译命令】cmake .. -DENABLE_ORT_BACKEND=ON          -DENABLE_PADDLE_BACKEND=ON          -DENABLE_OPENVINO_BACKEND=ON          -DENABLE_TRT_BACKEND=ON          -DWITH_GPU=ON          -DTRT_DIRECTORY=/usr/local/TensorRT-8.6.1.6          -DCUDA_DIRECTORY=/usr/local/cuda-11.8          -DCMAKE_INSTALL_PREFIX=${PWD}/compiled_fastdeploy_sdk          -DENABLE_VISION=ON          -DOPENCV_DIRECTORY=/usr/local/lib/cmake/opencv4 -DENABLE_TEXT=ON -DCMAKE_CUDA_COMPILER=/usr/local/cuda-11.8/bin/nvcc
- 【系统平台】: Linux x64(Ubuntu 20.04)
- 【硬件】： cuda11.8
- 【编译语言】： C++ / Python(3.7或3.8等）

错误：
/usr/bin/ld: /home/wxb/computerprograms/c++/FastDeploy/build/compiled_fastdeploy_sdk/lib/libfastdeploy.so: undefined reference to `nvjpegJpegStreamParseHeader'
/usr/bin/ld: /home/wxb/computerprograms/c++/FastDeploy/build/compiled_fastdeploy_sdk/lib/libfastdeploy.so: undefined reference to `nvjpegDecodeBatchedSupported'
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/infer_with_face_align_demo.dir/build.make:128: infer_with_face_align_demo] Error 1
make[1]: *** [CMakeFiles/Makefile2:112: CMakeFiles/infer_with_face_align_demo.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
/usr/bin/ld: /home/wxb/computerprograms/c++/FastDeploy/build/compiled_fastdeploy_sdk/lib/libfastdeploy.so: undefined reference to `nvjpegJpegStreamParseHeader'
/usr/bin/ld: /home/wxb/computerprograms/c++/FastDeploy/build/compiled_fastdeploy_sdk/lib/libfastdeploy.so: undefined reference to `nvjpegDecodeBatchedSupported'
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/infer_without_face_align_demo.dir/build.make:128: infer_without_face_align_demo] Error 1
make[1]: *** [CMakeFiles/Makefile2:138: CMakeFiles/infer_without_face_align_demo.dir/all] Error 2
make: *** [Makefile:91: all] Error 2

**Comment by rainyfly** [comment]
看报错像是有某个依赖的so没有找到
