### ISSUE TITLE
Fastdeploy交叉编译过程中出现的libpaddle_full_api_shared.so: file not recognized: File format not recognized collect2: error: ld returned 1 exit status错误？

### ISSUE THREAD

**Issue by MrMzl** [PaddlePaddle/FastDeploy#2334]
*********************************************
温馨提示：根据社区不完全统计，按照模板提问，可以加快回复和解决问题的速度
*********************************************

## 环境

- 【FastDeploy版本】： 说明具体的版本，如fastdeploy-1.0.6
- 【编译命令】交叉编译方式，具体命令见下面log。
- 【系统平台】: ：本地Ubuntu20.04（x86-64）
- 【硬件】： 树莓派4B（aarch64）
- 【编译语言】： C++ 

## 问题日志及出现问题的操作流程
- 【需求描述】
- - 由于树莓派板端性能的限制，考虑采用交叉编译的方式在本地PC上进行源码编译，完成后上传到树莓派上进行模型部署验证。通过Fastdeploy以前的I和树莓派相关的issue查询，发现树莓派是支持paddlelite的，因此在交叉编译中打开了paddlelite配置项。
- 【编译方式】
- - Step1：本地PC安装树莓派交叉编译工具，已完成。
- - Step2：执行交叉编译命令如下：
- - - ` cmake .. -DCMAKE_C_COMPILER=/opt/raspberrypi/tools/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian-x64/bin/arm-linux-gnueabihf-gcc -DCMAKE_CXX_COMPILER=/opt/raspberrypi/tools/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian-x64/bin/arm-linux-gnueabihf-g++ -DCMAKE_TOOLCHAIN_FILE=../cmake/toolchain.cmake -DTARGET_ABI=arm64 -DENABLE_VISION=ON -DENABLE_LITE_BACKEND=ON -DCMAKE_INSTALL_PREFIX=${PWD}/fastdeploy-1.0.6`
- - - cmake编译通过。
- - Step3：执行make，‘make -j10’，**报错信息如下：**
- - - `[100%] Linking CXX shared library libfastdeploy.so
third_libs/install/paddlelite/lib/libpaddle_full_api_shared.so: file not recognized: File format not recognized
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/fastdeploy.dir/build.make:2751: libfastdeploy.so.1.0.6] Error 1
make[1]: *** [CMakeFiles/Makefile2:145: CMakeFiles/fastdeploy.dir/all] Error 2
make: *** [Makefile:152: all] Error 2`
- - 详细编译日志：
[log_2(1).txt](https://github.com/PaddlePaddle/FastDeploy/files/13768341/log_2.1.txt)
- -修改-DCMAKE_TOOLCHAIN_FILE后重新编译
- - Step2：执行交叉编译命令如下：
- - - ` cmake .. -DCMAKE_C_COMPILER=/opt/raspberrypi/tools/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian-x64/bin/arm-linux-gnueabihf-gcc -DCMAKE_CXX_COMPILER=/opt/raspberrypi/tools/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian-x64/bin/arm-linux-gnueabihf-g++ -DCMAKE_TOOLCHAIN_FILE=../cmake/toolchain.cmake -DTARGET_ABI=armhf -DENABLE_VISION=ON -DENABLE_LITE_BACKEND=ON -DCMAKE_INSTALL_PREFIX=${PWD}/fastdeploy-1.0.6` 
- - - cmake编译不通过
- - Step3：执行make，‘make -j10’，**报错信息如下：**
- - - `CMake Error at cmake/paddlelite.cmake:51 (message):
  Only support Linux aarch64 now, x64 is not supported with backend Paddle
  Lite.`
- - 详细编译日志：
[log_1.txt](https://github.com/PaddlePaddle/FastDeploy/files/13768378/log_1.txt)

**Comment by rainyfly** [comment]
![image](https://github.com/PaddlePaddle/FastDeploy/assets/22424850/1fa63e17-d1b8-4b28-a772-b67f94420608)

**Comment by rainyfly** [comment]
这个可能得设置成aarch64
