### ISSUE TITLE
FastDeploy部署 examples/vision/detection/paddledetection/python/infer_mask_rcnn.py运行官方给出的模型可以推理，自己训练的模型推理报错

### ISSUE THREAD

**Issue by laishenghui** [PaddlePaddle/FastDeploy#2341]
- 【FastDeploy版本】： [说明具体的版本，如fastdeploy-linux-gpu-0.8.0]
-   fastdeploy-python         1.0.7
-   由fastdeploy_python-1.0.7-cp39-cp39-win_amd64.whl文件安装
- 【系统平台】: Windows x64(Windows10) 
- 【硬件】： 使用的时CPU版本
- 【编译语言】： Python == 3.9 

## 问题日志及出现问题的操作流程
- 附上详细的问题日志有助于快速定位分析
- 【模型跑不通】
- 使用examples运行官方提供的模型，可以正常推理
- 使用自己训练的模型不能推理
- 代码-examples/vision/detection/paddledetection/python/infer_mask_rcnn.py未改动该文件
- 运行参数 
- --model_dir
D:\Paddle\3.PaddleDetection\FastDeploy\ModelTest\mask_rcnn_r50_1x_coco_all
--image
D:\Paddle\3.PaddleDetection\FastDeploy\ModelTest\Images\000000014439.jpg
--device
cpu
 使用的官方模型下载链接：https://bj.bcebos.com/paddlehub/fastdeploy/mask_rcnn_r50_1x_coco.tgz
自己训练的模型：太大了，我传不上来，我是用coco数据集训练的，配置用的就是paddledetection里面的configs/mask_rcnn/mask_rcnn_r50_1x_coco.yml文件，我只改动了里面的训练batchsize

错误log：
D:\Anaconda3\envs\fastdeploy\python.exe D:\Paddle\3.PaddleDetection\FastDeploy\FastDeploy-develop\examples\vision\detection\paddledetection\python\infer_mask_rcnn.py --model_dir D:\Paddle\3.PaddleDetection\FastDeploy\ModelTest\mask_rcnn_r50_1x_coco_all --image D:\Paddle\3.PaddleDetection\FastDeploy\ModelTest\Images\000000014439.jpg --device cpu 
[INFO] fastdeploy/vision/common/processors/transform.cc(159)::fastdeploy::vision::FuseNormalizeColorConvert	BGR2RGB and Normalize are fused to Normalize with swap_rb=1
WARNING: Logging before InitGoogleLogging() is written to STDERR
W0109 16:42:01.589668 10892 analysis_config.cc:971] It is detected that mkldnn and memory_optimize_pass are enabled at the same time, but they are not supported yet. Currently, memory_optimize_pass is explicitly disabled
[INFO] fastdeploy/runtime/runtime.cc(273)::fastdeploy::Runtime::CreatePaddleBackend	Runtime initialized with Backend::PDINFER in Device::CPU.
Traceback (most recent call last):
  File "D:\Paddle\3.PaddleDetection\FastDeploy\FastDeploy-develop\examples\vision\detection\paddledetection\python\infer_mask_rcnn.py", line 74, in <module>
    result = model.predict(im)
  File "D:\Anaconda3\envs\fastdeploy\lib\site-packages\fastdeploy\vision\detection\ppdet\__init__.py", line 126, in predict
    return self._model.predict(im)
RuntimeError: could not create a primitive descriptor for a reorder primitive

Process finished with exit code 1

**Comment by rainyfly** [comment]
这个模型是怎么导出的呢，
![image](https://github.com/PaddlePaddle/FastDeploy/assets/22424850/2c3222ed-3b57-4903-bdd3-07bf0a3d92f6)
我看这个里面还需要个infer_cfg.yml ，导出的模型的配置是否正确呢

**Comment by NyquistBodeTu** [comment]
infer_cfg.yml 这个文件是哪来的，我导出的只有.rknn模型啊
