### ISSUE TITLE
多分类跟踪模型加载

### ISSUE THREAD

**Issue by kitterive** [PaddlePaddle/FastDeploy#2345]
目前这个模型https://bj.bcebos.com/v1/paddledet/models/mot/mcfairmot_hrnetv2_w18_dlafpn_30e_576x320_bdd100k_mcmot.tar 是不支持吗？
错误信息：[INFO] fastdeploy/vision/common/processors/transform.cc(93)::fastdeploy::vision::FuseNormalizeHWC2CHW   Normalize and HWC2CHW are fused to NormalizeAndPermute  in preprocessing pipeline.
[Paddle2ONNX] Oops, there are some operators not supported yet, including conditional_block,lod_array_length,masked_select,select_input,tensor_array_to_tensor,write_to_array,
[ERROR] Due to the unsupported operators, the conversion is aborted.

**Comment by kitterive** [comment]
#说明

仅支持JDE模型（JDE，FairMOT，MCFairMOT)；
目前暂不支持SDE模型的部署，待PaddleDetection官方更新SED部署代码后，对SDE模型进行支持。

看你们的说明支持 MCFairMOT 的，我怎么只加载成功FairMOT模型，加载不了MCFairMOT模型呢

**Comment by kitterive** [comment]
版本号1.0.0.0

**Comment by ChaoII** [comment]
> 版本号1.0.0.0

用的什么推理后端

**Comment by kitterive** [comment]
谢谢，现在知道了， 好像是不能用onnx或者trt后端，只能用paddle的后端，是不是有些算子还转不了onnx?
