### ISSUE TITLE
WARNING:root:`RuntimeOption.enable_trt_fp16` will be deprecated in v1.2.0, please use `RuntimeOption.trt_option.enable_fp16 = True` instead.

### ISSUE THREAD

**Issue by txy00001** [PaddlePaddle/FastDeploy#2358]
![image](https://github.com/PaddlePaddle/FastDeploy/assets/47891269/5920ec3b-18aa-40b5-a0f8-9c048d823a92)
如上图，这个需要在脚本里更改么？我看源码脚本没有变化

**Comment by rainyfly** [comment]
warning信息，可以按照要求改一下，不改目前也能正常跑
