### ISSUE TITLE
将rknpu2中的rkyolov5添加到capi，执行中无连接错误

### ISSUE THREAD

**Issue by chatop2020** [PaddlePaddle/FastDeploy#2361]
[INFO] fastdeploy/runtime/backends/rknpu2/rknpu2_backend.cc(81)::GetSDKAndDeviceVersion rknpu2 runtime version: 1.5.1b19 (32afb0e92@2023-07-14T12:46:17)
[INFO] fastdeploy/runtime/backends/rknpu2/rknpu2_backend.cc(82)::GetSDKAndDeviceVersion rknpu2 driver version: 0.9.2
index=0, name=images, n_dims=4, dims=[1, 640, 640, 3], n_elems=1228800, size=1228800, fmt=NHWC, type=INT8, qnt_type=AFFINE, zp=-128, scale=0.003922, pass_through=0
index=0, name=output0, n_dims=4, dims=[1, 36, 80, 80], n_elems=230400, size=230400, fmt=NCHW, type=FP32, qnt_type=AFFINE, zp=-128, scale=0.003921, pass_through=0
index=1, name=283, n_dims=4, dims=[1, 36, 40, 40], n_elems=57600, size=57600, fmt=NCHW, type=FP32, qnt_type=AFFINE, zp=-128, scale=0.003921, pass_through=0
index=2, name=285, n_dims=4, dims=[1, 36, 20, 20], n_elems=14400, size=14400, fmt=NCHW, type=FP32, qnt_type=AFFINE, zp=-128, scale=0.003921, pass_through=0
[INFO] fastdeploy/runtime/runtime.cc(367)::CreateRKNPU2Backend  Runtime initialized with Backend::RKNPU2 in Device::RKNPU.
15
dotnet: symbol lookup error: /data1/YoloDetect/TestLibFastDepoly/bin/Debug/net6.0/libfastdeploy.so: undefined symbol: _ZN10fastdeploy35FD_C_CheckAndConvertRKYOLOV5WrapperEP20FD_C_RKYOLOV5Wrapper

但编译过程中并没有任何报错

我用ldd和nm分析了so文件，结果如下

 ldd -r libfastdeploy.so
        linux-vdso.so.1 (0x0000007fa5fb8000)
        librknnrt.so => /data1/FastDeploy/build/third_libs/install/rknpu2_runtime/lib/librknnrt.so (0x0000007fa5189000)
        libopencv_video.so.3.4 => /data1/FastDeploy/build/third_libs/install/opencv/lib/libopencv_video.so.3.4 (0x0000007fa5136000)
        libopencv_calib3d.so.3.4 => /data1/FastDeploy/build/third_libs/install/opencv/lib/libopencv_calib3d.so.3.4 (0x0000007fa502b000)
        libopencv_imgcodecs.so.3.4 => /data1/FastDeploy/build/third_libs/install/opencv/lib/libopencv_imgcodecs.so.3.4 (0x0000007fa4e63000)
        libopencv_imgproc.so.3.4 => /data1/FastDeploy/build/third_libs/install/opencv/lib/libopencv_imgproc.so.3.4 (0x0000007fa4a68000)
        libopencv_core.so.3.4 => /data1/FastDeploy/build/third_libs/install/opencv/lib/libopencv_core.so.3.4 (0x0000007fa475b000)
        libstdc++.so.6 => /lib/aarch64-linux-gnu/libstdc++.so.6 (0x0000007fa4560000)
        libm.so.6 => /lib/aarch64-linux-gnu/libm.so.6 (0x0000007fa44b5000)
        libgcc_s.so.1 => /lib/aarch64-linux-gnu/libgcc_s.so.1 (0x0000007fa4491000)
        libc.so.6 => /lib/aarch64-linux-gnu/libc.so.6 (0x0000007fa431d000)
        libpthread.so.0 => /lib/aarch64-linux-gnu/libpthread.so.0 (0x0000007fa42ec000)
        libopencv_flann.so.3.4 => /opt/libs/fastDeploy/third_libs/install/opencv/lib/libopencv_flann.so.3.4 (0x0000007fa4288000)
        libz.so.1 => /lib/aarch64-linux-gnu/libz.so.1 (0x0000007fa425e000)
        libdl.so.2 => /lib/aarch64-linux-gnu/libdl.so.2 (0x0000007fa424a000)
        /lib/ld-linux-aarch64.so.1 (0x0000007fa5f88000)
undefined symbol: _ZN10fastdeploy35FD_C_CheckAndConvertRKYOLOV5WrapperEP20FD_C_RKYOLOV5Wrapper  (./libfastdeploy.so)

nm libfastdeploy.so|grep RKYOLOV5
00000000006aade0 T FD_C_CreateRKYOLOV5Wrapper
00000000006ab310 T FD_C_DestroyRKYOLOV5Wrapper
00000000006abe20 t FD_C_RKYOLOV5WrapperBatchPredict
00000000006ab6f0 T FD_C_RKYOLOV5WrapperInitialized
00000000006ab640 T FD_C_RKYOLOV5WrapperPredict
                 U _ZN10fastdeploy35FD_C_CheckAndConvertRKYOLOV5WrapperEP20FD_C_RKYOLOV5Wrapper
0000000000468520 T _ZN10fastdeploy6vision9detection8RKYOLOV510InitializeEv
00000000004689e0 T _ZN10fastdeploy6vision9detection8RKYOLOV512BatchPredictERKSt6vectorIN2cv3MatESaIS5_EEPS3_INS0_15DetectionResultESaISA_EE
000000000046ac60 W _ZN10fastdeploy6vision9detection8RKYOLOV515GetPreprocessorEv
000000000046ac70 W _ZN10fastdeploy6vision9detection8RKYOLOV516GetPostprocessorEv
0000000000463cf0 T _ZN10fastdeploy6vision9detection8RKYOLOV57PredictEPN2cv3MatEPNS0_15DetectionResultEff
0000000000468300 T _ZN10fastdeploy6vision9detection8RKYOLOV57PredictERKN2cv3MatEPNS0_15DetectionResultE
0000000000469ab0 T _ZN10fastdeploy6vision9detection8RKYOLOV5C1ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESA_RKNS_13RuntimeOptionERKNS_11ModelFormatE
0000000000469ab0 T _ZN10fastdeploy6vision9detection8RKYOLOV5C2ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESA_RKNS_13RuntimeOptionERKNS_11ModelFormatE
000000000046ac80 W _ZNK10fastdeploy6vision9detection8RKYOLOV59ModelNameB5cxx11Ev
000000000092dcc8 V _ZTIN10fastdeploy6vision9detection8RKYOLOV5E
000000000083e4c8 V _ZTSN10fastdeploy6vision9detection8RKYOLOV5E
000000000092dce0 V _ZTVN10fastdeploy6vision9detection8RKYOLOV5E

可以看到

  U _ZN10fastdeploy35FD_C_CheckAndConvertRKYOLOV5WrapperEP20FD_C_RKYOLOV5Wrapper

表示链接有问题，不知道怎么解决，希望帮忙看看，谢谢。

**Comment by rainyfly** [comment]
感觉像是只声明了接口，但是没有接口的具体实现，所以虽然编译没有报错，但是链接报错了。https://github.com/PaddlePaddle/FastDeploy/pull/1418  可以参考这个PR看看是不是有地方漏了没加进去

**Comment by chatop2020** [comment]
我已经自己解决，谢谢
