### ISSUE TITLE
关于deploy.yaml

### ISSUE THREAD

**Issue by rememberBr** [PaddlePaddle/FastDeploy#2364]
*********************************************
温馨提示：根据社区不完全统计，按照模板提问，可以加快回复和解决问题的速度
*********************************************

## 环境

- 【FastDeploy版本】： aistudio导出的0.0.0
- 【系统平台】: Linux x64(Ubuntu 20.04) / Windows x64(Windows10)
- 【硬件】：Inter CPU
- 【编译语言】： C++ / Python 3.8

## 问题日志及出现问题的操作流程
不算bug，应该是一些疑问，我使用paddleSeg训练的pp-liteSeg模型，使用python tools/paddle_infer_shape.py导出可推理的模型，同时也生成了一个deploy.yaml文件，但是该文件似乎有问题（这问题应该是paddleSeg的paddle_infer_shape.py的问题）：
transforms:
  - target_size:
    - 64
    - 64
    type: Resize
  - mean:
    - 0.78020299
    std:
    - 0.01534636
    type: Normalize
明显type不在它应该的位置。
在使用fastDeploy进行推理时，需要设置一个config文件，我设置为这个有问题的deploy.yaml它也能推理，但是我不知道model = fd.vision.segmentation.PaddleSegModel(model_file, params_file, config_file, runtime_option=runtime_option)是否正确加载了transforms的内容，请问这个文件正确的样子应该是怎样的呢？我使用paddle2onnx转了onnx模型使用onnxruntime进行推理（onnxruntime的数据预处理我确定就是我想要的），使用np.testing.assert_allclose进行比较，整体差距约8%，我感觉问题应该就在数据预处理的位置，但是我不知该如何进行检查，请问是否有办法确认在model.predict内部每一步图像如何变化，或者其他的建议呢

**Comment by jiangjiajun** [comment]
可以下载一个FastDeploy示例里面的Seg模型进对对比yaml，参照着修改.

预处理的逻辑可以参考这里 https://github.com/PaddlePaddle/FastDeploy/blob/develop/fastdeploy/vision/segmentation/ppseg/preprocessor.cc#L29
