### ISSUE TITLE
让用户自己选择模型，vision应该一怎么判断

### ISSUE THREAD

**Issue by monkeycc** [PaddlePaddle/FastDeploy#237]
让用户自己选择模型的文件夹

那么我应该怎么判断模型种类

然后判断 逻辑处理 对应的
```
vision.classification.PaddleClasModel(model_file, params_file, config_file,)
vision.detection.YOLOv3(model_file, params_file, config_file,)
vision.detection.PPYOLO(model_file, params_file, config_file)
vision.detection.FasterRCNN(model_file, params_file, config_file)
vision.detection.MaskRCNN(model_file, params_file, config_file)
```

是否增加一个判断模型种类的函数

**Comment by ChaoII** [comment]
> 让用户自己选择模型的文件夹
> 
> 那么我应该怎么判断模型种类
> 
> 然后判断 逻辑处理 对应的
> 
> ```
> vision.classification.PaddleClasModel(model_file, params_file, config_file,)
> vision.detection.YOLOv3(model_file, params_file, config_file,)
> vision.detection.PPYOLO(model_file, params_file, config_file)
> vision.detection.FasterRCNN(model_file, params_file, config_file)
> vision.detection.MaskRCNN(model_file, params_file, config_file)
> ```
> 
> 是否增加一个判断模型种类的函数

搞个枚举值，一个个枚举。

**Comment by DefTruth** [comment]
可以考虑用python的isinstance进行判断：
```python
if isinstance(model, vision.detection.YOLOv3):
    # do some things
elif isinstance(model, vision.detection.PPYOLO):
    # do some things
elif isinstance(model, vision.detection.FasterRCNN):
    # do some things
else:
    pass
```
