### ISSUE TITLE
./infer_demo: error while loading shared libraries: libonnxruntime.so.1.12.0: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by chlg** [PaddlePaddle/FastDeploy#2372]
./infer_demo: error while loading shared libraries: libonnxruntime.so.1.12.0: cannot open shared object file: No such file or directory

**Comment by jiangjiajun** [comment]
Refer the quick start tutorial, it shows how to solve this problem. https://github.com/PaddlePaddle/FastDeploy/blob/develop/docs/cn/quick_start/models/cpp.md
