### ISSUE TITLE
Orange Pi AIpro , 采用 华为昇腾NPU  , 希望加入硬件支持

### ISSUE THREAD

**Issue by monkeycc** [PaddlePaddle/FastDeploy#2373]
http://www.orangepi.cn/html/hardWare/computerAndMicrocontrollers/details/Orange-Pi-AIpro.html
自带 pytorch_npu   CANN

https://github.com/PaddlePaddle/FastDeploy/blob/develop/docs/cn/build_and_install/huawei_ascend.md
华为昇腾NPU 部署环境编译准备

感觉有点不一样

希望加入支持

**Comment by jiangjiajun** [comment]
对于其它的硬件暂不在支持计划内，但如果有开发者愿意贡献，我可以协助Review合入。
