### ISSUE TITLE
fastdeploy预编译库无法使用

### ISSUE THREAD

**Issue by a819411321** [PaddlePaddle/FastDeploy#2374]
*********************************************
温馨提示：根据社区不完全统计，按照模板提问，可以加快回复和解决问题的速度
*********************************************

## 环境

- 【FastDeploy版本】： fastdeploy-win-x64-gpu-1.0.7
- 【系统平台】: win11
- 【硬件】： Nvidia GPU 3060， CUDA 11.7 CUDNN 8.7
- 【编译语言】： C++ 
- 【编译器】： msvc2022 

## 问题日志及出现问题的操作流程
- 【官方示例报错】
下载了fastdeploy-win-x64-gpu-1.0.7，以及按照官方示例下载了ppyoloe_crn_l_300e_coco和test_det.jpg，以及代码infer_demo.cc。
目录结构
fastdeploy_test/
                        build
                        ppyoloe_crn_l_300e_coco
                        CmakeLists.txt
                        test_det.jpg

按照官方操作
mkdir build
cd build
cmake .. -G "Visual Studio 17 2022" -A x64（原版 cmake .. -G "Visual Studio 16 2019" -A x64）
出现报错
`
PS D:\AI_lib\fastdeploy_test\build> cmake .. -G "Visual Studio 17 2022" -A x64
-- The C compiler identification is MSVC 19.37.32825.0
-- The CXX compiler identification is MSVC 19.37.32825.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.37.32822/bin/Hostx64/x64/cl.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.37.32822/bin/Hostx64/x64/cl.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- The path of ONNXRuntime is D:/AI_lib/fastdeploy-win-x64-gpu-1.0.7/third_libs/install/onnxruntime/lib.
-- OPENVINO_LIBS = D:/AI_lib/fastdeploy-win-x64-gpu-1.0.7/third_libs/install/openvino/runtime/lib/openvino.lib;TBB::tbb;TBB::tbbmalloc
CMake Error at D:/AI_lib/fastdeploy-win-x64-gpu-1.0.7/FastDeploy.cmake:228 (message):
  [FastDeploy] Cannot find library cudart in /usr/local/cuda, Please define
  CUDA_DIRECTORY, e.g -DCUDA_DIRECTORY=/path/to/cuda
Call Stack (most recent call first):
  CMakeLists.txt:4 (include)

`

**Comment by Wsk0317** [comment]
请问问题解决了没，怎么解决的？
