### ISSUE TITLE
请问有没有基于CUDA 11.8的镜像？

### ISSUE THREAD

**Issue by neo502721** [PaddlePaddle/FastDeploy#2375]
*********************************************
温馨提示：根据社区不完全统计，按照模板提问，可以加快回复和解决问题的速度
*********************************************

## 环境

- 【FastDeploy版本】： 说明具体的版本，如fastdeploy-linux-gpu-0.8.0
- 【编译命令】如果您是自行编译的FastDeploy，请说明您的编译方式（参数命令）
- 【系统平台】: Linux x64(Ubuntu 18.04) 
- 【硬件】： CUDA 11.8

## 问题日志及出现问题的操作流程
请问有没有基于CUDA 11.8的镜像？

**Comment by rainyfly** [comment]
目前还没有编译基于cuda11.8的镜像

**Comment by neo502721** [comment]
好的，谢谢回复，先关闭了。
