### ISSUE TITLE
在使用fastdeploy进行推理时

### ISSUE THREAD

**Issue by menginbaidu** [PaddlePaddle/FastDeploy#2384]
*********************************************
温馨提示：根据社区不完全统计，按照模板提问，可以加快回复和解决问题的速度
*********************************************

## 环境

- 【FastDeploy版本】：registry.baidubce.com/paddlepaddle/fastdeploy:1.0.4-gpu-cuda11.4-trt8.5-21.10
- 【系统平台】: Linux x64(Ubuntu 18.04)
- 【硬件】： 说明具体硬件型号，如 Nvidia GPU 3080TI， CUDA 11.2 CUDNN 8.3
- 【编译语言】： Python3.8
按照官方给出的教程以及官方给出的模型，在请求时报错
![1315cd777b24376c82d849b434a89b29](https://github.com/PaddlePaddle/FastDeploy/assets/137677731/21c0e4a5-c08b-4668-87b1-0bb6beaaa334)

**Comment by heliqi** [comment]
是运行的什么模型？

**Comment by heliqi** [comment]
@menginbaidu  请给下运行的是哪个教程模型

**Comment by heliqi** [comment]
使用最新 1.0.7 镜像已修复: registry.baidubce.com/paddlepaddle/fastdeploy:1.0.7-gpu-cuda11.4-trt8.5-21.10
