### ISSUE TITLE
加载uie模型后是否可以动态修改配置

### ISSUE THREAD

**Issue by wanshichenguang** [PaddlePaddle/FastDeploy#2397]
uie = UIEModel(
    model_path,
    param_path,
    vocab_path,
    position_prob=0.5,
    max_length=256, 
    schema=schema,
    runtime_option=runtime_option)
是否可以动态修改position_prob、max_length、schema
而不需要去初始化模型

**Comment by rainyfly** [comment]
https://github.com/PaddlePaddle/FastDeploy/blob/develop/fastdeploy/text/uie/uie_pybind.cc
python层的接口不支持，看pybind里没有提供接口修改对应C++类里面的这三个属性，除非自己加一下重新编译看看
