### ISSUE TITLE
USA Team seeking english support

### ISSUE THREAD

**Issue by zevr10** [PaddlePaddle/FastDeploy#24]
Hello my friends -- we are a NYC based team interested to explore using the PaddlePaddle framework. Do you know any english-speaking members of the PaddlePaddle community that we may connect with?

Thank you
Zev

**Comment by leiqing1** [comment]
@purplesystems Hello, Do you have any problems with FastDeploy?
 If you have any questions using PaddlePaddle,  you can contact with the  PaddlePaddle community in english issue.

**Comment by leiqing1** [comment]
@purplesystems  hi welcome to FastDeploy Slack and share it with friends if in need https://join.slack.com/t/fastdeployworkspace/shared_invite/zt-1hhvpb279-iw2pNPwrDaMBQ5OQhO3Siw

**Comment by jiangjiajun** [comment]
此ISSUE由于一年未更新，将会关闭处理，如有需要，可再次更新打开。
