### ISSUE TITLE
--use_trt True 每一次build都要花费大量时间

### ISSUE THREAD

**Issue by kissablemt** [PaddlePaddle/FastDeploy#2406]
能否build一次后，有缓存，可以直接读取
https://github.com/PaddlePaddle/FastDeploy/tree/cc8d1f3c9f31ea4919972f14ee3eaaa9a09966e2/examples/vision/detection/yolov5lite/python
用的是这里的代码

**Comment by Jiang-Jia-Jun** [comment]
支持缓存，调用option.trt_option.serialize_file = "./test_model.trt"，即会在首次初始化后，将模型缓存至这个文件，再次执行时，如若此文件存在，会优先加载这个缓存的文件，跳过build步骤
