### ISSUE TITLE
cmake 编译，第三方库冗余、冲突的问题

### ISSUE THREAD

**Issue by LiuPeiqiCN** [PaddlePaddle/FastDeploy#241]
我在自己编译FastDeploy时，发现很多third_party都是直接下载使用的，感觉这好像是贵司的传统？下载的预编译库还带了个OpenCV3和onnxruntime的动态链接库，然而我自己的环境已经安装了特定版本的OpenCV4，onnxruntime，yaml-cpp等，我却无法链接这些已经存在的库，很容易出现多版本、静动态库混用的问题。所以能否增加使用系统已安装库的编译选项？

**Comment by DefTruth** [comment]
请问您比较关注哪些依赖库的可以定制化编译呢？

**Comment by LiuPeiqiCN** [comment]
如果OpenCV、onnxruntime、yaml-cpp可以定制化编译就好了，其他的paddle2onnx和paddle_inference等paddle系的可以直接下载倒是蛮方便的。

**Comment by jiangjiajun** [comment]
@liupeiqiHN 感谢你的使用反馈。 在先前引入第三方库时，为了简化编译过程，因为对部分库采用了自动下载的方式。 但你上面提到的“增加已安装库编译选项”这个确实需要考虑。 我们争取在0.3版本完成编译体验的优化。

**Comment by LiuPeiqiCN** [comment]
不支持静态静态编译
https://github.com/PaddlePaddle/FastDeploy/blob/e4eff9f9b549dea789ee831043d088d564b9d175/fastdeploy/utils/utils.h#L26
```
#if defined(_WIN32)
#ifdef FASTDEPLOY_LIB
#define FASTDEPLOY_DECL __declspec(dllexport)
#else
#define FASTDEPLOY_DECL __declspec(dllimport)
#endif  // FASTDEPLOY_LIB
#else
#define FASTDEPLOY_DECL __attribute__((visibility("default")))
#endif  // _WIN32
```

**Comment by jiangjiajun** [comment]
此ISSUE由于一年未更新，将会关闭处理，如有需要，可再次更新打开。
