### ISSUE TITLE
sophon se7 编译安装 执行失败

### ISSUE THREAD

**Issue by SweatLin** [PaddlePaddle/FastDeploy#2410]
*********************************************
温馨提示：根据社区不完全统计，按照模板提问，可以加快回复和解决问题的速度
*********************************************

## 环境
采用算能编译部署：
# Download the latest source code
git clone https://github.com/PaddlePaddle/FastDeploy.git
cd FastDeploy/python
export ENABLE_SOPHGO_BACKEND=ON
export ENABLE_VISION=ON

python setup.py build
python setup.py bdist_wheel

cd dist
pip install fastdeploy_python-0.0.0-cp38-cp38-linux_aarch64.whl

- 【FastDeploy版本】：
-fastapi             0.110.0
fastdeploy-python   0.0.0
fastdeploy-tools    0.0.5
- 【系统平台】: Linux x64(Ubuntu 18.04) 
- 【硬件】： sophon se7
-

## 问题日志及出现问题的操作流程
- 附上详细的问题日志有助于快速定位分析

root@bm1684:/home/paddle/ppliteseg# python3 ppliteseg_fastdeploy_sophon.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/fastdeploy/c_lib_wrap.py", line 164, in <module>
    from .libs.fastdeploy_main import *
ImportError: libopencv_flann.so.3.4: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "ppliteseg_fastdeploy_sophon.py", line 6, in <module>
    import fastdeploy as fd
  File "/usr/local/lib/python3.8/dist-packages/fastdeploy/__init__.py", line 122, in <module>
    from .c_lib_wrap import (
  File "/usr/local/lib/python3.8/dist-packages/fastdeploy/c_lib_wrap.py", line 166, in <module>
    raise RuntimeError(f"FastDeploy initalized failed! Error: {e}")
RuntimeError: FastDeploy initalized failed! Error: libopencv_flann.so.3.4: cannot open shared object file: No such file or directory
运行报错

**Comment by heliqi** [comment]
你系统没有提前安装opencv， 安装完opencv即可
