### ISSUE TITLE
fastdeploy 服务化部署paddleocr如何调整输入图片为base64编码

### ISSUE THREAD

**Issue by KyleWang-Hunter** [PaddlePaddle/FastDeploy#2411]
我现在试着用fastdeploy服务化部署的方式部署paddleocrv3模型，但是输入的图片是一个list，这也太慢了吧。有没有可以将输入数据转换为base64的参考资料？

**Comment by heliqi** [comment]
你可以自己改造下preprocess部分的代码，把输入从矩阵改成base64即可。 
目前没提供这种例子，但改造应该很容易。 你可以提pr到仓库，我帮你review看看是否改的ok

**Comment by ouerum** [comment]
请问下改造好的pr有了么？
