### ISSUE TITLE
文档中的链接失效

### ISSUE THREAD

**Issue by TingquanGao** [PaddlePaddle/FastDeploy#2413]
[文档](https://github.com/PaddlePaddle/FastDeploy/blob/develop/serving/README_CN.md)中关于PPOCR的[链接](https://github.com/PaddlePaddle/FastDeploy/blob/develop/serving/README_CN.md)失效：

<img width="488" alt="image" src="https://github.com/PaddlePaddle/FastDeploy/assets/12560511/31737d42-c606-478a-9eba-3353ef092b2b">

**Comment by heliqi** [comment]
多谢指出，新的链接在： https://github.com/PaddlePaddle/FastDeploy/tree/develop/examples/vision/ocr/PP-OCR/serving/fastdeploy_serving

也欢迎提PR帮忙修复问题
