### ISSUE TITLE
多模型共用一个infer_cfg.yaml，扩展Label_list字段后，预测返回label_id

### ISSUE THREAD

**Issue by njflove** [PaddlePaddle/FastDeploy#2416]
## 环境

- 【FastDeploy版本】：fastdeploy-python-1.0.7
- 【系统平台】:  Windows x64(Windows10)
- 【硬件】： i5-6400 CPU
- 【编译语言】：Python3.8

## 问题日志及出现问题的操作流程
- 【DET_RESULT】
    我使用ensemble启动两个模型（picodet_l_640_coco_lcnet_cpu、picodet_l_640_coco_lcnet_hd）共用postprocess/1/infer_cfg.ymal，并将两个模型的label_list合并保存，但无论是调用picodet_l_640_coco_lcnet_cpu还是picodet_l_640_coco_lcnet_hd，返回的预测结果abel_ids字段总为0。是我没有弄对，还是说本身就不可以这样做？

- 【模型仓库】
![image](https://github.com/PaddlePaddle/FastDeploy/assets/41934985/de110225-5512-4251-874a-ad4aae5b3ef5)
-  【infer_cfg.yaml内容】
![image](https://github.com/PaddlePaddle/FastDeploy/assets/41934985/4de5c2a0-5560-47db-b141-5160861754a7)
-  【预测及返回结果】
![image](https://github.com/PaddlePaddle/FastDeploy/assets/41934985/1e7e1623-6839-4b6d-8817-5c1864e0dff2)

新手上路，还请大佬赐教。

**Comment by heliqi** [comment]
你先试试不合并，单独使用是否返回正常。 先确认下模型或者后处理是正常的，再进一步看合并。
理论上： 后处理使用同一个postprocess是ok的， 但是label-list和infer_cfg.ymal合并需要特殊处理下后处理逻辑

**Comment by njflove** [comment]
> 你先试试不合并，单独使用是否返回正常。 先确认下模型或者后处理是正常的，再进一步看合并。 理论上： 后处理使用同一个postprocess是ok的， 但是label-list和infer_cfg.ymal合并需要特殊处理下后处理逻辑

我的两个模型picodet_l_640_coco_lcnet_cpu、picodet_l_640_coco_lcnet_hd都是单分类的，所以单独使用返回0是没有问题的，现在我主要想实现多个模型共用一个preprocess和postprocess，因为后面我们还需要训练很多个模型，单独来做太复杂了。另外您说label-list和infer_cfg.ymal合并需要特殊处理，这个有什么可参考的资料吗？

**Comment by heliqi** [comment]
我举个例子：
假设模型A的label是 0、1、2； 模型B的label是 0、1
那么 合并后的label-list 是0、1、2、3、4， 但是模型输出的分类还是0、1、2和0、1， 这时需要你模型B的后处理里把分类结果从0、1映射为 3、4

暂时没有参考的例子

**Comment by njflove** [comment]
> 我举个例子： 假设模型A的label是 0、1、2； 模型B的label是 0、1 那么 合并后的label-list 是0、1、2、3、4， 但是模型输出的分类还是0、1、2和0、1， 这时需要你模型B的后处理里把分类结果从0、1映射为 3、4
> 
> 暂时没有参考的例子

好的，我找些资料尝试修改下，非常感谢答复。
