### ISSUE TITLE
在执行examples下的关键点rknn模型推理测试时出现未知输入参数。

### ISSUE THREAD

**Issue by xianningblog** [PaddlePaddle/FastDeploy#2417]
*********************************************
温馨提示：根据社区不完全统计，按照模板提问，可以加快回复和解决问题的速度
*********************************************

## 环境

- 【FastDeploy版本】： 说明具体的版本，如fastdeploy 3.0.11
- 【系统平台】: Linux x64(Ubuntu 20.04) 
- 【硬件】： Nvidia GPU 2080TI， CUDA 12.2 
- 【编译语言】： python 3.8

## 问题日志及出现问题的操作流程
在执行examples下的关键点rknn模型推理测试时出现未知输入参数。
即输入python pptinypose_infer.py --tinypose_model_dir PP_TinyPose_256x192_infer --image hrnet_demo.jpg后报以下错误。
![QQ图片20240328113244](https://github.com/PaddlePaddle/FastDeploy/assets/52063950/03224efd-4adf-4410-aff8-cfa0e59a07de)

**Comment by heliqi** [comment]
python pptinypose_infer.py --help 可以看看参数是否都正确
