### ISSUE TITLE
RuntimeError: tensor type 0 is not supported

### ISSUE THREAD

**Issue by ZhangLe-fighting** [PaddlePaddle/FastDeploy#242]
按照教程替换模型与demo图片，如上述报错，如何修改输入呢？
模型是ppyoloe
输入是2k图

**Comment by ZhangLe-fighting** [comment]
[ERROR] csrc/fastdeploy/backends/ort/utils.cc(30)::GetOrtDtype	Unrecognized fastdeply data type:FDDataType::UINT8.
Traceback (most recent call last):
  File "main.py", line 9, in <module>
    result = model.predict(im.copy())
  File "/home/hik/anaconda3/envs/paddle_pkg/lib/python3.6/site-packages/fastdeploy/vision/detection/ppdet/__init__.py", line 38, in predict
    return self._model.predict(input_image)
RuntimeError: tensor type 0 is not supported

**Comment by ZhangLe-fighting** [comment]
测试如下：  
1 import cv2
  2 import fastdeploy.vision as vision
  3 
  4 
  5 model = vision.detection.PPYOLOE("m/model.pdmodel",
  6                                  "m/model.pdiparams",
  7                                  "m/infer_cfg.yml")
  8 im = cv2.imread("Images/1.jpg")
  9 result = model.predict(im.copy())
 10 print(result)
 11 
 12 vis_im = vision.vis_detection(im, result, score_threshold=0.5)
 13 cv2.imwrite("vis_image.jpg", vis_im)

**Comment by jiangjiajun** [comment]
你好，方便提供一下你的模型吗？这个问题正在修复中，预计今下午发版的0.2.1版本就可以支持

**Comment by ZhangLe-fighting** [comment]
十分抱歉，模型涉及到公司项目，是不能提供的，
模型是使用PaddleDetection_YOLOSeries/configs/ppyoloe/ppyoloe_crn_l_300e_coco.yml这个配置训练的

**Comment by jiangjiajun** [comment]
@ZhangLe-fighting 在导出模型时，是有额外将归一化集成到模型里面了吗？

**Comment by ZhangLe-fighting** [comment]
python tools/export_model.py -c configs/ppyoloe/ppyoloe_crn_l_300e_coco.yml -o weights=output/ppyoloe_crn_l_300e_coco/best_model.pdparams

这个是我导出模型时，运行的指令

**Comment by jiangjiajun** [comment]
@ZhangLe-fighting  试下先卸载现有的fastdeploy

安装下0.2.1版本的fastdeploy，下载链接如下

- CPU版本： https://bj.bcebos.com/fastdeploy/dev/wheels/fastdeploy_python-0.2.1-cp36-cp36m-manylinux1_x86_64.whl
- GPU版本： https://bj.bcebos.com/fastdeploy/dev/wheels/fastdeploy_gpu_python-0.2.1-cp36-cp36m-manylinux1_x86_64.whl

麻烦测试后反馈下哈

**Comment by ZhangLe-fighting** [comment]
您好，该问题已修复，现在可以正常使用，但是我现在想把结果按照列表的形式返回文本并存储，只能自己处理输出的结果嘛？

**Comment by ZhangLe-fighting** [comment]
有没有关于fastdeploy的相关api函数的说明呀

**Comment by jiangjiajun** [comment]
具体可以查看每个模型对应的api说明， example/vision/detection/paddledetection/python和cpp目录下的README分别有其python/api说明

**Comment by ZhangLe-fighting** [comment]
问一下，现在支持GPU推理嘛，我设置了一下没成功诶

**Comment by jiangjiajun** [comment]
支持，注意安装GPU的包， 参考项目Readme里面的安装说明。

如若已经安装了cpu的包，请注意先卸载

**Comment by ZhangLe-fighting** [comment]
您好：
python tools/export_model.py -c configs/ppyoloe/ppyoloe_crn_l_300e_coco.yml -o weights=output/ppyoloe_crn_l_300e_coco/best_model.pdparams

RuntimeError: /onnxruntime_src/onnxruntime/core/providers/cuda/cuda_call.cc:122 bool onnxruntime::CudaCall(ERRTYPE, const char*, const char*, ERRTYPE, const char*) [with ERRTYPE = cudaError; bool THRW = true] /onnxruntime_src/onnxruntime/core/providers/cuda/cuda_call.cc:116 bool onnxruntime::CudaCall(ERRTYPE, const char*, const char*, ERRTYPE, const char*) [with ERRTYPE = cudaError; bool THRW = true] CUDA failure 3: initialization error ; GPU=490585848 ; hostname=Thor ; expr=cudaSetDevice(info_.device_id); 

将export的模型部署在英伟达T4卡上时，出现了如上的错误，不太明白是什么原因导致的，如果您了解的话，麻烦解答一下。

**Comment by jiangjiajun** [comment]
Hi，请问能跑Tensort吗，当前看是ONNX Runtim报错了

**Comment by ZhangLe-fighting** [comment]
我刚入门...不太懂，Tensort和CUDA是平行的库嘛，就是使用Tensort可以避免CUDA版本不一致的问题嘛？

**Comment by ZhangLe-fighting** [comment]
我打包环境的cuda版本是11.2，使用了当前这个套件，目前部署的环境cuda版本是10.1，问一下这是不是报错的主要原因呢？

**Comment by DefTruth** [comment]
应该是的，部署环境的CUDA版本是需要和您编译时的保持一致的。

**Comment by ZhangLe-fighting** [comment]
如果使用这个套件的话，只能升级部署环境嘛？
这个套件支持CUDA10.1嘛？因为我这边可能没办法升级部署环境

**Comment by ZhangLe-fighting** [comment]
官方能发布支持多个CUDA版本的套件不 ？。？

**Comment by ZhangLe-fighting** [comment]
官方您好，问一下能否发布一个支持CUDA10.1的分支，部署端环境没办法升级呜呜呜

**Comment by jiangjiajun** [comment]
如果你只是需要TensorRT部署，可以自行编译FastDeploy。 当前Cuda 10.1上只能支持TensorRT

**Comment by ZhangLe-fighting** [comment]
> 如果你只是需要TensorRT部署，可以自行编译FastDeploy。 当前Cuda 10.1上只能支持TensorRT

我去TensorRT官网看了一下，没有找到CUDA10.1对应的发行版本，请问需要下载哪个版本呢？

**Comment by jiangjiajun** [comment]
> > 如果你只是需要TensorRT部署，可以自行编译FastDeploy。 当前Cuda 10.1上只能支持TensorRT
> 
> 我去TensorRT官网看了一下，没有找到CUDA10.1对应的发行版本，请问需要下载哪个版本呢？

下载10.2对应的即可

**Comment by ZhangLe-fighting** [comment]
麻烦您提供一下python编译选项的设置...

**Comment by jiangjiajun** [comment]
> 麻烦您提供一下python编译选项的设置...


```
git clone https://github.com/PaddlePaddle/FastDeploy.git
cd FastDeploy/python

export ENABLE_TRT_BACKEND=ON
export ENABLE_VISION=ON
export ENABLE_OPENVINO_BACKEND=ON
export WITH_GPU=ON
export TRT_DIRECTORY=/trt/xxxx
export CUDA_DIRECTORY=/usr/loca/cuda-10.2

python setup.py build
python setup.py bdist_wheel
```

**Comment by ZhangLe-fighting** [comment]
环境搞了一天没搞好，555555555555555
打算明天用 paddleinference 部署试一下...

**Comment by jiangjiajun** [comment]
> 环境搞了一天没搞好，555555555555555
> 打算明天用 paddleinference 部署试一下...

方便的话，可以加我们微信群，了解下你具体遇到啥问题

**Comment by ZhangLe-fighting** [comment]
InvalidArgumentError: The type of data we are trying to retrieve does not match the type of data currently contained in the container.
      [Hint: Expected dtype() == paddle::experimental::CppTypeToDataType<T>::Type(), but received dtype():10 != paddle::experimental::CppTypeToDataType<T>::Type():12.] (at /paddle/paddle/phi/core/dense_tensor.cc:137)
      [operator < elementwise_mul > error]

使用paddleinference推理，没用到infer_cfg.yml这个文件，然后按照教程将图片使用cv2读取，resize\transpose之后输入出现如上错误，请问有没有具体的教程呀，就是图片输入如何处理，然后加载pdmodel和pdiparams文件包含infer_cfg.yml的信息嘛，比如target_size之类的信息，上面错误好像是输入处理的不对...

**Comment by ZhangLe-fighting** [comment]
> > 环境搞了一天没搞好，555555555555555
> > 打算明天用 paddleinference 部署试一下...
> 
> 方便的话，可以加我们微信群，了解下你具体遇到啥问题

好滴

**Comment by ZhangLe-fighting** [comment]
CMake Error at CMakeLists.txt:281 (find_package):
  By not providing "FindOpenCV.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "OpenCV", but
  CMake did not find one.

  Could not find a package configuration file provided by "OpenCV" with any
  of the following names:

    OpenCVConfig.cmake
    opencv-config.cmake

  Add the installation prefix of "OpenCV" to CMAKE_PREFIX_PATH or set
  "OpenCV_DIR" to a directory containing one of the above files.  If "OpenCV"
  provides a separate development package or SDK, be sure it has been
  installed.

进行编译的时候出现这个错误，但是我并没有找到这个文件

**Comment by jiangjiajun** [comment]
<img width="310" alt="image" src="https://user-images.githubusercontent.com/19339784/192506650-909ec3f6-6b82-4c7f-9e26-1ce8fb6209d0.png">
加入这个微信群在线沟通哈

**Comment by ZhangLe-fighting** [comment]
加了...没人回答我的问题呀

**Comment by jiangjiajun** [comment]
在群里找到我头像，直接加我吧

**Comment by jiangjiajun** [comment]
此ISSUE由于一年未更新，将会关闭处理，如有需要，可再次更新打开。
