### ISSUE TITLE
c#编译fastdeploy，在nuget restore时出现报错：无法计算表达式“[MSBuild]::NormalizePath('', '')”。参数“path”的长度不能为零。

### ISSUE THREAD

**Issue by gunh4mmer** [PaddlePaddle/FastDeploy#2438]
*********************************************
温馨提示：根据社区不完全统计，按照模板提问，可以加快回复和解决问题的速度
*********************************************

## 环境

- 【编译命令】
- cmake .. -G "Visual Studio 16 2019" -A x64 ^
         -DENABLE_ORT_BACKEND=ON ^
         -DENABLE_PADDLE_BACKEND=ON ^
         -DENABLE_OPENVINO_BACKEND=ON ^
         -DENABLE_TRT_BACKEND=ON ^
         -DENABLE_VISION=ON ^
         -DENABLE_TEXT=ON ^
         -DWITH_GPU=ON ^
         -DWITH_CSHARPAPI=ON ^
         -DTRT_DIRECTORY="D:\TensorRT-8.6.1.6" ^
         -DCUDA_DIRECTORY="C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.7" ^
         -DCMAKE_INSTALL_PREFIX="D:\paddle_fastdeploy"

- 【系统平台】:  Windows x64(Windows10)
- 【硬件】：  Nvidia GPU 3060ti， CUDA 11.7 CUDNN 8.6.0  tensorRT GA 8.6（8.6.1.6）
- 【编译语言】：c#

错误信息如下图：
<img width="628" alt="EE175819-1525-47b6-B9FA-47D3473CEE2B" src="https://github.com/PaddlePaddle/FastDeploy/assets/73456895/aba04f09-1ffc-49ed-83ab-504486681d36">

**Comment by heliqi** [comment]
应该是传的cuda路径有字符转义的问题，导致路径组合时报错。 
1. 可以对一些特殊字符 / 空格 等用转义处理下
2. 目录不要用中文名

**Comment by gunh4mmer** [comment]
该问题已解决，在电脑上重新配置了推荐环境，即cuda11.2， cudnn8.4.1.50，tensorRT8.5.2.2解决问题
