### ISSUE TITLE
FastDeploy预计啥时候支持PP OCR V4的模型？

### ISSUE THREAD

**Issue by GentlerMan** [PaddlePaddle/FastDeploy#2444]
FastDeploy预计啥时候支持PP OCR V4的模型？另外请教下，现阶段在线的星河PaddleX的模型，是否均支持使用FastDeploy进行推理，目前测试的是支持C++和Py，如果使用C#编译版是否也能支持使用？

**Comment by heliqi** [comment]
官方没有计划支持新的OCR模型，需要开发者贡献下。 
理论上可以用FD推理，但如果是不支持或较新的模型，在前后处理上会有问题
