### ISSUE TITLE
希望增加pp-shitu部署的更多示例

### ISSUE THREAD

**Issue by lemon3853** [PaddlePaddle/FastDeploy#2456]
pp-shitu只有det和rec单独使用的demo
希望增加Pipeline完整示例

**Comment by Jiang-Jia-Jun** [comment]
可以自行部署组合。

**Comment by lemon3853** [comment]
> 可以自行部署组合。

![image](https://github.com/PaddlePaddle/FastDeploy/assets/59115919/8d3e72ec-b8df-4c71-b5ad-1899d055c836)
安卓sdk好像也没有封装shitu的api呀
