### ISSUE TITLE
这个源码能在cuda10.2+cudnn7.6.5上进行编译吗

### ISSUE THREAD

**Issue by futureflsl** [PaddlePaddle/FastDeploy#246]
我在windows10 x64用VS2019+cuda10.2+cudnn7.6.5编译总出错

**Comment by jiangjiajun** [comment]
当前仅适配了cuda 11, cudnn8。 在cuda10上编译不兼容

**Comment by ZhangLe-fighting** [comment]
> cuda10

问一下，目前有计划支持CUDA10.1嘛，我这边需要部署的硬件都是CUDA10.1的，而且应该设备没有升级的计划

**Comment by jiangjiajun** [comment]
此ISSUE由于一年未更新，将会关闭处理，如有需要，可再次更新打开。
