### ISSUE TITLE
fastdeploy的sophgo开发案例，ppyoloe正常转模型及推理，转picodet模型为bmodel正常，推理结果出错，yolov8还未开始调试

### ISSUE THREAD

**Issue by yscolc** [PaddlePaddle/FastDeploy#2460]
请各位大佬进行指教，具体信息及操作如下：

## 环境
- 【FastDeploy版本】: 自行编译
- 【编译命令】自行编译的FastDeploy，参考[SOPHGO 部署库编译](https://github.com/PaddlePaddle/FastDeploy/blob/release/1.0.7/docs/cn/build_and_install/sophgo.md)  进行的python版本编译，SOPHGO 的环境版本统一为0.4.9
- 【系统平台】: 系统--Ubuntu 20.04.4  硬件架构--arm64
- 【硬件】： 具体硬件型号，sophgo  bm1684 aarch64
- 【编译语言】：  Python 3.8.10

## 问题日志及出现问题的操作流程

1. 按照ppyoloe转模型案例，跑通ppyoloe模型的转换及推理，print打印的结果及result图片正常显示
2. 根据ppyoloe转模型案例，picodet模型的bmodel转换成功，但是推理结果不正确。转模型具体操作命令如下：
- paddle2onnx --model_dir picodet_s_320_coco_lcnet --model_filename model.pdmodel --params_filename model.pdiparams --save_file picodet_s_320_coco_lcnet.onnx --enable_dev_version True
- python -m paddle2onnx.optimize --input_model picodet_s_320_coco_lcnet.onnx --output_model picodet_s_320_coco_lcnet.onnx --input_shape_dict "{'image':[1,3,640,640]}"
- model_transform.py --model_name picodet_s_320_coco_lcnet --model_def ../picodet_s_320_coco_lcnet.onnx --input_shapes [[1,3,640,640],[1,2]] --keep_aspect_ratio --pixel_format rgb --output_names p2o.Div.79,p2o.Concat.9 --mlir picodet_s_320_coco_lcnet.mlir
- model_deploy.py --mlir picodet_s_320_coco_lcnet.mlir --quantize F32 --chip bm1684 --model picodet_s_320_coco_lcnet_f32.bmodel

3.推理部分代码如下图：
![image](https://github.com/PaddlePaddle/FastDeploy/assets/96225888/bf6501f9-8d9c-4852-b432-b49bc0d029b4)

4.推理print的结果如下图：
![image](https://github.com/PaddlePaddle/FastDeploy/assets/96225888/a23f8f01-d792-4a72-80df-ad5d2468273c)

5.推理后的sophgo_result_picodet.jpg无改变：
![image](https://github.com/PaddlePaddle/FastDeploy/assets/96225888/bb5e4f7e-5446-4fbf-966f-28891ba25c6b)

**Comment by heliqi** [comment]
可能是转换过程有问题，你可以排查下前后处理的结果是否有问题

**Comment by yscolc** [comment]
> 可能是转换过程有问题，你可以排查下前后处理的结果是否有问题

已解决、tpu-mlir的bug，升级最新版即可
