### ISSUE TITLE
Failed to build on Ubuntu 20

### ISSUE THREAD

**Issue by danhdoan** [PaddlePaddle/FastDeploy#2467]
## Environment

FastDeploy version: 1.0.7
OS Platform: Linux x64 (Ubuntu 20.04)
Hardware: AMD Ryzen 5, GeForce RTX 3060
Program Language: C#

## Problem description
After compiling FastDeploy, application is built successfully, but failed to run

libonnxruntime.so.1.12.0: cannot open shared object file: No such file or directory
/usr/share/dotnet/shared/Microsoft.NETCore.App/8.0.4/fastdeploy.dll.so: cannot open shared object file: No such file or directory
/project_path/bin/Debug/net8.0/fastdeploy.dll.so: cannot open shared object file: No such file or directory
/project_path/bin/Debug/net8.0/runtimes/linux-x64/native/libfastdeploy.dll.so: cannot open shared object file: No such file or directory
/usr/share/dotnet/shared/Microsoft.NETCore.App/8.0.4/libfastdeploy.dll.so: cannot open shared object file: No such file or directory
/project_path/bin/Debug/net8.0/libfastdeploy.dll.so: cannot open shared object file: No such file or directory
/project_path/bin/Debug/net8.0/runtimes/linux-x64/native/fastdeploy.dll: cannot open shared object file: No such file or directory
/usr/share/dotnet/shared/Microsoft.NETCore.App/8.0.4/fastdeploy.dll: cannot open shared object file: No such file or directory
/project_path/bin/Debug/net8.0/fastdeploy.dll: cannot open shared object file: No such file or directory
/project_path/bin/Debug/net8.0/runtimes/linux-x64/native/libfastdeploy.dll: cannot open shared object file: No such file or directory
/usr/share/dotnet/shared/Microsoft.NETCore.App/8.0.4/libfastdeploy.dll: cannot open shared object file: No such file or directory
/project_path/bin/Debug/net8.0/libfastdeploy.dll: cannot open shared object file: No such file or directory

Could you suggest a detailed document to compile and link dynamic library to the current project?

**Comment by Jiang-Jia-Jun** [comment]
Refer this doc https://github.com/PaddlePaddle/FastDeploy/blob/develop/docs/en/faq/use_sdk_on_linux.md

**Comment by danhdoan** [comment]
Thanks!
