### ISSUE TITLE
在rk3588上部署paddleseg模型，发现在性能十分不如意，有没有办法提高npu的占用率或者是多核调用？

### ISSUE THREAD

**Issue by Gary-zyt** [PaddlePaddle/FastDeploy#2478]
在瑞芯微rk3588上部署paddleseg的模型（如pp-liteseg），发现在npu只调用Core0，且占用率只有5%-15%左右，有没有办法提高npu的占用率或者是多核调用？python语言下,预测代码如下所示：
import fastdeploy as fd
import cv2
import os

def parse_arguments():
    import argparse
    import ast
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--model_file", required=True, help="Path of PaddleSeg model.")
    parser.add_argument(
        "--config_file", required=True, help="Path of PaddleSeg config.")
    parser.add_argument(
        "--image", type=str, required=True, help="Path of test image file.")
    return parser.parse_args()

def build_option(args):
    option = fd.RuntimeOption()
    option.use_rknpu2()
    return option

args = parse_arguments()

# setup runtime
runtime_option = build_option(args)
model_file = args.model_file
params_file = ""
config_file = args.config_file
model = fd.vision.segmentation.PaddleSegModel(
    model_file,
    params_file,
    config_file,
    runtime_option=runtime_option,
    model_format=fd.ModelFormat.RKNN)

model.preprocessor.disable_normalize()
model.preprocessor.disable_permute()

# predict
im = cv2.imread(args.image)
result = model.predict(im)
print(result)

# visualize
vis_im = fd.vision.vis_segmentation(im, result, weight=0.5)
cv2.imwrite("vis_img.png", vis_im)

**Comment by Gary-zyt** [comment]
能否在runtime_option中设定调用多个npu？官方文档中我只看到，选择调用npu或cpu，但目前调用npu发现只能调用单个的（Core0）
model = fd.vision.segmentation.PaddleSegModel(
model_file,
params_file,
config_file,
runtime_option=runtime_option,
model_format=fd.ModelFormat.RKNN)

**Comment by Jiang-Jia-Jun** [comment]
暂时不支持

**Comment by Gary-zyt** [comment]
> 暂时不支持



> 暂时不支持

好的

**Comment by NyquistBodeTu** [comment]
现在有没有支持多npu推理啊，ocr只有3~4帧，处于完全不能用的状态
