### ISSUE TITLE
PaddleSeg (OCRNet and PPliteSeg) output is not correct

### ISSUE THREAD

**Issue by universea** [PaddlePaddle/FastDeploy#2489]
## Environment

FastDeploy version:1.0.7
OS Platform: e.g. Linux x64
Hardware: e.g. Nvidia GPU 4090  CUDA 12.4 CUDNN 8.3
Program Language: e.g. Python 3.10

## Problem description
I have try different options:

"option.use_gpu()
option.use_paddle_backend() # Paddle Inference
option.use_trt_backend() # TensorRT
option.use_openvino_backend() # OpenVINO
option.use_ort_backend() # ONNX Runtime"

All the output is zero.

<img width="607" alt="1720575196977" src="https://github.com/PaddlePaddle/FastDeploy/assets/13444641/0430549e-25ec-4c8e-96d3-6c897a9b483f">

**Comment by priyankavgalagali** [comment]
have you tried with other images and also can you tell which kind of images is that? if possible?

**Comment by universea** [comment]
> have you tried with other images and also can you tell which kind of images is that? if possible?

Thanks for your reply, I have tried to use the result to draw the mask by using matplotlib, it is ok now.

But this api vis_im = fd.vision.vis_segmentation(im, result, weight=0.5) not work.


import matplotlib.pyplot as plt


shape = result.shape  # 例如 [544, 656]
label_map = result.label_map  # 例如 [0, 0, 0, ..., 0]

label_map_np = np.array(label_map)

label_map_np = label_map_np.reshape(shape)

print("Label Map Shape:", label_map_np.shape)

original_image = im


masked_image = original_image.copy()
masked_image[label_map_np > 0] = [255, 0, 0]  # 用红色显示掩码部分


plt.figure(figsize=(12, 6))
plt.subplot(1, 2, 1)
plt.title("Original Image")
plt.imshow(cv2.cvtColor(original_image, cv2.COLOR_BGR2RGB))

plt.subplot(1, 2, 2)
plt.title("Masked Image")
plt.imshow(cv2.cvtColor(masked_image, cv2.COLOR_BGR2RGB))

plt.show()
