### ISSUE TITLE
运行python代码报错condition: bindings[x] || nullBindingOK

### ISSUE THREAD

**Issue by MichaelSunEngineer** [PaddlePaddle/FastDeploy#2509]
*********************************************
温馨提示：根据社区不完全统计，按照模板提问，可以加快回复和解决问题的速度
*********************************************

## 环境

- 【FastDeploy版本】： deploy自己编译
- 【编译命令】export ENABLE_ORT_BACKEND=ON
                        export ENABLE_PADDLE_BACKEND=OFF
                        export ENABLE_OPENVINO_BACKEND=OFF
                        export ENABLE_VISION=ON
                        export ENABLE_TEXT=OFF
                        export ENABLE_TRT_BACKEND=ON
                        export WITH_GPU=ON
                        export CUDA_DIRECTORY=/usr/local/cuda
                        export TRT_DIRECTORY=/home/sh/soft/TensorRT-8.5.3.1/
- 【系统平台】: Linux x64(Ubuntu 22.04)
- 【硬件】： 笔记本 Nvidia GPU 1050， CUDA 11.4 CUDNN 8.6
- 【编译语言】：Python3.10

## 问题日志及出现问题的操作流程
- 【模型跑不通】
- - examples/vision/detection/paddledetection/python/infer_ppyoloe.py部署示例可以跑通，用的是ppyoloe_crn_l_300e_coco模型。
-但是当使用pphuman提供的ppyoloe_crn_s_36e_crowdhuman模型就会报错，模型连接为https://paddledet.bj.bcebos.com/models/ppyoloe_crn_s_36e_crowdhuman.pdparams
- 下载的模型也经过pp-detection(v2.7)的模型转换，加了trt=true
- 报错内容如下
[INFO] fastdeploy/vision/common/processors/transform.cc(45)::FuseNormalizeCast	Normalize and Cast are fused to Normalize in preprocessing pipeline.
[INFO] fastdeploy/vision/common/processors/transform.cc(93)::FuseNormalizeHWC2CHW	Normalize and HWC2CHW are fused to NormalizeAndPermute  in preprocessing pipeline.
[INFO] fastdeploy/vision/common/processors/transform.cc(159)::FuseNormalizeColorConvert	BGR2RGB and NormalizeAndPermute are fused to NormalizeAndPermute with swap_rb=1
[WARNING] fastdeploy/runtime/backends/tensorrt/trt_backend.cc(731)::CreateTrtEngineFromOnnx	Cannot build engine right now, because there's dynamic input shape exists, list as below,
[WARNING] fastdeploy/runtime/backends/tensorrt/trt_backend.cc(735)::CreateTrtEngineFromOnnx	Input 0: TensorInfo(name: image, shape: [-1, 3, 640, 640], dtype: FDDataType::FP32)
[WARNING] fastdeploy/runtime/backends/tensorrt/trt_backend.cc(735)::CreateTrtEngineFromOnnx	Input 1: TensorInfo(name: scale_factor, shape: [-1, 2], dtype: FDDataType::FP32)
[WARNING] fastdeploy/runtime/backends/tensorrt/trt_backend.cc(737)::CreateTrtEngineFromOnnx	FastDeploy will build the engine while inference with input data, and will also collect the input shape range information. You should be noticed that FastDeploy will rebuild the engine while new input shape is out of the collected shape range, this may bring some time consuming problem, refer https://github.com/PaddlePaddle/FastDeploy/blob/develop/docs/en/faq/tensorrt_tricks.md for more details.
[INFO] fastdeploy/runtime/runtime.cc(339)::CreateTrtBackend	Runtime initialized with Backend::TRT in Device::GPU.
start det
[WARNING] fastdeploy/runtime/backends/tensorrt/utils.cc(40)::Update	[New Shape Out of Range] input name: image, shape: [1, 3, 640, 640], The shape range before: min_shape=[-1, 3, 640, 640], max_shape=[-1, 3, 640, 640].
[WARNING] fastdeploy/runtime/backends/tensorrt/utils.cc(52)::Update	[New Shape Out of Range] The updated shape range now: min_shape=[1, 3, 640, 640], max_shape=[1, 3, 640, 640].
[WARNING] fastdeploy/runtime/backends/tensorrt/utils.cc(40)::Update	[New Shape Out of Range] input name: scale_factor, shape: [1, 2], The shape range before: min_shape=[-1, 2], max_shape=[-1, 2].
[WARNING] fastdeploy/runtime/backends/tensorrt/utils.cc(52)::Update	[New Shape Out of Range] The updated shape range now: min_shape=[1, 2], max_shape=[1, 2].
[WARNING] fastdeploy/runtime/backends/tensorrt/trt_backend.cc(330)::Infer	TensorRT engine will be rebuilt once shape range information changed, this may take lots of time, you can set a proper shape range before loading model to avoid rebuilding process. refer https://github.com/PaddlePaddle/FastDeploy/blob/develop/docs/en/faq/tensorrt_tricks.md for more details.
[INFO] fastdeploy/runtime/backends/tensorrt/trt_backend.cc(572)::BuildTrtEngine	Start to building TensorRT Engine...

[ERROR] fastdeploy/runtime/backends/tensorrt/trt_backend.cc(239)::log	3: [executionContext.cpp::enqueueInternal::629] Error Code 3: API Usage Error (Parameter check failed at: runtime/api/executionContext.cpp::enqueueInternal::629, condition: bindings[x] || nullBindingOK
)
[ERROR] fastdeploy/runtime/backends/tensorrt/trt_backend.cc(348)::Infer	Failed to Infer with TensorRT.
[ERROR] fastdeploy/vision/detection/ppdet/base.cc(73)::BatchPredict	Failed to inference by runtime.
DetectionResult: [xmin, ymin, xmax, ymax, score, label_id]

FPS =  32.92232339089482

-主要代码：
model_dir = './infer_weights/ppyoloe_crn_l_300e_coco/'
image = './demo/test_img.jpg'

option = fd.RuntimeOption()
option.use_gpu()
option.use_trt_backend()
option.trt_option.serialize_file = './model_cache.trt'
option.enable_trt_fp16()    

model_file = os.path.join(model_dir, "model.pdmodel")
params_file = os.path.join(model_dir, "model.pdiparams")
config_file = os.path.join(model_dir, "infer_cfg.yml")

model = fd.vision.detection.PPYOLOE(
    model_file, params_file, config_file, runtime_option=option)

im = cv2.imread(image)
while True:
	time1 = time.time()
	result = model.predict(im)
	time2 = time.time()
	time_use = time2 - time1
	print(result)
	# cv2.imwrite("visualized_result.jpg", vis_im)
	print("FPS = ", str(1.0 / time_use))

**Comment by Jiang-Jia-Jun** [comment]
看起来是用了原生TensorRT而非PaddleInference推理后端。

PPDet导出模型加--trt=True仅当使用Paddle Inference推理后端适用。

如果是使用原生TensorRT，不用加--trt=True

**Comment by MichaelSunEngineer** [comment]
> 看起来是用了原生TensorRT而非PaddleInference推理后端。
> 
> PPDet导出模型加--trt=True仅当使用Paddle Inference推理后端适用。
> 
> 如果是使用原生TensorRT，不用加--trt=True
确实是用的原生TensorRT，但是如果导出模型不加--trt=True，也会报错，如下
[INFO] fastdeploy/vision/common/processors/transform.cc(45)::FuseNormalizeCast	Normalize and Cast are fused to Normalize in preprocessing pipeline.
[INFO] fastdeploy/vision/common/processors/transform.cc(93)::FuseNormalizeHWC2CHW	Normalize and HWC2CHW are fused to NormalizeAndPermute  in preprocessing pipeline.
[INFO] fastdeploy/vision/common/processors/transform.cc(159)::FuseNormalizeColorConvert	BGR2RGB and NormalizeAndPermute are fused to NormalizeAndPermute with swap_rb=1
[ERROR] Cannot found attribute beta in op: swish

**Comment by MichaelSunEngineer** [comment]
@Jiang-Jia-Jun 我转换使用的paddle是2.7版本，ppdet是2.6版本。是不是我转换模型的版本不对？应该用什么版本的

**Comment by MichaelSunEngineer** [comment]
解决了，用paddle2.4转ppyoloe_crn_s_36e_crowdhuman以后有输出了，但是pphuman中给出的ppyoloe_plus_crn_t_auxhead_320_60e_pphuman模型直接是导出好的model模型，运行报错同上，可不可给我下ppyoloe_plus_crn_t_auxhead_320_60e_pphuman.pdparams文件我自己转下
@Jiang-Jia-Jun @jzhang533 @edwardzhou @ZeyuChen

**Comment by MichaelSunEngineer** [comment]
使用paddle2.6 ppdet2.7导出ppyoloe_plus_crn_t_auxhead_320_60e_pphuman模型成功，放入fastdeploy执行报错内容为
"[INFO] fastdeploy/vision/common/processors/transform.cc(45)::FuseNormalizeCast	Normalize and Cast are fused to Normalize in preprocessing pipeline.
[INFO] fastdeploy/vision/common/processors/transform.cc(93)::FuseNormalizeHWC2CHW	Normalize and HWC2CHW are fused to NormalizeAndPermute  in preprocessing pipeline.
[INFO] fastdeploy/vision/common/processors/transform.cc(159)::FuseNormalizeColorConvert	BGR2RGB and NormalizeAndPermute are fused to NormalizeAndPermute with swap_rb=1
[ERROR] Cannot found attribute beta in op: swish"
其他说明
(paddle2.4导出报错got an unexpected keyword argument 'full_graph')
(模型链接https://paddledet.bj.bcebos.com/models/ppyoloe_plus_crn_t_auxhead_320_60e_pphuman.pdparams)
@Jiang-Jia-Jun @jzhang533 @edwardzhou @ZeyuChen

**Comment by Jiang-Jia-Jun** [comment]
> @Jiang-Jia-Jun 我转换使用的paddle是2.7版本，ppdet是2.6版本。是不是我转换模型的版本不对？应该用什么版本的

可以使用paddle 2.3的版本导出一个试下

**Comment by Jiang-Jia-Jun** [comment]
> 使用paddle2.6 ppdet2.7导出ppyoloe_plus_crn_t_auxhead_320_60e_pphuman模型成功，放入fastdeploy执行报错内容为 "[INFO] fastdeploy/vision/common/processors/transform.cc(45)::FuseNormalizeCast Normalize and Cast are fused to Normalize in preprocessing pipeline. [INFO] fastdeploy/vision/common/processors/transform.cc(93)::FuseNormalizeHWC2CHW Normalize and HWC2CHW are fused to NormalizeAndPermute in preprocessing pipeline. [INFO] fastdeploy/vision/common/processors/transform.cc(159)::FuseNormalizeColorConvert BGR2RGB and NormalizeAndPermute are fused to NormalizeAndPermute with swap_rb=1 [ERROR] Cannot found attribute beta in op: swish" 其他说明 (paddle2.4导出报错got an unexpected keyword argument 'full_graph') (模型链接https://paddledet.bj.bcebos.com/models/ppyoloe_plus_crn_t_auxhead_320_60e_pphuman.pdparams) @Jiang-Jia-Jun @jzhang533 @edwardzhou @ZeyuChen

使用Paddle 2.3试下

**Comment by MichaelSunEngineer** [comment]
paddle2.3安装不上，太老了。找到一个类似的问题https://github.com/PaddlePaddle/Paddle2ONNX/issues/1167
但是我改动
FastDeploy\paddle2onnx\mapper\activation.cc和
FastDeploy\paddle2onnx\legacy\op_mapper\activation.py文件，
重新编译安装FastDeploy.whl包，都不起作用呢？
@Jiang-Jia-Jun

**Comment by Jiang-Jia-Jun** [comment]
> 使用paddle2.6 ppdet2.7导出ppyoloe_plus_crn_t_auxhead_320_60e_pphuman模型成功，放入fastdeploy执行报错内容为 "[INFO] fastdeploy/vision/common/processors/transform.cc(45)::FuseNormalizeCast Normalize and Cast are fused to Normalize in preprocessing pipeline. [INFO] fastdeploy/vision/common/processors/transform.cc(93)::FuseNormalizeHWC2CHW Normalize and HWC2CHW are fused to NormalizeAndPermute in preprocessing pipeline. [INFO] fastdeploy/vision/common/processors/transform.cc(159)::FuseNormalizeColorConvert BGR2RGB and NormalizeAndPermute are fused to NormalizeAndPermute with swap_rb=1 [ERROR] Cannot found attribute beta in op: swish" 其他说明 (paddle2.4导出报错got an unexpected keyword argument 'full_graph') (模型链接https://paddledet.bj.bcebos.com/models/ppyoloe_plus_crn_t_auxhead_320_60e_pphuman.pdparams) @Jiang-Jia-Jun @jzhang533 @edwardzhou @ZeyuChen

我注意到你这里的提示是```Cannot found attribute beta in op: swish"```，也许你可以按如下方式来改动测试

1. 修改如下这行代码https://github.com/PaddlePaddle/FastDeploy/blob/develop/paddle2onnx/mapper/activation.h#L122 由原本```GetAttr("beta", &beta_);```改为```beta_=1.0;```
2. 重新编译FastDeploy，在编译时打开开关BUILD_PADDLE2ONNX=ON
