### ISSUE TITLE
Fastdeploy服务化部署时failed to load model 'cls_runtime': at least one version must be available under the version policy of model 'cls_runtime'

### ISSUE THREAD

**Issue by IceHowe** [PaddlePaddle/FastDeploy#2512]
*********************************************
温馨提示：根据社区不完全统计，按照模板提问，可以加快回复和解决问题的速度
*********************************************

## 环境

- 【FastDeploy版本】： fastdeploy:1.0.7-cpu-only-21.10
- 【系统平台】: Linux x64(Ubuntu 22.04) 
- 【编译语言】：Python3.9

## 问题日志及出现问题的操作流程
- 附上详细的问题日志有助于快速定位分析
- 【模型跑不通】
```bash
docker pull registry.baidubce.com/paddlepaddle/fastdeploy:1.0.7-cpu-only-21.10

docker run --name fdocr -dit -p 8000:8000 -p 8002:8002 -p 8001:8001  --shm-size="1g" -v $PWD:/ocr_serving registry.baidubce.com/paddlepaddle/fastdeploy:1.0.4-cpu-only-21.10 bash

docker exec -it -u root fdocr bash
```
使用CPU部署，运行docker时出错
![image](https://github.com/user-attachments/assets/3a263728-1493-4960-978b-ad62fede9200)
![image](https://github.com/user-attachments/assets/e0a3e7c8-df44-46b4-b284-90da7f2e32a5)
![image](https://github.com/user-attachments/assets/71421fa4-05bb-458c-93b3-ba4e3d79015d)
![image](https://github.com/user-attachments/assets/08aae6b3-46d6-4812-a6e5-017c5de16751)
![image](https://github.com/user-attachments/assets/7bbc30dd-0f96-4497-a0da-113f92fe2fcf)
![image](https://github.com/user-attachments/assets/433ae1af-d18c-484a-a5f2-546acebab327)

**Comment by lan11** [comment]
请问是怎么解决的，谢谢
