### ISSUE TITLE
RuntimeError: FastDeploy initalized failed!

### ISSUE THREAD

**Issue by netwu** [PaddlePaddle/FastDeploy#307]
硬件：Mac m1
版本：fastdeploy-python  0.2.1
安装方式：pip install numpy opencv-python fastdeploy-python -f https://www.paddlepaddle.org.cn/whl/fastdeploy.html
运行demo： python infer.py --model Unet_cityscapes_without_argmax_infer --image cityscapes_demo.png --device cpu
报错：

> $  python infer.py --model Unet_cityscapes_without_argmax_infer --image cityscapes_demo.png --device cpu
Traceback (most recent call last):
  File "/opt/miniconda3/envs/py39/lib/python3.9/site-packages/fastdeploy/c_lib_wrap.py", line 154, in <module>
    from .libs.fastdeploy_main import *
ImportError: dlopen(/opt/miniconda3/envs/py39/lib/python3.9/site-packages/fastdeploy/libs/fastdeploy_main.cpython-39-darwin.so, 0x0002): Library not loaded: '@rpath/libfastdeploy.0.2.1.dylib'
  Referenced from: '/opt/miniconda3/envs/py39/lib/python3.9/site-packages/fastdeploy/libs/fastdeploy_main.cpython-39-darwin.so'
  Reason: tried: '/Users/qiuyanjun/Desktop/dev/fastdeploy_build/FastDeploy/python/.setuptools-cmake-build/third_libs/install/paddle2onnx/lib/libfastdeploy.0.2.1.dylib' (no such file), '/Users/qiuyanjun/Desktop/dev/fastdeploy_build/FastDeploy/python/.setuptools-cmake-build/third_libs/install/onnxruntime/lib/libfastdeploy.0.2.1.dylib' (no such file), '/Users/qiuyanjun/Desktop/dev/fastdeploy_build/FastDeploy/python/.setuptools-cmake-build/third_libs/install/opencv/lib/libfastdeploy.0.2.1.dylib' (no such file), '/Users/qiuyanjun/Desktop/dev/fastdeploy_build/FastDeploy/python/.setuptools-cmake-build/third_libs/install/faster_tokenizer/lib/libfastdeploy.0.2.1.dylib' (no such file), '/Users/qiuyanjun/Desktop/dev/fastdeploy_build/FastDeploy/python/.setuptools-cmake-build/libfastdeploy.0.2.1.dylib' (no such file), 'loader_path/$loader_path/third_libs/opencv/libfastdeploy.0.2.1.dylib' (no such file), 'loader_path/$loader_path/third_libs/paddle2onnx/lib/libfastdeploy.0.2.1.dylib' (no such file), 'loader_path/$loader_path/third_libs/paddle2onnx/include/paddle2onnx/libfastdeploy.0.2.1.dylib' (no such file), 'loader_path/$loader_path/third_libs/paddle2onnx/include/paddle2onnx/paddle2onnx/libfastdeploy.0.2.1.dylib' (no such file), 'loader_path/$loader_path/third_libs/paddle2onnx/lib/paddle2onnx/libfastdeploy.0.2.1.dylib' (no such file), 'loader_path/$loader_path/third_libs/onnxruntime/lib/libfastdeploy.0.2.1.dylib' (no such file), 'loader_path/$loader_path/third_libs/onnxruntime/include/lib/libfastdeploy.0.2.1.dylib' (no such file), 'loader_path/$loader_path/third_libs/onnxruntime/lib/libonnxruntime.1.12.0.dylib.dSYM/libfastdeploy.0.2.1.dylib' (no such file), 'loader_path/$loader_path/third_libs/onnxruntime/lib/libonnxruntime.1.12.0.dylib.dSYM/Contents/libfastdeploy.0.2.1.dylib' (no such file), 'loader_path/$loader_path/third_libs/onnxruntime/lib/libonnxruntime.1.12.0.dylib.dSYM/Contents/Resources/libfastdeploy.0.2.1.dylib' (no such file), 'loader_path/$loader_path/third_libs/onnxruntime/lib/libonnxruntime.1.12.0.dylib.dSYM/Contents/Resources/DWARF/libfastdeploy.0.2.1.dylib' (no such file), 'loader_path/$loader_path/third_libs/onnxruntime/lib/libonnxruntime.1.12.0.dylib.dSYM/Contents/Resources/DWARF/DWARF/libfastdeploy.0.2.1.dylib' (no such file), 'loader_path/$loader_path/third_libs/faster_tokenizer/lib/libfastdeploy.0.2.1.dylib' (no such file), 'loader_path/$loader_path/third_libs/faster_tokenizer/include/faster_tokenizer/libfastdeploy.0.2.1.dylib' (no such file), 'loader_path/$loader_path/third_libs/faster_tokenizer/include/faster_tokenizer/decoders/libfastdeploy.0.2.1.dylib' (no such file), 'loader_path/$loader_path/third_libs/faster_tokenizer/include/faster_tokenizer/tokenizers/decoders/libfastdeploy.0.2.1.dylib' (no such file), 'loader_path/$loader_path/third_libs/faster_tokenizer/include/faster_tokenizer/normalizers/decoders/libfastdeploy.0.2.1.dylib' (no such file), 'loader_path/$loader_path/third_libs/faster_tokenizer/include/faster_tokenizer/core/decoders/libfastdeploy.0.2.1.dylib' (no such file), 'loader_path/$loader_path/third_libs/faster_tokenizer/include/faster_tokenizer/postprocessors/decoders/libfastdeploy.0.2.1.dylib' (no such file), 'loader_path/$loader_path/third_libs/faster_tokenizer/include/faster_tokenizer/utils/decoders/libfastdeploy.0.2.1.dylib' (no such file), 'loader_path/$loader_path/third_libs/faster_tokenizer/include/faster_tokenizer/models/decoders/libfastdeploy.0.2.1.dylib' (no such file), 'loader_path/$loader_path/third_libs/faster_tokenizer/include/faster_tokenizer/pretokenizers/decoders/libfastdeploy.0.2.1.dylib' (no such file), 'loader_path/$loader_path/third_libs/faster_tokenizer/include/faster_tokenizer/decoders/decoders/libfastdeploy.0.2.1.dylib' (no such file), 'loader_path/$loader_path/third_libs/faster_tokenizer/third_party/lib/libfastdeploy.0.2.1.dylib' (no such file), 'loader_path/$loader_path/third_libs/faster_tokenizer/third_party/include/nlohmann/libfastdeploy.0.2.1.dylib' (no such file), 'loader_path/$loader_path/third_libs/faster_tokenizer/third_party/include/glog/nlohmann/libfastdeploy.0.2.1.dylib' (no such file), 'loader_path/$loader_path/third_libs/faster_tokenizer/third_party/include/gflags/nlohmann/libfastdeploy.0.2.1.dylib' (no such file), 'loader_path/$loader_path/third_libs/faster_tokenizer/third_party/include/re2/nlohmann/libfastdeploy.0.2.1.dylib' (no such file), 'loader_path/$loader_path/third_libs/faster_tokenizer/third_party/include/nlohmann/nlohmann/libfastdeploy.0.2.1.dylib' (no such file), 'loader_path/$loader_path/third_libs/faster_tokenizer/third_party/lib/nlohmann/libfastdeploy.0.2.1.dylib' (no such file), 'loader_path/$loader_path/third_libs/faster_tokenizer/lib/nlohmann/libfastdeploy.0.2.1.dylib' (no such file), 'loader_path/$loader_path/third_libs/opencv/lib/libfastdeploy.0.2.1.dylib' (no such file), 'loader_path/$loader_path/third_libs/opencv/include/opencv2/libfastdeploy.0.2.1.dylib' (no such file), 'loader_path/$loader_path/third_libs/opencv/include/opencv/opencv2/libfastdeploy.0.2.1.dylib' (no such file), 'loader_path/$loader_path/third_libs/opencv/include/opencv2/calib3d/libfastdeploy.0.2.1.dylib' (no such file), 'loader_path/$loader_path/third_libs/opencv/include/opencv2/superres/calib3d/libfastdeploy.0.2.1.dylib' (no such file), 'loader_path/$loader_path/third_libs/opencv/include/opencv2/shape/calib3d/libfastdeploy.0.2.1.dylib' (no such file), 'loader_path/$loader_path/third_libs/opencv/include/opencv2/flann/calib3d/libfastdeploy.0.2.1.dylib' (no such file), 'loader_path/$loader_path/third_libs/opencv/include/opencv2/core/detail/libfastdeploy.0.2.1.dylib' (no such file), 'loader_path/$loader_path/third_libs/opencv/include/opencv2/core/hal/detail/libfastdeploy.0.2.1.dylib' (no such file), 'loader_path/$loader_path/third_libs/opencv/include/opencv2/core/cuda/detail/libfastdeploy.0.2.1.dylib' (no such file), 'loader_path/$loader_path/third_libs/opencv/include/opencv2/core/cuda/detail/detail/libfastdeploy.0.2.1.dylib' (no such file), 'loader_path/$loader_path/third_libs/opencv/include/opencv2/core/utils/detail/libfastdeploy.0.2.1.dylib' (no such file), 'loader_path/$loader_path/third_libs/opencv/include/opencv2/core/opencl/runtime/libfastdeploy.0.2.1.dylib' (no such file), 'loader_path/$loader_path/third_libs/opencv/include/opencv2/core/opencl/runtime/autogenerated/libfastdeploy.0.2.1.dylib' (no such file), 'loader_path/$loader_path/third_libs/opencv/include/opencv2/core/opencl/runtime/autogenerated/autogenerated/libfastdeploy.0.2.1.dylib' (no such file), 'loader_path/$loader_path/third_libs/opencv/include/opencv2/core/detail/autogenerated/libfastdeploy.0.2.1.dylib' (no such file), 'loader_path/$loader_path/third_libs/opencv/include/opencv2/stitching/detail/libfastdeploy.0.2.1.dylib' (no such file), 'loader_path/$loader_path/third_libs/opencv/include/opencv2/stitching/detail/detail/libfastdeploy.0.2.1.dylib' (no such file), 'loader_path/$loader_path/third_libs/opencv/include/opencv2/imgproc/detail/libfastdeploy.0.2.1.dylib' (no such file), 'loader_path/$loader_path/third_libs/opencv/include/opencv2/imgproc/hal/detail/libfastdeploy.0.2.1.dylib' (no such file), 'loader_path/$loader_path/third_libs/opencv/include/opencv2/objdetect/detail/libfastdeploy.0.2.1.dylib' (no such file), 'loader_path/$loader_path/third_libs/opencv/include/opencv2/ml/detail/libfastdeploy.0.2.1.dylib' (no such file), 'loader_path/$loader_path/third_libs/opencv/include/opencv2/imgcodecs/detail/libfastdeploy.0.2.1.dylib' (no such file), 'loader_path/$loader_path/third_libs/opencv/include/opencv2/dnn/utils/libfastdeploy.0.2.1.dylib' (no such file), 'loader_path/$loader_path/third_libs/opencv/include/opencv2/dnn/utils/utils/libfastdeploy.0.2.1.dylib' (no such file), 'loader_path/$loader_path/third_libs/opencv/include/opencv2/videoio/utils/libfastdeploy.0.2.1.dylib' (no such file), 'loader_path/$loader_path/third_libs/opencv/include/opencv2/highgui/utils/libfastdeploy.0.2.1.dylib' (no such file), 'loader_path/$loader_path/third_libs/opencv/include/opencv2/features2d/hal/libfastdeploy.0.2.1.dylib' (no such file), 'loader_path/$loader_path/third_libs/opencv/include/opencv2/features2d/hal/hal/libfastdeploy.0.2.1.dylib' (no such file), 'loader_path/$loader_path/third_libs/opencv/include/opencv2/videostab/hal/libfastdeploy.0.2.1.dylib' (no such file), 'loader_path/$loader_path/third_libs/opencv/include/opencv2/photo/hal/libfastdeploy.0.2.1.dylib' (no such file), 'loader_path/$loader_path/third_libs/opencv/include/opencv2/calib3d/hal/libfastdeploy.0.2.1.dylib' (no such file), 'loader_path/$loader_path/third_libs/opencv/lib/python2.7/libfastdeploy.0.2.1.dylib' (no such file), 'loader_path/$loader_path/third_libs/opencv/lib/pkgconfig/python2.7/libfastdeploy.0.2.1.dylib' (no such file), 'loader_path/$loader_path/third_libs/opencv/lib/python2.7/site-packages/libfastdeploy.0.2.1.dylib' (no such file), 'loader_path/$loader_path/third_libs/opencv/lib/python2.7/site-packages/cv2/libfastdeploy.0.2.1.dylib' (no such file), 'loader_path/$loader_path/third_libs/opencv/lib/python2.7/site-packages/cv2/python-2.7/libfastdeploy.0.2.1.dylib' (no such file), 'loader_path/$loader_path/third_libs/opencv/lib/python2.7/site-packages/cv2/python-2.7/python-2.7/libfastdeploy.0.2.1.dylib' (no such file), '/Users/qiuyanjun/Desktop/dev/fastdeploy_build/FastDeploy/python/.setuptools-cmake-build/third_libs/install/paddle2onnx/lib/libfastdeploy.0.2.1.dylib' (no such file), '/Users/qiuyanjun/Desktop/dev/fastdeploy_build/FastDeploy/python/.setuptools-cmake-build/third_libs/install/onnxruntime/lib/libfastdeploy.0.2.1.dylib' (no such file), '/Users/qiuyanjun/Desktop/dev/fastdeploy_build/FastDeploy/python/.setuptools-cmake-build/third_libs/install/opencv/lib/libfastdeploy.0.2.1.dylib' (no such file), '/Users/qiuyanjun/Desktop/dev/fastdeploy_build/FastDeploy/python/.setuptools-cmake-build/third_libs/install/faster_tokenizer/lib/libfastdeploy.0.2.1.dylib' (no such file), '/Users/qiuyanjun/Desktop/dev/fastdeploy_build/FastDeploy/python/.setuptools-cmake-build/libfastdeploy.0.2.1.dylib' (no such file), 'loader_path/$loader_path/third_libs/opencv/libfastdeploy.0.2.1.dylib' (no such file), 'loader_path/$loader_path/third_libs/paddle2onnx/lib/libfastdeploy.0.2.1.dylib' (no such file), 'loader_path/$loader_path/third_libs/paddle2onnx/include/paddle2onnx/libfastdeploy.0.2.1.dylib' (no such file), 'loader_path/$loader_path/third_libs/paddle2onnx/include/paddle2onnx/paddle2onnx/libfastdeploy.0.2.1.dylib' (no such file), 'loader_path/$loader_path/third_libs/paddle2onnx/lib/paddle2onnx/libfastdeploy.0.2.1.dylib' (no such file), 'loader_path/$loader_path/third_libs/onnxruntime/lib/libfastdeploy.0.2.1.dylib' (no such file), 'loader_path/$loader_path/third_libs/onnxruntime/include/lib/libfastdeploy.0.2.1.dylib' (no such file), 'loader_path/$loader_path/third_libs/onnxruntime/lib/libonnxruntime.1.12.0.dylib.dSYM/libfastdeploy.0.2.1.dylib' (no such file), 'loader_path/$loader_path/third_libs/onnxruntime/lib/libonnxruntime.1.12.0.dylib.dSYM/Contents/libfastdeploy.0.2.1.dylib' (no such file), 'loader_path/$loader_path/third_libs/onnxruntime/lib/libonnxruntime.1.12.0.dylib.dSYM/Contents/Resources/libfastdeploy.0.2.1.dylib' (no such file), 'loader_path/$loader_path/third_libs/onnxruntime/lib/libonnxruntime.1.12.0.dylib.dSYM/Contents/Resources/DWARF/libfastdeploy.0.2.1.dylib' (no such file), 'loader_path/$loader_path/third_libs/onnxruntime/lib/libonnxruntime.1.12.0.dylib.dSYM/Contents/Resources/DWARF/DWARF/libfastdeploy.0.2.1.dylib' (no such file), 'loader_path/$loader_path/third_libs/faster_tokenizer/lib/libfastdeploy.0.2.1.dylib' (no such file), 'loader_path/$loader_path/third_libs/faster_tokenizer/include/faster_tokenizer/libfastdeploy.0.2.1.dylib' (no such file), 'loader_path/$loader_path/third_libs/faster_tokenizer/include/faster_tokenizer/decoders/libfastdeploy.0.2.1.dylib' (no such file), 'loader_path/$loader_path/third_libs/faster_tokenizer/include/faster_tokenizer/tokenizers/decoders/libfastdeploy.0.2.1.dylib' (no such file), 'loader_path/$loader_path/third_libs/faster_tokenizer/include/faster_tokenizer/normalizers/decoders/libfastdeploy.0.2.1.dylib' (no such file), 'loader_path/$loader_path/third_libs/faster_tokenizer/include/faster_tokenizer/core/decoders/libfastdeploy.0.2.1.dylib' (no such file), 'loader_path/$loader_path/third_libs/faster_tokenizer/include/faster_tokenizer/postprocessors/decoders/libfastdeploy.0.2.1.dylib' (no such file), 'loader_path/$loader_path/third_libs/faster_tokenizer/include/faster_tokenizer/utils/decoders/libfastdeploy.0.2.1.dylib' (no such file), 'loader_path/$loader_path/third_libs/faster_tokenizer/include/faster_tokenizer/models/decoders/libfastdeploy.0.2.1.dylib' (no such file), 'loader_path/$loader_path/third_libs/faster_tokenizer/include/faster_tokenizer/pretokenizers/decoders/libfastdeploy.0.2.1.dylib' (no such file), 'loader_path/$loader_path/third_libs/faster_tokenizer/include/faster_tokenizer/decoders/decoders/libfastdeploy.0.2.1.dylib' (no such file), 'loader_path/$loader_path/third_libs/faster_tokenizer/third_party/lib/libfastdeploy.0.2.1.dylib' (no such file), 'loader_path/$loader_path/third_libs/faster_tokenizer/third_party/include/nlohmann/libfastdeploy.0.2.1.dylib' (no such file), 'loader_path/$loader_path/third_libs/faster_tokenizer/third_party/include/glog/nlohmann/libfastdeploy.0.2.1.dylib' (no such file), 'loader_path/$loader_path/third_libs/faster_tokenizer/third_party/include/gflags/nlohmann/libfastdeploy.0.2.1.dylib' (no such file), 'loader_path/$loader_path/third_libs/faster_tokenizer/third_party/include/re2/nlohmann/libfastdeploy.0.2.1.dylib' (no such file), 'loader_path/$loader_path/third_libs/faster_tokenizer/third_party/include/nlohmann/nlohmann/libfastdeploy.0.2.1.dylib' (no such file), 'loader_path/$loader_path/third_libs/faster_tokenizer/third_party/lib/nlohmann/libfastdeploy.0.2.1.dylib' (no such file), 'loader_path/$loader_path/third_libs/faster_tokenizer/lib/nlohmann/libfastdeploy.0.2.1.dylib' (no such file), 'loader_path/$loader_path/third_libs/opencv/lib/libfastdeploy.0.2.1.dylib' (no such file), 'loader_path/$loader_path/third_libs/opencv/include/opencv2/libfastdeploy.0.2.1.dylib' (no such file), 'loader_path/$loader_path/third_libs/opencv/include/opencv/opencv2/libfastdeploy.0.2.1.dylib' (no such file), 'loader_path/$loader_path/third_libs/opencv/include/opencv2/calib3d/libfastdeploy.0.2.1.dylib' (no such file), 'loader_path/$loader_path/third_libs/opencv/include/opencv2/superres/calib3d/libfastdeploy.0.2.1.dylib' (no such file), 'loader_path/$loader_path/third_libs/opencv/include/opencv2/shape/calib3d/libfastdeploy.0.2.1.dylib' (no such file), 'loader_path/$loader_path/third_libs/opencv/include/opencv2/flann/calib3d/libfastdeploy.0.2.1.dylib' (no such file), 'loader_path/$loader_path/third_libs/opencv/include/opencv2/core/detail/libfastdeploy.0.2.1.dylib' (no such file), 'loader_path/$loader_path/third_libs/opencv/include/opencv2/core/hal/detail/libfastdeploy.0.2.1.dylib' (no such file), 'loader_path/$loader_path/third_libs/opencv/include/opencv2/core/cuda/detail/libfastdeploy.0.2.1.dylib' (no such file), 'loader_path/$loader_path/third_libs/opencv/include/opencv2/core/cuda/detail/detail/libfastdeploy.0.2.1.dylib' (no such file), 'loader_path/$loader_path/third_libs/opencv/include/opencv2/core/utils/detail/libfastdeploy.0.2.1.dylib' (no such file), 'loader_path/$loader_path/third_libs/opencv/include/opencv2/core/opencl/runtime/libfastdeploy.0.2.1.dylib' (no such file), 'loader_path/$loader_path/third_libs/opencv/include/opencv2/core/opencl/runtime/autogenerated/libfastdeploy.0.2.1.dylib' (no such file), 'loader_path/$loader_path/third_libs/opencv/include/opencv2/core/opencl/runtime/autogenerated/autogenerated/libfastdeploy.0.2.1.dylib' (no such file), 'loader_path/$loader_path/third_libs/opencv/include/opencv2/core/detail/autogenerated/libfastdeploy.0.2.1.dylib' (no such file), 'loader_path/$loader_path/third_libs/opencv/include/opencv2/stitching/detail/libfastdeploy.0.2.1.dylib' (no such file), 'loader_path/$loader_path/third_libs/opencv/include/opencv2/stitching/detail/detail/libfastdeploy.0.2.1.dylib' (no such file), 'loader_path/$loader_path/third_libs/opencv/include/opencv2/imgproc/detail/libfastdeploy.0.2.1.dylib' (no such file), 'loader_path/$loader_path/third_libs/opencv/include/opencv2/imgproc/hal/detail/libfastdeploy.0.2.1.dylib' (no such file), 'loader_path/$loader_path/third_libs/opencv/include/opencv2/objdetect/detail/libfastdeploy.0.2.1.dylib' (no such file), 'loader_path/$loader_path/third_libs/opencv/include/opencv2/ml/detail/libfastdeploy.0.2.1.dylib' (no such file), 'loader_path/$loader_path/third_libs/opencv/include/opencv2/imgcodecs/detail/libfastdeploy.0.2.1.dylib' (no such file), 'loader_path/$loader_path/third_libs/opencv/include/opencv2/dnn/utils/libfastdeploy.0.2.1.dylib' (no such file), 'loader_path/$loader_path/third_libs/opencv/include/opencv2/dnn/utils/utils/libfastdeploy.0.2.1.dylib' (no such file), 'loader_path/$loader_path/third_libs/opencv/include/opencv2/videoio/utils/libfastdeploy.0.2.1.dylib' (no such file), 'loader_path/$loader_path/third_libs/opencv/include/opencv2/highgui/utils/libfastdeploy.0.2.1.dylib' (no such file), 'loader_path/$loader_path/third_libs/opencv/include/opencv2/features2d/hal/libfastdeploy.0.2.1.dylib' (no such file), 'loader_path/$loader_path/third_libs/opencv/include/opencv2/features2d/hal/hal/libfastdeploy.0.2.1.dylib' (no such file), 'loader_path/$loader_path/third_libs/opencv/include/opencv2/videostab/hal/libfastdeploy.0.2.1.dylib' (no such file), 'loader_path/$loader_path/third_libs/opencv/include/opencv2/photo/hal/libfastdeploy.0.2.1.dylib' (no such file), 'loader_path/$loader_path/third_libs/opencv/include/opencv2/calib3d/hal/libfastdeploy.0.2.1.dylib' (no such file), 'loader_path/$loader_path/third_libs/opencv/lib/python2.7/libfastdeploy.0.2.1.dylib' (no such file), 'loader_path/$loader_path/third_libs/opencv/lib/pkgconfig/python2.7/libfastdeploy.0.2.1.dylib' (no such file), 'loader_path/$loader_path/third_libs/opencv/lib/python2.7/site-packages/libfastdeploy.0.2.1.dylib' (no such file), 'loader_path/$loader_path/third_libs/opencv/lib/python2.7/site-packages/cv2/libfastdeploy.0.2.1.dylib' (no such file), 'loader_path/$loader_path/third_libs/opencv/lib/python2.7/site-packages/cv2/python-2.7/libfastdeploy.0.2.1.dylib' (no such file), 'loader_path/$loader_path/third_libs/opencv/lib/python2.7/site-packages/cv2/python-2.7/python-2.7/libfastdeploy.0.2.1.dylib' (no such file), '/opt/miniconda3/envs/py39/bin/../lib/libfastdeploy.0.2.1.dylib' (no such file), '/opt/miniconda3/envs/py39/bin/../lib/libfastdeploy.0.2.1.dylib' (no such file), '/usr/local/lib/libfastdeploy.0.2.1.dylib' (no such file), '/usr/lib/libfastdeploy.0.2.1.dylib' (no such file)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/netwu/workspace/PaddlePaddle/FastDeploy/examples/vision/segmentation/paddleseg/python/infer.py", line 1, in <module>
    import fastdeploy as fd
  File "/opt/miniconda3/envs/py39/lib/python3.9/site-packages/fastdeploy/__init__.py", line 19, in <module>
    from .c_lib_wrap import (Frontend, Backend, FDDataType, TensorInfo, Device,
  File "/opt/miniconda3/envs/py39/lib/python3.9/site-packages/fastdeploy/c_lib_wrap.py", line 156, in <module>
    raise RuntimeError("FastDeploy initalized failed!")
RuntimeError: FastDeploy initalized failed!

**Comment by Zheng-Bicheng** [comment]
Paddle Backend好像暂时不支持M1 MACOS ，我M1 MacbookPro本地编译python包的时候提示如下:
```
CMake Error at cmake/paddle_inference.cmake:60 (message):
  Paddle Backend doesn't support Mac OSX with Arm64 now.
Call Stack (most recent call first):
  CMakeLists.txt:215 (include)
```

**Comment by JackonLiu** [comment]
装gpu版本试试

**Comment by jiangjiajun** [comment]
此ISSUE由于一年未更新，将会关闭处理，如有需要，可再次更新打开。
