### ISSUE TITLE
issues from wechat, about paddle serving

### ISSUE THREAD

**Issue by gglin001** [PaddlePaddle/FastDeploy#310]
hi, 这里记录了一些 在微信群里的问题, 主要涉及到 FastDeploy 和 paddleserving 两个库相关的问题, 可能放在这里更合适一点, 可以让更多的人看到, 希望可以解答一下, 感谢🙏

- 问一下，fastdeploy 跟 paddle serving 区别是什么;

- paddle serving 的开发似乎不太活跃了, 请问长期来看还会继续支持吗? 还是完全用 fastdeploy  替代?

- 它(指FastDeploy)比 padddle serving 优势在哪里，方便，安全，速度 还是互补的关系

**Comment by ChaoII** [comment]
>⚡️FastDeploy是一款易用高效的推理部署开发套件。覆盖业界🔥热门AI模型并提供📦开箱即用的部署体验，包括图像分类、目标检测、图像分割、人脸检测、人脸识别、人体关键点识别、文字识别、语义理解等多任务，满足开发者多场景，多硬件、多平台的产业部署需求。

1、首先paddlepaddle  servering 主要是针对服务化部署，并且推理后端应该是paddle_infer。
2、fastdeploy，包含不同的推理后端（ort、openvnio，pp_infer，trt，paddle-lite）不同后端针对不同硬件平台的优化方向不同，也会支持服务化部署。
3、fd包含部署场景（终端部署、服务部署）。
