### ISSUE TITLE
自训练PP_LiteSeg模型，模型导出后，使用FD推理，基本没效果。

### ISSUE THREAD

**Issue by xinsuinizhuan** [PaddlePaddle/FastDeploy#322]
使用PP_LiteSeg训练模型：
训练命令：
python export.py  --config configs/quick_start/pp_liteseg_optic_disc_512x512_1k.yml --model_path output/iter_10000/model.pdparams --save_dir output --input_shape 1 3 512 512

训练完后，使用python测试效果：
![图片](https://user-images.githubusercontent.com/40679769/194497348-c34e5c75-42c9-4647-9dd7-eaff09cf7506.png)
效果还可以。

模型导出：
python export.py  --config configs/quick_start/pp_liteseg_optic_disc_512x512_1k.yml --model_path output/iter_10000/model.pdparams --save_dir output --input_shape 1 3 512 512
其中，yaml参数文件为：
Deploy:
  input_shape:
  - 1
  - 3
  - 512
  - 512
  model: model.pdmodel
  output_dtype: int32
  output_op: argmax
  params: model.pdiparams
  transforms:
  - type: Normalize

然后使用FD推理，cpu，效果：
![图片](https://user-images.githubusercontent.com/40679769/194497638-3fa9b3ec-c089-4ff8-9bc8-d27c89c543c9.png)

但是使用https://github.com/PaddlePaddle/FastDeploy/tree/develop/examples/vision/segmentation/paddleseg下的[PP-LiteSeg-T(STDC1)-cityscapes](https://bj.bcebos.com/paddlehub/fastdeploy/PP_LiteSeg_T_STDC1_cityscapes_without_argmax_infer.tgz)提供的模型推理，正常，其中yaml文件为：
Deploy:
  input_shape:
  - -1
  - 3
  - -1
  - -1
  model: model.pdmodel
  output_dtype: float32
  output_op: none
  params: model.pdiparams
  transforms:
  - type: Normalize

**Comment by jiangjiajun** [comment]
@felixhjh

**Comment by felixhjh** [comment]
方便给一张上面的原图吗？ 我自测一下

**Comment by leiqing1** [comment]
@xinsuinizhuan 看上下两张图，图像的通道顺序不太对？（GRB/BGR）

**Comment by felixhjh** [comment]
PaddleSeg官方库，predict.py 使用pp_liteseg_optic_disc_512x512_1k.yml并没有进行crop然后预测的操作，因此这边导出模型也可以不指定--input_shape

**Comment by felixhjh** [comment]
导出模型的时候 指定--input_shape可以支持包括ONNXRuntime/TensorRT的推理，同时可以减少推理时的显存消耗（2048的图会被缩放到512再推理，结果再会放大回来），但是会降低一些精度。  不指定--input_shape目前则只能支持Paddle Inference推理
