### ISSUE TITLE
OCR部署，初始化判断问题

### ISSUE THREAD

**Issue by jiangjiajun** [PaddlePaddle/FastDeploy#323]
![image](https://user-images.githubusercontent.com/19339784/194505773-2e8cbc95-5156-4bdb-a0b0-c2f895a5d6fb.png)

此外，OCR中模型的预处理需说明清楚。 如若模型由PaddleOCR导出，或下载，需对哪几个模型做怎样的处理操作
 
@yunyaoXYY

**Comment by yunyaoXYY** [comment]
1. 模型预处理问题已提PR，在"Add Initialize function to PP-OCR"里. (后续PaddleOCR完全更新模型库后，这部分readme就不需要了）

2.PP-OCR初始化功能已提PR https://github.com/PaddlePaddle/FastDeploy/pull/326
