### ISSUE TITLE
Will Text Detection Using PP-OCR Be Made Available for Server Side Deployment?

### ISSUE THREAD

**Issue by rattling** [PaddlePaddle/FastDeploy#329]
I was hoping to do a light deployment of text detection on a Linux server using FastDeploy in Python.

However, PP-OCR and later versions aren't listed in the supported model list for server side deployment.

I have tried to import it in any case along the lines of the tutorial for PPYOLOE but not sure how to pass the required det_model and cls_model parameters. I presume there isn't a way of doing this and this is just a stub?

Wondering if PP-OCR may be made available for server side deployment at some stage?

**Comment by yunyaoXYY** [comment]
> 

Hello, 
1) PP-OCR series are supported in FastDeploy now, see examples as https://github.com/PaddlePaddle/FastDeploy/tree/develop/examples/vision/ocr/PPOCRSystemv3 
You could deploy the models on your Linux server. 

2)BTW, I'm not very clear about the "server side deployment" mentioned in your questions, do you mean that you want to deploy the PP-OCR models in server system?(Like TensorFlow-serving/ Triton ) If so, we will support the PP-OCR models on FastDeploy-Serving in the future .

3) Do you have Apps like Discord / Slack or something like them? For a more convenient talk, you could leave a way to contact.

**Comment by yunyaoXYY** [comment]
> I was hoping to do a light deployment of text detection on a Linux server using FastDeploy in Python.
> 
> However, PP-OCR and later versions aren't listed in the supported model list for server side deployment.
> 
> I have tried to import it in any case along the lines of the tutorial for PPYOLOE but not sure how to pass the required det_model and cls_model parameters. I presume there isn't a way of doing this and this is just a stub?
> 
> Wondering if PP-OCR may be made available for server side deployment at some stage?

Hello,

1.PP-OCR series are supported in FastDeploy now, see examples as https://github.com/PaddlePaddle/FastDeploy/tree/develop/examples/vision/ocr/PP-OCRv3
You could deploy the models on your Linux server.

2.BTW, I'm not very clear about the "server side deployment" mentioned in your questions, do you mean that you want to deploy the PP-OCR models in server system?(Like TensorFlow-serving/ Triton ) If so, we will support the PP-OCR models on FastDeploy-Serving in the future.

3.Do you have Apps like Discord / Slack or something like them? For a more convenient talk, you could leave a way to contact.

**Comment by rattling** [comment]
Hi there,
I got it working from your example, swapping the detection/recognition models for the English ones.  It works great.  As for server side, I only meant that deploying on Linux rather than on mobile devices.

This is very useful as a full paddlepaddle installation was in conflict due to OS on my deployed application.  FastDeploy is a great way to reduce the deployment footprint.

Happy to connect in whatever the best way is. Is there a discord or slack channel around FastDeploy in English?

Many thanks, John.

**Comment by yunyaoXYY** [comment]
> 

Hello John,

Great! Good to know it works for you! 

FastDeploy does not have channels in Discord or Slack for now.
I was meant to give my personal support for you on Discord/Slack yesterday. 

Best regards,
Yunyao

**Comment by yunyaoXYY** [comment]
> Hi there, I got it working from your example, swapping the detection/recognition models for the English ones. It works great. As for server side, I only meant that deploying on Linux rather than on mobile devices.
> 
> This is very useful as a full paddlepaddle installation was in conflict due to OS on my deployed application. FastDeploy is a great way to reduce the deployment footprint.
> 
> Happy to connect in whatever the best way is. Is there a discord or slack channel around FastDeploy in English?
> 
> Many thanks, John.

Hello John,

Great! Good to know it works for you!

FastDeploy does not have channels in Discord or Slack for now.
I was meant to give my personal support for you on Discord/Slack yesterday.

Best regards,
Yunyao

**Comment by leiqing1** [comment]
@rattling hi welcome to FastDeploy Slack and share it with friends if in need https://join.slack.com/t/fastdeployworkspace/shared_invite/zt-1hhvpb279-iw2pNPwrDaMBQ5OQhO3Siw
