### ISSUE TITLE
新模型咨询

### ISSUE THREAD

**Issue by ChaoII** [PaddlePaddle/FastDeploy#330]
请问一下，FD后期是否有对paddledetection 危险行为识别等pipeline部署的支持，还有paddlecls中的物品识别？目前有需求做异常行为识别，人/车辆属性分析等等。谢谢

**Comment by jiangjiajun** [comment]
有没有兴趣一起来做？

**Comment by ChaoII** [comment]
> 

有兴趣，不过目前没接触过，需要研究研究怎么玩的。

**Comment by jiangjiajun** [comment]
在微信交流群里找到我的头像（应该在群成员前几位），加我私聊哈
