### ISSUE TITLE
{"code":"NoSuchKey","message":"The specified key does not exist.","requestId":"1e32ec72-7aed-48f4-b466-c2fcc5fb158e"}

### ISSUE THREAD

**Issue by lucasjinreal** [PaddlePaddle/FastDeploy#356]
Please using git, rather than BCE....

**Comment by jiangjiajun** [comment]
Hi, Do you mean you cannot download the files stored on bce server?

**Comment by lucasjinreal** [comment]
https://bj.bcebos.com/fastdeploy/third_libs/paddle2onnx-osx-arm64-1.0.1.tgz

can u pelase open it

**Comment by jiangjiajun** [comment]
> https://bj.bcebos.com/fastdeploy/third_libs/paddle2onnx-osx-arm64-1.0.1.tgz
> 
> can u pelase open it

This file is not on the server, we will upload it, please rebuild the code in half hours, sorry for the bug.

Or you can modify`FastDeploy/cmake/paddle2onnx.cmake`, change `VERSION` from `1.0.1` to `1.0.1rc`

**Comment by jiangjiajun** [comment]
@jinfagang Hi, the file is uploaded now, if there's any problem, please comment on this issue

**Comment by jiangjiajun** [comment]
此ISSUE由于一年未更新，将会关闭处理，如有需要，可再次更新打开。
