### ISSUE TITLE
3D Object Detection什么时候可以支持

### ISSUE THREAD

**Issue by A1exy** [PaddlePaddle/FastDeploy#358]
请问3D Object Detection计划什么时候可以支持

**Comment by jiangjiajun** [comment]
Hi, @A1exy 你有哪个模型的需求呢？

**Comment by A1exy** [comment]
@jiangjiajun  单目3D的都可以，比如SMOKE等，短期内有计划支持不

**Comment by A1exy** [comment]
我看你们列出来要支持3D目标检测

**Comment by jiangjiajun** [comment]
此ISSUE由于一年未更新，将会关闭处理，如有需要，可再次更新打开。
