### ISSUE TITLE
serving部署，设置tensorrt推理引擎无效

### ISSUE THREAD

**Issue by richjjj** [PaddlePaddle/FastDeploy#360]
镜像是paddlepaddle/fastdeploy:0.3.0-gpu-cuda11.4-trt8.4-21.10

![image](https://user-images.githubusercontent.com/37280580/195551974-5ea80b55-1619-49ad-a2b5-1f1ce08a8b0a.png)
![image](https://user-images.githubusercontent.com/37280580/195552332-e3d9dc85-7d7e-463f-b048-29e6411e1edb.png)

**Comment by heliqi** [comment]
配置有换成GPU吗？ TensorRT只能跑在GPU上， 比如配置改成如下:

instance_group [
  {
      count: 1
      kind: KIND_GPU
      gpus:[0]
  }
]


runtime的config配置可以参照这个文档，有详细介绍: https://github.com/PaddlePaddle/FastDeploy/blob/develop/serving/docs/zh_CN/model_configuration.md

**Comment by richjjj** [comment]
有的，输出日志是 Backend::ORT in Device::GPU

**Comment by heliqi** [comment]
是哪个模型？有删掉重新拉最新的镜像吗（中间有更新）？我这边测试yolo是可以的启动的

如果是最新镜像，麻烦提供下模型，我这边验证下

**Comment by richjjj** [comment]
嗯嗯，新版本的镜像没问题啦
