### ISSUE TITLE
Windows GPU环境下使用，提示cudnn64_8.dll异常

### ISSUE THREAD

**Issue by publicforlijun** [PaddlePaddle/FastDeploy#362]
![Untitled](https://user-images.githubusercontent.com/37092245/195559567-64fdb5a8-3535-48c6-a6ea-1586ed62aa85.png)

**Comment by publicforlijun** [comment]
显卡是NVIDIA GeForce GTX 1660 SUPER

**Comment by publicforlijun** [comment]
CUDA   v11.8
cudnn-windows-x86_64-8.6.0.163_cuda11-archive

**Comment by jiangjiajun** [comment]
看这个错误像是没有找到cudnn, 有配置环境变量吗？

**Comment by DefTruth** [comment]
@publicforlijun 有详细的log吗，看看具体是啥问题

**Comment by publicforlijun** [comment]
> 看这个错误像是没有找到cudnn, 有配置环境变量吗？

报错出现在cudnn64_8.dll里面   
![Untitled](https://user-images.githubusercontent.com/37092245/195747528-e4675b9b-94f2-4b43-9528-3687042aa9a6.png)
从进程加载DLL来看,有3个cudnn开头的,应该不是环境问题吧

**Comment by DefTruth** [comment]
目前我们还没有在 cuda 11.8 + cudnn 8.6.x 这种最新的配置上测试过，应该是cuda最近更新了版本，我们先尝试下复现您的问题哈

**Comment by publicforlijun** [comment]
> @publicforlijun 有详细的log吗，看看具体是啥问题
![Uploading Untitled.png…]()

提示zlibwapi.dll找不到，这个是干嘛用的？

**Comment by publicforlijun** [comment]
> 提示zlibwapi.dll找不到，这个是干嘛用的？



> 目前我们还没有在 cuda 11.8 + cudnn 8.6.x 这种最新的配置上测试过，应该是cuda最近更新了版本，我们先尝试下复现您的问题哈

提示zlibwapi.dll找不到，这个是干嘛用的？

**Comment by publicforlijun** [comment]
zlibwapi.dll 缺失导致的报错.找到对应zlip资源问题修正

**Comment by DefTruth** [comment]
> > 提示zlibwapi.dll找不到，这个是干嘛用的？
> 
> > 目前我们还没有在 cuda 11.8 + cudnn 8.6.x 这种最新的配置上测试过，应该是cuda最近更新了版本，我们先尝试下复现您的问题哈
> 
> 提示zlibwapi.dll找不到，这个是干嘛用的？

高版本的cudnn引入了这个依赖，需要先安装zlip才能正常使用，可以看下官方文档：  
- https://docs.nvidia.com/deeplearning/cudnn/install-guide/index.html#install-windows

**Comment by YourHotPotato** [comment]
请问最后解决了吗？我也遇到了类似的错误：0x00007FFD6A50420D (cudnn64_8.dll) (Pro1.exe 中)处有未经处理的异常: 请求了严重的程序退出。

**Comment by Object1009** [comment]
> 请问最后解决了吗？我也遇到了类似的错误：0x00007FFD6A50420D (cudnn64_8.dll) (Pro1.exe 中)处有未经处理的异常: 请求了严重的程序退出。

你好老铁，我也遇到了同样的问题，请问你解决了吗？

**Comment by zhubinhe** [comment]
我也遇到了 怎么解决啊 更换dll文件 重新下驱动都没解决

**Comment by cai123cai-hub** [comment]
<img width="1328" height="669" alt="Image" src="https://github.com/user-attachments/assets/465f9528-c688-486a-8f76-0caba2469b33" />我也遇到了同样的问题

**Comment by SongPool** [comment]
我也碰到了相同的问题，通过提示的缺少dll找到这个博客，下载zlibwapi.dll放到指定文件夹就行了
https://www.cnblogs.com/Terrypython/p/18178934
