### ISSUE TITLE
希望能够尽快适配好PP-ShiTu。

### ISSUE THREAD

**Issue by yingeo** [PaddlePaddle/FastDeploy#369]
目前pp-shitu的端侧部署很困难，尤其是跨平台，希望FastDeploy适配好pp-shitu的端侧部署，尤其是Windows上的部署。

**Comment by ChaoII** [comment]
附议

**Comment by ziqi-jin** [comment]
PP-ShiTu 的部署已经着手开发，预计近期能够完成，请您耐心等待😄

**Comment by ziqi-jin** [comment]
> yingeo

您好，您有尝试过在Windows上安装PP-ShiTu需要的FAISS库吗

**Comment by yingeo** [comment]
是的

**Comment by ziqi-jin** [comment]
> 是的

您好，为了更好的集成PP-ShiTu，我想和您交流一下，是否方便编辑邮件发送您的微信号到 jinziqi01@baidu.com ，我会联系您。

**Comment by thomas-yanxin** [comment]
➕1

**Comment by LL020202** [comment]
＋１

**Comment by yingeo** [comment]
FastDeploy对PP-ShiTu的支持有进展了吗？

**Comment by monkeycc** [comment]
FastDeploy对PP-ShiTu的支持有进展了吗？

**Comment by yingeo** [comment]
你好，shitu一直没动静，请问大概是么时候会适配好呢？

**Comment by monkeycc** [comment]
PP-ShiTu

2023年了 还没弄

**Comment by shao77622** [comment]
+1，waiting for pp-shitu

**Comment by shao77622** [comment]
wish a pp-shitu python sdk，including build_gallery.

**Comment by thomas-yanxin** [comment]
PP-ShiTu到哪一步了（~_~

**Comment by jiangjiajun** [comment]
> PP-ShiTu到哪一步了（~_~

50%

**Comment by Hongyuan-Liu** [comment]
我也在做PP-shitu，在rv1126上用rk官方的做法部署，量化掉点很大，不知道用fastdeploy是否在精度和性能上都有提升

**Comment by thomas-yanxin** [comment]
> > PP-ShiTu到哪一步了（~_~
> 
> 50%

再来问一问

**Comment by wenzhu2018** [comment]
> P-ShiTu需

问一下，现在是什么情况
