### ISSUE TITLE
有计划支持Multi-object tracking PP-Tracking吗？

### ISSUE THREAD

**Issue by jerryandjune** [PaddlePaddle/FastDeploy#373]
对应PaddleDetection：https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.5/configs/mot

**Comment by jiangjiajun** [comment]
https://github.com/PaddlePaddle/FastDeploy/pull/357 你是指这个模型吗，正在PR Review中

**Comment by ChaoII** [comment]
已经PR，注意：目前测试支持单阶段JDE部署方式，SED（由检测和embeding两个模型串联）的方式暂不支持，建议fairMOT，后期合并后，欢迎编译并尝试部署，有任何问题欢迎提issue。

**Comment by jerryandjune** [comment]
看到已经更新了，感谢

**Comment by jiangjiajun** [comment]
此ISSUE由于一年未更新，将会关闭处理，如有需要，可再次更新打开。
