### ISSUE TITLE
yolov7 姿态

### ISSUE THREAD

**Issue by JustinBili** [PaddlePaddle/FastDeploy#390]
请问近期会有计划部署yolov7 的人体姿态识别吗？

**Comment by DefTruth** [comment]
是指这个分支吗：
- https://github.com/WongKinYiu/yolov7/tree/pose

**Comment by JustinBili** [comment]
> 
是的

**Comment by jiangjiajun** [comment]
此ISSUE由于一年未更新，将会关闭处理，如有需要，可再次更新打开。
