### ISSUE TITLE
matting 是否支持背景全透明

### ISSUE THREAD

**Issue by publicforlijun** [PaddlePaddle/FastDeploy#391]
我想要matting后的图片背景全部透明.
![Untitled](https://user-images.githubusercontent.com/37092245/196347590-0436a6ad-3cdd-47de-bf50-51a3303798dd.png)

尝试了使用一张256X256全透明的png图片,替换读取图片默认IMREAD_COLOR参数为IMREAD_UNCHANGED,在SwapBackgroundMatting的时候会有内存报错.

**Comment by DefTruth** [comment]
你的背景是4通道吗？目前暂时只支持3通道的背景替换

**Comment by publicforlijun** [comment]
> 你的背景是4通道吗？目前暂时只支持3通道的背景替换

也就是通过SwapBackgroundMatting是没法让分割后的背景透明？有没有方法让分割后的图片存储出来的图片带Alpha通道使得背景透明？

**Comment by jiangjiajun** [comment]
全透明的图，opencv支持吗，是否是需要Pillow来画图才行

**Comment by evehal** [comment]
请支持透明通道,没有透明通道还需要抠像,这不多此一举吗

**Comment by DefTruth** [comment]
我们正在排期来支持相关的功能哈~

**Comment by jiangjiajun** [comment]
此ISSUE由于一年未更新，将会关闭处理，如有需要，可再次更新打开。
