### ISSUE TITLE
Python CPU版本推理时报错：RuntimeError: FastDeploy initalized failed!

### ISSUE THREAD

**Issue by stq054188** [PaddlePaddle/FastDeploy#398]
运行环境：Win10 64位，Python3.7.5，fastdeploy-python==0.3.0
安装fastdeploy-python版本如下：
https://www.paddlepaddle.org.cn/whl/fastdeploy.html
[fastdeploy_python-0.3.0-cp37-cp37m-win_amd64.whl](https://bj.bcebos.com/fastdeploy/release/wheels/fastdeploy_python-0.3.0-cp37-cp37m-win_amd64.whl)
——————————————————————————————
运行代码(官方给的Demo Code)：
`import cv2
import fastdeploy.vision as vision

model = vision.detection.PPYOLOE("ppyoloe_crn_l_300e_coco/model.pdmodel",
                                 "ppyoloe_crn_l_300e_coco/model.pdiparams",
                                 "ppyoloe_crn_l_300e_coco/infer_cfg.yml")
im = cv2.imread("000000014439.jpg")
result = model.predict(im.copy())
print(result)

vis_im = vision.vis_detection(im, result, score_threshold=0.5)
cv2.imwrite("vis_image.jpg", vis_im)
`
——————————————————————————————
报错信息：
Traceback (most recent call last):
  File "D:\Python37\lib\site-packages\fastdeploy\c_lib_wrap.py", line 159, in <module>
    from .libs.fastdeploy_main import *
ImportError: DLL load failed: 找不到指定的程序。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\360MoveData\Users\xxx\Desktop\FastDeploy_Paddle\FastDeploy.py", line 2, in <module>
    import fastdeploy.vision as vision
  File "D:\Python37\lib\site-packages\fastdeploy\__init__.py", line 19, in <module>
    from .c_lib_wrap import (ModelFormat, Backend, FDDataType, TensorInfo, Device,
  File "D:\Python37\lib\site-packages\fastdeploy\c_lib_wrap.py", line 161, in <module>
    raise RuntimeError("FastDeploy initalized failed!")
RuntimeError: FastDeploy initalized failed!
——————————————————————————————
安装对应包的版本如下：
Requirement already satisfied: tqdm in d:\python37\lib\site-packages (from fastdeploy-python==0.3.0) (4.63.0)
Requirement already satisfied: wheel in d:\python37\lib\site-packages (from fastdeploy-python==0.3.0) (0.37.1)
Requirement already satisfied: requests in d:\python37\lib\site-packages (from fastdeploy-python==0.3.0) (2.27.1)
Requirement already satisfied: opencv-python in d:\python37\lib\site-packages (from fastdeploy-python==0.3.0) (4.1.2.30)
Requirement already satisfied: numpy in d:\python37\lib\site-packages (from fastdeploy-python==0.3.0) (1.21.5)
Requirement already satisfied: charset-normalizer~=2.0.0 in d:\python37\lib\site-packages (from requests->fastdeploy-python==0.3.0) (2.0.12)
Requirement already satisfied: idna<4,>=2.5 in d:\python37\lib\site-packages (from requests->fastdeploy-python==0.3.0) (3.3)
Requirement already satisfied: certifi>=2017.4.17 in d:\python37\lib\site-packages (from requests->fastdeploy-python==0.3.0) (2021.10.8)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in d:\python37\lib\site-packages (from requests->fastdeploy-python==0.3.0) (1.26.8)
Requirement already satisfied: colorama in d:\python37\lib\site-packages (from tqdm->fastdeploy-python==0.3.0) (0.4.5)
——————————————————————————————
请问是否还有其他依赖项需要安装？

**Comment by DefTruth** [comment]
已经收到您的问题，我们的同学先尝试复现您的问题哈

**Comment by DefTruth** [comment]
我们这边目前复现不出这个情况，您那边可以尝试管理员权限运行试一下吗？或者卸载后重新安装试一下？另外就是可以看下您当前执行脚本的目录下是否有fastdeploy的同名目录，如果有的话可能python会优先从您的当前目录查找fastdeploy

**Comment by stq054188** [comment]
> 我们这边目前复现不出这个情况，您那边可以尝试管理员权限运行试一下吗？或者卸载后重新安装试一下？另外就是可以看下您当前执行脚本的目录下是否有fastdeploy的同名目录，如果有的话可能python会优先从您的当前目录查找fastdeploy

是管理员权限运行的，还是报相同的错误。

**Comment by DefTruth** [comment]
可以尝试在anaconda的环境中运行，有可能是缺少了某些系统库

**Comment by stq054188** [comment]
> 可以尝试在anaconda的环境中运行，有可能是缺少了某些系统库

看起来确实是这个问题，我在另外一台电脑上可以正常运行并得到结果，谢谢您的回复和帮助！
