### ISSUE TITLE
解码器使用的cpu还是gpu

### ISSUE THREAD

**Issue by yangyangyang0110** [PaddlePaddle/FastDeploy#4]

**Comment by jiangjiajun** [comment]
你是指视频解码吗？

**Comment by yangyangyang0110** [comment]
是的， 主要关心解码方面有没有硬件加速(尤其在nvidia-gpu设备上)

**Comment by leiqing1** [comment]
FastDeploy目前里面使用的CPU，没有调研NV的硬解码模块。目前常见的网络协议都支持（rtsp rtmp hls http）。
咱们这边必须使用GPU解码，是遇到什么性能瓶颈了吗？

**Comment by populustremble** [comment]
有没有关于硬解码的交流群啊

**Comment by GeT-RiGhTTT** [comment]
> 



> FastDeploy目前里面使用的CPU解码，没有调用NV的硬解码模块，目前常见的网络协议都支持（rtsp rtmp hls http）。 后续会根据大家需要，确定是否引入硬解码。方便加我微信（18813190139）深入交流这块的需求？

请问一下现在支持硬解码了吗，还有视频的多线程处理该怎么操作
