### ISSUE TITLE
使用android ocr sdk(就是这个EasyEdge-Android-paddle-ocr-arm-SDK），如何配置模型Infer的相关参数，有没有说明文档？

### ISSUE THREAD

**Issue by vsharer** [PaddlePaddle/FastDeploy#414]
例如在paddle ocr里，我们通常这样配置：= PaddleOCR(use_angle_cls=True, lang="ch",det_db_box_thresh =0.1, det_db_score_mode='slow') 。在android ocr sdk里，应该如何设置这些参数呢？（我想对应的初始化实例代码应该是：InferManager manager = new InferManager(context, config, serialNum)。

**Comment by leiqing1** [comment]
你好，参考v0.1里面的文档 https://github.com/PaddlePaddle/FastDeploy/blob/release/0.1/docs/ARM-Linux-CPP-SDK-Inference.md
FastDeploy近期会更新移动端的SDK，可以关注下

**Comment by vsharer** [comment]
谢谢。但这个不是ocr的sdk api说明文档。

**Comment by jiangjiajun** [comment]
此ISSUE由于一年未更新，将会关闭处理，如有需要，可再次更新打开。
