### ISSUE TITLE
web_demo ,npm install 为啥找不到包

### ISSUE THREAD

**Issue by kkkkkkxser** [PaddlePaddle/FastDeploy#419]
![image](https://user-images.githubusercontent.com/57437076/197441491-fa510999-1829-4473-a1fd-911c65f14d77.png)

**Comment by peterwangfeng** [comment]
please use yarn that's ok

**Comment by kkkkkkxser** [comment]
> please use yarn that's ok

谢谢 确实可行了 ，是不是这个package.json有问题啊，yarn安装的时候可选列表都没有4.0

![image](https://user-images.githubusercontent.com/57437076/197443171-86d3a85b-f95e-43dd-add5-15ea8394bdda.png)

**Comment by peterwangfeng** [comment]
是的啊

**Comment by peterwangfeng** [comment]
please use yarn that's ok

**Comment by chenqianhe** [comment]
这个才发包，目前仓库可以指定npm是正常的。国内镜像得看不同服务商的同步时间

**Comment by chenqianhe** [comment]
> > please use yarn that's ok
> 
> 谢谢 确实可行了 ，是不是这个package.json有问题啊，yarn安装的时候可选列表都没有4.0
> 
> ![image](https://user-images.githubusercontent.com/57437076/197443171-86d3a85b-f95e-43dd-add5-15ea8394bdda.png)
> 
> 

yarn有的目前只建议3.1.0，3.1.1可能会有异常。
