### ISSUE TITLE
可支持推理结果、绘制分开执行吗？？

### ISSUE THREAD

**Issue by fanyuanxiang** [PaddlePaddle/FastDeploy#446]
fast deploy 可以支持推理和可视化结果分开吗；预测得到的DetectionResult 结果 ( result = model.predict(im.copy()) ) .可以支持序列化吗？ 然后在反序列化结果执行 vis_im = vision.vis_detection(im, result, score_threshold=0.5) 得到绘制检测对象的图片？

使用pickle序列化会出现错误
TypeError: can't pickle fastdeploy.libs.fastdeploy_main.vision.DetectionResult objects

**Comment by jiangjiajun** [comment]
目前结果还没有支持Pickle操作，会添加到后面支持

**Comment by jiangjiajun** [comment]
此ISSUE由于一年未更新，将会关闭处理，如有需要，可再次更新打开。
