### ISSUE TITLE
paddle_inference.cmake 版本更新需要同步更新 paddle inference IPU安装包

### ISSUE THREAD

**Issue by czr-gc** [PaddlePaddle/FastDeploy#466]
[commit](https://github.com/PaddlePaddle/FastDeploy/commit/f2747133d62f55b1b418dbc4e2f72089a28d2189) 更新了paddle_inference的版本名称，但是上传的IPU安装包后缀是`2.4-dev1`, 需要麻烦fastdeploy的同事同步更新下云端IPU安装包命名，否则会下载失败。谢谢。

**Comment by jiangjiajun** [comment]
已解决 https://github.com/PaddlePaddle/FastDeploy/pull/467
