### ISSUE TITLE
无法下载 FastDeploy macOS arm64 预编译库

### ISSUE THREAD

**Issue by albyho** [PaddlePaddle/FastDeploy#477]
[fastdeploy-osx-arm64-0.3.0.tgz](https://bj.bcebos.com/fastdeploy/release/cpp/fastdeploy-osx-arm64-0.4.0.tgz)

**Comment by jiangjiajun** [comment]
https://bj.bcebos.com/fastdeploy/dev/cpp/fastdeploy-osx-arm64-0.5.0.tgz

试下这个

**Comment by albyho** [comment]
> https://bj.bcebos.com/fastdeploy/dev/cpp/fastdeploy-osx-arm64-0.5.0.tgz
> 
> 试下这个

还是不行呢。

**Comment by jiangjiajun** [comment]
> > https://bj.bcebos.com/fastdeploy/dev/cpp/fastdeploy-osx-arm64-0.5.0.tgz
> > 
> > 试下这个
> 
> 还是不行呢。
> 
> 

这个可以下载哦，你说的不行是指运行有问题吗

**Comment by albyho** [comment]
是的，采用"非"科学上网能直接下载。
