### ISSUE TITLE
easyedge ocr的sdk,是否有文档？

### ISSUE THREAD

**Issue by vsharer** [PaddlePaddle/FastDeploy#480]
api接口说明，以及ocr模型相关的参数有哪些 ，在哪里配置？这些是否提供说明？例如det_db_box_thresh =0.3,det_db_score_mode='slow', det_limit_type='min'，这些参数在服务版的ocr里是可以配置的，但在easyedge里如何配置？

**Comment by leiqing1** [comment]
你好，easyedge的文档有的，直接在网页就可以看，详细见该图
![image](https://user-images.githubusercontent.com/54695910/199439302-e9535c2f-fa6e-4c05-850e-32092696a870.png)

**Comment by leiqing1** [comment]
@vsharer easyedge里面的demo是体验版本，不支持模型层面的配置哈，可以直接用来集成试用。

**Comment by vsharer** [comment]
> @vsharer easyedge里面的demo是体验版本，不支持模型层面的配置哈，可以直接用来集成试用。

谢谢。那我需要进行模型层面的配置，例如"det_db_box_thresh =0.3,det_db_score_mode='slow', det_limit_type='min'",需要怎么做呢

**Comment by leiqing1** [comment]
> 

这个需要看一下Java代码，研究下能不能修改。 easyedge的Java代码是开源的，可以直接修改。

**Comment by vsharer** [comment]
> > 
> 
> 这个需要看一下Java代码，研究下能不能修改。 easyedge的Java代码是开源的，可以直接修改。

easyedge我只下载到ocr sdk的编译过的包，请问其中的j开源ava代码时在哪里有，能否提供一下链接，谢谢。

**Comment by jiangjiajun** [comment]
此ISSUE由于一年未更新，将会关闭处理，如有需要，可再次更新打开。
