### ISSUE TITLE
如何将代码集成到我自己开发的app中呢？

### ISSUE THREAD

**Issue by wzy123456wzy** [PaddlePaddle/FastDeploy#483]
如何将代码集成到我自己开发的app中呢，我想在自己的app中调用模型

**Comment by DefTruth** [comment]
可以先参考这个文档在Android接入FastDeploy的模型能力哈，我们计划会在后续提供aar包直接调用。目前可以通过JNI的方式接入您想使用的模型（暂时只支持Paddle系列的模型），参考文档：  
- [在 Android 中通过 JNI 使用 FastDeploy C++ SDK](https://github.com/PaddlePaddle/FastDeploy/blob/develop/docs/cn/faq/use_cpp_sdk_on_android.md)    

以及相关的app案例：  
- [图像分类Android使用文档](../../../examples/vision/classification/paddleclas/android/README.md)  
- [目标检测Android使用文档](../../../examples/vision/detection/paddledetection/android/README.md)

**Comment by jiangjiajun** [comment]
此ISSUE由于一年未更新，将会关闭处理，如有需要，可再次更新打开。
