### ISSUE TITLE
paddleocr训练出来的三个模型，能否部署到同一个web服务上？

### ISSUE THREAD

**Issue by waizao** [PaddlePaddle/FastDeploy#501]
用paddleocr训练出来的三个模型，模型1为验证码识别，模型2为身份证件识别，模型3为动物识别
能否多个模型用开启一个web服务（即只用一个端口8866），通过url路径参数区分模型？
这种场景，怎么使用FastDeploy部署哈？

**Comment by magicleo** [comment]
同问！
