### ISSUE TITLE
RKNPU2 import issue

### ISSUE THREAD

**Issue by czr-gc** [PaddlePaddle/FastDeploy#519]
FastDeploy在设备无关的代码上import了设备相关的依赖`RKNPU2`:

https://github.com/PaddlePaddle/FastDeploy/blob/f95654b7ef818781899f19f7d56f90b67f0f3b9d/python/fastdeploy/runtime.py#L19
https://github.com/PaddlePaddle/FastDeploy/blob/f95654b7ef818781899f19f7d56f90b67f0f3b9d/python/fastdeploy/__init__.py#L22

如果源码编译时，没有enable rknpu2,  `import fastdeploy`会报错：
```
(base) λ sgjur-pod006-1 python → λ git develop* → python infer.py --model ResNet50_vd_infer --image ILSVRC2012_val_00000010.jpeg --device cpu --topk 1
Traceback (most recent call last):
  File "infer.py", line 1, in <module>
    import fastdeploy as fd
  File "/root/miniconda3/lib/python3.7/site-packages/fastdeploy/__init__.py", line 19, in <module>
    from .c_lib_wrap import (
ImportError: cannot import name 'rknpu2' from 'fastdeploy.c_lib_wrap' (/root/miniconda3/lib/python3.7/site-packages/fastdeploy/c_lib_wrap.py)
```

建议将RKNPU包一层不要直接import进来。

另外， `ModelFormat`被import了两次，应该也是个小问题：
https://github.com/PaddlePaddle/FastDeploy/blob/f95654b7ef818781899f19f7d56f90b67f0f3b9d/python/fastdeploy/__init__.py#L20
https://github.com/PaddlePaddle/FastDeploy/blob/f95654b7ef818781899f19f7d56f90b67f0f3b9d/python/fastdeploy/__init__.py#L28

**Comment by czr-gc** [comment]
Update:

进一步debug发现，问题出现在：

https://github.com/PaddlePaddle/FastDeploy/blob/e8343909ca523f92c955723fe2a5d64f6c966938/fastdeploy/backends/paddle/paddle_backend.cc#L102

这一行编译报错没有注意，导致pybind添加rknpu没有正确执行。后面import出现错误。

`paddle2onnx` 需要include `paddle2onnx.cmake`进行编译。如果只编译paddle后端，`paddle2onnx.cmake`似乎并没有正确的添加进来，需要做如下更改才行：

```
diff --git a/CMakeLists.txt b/CMakeLists.txt
index 2dd5a15..7c2c470 100755
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -205,6 +205,7 @@ if(ENABLE_LITE_BACKEND)
 endif()

 if(ENABLE_PADDLE_BACKEND)
+  set(ENABLE_PADDLE_FRONTEND ON)
   add_definitions(-DENABLE_PADDLE_BACKEND)
   list(APPEND ALL_DEPLOY_SRCS ${DEPLOY_PADDLE_SRCS})
   include(${PROJECT_SOURCE_DIR}/cmake/paddle_inference.cmake)
```

**Comment by czr-gc** [comment]
@jiangjiajun , 还麻烦确认下CMake中需要的`ENABLE_PADDLE_FRONTEND`是不是一个问题？

**Comment by czr-gc** [comment]
Fixed in https://github.com/PaddlePaddle/FastDeploy/pull/522

**Comment by jiangjiajun** [comment]
PR已合入解决，感谢
