### ISSUE TITLE
编译后打开编译代码，引入都报错了

### ISSUE THREAD

**Issue by chfeizy** [PaddlePaddle/FastDeploy#521]
git clone https://github.com/PaddlePaddle/FastDeploy.git
cd FastDeploy
mkdir build && cd build
cmake .. -DENABLE_ORT_BACKEND=ON \
         -DENABLE_PADDLE_BACKEND=ON \
         -DENABLE_OPENVINO_BACKEND=ON \
         -DCMAKE_INSTALL_PREFIX=${PWD}/compiled_fastdeploy_sdk \
         -DENABLE_VISION=ON \
         -DENABLE_TEXT=ON
make -j12
make install

按照以上执行后打开compiled_fastdeploy_sdk里的代码
<img width="1475" alt="image" src="https://user-images.githubusercontent.com/6427629/200478980-0d34cd8c-1e1f-4fa2-9dad-0c7b603cb6ed.png">
引入都报错的

**Comment by chfeizy** [comment]
<img width="360" alt="image" src="https://user-images.githubusercontent.com/6427629/200479210-f3de29fb-450b-4140-8a65-8ccf53ddf87f.png">
opencv用的3.4.16 的这个版本太低了现在基本都用4.5 的了

**Comment by jiangjiajun** [comment]
你这里指的报错，是指编译出错了吗？ 能否贴一下错误日志

**Comment by chfeizy** [comment]
直接打开编译生成里的example文件，是引用有问题

**Comment by jiangjiajun** [comment]
是指IDE里面的显示问题吗？ 你的IDE是VS Code吗？

**Comment by chfeizy** [comment]
clion

**Comment by chfeizy** [comment]
感觉是库的引用有问题，结构里代码都有的

**Comment by chfeizy** [comment]
知道了是例子要单独再引入刚才编译的 sdk

**Comment by chfeizy** [comment]
<img width="1117" alt="image" src="https://user-images.githubusercontent.com/6427629/200513763-145aea60-546c-487f-8d8d-25a785bb55d6.png">
/Users/also/www/FastDeploy/examples/vision/matting/rvm/cpp/build/infer_demo
infer_demo(25161,0x7ff84c6be4c0) malloc: Attempted to register zone more than once: 0x10ebe2160
[INFO] fastdeploy/runtime.cc(513)::Init	Runtime initialized with Backend::OPENVINO in Device::CPU.
Visualized result save in ./visualized_result.jpg and ./visualized_result_fg.jpg
infer_demo(25161,0x7ff84c6be4c0) malloc: *** error for object 0x111931b40: pointer being freed was not allocated
infer_demo(25161,0x7ff84c6be4c0) malloc: *** set a breakpoint in malloc_error_break to debug
Signal: SIGABRT (signal SIGABRT)
Terminated due to signal 6

Process finished with exit code 6


运行测试会进入断点

**Comment by wuhongsheng** [comment]
+1
