### ISSUE TITLE
paddlex inference_model 模型可以支持使用fastDeploy推理、部署吗 ？

### ISSUE THREAD

**Issue by fanyuanxiang** [PaddlePaddle/FastDeploy#527]
paddlex v1.3.0

├── model.yml
├── __model__
└──  __params__
        
==============
paddlex v2.1.0

├── model.pdiparams
├── model.pdiparams.info
├── model.pdmodel
├── model.yml
└── pipeline.yml

**Comment by jiangjiajun** [comment]
暂时还没支持，你可以在这里按优先级列一下你想支持部署的模型吗？

**Comment by fanyuanxiang** [comment]
> 暂时还没支持，你可以在这里按优先级列一下你想支持部署的模型吗？

faster_rcnn_r50_fpn、ppyolov2、resnet50_vd_ssld 、deeplabv3p_resnet50_vd

**Comment by jiangjiajun** [comment]
此ISSUE由于一年未更新，将会关闭处理，如有需要，可再次更新打开。
