### ISSUE TITLE
PP-OCRv3识别中文字符乱码

### ISSUE THREAD

**Issue by sunyuchen1977** [PaddlePaddle/FastDeploy#537]
运行examples\vision\ocr\PP-OCRv3\cpp中的infer.cc代码，可以检测到字符具体位置，但是输出的中文字符内容是乱码，数字正常。模型、字典都确认过没问题。

**Comment by yunyaoXYY** [comment]
> 运行examples\vision\ocr\PP-OCRv3\cpp中的infer.cc代码，可以检测到字符具体位置，但是输出的中文字符内容是乱码，数字正常。模型、字典都确认过没问题。

Hi你好，我想确认一下
模型和字典都是从FastDeploy提供的链接下载的吗？
预测的图片用的是什么图片呢，方便发一下吗，我来复现一下

**Comment by sunyuchen1977** [comment]
你好，昨天回复了，不知为啥没了。模型和字典都都是从FastDeploy提供的链接下载的，我试了几张图片，都是中文乱码，数字没问题，所以应该有中文的图片就能复现。不知是不是我这配置问题。

> > 运行examples\vision\ocr\PP-OCRv3\cpp中的infer.cc代码，可以检测到字符具体位置，但是输出的中文字符内容是乱码，数字正常。模型、字典都确认过没问题。
> 
> Hi你好，我想确认一下 模型和字典都是从FastDeploy提供的链接下载的吗？ 预测的图片用的是什么图片呢，方便发一下吗，我来复现一下

**Comment by yunyaoXYY** [comment]
> 

你好，我在linux上复现了没有问题呢.  你是在Win上部署的吗，可以检查下输出的编码格式，可能是这个导致乱码

**Comment by yunyaoXYY** [comment]
> 你好，昨天回复了，不知为啥没了。模型和字典都都是从FastDeploy提供的链接下载的，我试了几张图片，都是中文乱码，数字没问题，所以应该有中文的图片就能复现。不知是不是我这配置问题。
> 
> > > 运行examples\vision\ocr\PP-OCRv3\cpp中的infer.cc代码，可以检测到字符具体位置，但是输出的中文字符内容是乱码，数字正常。模型、字典都确认过没问题。
> > 
> > 
> > Hi你好，我想确认一下 模型和字典都是从FastDeploy提供的链接下载的吗？ 预测的图片用的是什么图片呢，方便发一下吗，我来复现一下

你好，我在linux上复现了没有问题呢. 你是在Win上部署的吗，可以检查下输出的编码格式，可能是这个导致乱码

**Comment by sunyuchen1977** [comment]
> > 你好，昨天回复了，不知为啥没了。模型和字典都都是从FastDeploy提供的链接下载的，我试了几张图片，都是中文乱码，数字没问题，所以应该有中文的图片就能复现。不知是不是我这配置问题。
> > > > 运行examples\vision\ocr\PP-OCRv3\cpp中的infer.cc代码，可以检测到字符具体位置，但是输出的中文字符内容是乱码，数字正常。模型、字典都确认过没问题。
> > > 
> > > 
> > > Hi你好，我想确认一下 模型和字典都是从FastDeploy提供的链接下载的吗？ 预测的图片用的是什么图片呢，方便发一下吗，我来复现一下
> 
> 你好，我在linux上复现了没有问题呢. 你是在Win上部署的吗，可以检查下输出的编码格式，可能是这个导致乱码

你好，我是在win10上部署的，用的vs2019，调整了一下编码格式后问题解决了。感谢回复。

**Comment by GreenAvocado92** [comment]
> 

你好，我也遇到相同的问题了，我想问下，怎么改编码格式
