### ISSUE TITLE
您好，我在使用您们给的yolov7end2end_trt案例时，遇到问题CudaCast only support input INT64, output INT32。

### ISSUE THREAD

**Issue by TWK2022** [PaddlePaddle/FastDeploy#549]
您好，我在使用您们给的yolov7end2end_trt案例时，遇到问题CudaCast only support input INT64, output INT32。
我的环境是windows，fastdeploy-gpu-python0.5,0，python3.8.5，cuda11.6，cudnn11.6
使用的命令是python infer.py --model yolov7-end2end-trt-nms.onnx --image 001.jpg --device gpu --use_trt True
报错信息是：
[FastDeploy][INFO]:  Successfully found CUDA ToolKit from system PATH env -> D:\CUDA\development\bin
[INFO] fastdeploy/backends/tensorrt/trt_backend.cc(486)::fastdeploy::TrtBackend::BuildTrtEngine Start to building TensorRT Engine...
[INFO] fastdeploy/backends/tensorrt/trt_backend.cc(572)::fastdeploy::TrtBackend::BuildTrtEngine TensorRT Engine is built successfully.
[INFO] fastdeploy/runtime.cc(475)::fastdeploy::Runtime::Init    Runtime initialized with Backend::TRT in Device::GPU.
[ERROR] fastdeploy/function/cuda_cast.cu(41)::fastdeploy::CudaCast      CudaCast only support input INT64, output INT32.
非常感谢!!

**Comment by wang-xinyu** [comment]
我这里没有复现这个问题， 您的yolov7-end2end-trt-nms.onnx是下载的这个文件吗？https://bj.bcebos.com/paddlehub/fastdeploy/yolov7-end2end-trt-nms.onnx

**Comment by TWK2022** [comment]
> 我这里没有复现这个问题， 您的yolov7-end2end-trt-nms.onnx是下载的这个文件吗？https://bj.bcebos.com/paddlehub/fastdeploy/yolov7-end2end-trt-nms.onnx

是的，我也重新用您给的链接试了一次

**Comment by wang-xinyu** [comment]
安装fastdeploy-gpu-python的命令是什么呢？

**Comment by TWK2022** [comment]
> 安装fastdeploy-gpu-python的命令是什么呢？

是这个：pip install fastdeploy-gpu-python -f https://www.paddlepaddle.org.cn/whl/fastdeploy.html

**Comment by wang-xinyu** [comment]
复现了，0.5.0有问题，我再debug一下。

0.6.0可以
您试一下pip install fastdeploy-gpu-python==0.6.0 -f https://www.paddlepaddle.org.cn/whl/fastdeploy.html

**Comment by TWK2022** [comment]
> 复现了，0.5.0有问题，我再debug一下。
> 
> 0.6.0可以 您试一下pip install fastdeploy-gpu-python==0.6.0 -f https://www.paddlepaddle.org.cn/whl/fastdeploy.html

好像是不是没有windows版本的呢

**Comment by wang-xinyu** [comment]
我这里能安装， 或者直接下载这个 https://bj.bcebos.com/fastdeploy/dev/wheels/fastdeploy_gpu_python-0.6.0-cp38-cp38-win_amd64.whl

**Comment by TWK2022** [comment]
> 我这里能安装， 或者直接下载这个 https://bj.bcebos.com/fastdeploy/dev/wheels/fastdeploy_gpu_python-0.6.0-cp38-cp38-win_amd64.whl

可以啦，太感谢了，还专门发了邮件，谢谢(✪▽✪)(｡･ω･｡)ﾉ♡♡♡
