### ISSUE TITLE
cmake失败

### ISSUE THREAD

**Issue by BuLuoPiaoYu** [PaddlePaddle/FastDeploy#57]
模型如下
![image](https://user-images.githubusercontent.com/54087448/181667247-54b036fd-72c3-4a5e-b0d3-05ee7480b85a.png)

cmake报错如下
![image](https://user-images.githubusercontent.com/54087448/181667209-1ad56baf-2156-4076-ba3f-85bd931de755.png)

**Comment by leiqing1** [comment]
直接cmake ..就行，不用加其他选项。

你是在cmake的时候把 EDGE_BUILD_OPENCV 编译选项开了吧，这个不用开的，SDK里面自带opencv的动态库
![image](https://user-images.githubusercontent.com/54695910/181729825-771ab65d-ae5f-4b5f-9008-15804ed069a4.png)
![image](https://user-images.githubusercontent.com/54695910/181729879-4c4e7113-e68e-415a-9f14-40504c7da059.png)
![image](https://user-images.githubusercontent.com/54695910/181729914-7d29d3c1-5b32-4c78-b637-5f8fbf58aa26.png)

**Comment by BuLuoPiaoYu** [comment]
不开Opencv是可以Cmake成功的，不过VS这边编译还是会报错的，不知道这个要怎么解决？
![image](https://user-images.githubusercontent.com/54087448/182054122-e50f98d9-6eb6-4702-810a-37e4fc3853a2.png)

VS报错信息
![image](https://user-images.githubusercontent.com/54087448/182053970-5045a3a1-fde8-41b6-ac81-d934d0ba1c1c.png)

**Comment by jiangjiajun** [comment]
此ISSUE由于一年未更新，将会关闭处理，如有需要，可再次更新打开。
