### ISSUE TITLE
FastDeploy部署模型时运行出错

### ISSUE THREAD

**Issue by colinchou2020** [PaddlePaddle/FastDeploy#596]
FastDeploy部署模型时运行出错，提示未加载kernelbase.pdb

**Comment by jiangjiajun** [comment]
是否与此issue是同一个问题？ https://github.com/PaddlePaddle/FastDeploy/issues/597

**Comment by chenqianhe** [comment]
> FastDeploy部署模型时运行出错，提示未加载kernelbase.pdb

确认下部署平台和语言哈，不像是js相关

**Comment by colinchou2020** [comment]
> > FastDeploy部署模型时运行出错，提示未加载kernelbase.pdb
> 
> 确认下部署平台和语言哈，不像是js相关

vs2019 CPU环境部署，编译库完全按按照官方指导的编译的

**Comment by chenqianhe** [comment]
@jiangjiajun 麻烦看看给谁处理哈

**Comment by colinchou2020** [comment]
> @jiangjiajun 麻烦看看给谁处理哈

fastdeploy::RuntimeOption option;  执行到这句的时候报的，在使用编译的fastdeploy.dll库测试PP-OCRv3例子时出现。

**Comment by jiangjiajun** [comment]
- 按照示例代码，使用命令行编译是否可以编译和执行
- 贴一下具体的出错提示截图

**Comment by colinchou2020** [comment]
![image](https://user-images.githubusercontent.com/50770300/204678731-6c31dc4f-b639-488c-be53-3ee307e59f6e.png)
![image](https://user-images.githubusercontent.com/50770300/204678749-5a645782-8dbe-4e02-a142-07809095fa31.png)

**Comment by colinchou2020** [comment]
库是使用这些编码的
![image](https://user-images.githubusercontent.com/50770300/204679207-92bbf9e7-131b-48ad-af99-f8ac257a49c5.png)

**Comment by colinchou2020** [comment]
库是使用这些编译的
![image](https://user-images.githubusercontent.com/50770300/204679243-a2e64ae1-3900-43ea-9b0d-d115a16fea72.png)

**Comment by colinchou2020** [comment]
使用编译的库测试这个demo时报错
![image](https://user-images.githubusercontent.com/50770300/204679427-03bff7bc-4a5c-40c0-b40c-35896ceb437b.png)

**Comment by colinchou2020** [comment]
> * 按照示例代码，使用命令行编译是否可以编译和执行
> * 贴一下具体的出错提示截图

以上是异常的情况，帮忙看看是什么问题，感谢

**Comment by jiangjiajun** [comment]
你好，试下给每个模型的option切换成option.UsePaddleInferBackend()试下，当前看到是openvino后端出错

**Comment by colinchou2020** [comment]
> 你好，试下给每个模型的option切换成option.UsePaddleInferBackend()试下，当前看到是openvino后端出错
还是报错呢
![image](https://user-images.githubusercontent.com/50770300/205053856-7029080e-b903-4e65-a2ac-ebad33323cb3.png)
![image](https://user-images.githubusercontent.com/50770300/205053903-eb74df61-acf6-48fb-8826-4444e78d2f06.png)

**Comment by colinchou2020** [comment]
> 你好，试下给每个模型的option切换成option.UsePaddleInferBackend()试下，当前看到是openvino后端出错



> 你好，试下给每个模型的option切换成option.UsePaddleInferBackend()试下，当前看到是openvino后端出错

仅运行这些代码就报错了

![image](https://user-images.githubusercontent.com/50770300/205054245-f3df9f9f-4f6f-4cd9-8319-8f819b047405.png)

**Comment by jiangjiajun** [comment]
请问你是使用命令行方式来编译的吗，试下使用命令行的方式进行编译看下呢？https://github.com/PaddlePaddle/FastDeploy/blob/develop/docs/cn/faq/use_sdk_on_windows.md#CommandLine

**Comment by qinlihaoWork** [comment]
遇到同样的错误，使用fastdeploy1.0.1、1.0.0、0.8.0都会报错(ov::Exception)，用0.3.0可以正常部署(winx64平台)

**Comment by jiangjiajun** [comment]
> 遇到同样的错误，使用fastdeploy1.0.1、1.0.0、0.8.0都会报错(ov::Exception)，用0.3.0可以正常部署(winx64平台)

运行的是什么模型呢？

**Comment by qinlihaoWork** [comment]
> 

运行的PP-PicoDet

**Comment by qinlihaoWork** [comment]
> > 遇到同样的错误，使用fastdeploy1.0.1、1.0.0、0.8.0都会报错(ov::Exception)，用0.3.0可以正常部署(winx64平台)
> 
> 运行的是什么模型呢？

运行的PP-PicoDet

**Comment by geoyee** [comment]
我也遇到了这个问题，但是我把`mklml.dll`放到release后就可以运行了

**Comment by franciszq** [comment]
请问解决了吗？我也遇到这个问题了

**Comment by franciszq** [comment]
> 我也遇到了这个问题，但是我把`mklml.dll`放到release后就可以运行了

我这边放了还是不行

**Comment by franciszq** [comment]
我这边解决了该问题，使用他们提供的工具把所有的dll放到了工程exe的目录下：https://github.com/PaddlePaddle/FastDeploy/blob/release/1.0.2/docs/cn/faq/use_sdk_on_windows.md#413-fastdeploy_initbat-%E5%AE%89%E8%A3%85-sdk-%E4%B8%AD%E6%89%80%E6%9C%89%E7%9A%84-dll-%E5%88%B0%E6%8C%87%E5%AE%9A%E7%9A%84%E7%9B%AE%E5%BD%95-%E6%8E%A8%E8%8D%90
