### ISSUE TITLE
Web Demo替换模型失败

### ISSUE THREAD

**Issue by dium6i** [PaddlePaddle/FastDeploy#597]
按照教程（https://github.com/PaddlePaddle/FastDeploy/blob/develop/examples/application/js/WebDemo.md ）来，使用 npm run dev 后成功运行demo，OCR中也可以正常识别。但在模型替换时，按照步骤3给的例子：
await ocr.init();
修改为
await ocr.init({modelPath: "https://js-models.bj.bcebos.com/PaddleOCR/PP-OCRv3/ch_PP-OCRv3_det_infer_js_960/model.json"});
替换模型后，再次 npm run dev 后，页面就一直停留在“正在加载模型”了。

检查网页元素，正常时det和rec的model.json都读取过来了；替换模型后，发现只有rec的model.json文件读取过来了。

是哪里还需要操作么，还是我的操作不对？

**Comment by chenqianhe** [comment]
> 按照教程（https://github.com/PaddlePaddle/FastDeploy/blob/develop/examples/application/js/WebDemo.md ）来，使用 npm run dev 后成功运行demo，OCR中也可以正常识别。但在模型替换时，按照步骤3给的例子： await ocr.init(); 修改为 await ocr.init({modelPath: "[https://js-models.bj.bcebos.com/PaddleOCR/PP-OCRv3/ch_PP-OCRv3_det_infer_js_960/model.json"}](https://js-models.bj.bcebos.com/PaddleOCR/PP-OCRv3/ch_PP-OCRv3_det_infer_js_960/model.json%22%7D)); 替换模型后，再次 npm run dev 后，页面就一直停留在“正在加载模型”了。
> 
> 检查网页元素，正常时det和rec的model.json都读取过来了；替换模型后，发现只有rec的model.json文件读取过来了。
> 
> 是哪里还需要操作么，还是我的操作不对？

看一下console的报错

**Comment by chenqianhe** [comment]
检查下console报错以及网络请求状况，是det根本没下载吗

**Comment by dium6i** [comment]
> 检查下console报错以及网络请求状况，是det根本没下载吗

我不太懂js，不知道下面的报错信息是不是您想要的。
![1111](https://user-images.githubusercontent.com/75460093/201890126-1042cfcf-caac-4fe0-a88c-77da0a07da87.jpg)

det的model.json根本没下载，只有rec的model.json下载了。
![2222](https://user-images.githubusercontent.com/75460093/201891004-0545217e-24df-4158-b309-c28fa719a702.jpg)

**Comment by chenqianhe** [comment]
> > 检查下console报错以及网络请求状况，是det根本没下载吗
> 
> 我不太懂js，不知道下面的报错信息是不是您想要的。 ![1111](https://user-images.githubusercontent.com/75460093/201890126-1042cfcf-caac-4fe0-a88c-77da0a07da87.jpg)
> 
> det的model.json根本没下载，只有rec的model.json下载了。 ![2222](https://user-images.githubusercontent.com/75460093/201891004-0545217e-24df-4158-b309-c28fa719a702.jpg)

如果是ocr完整调用的话，需要这样传入：
```
await ocr.init("https://js-models.bj.bcebos.com/PaddleOCR/PP-OCRv3/ch_PP-OCRv3_det_infer_js_960/model.json", "https://js-models.bj.bcebos.com/PaddleOCR/PP-OCRv3/ch_PP-OCRv3_rec_infer_js/model.json");
```
第一个参数时det模型，第二个参数时rec模型

文档实例有一些误导；给的是调用单个模型的改法

也可以通过接口定义看到参数怎么传；不同模型应用可能不太一样

<img width="804" alt="image" src="https://user-images.githubusercontent.com/54462604/201939950-0336524d-3ca3-41f7-b6e6-c097665d85a4.png">

**Comment by chenqianhe** [comment]
<img width="437" alt="image" src="https://user-images.githubusercontent.com/54462604/201940249-e4c4d0c2-c763-4f84-8d3f-181867535bff.png">

如果是这个的话就是参数传递问题

**Comment by dium6i** [comment]
> 如果是ocr完整调用的话，需要这样传入：
> 
> ```
> await ocr.init("https://js-models.bj.bcebos.com/PaddleOCR/PP-OCRv3/ch_PP-OCRv3_det_infer_js_960/model.json", "https://js-models.bj.bcebos.com/PaddleOCR/PP-OCRv3/ch_PP-OCRv3_rec_infer_js/model.json");
> ```
> 
> 第一个参数时det模型，第二个参数时rec模型
> 
> 文档实例有一些误导；给的是调用单个模型的改法
> 
> 也可以通过接口定义看到参数怎么传；不同模型应用可能不太一样
> 
> <img alt="image" width="804" src="https://user-images.githubusercontent.com/54462604/201939950-0336524d-3ca3-41f7-b6e6-c097665d85a4.png">

感谢回复，替换模型的问题已解决。还想再问一下，我下载官方的PPOCR-v3的det和rec推理模型（ https://paddleocr.bj.bcebos.com/PP-OCRv3/chinese/ch_PP-OCRv3_det_infer.tar 和 https://paddleocr.bj.bcebos.com/PP-OCRv3/chinese/ch_PP-OCRv3_rec_infer.tar ）用paddlejsconverter进行转换，得到了如下的结果，似乎是PPOCR-v3的模型不被支持？
![det](https://user-images.githubusercontent.com/75460093/202062856-da17a1c0-efe8-443e-a108-136427a4e150.jpg)
![rec](https://user-images.githubusercontent.com/75460093/202062876-44ebb510-19b2-45d8-93e3-6b0ad1ac97c2.jpg)
PaddleOCR提供的模型转换后与FastDeploy自带的model.json对比如下：（从左到右分别是OCR_det、FastDeploy_det、OCR_rec、FastDeploy_rec）
![compare](https://user-images.githubusercontent.com/75460093/202065085-e20b2736-33ae-4100-8db7-f83268154abe.jpg)
似乎模型输入的shape也不同，不知是不是paddlejsconverter（1.0.7）的问题。

替换成转换好的模型后，网页console信息如txt文档所示
[1668562773189.log](https://github.com/PaddlePaddle/FastDeploy/files/10017389/1668562773189.log)
看样子是部分op不被支持。

**Comment by chenqianhe** [comment]
@LDOUBLEV 帮忙看下是算子的问题吗

**Comment by dium6i** [comment]
使用PPOCR_v2的模型（ https://paddleocr.bj.bcebos.com/PP-OCRv2/chinese/ch_PP-OCRv2_det_infer.tar 和 https://paddleocr.bj.bcebos.com/PP-OCRv2/chinese/ch_PP-OCRv2_rec_infer.tar ）进行转换，得到如下的结果：
![det-v2](https://user-images.githubusercontent.com/75460093/202071155-402ec395-93b3-4feb-8036-9239391b4b9a.jpg)
![rec-v2](https://user-images.githubusercontent.com/75460093/202071166-37605c09-b707-484c-9f32-034b52869303.jpg)
网页可以正常加载模型，但识别图片无任何结果，console中部分信息如下：
![console](https://user-images.githubusercontent.com/75460093/202071867-e8feef0b-f8e8-47e2-8bb8-d1776edefa68.jpg)
有时console也会出现如下信息：
[1668567428135.log](https://github.com/PaddlePaddle/FastDeploy/files/10017746/1668567428135.log)

**Comment by LDOUBLEV** [comment]
> 替换模型的问题已解决。还想再问一下，我下载官方的PPOCR-v3的det和rec推理模型（ https://paddleocr.bj.bcebos.com/PP-OCRv3/chinese/ch_PP-OCRv3_det_infer.tar 和 https://paddleocr.bj.bcebos.com/PP-OCRv3/chinese/ch_PP-OCRv3_rec_infer.tar ）用paddlejsconverter进行转换，得到了如下的结果，似乎是PPOCR-v3的模型不被支持？


paddle.js 只支持固定shape的预测，现在PaddleOCR导出的inferencemodel都是动态shape的（h,w维度为-1）导致
paddle.js converter转模型后，h,w维度为1，解决方案如下：

重新导出inference model，导出inference model时，修改为固定shape；
以OCR检测为例：
修改 导出的shape ：https://github.com/PaddlePaddle/PaddleOCR/blob/44e60e81cc9a6e801f31080205734ff3069df675/tools/export_model.py#L161 为  infer_shape = [3, 960, 960] 

重新导出inference model ，再使用paddlejsconvert导出js模型。

导出后确认下model.json里的输入的h,w维度不是1了

**Comment by dium6i** [comment]
> 
> paddle.js 只支持固定shape的预测，现在PaddleOCR导出的inferencemodel都是动态shape的（h,w维度为-1）导致 paddle.js converter转模型后，h,w维度为1，解决方案如下：
> 
> 重新导出inference model，导出inference model时，修改为固定shape； 以OCR检测为例： 修改 导出的shape ：https://github.com/PaddlePaddle/PaddleOCR/blob/44e60e81cc9a6e801f31080205734ff3069df675/tools/export_model.py#L161 为 infer_shape = [3, 960, 960]
> 
> 重新导出inference model ，再使用paddlejsconvert导出js模型。
> 
> 导出后确认下model.json里的输入的h,w维度不是1了

修改后导出模型的model.json里的h, w维度正常了，但是网页端模型加载还是出问题，停留在正在加载模型的页面。console里的信息如下：（图片和txt）
![console](https://user-images.githubusercontent.com/75460093/202397544-ef271c75-1993-409e-b8f8-832294ecb058.jpg)
[1668674262817.log](https://github.com/PaddlePaddle/FastDeploy/files/10029437/1668674262817.log)

可以帮忙看看是哪里的问题么？ @chenqianhe

**Comment by chenqianhe** [comment]
> > paddle.js 只支持固定shape的预测，现在PaddleOCR导出的inferencemodel都是动态shape的（h,w维度为-1）导致 paddle.js converter转模型后，h,w维度为1，解决方案如下：
> > 重新导出inference model，导出inference model时，修改为固定shape； 以OCR检测为例： 修改 导出的shape ：https://github.com/PaddlePaddle/PaddleOCR/blob/44e60e81cc9a6e801f31080205734ff3069df675/tools/export_model.py#L161 为 infer_shape = [3, 960, 960]
> > 重新导出inference model ，再使用paddlejsconvert导出js模型。
> > 导出后确认下model.json里的输入的h,w维度不是1了
> 
> 修改后导出模型的model.json里的h, w维度正常了，但是网页端模型加载还是出问题，停留在正在加载模型的页面。console里的信息如下：（图片和txt） ![console](https://user-images.githubusercontent.com/75460093/202397544-ef271c75-1993-409e-b8f8-832294ecb058.jpg) [1668674262817.log](https://github.com/PaddlePaddle/FastDeploy/files/10029437/1668674262817.log)
> 
> 可以帮忙看看是哪里的问题么？ @chenqianhe

刷新重进或者换个浏览器试试，或者换个独显的电脑？您这边电脑显卡配置可以说一下吗？

**Comment by dium6i** [comment]
> > > paddle.js 只支持固定shape的预测，现在PaddleOCR导出的inferencemodel都是动态shape的（h,w维度为-1）导致 paddle.js converter转模型后，h,w维度为1，解决方案如下：
> 
> > > 重新导出inference model，导出inference model时，修改为固定shape； 以OCR检测为例： 修改 导出的shape ：https://github.com/PaddlePaddle/PaddleOCR/blob/44e60e81cc9a6e801f31080205734ff3069df675/tools/export_model.py#L161 为 infer_shape = [3, 960, 960]
> 
> > > 重新导出inference model ，再使用paddlejsconvert导出js模型。
> 
> > > 导出后确认下model.json里的输入的h,w维度不是1了
> 
> > 
> 
> > 修改后导出模型的model.json里的h, w维度正常了，但是网页端模型加载还是出问题，停留在正在加载模型的页面。console里的信息如下：（图片和txt） ![console](https://user-images.githubusercontent.com/75460093/202397544-ef271c75-1993-409e-b8f8-832294ecb058.jpg) [1668674262817.log](https://github.com/PaddlePaddle/FastDeploy/files/10029437/1668674262817.log)
> 
> > 
> 
> > 可以帮忙看看是哪里的问题么？ @chenqianhe
> 
> 
> 
> 刷新重进或者换个浏览器试试，或者换个独显的电脑？您这边电脑显卡配置可以说一下吗？

我的电脑是AMD的集成显卡。但是使用web demo默认的模型时我的集显电脑也是可以正常识别的。只要是独显的电脑（N卡A卡）都可以么？

**Comment by chenqianhe** [comment]
> > > > paddle.js 只支持固定shape的预测，现在PaddleOCR导出的inferencemodel都是动态shape的（h,w维度为-1）导致 paddle.js converter转模型后，h,w维度为1，解决方案如下：
> > 
> > 
> > > > 重新导出inference model，导出inference model时，修改为固定shape； 以OCR检测为例： 修改 导出的shape ：https://github.com/PaddlePaddle/PaddleOCR/blob/44e60e81cc9a6e801f31080205734ff3069df675/tools/export_model.py#L161 为 infer_shape = [3, 960, 960]
> > 
> > 
> > > > 重新导出inference model ，再使用paddlejsconvert导出js模型。
> > 
> > 
> > > > 导出后确认下model.json里的输入的h,w维度不是1了
> > 
> > 
> > > 
> > 
> > 
> > > 修改后导出模型的model.json里的h, w维度正常了，但是网页端模型加载还是出问题，停留在正在加载模型的页面。console里的信息如下：（图片和txt） ![console](https://user-images.githubusercontent.com/75460093/202397544-ef271c75-1993-409e-b8f8-832294ecb058.jpg) [1668674262817.log](https://github.com/PaddlePaddle/FastDeploy/files/10029437/1668674262817.log)
> > 
> > 
> > > 
> > 
> > 
> > > 可以帮忙看看是哪里的问题么？ @chenqianhe
> > 
> > 
> > 刷新重进或者换个浏览器试试，或者换个独显的电脑？您这边电脑显卡配置可以说一下吗？
> 
> 我的电脑是AMD的集成显卡。但是使用web demo默认的模型时我的集显电脑也是可以正常识别的。只要是独显的电脑（N卡A卡）都可以么？

刷新或换浏览器试试；我这边也在集显电脑出现正常情况，但有时候换个浏览器就正常了。然后独显基本没遇到过。

或者是你如果要适配大多数情况，就得看下Paddle.js库，然后把backend替换成cpu的

**Comment by dium6i** [comment]
> > > > > paddle.js 只支持固定shape的预测，现在PaddleOCR导出的inferencemodel都是动态shape的（h,w维度为-1）导致 paddle.js converter转模型后，h,w维度为1，解决方案如下：
> > > 
> > > 
> > > > > 重新导出inference model，导出inference model时，修改为固定shape； 以OCR检测为例： 修改 导出的shape ：https://github.com/PaddlePaddle/PaddleOCR/blob/44e60e81cc9a6e801f31080205734ff3069df675/tools/export_model.py#L161 为 infer_shape = [3, 960, 960]
> > > 
> > > 
> > > > > 重新导出inference model ，再使用paddlejsconvert导出js模型。
> > > 
> > > 
> > > > > 导出后确认下model.json里的输入的h,w维度不是1了
> > > 
> > > 
> > > > 
> > > 
> > > 
> > > > 修改后导出模型的model.json里的h, w维度正常了，但是网页端模型加载还是出问题，停留在正在加载模型的页面。console里的信息如下：（图片和txt） ![console](https://user-images.githubusercontent.com/75460093/202397544-ef271c75-1993-409e-b8f8-832294ecb058.jpg) [1668674262817.log](https://github.com/PaddlePaddle/FastDeploy/files/10029437/1668674262817.log)
> > > 
> > > 
> > > > 
> > > 
> > > 
> > > > 可以帮忙看看是哪里的问题么？ @chenqianhe
> > > 
> > > 
> > > 刷新重进或者换个浏览器试试，或者换个独显的电脑？您这边电脑显卡配置可以说一下吗？
> > 
> > 
> > 我的电脑是AMD的集成显卡。但是使用web demo默认的模型时我的集显电脑也是可以正常识别的。只要是独显的电脑（N卡A卡）都可以么？
> 
> 刷新或换浏览器试试；我这边也在集显电脑出现正常情况，但有时候换个浏览器就正常了。然后独显基本没遇到过。
> 
> 或者是你如果要适配大多数情况，就得看下Paddle.js库，然后把backend替换成cpu的

好的，我先找电脑多试试看。

**Comment by yinqinggong** [comment]
> > 替换模型的问题已解决。还想再问一下，我下载官方的PPOCR-v3的det和rec推理模型（ https://paddleocr.bj.bcebos.com/PP-OCRv3/chinese/ch_PP-OCRv3_det_infer.tar 和 https://paddleocr.bj.bcebos.com/PP-OCRv3/chinese/ch_PP-OCRv3_rec_infer.tar ）用paddlejsconverter进行转换，得到了如下的结果，似乎是PPOCR-v3的模型不被支持？
> 
> paddle.js 只支持固定shape的预测，现在PaddleOCR导出的inferencemodel都是动态shape的（h,w维度为-1）导致 paddle.js converter转模型后，h,w维度为1，解决方案如下：
> 
> 重新导出inference model，导出inference model时，修改为固定shape； 以OCR检测为例： 修改 导出的shape ：https://github.com/PaddlePaddle/PaddleOCR/blob/44e60e81cc9a6e801f31080205734ff3069df675/tools/export_model.py#L161 为 infer_shape = [3, 960, 960]
> 
> 重新导出inference model ，再使用paddlejsconvert导出js模型。
> 
> 导出后确认下model.json里的输入的h,w维度不是1了

求助。。。我也遇到同样的问题，自己训练的检测模型（PPOCR-v3的det）经上述修改为固定shape后，即infer_shape = [3, 960, 960]，可以正常运行了，但识别模型（PPOCR-v3的rec）也修改为固定shape，即infer_shape = [3, 48, 320]后，推理报错，请问识别模型该如何修改？
