### ISSUE TITLE
FastDeploy与官方的easyedge的demo，同样模型性能有明显差距

### ISSUE THREAD

**Issue by denonzhu** [PaddlePaddle/FastDeploy#601]
同一部手机，FastDeploy的性能非常低，不知道是不是优化没做好

**Comment by denonzhu** [comment]
![WechatIMG4](https://user-images.githubusercontent.com/5187679/201927519-e3c2bf83-2c8c-4688-b354-eb74929339f1.jpeg)
![WechatIMG5](https://user-images.githubusercontent.com/5187679/201927535-fe88e523-7e1f-47ef-978c-56162907a32e.jpeg)
同样模型，fps一个4-20，一个fps 40-60

**Comment by DefTruth** [comment]
加载的模型都分别是什么呢？手机的机型和芯片分别是什么呢？方便提供下edge和在fastdeploy中跑的模型吗？以及计算FPS的方式？

**Comment by denonzhu** [comment]
手机是麒麟9000，华为nova 8pro ,  fastdeploy就是例子中的picodet_s_320_coco_lcnet， edge是[PP-PicoDet-s_320_lcnet](https://ai.baidu.com/easyedge/app/openSource)
<img width="356" alt="image" src="https://user-images.githubusercontent.com/5187679/201932121-2e751486-977a-4824-84ea-f5f002b6e8e6.png">
https://paddledet.bj.bcebos.com/deploy/third_engine/PP-PicoDet.apk

两个模型应该是一样的

**Comment by DefTruth** [comment]
按理说不应该这么慢，nova 7 上app中测试过，一般是 22+fps，包含所有的前后处理和渲染时间在内

**Comment by DefTruth** [comment]
这个apk的源代码有吗？看下具体fps的计算逻辑是咋样的

**Comment by DefTruth** [comment]
<img width="849" alt="a17f3f10afccf0159d5bf85b319f0e8f" src="https://user-images.githubusercontent.com/31974251/201935386-18b4bc49-e8f4-4d95-bdb1-809ce573ba6f.png">

<img width="499" alt="2d2b4ac8c9aeb79a9901458249049dc1" src="https://user-images.githubusercontent.com/31974251/201935470-6c264826-99d9-4318-a4cb-f167a97e6c45.png">

另外，我看到模型文件的大小和我们目前提供的也并不一样，使用的使用的推理引擎也不一样。方便提供一下这个apk的源码地址吗

**Comment by leiqing1** [comment]
印象中，ncnn的picodet demo是使用fp16 + 4线程来运行程序的

**Comment by denonzhu** [comment]
> 
应该是这个地址
https://github.com/JiweiMaster/PP-PicoDet-Android-Demo

**Comment by denonzhu** [comment]
> 按理说不应该这么慢，nova 7 上app中测试过，一般是 22+fps，包含所有的前后处理和渲染时间在内

截图是4fps,实际平均能达到20左右，但是跟[官方PP-PicoDet](https://github.com/JiweiMaster/PP-PicoDet-Android-Demo)那个比较差了一半

**Comment by DefTruth** [comment]
> > 按理说不应该这么慢，nova 7 上app中测试过，一般是 22+fps，包含所有的前后处理和渲染时间在内
> 
> 截图是4fps,实际平均能达到20左右，但是跟[官方PP-PicoDet](https://github.com/JiweiMaster/PP-PicoDet-Android-Demo)那个比较差了一半

感谢您的提问哈，我回复一下这个问题，这里面有几个原因：  
- 1. 计算fps的方式不一样，目前fd提供的demo计算fps逻辑是包含：camera渲染、每帧bitmap的创建和回收、模型前处理、模型推理、模型后处理、推理结果可视化、可视化结果转换到bitmap、bitmap绘制等所有的时间在内。我review了下您发的链接中的代码，应该是只统计了模型前处理、模型推理、模型后处理的时间来计算fps
- 2. App环境中运行，由于camera等占用cpu资源，会导致模型推理可用的计算资源变少，因此app中运行，模型的推理耗时会产生波动。以下是使用fd中picodet_s模型，在shell中测试的性能，包含模型推理和所有前后处理的耗时，测试机为华为nova 7 pro、麒麟985 CPU：  

<img width="414" alt="image" src="https://user-images.githubusercontent.com/31974251/202068609-37de1575-f65d-4ad1-8d73-641c38e01efe.png">  

- 3. 目前app demo是用作给用户展示fd用法的作用，所以暂时没有针对Android camera进行性能优化。camera的优化我们也正在考虑，可能会在后续的版本中添加一些相关的功能。

**Comment by denonzhu** [comment]
> > > 按理说不应该这么慢，nova 7 上app中测试过，一般是 22+fps，包含所有的前后处理和渲染时间在内
> > 
> > 
> > 截图是4fps,实际平均能达到20左右，但是跟[官方PP-PicoDet](https://github.com/JiweiMaster/PP-PicoDet-Android-Demo)那个比较差了一半
> 
> 感谢您的提问哈，我回复一下这个问题，这里面有几个原因：
> 
> * 1. 计算fps的方式不一样，目前fd提供的demo计算fps逻辑是包含：camera渲染、每帧bitmap的创建和回收、模型前处理、模型推理、模型后处理、推理结果可视化、可视化结果转换到bitmap、bitmap绘制等所有的时间在内。我review了下您发的链接中的代码，应该是只统计了模型前处理、模型推理、模型后处理的时间来计算fps
> * 2. App环境中运行，由于camera等占用cpu资源，会导致模型推理可用的计算资源变少，因此app中运行，模型的推理耗时会产生波动。以下是使用fd中picodet_s模型，在shell中测试的性能，包含模型推理和所有前后处理的耗时，测试机为华为nova 7 pro、麒麟985 CPU：
> 
> <img alt="image" width="414" src="https://user-images.githubusercontent.com/31974251/202068609-37de1575-f65d-4ad1-8d73-641c38e01efe.png">
> 
> * 3. 目前app demo是用作给用户展示fd用法的作用，所以暂时没有针对Android camera进行性能优化。camera的优化我们也正在考虑，可能会在后续的版本中添加一些相关的功能。

好的感谢，希望优化一个camera的版本，这样这边就能考虑把现有模型部署改成fd的方式了

**Comment by jiangjiajun** [comment]
此ISSUE由于一年未更新，将会关闭处理，如有需要，可再次更新打开。
