### ISSUE TITLE
咨询：PP-yoloe-r 这个模型能用fastdeploy部署在安卓上吗

### ISSUE THREAD

**Issue by denonzhu** [PaddlePaddle/FastDeploy#602]
PP-YOLOE-R是一个高效的单阶段Anchor-free旋转框检测模型https://github.com/PaddlePaddle/PaddleDetection/blob/develop/configs/rotate/ppyoloe_r/README.md

**Comment by jiangjiajun** [comment]
旋转框，目前没支持

**Comment by denonzhu** [comment]
好的，感谢
