### ISSUE TITLE
Python API可视化增加标签展示

### ISSUE THREAD

**Issue by JackonLiu** [PaddlePaddle/FastDeploy#643]
platform：windows10
python3.8
onnx==1.12.0
安装方式
pip install fastdeploy-python -f https://www.paddlepaddle.org.cn/whl/fastdeploy.html
yolov5-5.0
导出方式
`python export.py --weights runs/train/exp33/weights/best.pt --include onnx`

       result = model.predict(im.copy())
        print(result)
        print(frame_index)
        t3 = time.time()
        print('detect frames: %.4f frames/s' % (1 / (t3 - t2)))
        # 预测结果可视化
        label_ids = result.label_ids
        if label_ids:
            for i in range(len(label_ids)):
                if label_ids[i] == 0:
                    label_ids[i] = 'hat'
                else:
                    label_ids[i] = 'person'
        result.label_ids = label_ids
        if result.boxes:
            vis_im = fd.vision.vis_detection(im, result,score_threshold=0.7)

[FastDeploy][INFO]:  Successfully found CUDA ToolKit from system PATH env -> C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.1\bin
[INFO] fastdeploy/runtime.cc(528)::fastdeploy::Runtime::Init	Runtime initialized with Backend::OPENVINO in Device::CPU.
(1440, 2560, 3)
DetectionResult: [xmin, ymin, xmax, ymax, score, label_id]
219.655457,190.753174, 591.998047, 611.119873, 0.911301, 0

0
detect frames: 2.4705 frames/s
Traceback (most recent call last):
  File "C:\Program Files\JetBrains\PyCharm 2020.1\plugins\python\helpers\pydev\pydevd.py", line 1438, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "C:\Program Files\JetBrains\PyCharm 2020.1\plugins\python\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "C:/Users/Administrator/projects/FastDeploy-develop/examples/vision/detection/yolov5/python/infer_video.py", line 68, in <module>
    result.label_ids = label_ids
TypeError: (): incompatible function arguments. The following argument types are supported:
    1. (self: fastdeploy.libs.fastdeploy_main.vision.DetectionResult, arg0: List[int]) -> None

Invoked with: DetectionResult: [xmin, ymin, xmax, ymax, score, label_id]
219.655457,190.753174, 591.998047, 611.119873, 0.911301, 0
, ['hat']

我知道错误的原因是不能直接换成字符串，但是希望之后能增加字符串的方式，不然很多场景检测出来的图片不能用！！！

**Comment by jiangjiajun** [comment]
你好，我们已经在C++接口增加传入label_list来支持可视化展示标签的功能，Python API会在这周0.8版本增加进去

**Comment by JackonLiu** [comment]
> 你好，我们已经在C++接口增加传入label_list来支持可视化展示标签的功能，Python API会在这周0.8版本增加进去

是将数字转换为字符串对吧？

**Comment by jiangjiajun** [comment]
用法类似
```
label_list = list()
with open("label_list.txt", "r") as f:
     for line in f:
          label_list.append(line.strip())

vis_im = fd.vision.vis_detection(im, result,score_threshold=0.7, label_list=label_list)
```

可视化后即会对应Label_id将数字转化对应的字符串

**Comment by JackonLiu** [comment]
了解了，多谢解答，期待更新

**Comment by JackonLiu** [comment]
> 用法类似
> 
> ```
> label_list = list()
> with open("label_list.txt", "r") as f:
>      for line in f:
>           label_list.append(line.strip())
> 
> vis_im = fd.vision.vis_detection(im, result,score_threshold=0.7, label_list=label_list)
> ```
> 
> 可视化后即会对应Label_id将数字转化对应的字符串

我已更新至0.8，但是还是不行

**Comment by jiangjiajun** [comment]
> > 用法类似
> > 
> > ```
> > label_list = list()
> > with open("label_list.txt", "r") as f:
> >      for line in f:
> >           label_list.append(line.strip())
> > 
> > vis_im = fd.vision.vis_detection(im, result,score_threshold=0.7, label_list=label_list)
> > ```
> > 
> > 可视化后即会对应Label_id将数字转化对应的字符串
> 
> 我已更新至0.8，但是还是不行



。。。研发压力太大，会在周末的版本release出来

**Comment by JackonLiu** [comment]
> 

哈哈哈哈，没关系，不急， 期待，辛苦了

**Comment by jiangjiajun** [comment]
@JackonLiu 已经添加了支持，可以参考此文档安装nightly build版本使用 https://github.com/PaddlePaddle/FastDeploy/blob/develop/docs/en/build_and_install/download_prebuilt_libraries.md
