### ISSUE TITLE
Jetson部署OCR

### ISSUE THREAD

**Issue by ccLemonTree** [PaddlePaddle/FastDeploy#65]
请问有在Jetson上部署OCR的Demo嘛

**Comment by leiqing1** [comment]
OCRv1～V3的Jetson部署demo都有，需要Jetpack4.6. 可以参考这个文档体验：https://github.com/PaddlePaddle/FastDeploy/blob/release/0.1.0/docs/Jetson-Linux-CPP-SDK-Inference.md
近期会发布v0.3，产品体验会升级。

**Comment by ccLemonTree** [comment]
好的 感谢

**Comment by AI-Mart** [comment]
> OCRv1～V3的Jetson部署demo都有，需要Jetpack4.6. 可以参考这个文档体验：https://github.com/PaddlePaddle/FastDeploy/blob/release/0.1.0/docs/Jetson-Linux-CPP-SDK-Inference.md 近期会发布v0.3，产品体验会升级。

大概什么时候发布v0.3呢？

**Comment by jiangjiajun** [comment]
> > OCRv1～V3的Jetson部署demo都有，需要Jetpack4.6. 可以参考这个文档体验：https://github.com/PaddlePaddle/FastDeploy/blob/release/0.1.0/docs/Jetson-Linux-CPP-SDK-Inference.md 近期会发布v0.3，产品体验会升级。
> 
> 大概什么时候发布v0.3呢？

请问下你在Jetson上部署是指用TensorRT部署吗？

**Comment by jiangjiajun** [comment]
此ISSUE由于一年未更新，将会关闭处理，如有需要，可再次更新打开。
