### ISSUE TITLE
[模型支持] 期望能够支持paddleOCR 中的版面分析模型

### ISSUE THREAD

**Issue by wmpscc** [PaddlePaddle/FastDeploy#650]
Hardware: x86 CPU 
OS: Linux
Model name: picodet_lcnet_x1_0_fgd_layout
Model link: [picodet_lcnet_x1_0_fgd_layout](https://github.com/PaddlePaddle/PaddleOCR/blob/dygraph/ppstructure/docs/models_list.md)
Detailed Description: Example: 还没发现本框架有支持版面分析模型，有这方面需求。能否以picodet_lcnet_x1_0_fgd_layout模型为例，提供一个版面分析模型deploy.

**Comment by jiangjiajun** [comment]
Hi，你认为目前现有PaddleOCR里的版本分析模型的部署方案有哪些点觉得需要提升吗

**Comment by wmpscc** [comment]
> Hi，你认为目前现有PaddleOCR里的版本分析模型的部署方案有哪些点觉得需要提升吗

原部署方案依赖的框架较大，需要更多的运行内存。期望一个更精简的方案。

**Comment by jiangjiajun** [comment]
此ISSUE由于一年未更新，将会关闭处理，如有需要，可再次更新打开。
