### ISSUE TITLE
picodet 训练的模型安卓报错，用的是configs/picodet/picodet_s_416_coco_lcnet.yml

### ISSUE THREAD

**Issue by denonzhu** [PaddlePaddle/FastDeploy#662]
<img width="1319" alt="image" src="https://user-images.githubusercontent.com/5187679/203303091-7f212853-84dd-46bd-a7a9-851ca56c0281.png">

**Comment by denonzhu** [comment]
<img width="869" alt="image" src="https://user-images.githubusercontent.com/5187679/203303353-7332f02d-9e1a-40ba-acd6-e71b7997d21d.png">
模型eval正常，使用默认命令导出，但是导出的模型再安卓直接报错，闪退

**Comment by denonzhu** [comment]
模型文件
[Uploading 归档.zip…]()

**Comment by DefTruth** [comment]
@denonzhu 请问是用哪里的android代码来跑的这个模型呢？

**Comment by denonzhu** [comment]
> @denonzhu 请问是用哪里的android代码来跑的这个模型呢？

就是当前最新开发分支的代码

**Comment by denonzhu** [comment]
你把我上面导出的模型，替换原代码里面的文件，运行就立马闪退，断点代码，发现是在做预测的时候崩溃了

**Comment by DefTruth** [comment]
是哪个目录下的？因为刚刚更新了代码

**Comment by denonzhu** [comment]
华为nova8 pro运行报错日志：
<img width="1424" alt="image" src="https://user-images.githubusercontent.com/5187679/203310332-5970dc35-37d9-46b4-a988-8671318046ae.png">

**Comment by DefTruth** [comment]
我们排查一下哈，可以提一下您替换的代码部分吗？

**Comment by denonzhu** [comment]
小米9 运行日志：
<img width="1320" alt="image" src="https://user-images.githubusercontent.com/5187679/203310612-ff25d59c-2932-43fc-a3ed-540037893de7.png">

**Comment by denonzhu** [comment]
修改代码如下：

<img width="1014" alt="image" src="https://user-images.githubusercontent.com/5187679/203310765-35949f0c-101c-4dc3-a857-93669b08cb38.png">
<img width="971" alt="image" src="https://user-images.githubusercontent.com/5187679/203310830-ce576b37-faf5-497b-936a-42c40c11759b.png">
<img width="971" alt="image" src="https://user-images.githubusercontent.com/5187679/203310883-d703cd37-9302-46c6-9fe3-c914b081b9c1.png">

**Comment by denonzhu** [comment]
> 模型文件 Uploading 归档.zip…

这个模型就是用picodet官方默认配置文件训练的,导出代码未添加任何参数
`python tools/export_model.py -c  configs/picodet/picodet_s_416_coco_lcnet.yml --output_dir=./inference \
  -o weights=./output/picodet_s_416_coco_lcnet/best_model.pdparams`

**Comment by denonzhu** [comment]
> 是哪个目录下的？因为刚刚更新了代码

跟刚刚更新的代码无关，官方的模型是可以正常运行，自己训练的不行。我刚刚更新最新代码，还是一样的报错，替换回官方的模型就正常

**Comment by DefTruth** [comment]
好的，我们排查一下

**Comment by DefTruth** [comment]
> 模型文件 Uploading 归档.zip…

这个模型文件地址是空的

**Comment by denonzhu** [comment]
> > 模型文件 Uploading 归档.zip…
> 
> 这个模型文件地址是空的

我上传到网盘试试，网盘地址： 链接: https://pan.baidu.com/s/1iltkLk9NdNe22mO5yx_53g?pwd=vnpk 提取码: vnpk

**Comment by denonzhu** [comment]
[picodet_416_waybill.zip](https://github.com/PaddlePaddle/FastDeploy/files/10072198/picodet_416_waybill.zip)

**Comment by denonzhu** [comment]
> [picodet_416_waybill.zip](https://github.com/PaddlePaddle/FastDeploy/files/10072198/picodet_416_waybill.zip)

我重新上传了一下

**Comment by DefTruth** [comment]
好的哈~ 我们的同学近期会来跟进这个问题哈

**Comment by DefTruth** [comment]
@denonzhu 已经复现出相同的情况，我们正在排查具体的问题哈

**Comment by DefTruth** [comment]
另外，能否提供一张可正常输出检测结果的测试图片呢？

**Comment by DefTruth** [comment]
@denonzhu 已经在PR中修复了这个问题，可以删除原有的缓存和libs目录下的库，在android studio中重新编译一下试试

**Comment by denonzhu** [comment]
好的，我测试一下

**Comment by DefTruth** [comment]
labelFile指向的路径可以替换成你的2个label标签，新建一个txt文件，每行是一个label

**Comment by denonzhu** [comment]
<img width="1361" alt="image" src="https://user-images.githubusercontent.com/5187679/203791660-c26c4a6f-de9e-4b43-ac85-5bef652b180c.png">
ha还是闪退

**Comment by denonzhu** [comment]
代码已经更新到最新版本

**Comment by denonzhu** [comment]
可以了，应该是缓存问题，下载最新的fd.aar可以运行了

**Comment by DefTruth** [comment]
先把原来的aar删掉再试下

**Comment by DefTruth** [comment]
> 可以了，应该是缓存问题，下载最新的fd.aar可以运行了

nice ~

**Comment by denonzhu** [comment]
性能非常不错，点赞，fps能达到2
![141669295595_ pic](https://user-images.githubusercontent.com/5187679/203792937-4d56d208-acaf-4601-aea9-b55ef48bb7cf.jpg)

**Comment by DefTruth** [comment]
如有有遇到新的问题，也欢迎给我们提issue哈

**Comment by denonzhu** [comment]
> 另外，能否提供一张可正常输出检测结果的测试图片呢？

就是随便搞个快递面单就可以识别了，这个只检测快递单

**Comment by denonzhu** [comment]
> 如有有遇到新的问题，也欢迎给我们提issue哈

好的，下一个开始测试ocr
