### ISSUE TITLE
fd安卓部署为啥不能支持paddlite 导出的nb模型，这样性能会不会更好点

### ISSUE THREAD

**Issue by denonzhu** [PaddlePaddle/FastDeploy#664]

**Comment by jiangjiajun** [comment]
性能是一样的。 后面PaddleLite也会更推荐大家直接使用Paddle格式

**Comment by denonzhu** [comment]
但是我看通过 paddle lite工具导出的模型会更小一点，是不是导出成nb格式的时候还做了裁剪

**Comment by jiangjiajun** [comment]
> 但是我看通过 paddle lite工具导出的模型会更小一点，是不是导出成nb格式的时候还做了裁剪

基本一样，如果是量化的格式，会减少转换后的体积

**Comment by denonzhu** [comment]
明白了
