### ISSUE TITLE
windows/Ubuntu C++ SDK 标签ID不一致的问题

### ISSUE THREAD

**Issue by JackonLiu** [PaddlePaddle/FastDeploy#669]
platform：windows10
python3.8
onnx==1.12.0
安装方式
pip install fastdeploy-python -f https://www.paddlepaddle.org.cn/whl/fastdeploy.html
yolov5-5.0
导出方式
python export.py --weights runs/train/exp33/weights/best.pt --include onnx

windows C++ SDK 编译方式是参考这个文档：use_sdk_on_windows.md
`
E:\program\fastdeploy-win-x64-gpu-0.2.1\examples\vision\detection\yolov7\cpp\build\Release>infer.exe models/cable.onnx photo/2.png 0  # CPU
[INFO] fastdeploy/fastdeploy_runtime.cc(283)::fastdeploy::Runtime::Init Runtime initialized with Backend::OPENVINO in device Device::CPU.
DetectionResult: [xmin, ymin, xmax, ymax, score, label_id]
0.000000,0.000000, 0.000000, 0.000000, 1.548668, 44

Visualized result saved in ./vis_result.jpg
`

我的onnx标签是从0-4的，但是这里居然 出现了44，请问这是什么原因？

**Comment by wjj19950828** [comment]
@JackonLiu 麻烦提供一下ONNX模型吧，另外可以看下可视化结果是否正确

**Comment by JackonLiu** [comment]
> @JackonLiu 麻烦提供一下ONNX模型吧，另外可以看下可视化结果是否正确

抱歉，这属于公司机密，无法提供，可视化结果没出来，什么也没检测到

**Comment by wjj19950828** [comment]
@JackonLiu 原生ONNX结果正确吗，可以提供一个效果不是那么好的ONNX，主要看下前后处理能否对齐

**Comment by JackonLiu** [comment]
> 

原生的onnx是正常的，我感觉问题出在编译的exe文件上，好像默认用的是coco的数据集打包的，还有个问题就是用编译出来的exe做推理检测效果变差了，有些我能用pt文件检测出来的，但是用exe+onnx却检测不出来了，你们可以检查下

**Comment by JackonLiu** [comment]
> 

我找到问题了，yolov7导出的模型就有这个问题，yolov5的就很正常
