### ISSUE TITLE
FastDeploy部署PaddleDetection模型

### ISSUE THREAD

**Issue by Abris-087** [PaddlePaddle/FastDeploy#670]
您好，请问如何利用FastDeploy部署PaddleDetection训练出的yolov5模型？  我想把.pdmodel和.pdiparams转化成onnx格式，但是调用paddle2onnx出现了如下报错。
![1669169408897](https://user-images.githubusercontent.com/61613537/203456960-ca3df049-74d0-4cab-a0d6-8ad2b052e78d.jpg)

**Comment by jiangjiajun** [comment]
PaddleDetection的YOLOv5目前还没支持，正在支持中哈

**Comment by Abris-087** [comment]
> PaddleDetection的YOLOv5目前还没支持，正在支持中哈

您好，我看到PaddleYOLO/configs/yolov5/README中写道：可以将paddle模型转化成onnx模型！
![image](https://user-images.githubusercontent.com/61613537/204080889-6753fb74-c695-4d6a-9a31-0dd1e1aac749.png)
我试了一下也成功了，但是转化来的onnx模型放到JetsonNano中调用却失败了，是因为FastDeploy不支持吗？
![image](https://user-images.githubusercontent.com/61613537/204080868-63001e02-084d-415f-93fb-850a4f276cd3.png)

**Comment by jiangjiajun** [comment]
不能这样使用。ppdet训练的yolov5除了格式与原torch的yolov5不同之外，输入要求的数量，预处理等都不同，不能直接复用

**Comment by jiangjiajun** [comment]
此ISSUE由于一年未更新，将会关闭处理，如有需要，可再次更新打开。
