### ISSUE TITLE
ERROR: No matching distribution found for fastdeploy-gpu-python

### ISSUE THREAD

**Issue by athmoon** [PaddlePaddle/FastDeploy#672]
pip install fastdeploy-gpu-python -f https://www.paddlepaddle.org.cn/whl/fastdeploy.html
Looking in links: https://www.paddlepaddle.org.cn/whl/fastdeploy.html
ERROR: Could not find a version that satisfies the requirement fastdeploy-gpu-python (from versions: none)
ERROR: No matching distribution found for fastdeploy-gpu-python

**Comment by athmoon** [comment]
PS C:\Users\moonpc> python -V
Python 3.11.0
PS C:\Users\moonpc> pip --version
pip 22.3.1 from D:\prog\install\Python\Python311\Lib\site-packages\pip (python 3.11)

**Comment by jiangjiajun** [comment]
Currently, only python3.6 ~ 3.10 are supported

**Comment by athmoon** [comment]
> Currently, only python3.6 ~ 3.10 are supported

yes,I just tried 3.10, Thanks!

**Comment by athmoon** [comment]
becauseof conda, It's better to use python 3.9.
https://repo.anaconda.com/miniconda/Miniconda3-py39_4.12.0-Windows-x86_64.exe
https://www.python.org/ftp/python/3.9.13/python-3.9.13-amd64.exe
