### ISSUE TITLE
./infer_demo: error while loading shared libraries: libpaddle2onnx.so.1.0.1: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by JackonLiu** [PaddlePaddle/FastDeploy#673]
platform：wsl2 Ubuntu20.0.4
python3.9
onnx==1.12.0
安装方式
pip install fastdeploy-python -f https://www.paddlepaddle.org.cn/whl/fastdeploy.html

步骤参考文档：FastDeploy-develop\examples\vision\detection\yolov7\cpp\README.md

步骤一切顺利，但是推理时报错
`(base) root@computer:/mnt/c/Users/Administrator/projects/FastDeploy-develop/fastdeploy-linux-x64-0.6.0/examples/vision/detection/yolov7/cpp/build# ./infer_demo yolov7.onnx 000000014439.jpg 2
./infer_demo: error while loading shared libraries: libpaddle2onnx.so.1.0.1: cannot open shared object file: No such file or directory
`

**Comment by jiangjiajun** [comment]
Hi, @JackonLiu 麻烦手动将这个文件 https://github.com/PaddlePaddle/FastDeploy/blob/develop/scripts/fastdeploy_init.sh 拷贝到你的目录`/mnt/c/Users/Administrator/projects/FastDeploy-develop/fastdeploy-linux-x64-0.6.0/`下，然后执行 `source /mnt/c/Users/Administrator/projects/FastDeploy-develop/fastdeploy-linux-x64-0.6.0/fastdeploy_init.sh`

这样会将库添加到你的环境变量，让可执行二进制程序找到相应的.so

**Comment by jiangjiajun** [comment]
另外我们最新版本已经更新到0.8.0，可下载最新版本使用

**Comment by JackonLiu** [comment]
> 

 error while loading shared libraries: libopencv_video.so.3.4: cannot open shared object file: No such file or directory
按照您的方法去试了下，又出现了上面这个问题

**Comment by jiangjiajun** [comment]
建议先删除本地0.6.0的版本，然后下载0.8.0的版本。 我们在0.8.0版本里面内置了fastdeploy_init.sh（此前版本init.sh存在问题）

**Comment by JackonLiu** [comment]
> 建议先删除本地0.6.0的版本，然后下载0.8.0的版本。 我们在0.8.0版本里面内置了fastdeploy_init.sh（此前版本init.sh存在问题）

(base) root@computer:/mnt/c/Users/Administrator/projects/FastDeploy-develop/FastDeploy-release-0.8.0/examples/vision/detection/yolov7/cpp/build# wget https://bj.bcebos.com/fastdeploy/release/cpp/fastdeploy-linux-x64-0.8.0.tgz
--2022-11-23 16:43:05--  https://bj.bcebos.com/fastdeploy/release/cpp/fastdeploy-linux-x64-0.8.0.tgz
Resolving bj.bcebos.com (bj.bcebos.com)... 220.181.33.43, 220.181.33.44, 110.242.68.39, ...
Connecting to bj.bcebos.com (bj.bcebos.com)|220.181.33.43|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2022-11-23 16:43:06 ERROR 404: Not Found.

这个命令目前是404

**Comment by JackonLiu** [comment]
> 建议先删除本地0.6.0的版本，然后下载0.8.0的版本。 我们在0.8.0版本里面内置了fastdeploy_init.sh（此前版本init.sh存在问题）

我用0.7.0版本的也有问题，把FastDeploy-release-0.8.0里的fastdeploy_init.sh复制过来还是有问题

**Comment by jiangjiajun** [comment]
贴一下执行source后的日志提示，同时检查一下日志中列的路径下，是否存在文件

**Comment by JackonLiu** [comment]
> 贴一下执行source后的日志提示，同时检查一下日志中列的路径下，是否存在文件

(base) root@computer:/mnt/c/Users/Administrator/projects/FastDeploy-develop/FastDeploy-release-0.8.0/examples/vision/detection/yolov7/cpp/build/fastdeploy-linux-x64-0.7.0# source fastdeploy_init.sh
Import environment variable from FastDeploy...
FastDeploy Lib: /mnt/c/Users/Administrator/projects/FastDeploy-develop/FastDeploy-release-0.8.0/examples/vision/detection/yolov7/cpp/build/fastdeploy-linux-x64-0.7.0/lib
Paddle2ONNX Lib: /mnt/c/Users/Administrator/projects/FastDeploy-develop/FastDeploy-release-0.8.0/examples/vision/detection/yolov7/cpp/build/fastdeploy-linux-x64-0.7.0/third_libs/install/paddle2onnx/lib
ONNX Runtime Lib: /mnt/c/Users/Administrator/projects/FastDeploy-develop/FastDeploy-release-0.8.0/examples/vision/detection/yolov7/cpp/build/fastdeploy-linux-x64-0.7.0/third_libs/install/onnxruntime/lib
OpenCV Lib: /mnt/c/Users/Administrator/projects/FastDeploy-develop/FastDeploy-release-0.8.0/examples/vision/detection/yolov7/cpp/build/fastdeploy-linux-x64-0.7.0/third_libs/install/opencv/lib
OpenVINO Lib: /mnt/c/Users/Administrator/projects/FastDeploy-develop/FastDeploy-release-0.8.0/examples/vision/detection/yolov7/cpp/build/fastdeploy-linux-x64-0.7.0/third_libs/install/openvino/runtime/lib
Paddle Inference Lib: /mnt/c/Users/Administrator/projects/FastDeploy-develop/FastDeploy-release-0.8.0/examples/vision/detection/yolov7/cpp/build/fastdeploy-linux-x64-0.7.0/third_libs/install/paddle_inference/paddle/lib
MKLDNN Lib: /mnt/c/Users/Administrator/projects/FastDeploy-develop/FastDeploy-release-0.8.0/examples/vision/detection/yolov7/cpp/build/fastdeploy-linux-x64-0.7.0/third_libs/install/paddle_inference/third_party/install/mkldnn/lib
MKLML Lib: /mnt/c/Users/Administrator/projects/FastDeploy-develop/FastDeploy-release-0.8.0/examples/vision/detection/yolov7/cpp/build/fastdeploy-linux-x64-0.7.0/third_libs/install/paddle_inference/third_party/install/mklml/lib


这些文件下都是存在文件的，但是有一个命令没执行成功

if [ -d ${INSTALLED_PREBUILT_FASTDEPLOY_DIR}/third_libs/install/fast_tokenizer ]; then
	export LD_LIBRARY_PATH=${INSTALLED_PREBUILT_FASTDEPLOY_DIR}/third_libs/install/fast_tokenizer/lib:${LD_LIBRARY_PATH}
	echo "FastTokenizer Lib: ${INSTALLED_PREBUILT_FASTDEPLOY_DIR}/third_libs/install/fast_tokenizer/lib"
fi

**Comment by JackonLiu** [comment]
error while loading shared libraries: libcore_tokenizers.so: cannot open shared object file: No such file or directory
现在的报错又成了这个

**Comment by jiangjiajun** [comment]
wget https://bj.bcebos.com/fastdeploy/release/cpp/fastdeploy-linux-x64-0.8.0.tgz  0.8版本已经上传

**Comment by jiangjiajun** [comment]
https://bj.bcebos.com/fastdeploy/release/cpp/fastdeploy-linux-x64-0.8.0.tgz 0.8版本已经上传，使用这个版本吧

**Comment by JackonLiu** [comment]
> wget https://bj.bcebos.com/fastdeploy/release/cpp/fastdeploy-linux-x64-0.8.0.tgz

还是有问题
 cd fastdeploy-linux-x64-0.8.0
(base) root@computer:/mnt/c/Users/Administrator/projects/FastDeploy-develop/FastDeploy-release-0.8.0/examples/vision/detection/yolov7/cpp/build/fastdeploy-linux-x64-0.8.0# source fastdeploy_init.sh
Import environment variable from FastDeploy...
FastDeploy Lib: /mnt/c/Users/Administrator/projects/FastDeploy-develop/FastDeploy-release-0.8.0/examples/vision/detection/yolov7/cpp/build/fastdeploy-linux-x64-0.8.0/lib
FastTokenizer Lib: /mnt/c/Users/Administrator/projects/FastDeploy-develop/FastDeploy-release-0.8.0/examples/vision/detection/yolov7/cpp/build/fastdeploy-linux-x64-0.8.0/third_libs/install/fast_tokenizer/lib
Paddle2ONNX Lib: /mnt/c/Users/Administrator/projects/FastDeploy-develop/FastDeploy-release-0.8.0/examples/vision/detection/yolov7/cpp/build/fastdeploy-linux-x64-0.8.0/third_libs/install/paddle2onnx/lib
ONNX Runtime Lib: /mnt/c/Users/Administrator/projects/FastDeploy-develop/FastDeploy-release-0.8.0/examples/vision/detection/yolov7/cpp/build/fastdeploy-linux-x64-0.8.0/third_libs/install/onnxruntime/lib
OpenCV Lib: /mnt/c/Users/Administrator/projects/FastDeploy-develop/FastDeploy-release-0.8.0/examples/vision/detection/yolov7/cpp/build/fastdeploy-linux-x64-0.8.0/third_libs/install/opencv/lib64
OpenVINO Lib: /mnt/c/Users/Administrator/projects/FastDeploy-develop/FastDeploy-release-0.8.0/examples/vision/detection/yolov7/cpp/build/fastdeploy-linux-x64-0.8.0/third_libs/install/openvino/runtime/lib
Paddle Inference Lib: /mnt/c/Users/Administrator/projects/FastDeploy-develop/FastDeploy-release-0.8.0/examples/vision/detection/yolov7/cpp/build/fastdeploy-linux-x64-0.8.0/third_libs/install/paddle_inference/paddle/lib
MKLDNN Lib: /mnt/c/Users/Administrator/projects/FastDeploy-develop/FastDeploy-release-0.8.0/examples/vision/detection/yolov7/cpp/build/fastdeploy-linux-x64-0.8.0/third_libs/install/paddle_inference/third_party/install/mkldnn/lib
MKLML Lib: /mnt/c/Users/Administrator/projects/FastDeploy-develop/FastDeploy-release-0.8.0/examples/vision/detection/yolov7/cpp/build/fastdeploy-linux-x64-0.8.0/third_libs/install/paddle_inference/third_party/install/mklml/lib
(base) root@computer:/mnt/c/Users/Administrator/projects/FastDeploy-develop/FastDeploy-release-0.8.0/examples/vision/detection/yolov7/cpp/build/fastdeploy-linux-x64-0.8.0# cd ..
(base) root@computer:/mnt/c/Users/Administrator/projects/FastDeploy-develop/FastDeploy-release-0.8.0/examples/vision/detection/yolov7/cpp/build# ./infer_demo yolov7.onnx 000000014439.jpg 0
./infer_demo: error while loading shared libraries: libopencv_video.so.3.4: cannot open shared object file: No such file or directory

**Comment by jiangjiajun** [comment]
/mnt/c/Users/Administrator/projects/FastDeploy-develop/FastDeploy-release-0.8.0/examples/vision/detection/yolov7/cpp/build/fastdeploy-linux-x64-0.8.0/third_libs/install/opencv/lib64 这个路径下有.so吗

**Comment by JackonLiu** [comment]
> /mnt/c/Users/Administrator/projects/FastDeploy-develop/FastDeploy-release-0.8.0/examples/vision/detection/yolov7/cpp/build/fastdeploy-linux-x64-0.8.0/third_libs/install/opencv/lib64 这个路径下有.so吗

有

**Comment by jiangjiajun** [comment]
fastdeploy_init.sh本质上就是通过export LD_LIBRARY_PATH将库路径加入到环境变量。如果你确认这个目录下有libopencv_video.so但是执行二进制时找不到，可以手动将路径加入到环境变量试下

**Comment by JackonLiu** [comment]
> 

不知道为何，环境变量已经配好了，就是不生效，算了，我放弃了，感谢您的解答

**Comment by JackonLiu** [comment]
这个版本的：fastdeploy-linux-x64-1.0.0 测试成功
依次执行以下命令即可
source fastdeploy-linux-x64-1.0.0/fastdeploy_init.sh
cmake .. -DFASTDEPLOY_INSTALL_DIR=${PWD}/fastdeploy-linux-x64-1.0.0
make -j

**Comment by jiangjiajun** [comment]
最新版本已经升级到1.0.2，欢迎下载使用
