### ISSUE TITLE
运行错误

### ISSUE THREAD

**Issue by huyuejingling** [PaddlePaddle/FastDeploy#684]
linux(ubuntu 18.04)编译成功后，运行测试 报错 Illegal instruction (core dumped),是因为cpu 指令不支持吗？

**Comment by jiangjiajun** [comment]
拉预编译的包，可以正常使用吗？

**Comment by huyuejingling** [comment]
同样的错误，我才自己编译的，结果还是一样

**Comment by jiangjiajun** [comment]
是在哪一行报错的，有截图吗

**Comment by huyuejingling** [comment]
![image](https://user-images.githubusercontent.com/7887096/203671269-f0c9cc07-0d77-447b-9cb2-70241756af97.png)
引入的时候就会报错

**Comment by jiangjiajun** [comment]
此ISSUE由于一年未更新，将会关闭处理，如有需要，可再次更新打开。
