### ISSUE TITLE
Runtime运行结果和onnxruntime、pytorch不一致

### ISSUE THREAD

**Issue by yz2yz** [PaddlePaddle/FastDeploy#685]
通过pytorch训练导出的onnx模型，pytorch和onnxruntimer推理结果一致；但是和fastdeploy的输出结果不一致。
为了验证，使用了infer_onnx_onnxruntime.py改造下，固定输入（原有示例是随机输入），发现和onnxruntime的也不一致。
import fastdeploy as fd
from fastdeploy import ModelFormat
import numpy as np
import cv2

model_url = "https://bj.bcebos.com/fastdeploy/models/mobilenetv2.onnx"
fd.download(model_url, path="./temp")

def prev_proc(img:np.ndarray):

    # img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
    img = img.astype(np.float32)   # 不做颜色转换
    img = cv2.resize(img, (224, 224))
    img /= 255.0
    img = np.transpose(img, (2,0,1))
    img = np.expand_dims(img, axis=0)
    # img = torch.from_numpy(img).to(device, non_blocking=True)

    return img

option = fd.RuntimeOption()
option.set_model_path("./temp/mobilenetv2.onnx", model_format=ModelFormat.ONNX)

option.use_ort_backend()
option.use_gpu()

runtime = fd.Runtime(option)

input_name = runtime.get_input_info(0).name
output_name = runtime.get_output_info(0).name
print(' input_name:', input_name, runtime.get_input_info(0).shape, runtime.get_input_info(0).dtype)
print('output_name:', output_name)

fname = 'imgs/__roi.jpg'
img = cv2.imdecode(np.fromfile(fname, dtype=np.uint8), cv2.IMREAD_COLOR)
img = prev_proc(img)

results = runtime.infer({
    input_name: img
})

print(results[0][0][:10])

# 以上是 官方的runtime推理版本，下面是onnxruntime推理版本：

import onnxruntime as ort
import numpy as np
import cv2

def prev_proc(img:np.ndarray):

    # img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
    img = img.astype(np.float32)   # 不做颜色转换
    img = cv2.resize(img, (224, 224))
    img /= 255.0
    img = np.transpose(img, (2,0,1))
    img = np.expand_dims(img, axis=0)

    return img

fname = 'imgs/__roi.jpg'
img = cv2.imdecode(np.fromfile(fname, dtype=np.uint8), cv2.IMREAD_COLOR)
img = prev_proc(img)

onnx_file = "./temp/mobilenetv2.onnx"
ort_sess = ort.InferenceSession(onnx_file, providers=ort.get_available_providers())
ort_inputs = {ort_sess.get_inputs()[0].name: img}
results = ort_sess.run(None, ort_inputs)

print(results[0][0][:10])

**Comment by jiangjiajun** [comment]
上传一下模型和测试图片，我们复现下看看

**Comment by yz2yz** [comment]
![__roi](https://user-images.githubusercontent.com/37030617/203676996-47c3a0fb-35a0-413d-8217-a8a40d951799.jpg)
测试图片已上传；
以上脚本中用的模型是 官方示例里的 https://bj.bcebos.com/fastdeploy/models/mobilenetv2.onnx
自己的模型超过25M，无法上传。

**Comment by jiangjiajun** [comment]
@yz2yz Hi， 感谢你的反馈，我复现了你的问题。这个问题原因分析如下

1. numpy在做处理过程中，最终得到的img已经不是一个内存连续的数据
2. FD的python接口，在接收到传入来的numpy时，没有拷贝numpy的内存，而是直接拿到内存开始的指针
3. 由于内存不连续，底层推理出错

当前的处理方式，你在执行`runtime.infer({"inputs": img})` 这一行时，可以改成
```
img = np.ascontiguousarray(img)
runtime.infer({"inputs": img})
```

为了在FD解决这个问题，我同步提了另外一个PR来处理非连续内存输入的问题 https://github.com/PaddlePaddle/FastDeploy/pull/689

**Comment by yz2yz** [comment]
太感谢了
