### ISSUE TITLE
希望c#也能用fastdeploy部署

### ISSUE THREAD

**Issue by ZXH109030** [PaddlePaddle/FastDeploy#686]
c#广泛用于工业应用场景，尤其是制造业。反而，C++的应用在这一块是很少的，请求有C#调用的方法

**Comment by albyho** [comment]
P/Invoke 或 C++/CLI 不就行了?

**Comment by jiangjiajun** [comment]
此ISSUE由于一年未更新，将会关闭处理，如有需要，可再次更新打开。
