### ISSUE TITLE
是否支持windows32位编译？

### ISSUE THREAD

**Issue by wzy123456wzy** [PaddlePaddle/FastDeploy#690]
是否支持windows32位编译？

**Comment by DefTruth** [comment]
请问您主要想部署的场景是什么呢？是必须要32位吗？以及想要用的推理后端是啥？

**Comment by wzy123456wzy** [comment]
> 请问您主要想部署的场景是什么呢？是必须要32位吗？以及想要用的推理后端是啥？

em 系统是windows 10 64位，但是有32位进程需要调用接口，不用服务的形式，是打算调用dll，直接集成进去，推理后端是Paddle

**Comment by hhxdestiny** [comment]
@DefTruth 如果有PC客户端部署的场景的话，可能仍有一部分用户使用的机器到目前为止是win7 32位，这个确实头疼
