### ISSUE TITLE
能否提供模型加密的接口？

### ISSUE THREAD

**Issue by wzy123456wzy** [PaddlePaddle/FastDeploy#699]
模型在交付给客户的时候，没有加密手段，很难落地在客户环境上，只能自己公司环境内使用，没有办法满足客户私有云环境的需求。

**Comment by denonzhu** [comment]
自行通过软件把模型加密，加载的时候解密就好了

**Comment by wzy123456wzy** [comment]
> 

是有看过这种方法，不过感觉还是存在隐患，我看到Paddlex是有读文件流的接口，这样更保险一些

**Comment by jiangjiajun** [comment]
目前FD确实还没提供读文件流的接口，这个加入到需求列表。 之后用户在使用时，只需要将解密后的文件流传给FD即可

**Comment by wzy123456wzy** [comment]
> 

可以的话，最好是PC和手机都加上，在手机上的apk经常被人用mt管理器给掏了。。模型直接被人搞走啦

**Comment by felixhjh** [comment]
> > 
> 
> 是有看过这种方法，不过感觉还是存在隐患，我看到Paddlex是有读文件流的接口，这样更保险一些

可以参考上面的PR具体使用方式，已经加入了读文件流的接口，但是暂时只支持Paddle Inference的后端推理引擎，后续加入新的后端推理引擎的支持会再链接到这个issue

**Comment by felixhjh** [comment]
已支持，参照如上PR
