### ISSUE TITLE
Requirement collection for new model/hardware

### ISSUE THREAD

**Issue by leiqing1** [PaddlePaddle/FastDeploy#7]
If you want FastDeploy to support new AI models/new hardware, or build an ecosystem with FastDeploy, please feel free to contact us：
1. Hardware: Example:Amlogic A311D
2. OS: Example:Linux
3. Model name: Example:PP-PicoDet
4. Model link: Example:https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.4/configs/picodet
5. Detailed Description: Example: I hope to use the PP-PicoDet-M model in my own vehicle detection scene to achieve service deployment, but I do not understand the pre- and post-processing of the algorithm, and the deployment is difficult.
6. Contact info:leiqing@baidu.com

**Comment by jiangjiajun** [comment]
此ISSUE由于一年未更新，将会关闭处理，如有需要，可再次更新打开。
