### ISSUE TITLE
ppyoloe模型 多显卡环境使用trt加速，使用第二张显卡出错。Builder was created on device different than current device.

### ISSUE THREAD

**Issue by yyj2013-two** [PaddlePaddle/FastDeploy#707]
## 环境

- FastDeploy版本： 0.7.0 自己编译的 修改了opencv的版本
- 系统平台: Windows x64(Windows10)
- 硬件： CUDA 11.2 CUDNN 8.3 N卡2060 12G和2070ti 11G
- 编译语言： C++ / Python(3.7或3.8等）

## 问题描述
![7a5ef5ba6d9cae71e4452f9ed748f26](https://user-images.githubusercontent.com/54255051/204067192-ace5fbd7-6a6f-4afe-986f-1f851a985498.png)

![9047c34aaf4cc1949276577a7a83641](https://user-images.githubusercontent.com/54255051/204067193-4fafa2f5-df5c-482a-a0e1-5a0200f8c421.png)
![4dfb7e781cfb7f0f7b613d8b44f0850](https://user-images.githubusercontent.com/54255051/204067196-b8c810e4-9410-4607-be7c-e8706133dc96.png)

**Comment by jiangjiajun** [comment]
@yyj2013-two Hi， 由于我这里没有存在多卡的Windows机器，你能帮忙删除一下原代码中的这一行，重新编译测试看能否正常运行吗
https://github.com/PaddlePaddle/FastDeploy/blob/develop/fastdeploy/backends/tensorrt/trt_backend.cc#L305

**Comment by yyj2013-two** [comment]
问题找到了，是因为创建模型和推理不在同一个线程导致的。

**Comment by jiangjiajun** [comment]
@yyj2013-two 也麻烦附一下可以复现的代码供我们分析一下

**Comment by jiangjiajun** [comment]
此ISSUE由于一年未更新，将会关闭处理，如有需要，可再次更新打开。
