### ISSUE TITLE
[Backend] PaddleDetection PicoDet demo 开启paddle_trt出现double free or corruption (!prev)

### ISSUE THREAD

**Issue by wjj19950828** [PaddlePaddle/FastDeploy#711]
## 环境

- FastDeploy版本： Develop
- 系统平台: Linux x64(Ubuntu 18.04)
- 硬件：T4， CUDA 11.7 CUDNN 8.4
- 编译语言： C++

## 问题描述

PaddleDetection demo，在跑paddle_trt后端时会报```double free or corruption (!prev)```, 如下图, paddle_gpu/paddle_cpu无问题
<img width="958" alt="image" src="https://user-images.githubusercontent.com/19977378/204131093-c78f7357-47d6-4a8f-a967-7fa1a428dabf.png">

复现步骤：
以PicoDet为例，在GpuInfer中，option配置如下：
```c++
auto option = fastdeploy::RuntimeOption();
option.UseGpu();
option.UseTrtBackend();
option.EnablePaddleToTrt();

auto model = fastdeploy::vision::detection::PicoDet(model_file, params_file,
                                                    config_file, option);
```

编译
```shell
mkdir build && cd build
cmake .. -DFASTDEPLOY_INSTALL_DIR=${PWD}/fastdeploy-linux-x64-x.x.x
make -j
./infer_picodet_demo ppdet_model/picodet_l_320_coco_lcnet/ 000000014439.jpg 1
```

**Comment by jiangjiajun** [comment]
此ISSUE由于一年未更新，将会关闭处理，如有需要，可再次更新打开。
