### ISSUE TITLE
关于使用FastDeploy部署YOLOE模型的一些疑问

### ISSUE THREAD

**Issue by Dekadenc** [PaddlePaddle/FastDeploy#740]
请问我想在Jeston nano上部署PP-YOLOE模型，使用FastDeploy和Paddle-Lite哪个比较合适

**Comment by jiangjiajun** [comment]
FastDeploy与Paddle Lite是不同类型的产品。 FastDeploy在移动端、边缘端部署也依赖Paddle Lite。

FastDeploy侧重于模型**端到端**的部署（即包含模型任务部署时的数据前后处理），支持多硬件和多后端，可以看到的是除了Paddle Lite，也包含Paddle Inference、OpenVINO、TensorRT、ONNX Runtime等不同的后端，在架构上也可以支持其它的推理引擎。

**Comment by jiangjiajun** [comment]
此ISSUE由于一年未更新，将会关闭处理，如有需要，可再次更新打开。
