### ISSUE TITLE
md文档

### ISSUE THREAD

**Issue by GeT-RiGhTTT** [PaddlePaddle/FastDeploy#750]
## 在fastdeply/docs/cn/quick_start/models/cpp.md中第三步准备CmakeList.txt和第四步中的目录结构不太明白

3. 准备CMakeList.txt
FastDeploy中包含多个依赖库，直接采用g++或编译器编译较为繁杂，推荐使用cmake进行编译配置。示例配置如下，

假设下载或准备的FastDeploy C++ SDK在/Paddle/Download目录下，且目录名为fastdeploy_cpp_sdk，在开发者的项目中只需添加如下代码，即可引入FASTDEPLOY_INCS和FASTDEPLOY_LIBS两个变量，分别表示依赖的头文件和库文件

include(/Paddle/Download/fastdeploy_cpp_sdk/FastDeploy.cmake)
PROJECT(infer_demo C CXX)
CMAKE_MINIMUM_REQUIRED (VERSION 3.10)

include(/Path/to/fastdeploy_cpp_sdk/FastDeploy.cmake)

include_directories(${FASTDEPLOY_INCS})

add_executable(infer_demo ${PROJECT_SOURCE_DIR}/infer_demo.cc)
target_link_libraries(infer_demo ${FASTDEPLOY_LIBS})
4. 编译可执行程序
假设当前目录已经准备好infer_demo.cc和CMakeLists.txt两个文件，目录结构如下所示，即可进行编译

这里目录结构文档中没有显示

**Comment by jiangjiajun** [comment]
已经删除“目录结构如下所示”，因为此目录下就两个文件`infer_demo.cc`和`CMakeLists.txt`，你现在使用有什么问题吗？

**Comment by GeT-RiGhTTT** [comment]
执行时如提示error while loading shared libraries: libxxx.so: cannot open shared object file: No such file...，说明程序执行时没有找到FastDeploy的库路径，可通过执行如下命令，将FastDeploy的库路径添加到环境变量之后，重新执行二进制程序。

source /Path/to/fastdeploy_cpp_sdk/fastdeploy_init.sh


我source完还是回报同样的错误

**Comment by jiangjiajun** [comment]
source时的日志提示贴一下

**Comment by GeT-RiGhTTT** [comment]
icra@icra:~/extenddisk/ZZL/FastDeploy-release-0.8.0/deploy/build$ ./infer_demo 
./infer_demo: error while loading shared libraries: libnvinfer.so.7: cannot open shared object file: No such file or directory
icra@icra:~/extenddisk/ZZL/FastDeploy-release-0.8.0/deploy/build$ source /home/icra/extenddisk/ZZL/FastDeploy-release-0.8.0/build/compiled_fastdeploy_sdk/fastdeploy_init.sh
Import environment variable from FastDeploy...
FastDeploy Lib: /home/icra/extenddisk/ZZL/FastDeploy-release-0.8.0/build/compiled_fastdeploy_sdk/lib
FastTokenizer Lib: /home/icra/extenddisk/ZZL/FastDeploy-release-0.8.0/build/compiled_fastdeploy_sdk/third_libs/install/fast_tokenizer/lib
Paddle2ONNX Lib: /home/icra/extenddisk/ZZL/FastDeploy-release-0.8.0/build/compiled_fastdeploy_sdk/third_libs/install/paddle2onnx/lib
ONNX Runtime Lib: /home/icra/extenddisk/ZZL/FastDeploy-release-0.8.0/build/compiled_fastdeploy_sdk/third_libs/install/onnxruntime/lib
OpenCV Lib: /home/icra/extenddisk/ZZL/FastDeploy-release-0.8.0/build/compiled_fastdeploy_sdk/third_libs/install/opencv/lib
OpenVINO Lib: /home/icra/extenddisk/ZZL/FastDeploy-release-0.8.0/build/compiled_fastdeploy_sdk/third_libs/install/openvino/runtime/lib
TensorRT Lib: /home/icra/extenddisk/ZZL/FastDeploy-release-0.8.0/build/compiled_fastdeploy_sdk/third_libs/install/tensorrt/lib
Paddle Inference Lib: /home/icra/extenddisk/ZZL/FastDeploy-release-0.8.0/build/compiled_fastdeploy_sdk/third_libs/install/paddle_inference/paddle/lib
MKLDNN Lib: /home/icra/extenddisk/ZZL/FastDeploy-release-0.8.0/build/compiled_fastdeploy_sdk/third_libs/install/paddle_inference/third_party/install/mkldnn/lib
MKLML Lib: /home/icra/extenddisk/ZZL/FastDeploy-release-0.8.0/build/compiled_fastdeploy_sdk/third_libs/install/paddle_inference/third_party/install/mklml/lib

**Comment by jiangjiajun** [comment]
@GeT-RiGhTTT 你能试把这个脚本https://github.com/PaddlePaddle/FastDeploy/blob/develop/scripts/fastdeploy_init.sh拷到/home/icra/extenddisk/ZZL/FastDeploy-release-0.8.0 这个目录下，重新再执行一次source吗，如果还有问题的话，再贴一下日志看下

**Comment by GeT-RiGhTTT** [comment]
报同样的错误

**Comment by GeT-RiGhTTT** [comment]
icra@icra:~/extenddisk/ZZL/FastDeploy-release-0.8.0/deploy/build$ source /home/icra/extenddisk/ZZL/FastDeploy-release-0.8.0/fastdeploy_init.sh
=============== Information ======================
FastDeploy Library Path: /home/icra/extenddisk/ZZL/FastDeploy-release-0.8.0
Platform: Linux
==================================================
Find Library Directory: /home/icra/extenddisk/ZZL/FastDeploy-release-0.8.0/build
Find Library Directory: /home/icra/extenddisk/ZZL/FastDeploy-release-0.8.0/build/compiled_fastdeploy_sdk/lib
Find Library Directory: /home/icra/extenddisk/ZZL/FastDeploy-release-0.8.0/build/compiled_fastdeploy_sdk/third_libs/install/onnxruntime/lib
Find Library Directory: /home/icra/extenddisk/ZZL/FastDeploy-release-0.8.0/build/compiled_fastdeploy_sdk/third_libs/install/paddle_inference/paddle/lib
Find Library Directory: /home/icra/extenddisk/ZZL/FastDeploy-release-0.8.0/build/compiled_fastdeploy_sdk/third_libs/install/paddle_inference/third_party/install/mklml/lib
Find Library Directory: /home/icra/extenddisk/ZZL/FastDeploy-release-0.8.0/build/compiled_fastdeploy_sdk/third_libs/install/paddle_inference/third_party/install/mkldnn/lib
Find Library Directory: /home/icra/extenddisk/ZZL/FastDeploy-release-0.8.0/build/compiled_fastdeploy_sdk/third_libs/install/fast_tokenizer/lib
Find Library Directory: /home/icra/extenddisk/ZZL/FastDeploy-release-0.8.0/build/compiled_fastdeploy_sdk/third_libs/install/opencv/lib64
Find Library Directory: /home/icra/extenddisk/ZZL/FastDeploy-release-0.8.0/build/compiled_fastdeploy_sdk/third_libs/install/openvino/runtime/lib
Find Library Directory: /home/icra/extenddisk/ZZL/FastDeploy-release-0.8.0/build/compiled_fastdeploy_sdk/third_libs/install/openvino/runtime/3rdparty/omp/lib
Find Library Directory: /home/icra/extenddisk/ZZL/FastDeploy-release-0.8.0/build/compiled_fastdeploy_sdk/third_libs/install/paddle2onnx/lib
Find Library Directory: /home/icra/extenddisk/ZZL/FastDeploy-release-0.8.0/build/compiled_fastdeploy_sdk/third_libs/install/tensorrt/lib
Find Library Directory: /home/icra/extenddisk/ZZL/FastDeploy-release-0.8.0/build/compiled_fastdeploy_sdk/third_libs/install/tensorrt/lib/stubs
Find Library Directory: /home/icra/extenddisk/ZZL/FastDeploy-release-0.8.0/build/third_libs/paddle_inference/src/extern_paddle_inference/paddle/lib
Find Library Directory: /home/icra/extenddisk/ZZL/FastDeploy-release-0.8.0/build/third_libs/paddle_inference/src/extern_paddle_inference/third_party/install/mklml/lib
Find Library Directory: /home/icra/extenddisk/ZZL/FastDeploy-release-0.8.0/build/third_libs/paddle_inference/src/extern_paddle_inference/third_party/install/mkldnn/lib
Find Library Directory: /home/icra/extenddisk/ZZL/FastDeploy-release-0.8.0/build/third_libs/fast_tokenizer/src/extern_fast_tokenizer/lib
Find Library Directory: /home/icra/extenddisk/ZZL/FastDeploy-release-0.8.0/build/third_libs/paddle2onnx/src/extern_paddle2onnx/lib64
Find Library Directory: /home/icra/extenddisk/ZZL/FastDeploy-release-0.8.0/build/third_libs/install/onnxruntime/lib
Find Library Directory: /home/icra/extenddisk/ZZL/FastDeploy-release-0.8.0/build/third_libs/install/paddle_inference/paddle/lib
Find Library Directory: /home/icra/extenddisk/ZZL/FastDeploy-release-0.8.0/build/third_libs/install/paddle_inference/third_party/install/mklml/lib
Find Library Directory: /home/icra/extenddisk/ZZL/FastDeploy-release-0.8.0/build/third_libs/install/paddle_inference/third_party/install/mkldnn/lib
Find Library Directory: /home/icra/extenddisk/ZZL/FastDeploy-release-0.8.0/build/third_libs/install/fast_tokenizer/lib
Find Library Directory: /home/icra/extenddisk/ZZL/FastDeploy-release-0.8.0/build/third_libs/install/opencv/lib64
Find Library Directory: /home/icra/extenddisk/ZZL/FastDeploy-release-0.8.0/build/third_libs/install/openvino/runtime/lib
Find Library Directory: /home/icra/extenddisk/ZZL/FastDeploy-release-0.8.0/build/third_libs/install/openvino/runtime/3rdparty/omp/lib
Find Library Directory: /home/icra/extenddisk/ZZL/FastDeploy-release-0.8.0/build/third_libs/install/paddle2onnx/lib
Find Library Directory: /home/icra/extenddisk/ZZL/FastDeploy-release-0.8.0/build/third_libs/install/tensorrt/lib
Find Library Directory: /home/icra/extenddisk/ZZL/FastDeploy-release-0.8.0/build/third_libs/install/tensorrt/lib/stubs
[Execute] Will try to export all the library directories to environments, if not work, please try to export these path by your self.
icra@icra:~/extenddisk/ZZL/FastDeploy-release-0.8.0/deploy/build$ ./infer_demo 
./infer_demo: error while loading shared libraries: libnvinfer.so.7: cannot open shared object file: No such file or directory

**Comment by jiangjiajun** [comment]
这个fastdeploy-release-0.8.0是你自己编译的吗，试下直接下载预编译的看下。注意重新开一个命令终端，因为当前终端已经导入了目前这个包的环境变量

在这里重新下载 https://github.com/PaddlePaddle/FastDeploy/blob/develop/docs/en/build_and_install/download_prebuilt_libraries.md

看这里的提示，应该是在编译fastdeploy的时候，链接到你环境中的tensorrt 7.x版本了

**Comment by GeT-RiGhTTT** [comment]
这个文件夹的子文件夹有个build文件夹，是我自己编译的GPU部署C++SKD编译安装

**Comment by jiangjiajun** [comment]
先下载预编译的包测试下哈

**Comment by GeT-RiGhTTT** [comment]
我重新编译了一下，应该链接到了tensorrt 8.x版本，这个问题已经解决了，但是我运行./infer_demo报如下错误
icra@icra:~/extenddisk/ZZL/FastDeploy-release-0.8.0/deploy/build$ ./infer_demo 
[ERROR] fastdeploy/vision/detection/ppdet/preprocessor.cc(37)::BuildPreprocessPipelineFromConfig	Failed to load yaml file infer_cfg.yml, maybe you should check this file.
[ERROR] fastdeploy/vision/detection/ppdet/preprocessor.cc(26)::PaddleDetPreprocessor	Failed to create PaddleDetPreprocessor.
已放弃 (核心已转储)

-----------------------------------------------------------
这是infer_demo里的文件地址：
int main() {
  std::string model_file = "model.pdmodel";
  std::string params_file = "model.pdiparams";
  std::string infer_cfg_file = "infer_cfg.yml";
————————————————————————————————
这是我的目录结构：
![Snipaste_2022-11-30_17-41-39](https://user-images.githubusercontent.com/58615953/204761657-2faedd7c-ca16-45f7-ac70-6bc605e5e759.png)

**Comment by GeT-RiGhTTT** [comment]
另外，能不能加您个联系方式，因为这是部署的最后一步了，我嫌在github上联系有点繁琐，而且没法第一时间反馈，这是我的邮箱zlzhang0v0@foxmail.com

**Comment by jiangjiajun** [comment]
```
[ERROR] fastdeploy/vision/detection/ppdet/preprocessor.cc(37)::BuildPreprocessPipelineFromConfig Failed to load yaml file infer_cfg.yml, maybe you should check this file.
```
这里提示已经很清楚了，没有找到 infer_cfg.yml， 建议检查下传入的模型路径。 加一下我们微信群

![A82A5CD300658C1D0DE1D843C8962BAF](https://user-images.githubusercontent.com/19339784/204766335-3a55488a-e7f8-4b1b-85d7-3df746600955.png)
