### ISSUE TITLE
【已支持】jetson什么时候可以支持fastdeploy gpu版本或者tensorrt版本？

### ISSUE THREAD

**Issue by futureflsl** [PaddlePaddle/FastDeploy#756]
如题，fastdeploy目前只能在jetson上使用cpu，什么时候可以支持gpu

**Comment by jiangjiajun** [comment]
我认为应该在下周五前可以支持

**Comment by jiangjiajun** [comment]
已支持，参考最新文档  https://github.com/PaddlePaddle/FastDeploy/blob/develop/docs/cn/build_and_install/jetson.md

**Comment by jiangjiajun** [comment]
此ISSUE由于一年未更新，将会关闭处理，如有需要，可再次更新打开。
