### ISSUE TITLE
ARM开发板使用cpu部署Fastdeploy遇到的问题？

### ISSUE THREAD

**Issue by Hyperpepe** [PaddlePaddle/FastDeploy#758]
## 环境
- FastDeploy版本： 没有适用的python包。
- 系统平台: Ubuntu 2004
- 硬件： Khadas VIM3
- 编译语言： Python(3.8）

## 问题描述
在wheel列表中找不到适用于arrch的whl文件，也就代表着没法安装环境，但是很奇怪的是能用pip 直接安装fastdeploy-python包，但是版本过低。
![image](https://user-images.githubusercontent.com/74920047/204745456-d72da433-1878-49d8-87b5-d727ae0ef9af.png)
zhe这是我下载的manylinux那个whl文件。
![image](https://user-images.githubusercontent.com/74920047/204745544-cc727405-d817-4ded-af54-f3203c22a2e6.png)

**Comment by jiangjiajun** [comment]
pip install https://bj.bcebos.com/fastdeploy/release/wheels/fastdeploy_python-1.0.0-cp38-cp38-manylinux_2_17_aarch64.whl


我们的库还没托管到pypi源上（CPU以及aarch64的会在最近几天托管上去），当前安装时，需要通过如下命令(不过下面命令aarch64最新的还是0.2.0的版本，今晚会更新成1.0版本)
```
pip install fastdeploy-python -f https://www.paddlepaddle.org.cn/whl/fastdeploy.html

```

**Comment by Hyperpepe** [comment]
好滴
