### ISSUE TITLE
paddleDetection 导出的yolov3 训练模型，在fastdeploy中使用范例预测报错

### ISSUE THREAD

**Issue by formero009** [PaddlePaddle/FastDeploy#772]
## 环境

- FastDeploy版本： 编译安装的0.8.0
- 系统平台: Linux x64(Ubuntu 18.04)
- 硬件： 说明具体硬件型号，CPU
- 编译语言： Python3.8

## 问题描述
在paddledetection中通过 configs/yolov3/yolov3_darknet53_270e_voc.yml 训练的模型，训练完成后通过 tools/infer.py 测试没有问题，
后通过 tools/export_model.py 导出静态模型。导出命令如下:
cd ~/work/PaddleDetection/ && python tools/export_model.py -c configs/yolov3/yolov3_darknet53_270e_voc.yml --output_dir=./inference_model

后将导出的静态模型部署到fastdeploy 环境，使用example中的代码进行测试，报错。
https://github.com/PaddlePaddle/FastDeploy/blob/release/1.0/examples/vision/detection/paddledetection/python/infer_yolov3.py

具体报错内容如下：
![5fd60932a61a021547099e06f51c204](https://user-images.githubusercontent.com/25760739/205075789-0f50d711-002a-45ab-9b6c-77a12ac9c3f6.png)

模型是使用的是下面的开源项目预测的
https://aistudio.baidu.com/aistudio/projectdetail/2025555?channelType=0&channel=0

**Comment by formero009** [comment]
模型文件：yolov3_darknet53_270e_voc.tar.gz

https://tempt.bj.bcebos.com/yolov3_darknet53_270e_voc.tar.gz?authorization=bce-auth-v1/808a52ca8aa547c6b022debe8abb3d56/2022-12-01T14%3A42%3A11Z/-1/host/ab16108853f7aa011d40d78fb1014b965ebfe0267b48b91d42748b973649e58a

**Comment by jiangjiajun** [comment]
是的，因为PaddleX目前还没有支持。正在支持中

**Comment by formero009** [comment]
可是我用的不是paddlex呀

**Comment by formero009** [comment]
> 是的，因为PaddleX目前还没有支持。正在支持中

可是我用的不是paddlex呀

**Comment by jiangjiajun** [comment]
![image](https://user-images.githubusercontent.com/19339784/205221369-cf9fa6b1-418c-44ce-90bf-05128599fc4d.png)
这个模型有些奇怪，旁边有一段独立的分支，麻烦检查下模型哈

**Comment by formero009** [comment]
> ![image](https://user-images.githubusercontent.com/19339784/205221369-cf9fa6b1-418c-44ce-90bf-05128599fc4d.png) 这个模型有些奇怪，旁边有一段独立的分支，麻烦检查下模型哈

麻烦问下你的这个模型图是怎么查看的？我看看我是不是导出错模型了

**Comment by jiangjiajun** [comment]
使用netron查看的，你可以咨询下PaddleDetection

**Comment by formero009** [comment]
> 使用netron查看的，你可以咨询下PaddleDetection

好的，我用visualdl看到了，我问下他们

**Comment by jiangjiajun** [comment]
此ISSUE由于一年未更新，将会关闭处理，如有需要，可再次更新打开。
