### ISSUE TITLE
部署ocr服务端 报错

### ISSUE THREAD

**Issue by Gmgge** [PaddlePaddle/FastDeploy#776]
1.按照[FastDeploy/examples/vision/ocr/PP-OCRv3/serving/](https://github.com/PaddlePaddle/FastDeploy/tree/develop/examples/vision/ocr/PP-OCRv3/serving)中的教程，进行服务端部署，使用了cpu版本的docker
2.在执行[启动服务端](https://github.com/PaddlePaddle/FastDeploy/tree/develop/examples/vision/ocr/PP-OCRv3/serving#13-%E5%90%AF%E5%8A%A8%E6%9C%8D%E5%8A%A1%E7%AB%AF%E5%9C%A8docker%E5%86%85)时：fastdeployserver --model-repository=/ocr_serving/models，报错error: creating server: Internal - failed to load all models
3.模型文件已经下载并按照教程解压等操作
4.部分日志如下：
E1202 06:13:21.330826 189 model_repository_manager.cc:1395] failed to load model 'cls_pp': at least one version must be available under the version policy of model 'cls_pp'
E1202 06:13:21.330861 189 model_repository_manager.cc:1395] failed to load model 'pp_ocr': at least one version must be available under the version policy of model 'pp_ocr'
E1202 06:13:21.330882 189 model_repository_manager.cc:1395] failed to load model 'rec_pp': at least one version must be available under the version policy of model 'rec_pp'
...
I1202 06:13:21.331038 189 server.cc:592]
+-----------------+---------+----------------------------------------+
| Model           | Version | Status                                 |
+-----------------+---------+----------------------------------------+
| cls_postprocess | 1       | READY                                  |
| cls_pp          | -       | Not loaded: No model version was found |
| cls_runtime     | 1       | READY                                  |
| det_postprocess | 1       | READY                                  |
| det_preprocess  | 1       | READY                                  |
| det_runtime     | 1       | READY                                  |
| pp_ocr          | -       | Not loaded: No model version was found |
| rec_postprocess | 1       | READY                                  |
| rec_pp          | -       | Not loaded: No model version was found |
| rec_runtime     | 1       | READY                                  |
+-----------------+---------+----------------------------------------+

Cleaning up...
I1202 06:13:22.375757 189 model_repository_manager.cc:1166] successfully unloaded 'det_postprocess' version 1
I1202 06:13:22.376097 189 model_repository_manager.cc:1166] successfully unloaded 'cls_postprocess' version 1
I1202 06:13:22.379952 189 model_repository_manager.cc:1166] successfully unloaded 'det_preprocess' version 1
I1202 06:13:22.381652 189 model_repository_manager.cc:1166] successfully unloaded 'rec_postprocess' version 1
I1202 06:13:23.331767 189 server.cc:267] Timeout 28: Found 0 live models and 0 in-flight non-inference requests
error: creating server: Internal - failed to load all models

**Comment by Gmgge** [comment]
E1202 06:55:08.349736 315 model_repository_manager.cc:1395] failed to load model 'cls_pp': at least one version must be available under the version policy of model 'cls_pp'
E1202 06:55:08.349772 315 model_repository_manager.cc:1395] failed to load model 'pp_ocr': at least one version must be available under the version policy of model 'pp_ocr'
E1202 06:55:08.349795 315 model_repository_manager.cc:1395] failed to load model 'rec_pp': at least one version must be available under the version policy of model 'rec_pp'

**Comment by HexToString** [comment]
/usr/lib/python3/dist-packages/requests/init.py:89: RequestsDependencyWarning: urllib3 (1.26.13) or chardet (3.0.4) doesn't match a supported version!
warnings.warn("urllib3 ({}) or chardet ({}) doesn't match a supported "
utf-8

**Comment by HexToString** [comment]
看起来是这里的问题，编解码的问题。

**Comment by Gmgge** [comment]
已经修复了这个提示问题 不会报这个warnings了，但是依然报错=_=

**Comment by Gmgge** [comment]
错误是否是因为这个，无法构建这三个模型
E1202 06:55:08.349736 315 model_repository_manager.cc:1395] failed to load model 'cls_pp': at least one version must be available under the version policy of model 'cls_pp'
E1202 06:55:08.349772 315 model_repository_manager.cc:1395] failed to load model 'pp_ocr': at least one version must be available under the version policy of model 'pp_ocr'
E1202 06:55:08.349795 315 model_repository_manager.cc:1395] failed to load model 'rec_pp': at least one version must be available under the version policy of model 'rec_pp'

I1202 06:55:08.349942 315 server.cc:592]
+-----------------+---------+----------------------------------------+
| Model           | Version | Status                                 |
+-----------------+---------+----------------------------------------+
| cls_postprocess | 1       | READY                                  |
| cls_pp          | -       | Not loaded: No model version was found |
| cls_runtime     | 1       | READY                                  |
| det_postprocess | 1       | READY                                  |
| det_preprocess  | 1       | READY                                  |
| det_runtime     | 1       | READY                                  |
| pp_ocr          | -       | Not loaded: No model version was found |
| rec_postprocess | 1       | READY                                  |
| rec_pp          | -       | Not loaded: No model version was found |
| rec_runtime     | 1       | READY                                  |
+-----------------+---------+----------------------------------------+

**Comment by HexToString** [comment]
在 serving文件夹中，执行
mkdir models/pp_ocr/1 && mkdir models/rec_pp/1 && mkdir models/cls_pp/1

**Comment by HexToString** [comment]
就是在串联的model下面创建1个空的1的文件夹试试

**Comment by HexToString** [comment]
如果解决了记得回复我一下。

**Comment by Gmgge** [comment]
@HexToString 你好
1.非常感谢你的指导，创建版本的空文件夹即可解决该报错；
2.在客户端发送请求测试中python3 client.py，会报错端口号不对failed to connect to all addresses，经查看，服务端默认端口号8001，客户端默认端口号9001，修改客户端端口号即可正常。
经测试修复上面两点，可以正常运行该demo，再一次感谢你的回复
