### ISSUE TITLE
请问目前安卓端的目标检测模型只支持PicoDet模型吗？能否提供其他模型？

### ISSUE THREAD

**Issue by wzy123456wzy** [PaddlePaddle/FastDeploy#777]
请问目前安卓端的目标检测模型只支持PicoDet模型吗？PicoDet是否只支持picodet_l_320_coco_lcnet,支持其他的PioDet模型吗？比如picodet_l_640_coco_lcnet.yml，picodet_l_960_coco_lcnet.yml

**Comment by jiangjiajun** [comment]
PicoDet系列，都支持

**Comment by DefTruth** [comment]
可以参考我们的android工程文档说明：
- https://github.com/PaddlePaddle/FastDeploy/tree/develop/examples/vision/detection/paddledetection/android

**Comment by wzy123456wzy** [comment]
> PicoDet系列，都支持

比如PPYOLO系列，可以支持嘛？

**Comment by leiqing1** [comment]
> 你需要将哪个模型部署在安卓端呢，可以给我们提需求，或者直接贡献到FastDeploy哈。
picodet是专门为移动端设计的，arm cpu速度非常快，也建议首选picodet。

**Comment by vamoslc** [comment]
问下rk3588支持picodet全系列吗？ 或者目前支持哪些系列的麻烦列一下吧

**Comment by vamoslc** [comment]
不是只支持picodet&nbsp;你可以在paddle的官方网站上查查&nbsp;很多的


---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年4月2日(周二) 下午2:40
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [PaddlePaddle/FastDeploy] 请问目前安卓端的目标检测模型只支持PicoDet模型吗？能否提供其他模型？ (Issue #777)




 
Closed #777 as completed.
 
&mdash;
