### ISSUE TITLE
PP-OCRv3 Rec 模型，FastDeploy 的准确率相较 PaddleOCR 有一定幅度的下降

### ISSUE THREAD

**Issue by MistEO** [PaddlePaddle/FastDeploy#782]
## 环境

- FastDeploy版本： develop 自行编译，尝试过 release/0.8, release/1.0, 目前使用的是 commit 4fd333f, 均稳定复现
- 系统平台: Windows 11
- 硬件： CPU
- 编译语言： C++

## 问题描述

仅使用识别模型，不使用检测。使用同一个模型（ch_PP-OCRv3_rec_infer），fastdeploy 在相比原本的 [PaddleOCR](https://github.com/PaddlePaddle/PaddleOCR) 库识别效果下降了不少（PaddleOCR 的 [接口](https://github.com/MaaAssistantArknights/PaddleOCR) 是我们自己封装的，不过应该没啥影响），很多原来可以识别出来的图，现在识别错了，或者干脆没有识别结果了。

一开始尝试的是 FastDeploy ONNX Runtime，发现识别率下降了不少，以为是模型转换带来的精度损失。故又使用了 FastDeploy Paddle Inference，识别结果 text 与 Ort 相同，score 差异微乎其微。但这些原本的 PaddleOCR 库都是可以正确识别且得分很高的。怀疑是不是 FastDeploy 在预处理的时候损失了精度或者弄错了什么？

（注：我的环境等应该是正常的，大部分情况识别还是 OK 的，只是少部分图片一直不对）

## 测试用例

测试图片：
![10k](https://user-images.githubusercontent.com/18511905/205291635-efa93d33-cc0b-4ec7-892c-ed556bea1d3d.png)

PaddleOCR，识别正确且得分很高：
![image](https://user-images.githubusercontent.com/18511905/205291879-22679294-6ec0-40a0-986d-d78ca2353aaa.png)

FastDeploy ONNX Runtime，无识别结果，得分 0：
![image](https://user-images.githubusercontent.com/18511905/205294193-f4bf545b-9843-4223-9520-92effc79016e.png)

FastDeploy Paddle Inference，无识别结果，得分 0：
![image](https://user-images.githubusercontent.com/18511905/205293736-a647fe31-e423-4c4c-ae7d-269076686522.png)

FastDeploy 测试代码：
```c++
#include <opencv2/opencv.hpp>
#include <fastdeploy/vision.h>

int main()
{
	fastdeploy::RuntimeOption option;
	//option.UseOrtBackend();
	option.UsePaddleInferBackend();

	fastdeploy::vision::ocr::Recognizer rec(
		"PaddleOCR/rec/inference.pdmodel",
		"PaddleOCR/rec/inference.pdiparams",
		"PaddleOCR/ppocr_keys_v1.txt",
		option);

	if (!rec.Initialized()) {
		return -1;
	}

	cv::Mat image = cv::imread("10k.png");

	std::vector<std::string> texts;
	std::vector<float> scores;
	rec.BatchPredict({ image }, &texts, &scores);

	if (texts.empty() || scores.empty()) {
		std::cerr << "empty" << std::endl;
	}
	else {
		std::cout << "text:" << texts.front() << ", score:" << scores.front() << std::endl;
	}

	return 0;
}
```

## 题外话

`release/0.8` 的时候还是有 `Recognizer::Predict` 的，支持传入单张图片，现在咋只有 `Recognizer::BatchPredict` 了（只能传入一组图片）？嘛虽然也没什么影响，感觉 det 都有 rec 却删了这个挺怪的_(:з」∠)_

## 再题外话

看各位在一些 issue 下回复问为啥用 ORT 而不是 PDInfer，我想说 PDInfer 吃内存实在是吃的太厉害的，加载同一个模型，检测 + 识别 720p 同一张图片，PDInfer 后端要占用 700M 左右内存，且再识别又会吃的更多，我也不知道是 cache 还是内存泄漏。ORT 只占用 300M 不到，而且速度能快一倍以上。不过这个应该不是 FastDeploy 的问题，PaddleOCR 那边也是这样

## 再再题外话

这个库实在是太方便了，感谢各位！

**Comment by MistEO** [comment]
看起来也有人反馈过一个类似的问题 https://github.com/PaddlePaddle/FastDeploy/issues/774

**Comment by yunyaoXYY** [comment]
> ## 环境
> * FastDeploy版本： develop 自行编译，尝试过 release/0.8, release/1.0, 目前使用的是 commit [4fd333f](https://github.com/PaddlePaddle/FastDeploy/commit/4fd333f7f0932a5b1f179e0864bb69dd80e48580), 均稳定复现
> * 系统平台: Windows 11
> * 硬件： CPU
> * 编译语言： C++
> 
> ## 问题描述
> 仅使用识别模型，不使用检测。使用同一个模型（ch_PP-OCRv3_rec_infer），fastdeploy 在相比原本的 [PaddleOCR](https://github.com/PaddlePaddle/PaddleOCR) 库识别效果下降了不少（PaddleOCR 的 [接口](https://github.com/MaaAssistantArknights/PaddleOCR) 是我们自己封装的，不过应该没啥影响），很多原来可以识别出来的图，现在识别错了，或者干脆没有识别结果了。
> 
> 一开始尝试的是 FastDeploy ONNX Runtime，发现识别率下降了不少，以为是模型转换带来的精度损失。故又使用了 FastDeploy Paddle Inference，识别结果 text 与 Ort 相同，score 差异微乎其微。但这些原本的 PaddleOCR 库都是可以正确识别且得分很高的。怀疑是不是 FastDeploy 在预处理的时候损失了精度或者弄错了什么？
> 
> （注：我的环境等应该是正常的，大部分情况识别还是 OK 的，只是少部分图片一直不对）
> 
> ## 测试用例
> 测试图片： ![10k](https://user-images.githubusercontent.com/18511905/205291635-efa93d33-cc0b-4ec7-892c-ed556bea1d3d.png)
> 
> PaddleOCR，识别正确且得分很高： ![image](https://user-images.githubusercontent.com/18511905/205291879-22679294-6ec0-40a0-986d-d78ca2353aaa.png)
> 
> FastDeploy ONNX Runtime，无识别结果，得分 0： ![image](https://user-images.githubusercontent.com/18511905/205294193-f4bf545b-9843-4223-9520-92effc79016e.png)
> 
> FastDeploy Paddle Inference，无识别结果，得分 0： ![image](https://user-images.githubusercontent.com/18511905/205293736-a647fe31-e423-4c4c-ae7d-269076686522.png)
> 
> FastDeploy 测试代码：
> 
> ```c++
> #include <opencv2/opencv.hpp>
> #include <fastdeploy/vision.h>
> 
> int main()
> {
> 	fastdeploy::RuntimeOption option;
> 	//option.UseOrtBackend();
> 	option.UsePaddleInferBackend();
> 
> 	fastdeploy::vision::ocr::Recognizer rec(
> 		"PaddleOCR/rec/inference.pdmodel",
> 		"PaddleOCR/rec/inference.pdiparams",
> 		"PaddleOCR/ppocr_keys_v1.txt",
> 		option);
> 
> 	if (!rec.Initialized()) {
> 		return -1;
> 	}
> 
> 	cv::Mat image = cv::imread("10k.png");
> 
> 	std::vector<std::string> texts;
> 	std::vector<float> scores;
> 	rec.BatchPredict({ image }, &texts, &scores);
> 
> 	if (texts.empty() || scores.empty()) {
> 		std::cerr << "empty" << std::endl;
> 	}
> 	else {
> 		std::cout << "text:" << texts.front() << ", score:" << scores.front() << std::endl;
> 	}
> 
> 	return 0;
> }
> ```
> 
> ## 题外话
> `release/0.8` 的时候还是有 `Recognizer::Predict` 的，支持传入单张图片，现在咋只有 `Recognizer::BatchPredict` 了（只能传入一组图片）？嘛虽然也没什么影响，感觉 det 都有 rec 却删了这个挺怪的_(:з」∠)_
> 
> ## 再题外话
> 看各位在一些 issue 下回复问为啥用 ORT 而不是 PDInfer，我想说 PDInfer 吃内存实在是吃的太厉害的，加载同一个模型，检测 + 识别 720p 同一张图片，PDInfer 后端要占用 700M 左右内存，且再识别又会吃的更多，我也不知道是 cache 还是内存泄漏。ORT 只占用 300M 不到，而且速度能快一倍以上。不过这个应该不是 FastDeploy 的问题，PaddleOCR 那边也是这样
> 
> ## 再再题外话
> 这个库实在是太方便了，感谢各位！

Hello，
1）目前的一个Diff，是PaddleOCR三个模型的BS是固定为1，1，6的, FastDeploy的PP-OCR现在的cls和rec模型的BS不固定，这个会造成精度diff.
2）目前不支持这样单独使用一个模型.
3)   以上两点，均在 https://github.com/PaddlePaddle/FastDeploy/pull/764 这个PR里被升级修复.

**Comment by MistEO** [comment]
@yunyaoXYY @HexToString Hi, 我切到了这个 PR 的分支上，还是上面这张“一万”的图，同样没有识别结果，问题仍然存在。

看了下提交的代码，似乎这个 batch_size 只改变同时处理的图片数量？但如果仅送入一张图片的话，`start_index` 和 `end_index` 相较之前好像没有区别。

**Comment by MistEO** [comment]
@jiangjiajun @yunyaoXYY @HexToString 

Hi, 请问这个问题有什么进展吗？谢谢

**Comment by yunyaoXYY** [comment]
> @jiangjiajun @yunyaoXYY @HexToString
> 
> Hi, 请问这个问题有什么进展吗？谢谢

我这两天复现一下看看

**Comment by yunyaoXYY** [comment]
> ```c++
> #include <opencv2/opencv.hpp>
> #include <fastdeploy/vision.h>
> 
> int main()
> {
> 	fastdeploy::RuntimeOption option;
> 	//option.UseOrtBackend();
> 	option.UsePaddleInferBackend();
> 
> 	fastdeploy::vision::ocr::Recognizer rec(
> 		"PaddleOCR/rec/inference.pdmodel",
> 		"PaddleOCR/rec/inference.pdiparams",
> 		"PaddleOCR/ppocr_keys_v1.txt",
> 		option);
> 
> 	if (!rec.Initialized()) {
> 		return -1;
> 	}
> 
> 	cv::Mat image = cv::imread("10k.png");
> 
> 	std::vector<std::string> texts;
> 	std::vector<float> scores;
> 	rec.BatchPredict({ image }, &texts, &scores);
> 
> 	if (texts.empty() || scores.empty()) {
> 		std::cerr << "empty" << std::endl;
> 	}
> 	else {
> 		std::cout << "text:" << texts.front() << ", score:" << scores.front() << std::endl;
> 	}
> 
> 	return 0;
> }
> ```

Hi你好，这样可以解决.
拉一下最新代码，然后把rec_preprocessor.cc里的OcrRecognizerResizeImage函数中, 
  std::vector<float> value = {0, 0, 0}; 改成   std::vector<float> value = {127, 127, 127}; 
重新编译后，再试一下.

**Comment by yunyaoXYY** [comment]
> @jiangjiajun @yunyaoXYY @HexToString
> 
> Hi, 请问这个问题有什么进展吗？谢谢

Hi你好，这样可以解决.
拉一下最新代码，然后把rec_preprocessor.cc里的OcrRecognizerResizeImage函数中,
std::vector value = {0, 0, 0}; 改成 std::vector value = {127, 127, 127};
重新编译后，再试一下.

**Comment by MistEO** [comment]
![image](https://user-images.githubusercontent.com/18511905/208850249-4a4400cc-8ef3-4078-87e5-a5dcf0d8415f.png)

有结果了，得分和 PaddleOCR 基本差不多，应该是在合理的误差范围内。非常感谢！
