### ISSUE TITLE
FastDeploy加载PaddleSeg导出模型的推理结果与Paddleseg推理结果不一致

### ISSUE THREAD

**Issue by FjjRichard** [PaddlePaddle/FastDeploy#789]
## 环境

- FastDeploy版本： 1.0.0 cpu版本
- 系统平台: Windows x64(Windows10)
- 硬件：  Cpu I5-12400F
- 编译语言： C++ / Python(3.7或3.8等）

## 问题描述
fd 加载PaddleSeg导出的模型，推理结果和 使用PaddleSeg本身推理模块推理出来的结果不一致。
模型是语义分割模型，分割类别有0,1,2。
fd推理的结果会在类别2的边缘增加类别1。实际标注数据类别2的边缘不存在类别1，PaddleSeg推理的结果正常。
下图是，屏蔽的类别2的情况，明显看到fd推理结果在类别2边缘增加了类别1的轮廓

![1](https://user-images.githubusercontent.com/63178095/205495113-fb1d2be5-079d-4bf0-a949-c4888d43654e.jpg)

**Comment by felixhjh** [comment]
您好，这个是您自训练的模型对吗？ 方便贴一下你的deploy.yml的文件内容吗？如果可以的话可以给个模型让我来复现下结果吗？

**Comment by FjjRichard** [comment]
> 您好，这个是您自训练的模型对吗？ 方便贴一下你的deploy.yml的文件内容吗？如果可以的话可以给个模型让我来复现下结果吗？

是的自己训练的模型
deploy.yml内容如下
Deploy:
  input_shape:
  - 1
  - 3
  - 512
  - 512
  model: model.pdmodel
  output_dtype: int32
  output_op: argmax
  params: model.pdiparams
  transforms:
  - type: Normalize


可以提供模型和少量数据

**Comment by felixhjh** [comment]
如果方便的话，可以打包一份发送到huangjianhui04@baidu.com，感谢~

**Comment by FjjRichard** [comment]
> 已发，请查收



> 如果方便的话，可以打包一份发送到[huangjianhui04@baidu.com](mailto:huangjianhui04@baidu.com)，感谢~

**Comment by felixhjh** [comment]
> 下图是，屏蔽的类别2的情况，明显看到fd推理结果在类别2边缘增加了类别1的轮廓

<img width="635" alt="image" src="https://user-images.githubusercontent.com/16222477/205865615-bcc3f09d-2fad-4458-ae77-d019595053ab.png">
FD 最新的代码已经修复相关问题了~ 可以自行编译或者
pip install fastdeploy-gpu-python==0.0.0 -f https://www.paddlepaddle.org.cn/whl/fastdeploy_nightly_build.html 
安装最新develop分支的FD python包

**Comment by FjjRichard** [comment]
> -python==0.0.0 -f

感谢，经测试后，没有问题
