### ISSUE TITLE
视频文件读取失败

### ISSUE THREAD

**Issue by GeT-RiGhTTT** [PaddlePaddle/FastDeploy#793]
这是.cc文件
![cc](https://user-images.githubusercontent.com/58615953/205540483-b303e3eb-5fdc-443c-930d-e1ff809bc324.png)
下面是报错情况
![ccc](https://user-images.githubusercontent.com/58615953/205540549-d1005c4f-5a84-4629-9f49-7441c72f3be0.png)

**Comment by jiangjiajun** [comment]
你好，能麻烦附一下你的系统环境吗？包括Linux或Mac，以及x64或aarch64， 以及Ubuntu版本

**Comment by GeT-RiGhTTT** [comment]
- icra@icra:~/extenddisk/ZZL/FastDeploy-release-0.8.0/deploy/build$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.5 LTS
Release:	18.04
Codename:	bionic
- icra@icra:~/extenddisk/ZZL/FastDeploy-release-0.8.0/deploy/build$ gcc -v
使用内建 specs。
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/local/libexec/gcc/x86_64-pc-linux-gnu/8.2.0/lto-wrapper
目标：x86_64-pc-linux-gnu
配置为：../gcc-8.2.0/configure --enable-checking=release --enable-languages=c,c++ --disable-multilib
线程模型：posix
gcc 版本 8.2.0 (GCC) 
-icra@icra:~/extenddisk/ZZL/FastDeploy-release-0.8.0/deploy/build$ nvcc -V
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2020 NVIDIA Corporation
Built on Mon_Nov_30_19:08:53_PST_2020
Cuda compilation tools, release 11.2, V11.2.67
Build cuda_11.2.r11.2/compiler.29373293_0
- icra@icra:~/extenddisk/ZZL/FastDeploy-release-0.8.0/deploy/build$ cat /usr/include/cudnn_version.h | grep CUDNN_MAJOR -A 2
#define CUDNN_MAJOR 8
#define CUDNN_MINOR 1
#define CUDNN_PATCHLEVEL 1

#define CUDNN_VERSION (CUDNN_MAJOR * 1000 + CUDNN_MINOR * 100 + CUDNN_PATCHLEVEL)

#endif /* CUDNN_VERSION_H */

**Comment by jiangjiajun** [comment]
@GeT-RiGhTTT 能够提供下你的视频文件吗，我来测试下

**Comment by GeT-RiGhTTT** [comment]
emm，那个视频是之前军方的一个项目，不太方便给您，不好意思哈，不过其他您测试其他视频应该也行

**Comment by jiangjiajun** [comment]
Hi, @GeT-RiGhTTT 

受限于不同Linux平台的限制 ，当前FastDeploy内置的OpenCV确实不能读取视频。 不过你可以参考这篇文档，来产出支持视频读取的FastDeploy。

- [自定义OpenCV](https://github.com/PaddlePaddle/FastDeploy/blob/develop/docs/cn/faq/custom_opencv.md)

有任何问题和进展可以在这个issue下反馈

**Comment by GeT-RiGhTTT** [comment]
好的，我看一下，谢谢你
