### ISSUE TITLE
Error in Build FastDeploy Library on Nvidia Jetson Platform

### ISSUE THREAD

**Issue by OwenHuaKargo** [PaddlePaddle/FastDeploy#809]
## Environment

FastDeploy version: the latest code in develop branch
OS Platform: Jetson AGX Xavier
Program Language: e.g. Python 3.6

## Problem description
Python build success with only onnxruntime on CPU. When running with the trt backend, libonnxruntime.so is not found.

**Comment by OwenHuaKargo** [comment]
![image](https://user-images.githubusercontent.com/105018891/206035543-9437dd7c-6f91-4d4c-8d6c-be74549e73fd.png)

**Comment by jiangjiajun** [comment]
This shouldn't happen. How did you build the FastDeploy?

**Comment by OwenHuaKargo** [comment]
I basically followed the instruction here. https://github.com/PaddlePaddle/FastDeploy/blob/develop/docs/en/build_and_install/jetson.md. A weird thing happened during the build is it will fall back to onnxruntime CPU as the message says the aarch64 is not supported for the GPU compiling.

**Comment by jiangjiajun** [comment]
The message is right. Because there's no prebuilt onnxruntime-gpu for Jetson, so only cpu is available.

Could you list your directory `/home/kargo/.local/lib/python3.6....../fastdeploy/libs/third_libs/onnxruntime/lib`, check if there's `libonnxruntime.so.1.12.0`

**Comment by OwenHuaKargo** [comment]
I only found `libonnxruntime.so`. Also, if I am not wrong, Jetson Zoo has prebuilt onnxruntime-gpu for jetson. https://elinux.org/Jetson_Zoo#ONNX_Runtime

**Comment by jiangjiajun** [comment]
> 

There should be a `libonnxruntime.so.1.12.0`, I'm not sure why this happen, could you rebuild the wheel, and check if it works?

And for the Jetson Zoo, I haven't found a prebuilt onnxruntime c++ library for jetson yet, if you know, please let me know.

**Comment by jiangjiajun** [comment]
此ISSUE由于一年未更新，将会关闭处理，如有需要，可再次更新打开。
