### ISSUE TITLE
这个框架Anomaly.Paddle能不能推理的

### ISSUE THREAD

**Issue by monkeycc** [PaddlePaddle/FastDeploy#811]
`https://github.com/ultranity/Anomaly.Paddle`

我看模型也是 pdparams

**Comment by jiangjiajun** [comment]
不支持直接加载完成端到端部署。但是可以使用FastDeploy Runtime来推理模型，参考这里的示例https://github.com/PaddlePaddle/FastDeploy/tree/develop/examples/runtime

**Comment by jiangjiajun** [comment]
此ISSUE由于一年未更新，将会关闭处理，如有需要，可再次更新打开。
