### ISSUE TITLE
python打包exe运行时找不到dll

### ISSUE THREAD

**Issue by OpenStreamData** [PaddlePaddle/FastDeploy#812]
## 环境
win10 cuda11.8 python3.8 yolov7 gpu版本

[FastDeploy][INFO]:  Successfully found CUDA ToolKit from system PATH env -> C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8\bin
Traceback (most recent call last):
  File "fastdeploy\c_lib_wrap.py", line 164, in <module>
ImportError: DLL load failed while importing fastdeploy_main: 动态链接库(DLL)初始化例程失败。

**Comment by jiangjiajun** [comment]
为什么需要将python打包成exe。 FastDeploy也有提供C++部署代码，可以直接使用

**Comment by LiJiaming5558** [comment]
我没有打包exe，正常调用的时候，出现了一次这个问题，
DLL load failed while importing fastdepoly_main: 找不到指定的模块

**Comment by weiweijeff** [comment]
有谁解决这个问题了吗？编写python程序使用了fastdepoly，如果不能使用pyinstaller打包，把程序换成C++又有很大工作量了。
---------------------------------------------------------
我后来使用cx_Freeze打包了程序，cx_Freeze打包后是一个小exe程序带上lib文件夹，也能用。

**Comment by zachary-zheng** [comment]
Mark 一下，我也碰到这个问题了，File "fastdeploy\c_lib_wrap.py", line 164, in <module>
ImportError: DLL load failed: A dynamic link library (DLL) initialization routine failed.
有一说一，用python 开发速度快直接打包成exe 比用c++ 方便太多了。

> 为什么需要将python打包成exe。 FastDeploy也有提供C++部署代码，可以直接使用

**Comment by WilliamQf-AI** [comment]
> 为什么需要将python打包成exe。FastDeploy也有提供C++部署代码，可以直接使用



> 为什么需要将python打包成exe。FastDeploy也有提供C++部署代码，可以直接使用

版面恢复的就没有呢

**Comment by zachary-zheng** [comment]
直接copy ...\site-packages\fastdeploy\libs libs文件夹到打包目录的fastdeploy内替换即可！已经解决！
