### ISSUE TITLE
windows cmake gui下编译后，出现问题反馈

### ISSUE THREAD

**Issue by xinsuinizhuan** [PaddlePaddle/FastDeploy#818]
windows10 VS2019 cmake gui编译后：
1、vision_facealign三个Vsion工程和headpos工程报错，链接错误，说是_PathApend函数链接错误，需要在链接库里面增加shlwapi.lib
2、编译后在bin/release下只生成了exe，未将所有需要的库拷贝到release下，需要手动拷贝。

**Comment by DefTruth** [comment]
感谢您的反馈，我们正在排查具体的问题哈

**Comment by jiangjiajun** [comment]
此ISSUE由于一年未更新，将会关闭处理，如有需要，可再次更新打开。
