### ISSUE TITLE
有人流量出入口统计模型的部署案例吗

### ISSUE THREAD

**Issue by AI-Mart** [PaddlePaddle/FastDeploy#820]
有人流量出入口统计模型的部署案例吗

**Comment by jiangjiajun** [comment]
目前没有这个部署案例。 请问在哪里有相关的模型示例么

**Comment by MontaEllis** [comment]
同问，想要个流量统计的案例，类似于这个【https://aistudio.baidu.com/aistudio/projectdetail/4415732?channelType=0&channel=0】

**Comment by jiangjiajun** [comment]
此ISSUE由于一年未更新，将会关闭处理，如有需要，可再次更新打开。
