### ISSUE TITLE
onnx inference weird result

### ISSUE THREAD

**Issue by gedance** [PaddlePaddle/FastDeploy#822]
## Environment

FastDeploy version: e.g 0.8.0 or the latest code in develop branch
OS Platform: Windows x64
Hardware: cpu
Program Language: e.g. Python 3.8

## Problem description
Please attach the log file if there's problem happend.

Hi, 
I got the latest FastDeploy SDK and installed successfully, and I am facing some issues with inference results.
Testing 2 models (same classes, all the same parameters) just with different datasets(added more data) trained and converted to onnx, but one inferences fine, the other one draws boxes and label incorrectly.
Both onnx works fine when I do onnxruntim inference in python code.

test model : 2 Yolox tiny model converted to onnx (both opset 11)
inference yolox exe command:
$ ./vision_detection_yolox_infer.exe yolox_tiny_20221206_v5.onnx ./imgs/5.jpg 0

When I look at the Netron, I don't see any differences at all.
Could you please let me know what might be the reason for these weird results?

Thank you!

**Comment by jiangjiajun** [comment]
@gedance Do you mean the difference comes from FastDeploy? With your description, it looks like one of your model is not trained well which makes incorrect result.

**Comment by gedance** [comment]
> @gedance Do you mean the difference comes from FastDeploy? With your description, it looks like one of your model is not trained well which makes incorrect result.

Yes, the same 2 model results are different when I inference from FastDeploy. 
The thing is that one was trained using old Yolox (launched version), another trained with the latest version.
Thanks for the response anyways! :) Will try to find out what caused the issue.

**Comment by gedance** [comment]
Verified that it was yolox version issue: one with old Yolox (launched version), another trained with the latest version
The latest version works fine :)

Thanks FastDeploy team, really appreciate your work , I'm learning a lot from this. Cheers!
