### ISSUE TITLE
FastDeploy/docs/cn/faq/custom_opencv.md

### ISSUE THREAD

**Issue by GeT-RiGhTTT** [PaddlePaddle/FastDeploy#828]
能读取视频，但是帧为空
![111](https://user-images.githubusercontent.com/58615953/206196194-95c834fa-7440-4f20-8c8b-98d103dd5655.png)
![1111](https://user-images.githubusercontent.com/58615953/206196287-846a96f0-42b5-4f06-8fa3-870529793c73.png)

**Comment by GeT-RiGhTTT** [comment]
@jiangjiajun 或者能在FastDeploy/examples/vision/detection/paddledetection/cpp里上传个demo吗

**Comment by jiangjiajun** [comment]
https://github.com/PaddlePaddle/FastDeploy/tree/develop/examples/vision/tracking/pptracking/cpp 参考这个demo

**Comment by jiangjiajun** [comment]
此ISSUE由于一年未更新，将会关闭处理，如有需要，可再次更新打开。
