### ISSUE TITLE
benchmark_ppocr.py 未能创建模型

### ISSUE THREAD

**Issue by dchld** [PaddlePaddle/FastDeploy#843]
环境：windows 10 64位
  git clone的最新的FastDeploy代码。
 进入FastDeploy\benchmark目录，执行下面的命令行
(paddle_env) D:\paddle\FastDeploy\benchmark>.\benchmark_ppocr.py --model D:\paddle\models\quat_OCRv3 --det_model det --rec_model rec    --cls_model cls --image d:\openvino\pic_car --cpu_num_thread 24 --iter_num 300 --backend ort  --rec_label_file D:\paddle\models\quat\imglist.txt

发现在在调用到 fd.vision.ocr.DBDetector这函数时，Python程序就退出了
![6494914c74c8335a3d990fbae5ef36a](https://user-images.githubusercontent.com/77605321/206650458-cc1a0851-6a2c-4c38-81ef-e00f41621a53.jpg)

说明：
1。 D:\paddle\models\quat_OCRv3\det和D:\paddle\models\quat_OCRv3\rec目录下的模型文件来自 PaddleOCR开源大礼包\OCR场景应用模型库\车牌识别\蓝绿黄牌识别\CCPD中带quant的模型。
2。backend 参数，换作paddle也是出错

**Comment by wjj19950828** [comment]
@dchld 感谢反馈，这个PR已经修复，可以试下最新代码：https://github.com/PaddlePaddle/FastDeploy/pull/859

**Comment by jiangjiajun** [comment]
此ISSUE由于一年未更新，将会关闭处理，如有需要，可再次更新打开。
