### ISSUE TITLE
imgasize设置问题

### ISSUE THREAD

**Issue by sl00001** [PaddlePaddle/FastDeploy#844]
之前使用0.6版本的时候遇到需要修改图片尺寸 ，infer.cc里面加上model.size_={640,640};但是1.0版本里面这样加就不对了 ，应该怎么去设置呢  谢谢

**Comment by jiangjiajun** [comment]
哪个模型？ 如果是YOLO系列，在1.0中我们重新拆分了模型实现。 对于预处理参数的设置通过`model.GetPreprocessor().SetXXX()`来修改，具体参考C++ API文档 https://baidu-paddle.github.io/fastdeploy-api/cpp/html/

**Comment by sl00001** [comment]
> 哪个模型？ 如果是YOLO系列，在1.0中我们重新拆分了模型实现。 对于预处理参数的设置通过`model.GetPreprocessor().SetXXX()`来修改，具体参考C++ API文档 https://baidu-paddle.github.io/fastdeploy-api/cpp/html/
是yolo系列，我试试， 感谢

**Comment by jiangjiajun** [comment]
此ISSUE由于一年未更新，将会关闭处理，如有需要，可再次更新打开。
