### ISSUE TITLE
 官方环境 error while loading shared libraries: libopencv_video.so.3.4:

### ISSUE THREAD

**Issue by zdyshine** [PaddlePaddle/FastDeploy#848]
## 环境
- 官方环境：docker pull paddlepaddle/fastdeploy:1.0.0-gpu-cuda11.4-trt8.4-21.10

## 问题描述

参照https://github.com/PaddlePaddle/FastDeploy/tree/develop/examples/vision/sr/ppmsvsr/cpp说明进行执行出错：
预编译使用：[fastdeploy-linux-x64-1.0.1.tgz](https://bj.bcebos.com/fastdeploy/release/cpp/fastdeploy-linux-x64-1.0.1.tgz)

命令：./infer_demo PP-MSVSR_reds_x4 vsr_src.mp4 2 2
错误：./infer_demo: error while loading shared libraries: libopencv_video.so.3.4: cannot open shared object file: No such file or directory

**Comment by jiangjiajun** [comment]
执行 source fastdeploy-linux-x64-1.0.1/fastdeploy_init.sh

然后再执行这个二进制试下

**Comment by zdyshine** [comment]
Thanks
