### ISSUE TITLE
Web Demo OCR无法检测和识别文本

### ISSUE THREAD

**Issue by wujushan** [PaddlePaddle/FastDeploy#849]
按照教程https://github.com/PaddlePaddle/FastDeploy/blob/develop/examples/application/js/WebDemo.md 来部署web demo。进行OCR功能的测试。

> 运行环境： win 10 + google chrome 107.0.5304.107 + node v18.12.1 + npm 8.19.2

在模型加载阶段好像可以下载好det和rec模型（状态码都为200）

![download_models](https://user-images.githubusercontent.com/12782418/206849465-1b1b0985-f91f-4ef2-8498-93d977cd3ae7.png)

但在点击识别后，发现没有识别结果：
![rec_result](https://user-images.githubusercontent.com/12782418/206849552-78af7140-e32d-4036-b378-a6e8c302284a.png)

**Comment by chenqianhe** [comment]
1. 多试几次都是没有结果的吗
2. 控制台没有报错是吗
3. 可以发下原图，我们也试一下吗

**Comment by wujushan** [comment]
@chenqianhe 谢谢你的回复。我换了个环境，可以跑通了。
> win10 + google chrome 108.0.5359.99 + node v18.12.1 + npm 9.2.0 
我会把之前测试环境下的版本升级一下，重新进行一次测试看看。
