### ISSUE TITLE
C++部署编译出错

### ISSUE THREAD

**Issue by GeT-RiGhTTT** [PaddlePaddle/FastDeploy#850]
## CPU-C++部署编译

- 系统平台: 
![111](https://user-images.githubusercontent.com/58615953/206852022-5e6b5198-6006-45c4-9fa3-f8c031b0483c.png)

## 问题描述
- 按照cpp.md编译出错 ，错误如下
![1111](https://user-images.githubusercontent.com/58615953/206852062-cb22d837-bd16-4b48-a113-36aa0aac2dd6.png)

**Comment by jiangjiajun** [comment]
参考下examples/vision/detection/paddledetection/cpp下面的代码调用

**Comment by GeT-RiGhTTT** [comment]
还是会报同样的错误

**Comment by GeT-RiGhTTT** [comment]
![image](https://user-images.githubusercontent.com/58615953/206909144-33104e15-65ed-4cb7-bf75-3fd9b19b16c0.png)
![image](https://user-images.githubusercontent.com/58615953/206909156-32dc59c7-9ce3-45d0-9f76-b50cda04f4a0.png)

**Comment by jiangjiajun** [comment]
你使用的FastDeploy C++ SDK版本是多少呢？ 这个代码我们每天都在测试，不会有问题

**Comment by GeT-RiGhTTT** [comment]
> 你使用的FastDeploy C++ SDK版本是多少呢？ 这个代码我们每天都在测试，不会有问题

我自己按照cpu.md编译的

**Comment by jiangjiajun** [comment]
那需要检查下编译时的开关是否正确，除了下面列的开关可以自行修改。其余开关不要修改
![image](https://user-images.githubusercontent.com/19339784/206945985-1d43a7e4-d043-42f1-a0ec-fbbef74c4710.png)

**Comment by GeT-RiGhTTT** [comment]
> 那需要检查下编译时的开关是否正确，除了下面列的开关可以自行修改。其余开关不要修改 ![image](https://user-images.githubusercontent.com/19339784/206945985-1d43a7e4-d043-42f1-a0ec-fbbef74c4710.png)
平台是linux aarch64，所以只加了ENABLE_ORT_BACKEND这一个选项，cmake .. -DENABLE_ORT_BACKEND=ON -CMAKE_INSTALL_PREFIX=${PWD}/compiled_fastdeploy_skd -DOPENCV_DIRECTOORY=/PATH/TO/OPENCV

**Comment by jiangjiajun** [comment]
需要添加ENABLE_VISION=ON

**Comment by GeT-RiGhTTT** [comment]
> 需要添加ENABLE_VISION=ON 这个不是不支持linux(aarch64)嘛

**Comment by GeT-RiGhTTT** [comment]
感谢感谢！搞定了。

**Comment by jiangjiajun** [comment]
此ISSUE由于一年未更新，将会关闭处理，如有需要，可再次更新打开。
