### ISSUE TITLE
yolov5 serving 部署有问题

### ISSUE THREAD

**Issue by richjjj** [PaddlePaddle/FastDeploy#865]
## 环境
- 镜像版本是 paddlepaddle/fastdeploy:1.0.0-gpu-cuda11.4-trt8.4-21.10

## 问题描述
- 出错代码 https://github.com/PaddlePaddle/FastDeploy/blob/7415552cb2d7001fa0c5d69a12b6a1181395a989/examples/vision/detection/yolov5/serving/models/preprocess/1/model.py#L72
- 当前版本下预处理代码有变化，没有preprocess方法。postprocess同理

**Comment by wjj19950828** [comment]
@zcfblq 您好，目前前后处理方式已经更新，在这个PR，已经合入，拉去最新代码即可：https://github.com/PaddlePaddle/FastDeploy/pull/874

**Comment by richjjj** [comment]
是可以啦
