### ISSUE TITLE
fatal error: onnxruntime_cxx_api.h: No such file or directory

### ISSUE THREAD

**Issue by zdyshine** [PaddlePaddle/FastDeploy#869]
## 环境
FastDeploy版本： 
git clone https://github.com/PaddlePaddle/FastDeploy.git
cd FastDeploy

如果您是自行编译的FastDeploy，请说明您的编译方式（参数命令）
mkdir build && cd build
cmake .. -DENABLE_ORT_BACKEND=ON \
         -DWITH_GPU=ON \
         -DORT_DIRECTORY=/workspace/onnxruntime-1.13.1 \
         -DCUDA_DIRECTORY=/usr/local/cuda \
         -DCMAKE_INSTALL_PREFIX=${PWD}/compiled_fastdeploy_sdk \
onnxruntime-1.13.1是从这里下载的: https://github.com/microsoft/onnxruntime/releases
- 系统平台:
docker pull nvidia/cuda:11.3.0-cudnn8-devel-ubuntu20.04
- 硬件： 3090
- 编译语言： C++

## 问题描述
cmake之后
-- *************FastDeploy Building Summary**********
--   CMake version             : 3.25.1
--   CMake command             : /usr/local/bin/cmake
--   System                    : Linux
--   C++ compiler              : /usr/bin/c++
--   C++ compiler version      : 9.4.0
--   CXX flags                 : -Wno-format
--   Build type                :
--   Compile definitions       : _GLIBCXX_USE_CXX11_ABI=1;FASTDEPLOY_LIB;ENABLE_ORT_BACKEND;WITH_GPU;ENABLE_PADDLE_FRONTEND
--   CMAKE_PREFIX_PATH         :
--   CMAKE_INSTALL_PREFIX      : /workspace/FastDeploy/build/compiled_fastdeploy_sdk
--   CMAKE_MODULE_PATH         :
--
--   FastDeploy version        : 0.0.0
--   Paddle2ONNX version       : 1.0.5
--   ENABLE_ORT_BACKEND        : ON
--   ENABLE_RKNPU2_BACKEND     : OFF
--   ENABLE_PADDLE_BACKEND     : OFF
--   ENABLE_LITE_BACKEND       : OFF
--   ENABLE_POROS_BACKEND      : OFF
--   ENABLE_TRT_BACKEND        : OFF
--   ENABLE_OPENVINO_BACKEND   : OFF
--   ONNXRuntime version       : 1.12.0
--   WITH_GPU                  : ON
--   CUDA_DIRECTORY            : /usr/local/cuda
--   TRT_DRECTORY              :
--   BUILD_CUDA_SRC            : ON
--   ENABLE_VISION             : OFF
--   ENABLE_TEXT               : OFF
--   ENABLE_DEBUG              :
--   ENABLE_VISION_VISUALIZE   :
-- Configuring done
-- Generating done
-- Build files have been written to: /workspace/FastDeploy/build

之后执行make -j12出错:

/workspace/FastDeploy/./fastdeploy/backends/ort/ort_backend.h:23:10: fatal error: onnxruntime_cxx_api.h: No such file or directory
   23 | #include "onnxruntime_cxx_api.h"  // NOLINT
      |          ^~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/fastdeploy.dir/build.make:440: CMakeFiles/fastdeploy.dir/fastdeploy/runtime.cc.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/Makefile2:128: CMakeFiles/fastdeploy.dir/all] Error 2
make: *** [Makefile:136: all] Error 2

我是想使用docker进行部署，仅使用ORT推理

**Comment by jiangjiajun** [comment]
需要确保 /workspace/onnxruntime-1.13.1 这个目录下包含`include/onnxruntime_cxx_api.h`这个文件路径

另外目前FD适配到ORT的1.12版本，1.13还没测试过

**Comment by zdyshine** [comment]
感谢回复，我先尝试下

**Comment by zdyshine** [comment]
> 需要确保 /workspace/onnxruntime-1.13.1 这个目录下包含`include/onnxruntime_cxx_api.h`这个文件路径
> 
> 另外目前FD适配到ORT的1.12版本，1.13还没测试过

感谢回复！
使用ORT的1.12版本已成功编译。令想咨询下如何使用转出的ONNX模型，有示例代码吗？

**Comment by jiangjiajun** [comment]
https://github.com/PaddlePaddle/FastDeploy/tree/develop/examples/runtime 参考这里

**Comment by zdyshine** [comment]
> https://github.com/PaddlePaddle/FastDeploy/tree/develop/examples/runtime 参考这里

请问这个目录下
https://github.com/PaddlePaddle/FastDeploy/tree/develop/examples/runtime/cpp
CMakelist.txt中
-------------------------------------------------------------------------------------
1.PROJECT(runtime_demo C CXX)
2.CMAKE_MINIMUM_REQUIRED (VERSION 3.12)
3.
4.# 指定下载解压后的fastdeploy库路径
5.option(FASTDEPLOY_INSTALL_DIR "Path of downloaded fastdeploy sdk.")
6.
7.include(${FASTDEPLOY_INSTALL_DIR}/FastDeploy.cmake)
8.
9.# 添加FastDeploy依赖头文件
10.include_directories(${FASTDEPLOY_INCS})
11.
12.add_executable(runtime_demo ${PROJECT_SOURCE_DIR}/infer_onnx_openvino.cc)
13.# 添加FastDeploy库依赖
14.target_link_libraries(runtime_demo ${FASTDEPLOY_LIBS})
-------------------------------------------------------------------------------------
第5行Path of downloaded fastdeploy sdk.是指fastdeploy 的安装目录吗。比如我git的FastDeploy在/workspace/FastDeploy
Path of downloaded fastdeploy sdk.是/workspace/FastDeploy吗？

指定后报错：
CMake Error at CMakeLists.txt:7 (include):
  include could not find requested file:

    /FastDeploy.cmake
所以有些疑问。

另外可以给一个微信群二维码，我在FastDeploy的Readme中扫码之后，没有弹出二维码，无法进群。
感谢

**Comment by zdyshine** [comment]
> > https://github.com/PaddlePaddle/FastDeploy/tree/develop/examples/runtime 参考这里
> 
> ## 请问这个目录下
> https://github.com/PaddlePaddle/FastDeploy/tree/develop/examples/runtime/cpp
> CMakelist.txt中
> ## 1.PROJECT(runtime_demo C CXX)
> 2.CMAKE_MINIMUM_REQUIRED (VERSION 3.12)
> 3.
> 4.# 指定下载解压后的fastdeploy库路径
> 5.option(FASTDEPLOY_INSTALL_DIR "Path of downloaded fastdeploy sdk.")
> 6.
> 7.include(${FASTDEPLOY_INSTALL_DIR}/FastDeploy.cmake)
> 8.
> 9.# 添加FastDeploy依赖头文件
> 10.include_directories(${FASTDEPLOY_INCS})
> 11.
> 12.add_executable(runtime_demo ${PROJECT_SOURCE_DIR}/infer_onnx_openvino.cc)
> 13.# 添加FastDeploy库依赖
> 14.target_link_libraries(runtime_demo ${FASTDEPLOY_LIBS})
> 第5行Path of downloaded fastdeploy sdk.是指fastdeploy 的安装目录吗。比如我git的FastDeploy在/workspace/FastDeploy Path of downloaded fastdeploy sdk.是/workspace/FastDeploy吗？
> 
> 指定后报错： CMake Error at CMakeLists.txt:7 (include): include could not find requested file:
> 
> ```
> /FastDeploy.cmake
> ```
> 
> 所以有些疑问。
> 
> 另外可以给一个微信群二维码，我在FastDeploy的Readme中扫码之后，没有弹出二维码，无法进群。 感谢

第5行Path of downloaded fastdeploy sdk.是指fastdeploy 的安装目录吗。比如我git的FastDeploy在/workspace/FastDeploy
Path of downloaded fastdeploy sdk.是/workspace/FastDeploy吗？
在build目录下，已自行解決。

**Comment by zdyshine** [comment]
在https://github.com/PaddlePaddle/FastDeploy/tree/develop/examples/runtime/cpp中，
执行
mkdir build & cd build
cmake .. -DFASTDEPLOY_INSTALL_DIR=$fastdeploy_cpp_sdk
make -j之后
执行：./runtime_demo
出现：./runtime_demo: error while loading shared libraries: libonnxruntime.so.1.12.0: cannot open shared object file: No such file or directory
然后执行：
source /Path/to/fastdeploy_cpp_sdk/fastdeploy_init.sh
出现：
=============== Information ======================
FastDeploy Library Path: /workspace/FastDeploy/build/compiled_fastdeploy_sdk
Platform: Linux
==================================================
Find Library Directory: /workspace/FastDeploy/build/compiled_fastdeploy_sdk/third_libs/install/paddle2onnx/lib
Find Library Directory: /workspace/FastDeploy/build/compiled_fastdeploy_sdk/lib
[Execute] Will try to export all the library directories to environments, if not work, please try to export these path by your self.
继续执行：./runtime_demo
依然报错：
./runtime_demo: error while loading shared libraries: libonnxruntime.so.1.12.0: cannot open shared object file: No such file or directory

这个是自己编译的onnxruntime有问题吗？

**Comment by zdyshine** [comment]
感谢，已自行解决遇到的问题。另外可以分享下微信群么？我填了问卷，但是加不进去

**Comment by jiangjiajun** [comment]
<img width="340" alt="image" src="https://user-images.githubusercontent.com/19339784/207302381-a78c6955-a277-42aa-b93f-ff47fddb32f3.png">
