### ISSUE TITLE
error while loading shared libraries: libfastdeploy.so.0.0.0: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by MrMzl** [PaddlePaddle/FastDeploy#870]
## 环境

- FastDeploy版本：git clone https://github.com/PaddlePaddle/FastDeploy.git
- 系统平台: Linux firefly 4.19.219  aarch64 aarch64 aarch64 GNU/Linux
- 硬件： AIO-RK3568J
- 编译语言： C++

## 编译流程
按照下面链接中的编译c++ SDK执行
https://github.com/PaddlePaddle/FastDeploy/blob/develop/docs/cn/build_and_install/rknpu2.md
cd FastDeploy
firefly@firefly:~/FastDeploy/build$ cmake .. -DENABLE_ORT_BACKEND=ON -DENABLE_RKNPU2_BACKEND=ON -DENABLE_VISION=ON -DRKNN2_TARGET_SOC=RK356X -DCMAKE_INSTALL_PREFIX=${PWD}/fastdeploy-0.0.3 
firefly@firefly:~/FastDeploy/build$ make -j8
firefly@firefly:~/FastDeploy/build$ make install
上述编译流程均成功

## 问题描述
- 模型部署出错
https://github.com/PaddlePaddle/FastDeploy/tree/develop/examples/vision/detection/paddledetection/rknpu2/cpp
生成基本目录，编译均成功,在运行例程中出现错误提示:error while loading shared libraries: libfastdeploy.so.0.0.0: cannot open shared object file: No such file or directory

**Comment by jiangjiajun** [comment]
试下执行
```
source  /Path/To/fastdeploy-cpp-sdk/fastdeploy_init.sh
```
然后再执行编译后的二进制文件

**Comment by MrMzl** [comment]
firefly@firefly:~/FastDeploy/scripts$ source fastdeploy_init.sh 
=============== Information ======================
FastDeploy Library Path: /home/firefly/FastDeploy/scripts/fastdeploy_init.sh
Platform: Linux
==================================================
[Execute] Will try to export all the library directories to environments, if not work, please try to export these path by your self.
执行后运行infer_picidet示下，仍然报之前的错误提示。
firefly@firefly:~/FastDeploy/examples/vision/detection/paddledetection/rknpu2/cpp/build/install$ ./infer_picodet 
./infer_picodet: error while loading shared libraries: libfastdeploy.so.0.0.0: cannot open shared object file: No such file or `directory`

**Comment by Zheng-Bicheng** [comment]
您好，make install 后在install目录下会生成lib目录，里面包含了链接需要的所有动态库，输入以下命令指定动态链接库的位置
```
export LD_LIBRARY_PATH=./lib
```

**Comment by MrMzl** [comment]
收到，感谢回复，该问题已解决
