### ISSUE TITLE
【12月部署月-直播课来啦】FastDeploy联合十大硬件公司，《产业级AI 模型部署全攻略》，12月12日～12月30日

### ISSUE THREAD

**Issue by leiqing1** [PaddlePaddle/FastDeploy#873]
![12月部署月](https://user-images.githubusercontent.com/54695910/207280316-f95d56eb-0054-4ae7-848d-0056bf3332a1.jpg)

**Comment by jiangjiajun** [comment]
此ISSUE由于一年未更新，将会关闭处理，如有需要，可再次更新打开。
