### ISSUE TITLE
C++GPU 编译错误 cuda

### ISSUE THREAD

**Issue by 827346462** [PaddlePaddle/FastDeploy#877]
hi,我通过下载预编译文件fastdeploy-linux-x64-gpu-1.0.1。在
FastDeploy/build 工作目录下执行
$ cmake .. -DFASTDEPLOY_INSTALL_DIR=${PWD}/fastdeploy-linux-x64-gpu-1.0.1

我的环境：
cuda 11.6

出现了cuda相关错误：
-- Check for working CUDA compiler: /usr/bin/nvcc
-- Check for working CUDA compiler: /usr/bin/nvcc - broken
CMake Error at /usr/local/lib/python3.6/dist-packages/cmake/data/share/cmake-3.22/Modules/CMakeTestCUDACompiler.cmake:56 (message):
  The CUDA compiler

    "/usr/bin/nvcc"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: /data/LX/FastDeploy/build/CMakeFiles/CMakeTmp
    
    Run Build Command(s):/usr/bin/ninja cmTC_29932 && [1/2] Building CUDA object CMakeFiles/cmTC_29932.dir/main.cu.o
    FAILED: CMakeFiles/cmTC_29932.dir/main.cu.o 
    /usr/bin/nvcc      -c /data/LX/FastDeploy/build/CMakeFiles/CMakeTmp/main.cu -o CMakeFiles/cmTC_29932.dir/main.cu.o
    ptxas fatal   : Value 'sm_30' is not defined for option 'gpu-name'
    ninja: build stopped: subcommand failed.

**Comment by 827346462** [comment]
我也尝试直接源码编译：
出现类似的错误。
按照GPU部署库编译https://github.com/PaddlePaddle/FastDeploy/blob/develop/docs/cn/build_and_install/gpu.md

执行cmake .. -DENABLE_ORT_BACKEND=ON \
         -DENABLE_PADDLE_BACKEND=ON \
         -DENABLE_OPENVINO_BACKEND=ON \
         -DENABLE_TRT_BACKEND=ON \
         -DWITH_GPU=ON \
         -DTRT_DIRECTORY=/data/LX/tensorrt/TensorRT-8.4.1 \
         -DCUDA_DIRECTORY=/usr/local/cuda \
         -DCMAKE_INSTALL_PREFIX=${PWD}/compiled_fastdeploy_sdk \
         -DENABLE_VISION=ON \
         -DOPENCV_DIRECTORY=/usr/local/opencv4 \
         -DENABLE_TEXT=ON

我修改了opencv 的路径和Tensorrt的路径
报错如下：
-- Detecting CUDA compiler ABI info - failed
-- Check for working CUDA compiler: /usr/bin/nvcc
-- Check for working CUDA compiler: /usr/bin/nvcc - broken
CMake Error at /usr/local/lib/python3.6/dist-packages/cmake/data/share/cmake-3.22/Modules/CMakeTestCUDACompiler.cmake:56 (message):
  The CUDA compiler

    "/usr/bin/nvcc"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: /data/LX/FastDeploy/build/CMakeFiles/CMakeTmp
    
    Run Build Command(s):/usr/bin/ninja cmTC_a4646 && [1/2] Building CUDA object CMakeFiles/cmTC_a4646.dir/main.cu.o
    FAILED: CMakeFiles/cmTC_a4646.dir/main.cu.o 
    /usr/bin/nvcc      -c /data/LX/FastDeploy/build/CMakeFiles/CMakeTmp/main.cu -o CMakeFiles/cmTC_a4646.dir/main.cu.o
    ptxas fatal   : Value 'sm_30' is not defined for option 'gpu-name'
    ninja: build stopped: subcommand failed.

**Comment by wang-xinyu** [comment]
@827346462 用的是什么显卡？

**Comment by wang-xinyu** [comment]
/usr/bin/nvcc这个nvcc可能不是cuda11.6的吧，试试用/usr/local/cuda/bin/nvcc

**Comment by 827346462** [comment]
> @827346462 用的是什么显卡？

RTX3090

**Comment by 827346462** [comment]
> 

/usr/bin/nvcc 这个文件内容是：
#!/bin/sh

exec /usr/lib/nvidia-cuda-toolkit/bin/nvcc "$@"

**Comment by 827346462** [comment]
> /usr/bin/nvcc这个nvcc可能不是cuda11.6的吧，试试用/usr/local/cuda/bin/nvcc
我解决了，将nvcc 重新指定了
