### ISSUE TITLE
paddleclas配置文件出错，导致fastdeploy无法识别

### ISSUE THREAD

**Issue by l976308589** [PaddlePaddle/FastDeploy#881]
使用paddleclas，基于 MobileNetV3_large_x1_0_ssld完成训练，效果很好
移植到fast deploy，使用paddleclas的inference_cls.yml作为配置文件，识别出错

**Comment by jiangjiajun** [comment]
附上模型、yml文件，以及出错的日志

**Comment by jiangjiajun** [comment]
此ISSUE由于一年未更新，将会关闭处理，如有需要，可再次更新打开。
