### ISSUE TITLE
C++,GPU编译opencv报错

### ISSUE THREAD

**Issue by zdyshine** [PaddlePaddle/FastDeploy#883]
FastDeploy版本：
git clone https://github.com/PaddlePaddle/FastDeploy.git
cd FastDeploy

如果您是自行编译的FastDeploy，请说明您的编译方式（参数命令）
mkdir build && cd build
cmake .. -DENABLE_ORT_BACKEND=ON
-DWITH_GPU=ON
-DORT_DIRECTORY=/workspace/onnxruntime-1.13.1
-DCUDA_DIRECTORY=/usr/local/cuda
-DCMAKE_INSTALL_PREFIX=${PWD}/compiled_fastdeploy_sdk
onnxruntime-1.13.1是从这里下载的: https://github.com/microsoft/onnxruntime/releases

系统平台:
docker pull nvidia/cuda:11.3.0-cudnn8-devel-ubuntu20.04
硬件： 3090
编译语言： C++

# 昨天尝试编译没有opencv的版本成功了，今天准备加上opencv，进行如下操作：

从网页https://opencv.org/releases/下载OpenCV – 4.5.5的Sources代码，然后执行：
cmake .. -DENABLE_ORT_BACKEND=ON \
         -DWITH_GPU=ON \
         -DORT_DIRECTORY=/workspace/onnxruntime-linux-x64-gpu-1.12.0 \
         -DCUDA_DIRECTORY=/usr/local/cuda \
         -DCMAKE_INSTALL_PREFIX=${PWD}/compiled_fastdeploy_sdk \
         -DENABLE_VISION=ON \
         -DOPENCV_DIRECTORY=/workspace/opencv-4.5.5
出错如下：
CMake Error at cmake/opencv.cmake:142 (find_package):
  Could not find a package configuration file provided by "OpenCV" with any
  of the following names:

    OpenCVConfig.cmake
    opencv-config.cmake

  Add the installation prefix of "OpenCV" to CMAKE_PREFIX_PATH or set
  "OpenCV_DIR" to a directory containing one of the above files.  If "OpenCV"
  provides a separate development package or SDK, be sure it has been
  installed.
Call Stack (most recent call first):
  CMakeLists.txt:420 (include)

尝试locate OpenCVConfig.cmake和find / OpenCVConfig.cmake都没有找到该文件
请问是我opencv代码下载错了吗？该怎么操作。

**Comment by jiangjiajun** [comment]
参考这篇文档  https://github.com/PaddlePaddle/FastDeploy/blob/develop/docs/cn/faq/custom_opencv.md


- 通过-DOPENCV_DIRECTORY指定环境中的OpenCV编译即可, 注意此处的路径/usr/lib/x86_64-linux-gnu/cmake/opencv4需根据你的实际环境路径来设定，此目录下包含OpenCVConfig-version.cmake、OpenCVConfig.cmake等文件。

**Comment by zdyshine** [comment]
> 参考这篇文档 https://github.com/PaddlePaddle/FastDeploy/blob/develop/docs/cn/faq/custom_opencv.md
> 
> * 通过-DOPENCV_DIRECTORY指定环境中的OpenCV编译即可, 注意此处的路径/usr/lib/x86_64-linux-gnu/cmake/opencv4需根据你的实际环境路径来设定，此目录下包含OpenCVConfig-version.cmake、OpenCVConfig.cmake等文件。

感谢回复，下载opencv源码后进行编译，在/usr/local/lib/cmake/opencv4找到对应文件
然后
cmake .. -DENABLE_ORT_BACKEND=ON \
>          -DWITH_GPU=ON \
>          -DORT_DIRECTORY=/workspace/onnxruntime-linux-x64-gpu-1.12.0 \
>          -DCUDA_DIRECTORY=/usr/local/cuda \
>          -DCMAKE_INSTALL_PREFIX=${PWD}/compiled_fastdeploy_sdk \
>          -DENABLE_VISION=ON \
>          -DOPENCV_DIRECTORY=/usr/local/lib/cmake/opencv4/
成功

然后我在example文件夹下:
mkdir vision_test && cd vision_test

按照https://github.com/PaddlePaddle/FastDeploy#fastdeploy-quick-start-cpp

vim test.cc

#include "fastdeploy/vision.h"
int main(int argc, char* argv[]) {
  namespace vision = fastdeploy::vision;
  auto im = cv::imread("000000014439.jpg");

  cv::imwrite("vis_image.jpg", im);
  return 0;
 }
之后按照https://github.com/PaddlePaddle/FastDeploy/tree/develop/examples/vision/matting/ppmatting/cpp
创建CMakeLists.txt -> bulid -> cmake
执行make -j 时出错：
/workspace/FastDeploy/examples/vision_test/test.cc:4:22: error: ‘fastdeploy’ has not been declared
    4 |   namespace vision = fastdeploy::vision;
      |                      ^~~~~~~~~~
/workspace/FastDeploy/examples/vision_test/test.cc:4:34: error: ‘vision’ is not a namespace-name
    4 |   namespace vision = fastdeploy::vision;
      |                                  ^~~~~~
/workspace/FastDeploy/examples/vision_test/test.cc:5:13: error: ‘cv’ has not been declared
    5 |   auto im = cv::imread("000000014439.jpg");
      |             ^~
/workspace/FastDeploy/examples/vision_test/test.cc:7:3: error: ‘cv’ has not been declared
    7 |   cv::imwrite("vis_image.jpg", im);
      |   ^~
make[2]: *** [CMakeFiles/infer_demo.dir/build.make:76: CMakeFiles/infer_demo.dir/test.cc.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:83: CMakeFiles/infer_demo.dir/all] Error 2
make: *** [Makefile:91: all] Error 2

我是想读取图像，预处理，网络推理，后处理，保存结果，一步一步的尝试。
请问这样的思路，需要怎么操作才行。

**Comment by jiangjiajun** [comment]
建议先不用自己编译FastDeploy，而是直接参照文档，下载预编译的库，跑通一个模型看看

**Comment by zdyshine** [comment]
> 建议先不用自己编译FastDeploy，而是直接参照文档，下载预编译的库，跑通一个模型看看

明白，前几天在官方的docker中有跑通过几个模型，但是官方的docker容器太大，现在需要自己编译，然后添加模型。。。

**Comment by jiangjiajun** [comment]
如果编译成功，不会出现找不到fastdeploy命名空间的问题，建议再检查下编译和make install生成的fastdeploy sdk包

**Comment by zdyshine** [comment]
> 如果编译成功，不会出现找不到fastdeploy命名空间的问题，建议再检查下编译和make install生成的fastdeploy sdk包

感谢回复。
我在自定义编译，只使用了onnxruntime和opencv，其他均没有编译，目前可以成功执行https://github.com/PaddlePaddle/FastDeploy/blob/develop/examples/runtime/cpp/infer_onnx_onnxruntime.cc文件，这个是否能说明编译的没问题？

**Comment by jiangjiajun** [comment]
是的

**Comment by zdyshine** [comment]
> 是的

做了一些加载预编译的尝试，通过官方提供的[fastdeploy-linux-x64-gpu-1.0.1.tgz](https://bj.bcebos.com/fastdeploy/release/cpp/fastdeploy-linux-x64-gpu-1.0.1.tgz)，加载#include "fastdeploy/vision.h"并进行cv相关操作不报错，
我怀疑是不是因为我自己的编译问题，导致没有把fastdeploy/vision.h编译进去，我自己的编译命令是
cmake .. -DENABLE_ORT_BACKEND=ON \
         -DWITH_GPU=ON \
         -DORT_DIRECTORY=/workspace/onnxruntime-linux-x64-gpu-1.12.0 \
         -DCUDA_DIRECTORY=/usr/local/cuda \
         -DCMAKE_INSTALL_PREFIX=${PWD}/compiled_fastdeploy_sdk \
         -DENABLE_VISION=ON \
         -DOPENCV_DIRECTORY=/usr/local/lib/cmake/opencv4/
请问这么编译有问题吗？

**Comment by jiangjiajun** [comment]
这个cmake命令没有问题。 问题可能在于你编译demo代码，给出编译demo代码时的cmake日志和命令看下

**Comment by zdyshine** [comment]
> 这个cmake命令没有问题。 问题可能在于你编译demo代码，给出编译demo代码时的cmake日志和命令看下

感谢回复，在您回复的时候，我这边刚刚解决这个问题。复盘了一下使用的编译命令。报错原因如下：
首次编译，不使用opencv：
cmake .. -DENABLE_ORT_BACKEND=ON
-DWITH_GPU=ON
-DORT_DIRECTORY=/workspace/onnxruntime-linux-x64-gpu-1.12.0
-DCUDA_DIRECTORY=/usr/local/cuda
-DCMAKE_INSTALL_PREFIX=${PWD}/compiled_fastdeploy_sdk
首次编译之后，做了一些onnxruntime样例代码尝试，没问题。之后想把opencv编译进去，于是直接执行：
cmake .. -DENABLE_ORT_BACKEND=ON
-DWITH_GPU=ON
-DORT_DIRECTORY=/workspace/onnxruntime-linux-x64-gpu-1.12.0
-DCUDA_DIRECTORY=/usr/local/cuda
-DCMAKE_INSTALL_PREFIX=${PWD}/compiled_fastdeploy_sdk
-DENABLE_VISION=ON
-DOPENCV_DIRECTORY=/usr/local/lib/cmake/opencv4/
之后忘记执行make -j12和make install，导致还是第一次执行得到的文件，FastDeploy.cmake中ENABLE_VISION 为OFF
所以一直报错。
感谢您一直的回复。

**Comment by zdyshine** [comment]
另外在使用官方提供的[fastdeploy-linux-x64-gpu-1.0.1.tgz](https://bj.bcebos.com/fastdeploy/release/cpp/fastdeploy-linux-x64-gpu-1.0.1.tgz)时，由于我只想使用onnxruntime，其他先不使用，在fastdeploy-linux-x64-gpu-1.0.1的third_libs中有一些预编译的tensorrt，openvimo等，大概占用4.4G的空间。我尝试把onnxruntime和opencv之外的全删除，然后修改FastDeploy.cmake配置对应参数为OFF。之后进行代码的一些操作：
cmake .. -DFASTDEPLOY_INSTALL_DIR=/workspace/fastdeploy可以成功执行：
-- The path of ONNXRuntime is /workspace/fastdeploy/third_libs/install/onnxruntime/lib.
-- The path of OpenCV is /workspace/fastdeploy/third_libs/install/opencv.
--
-- *************FastDeploy Building Summary**********
--   CMake version             : 3.25.1
--   CMake command             : /usr/local/bin/cmake
--   System                    : Linux
--   C++ compiler              : /usr/bin/c++
--   C++ compiler version      : 9.4.0
--   CXX flags                 : -Wno-format
--   WITH_GPU                  : ON
--   ENABLE_ORT_BACKEND        : ON
--   ENABLE_RKNPU2_BACKEND     : OFF
--   ENABLE_PADDLE_BACKEND     : OFF
--   ENABLE_POROS_BACKEND      : OFF
--   ENABLE_OPENVINO_BACKEND   : OFF
--   ENABLE_TRT_BACKEND        : OFF
--   ENABLE_LITE_BACKEND       : OFF
--   ENABLE_TRT_BACKEND        : OFF
--   ENABLE_VISION             : ON
--   ENABLE_TEXT               : OFF
--   CUDA_DIRECTORY            : /usr/local/cuda
--   DEPENDENCY_LIBS           : /workspace/fastdeploy/lib/libfastdeploy.so;/workspace/fastdeploy/third_libs/install/onnxruntime/lib/libonnxruntime.so;/usr/local/cuda/lib64/libcudart.so;opencv_calib3d;opencv_core;opencv_dnn;opencv_features2d;opencv_flann;opencv_highgui;opencv_imgcodecs;opencv_imgproc;opencv_ml;opencv_objdetect;opencv_photo;opencv_shape;opencv_stitching;opencv_superres;opencv_video;opencv_videoio;opencv_videostab
-- Configuring done
-- Generating done
-- Build files have been written to: /workspace/fastdeploy/examples/runtime/cpp/build

但是make -j报错：

/usr/bin/ld: warning: libpaddle_inference.so, needed by /workspace/fastdeploy/lib/libfastdeploy.so, not found (try using -rpath or -rpath-link)
/usr/bin/ld: warning: libdnnl.so.2, needed by /workspace/fastdeploy/lib/libfastdeploy.so, not found (try using -rpath or -rpath-link)
/usr/bin/ld: warning: libiomp5.so, needed by /workspace/fastdeploy/lib/libfastdeploy.so, not found (try using -rpath or -rpath-link)
/usr/bin/ld: warning: libopenvino.so, needed by /workspace/fastdeploy/lib/libfastdeploy.so, not found (try using -rpath or -rpath-link)
/usr/bin/ld: warning: libnvinfer.so.8, needed by /workspace/fastdeploy/lib/libfastdeploy.so, not found (try using -rpath or -rpath-link)
/usr/bin/ld: warning: libnvonnxparser.so.8, needed by /workspace/fastdeploy/lib/libfastdeploy.so, not found (try using -rpath or -rpath-link)
/usr/bin/ld: warning: libnvinfer_plugin.so.8, needed by /workspace/fastdeploy/lib/libfastdeploy.so, not found (try using -rpath or -rpath-link)
/usr/bin/ld: warning: libcore_tokenizers.so, needed by /workspace/fastdeploy/lib/libfastdeploy.so, not found (try using -rpath or -rpath-link)
/usr/bin/ld: warning: libpaddle2onnx.so.1.0.5, needed by /workspace/fastdeploy/lib/libfastdeploy.so, not found (try using -rpath or -rpath-link)
/usr/bin/ld: /workspace/fastdeploy/lib/libfastdeploy.so: undefined reference to `paddlenlp::fast_tokenizer::core::Encoding::GetOffsets() const'
/usr/bin/ld: /workspace/fastdeploy/lib/libfastdeploy.so: undefined reference to `paddlenlp::fast_tokenizer::pretokenizers::CharToBytesOffsetConverter::CharToBytesOffsetConverter(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
/usr/bin/ld: /workspace/fastdeploy/lib/libfastdeploy.so: undefined reference to `void paddle_infer::Tensor::CopyToCpu<int>(int*) const'
/usr/bin/ld: /workspace/fastdeploy/lib/libfastdeploy.so: undefined reference to `createInferRuntime_INTERNAL'
/usr/bin/ld: /workspace/fastdeploy/lib/libfastdeploy.so: undefined reference to `ov::Any::Base::init(std::shared_ptr<ov::Node> const&)'
/usr/bin/ld: /workspace/fastdeploy/lib/libfastdeploy.so: undefined reference to `float* paddle_infer::Tensor::data<float>(paddle_infer::PlaceType*, int*) const'
/usr/bin/ld: /workspace/fastdeploy/lib/libfastdeploy.so: undefined reference to `paddle_infer::Predictor::GetOutputHandle(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
/usr/bin/ld: /workspace/fastdeploy/lib/libfastdeploy.so: undefined reference to `paddle2onnx::PaddleReader::PaddleReader(char const*, int)'
/usr/bin/ld: /workspace/fastdeploy/lib/libfastdeploy.so: undefined reference to `unsigned char* paddle_infer::Tensor::data<unsigned char>(paddle_infer::PlaceType*, int*) const'
/usr/bin/ld: /workspace/fastdeploy/lib/libfastdeploy.so: undefined reference to `ov::Any::Any(char const*)'
/usr/bin/ld: /workspace/fastdeploy/lib/libfastdeploy.so: undefined reference to `ov::InferRequest::infer()'
/usr/bin/ld: /workspace/fastdeploy/lib/libfastdeploy.so: undefined reference to `vtable for ov::Any::Base'
/usr/bin/ld: /workspace/fastdeploy/lib/libfastdeploy.so: undefined reference to `ov::Dimension::Dimension(long)'
/usr/bin/ld: /workspace/fastdeploy/lib/libfastdeploy.so: undefined reference to `ov::as_node_vector(std::vector<ov::Output<ov::Node>, std::allocator<ov::Output<ov::Node> > > const&)'
/usr/bin/ld: /workspace/fastdeploy/lib/libfastdeploy.so: undefined reference to `ov::Any::Base::as_runtime_attribute() const'
/usr/bin/ld: /workspace/fastdeploy/lib/libfastdeploy.so: undefined reference to `paddlenlp::fast_tokenizer::core::Tokenizer::EnableTruncMethod(unsigned long, unsigned long, paddlenlp::fast_tokenizer::core::Direction, paddlenlp::fast_tokenizer::core::TruncStrategy)'
/usr/bin/ld: /workspace/fastdeploy/lib/libfastdeploy.so: undefined reference to `ov::util::Read<int, void>::operator()(std::istream&, int&) const'
/usr/bin/ld: /workspace/fastdeploy/lib/libfastdeploy.so: undefined reference to `ov::CompiledModel::~CompiledModel()'
/usr/bin/ld: /workspace/fastdeploy/lib/libfastdeploy.so: undefined reference to `ov::PartialShape::PartialShape(std::vector<ov::Dimension, std::allocator<ov::Dimension> >)'
/usr/bin/ld: /workspace/fastdeploy/lib/libfastdeploy.so: undefined reference to `void paddle_infer::Tensor::ShareExternalData<unsigned char>(unsigned char const*, std::vector<int, std::allocator<int> > const&, paddle_infer::PlaceType, paddle_infer::DataLayout)'
/usr/bin/ld: /workspace/fastdeploy/lib/libfastdeploy.so: undefined reference to `ov::Model::reshape(std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, ov::PartialShape, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, ov::PartialShape> > > const&)'
请问我这种操作方式可行吗？不可行的话我就不继续尝试了。。。

**Comment by zdyshine** [comment]
另外请教下如何生成自己的预编译库，类似[fastdeploy-linux-x64-gpu-1.0.1.tgz](https://bj.bcebos.com/fastdeploy/release/cpp/fastdeploy-linux-x64-gpu-1.0.1.tgz)这样

**Comment by jiangjiajun** [comment]
```
/workspace/fastdeploy
```
这个目录看起来不是编译生成的sdk库（注意是要make install生成的库，而非下载的FastDeploy源代码）如何编译其实文档里面有说 https://github.com/PaddlePaddle/FastDeploy/tree/develop/docs/cn/build_and_install

**Comment by zdyshine** [comment]
> ```
> /workspace/fastdeploy
> ```
> 
> 这个目录看起来不是编译生成的sdk库（注意是要make install生成的库，而非下载的FastDeploy源代码）如何编译其实文档里面有说 https://github.com/PaddlePaddle/FastDeploy/tree/develop/docs/cn/build_and_install

抱歉忘记说了，我修改了文件名：原始文件是fastdeploy-linux-x64-gpu-1.0.1 修改之后是fastdeploy，去掉了后面的东西
