### ISSUE TITLE
PPOCRV3服务化部署,切换TRT后端报错

### ISSUE THREAD

**Issue by wxz5459** [PaddlePaddle/FastDeploy#891]
## 环境

- FastDeploy版本： 官方docker的GPU版本fastdeploy-linux-gpu-1.0.0
- 系统平台: Linux x64(Ubuntu 18.04) 
- 硬件： NVIDIA V100
- 编译语言： C++ / Python3.8

## 问题描述
- 参考PP-OCR服务化部署示例，在docker中部署PPOCRV3的服务化版本，切换到TensorRT引擎，参数如下：
optimization {
  execution_accelerators {
    gpu_execution_accelerator : [
      {
        name : "tensorrt"
        # 使用TensorRT的FP16推理,其他可选项为: trt_fp32、trt_int8
        parameters { key: "precision" value: "trt_fp16" }
      }
    ]
  }
}
发送预测请求后，报如下错误：
[WARNING] fastdeploy/backends/tensorrt/utils.cc(40)::Update	[New Shape Out of Range] input name: x, shape: [1, 3, 960, 736], The shape range before: min_shape=[-1, 3, -1, -1], max_shape=[-1, 3, -1, -1].
[WARNING] fastdeploy/backends/tensorrt/utils.cc(52)::Update	[New Shape Out of Range] The updated shape range now: min_shape=[1, 3, 960, 736], max_shape=[1, 3, 960, 736].
[WARNING] fastdeploy/backends/tensorrt/trt_backend.cc(296)::Infer	TensorRT engine will be rebuilt once shape range information changed, this may take lots of time, you can set a proper shape range before loading model to avoid rebuilding process. refer https://github.com/PaddlePaddle/FastDeploy/blob/develop/docs/en/faq/tensorrt_tricks.md for more details.
[INFO] fastdeploy/backends/tensorrt/trt_backend.cc(495)::BuildTrtEngine	[TrtBackend] Use FP16 to inference.
[INFO] fastdeploy/backends/tensorrt/trt_backend.cc(500)::BuildTrtEngine	Start to building TensorRT Engine...
[ERROR] fastdeploy/backends/tensorrt/trt_backend.cc(238)::log	2: [pluginV2DynamicExtRunner.cpp::execute::115] Error Code 2: Internal Error (Assertion status == kSTATUS_SUCCESS failed. )
[ERROR] fastdeploy/backends/tensorrt/trt_backend.cc(238)::log	2: [builder.cpp::buildSerializedNetwork::636] Error Code 2: Internal Error (Assertion engine != nullptr failed. )
[ERROR] fastdeploy/backends/tensorrt/trt_backend.cc(563)::BuildTrtEngine	Failed to call buildSerializedNetwork().
[ERROR] fastdeploy/backends/tensorrt/trt_backend.cc(394)::SetInputs	TRTBackend SetInputs not find name:x
Signal (6) received.
 0# 0x0000558EC5DF48A9 in fastdeployserver
 1# 0x00007EFC6FF46210 in /usr/lib/x86_64-linux-gnu/libc.so.6
 2# gsignal in /usr/lib/x86_64-linux-gnu/libc.so.6
 3# abort in /usr/lib/x86_64-linux-gnu/libc.so.6
 4# fastdeploy::TrtBackend::SetInputs(std::vector<fastdeploy::FDTensor, std::allocator<fastdeploy::FDTensor> > const&) in /opt/fastdeploy/lib/libfastdeploy_runtime.so.1.0.0
 5# fastdeploy::TrtBackend::Infer(std::vector<fastdeploy::FDTensor, std::allocator<fastdeploy::FDTensor> >&, std::vector<fastdeploy::FDTensor, std::allocator<fastdeploy::FDTensor> >*, bool) in /opt/fastdeploy/lib/libfastdeploy_runtime.so.1.0.0
 6# fastdeploy::Runtime::Infer() in /opt/fastdeploy/lib/libfastdeploy_runtime.so.1.0.0
 7# 0x00007EFC50020134 in /opt/tritonserver/backends/fastdeploy/libtriton_fastdeploy.so
 8# 0x00007EFC50023B96 in /opt/tritonserver/backends/fastdeploy/libtriton_fastdeploy.so
 9# TRITONBACKEND_ModelInstanceExecute in /opt/tritonserver/backends/fastdeploy/libtriton_fastdeploy.so
10# 0x00007EFC70AD283A in /opt/tritonserver/bin/../lib/libtritonserver.so
11# 0x00007EFC70AD304D in /opt/tritonserver/bin/../lib/libtritonserver.so
12# 0x00007EFC70987801 in /opt/tritonserver/bin/../lib/libtritonserver.so
13# 0x00007EFC70ACCDC7 in /opt/tritonserver/bin/../lib/libtritonserver.so
14# 0x00007EFC70334DE4 in /usr/lib/x86_64-linux-gnu/libstdc++.so.6
15# 0x00007EFC707B2609 in /usr/lib/x86_64-linux-gnu/libpthread.so.0
16# clone in /usr/lib/x86_64-linux-gnu/libc.so.6

**Comment by jiangjiajun** [comment]
@wxz5459 Hi, 感谢反馈。 1.0.0的镜像确实存在TRT下开FP16的问题，我们已更新镜像，麻烦拉最新的1.0.1镜像进行部署
```
docker pull  registry.baidubce.com/paddlepaddle/fastdeploy:1.0.1-gpu-cuda11.4-trt8.4-21.10
```

如若还有任何问题，可在此issue下随时反馈

**Comment by wxz5459** [comment]
感谢更新，用新版本后可以正常预测。
同时发现一个新问题：
每次预测新图片的时候，因rec部分的batch_size不是固定的，导致服务一直在rebuild TensorRT engine（相当耗时）,请问是否可参考RuntimeOption，提供手动设置动态Shape的接口？

**Comment by jiangjiajun** [comment]
@wxz5459  TRT动态Shape的设置，可以参考这个demo https://github.com/PaddlePaddle/FastDeploy/blob/develop/examples/vision/classification/paddleclas/serving/models/runtime/config.pbtxt

**Comment by wxz5459** [comment]
在config.pbtxt里面设置动态shape后，可以正常执行预测了
但在单卡上开启多实例（det和rec分别开启2个实例）后，执行预测时会报如下错误：
I1222 08:42:53.500125 3792 grpc_server.cc:4117] Started GRPCInferenceService at 0.0.0.0:8030
I1222 08:42:53.500498 3792 http_server.cc:2815] Started HTTPService at 0.0.0.0:8000
I1222 08:42:53.542426 3792 http_server.cc:167] Started Metrics Service at 0.0.0.0:8002
[ERROR] fastdeploy/backends/tensorrt/trt_backend.cc(238)::log	3: [executionContext.cpp::setBindingDimensions::940] Error Code 3: API Usage Error (Parameter check failed at: runtime/api/executionContext.cpp::setBindingDimensions::940, condition: mOptimizationProfile >= 0 && mOptimizationProfile < mEngine.getNbOptimizationProfiles()
)
[ERROR] fastdeploy/backends/tensorrt/trt_backend.cc(238)::log	3: [executionContext.cpp::getBindingDimensions::997] Error Code 3: API Usage Error (Parameter check failed at: runtime/api/executionContext.cpp::getBindingDimensions::997, condition: mOptimizationProfile >= 0 && mOptimizationProfile < mEngine.getNbOptimizationProfiles()
)
Signal (11) received.
 0# 0x000055979CE8B8A9 in fastdeployserver
 1# 0x00007F7442AE7210 in /usr/lib/x86_64-linux-gnu/libc.so.6
 2# int std::accumulate<int const*, int, std::multiplies<long> >(int const*, int const*, int, std::multiplies<long>) in /opt/fastdeploy/lib/libfastdeploy_runtime.so.1.0.1
 3# fastdeploy::Volume(nvinfer1::Dims32 const&) in /opt/fastdeploy/lib/libfastdeploy_runtime.so.1.0.1
 4# fastdeploy::FDGenericBuffer<fastdeploy::FDDeviceAllocator, fastdeploy::FDDeviceFree>::resize(nvinfer1::Dims32 const&) in /opt/fastdeploy/lib/libfastdeploy_runtime.so.1.0.1
 5# fastdeploy::TrtBackend::AllocateOutputsBuffer(std::vector<fastdeploy::FDTensor, std::allocator<fastdeploy::FDTensor> >*, bool) in /opt/fastdeploy/lib/libfastdeploy_runtime.so.1.0.1
 6# fastdeploy::TrtBackend::Infer(std::vector<fastdeploy::FDTensor, std::allocator<fastdeploy::FDTensor> >&, std::vector<fastdeploy::FDTensor, std::allocator<fastdeploy::FDTensor> >*, bool) in /opt/fastdeploy/lib/libfastdeploy_runtime.so.1.0.1
 7# fastdeploy::Runtime::Infer() in /opt/fastdeploy/lib/libfastdeploy_runtime.so.1.0.1
 8# 0x00007F7428446184 in /opt/tritonserver/backends/fastdeploy/libtriton_fastdeploy.so
 9# 0x00007F74284498D6 in /opt/tritonserver/backends/fastdeploy/libtriton_fastdeploy.so
10# TRITONBACKEND_ModelInstanceExecute in /opt/tritonserver/backends/fastdeploy/libtriton_fastdeploy.so
11# 0x00007F744367383A in /opt/tritonserver/bin/../lib/libtritonserver.so
12# 0x00007F744367404D in /opt/tritonserver/bin/../lib/libtritonserver.so
13# 0x00007F7443528801 in /opt/tritonserver/bin/../lib/libtritonserver.so
14# 0x00007F744366DDC7 in /opt/tritonserver/bin/../lib/libtritonserver.so
15# 0x00007F7442ED5DE4 in /usr/lib/x86_64-linux-gnu/libstdc++.so.6
16# 0x00007F7443353609 in /usr/lib/x86_64-linux-gnu/libpthread.so.0
17# clone in /usr/lib/x86_64-linux-gnu/libc.so.6

Segmentation fault (core dumped)
1222 08:44:19.386902 3964 pb_stub.cc:777] Non-graceful termination detected. 1222 08:44:19.386908 3913 pb_stub.cc:777] Non-graceful termination detected. 1222 08:44:19.386907 3802 pb_stub.cc:777] Non-graceful termination detected. 


1222 08:44:19.386932 3859 pb_stub.cc:777] Non-graceful termination detected.

**Comment by HexToString** [comment]
你换一下镜像的版本，1.0.0镜像里面的onnxruntime好像确实是有点问题，将版本号换为1.0.1试试

**Comment by HexToString** [comment]
在配置中添加
parameters {key: "is_clone" value: "0"}

**Comment by HexToString** [comment]
您好，您反馈的这个问题经我们验证是存在的。
目前临时的解决方式是：
当使用tensorrt后端，count数量>1时候，需要在
gpu_execution_accelerator : [{
    name : "tensorrt"
    # 添加以下参数，可以解决该问题
    parameters {key: "is_clone" value: "0"}
}]

后续我们会修复该问题。

**Comment by wxz5459** [comment]
感谢，添加参数后，可以正常预测
切换到paddle后端，使用MKLDNN来预测，发现检测模型无法正常工作，不报错但输出为空，可能是因为没有删除conv_transpose_eltwiseadd_bn_fuse_pass和matmul_transpose_reshape_fuse_pass这两个节点导致的，我打算先在FastDeploy/serving/src/fastdeploy_runtime.cc中添加delete_pass参数（调用runtime_options_->DeletePaddleBackendPass）来删除，烦请在后续优化中考虑下这个问题。

**Comment by yunyaoXYY** [comment]
> 感谢，添加参数后，可以正常预测 切换到paddle后端，使用MKLDNN来预测，发现检测模型无法正常工作，不报错但输出为空，可能是因为没有删除conv_transpose_eltwiseadd_bn_fuse_pass和matmul_transpose_reshape_fuse_pass这两个节点导致的，我打算先在FastDeploy/serving/src/fastdeploy_runtime.cc中添加delete_pass参数（调用runtime_options_->DeletePaddleBackendPass）来删除，烦请在后续优化中考虑下这个问题。

Hi你好, MKLDNN预测PP-OCR不需要删除pass就能正常预测啊.
你能把 『官方docker的GPU版本fastdeploy-linux-gpu-1.0.0』这个换成1.0.1版本再试一下吗?

**Comment by wxz5459** [comment]
将版本更新到1.0.2后，CPU环境下，切换到paddle后端进行测试，结果如下：
1、删除pass后结果无变化
2、关闭mkldnn，PPOCRV3的检测模型输出结果正常
3、开启mkldnn，PPOCRV3的检测模型输出结果存在问题，每个box看着只有第一个元素有值？
[[[[5.2411499e-13 0.0000000e+00 0.0000000e+00 ... 0.0000000e+00
    0.0000000e+00 0.0000000e+00]
   [5.3670311e-15 0.0000000e+00 0.0000000e+00 ... 0.0000000e+00
    0.0000000e+00 0.0000000e+00]
   [1.4918782e-15 0.0000000e+00 0.0000000e+00 ... 0.0000000e+00
    0.0000000e+00 0.0000000e+00]

**Comment by jiangjiajun** [comment]
此ISSUE由于一年未更新，将会关闭处理，如有需要，可再次更新打开。
