### ISSUE TITLE
请问 infer 函数支持拼图吗？

### ISSUE THREAD

**Issue by cunjing56** [PaddlePaddle/FastDeploy#895]
参考这个案例，会遇到需要大图切图再训练的情况，paddledetection 的infer支持拼图预测

!python tools/infer.py -c configs/smalldet/ppyoloe_crn_l_80e_sliced_visdrone_640_025.yml -o weights=output/ppyoloe_crn_l_80e_sliced_visdrone_640_025/best_model.pdparams --infer_img=../data/test/1__H2_817171_IO-NIO198M_210121A0050-1-1.jpg --draw_threshold=0.25 --slice_infer --slice_size 640 640 --overlap_ratio 0.25 0.25 --combine_method=nms --match_threshold=0.6 --match_metric=iou --save_results=True

https://aistudio.baidu.com/aistudio/projectdetail/5122094?contributionType=1

如果用这个案例训练的模型，导出后在fastdeploy预测，可以支持infer_img是原图，但是先切图再预测，再拼图，再传回拼图的预测结果吗？

**Comment by jiangjiajun** [comment]
目前没有支持，需要自行切图+拼图

**Comment by jiangjiajun** [comment]
此ISSUE由于一年未更新，将会关闭处理，如有需要，可再次更新打开。
