### ISSUE TITLE
最后的执行程序如何得到一个.so动态库文件

### ISSUE THREAD

**Issue by zdyshine** [PaddlePaddle/FastDeploy#896]
感谢开源和指导，最后成功make到可执行二进制文件./runtime_demo。想请问下，如果想得到一个.so动态库文件，该如何操作？

**Comment by jiangjiajun** [comment]
这个可以在网上找一下说明，cmake如何配置编译生成动态库

**Comment by zdyshine** [comment]
> 这个可以在网上找一下说明，cmake如何配置编译生成动态库

感谢回复，已解决
