### ISSUE TITLE
边缘侧部署Serving

### ISSUE THREAD

**Issue by Sqhttwl** [PaddlePaddle/FastDeploy#9]
反馈一个bug,文档中写的是./easyedge_serving ./RES可以启动http服务
![1addb70e0f0a8ba8.jpg](https://user-images.githubusercontent.com/61459740/176999462-bbe2a4d4-4ece-464e-b242-1e492bb73684.jpg)
但实际需要在RES后面添加一个参数，任意一个数字
![mmexport1656762023211.jpg](https://user-images.githubusercontent.com/61459740/176999506-d3cc8eff-e6b9-41e9-a9d5-e7a6ac13de68.jpg)
![mmexport1656762018367.jpg](https://user-images.githubusercontent.com/61459740/176999511-eaeeb8c7-dc9b-4739-8351-9f7f53b39b64.jpg)
这里模型采用的是PP-YOLO的物体检测
![mmexport1656762015495.jpg](https://user-images.githubusercontent.com/61459740/176999522-58385c24-3479-4433-a423-7b908036e908.jpg)

**Comment by leiqing1** [comment]
您好，Jetson上测试Demo的bug已经收到，我们尽快修复。
您现在使用，可以通过修改src文件下的代码，重新编译源代码，可以先解决结合这个问题。
感谢您反馈问题！
