### ISSUE TITLE
请问Vectornet部署支持吗？

### ISSUE THREAD

**Issue by tanjatang** [PaddlePaddle/FastDeploy#900]
*********************************************
开源不易，工程师每天有大量研发工作，请直接按此issue模版进行提问

这会大大减少工程师与你确认使用环境，编译过程中的基础信息时间
*********************************************

## 环境

- FastDeploy版本： fastdeploy-linux-gpu-0.8.0
- 系统平台: Linux x64(Ubuntu 20.04) / Windows x64(Windows10) / Mac OSX arm(12.0) / Mac OSX intel(12.0)
- 硬件： 说明具体硬件型号，如 Nvidia GPU RTX3060 CUDA 11.4 CUDNN 8.3
- 编译语言： C++ 

## 问题描述
请问支持vectornet部署吗？

*********************************************
开源不易，工程师每天有大量研发工作，请直接按此issue模版进行提问

这会大大减少工程师与你确认使用环境，编译过程中的基础信息时间
*********************************************

**Comment by jiangjiajun** [comment]
这个模型来源于哪个开源项目呢，可以贴一下具体的链接么

**Comment by jiangjiajun** [comment]
此ISSUE由于一年未更新，将会关闭处理，如有需要，可再次更新打开。
