### ISSUE TITLE
使用FastDeploy进行OCR识别结果与PaddleOCR推理结果不一样

### ISSUE THREAD

**Issue by yz2yz** [PaddlePaddle/FastDeploy#904]
## 完整脚本和测试图片，网盘：
链接：https://pan.baidu.com/s/1M88ybh4tqWIMvtguZWBUYg 
提取码：gcez 

## 环境
FastDeploy版本： fastdeploy_python-1.0.1-cp38-cp38-win_amd64.whl
系统平台:Windows x64(Windows10)
硬件： 如 Nvidia GPU 3070TI， CUDA 11.6 CUDNN 8.5
编译语言： Python 3.8

## 问题描述
使用相同的权重，使用PaddleOCR推理能够正确识别车牌；
而通过fastdeploy识别错误。

## fastdeploy测试脚本：

import fastdeploy as fd
from fastdeploy import ModelFormat
import cv2
import numpy as np
import time

g_ocr1 = None
drop_score = 0.1

class Ocr1Trt:
    def __init__(self, enable_f16=False):

        self.det_model_file  = 'weights/chepai_det_serv_infer/inference.pdmodel'
        self.det_params_file = 'weights/chepai_det_serv_infer/inference.pdiparams'
        self.det_trt_file    = 'weights/chepai_det_serv_infer/chepai_det_serv_infer.trt'
        self.rec_model_file  = 'weights/chepai_rec_infer/inference.pdmodel'
        self.rec_params_file = 'weights/chepai_rec_infer/inference.pdiparams'
        self.rec_trt_file    = 'weights/chepai_rec_infer/chepai_rec_infer.trt'

        option_det = fd.RuntimeOption()
        gpuid = 0
        option_det.use_gpu(gpuid)
        option_det.use_trt_backend() # TensorRT
        if enable_f16:
            option_det.enable_trt_fp16()
        option_det.set_trt_cache_file(self.det_trt_file)
        option_det.set_trt_input_shape("x", [1, 3, 64, 64], [1, 3, 960, 960], [1, 3, 1920, 1920])

        t1 = time.time()
        self.det_model = fd.vision.ocr.DBDetector(
            model_file=self.det_model_file, 
            params_file=self.det_params_file, 
            runtime_option=option_det, model_format=ModelFormat.PADDLE)
        self.det_model.preprocessor.max_side_len = 960  # 960  # 1600
        print('ocr1 det_model:', self.det_model, (time.time() - t1))

        option_rec = fd.RuntimeOption()
        print('ocr_1_rec use_gpuid:'+str(gpuid))
        option_rec.use_gpu(gpuid)
        option_rec.use_trt_backend() # TensorRT
        if enable_f16:
            option_rec.enable_trt_fp16()
        option_rec.set_trt_cache_file(self.rec_trt_file)
        option_rec.set_trt_input_shape("x", [1, 3, 48, 10], [10, 3, 48, 320],  [128, 3, 48, 2304])
        t1 = time.time()
        self.rec_model = fd.vision.ocr.Recognizer(
            model_file=self.rec_model_file, 
            params_file=self.rec_params_file, 
            label_path='weights/dict/ppocr_keys_v1.txt',
            runtime_option=option_rec, model_format=ModelFormat.PADDLE)
        print('ocr1 rec_model:', self.rec_model, (time.time() - t1))

        self.g_model = fd.vision.ocr.PPOCRv3(det_model=self.det_model, cls_model=None, rec_model=self.rec_model)
        print('ocr1_model:', self.g_model)

    def ocr(self, img:np.ndarray, cls=False):
        result = self.g_model.predict(img)
        reses = []
        step = 2
        for conf,txt,box in zip(result.rec_scores, result.text, result.boxes):
            if conf < drop_score:
                continue
            box = [box[i:i+step] for i in range(0,len(box),step)]
            reses.append((box, (txt, conf)))
        return reses

def get_ocr1():
    global g_ocr1
    if g_ocr1:
        return g_ocr1
    
    g_ocr1 = Ocr1Trt(enable_f16=True)
    return g_ocr1

if __name__ == "__main__":
    fname = 'imgs/__truck.jpg'
    # fname = 'imgs/__crop1.jpg'
    img1 = cv2.imdecode(np.fromfile(fname, dtype=np.uint8), cv2.IMREAD_COLOR)

    result1 = get_ocr1().ocr(img1, cls=False)
    print('result1:', result1)

## PaddleOCR测试脚本：
import cv2
import numpy as np
from paddleocr import PaddleOCR

g_ocr1 = None

def get_ocr1():
    global g_ocr1
    if g_ocr1:
        return g_ocr1
    
    g_ocr1 = PaddleOCR(use_angle_cls=False, lang="ch", drop_score=0.1,
        det_model_dir='weights/chepai_det_serv_infer',
        rec_model_dir='weights/chepai_rec_infer',
        det_limit_side_len=960)

    return g_ocr1

if __name__ == "__main__":
    fname = 'imgs/__truck.jpg'
    # fname = 'imgs/__crop1.jpg'        # 检测出为None
    img1 = cv2.imdecode(np.fromfile(fname, dtype=np.uint8), cv2.IMREAD_COLOR)   #BGR

    result1 = get_ocr1().ocr(img1, cls=False)
    print('result1:', result1)

**Comment by yunyaoXYY** [comment]
你好，能把你那边的，FastDeploy和PaddleOCR的识别结果都发出来看一下吗

**Comment by yz2yz** [comment]
@yunyaoXYY ，上传到云盘了，请看下，我刚试过，FastDeploy和PaddleOCR的识别结果是不同的：

链接：https://pan.baidu.com/s/1YZQDSTY7N1DXcvDxgKBMOQ 
提取码：cf9j

**Comment by yunyaoXYY** [comment]
> @yunyaoXYY ，上传到云盘了，请看下，我刚试过，FastDeploy和PaddleOCR的识别结果是不同的：
> 
> 链接：https://pan.baidu.com/s/1YZQDSTY7N1DXcvDxgKBMOQ 提取码：cf9j

这是我用PaddleOCR,分别跑 truck和crop的结果，好像也没有识别出来，并没有复现出你截图的结果呢...

<img width="1263" alt="image" src="https://user-images.githubusercontent.com/109218879/208340574-760d7cbf-028f-40fc-8b07-b273453ccd64.png">

**Comment by yz2yz** [comment]
@yunyaoXYY 您好，我这边根据数据集做了训练，请用weights文件里的chepai_det_serv_infer和chepai_rec_infer来试一下；我这边不是用paddleocr里官方预训练模型的。谢谢！

**Comment by yunyaoXYY** [comment]
> @yunyaoXYY 您好，我这边根据数据集做了训练，请用weights文件里的chepai_det_serv_infer和chepai_rec_infer来试一下；我这边不是用paddleocr里官方预训练模型的。谢谢！

你好，我复现出你的问题了，PaddleOCR的C++版本和FastDeploy的结果是一样的，但是PaddleOCR的Python版本看起来才是更正确的结果. 原因是Python版本用到的各种库和C++的并不完全一样，所以造成了这种差异.

**Comment by maobaoqi** [comment]
我用fastdeploy例子用的OCRv3测试，识别结果比飞桨在线测试结果要差很多

**Comment by yunyaoXYY** [comment]
> 我用fastdeploy例子用的OCRv3测试，识别结果比飞桨在线测试结果要差很多

你好，
你用的是哪个版本的FastDeploy呢，
你说的『飞桨在线测试』是什么代码呢，
两者的输入图片，和识别结果能贴出来一下吗~？

**Comment by maobaoqi** [comment]
> > 我用fastdeploy例子用的OCRv3测试，识别结果比飞桨在线测试结果要差很多
> 
> 你好， 你用的是哪个版本的FastDeploy呢， 你说的『飞桨在线测试』是什么代码呢， 两者的输入图片，和识别结果能贴出来一下吗~？

我使用的是fastdeploy1.0.1这个版本，测试使用的是example中PP-OCRv3代码，模型用的是ch_PP_OCRv3。昨晚测试发现，更改backend为ort时，效果会好不少。

**Comment by yunyaoXYY** [comment]
> > > 我用fastdeploy例子用的OCRv3测试，识别结果比飞桨在线测试结果要差很多
> > 
> > 
> > 你好， 你用的是哪个版本的FastDeploy呢， 你说的『飞桨在线测试』是什么代码呢， 两者的输入图片，和识别结果能贴出来一下吗~？
> 
> 我使用的是fastdeploy1.0.1这个版本，测试使用的是example中PP-OCRv3代码，模型用的是ch_PP_OCRv3。昨晚测试发现，更改backend为ort时，效果会好不少。

那之前是哪个backend比较差呢？是paddle吗
如果是的话，意味着都用FastDeploy，ORT后端效果比Paddle好？
如果是的话，能否发一个预测图片呢

**Comment by laugh12321** [comment]
我这边用PPVehicle的车牌识别模型，在pipline上测试3张图片，全部检测正确。但是在FastDeploy上只检测正确一次，其中两次连车牌都没有检测上。尝试各种后端都一样。
![4951abed976500ad1739bd532c10509a_](https://user-images.githubusercontent.com/38065710/233531805-f150cb09-1996-4a22-b2bb-4f0ef0a9db9a.png)
![image](https://user-images.githubusercontent.com/38065710/233531839-24149a46-6ef9-4558-8ff8-466d6ec6e8c2.png)
