### ISSUE TITLE
每次在预测之前，都要初始化一下模型，导入模型文件，这个过程很慢。能不能程序初始化只导入一次

### ISSUE THREAD

**Issue by gllm126** [PaddlePaddle/FastDeploy#908]
## 环境

- FastDeploy版本： 说明具体的版本，如fastdeploy-windows-cpu-1.0
- 如果您是自行编译的FastDeploy，请说明您的编译方式（参数命令）
- 系统平台: Windows x64(Windows10)
- 硬件： Cpu
- 编译语言： C++ 

## 问题描述
以OCRv3为例：
	auto det_model = fastdeploy::vision::ocr::DBDetector(det_model_file, det_params_file, option);
	auto cls_model = fastdeploy::vision::ocr::Classifier(cls_model_file, cls_params_file, option);
	auto rec_model = fastdeploy::vision::ocr::Recognizer(rec_model_file, rec_params_file, rec_label_file, option);

	auto ppocr_v3 = fastdeploy::pipeline::PPOCRv3(&det_model, &cls_model, &rec_model);
每次在PPOCRv3预测之前必须对以上3个模型进行初始化，否则会崩。我的本意是：在程序初始化时只初始化一次这些模型文件，预测时，直接调用PPOCRv3即可。

**Comment by yz2yz** [comment]
是需要设置下RuntimeOption的SetTrtCacheFile吗？

**Comment by jiangjiajun** [comment]
你是指TensorRT加载慢，想提升初始化的速度。 还是指想通过一行代码初始PPOCRv3?

**Comment by gllm126** [comment]
每次预测时：都要调用以下3个语句，这3个语句是从文件读入模型，是IO操作，慢啊。我的理解，程序初始化运动一次，就可了，为什么每次预测都要导入模型文件？
auto det_model = fastdeploy::vision::ocr::DBDetector(det_model_file, det_params_file, option);
auto cls_model = fastdeploy::vision::ocr::Classifier(cls_model_file, cls_params_file, option);
auto rec_model = fastdeploy::vision::ocr::Recognizer(rec_model_file, rec_params_file, rec_label_file, option);

**Comment by gllm126** [comment]
如果在程序初始化只运行一次（导入模型的操作，即上述3行代码），第一次预测没问题，第二次程序会崩。

**Comment by jiangjiajun** [comment]
```
	auto det_model = fastdeploy::vision::ocr::DBDetector(det_model_file, det_params_file, option);
	auto cls_model = fastdeploy::vision::ocr::Classifier(cls_model_file, cls_params_file, option);
	auto rec_model = fastdeploy::vision::ocr::Recognizer(rec_model_file, rec_params_file, rec_label_file, option);

	auto ppocr_v3 = fastdeploy::pipeline::PPOCRv3(&det_model, &cls_model, &rec_model);
```

上面这四行，本身确实只用运行一次。后面你可以反复调用`ppocr_v3`这个实例，例如
```
for (int i = 0; i < 1000; ++i) {
  cv::Mat im = cv::imread("test.jpg");
  fastdeploy::vision::OCRResult result;
  ppocr_v3.Predict(im, &results);
}
```

**Comment by szufafa** [comment]
这应该可以用智能指针和动态内存的方法解决
我自己编写了一个初始化和预测的调用方式
你如果有需要可以参考 亲测可用
```
void create_detector(std::shared_ptr<void>* c_detector_ptr, char const* mode_path) {
    *c_detector_ptr = std::make_shared<fastdeploy::vision::detection::YOLOv5>(mode_path);
}

void delete_detector(std::shared_ptr<void>  c_detector_ptr) { c_detector_ptr.reset(); }

bbox_t* detect_custom(std::shared_ptr<void>  c_detector_ptr, cv::Mat img ,int *nbox) {

    fastdeploy::vision::DetectionResult res;

    bool ai = static_cast<fastdeploy::vision::detection::YOLOv5*> (c_detector_ptr.get())->Predict(&img,&res);
    if (!ai) {
        std::cerr << "Failed to predict." << std::endl;
        return NULL;
    }
    std::cout << res.Str() << std::endl;
}
```

**Comment by jiangjiajun** [comment]
此ISSUE由于一年未更新，将会关闭处理，如有需要，可再次更新打开。
