### ISSUE TITLE
vs2019跑Release模式可以跑通，Debug模式就会报错

### ISSUE THREAD

**Issue by alfheim1993** [PaddlePaddle/FastDeploy#923]
## 环境

- FastDeploy版本： fastdeploy-win-x64-gpu-1.0.1
- 系统平台:  Windows x64(Windows10) 
- 硬件： Nvidia GPU 2080TI， CUDA 11.2 CUDNN 8.3
- 编译语言： C++ 

## 问题描述
- Release模式可以跑通，Debug模式就会报错，有包含opencv的debug库opencv_world3416d.dll
![image](https://user-images.githubusercontent.com/59383646/208615541-edaa2fe4-c651-43fd-aa34-78de9813f9e1.png)

**Comment by jiangjiajun** [comment]
目前没有支持Debug模式

**Comment by alfheim1993** [comment]
好吧，这样调试起来比较麻烦，希望可以支持debug模式，感谢回复
