### ISSUE TITLE
[ERROR] Paddle2ONNX: Only support weight with lod_level = 0.

### ISSUE THREAD

**Issue by zhuqiang00099** [PaddlePaddle/FastDeploy#925]
## 环境

- FastDeploy版本： jetson自行编译
- 系统平台: jetpack 4.6.1   
- 硬件： jetson nano 4GB
- 编译语言： C++

## 问题描述
- 模型部署出错
- - 使用的是paddledetection2.4导出的picodet-m-320模型，类别数为2，导出的时候没有去掉NMS，就是很淳朴的导出。然后准备用trt推理，就报下面的错了。

*********************************************
[INFO] fastdeploy/vision/common/processors/transform.cc(159)::FuseNormalizeColorConvert BGR2RGB and Normalize are fused to Normalize with swap_rb=1
[ERROR] Paddle2ONNX: Only support weight with lod_level = 0.
Aborted (core dumped)

**Comment by gl94** [comment]
去掉nms就可以了
