### ISSUE TITLE
使用onnxruntime推理和fastdeploy推理同一个onnx模型，结果出现比较大的偏差

### ISSUE THREAD

**Issue by xxjordan** [PaddlePaddle/FastDeploy#933]
## 环境

- FastDeploy版本： fastdeploy-gpu-python              0.5.0
- 系统平台:Windows x64(Windows11) 
- 硬件： rtx3060ti
- 编译语言： Python3.9.7

## 问题描述
使用相同数据经过相同的处理方式，输入到onnexruntime和fastdeploy，最终结果出来有非常大的偏差，onnxruntime的结果没问题，但是fastdeploy基本就是不可用的结果
![2](https://user-images.githubusercontent.com/38773954/208836080-787218a1-1d60-4bb4-bc0a-d91b9498171c.png)
这张是onnxruntime推理的结果
![1](https://user-images.githubusercontent.com/38773954/208836139-c757e1fe-5174-4cd8-82f2-3679cb1bc113.png)
这张是fastdeploy的结果

代码、模型和数据在这里
链接：https://pan.baidu.com/s/1YjpzENl_OdsfHof0qzZABw
提取码：v3lo

**Comment by xxjordan** [comment]
代码、模型和数据在这里
链接：https://pan.baidu.com/s/1YjpzENl_OdsfHof0qzZABw 
提取码：v3lo

**Comment by Zheng-Bicheng** [comment]
我有个疑惑，为什么你要用fd当成推理引擎来用。这两个东西的定位应该是不一致的呀。

**Comment by xxjordan** [comment]
> 我有个疑惑，为什么你要用fd当成推理引擎来用。这两个东西的定位应该是不一致的呀。

我的概念里面fastdeploy不就应该是一个用于部署的推理引擎吗？

**Comment by Zheng-Bicheng** [comment]
> > 我有个疑惑，为什么你要用fd当成推理引擎来用。这两个东西的定位应该是不一致的呀。
> 
> 我的概念里面fastdeploy不就应该是一个用于部署的推理引擎吗？

FastDeploy类似一个推理工具。区别类似于，onnxruntime输入一张图片，得到的是模型的推理结果。fastdeploy输入一张图片，得到的是经过后处理之后的图片。

**Comment by xxjordan** [comment]
> 

哦哦，我才接触fd不久，没有做更深的研究，只是想试试用这个部署一个模型，目前就遇到这个麻烦

**Comment by xxjordan** [comment]
> > > 我有个疑惑，为什么你要用fd当成推理引擎来用。这两个东西的定位应该是不一致的呀。
> > 
> > 
> > 我的概念里面fastdeploy不就应该是一个用于部署的推理引擎吗？
> 
> FastDeploy类似一个推理工具。区别类似于，onnxruntime输入一张图片，得到的是模型的推理结果。fastdeploy输入一张图片，得到的是经过后处理之后的图片。

哦哦，我才接触fd不久，没有做更深的研究，只是想试试用这个部署一个模型，目前就遇到这个麻烦

**Comment by jiangjiajun** [comment]
@xxjordan 这个是一个已知的问题。我注意到你在使用0.5的fastdeploy，改成1.0.1的即可解决， 参考这个issue的说明 https://github.com/PaddlePaddle/FastDeploy/issues/685#issuecomment-1325970251

**Comment by xxjordan** [comment]
> @xxjordan 这个是一个已知的问题。我注意到你在使用0.5的fastdeploy，改成1.0.1的即可解决， 参考这个issue的说明 [#685 (comment)](https://github.com/PaddlePaddle/FastDeploy/issues/685#issuecomment-1325970251)

好的，多谢，问题已解决
