### ISSUE TITLE
rknn example里面infer_picodet.cc用到 deploy.yaml 找不到

### ISSUE THREAD

**Issue by pengwei1024** [PaddlePaddle/FastDeploy#937]
*********************************************
开源不易，工程师每天有大量研发工作，请直接按此issue模版进行提问

这会大大减少工程师与你确认使用环境，编译过程中的基础信息时间
*********************************************

## 环境
- FastDeploy版本： 说明具体的版本，如fastdeploy-linux-gpu-0.8.0
- 如果您是自行编译的FastDeploy，请说明您的编译方式（参数命令）
- 系统平台: Linux x64(Ubuntu 18.04) / Windows x64(Windows10) / Mac OSX arm(12.0) / Mac OSX intel(12.0)
- 硬件： 说明具体硬件型号，如 Nvidia GPU 3080TI， CUDA 11.2 CUDNN 8.3
- 编译语言： C++ / Python(3.7或3.8等）

## 问题描述
这个文件用onnx 推理用到了 deploy.yaml  文件找不到，运行报错
[infer_picodet.cc](https://github.com/PaddlePaddle/FastDeploy/blob/develop/examples/vision/detection/paddledetection/rknpu2/cpp/infer_picodet.cc)
infer_cfg.yml 是有的，把代码里面 deploy.yaml  路径换成 infer_cfg.yml  也是直接报错的
请问去哪能生成 deploy.yaml   ？

**Comment by Zheng-Bicheng** [comment]
不好意思，应该是infer_cfg.yml的。换成infer_cfg.yml后报什么错误呢

**Comment by Zheng-Bicheng** [comment]
已经修复这个问题

**Comment by pengwei1024** [comment]
已在官方的支持下解决，👍！

1、直接使用 infer_cfg.yml ，配置项加上  ` - type: Permute `
2、注释掉:   model.GetPostprocessor().ApplyDecodeAndNMS();
