### ISSUE TITLE
能否支持下paddlespeech的语音识别功能

### ISSUE THREAD

**Issue by jackyzjk** [PaddlePaddle/FastDeploy#942]
能否支持下paddlespeech的语音识别功能，要是能在端上部署那就更好了

**Comment by leiqing1** [comment]
@jackyzjk 请问具体是什么端上？arm cpu还是其他什么端侧设备？

**Comment by DefTruth** [comment]
@jackyzjk 请问具体比较关注paddlespeech中的哪些模型呢？

**Comment by jackyzjk** [comment]
> @jackyzjk 请问具体是什么端上？arm cpu还是其他什么端侧设备？

边缘计算端，使用arm cpu，cpu型号RK3588

**Comment by jackyzjk** [comment]
> @jackyzjk 请问具体比较关注paddlespeech中的哪些模型呢？

conformer_aishell和deepspeech2offline_aishell

**Comment by jiangjiajun** [comment]
此ISSUE由于一年未更新，将会关闭处理，如有需要，可再次更新打开。
