### ISSUE TITLE
paddle-js-models/ocr 引用问题

### ISSUE THREAD

**Issue by f13800138001** [PaddlePaddle/FastDeploy#946]
## 环境

 Windows x64(Windows10) /VUE 2.6/EDEG/

## 问题描述
vue2环境中引用npm包组件
import * as ocr from '@paddle-js-models/ocr'
提示下面的报错信息，是不支持vue2使用吗？
![image](https://user-images.githubusercontent.com/98594539/209064281-3c8333fd-2ec5-45d7-b5af-97462feadfef.png)

**Comment by chrispavs** [comment]
I'm having the same issue. Did you find a solution for this?

对不起，我不会说中文。我有同样的问题。你找到解决办法了吗？
