### ISSUE TITLE
使用ppocrv3进行cpp下的推理时，返回的result.text中的结果存在问题

### ISSUE THREAD

**Issue by jasper-cell** [PaddlePaddle/FastDeploy#947]
## 环境

- FastDeploy版本： fastdeploy-linux-gpu-0.8.0
- 系统平台: Linux x64(Ubuntu 18.04) 
- 硬件：如 Nvidia GPU 3080TI， CUDA 11.2 CUDNN 8.3
- 编译语言： C++

得到ppocrv3的推理结果后，该result.text是可以正常存储下来。
但是无法输出到终端进行完整的显示，而且使用opencv绘制到图像上每个字符间出现问号？
![image](https://user-images.githubusercontent.com/54393886/209069686-e9067eff-9050-4519-b2cb-278f497cf53a.png)
请问如何才能正常对该结果字符串进行显示呢？

**Comment by yunyaoXYY** [comment]
> ## 环境
> * FastDeploy版本： fastdeploy-linux-gpu-0.8.0
> * 系统平台: Linux x64(Ubuntu 18.04)
> * 硬件：如 Nvidia GPU 3080TI， CUDA 11.2 CUDNN 8.3
> * 编译语言： C++
> 
> 得到ppocrv3的推理结果后，该result.text是可以正常存储下来。 但是无法输出到终端进行完整的显示，而且使用opencv绘制到图像上每个字符间出现问号？ ![image](https://user-images.githubusercontent.com/54393886/209069686-e9067eff-9050-4519-b2cb-278f497cf53a.png) 请问如何才能正常对该结果字符串进行显示呢？

之前的版本, 识别模型有点问题， 先把0.8.0版本的换成 develop版本的试试.

**Comment by jiangjiajun** [comment]
这个其实都是编码的影响。 如何输出到屏幕，受限于终端输出对编译的配置。 如何通过opencv可视化出来，也是一样（opencv对中文字符支持确实不太好）

**Comment by jiangjiajun** [comment]
此ISSUE由于一年未更新，将会关闭处理，如有需要，可再次更新打开。
