### ISSUE TITLE
FastDeploy连续Infer同一张图100次,显存增长到4G,不释放问题。

### ISSUE THREAD

**Issue by shengzhe8688** [PaddlePaddle/FastDeploy#952]
*********************************************
支持飞桨的用户和程序员们也很不容易,也是一个帮助飞桨成长的过程,希望官方的大佬们能够认真对待、客观回答、直面问题，给出有效的解决方案、不逃避问题、不搪塞用户、不辜负众多支持飞桨的码农们。
*********************************************

## 环境

- FastDeploy版本： fastdeploy-linux-gpu-1.0.1 使用预编译库文件
- 测试程序：使用预编译库文件中的Demo,路径为：fastdeploy-linux-x64-gpu-1.0.1/examples/vision/ocr/PP-OCRv3/cpp/infer.cc
- 系统平台: Linux x64(Ubuntu 18.04) 
- 硬件：  Nvidia GPU 3060TI CUDA 11.2 CUDNN  8.1.1.33
- 编译语言： C++ / Python(3.7或3.8等）

## 问题描述
- **说明：** 我们项目中之前使用PaddleOCR因存在显存不释放问题，没有解决方案的情况下，使用FastDeploy试水，没想到FastDeploy也存在同样的问题。
- **具体问题：**
  1.同一张图片在循环infer1000次的情况下，内存占用4G不进行释放。请问显存的管理机制和释放机制是什么？为什么不自动释放？如果不支持自动释放？如何手动释放？
  2.fastDeploy是否支持多线程并行推理？支持的话Demo在哪儿或者如何实现？
-  **使用代码：** fastdeploy-linux-x64-gpu-1.0.1/examples/vision/ocr/PP-OCRv3/cpp/infer.cc
-  **测试方式：** 修改代码增加推理时间，在执行循环1000次推理，推理结束增加10s延时观察显存变化，并使用nvtop工具观察显存占用变化，发现推理完成、10s延时后内存并没有释放。
-  **截图：** 
![image](https://user-images.githubusercontent.com/16428236/209087186-c61ecb74-c60c-4d59-b94f-1c1e33fd3af1.png)

推理效果还是不错的,就是显存占用不释放。

![image](https://user-images.githubusercontent.com/16428236/209087064-c05816ab-50fc-47b6-8bb4-44af9f7e8c5a.png)

-  **使用代码:** 
 ```
  auto det_model = fastdeploy::vision::ocr::DBDetector(det_model_file, det_params_file, det_option);
  auto cls_model = fastdeploy::vision::ocr::Classifier(cls_model_file, cls_params_file, cls_option);
  auto rec_model = fastdeploy::vision::ocr::Recognizer(rec_model_file, rec_params_file, rec_label_file, rec_option);

  std::cout << "fastdeploy::vision::ocr init create complete!" << std::endl;


  assert(det_model.Initialized());
  assert(cls_model.Initialized());
  assert(rec_model.Initialized());

  // The classification model is optional, so the PP-OCR can also be connected in series as follows
  // auto ppocr_v3 = fastdeploy::pipeline::PPOCRv3(&det_model, &rec_model);
  std::cout << "fastdeploy::pipeline::PPOCRv3  complete!" << std::endl;
  //auto ppocr_v3 = fastdeploy::pipeline::PPOCRv3(&det_model, &cls_model, &rec_model);
  auto ppocr_v3 = fastdeploy::pipeline::PPOCRv3(&det_model, &rec_model);

  if(!ppocr_v3.Initialized()){
    std::cerr << "Failed to initialize PP-OCR." << std::endl;
    return;
  }

  auto im = cv::imread(image_file);

  fastdeploy::vision::OCRResult result;
  int num=1000;
  while (--num >0)
  {
    auto im_bak = im.clone();

    std::cout << "start detect!" << std::endl;
    auto start_time = std::chrono::system_clock::now();
    result.Clear();
    if (!ppocr_v3.Predict(&im, &result))
    {
      std::cerr << "Failed to predict." << std::endl;
      return;
    }

    std::cout << result.Str() << std::endl;
    float dt1 = std::chrono::duration_cast<std::chrono::milliseconds>(std::chrono::system_clock::now() - start_time).count();
    std::cout << "get plateNumber total time:" << dt1 << std::endl;
  }
  sleep(20);
  // auto vis_im = fastdeploy::vision::VisOcr(im_bak, result);
  // cv::imwrite("vis_result.jpg", vis_im);
  // std::cout << "Visualized result saved in ./vis_result.jpg" << std::endl;
```

- 附上详细的问题日志有助于工程师快速定位分析
- 性能问题，描述清楚对比的方式
- - 注意性能测试，循环跑N次，取后80%的用时平均（模型启动时，刚开始受限于资源分配，速度会较慢）
- - FastDeploy的Predict包含模型本身之外的数据前后处理用时
- 模型部署出错
- - 先执行`examples`下的部署示例，包括使用examples提供的模型，确认是否可以正确执行
- - 如若`examples`下的代码可以运行，但自己的模型，或自己的代码不能运行
- - - 提供自己的代码使用方式或自己的模型，供工程师快速定位问题

*********************************************
开源不易，工程师每天有大量研发工作，请直接按此issue模版进行提问

这会大大减少工程师与你确认使用环境，编译过程中的基础信息时间
*********************************************

**Comment by leiqing1** [comment]
@shengzhe8688 你好 shengzhe。请问你的问题解决了吗？是什么原因呢？

**Comment by dzz10** [comment]
@leiqing1 @shengzhe8688 你好,请问你的问题解决了吗？是什么原因呢？
