### ISSUE TITLE
我就想问多线程并行推理怎么做？

### ISSUE THREAD

**Issue by shengzhe8688** [PaddlePaddle/FastDeploy#956]
*********************************************
开源不易，工程师每天有大量研发工作，请直接按此issue模版进行提问

这会大大减少工程师与你确认使用环境，编译过程中的基础信息时间
*********************************************

## 环境

- FastDeploy版本： 说明具体的版本，如fastdeploy-linux-gpu-0.8.0
- 如果您是自行编译的FastDeploy，请说明您的编译方式（参数命令）
- 系统平台: Linux x64(Ubuntu 18.04) / Windows x64(Windows10) / Mac OSX arm(12.0) / Mac OSX intel(12.0)
- 硬件： 说明具体硬件型号，如 Nvidia GPU 3080TI， CUDA 11.2 CUDNN 8.3
- 编译语言： C++ / Python(3.7或3.8等）

## 问题描述
**我就想问多线程并行推理怎么做？**
- 附上详细的问题日志有助于工程师快速定位分析
- 性能问题，描述清楚对比的方式
- - 注意性能测试，循环跑N次，取后80%的用时平均（模型启动时，刚开始受限于资源分配，速度会较慢）
- - FastDeploy的Predict包含模型本身之外的数据前后处理用时
- 模型部署出错
- - 先执行`examples`下的部署示例，包括使用examples提供的模型，确认是否可以正确执行
- - 如若`examples`下的代码可以运行，但自己的模型，或自己的代码不能运行
- - - 提供自己的代码使用方式或自己的模型，供工程师快速定位问题

*********************************************
开源不易，工程师每天有大量研发工作，请直接按此issue模版进行提问

这会大大减少工程师与你确认使用环境，编译过程中的基础信息时间
*********************************************

**Comment by jiangjiajun** [comment]
https://github.com/PaddlePaddle/FastDeploy/tree/develop/tutorials/multi_thread 这里提供了多线程示例，目前支持了PaddleDetection、PaddleSeg、PaddleClas， OCR接下来会支持

**Comment by GeT-RiGhTTT** [comment]
> https://github.com/PaddlePaddle/FastDeploy/tree/develop/tutorials/multi_thread 这里提供了多线程示例，目前支持了PaddleDetection、PaddleSeg、PaddleClas， OCR接下来会支持

视频的多线程示例有嘛

**Comment by kFoodie** [comment]
TTS的有吗？

**Comment by jiangjiajun** [comment]
此ISSUE由于一年未更新，将会关闭处理，如有需要，可再次更新打开。
