### ISSUE TITLE
RKNN 不支持分类模型

### ISSUE THREAD

**Issue by pengwei1024** [PaddlePaddle/FastDeploy#957]
*********************************************
开源不易，工程师每天有大量研发工作，请直接按此issue模版进行提问

这会大大减少工程师与你确认使用环境，编译过程中的基础信息时间
*********************************************

## 环境

- FastDeploy版本： 最新版本
- 如果您是自行编译的FastDeploy，请说明您的编译方式（参数命令）
- 系统平台: Linux x64(Ubuntu 18.04) 
- 硬件： 说明具体硬件型号，如 RKNN3588
- 编译语言： C++ + Python 都想支持 

## 问题描述
- AssertionError: PaddleClasModel only support model format of ModelFormat.PADDLE now.
- 先支持下常用的 PPLCNet、PPLCNetv2、MobileNetv3、PPHGNet 等

**Comment by leiqing1** [comment]
@pengwei1024 我们正在支持中，也欢迎提pr一起来建设。

**Comment by Zheng-Bicheng** [comment]
开发者已经提PR自行解决，感谢这位开发者贡献的代码
