### ISSUE TITLE
How to customize the dependency environment of FastDeploy

### ISSUE THREAD

**Issue by geekchen007** [PaddlePaddle/FastDeploy#965]
## 问题描述
FastDeploy是一个很优秀的部署工具，在使用过程中对比之前的依赖管理，有以下疑问：
1）之前的部署策略是依赖的后端用什么，依赖环境就装什么。比如单独装onnx。但是现在fastdeploy“支持CPU和Nvidia GPU的部署，默认集成Paddle Inference、ONNX Runtime、OpenVINO以及TensorRT推理后端，Vision视觉模型模块，Text文本NLP模型模块”，这在测试开发阶段很方便，但是实际部署后，是否存在依赖环境冗余？

2）默认集成Paddle Inference、ONNX Runtime、OpenVINO以及TensorRT推理后端，Vision视觉模型模块，Text文本NLP模型模块的相关代码可以定制化裁剪吗？

参考依赖说明
https://github.com/PaddlePaddle/FastDeploy/blob/develop/docs/cn/build_and_install/download_prebuilt_libraries.md#1

![image](https://user-images.githubusercontent.com/9989714/209456445-7eec481e-28d8-488c-b570-2db4186e57f9.png)

**Comment by geekchen007** [comment]
相关代码在这FastDeploy/build_gpu.sh at develop · PaddlePaddle/FastDeploy
https://github.com/PaddlePaddle/FastDeploy/blob/develop/python/scripts/build_gpu.sh
```
export ENABLE_ORT_BACKEND=ON
export ENABLE_OPENVINO_BACKEND=ON
export ENABLE_PADDLE_BACKEND=ON
export ENABLE_TRT_BACKEND=ON
export TRT_DIRECTORY=/fastdeploy/libs/TensorRT-8.4.1.5
export CUDA_DIRECTORY=/usr/local/cuda
export ENABLE_VISION=ON
export WITH_GPU=ON
export CMAKE_CXX_COMPILER=/usr/local/gcc-8.2/bin/g++
```

**Comment by jiangjiajun** [comment]
> 相关代码在这FastDeploy/build_gpu.sh at develop · PaddlePaddle/FastDeploy https://github.com/PaddlePaddle/FastDeploy/blob/develop/python/scripts/build_gpu.sh
> 
> ```
> export ENABLE_ORT_BACKEND=ON
> export ENABLE_OPENVINO_BACKEND=ON
> export ENABLE_PADDLE_BACKEND=ON
> export ENABLE_TRT_BACKEND=ON
> export TRT_DIRECTORY=/fastdeploy/libs/TensorRT-8.4.1.5
> export CUDA_DIRECTORY=/usr/local/cuda
> export ENABLE_VISION=ON
> export WITH_GPU=ON
> export CMAKE_CXX_COMPILER=/usr/local/gcc-8.2/bin/g++
> ```

对的，可在这里自行根据选择编译

**Comment by jiangjiajun** [comment]
此ISSUE由于一年未更新，将会关闭处理，如有需要，可再次更新打开。
