### ISSUE TITLE
在rk3568板子上由于内存不足无法编译fastdeploy包，希望可以帮忙编译一个cp37m的，多谢

### ISSUE THREAD

**Issue by Rsndmmm** [PaddlePaddle/FastDeploy#969]
*********************************************
温馨提示：根据社区不完全统计，按照模板提问，可以加快回复和解决问题的速度
*********************************************

## 环境

- 【FastDeploy版本】： git上最新版本
- 【编译命令】
export ENABLE_ORT_BACKEND=ON
export ENABLE_RKNPU2_BACKEND=ON
export ENABLE_VISION=ON
export RKNN2_TARGET_SOC=RK3588
python3 setup.py build
python3 setup.py bdist_wheel
- 【系统平台】: Linux aarch64(FriendlyElec 5.10.110)
- 【硬件】： rk3568
- 【编译语言】： Python(3.7）

## 问题日志及出现问题的操作流程
编译时卡住不动

**Comment by Zheng-Bicheng** [comment]
链接: https://pan.baidu.com/s/1oWeAKRENy6lJNDYssUPcOQ?pwd=t6vi 提取码: t6vi 
--来自百度网盘超级会员v5的分享

**Comment by Zheng-Bicheng** [comment]
群里或者百度网盘都可以下载

**Comment by hjshd** [comment]
> 链接: https://pan.baidu.com/s/1oWeAKRENy6lJNDYssUPcOQ?pwd=t6vi 提取码: t6vi --来自百度网盘超级会员v5的分享

前辈，链接过期了，可以在分享一下吗？？
