### ISSUE TITLE
请问是否支持paddle inference 的多线程并发部署和调用？

### ISSUE THREAD

**Issue by Tian14267** [PaddlePaddle/FastDeploy#971]
大神们好。我想问下，fastdeploy是否支持paddle  inference 的多线程并发部署和调用？
想使用的项目：PaddleSpeech 中的 ASR 部署。希望能够支持多线程并发

**Comment by jiangjiajun** [comment]
如果你是直接使用FastDeploy里面的Runtime， 现在是支持的。用法与Paddle Inference类似，先创建一个`Runtime`实例，再通过调用`Clone`接口得到新的实例（与原实例共享内存），然后给不用的线程使用


@felixhjh 我们在`tutorials/multi_thread`下同样提供一个runtime的多线程示例吧

**Comment by Tian14267** [comment]
> 如果你是直接使用FastDeploy里面的Runtime， 现在是支持的。用法与Paddle Inference类似，先创建一个`Runtime`实例，再通过调用`Clone`接口得到新的实例（与原实例共享内存），然后给不用的线程使用
> 
> @felixhjh 我们在`tutorials/multi_thread`下同样提供一个runtime的多线程示例吧

好的非常感谢

**Comment by jiangjiajun** [comment]
此ISSUE由于一年未更新，将会关闭处理，如有需要，可再次更新打开。
