### ISSUE TITLE
使用gRPC Python部署PPOCRv3推理服务, 推理报错

### ISSUE THREAD

**Issue by miknyko** [PaddlePaddle/FastDeploy#972]
## 问题描述
你好, 我们使用gRPC Python搭建PPOCRV3服务端的时候, 会遭遇`Segmentation Fault`

## 环境

- 【FastDeploy版本】： `fastdeploy-gpu-python==1.0.1`  `grpcio==1.51.1` 
- 【编译命令】wheel安装
- 【系统平台】: Linux x64(Ubuntu 18.04) 
- 【硬件】： Nvidia T4
- 【编译语言】： python==3.7

## 问题日志

1. 使用gRPC Python搭建OCR推理服务端, 当RPC方法中运行`fastdeploy.vision.ocr.PPOCRv3.predict(image)`时, 此时服务端进程会报`Segmentation Fault(Core dumped)`
2. 尝试使用了不同的推理`backend`, 包括`openvino`, `onnx`, `cpu`, `gpu`, 都一定会出现
3. 尝试单独启动模型, 测试没有问题, 只有当在gRPC方法中调用时, 会出现此问题
4. 在此语句处替换成其他模型, 如`Yolov7`, 不会出现该错误, 推理正常完成.

**Comment by jiangjiajun** [comment]
我们已经提供了一个轻量级的Python服务化部署（基于FastAPI），你可以直接试用下哈。 目前提供了PaddleDetection的示例（需要安装nightly build版本的fastdeploy） https://github.com/PaddlePaddle/FastDeploy/tree/develop/examples/vision/detection/paddledetection/python/serving

**Comment by miknyko** [comment]
我们的服务都是用GRPC的, RESTFUL性能要差很多.

**Comment by wang-xinyu** [comment]
@miknyko 也可以尝试FastDeploy的Triton serving方案：https://github.com/PaddlePaddle/FastDeploy/blob/develop/examples/vision/ocr/PP-OCRv3/serving/README.md

目前FastDeploy提供了两套serving：
- Triton serving，高并发
- Simple serving，轻量化部署

**Comment by miknyko** [comment]
好的, 谢谢, 我去了解下, 但是也期待你们可以关注下这个问题, 个人认为gRPC的兼容还是挺重要的 😄

**Comment by wang-xinyu** [comment]
@miknyko Triton serving是gRPC的

**Comment by jiangjiajun** [comment]
> 好的, 谢谢, 我去了解下, 但是也期待你们可以关注下这个问题, 个人认为gRPC的兼容还是挺重要的 😄

麻烦提供一个最简单的复现代码和步骤哈

**Comment by jiangjiajun** [comment]
此ISSUE由于一年未更新，将会关闭处理，如有需要，可再次更新打开。
