### ISSUE TITLE
是否有计划提供streamer python API？

### ISSUE THREAD

**Issue by jerryandjune** [PaddlePaddle/FastDeploy#979]
目前看到这个获取RTSP视频流方法，只有C++方式，后续是否有计划提供python API方式？
[streamer](https://github.com/PaddlePaddle/FastDeploy/tree/develop/streamer)

**Comment by wang-xinyu** [comment]
有计划，目前没有确定时间，预计下个月

**Comment by jiangjiajun** [comment]
此ISSUE由于一年未更新，将会关闭处理，如有需要，可再次更新打开。
