### ISSUE TITLE
请问如何串联ch_PP-OCRv3_det_infer和ch_ppocr_mobile_v2.0_rec_infer模型部署呢？

### ISSUE THREAD

**Issue by lilianjie111111** [PaddlePaddle/FastDeploy#980]

**Comment by yunyaoXYY** [comment]
> _No description provided._

为什么会有这样的需求呢, v3的rec模型效果比v2是好的.
如果真想这么做的话，可以使用PP-OCRv2的demo用例，直接把v2的det模型 换成v3的det模型即可

**Comment by jiangjiajun** [comment]
https://github.com/PaddlePaddle/FastDeploy/tree/develop/examples/vision/ocr/PP-OCRv3  参考这个示例中的python或C++，里面有说明cls模型是可选项，可以不用传进去

**Comment by lilianjie111111** [comment]
> 

可是v3是48的，mobilev2是32的，实测下来速度差不少呢

**Comment by lilianjie111111** [comment]
> > _No description provided._
> 
> 为什么会有这样的需求呢, v3的rec模型效果比v2是好的. 如果真想这么做的话，可以使用PP-OCRv2的demo用例，直接把v2的det模型 换成v3的det模型即可

可是v3是48的，mobilev2是32的，实测下来速度差不少呢

**Comment by jiangjiajun** [comment]
此ISSUE由于一年未更新，将会关闭处理，如有需要，可再次更新打开。
