### ISSUE TITLE
解码模块video_decoder解不了rtmp

### ISSUE THREAD

**Issue by intjun** [PaddlePaddle/FastDeploy#989]
配置文件如下：

app:
  type: video_decoder
  enable-perf-measurement: true
  perf-measurement-interval-sec: 5

nvurisrcbin:
  uri: rtmp://localhost:55555/live/0.mp4
  gpu-id: 0

nvvideoconvert:
  gpu-id: 0

capsfilter:
  caps: video/x-raw,format=(string)BGR

appsink:
  sync: true
  max-buffers: 60
  drop: false

运行结果如下：
[INFO] /decode/FastDeploy/streamer/src/gstreamer/utils.cc(60)::CreatePipeline   Trying to launch pipeline: nvurisrcbin uri=rtmp://localhost:55555/live/0.mp4 gpu-id=0 ! nvvideoconvert gpu-id=0 ! capsfilter caps=video/x-raw,format=(string)BGR ! appsink sync=true max-buffers=60 drop=false 
appsink0
appsink0
Running Asynchronous...
一直停止不动。vlc播放器播放这个rtmp流没有问题。

**Comment by wang-xinyu** [comment]
试过视频文件了吗？视频文件是否有问题？

**Comment by lzh1998-jansen** [comment]
> 
app:
  type: video_decoder
  enable-perf-measurement: true
  perf-measurement-interval-sec: 5

nvurisrcbin:
  uri: rtsp://wowzaec2demo.streamlock.net/vod/mp4:BigBuckBunny_115k.mp4
  gpu-id: 1

nvvideoconvert:
  gpu-id: 1

capsfilter:
  caps: video/x-raw,format=(string)BGR

appsink:
  sync: true
  max-buffers: 60
  drop: false
~我试了一下 rtsp，也报错，Running Asynchronous...
ERROR from element aparsebin: Your GStreamer installation is missing a plug-in.
Error details: gstparsebin.c(3486): gst_parse_bin_expose (): /GstPipeline:pipeline0/GstDsNvUriSrcBin:dsnvurisrcbin0/GstParseBin:aparsebin:
no suitable plugins found:
Missing parser: MPEG-4 AAC (audio/mpeg, mpegversion=(int)4, stream-format=(string)raw, codec_data=(buffer)149056e500)

**Comment by lzh1998-jansen** [comment]
> > 
> 
> app: type: video_decoder enable-perf-measurement: true perf-measurement-interval-sec: 5
> 
> nvurisrcbin: uri: rtsp://wowzaec2demo.streamlock.net/vod/mp4:BigBuckBunny_115k.mp4 gpu-id: 1
> 
> nvvideoconvert: gpu-id: 1
> 
> capsfilter: caps: video/x-raw,format=(string)BGR
> 
> appsink: sync: true max-buffers: 60 drop: false ~我试了一下 rtsp，也报错，Running Asynchronous... ERROR from element aparsebin: Your GStreamer installation is missing a plug-in. Error details: gstparsebin.c(3486): gst_parse_bin_expose (): /GstPipeline:pipeline0/GstDsNvUriSrcBin:dsnvurisrcbin0/GstParseBin:aparsebin: no suitable plugins found: Missing parser: MPEG-4 AAC (audio/mpeg, mpegversion=(int)4, stream-format=(string)raw, codec_data=(buffer)149056e500)

测试那个自行车的MP4视频，是可以的

**Comment by intjun** [comment]
> 试过视频文件了吗？视频文件是否有问题？
视频文件跟rtsp流是没有问题的，就是rtmp有问题，烦请大佬解答一下这个问题，谢谢！

**Comment by lzh1998-jansen** [comment]
> sp流是没有问题的，就是rtmp有问题，烦请大佬

我的rtsp有问题，你知道咋配置，能输出rtsp流吗，

**Comment by intjun** [comment]
> > sp流是没有问题的，就是rtmp有问题，烦请大佬
> 
> 我的rtsp有问题，你知道咋配置，能输出rtsp流吗，

就是改一下uri，uri:rtsp://192.168.110.95:8554/，我的rtsp流是VLC放出来的。

**Comment by lzh1998-jansen** [comment]
> > > sp流是没有问题的，就是rtmp有问题，烦请大佬
> > 
> > 
> > 我的rtsp有问题，你知道咋配置，能输出rtsp流吗，
> 
> 就是改一下uri，uri:rtsp://192.168.110.95:8554/，我的rtsp流是VLC放出来的。

我也是这么设置的，我设置的rtsp流，用vlc 也可以看

**Comment by wang-xinyu** [comment]
@intjun 把nvurisrcbin那个Node换成下这个试试
```
uridecodebin3:
uri: rtmp://localhost:55555/live/0.mp4
```

**Comment by wang-xinyu** [comment]
@lzh1998-jansen 你的RTSP流里面看似包含了AAC的音频流，而又缺少了相应的plugin，所以可以换一个不带音频的RTSP流试试

**Comment by intjun** [comment]
> @intjun 把nvurisrcbin那个Node换成下这个试试
> 
> ```
> uridecodebin3:
> uri: rtmp://localhost:55555/live/0.mp4
> ```
还是停在那里，没解码成功，我用vlc播放这个rtmp流是可以播放的。
![1672197199(1)](https://user-images.githubusercontent.com/23567603/209751553-fe3ac841-443c-4888-85ea-3aae4ab0d030.png)

**Comment by wang-xinyu** [comment]
@intjun VLC的兼容性比较强，不确定这个流能否被GStreamer播放，

要不参考这个教程，用ffmpeg推一个rtmp流试试，https://docs.nvidia.com/metropolis/deepstream/dev-guide/text/DS_AVSync.html

**Comment by intjun** [comment]
> @intjun VLC的兼容性比较强，不确定这个流能否被GStreamer播放，
> 
> 要不参考这个教程，用ffmpeg推一个rtmp流试试，https://docs.nvidia.com/metropolis/deepstream/dev-guide/text/DS_AVSync.html
ffmpeg -re -i sample.mp4 -vcodec copy  -c:a aac -b:a 160k -ar 48000 -strict -2 -f flv rtmp://localhost:55555/live/0.mp4
命令进行推流，解码也是停在那里，解码不成功。大佬帮忙看看哈

**Comment by jiangjiajun** [comment]
此ISSUE由于一年未更新，将会关闭处理，如有需要，可再次更新打开。
