### ISSUE TITLE
自定义配置 FastDeploy Streamer 的yaml配置文件指南

### ISSUE THREAD

**Issue by lzh1998-jansen** [PaddlePaddle/FastDeploy#994]
感谢作者的付出，我根据超链接跳到gstreamer的文档，https://gstreamer.freedesktop.org/documentation/tools/gst-launch.html?gi-language=c#pipeline-examples，我本想像deepstream一样，配置输入输出rtsp流，显示出来，看看效果，但是那个gstreamer的文档，我没有看懂，怎么去配置 yaml文件，求讲解或者，多提供几个 yaml文件的demo

**Comment by wang-xinyu** [comment]
@lzh1998-jansen 可以参考PPYOLOE那个example，
输入RTSP，改nvurisrcbin的uri即可，
输出RTSP，把nvvideoencfilesinkbin替换为nvrtspoutsinkbin。

关于nvrtspoutsinkbin的属性配置，可以用命令查看：gst-inspect-1.0 nvrtspoutsinkbin

更多的Demo，我们正在规划中~

**Comment by lzh1998-jansen** [comment]
>

> @lzh1998-jansen 可以参考PPYOLOE那个example， 输入RTSP，改nvurisrcbin的uri即可， 输出RTSP，把nvvideoencfilesinkbin替换为nvrtspoutsinkbin。
> 
> 关于nvrtspoutsinkbin的属性配置，可以用命令查看：gst-inspect-1.0 nvrtspoutsinkbin
> 
> 更多的Demo，我们正在规划中~

感谢大佬，我也正在学着怎么用 gst-inspect-1.0 这些工具

**Comment by wang-xinyu** [comment]
@lzh1998-jansen 也欢迎你跑通之后提交PR来丰富demo，比如支持RTSP输入输出的yaml文件

**Comment by lzh1998-jansen** [comment]
> @lzh1998-jansen 也欢迎你跑通之后提交PR来丰富demo，比如支持RTSP输入输出的yaml文件

好的

**Comment by lzh1998-jansen** [comment]
![image](https://user-images.githubusercontent.com/61367424/209762654-5a929294-961b-4c2a-b570-ff3387411bf1.png)
修改之后，还是有问题，
如下
![image](https://user-images.githubusercontent.com/61367424/209762743-5db3acf7-8409-407d-9b60-0d2bb7fbbf88.png)

**Comment by wang-xinyu** [comment]
@lzh1998-jansen 这里把enable-perf-measurement设置为false试试

**Comment by lzh1998-jansen** [comment]
![image](https://user-images.githubusercontent.com/61367424/209771070-c16f816b-c3cc-4ded-9e21-7677d4e7fd13.png)
又是缺插件，我换了一个rtsp流了

**Comment by wang-xinyu** [comment]
安装这个试试
sudo apt install gstreamer1.0-libav

**Comment by lzh1998-jansen** [comment]
![image](https://user-images.githubusercontent.com/61367424/209777981-067a0180-df27-45a8-a0fd-3bf7560d3266.png)
没有解决

**Comment by jiangjiajun** [comment]
此ISSUE由于一年未更新，将会关闭处理，如有需要，可再次更新打开。
