### ISSUE TITLE
fastdeploy-gpu-python模块报错嘞

### ISSUE THREAD

**Issue by lilianjie111111** [PaddlePaddle/FastDeploy#995]
![image](https://user-images.githubusercontent.com/102579571/209754064-a095c819-581e-49a2-9455-d7fa6fcead2b.png)
安装gpu版本并且使用gpu，trt进行推理时报错

**Comment by DefTruth** [comment]
@lilianjie111111 请问具体的运行环境、操作系统版本、是否安装cudnn、cudnn版本、fastdeploy版本这些情况是怎样的呢？

**Comment by lilianjie111111** [comment]
> 

win11;
cuda11.7;
cudnn8.5;
fastdeploy-gpu-python1.0.1

**Comment by lilianjie111111** [comment]
> @lilianjie111111 请问具体的运行环境、操作系统版本、是否安装cudnn、cudnn版本、fastdeploy版本这些情况是怎样的呢？

win11;
cuda11.7;
cudnn8.5;
fastdeploy-gpu-python1.0.1

**Comment by DefTruth** [comment]
对于cuda11.7和cudnn8.5的测试我们暂时还没有覆盖到，您可以先尝试cuda11.2+cudnn8.2或cuda11.5+cudnn8.3(在win11下)，另外就是cudnn需要安装到cuda的bin目录下。可以参考：https://blog.csdn.net/Angeldream123/article/details/123526012

**Comment by lilianjie111111** [comment]
> 对于cuda11.7和cudnn8.5的测试我们暂时还没有覆盖到，您可以先尝试cuda11.2+cudnn8.2或cuda11.5+cudnn8.3(在win11下)，另外就是cudnn需要安装到cuda的bin目录下。可以参考：https://blog.csdn.net/Angeldream123/article/details/123526012

好嘞，我这边试试，谢谢您

**Comment by jiangjiajun** [comment]
此ISSUE由于一年未更新，将会关闭处理，如有需要，可再次更新打开。
