### ISSUE TITLE
could not reshape a memory descriptor

### ISSUE THREAD

**Issue by Tian14267** [PaddlePaddle/FastDeploy#997]
大神们好。我在使用fastdeploy运行ASR的流式识别时，遇到了这个问题：
```
Traceback (most recent call last):
  File "infer_wav_1.py", line 97, in <module>
    real_time_predict_8k()
  File "infer_wav_1.py", line 82, in real_time_predict_8k
    result = predictor.predict_stream_fastdeploy(audio_data=data, use_pun=args.use_pun, is_itn=args.is_itn, is_end=d == b'', sample_rate_in=8000)
  File "/sdb/fffan/2_relevant_experiment/PPASR_u2_deploy_1227_new_server_static_fastdeploy/ppasr/predict_fastdeploy.py", line 424, in predict_stream_fastdeploy
    output_chunk_probs = self.predictor.predict_chunk_conformer_fastdeploy(x_chunk=one_x_chunk,
  File "/sdb/fffan/2_relevant_experiment/PPASR_u2_deploy_1227_new_server_static_fastdeploy/ppasr/infer_utils/inference_fastdeploy.py", line 100, in predict_chunk_conformer_fastdeploy
    output_data = self.runtime.infer({
  File "/root/anaconda3/envs/paddle_py38/lib/python3.8/site-packages/fastdeploy/runtime.py", line 65, in infer
    return self._runtime.infer(data)
RuntimeError: could not reshape a memory descriptor
```
这个是在预测第二个人chunk的时候出现的。请问下这个是啥情况？

**Comment by Tian14267** [comment]
大神，我添加了`option.set_paddle_mkldnn(False)`之后，出现这个错误：
![1](https://user-images.githubusercontent.com/27938135/209899093-33426404-8277-4b6a-b4b3-7d568559348c.png)

原始paddle inference 代码：https://github.com/yeyupiaoling/PPASR/blob/develop/ppasr/infer_utils/inference_predictor.py
我针对这个代码进行修改，修改之后是这样的：
[inference_fastdeploy.zip](https://github.com/PaddlePaddle/FastDeploy/files/10317431/inference_fastdeploy.zip)

所有的模型都是基于这个代码：https://github.com/yeyupiaoling/PPASR

**Comment by jiangjiajun** [comment]
@Tian14267 麻烦提供下运行命令，以及相应的模型

提供包括
- 通过Paddle Inference即上面的Predictor正确跑起来的方式或命令
- 通过FD运行出错的方式或命令

**Comment by Tian14267** [comment]
> @Tian14267 麻烦提供下运行命令，以及相应的模型
> 
> 提供包括
> 
> * 通过Paddle Inference即上面的Predictor正确跑起来的方式或命令
> * 通过FD运行出错的方式或命令

链接：https://pan.baidu.com/s/1MOnA6mMHOAPlhgvw_ca9KQ?pwd=nh5m 
提取码：nh5m
paddle inference运行代码：infer_wav_0.py
fastdeploy运行代码：infer_wav_1.py
环境需要大神自己搭建一下了，我的环境requirement太乱了~~~

**Comment by Tian14267** [comment]
@joey12300 @jiangjiajun 大神好。请问这个问题大神们是否跟进？这个问题咋解决呀。辛苦大神了

**Comment by joey12300** [comment]
@Tian14267 你好，你的paddle inference的版本是多少呢

**Comment by Tian14267** [comment]
> @Tian14267 你好，你的paddle inference的版本是多少呢

![image](https://user-images.githubusercontent.com/27938135/210311279-9f4632be-5d7d-4dc0-8ba0-241b5c930ef6.png)
@joey12300

**Comment by Tian14267** [comment]
@joey12300 @jiangjiajun 大神好。请问这个问题由继续跟进吗？请问下有相关解决办法不~~~（密切关注中）

**Comment by joey12300** [comment]
![image](https://user-images.githubusercontent.com/10826371/210489227-f449dca0-1054-4ad7-94b2-693622c6119f.png)
@Tian14267 你好，我看了一下计算图，貌似这个输入名设置有问题，我调整过后就可以正常运行了，你参考这个修改再试试？

**Comment by Tian14267** [comment]
> 

好的我试一下。谢谢大神！

**Comment by jiangjiajun** [comment]
此ISSUE由于一年未更新，将会关闭处理，如有需要，可再次更新打开。
