### ISSUE TITLE
Feature - Any plans on supporting RK3399 / RK3399Pro architectures ?

### ISSUE THREAD

**Issue by UygarUsta99** [PaddlePaddle/FastDeploy#998]
We have been working with rk3399 for some time now but model exporting/conversion is quite messy and undocumented.We would like to use fastdeploy for our applications.Are there any plans or a  roadmap for supporting RK3399 / RK3399Pro architectures ? Thanks for the great work.

**Comment by Zheng-Bicheng** [comment]
As far as I know, RK3399 does not have its own NPU. Please confirm whether your chip model is RK3399.

**Comment by Zheng-Bicheng** [comment]
If you use RK3399/RK3399Pro, you can first try to use ONNX as the backend to infer the model. After improving the model deployment experience of RK3588, FastDeploy will add support for 3399Pro.

**Comment by UygarUsta99** [comment]
> As far as I know, RK3399 does not have its own NPU. Please confirm whether your chip model is RK3399.

RK3399Pro has NPU,just for clarification.We  will try with onnx backend.Thank you for your work and quick feedback.
